<div class="option" data='{"value":"Alsofeketevolgy","state":"Bihor"}'>Alsofeketevolgy</div>
<div class="option" data='{"value":"Alsofuves","state":"Bihor"}'>Alsofuves</div>
<div class="option" data='{"value":"Alsokimpany","state":"Bihor"}'>Alsokimpany</div>
<div class="option" data='{"value":"Alsopoeny","state":"Bihor"}'>Alsopoeny</div>
<div class="option" data='{"value":"Alsopojeny","state":"Bihor"}'>Alsopojeny</div>
<div class="option" data='{"value":"Alsovalenyagra","state":"Bihor"}'>Alsovalenyagra</div>
<div class="option" data='{"value":"Alsoverzar","state":"Bihor"}'>Alsoverzar</div>
<div class="option" data='{"value":"Aszoirtas","state":"Bihor"}'>Aszoirtas</div>
<div class="option" data='{"value":"Baita","state":"Bihor"}'>Baita</div>
<div class="option" data='{"value":"Balaleni","state":"Bihor"}'>Balaleni</div>
<div class="option" data='{"value":"Balaleny","state":"Bihor"}'>Balaleny</div>
<div class="option" data='{"value":"Baleni","state":"Bihor"}'>Baleni</div>
<div class="option" data='{"value":"Beius","state":"Bihor"}'>Beius</div>
<div class="option" data='{"value":"Bekafalva","state":"Bihor"}'>Bekafalva</div>
<div class="option" data='{"value":"Belegeni","state":"Bihor"}'>Belegeni</div>
<div class="option" data='{"value":"Belejeni","state":"Bihor"}'>Belejeni</div>
<div class="option" data='{"value":"Belenyes","state":"Bihor"}'>Belenyes</div>
<div class="option" data='{"value":"Belenyesirtas","state":"Bihor"}'>Belenyesirtas</div>
<div class="option" data='{"value":"Beleseny","state":"Bihor"}'>Beleseny</div>
<div class="option" data='{"value":"Belezseny","state":"Bihor"}'>Belezseny</div>
<div class="option" data='{"value":"Belhagymas","state":"Bihor"}'>Belhagymas</div>
<div class="option" data='{"value":"Belkismaros","state":"Bihor"}'>Belkismaros</div>
<div class="option" data='{"value":"Berheny","state":"Bihor"}'>Berheny</div>
<div class="option" data='{"value":"Biharfenyves","state":"Bihor"}'>Biharfenyves</div>
<div class="option" data='{"value":"Biharmagura","state":"Bihor"}'>Biharmagura</div>
<div class="option" data='{"value":"Biharmezo","state":"Bihor"}'>Biharmezo</div>
<div class="option" data='{"value":"Bihor","state":"Bihor"}'>Bihor</div>
<div class="option" data='{"value":"Bojana","state":"Bihor"}'>Bojana</div>
<div class="option" data='{"value":"Bontesd","state":"Bihor"}'>Bontesd</div>
<div class="option" data='{"value":"Borz","state":"Bihor"}'>Borz</div>
<div class="option" data='{"value":"Bradet","state":"Bihor"}'>Bradet</div>
<div class="option" data='{"value":"Bragyet","state":"Bihor"}'>Bragyet</div>
<div class="option" data='{"value":"Briheni","state":"Bihor"}'>Briheni</div>
<div class="option" data='{"value":"Briheny","state":"Bihor"}'>Briheny</div>
<div class="option" data='{"value":"Broaste","state":"Bihor"}'>Broaste</div>
<div class="option" data='{"value":"Brost","state":"Bihor"}'>Brost</div>
<div class="option" data='{"value":"Brusturi","state":"Bihor"}'>Brusturi</div>
<div class="option" data='{"value":"Brusztur","state":"Bihor"}'>Brusztur</div>
<div class="option" data='{"value":"Buntesti","state":"Bihor"}'>Buntesti</div>
<div class="option" data='{"value":"Buntyesd","state":"Bihor"}'>Buntyesd</div>
<div class="option" data='{"value":"Calugar","state":"Bihor"}'>Calugar</div>
<div class="option" data='{"value":"Calugari","state":"Bihor"}'>Calugari</div>
<div class="option" data='{"value":"Calugurita","state":"Bihor"}'>Calugurita</div>
<div class="option" data='{"value":"Camp","state":"Bihor"}'>Camp</div>
<div class="option" data='{"value":"Campani","state":"Bihor"}'>Campani</div>
<div class="option" data='{"value":"Carpinet","state":"Bihor"}'>Carpinet</div>
<div class="option" data='{"value":"Ciganyosd","state":"Bihor"}'>Ciganyosd</div>
<div class="option" data='{"value":"Cimp","state":"Bihor"}'>Cimp</div>
<div class="option" data='{"value":"Cimpanii de Jos","state":"Bihor"}'>Cimpanii de Jos</div>
<div class="option" data='{"value":"Cimpanii de Sus","state":"Bihor"}'>Cimpanii de Sus</div>
<div class="option" data='{"value":"Ciuntahaza","state":"Bihor"}'>Ciuntahaza</div>
<div class="option" data='{"value":"Ciuntesti","state":"Bihor"}'>Ciuntesti</div>
<div class="option" data='{"value":"Cociuba de Sus","state":"Bihor"}'>Cociuba de Sus</div>
<div class="option" data='{"value":"Cociuba Mica","state":"Bihor"}'>Cociuba Mica</div>
<div class="option" data='{"value":"Codru","state":"Bihor"}'>Codru</div>
<div class="option" data='{"value":"Colesti","state":"Bihor"}'>Colesti</div>
<div class="option" data='{"value":"Cristior de Sus","state":"Bihor"}'>Cristior de Sus</div>
<div class="option" data='{"value":"Cristioru de Sus","state":"Bihor"}'>Cristioru de Sus</div>
<div class="option" data='{"value":"Csontahaz","state":"Bihor"}'>Csontahaz</div>
<div class="option" data='{"value":"Csontahaza","state":"Bihor"}'>Csontahaza</div>
<div class="option" data='{"value":"Cucuceni","state":"Bihor"}'>Cucuceni</div>
<div class="option" data='{"value":"Cucueni","state":"Bihor"}'>Cucueni</div>
<div class="option" data='{"value":"Cusuis","state":"Bihor"}'>Cusuis</div>
<div class="option" data='{"value":"Cusuius","state":"Bihor"}'>Cusuius</div>
<div class="option" data='{"value":"Cziganyesd","state":"Bihor"}'>Cziganyesd</div>
<div class="option" data='{"value":"Cziganyosd","state":"Bihor"}'>Cziganyosd</div>
<div class="option" data='{"value":"Dombrovany","state":"Bihor"}'>Dombrovany</div>
<div class="option" data='{"value":"Dombrovicza","state":"Bihor"}'>Dombrovicza</div>
<div class="option" data='{"value":"Draganesti","state":"Bihor"}'>Draganesti</div>
<div class="option" data='{"value":"Draganfalva","state":"Bihor"}'>Draganfalva</div>
<div class="option" data='{"value":"Dragonyesd","state":"Bihor"}'>Dragonyesd</div>
<div class="option" data='{"value":"Dragonyest","state":"Bihor"}'>Dragonyest</div>
<div class="option" data='{"value":"Dumbravani","state":"Bihor"}'>Dumbravani</div>
<div class="option" data='{"value":"Dumbraveni","state":"Bihor"}'>Dumbraveni</div>
<div class="option" data='{"value":"Dumbravicza","state":"Bihor"}'>Dumbravicza</div>
<div class="option" data='{"value":"Dumbravita de Codru","state":"Bihor"}'>Dumbravita de Codru</div>
<div class="option" data='{"value":"Fanata","state":"Bihor"}'>Fanata</div>
<div class="option" data='{"value":"Fanate","state":"Bihor"}'>Fanate</div>
<div class="option" data='{"value":"Feketefalva","state":"Bihor"}'>Feketefalva</div>
<div class="option" data='{"value":"Felsofuves","state":"Bihor"}'>Felsofuves</div>
<div class="option" data='{"value":"Felsokimpany","state":"Bihor"}'>Felsokimpany</div>
<div class="option" data='{"value":"Felsokocsoba","state":"Bihor"}'>Felsokocsoba</div>
<div class="option" data='{"value":"Felsokristyor","state":"Bihor"}'>Felsokristyor</div>
<div class="option" data='{"value":"Felsomezos","state":"Bihor"}'>Felsomezos</div>
<div class="option" data='{"value":"Felsopoeny","state":"Bihor"}'>Felsopoeny</div>
<div class="option" data='{"value":"Felsopojeny","state":"Bihor"}'>Felsopojeny</div>
<div class="option" data='{"value":"Felsoverzar","state":"Bihor"}'>Felsoverzar</div>
<div class="option" data='{"value":"Fenes","state":"Bihor"}'>Fenes</div>
<div class="option" data='{"value":"Fenis","state":"Bihor"}'>Fenis</div>
<div class="option" data='{"value":"Ferice","state":"Bihor"}'>Ferice</div>
<div class="option" data='{"value":"Fericse","state":"Bihor"}'>Fericse</div>
<div class="option" data='{"value":"Finate","state":"Bihor"}'>Finate</div>
<div class="option" data='{"value":"Finis","state":"Bihor"}'>Finis</div>
<div class="option" data='{"value":"Fizis","state":"Bihor"}'>Fizis</div>
<div class="option" data='{"value":"Fonacza","state":"Bihor"}'>Fonacza</div>
<div class="option" data='{"value":"Fonohaza","state":"Bihor"}'>Fonohaza</div>
<div class="option" data='{"value":"Fonokismezo","state":"Bihor"}'>Fonokismezo</div>
<div class="option" data='{"value":"Fonokismezos","state":"Bihor"}'>Fonokismezos</div>
<div class="option" data='{"value":"Funacza","state":"Bihor"}'>Funacza</div>
<div class="option" data='{"value":"Fuzegy","state":"Bihor"}'>Fuzegy</div>
<div class="option" data='{"value":"Ghighiseni","state":"Bihor"}'>Ghighiseni</div>
<div class="option" data='{"value":"Giulesti","state":"Bihor"}'>Giulesti</div>
<div class="option" data='{"value":"Gradinari","state":"Bihor"}'>Gradinari</div>
<div class="option" data='{"value":"Gros","state":"Bihor"}'>Gros</div>
<div class="option" data='{"value":"Grosi","state":"Bihor"}'>Grosi</div>
<div class="option" data='{"value":"Gross","state":"Bihor"}'>Gross</div>
<div class="option" data='{"value":"Grosswardein","state":"Bihor"}'>Grosswardein</div>
<div class="option" data='{"value":"Grosz","state":"Bihor"}'>Grosz</div>
<div class="option" data='{"value":"Gurani","state":"Bihor"}'>Gurani</div>
<div class="option" data='{"value":"Gurany","state":"Bihor"}'>Gurany</div>
<div class="option" data='{"value":"Gyegyeseny","state":"Bihor"}'>Gyegyeseny</div>
<div class="option" data='{"value":"Hagymas","state":"Bihor"}'>Hagymas</div>
<div class="option" data='{"value":"Halmagygoros","state":"Bihor"}'>Halmagygoros</div>
<div class="option" data='{"value":"Hasmas","state":"Bihor"}'>Hasmas</div>
<div class="option" data='{"value":"Hatzmas","state":"Bihor"}'>Hatzmas</div>
<div class="option" data='{"value":"Havasdombro","state":"Bihor"}'>Havasdombro</div>
<div class="option" data='{"value":"Havaspoklos","state":"Bihor"}'>Havaspoklos</div>
<div class="option" data='{"value":"Hentisor","state":"Bihor"}'>Hentisor</div>
<div class="option" data='{"value":"Hesmas","state":"Bihor"}'>Hesmas</div>
<div class="option" data='{"value":"Hodisel","state":"Bihor"}'>Hodisel</div>
<div class="option" data='{"value":"Hodosel","state":"Bihor"}'>Hodosel</div>
<div class="option" data='{"value":"Honcer","state":"Bihor"}'>Honcer</div>
<div class="option" data='{"value":"Honczer","state":"Bihor"}'>Honczer</div>
<div class="option" data='{"value":"Honczisor","state":"Bihor"}'>Honczisor</div>
<div class="option" data='{"value":"Hontisor","state":"Bihor"}'>Hontisor</div>
<div class="option" data='{"value":"Huffladen","state":"Bihor"}'>Huffladen</div>
<div class="option" data='{"value":"Izbuc","state":"Bihor"}'>Izbuc</div>
<div class="option" data='{"value":"Judetul Bihor","state":"Bihor"}'>Judetul Bihor</div>
<div class="option" data='{"value":"Julesti","state":"Bihor"}'>Julesti</div>
<div class="option" data='{"value":"Kakacseny","state":"Bihor"}'>Kakacseny</div>
<div class="option" data='{"value":"Kakucsany","state":"Bihor"}'>Kakucsany</div>
<div class="option" data='{"value":"Kaluger","state":"Bihor"}'>Kaluger</div>
<div class="option" data='{"value":"Kalugyer","state":"Bihor"}'>Kalugyer</div>
<div class="option" data='{"value":"Kerpenyed","state":"Bihor"}'>Kerpenyed</div>
<div class="option" data='{"value":"Kerpenyet","state":"Bihor"}'>Kerpenyet</div>
<div class="option" data='{"value":"Kimp","state":"Bihor"}'>Kimp</div>
<div class="option" data='{"value":"Kimpany","state":"Bihor"}'>Kimpany</div>
<div class="option" data='{"value":"Kisbekafalva","state":"Bihor"}'>Kisbekafalva</div>
<div class="option" data='{"value":"Kiskoh","state":"Bihor"}'>Kiskoh</div>
<div class="option" data='{"value":"Kisnyegerfalva","state":"Bihor"}'>Kisnyegerfalva</div>
<div class="option" data='{"value":"Kisszedres","state":"Bihor"}'>Kisszedres</div>
<div class="option" data='{"value":"Kocsuba","state":"Bihor"}'>Kocsuba</div>
<div class="option" data='{"value":"Kofalva","state":"Bihor"}'>Kofalva</div>
<div class="option" data='{"value":"Kolafalva","state":"Bihor"}'>Kolafalva</div>
<div class="option" data='{"value":"Kollest","state":"Bihor"}'>Kollest</div>
<div class="option" data='{"value":"Korosbarafalva","state":"Bihor"}'>Korosbarafalva</div>
<div class="option" data='{"value":"Korossebes","state":"Bihor"}'>Korossebes</div>
<div class="option" data='{"value":"Korostarkany","state":"Bihor"}'>Korostarkany</div>
<div class="option" data='{"value":"Koszvenyes","state":"Bihor"}'>Koszvenyes</div>
<div class="option" data='{"value":"Lazuri","state":"Bihor"}'>Lazuri</div>
<div class="option" data='{"value":"Lazuri de Beius","state":"Bihor"}'>Lazuri de Beius</div>
<div class="option" data='{"value":"Leheceni","state":"Bihor"}'>Leheceni</div>
<div class="option" data='{"value":"Lehecseny","state":"Bihor"}'>Lehecseny</div>
<div class="option" data='{"value":"Lelesd","state":"Bihor"}'>Lelesd</div>
<div class="option" data='{"value":"Lelesti","state":"Bihor"}'>Lelesti</div>
<div class="option" data='{"value":"Livada Beiusului","state":"Bihor"}'>Livada Beiusului</div>
<div class="option" data='{"value":"Magura","state":"Bihor"}'>Magura</div>
<div class="option" data='{"value":"Merag","state":"Bihor"}'>Merag</div>
<div class="option" data='{"value":"Mezes","state":"Bihor"}'>Mezes</div>
<div class="option" data='{"value":"Mierag","state":"Bihor"}'>Mierag</div>
<div class="option" data='{"value":"Mizies","state":"Bihor"}'>Mizies</div>
<div class="option" data='{"value":"Mocesti","state":"Bihor"}'>Mocesti</div>
<div class="option" data='{"value":"Motesti","state":"Bihor"}'>Motesti</div>
<div class="option" data='{"value":"Negru","state":"Bihor"}'>Negru</div>
<div class="option" data='{"value":"Nyegerfalva","state":"Bihor"}'>Nyegerfalva</div>
<div class="option" data='{"value":"Nyegru","state":"Bihor"}'>Nyegru</div>
<div class="option" data='{"value":"Oradea","state":"Bihor"}'>Oradea</div>
<div class="option" data='{"value":"Pafranyos","state":"Bihor"}'>Pafranyos</div>
<div class="option" data='{"value":"Paganest","state":"Bihor"}'>Paganest</div>
<div class="option" data='{"value":"Pantasesd","state":"Bihor"}'>Pantasesd</div>
<div class="option" data='{"value":"Pantasesti","state":"Bihor"}'>Pantasesti</div>
<div class="option" data='{"value":"Petreleny","state":"Bihor"}'>Petreleny</div>
<div class="option" data='{"value":"Petrileni","state":"Bihor"}'>Petrileni</div>
<div class="option" data='{"value":"Petrileny","state":"Bihor"}'>Petrileny</div>
<div class="option" data='{"value":"Petroasa","state":"Bihor"}'>Petroasa</div>
<div class="option" data='{"value":"Petrosz","state":"Bihor"}'>Petrosz</div>
<div class="option" data='{"value":"Petrosza","state":"Bihor"}'>Petrosza</div>
<div class="option" data='{"value":"Pietroasa","state":"Bihor"}'>Pietroasa</div>
<div class="option" data='{"value":"Poclusa de Beius","state":"Bihor"}'>Poclusa de Beius</div>
<div class="option" data='{"value":"Poclusa de Beliu","state":"Bihor"}'>Poclusa de Beliu</div>
<div class="option" data='{"value":"Poiana","state":"Bihor"}'>Poiana</div>
<div class="option" data='{"value":"Poienii de Jos","state":"Bihor"}'>Poienii de Jos</div>
<div class="option" data='{"value":"Poienii de Sus","state":"Bihor"}'>Poienii de Sus</div>
<div class="option" data='{"value":"Pojana","state":"Bihor"}'>Pojana</div>
<div class="option" data='{"value":"Poklusa","state":"Bihor"}'>Poklusa</div>
<div class="option" data='{"value":"Ponoarele","state":"Bihor"}'>Ponoarele</div>
<div class="option" data='{"value":"Pusztahodisel","state":"Bihor"}'>Pusztahodisel</div>
<div class="option" data='{"value":"Pusztahodos","state":"Bihor"}'>Pusztahodos</div>
<div class="option" data='{"value":"Reny","state":"Bihor"}'>Reny</div>
<div class="option" data='{"value":"Rezbanya","state":"Bihor"}'>Rezbanya</div>
<div class="option" data='{"value":"Rezbanyafalu","state":"Bihor"}'>Rezbanyafalu</div>
<div class="option" data='{"value":"Rezbanyavaros","state":"Bihor"}'>Rezbanyavaros</div>
<div class="option" data='{"value":"Rieni","state":"Bihor"}'>Rieni</div>
<div class="option" data='{"value":"Rieny","state":"Bihor"}'>Rieny</div>
<div class="option" data='{"value":"Rituri","state":"Bihor"}'>Rituri</div>
<div class="option" data='{"value":"Saca","state":"Bihor"}'>Saca</div>
<div class="option" data='{"value":"Saliste","state":"Bihor"}'>Saliste</div>
<div class="option" data='{"value":"Saliste de Vascau","state":"Bihor"}'>Saliste de Vascau</div>
<div class="option" data='{"value":"Sarbesti","state":"Bihor"}'>Sarbesti</div>
<div class="option" data='{"value":"Saud","state":"Bihor"}'>Saud</div>
<div class="option" data='{"value":"Sebes","state":"Bihor"}'>Sebes</div>
<div class="option" data='{"value":"Sebis","state":"Bihor"}'>Sebis</div>
<div class="option" data='{"value":"Sirbesti","state":"Bihor"}'>Sirbesti</div>
<div class="option" data='{"value":"Sohodol","state":"Bihor"}'>Sohodol</div>
<div class="option" data='{"value":"Stancesti","state":"Bihor"}'>Stancesti</div>
<div class="option" data='{"value":"Stincesti","state":"Bihor"}'>Stincesti</div>
<div class="option" data='{"value":"Stoinesti","state":"Bihor"}'>Stoinesti</div>
<div class="option" data='{"value":"Sudrigi","state":"Bihor"}'>Sudrigi</div>
<div class="option" data='{"value":"Sudrigiu","state":"Bihor"}'>Sudrigiu</div>
<div class="option" data='{"value":"Sudrigiul","state":"Bihor"}'>Sudrigiul</div>
<div class="option" data='{"value":"Susam","state":"Bihor"}'>Susam</div>
<div class="option" data='{"value":"Susani","state":"Bihor"}'>Susani</div>
<div class="option" data='{"value":"Susany","state":"Bihor"}'>Susany</div>
<div class="option" data='{"value":"Susanyfalva","state":"Bihor"}'>Susanyfalva</div>
<div class="option" data='{"value":"Susd","state":"Bihor"}'>Susd</div>
<div class="option" data='{"value":"Sussan","state":"Bihor"}'>Sussan</div>
<div class="option" data='{"value":"Sust","state":"Bihor"}'>Sust</div>
<div class="option" data='{"value":"Sustiu","state":"Bihor"}'>Sustiu</div>
<div class="option" data='{"value":"Szaka","state":"Bihor"}'>Szaka</div>
<div class="option" data='{"value":"Szelistye","state":"Bihor"}'>Szelistye</div>
<div class="option" data='{"value":"Szod","state":"Bihor"}'>Szod</div>
<div class="option" data='{"value":"Szohodol","state":"Bihor"}'>Szohodol</div>
<div class="option" data='{"value":"Szood","state":"Bihor"}'>Szood</div>
<div class="option" data='{"value":"Sztohanyesti","state":"Bihor"}'>Sztohanyesti</div>
<div class="option" data='{"value":"Szudrics","state":"Bihor"}'>Szudrics</div>
<div class="option" data='{"value":"Szuszany","state":"Bihor"}'>Szuszany</div>
<div class="option" data='{"value":"Tarcaia","state":"Bihor"}'>Tarcaia</div>
<div class="option" data='{"value":"Tarcaita","state":"Bihor"}'>Tarcaita</div>
<div class="option" data='{"value":"Tarkaicza","state":"Bihor"}'>Tarkaicza</div>
<div class="option" data='{"value":"Tarkajcza","state":"Bihor"}'>Tarkajcza</div>
<div class="option" data='{"value":"Tarkany","state":"Bihor"}'>Tarkany</div>
<div class="option" data='{"value":"Tarkanyka","state":"Bihor"}'>Tarkanyka</div>
<div class="option" data='{"value":"Tiganestii de Beius","state":"Bihor"}'>Tiganestii de Beius</div>
<div class="option" data='{"value":"Valea de Jos","state":"Bihor"}'>Valea de Jos</div>
<div class="option" data='{"value":"Valea Neagra de Jos","state":"Bihor"}'>Valea Neagra de Jos</div>
<div class="option" data='{"value":"Varasfenes","state":"Bihor"}'>Varasfenes</div>
<div class="option" data='{"value":"Varzarii de Jos","state":"Bihor"}'>Varzarii de Jos</div>
<div class="option" data='{"value":"Varzarii de Sus","state":"Bihor"}'>Varzarii de Sus</div>
<div class="option" data='{"value":"Vasaskofalva","state":"Bihor"}'>Vasaskofalva</div>
<div class="option" data='{"value":"Vascau","state":"Bihor"}'>Vascau</div>
<div class="option" data='{"value":"Vaskoh","state":"Bihor"}'>Vaskoh</div>
<div class="option" data='{"value":"Vaskohaszod","state":"Bihor"}'>Vaskohaszod</div>
<div class="option" data='{"value":"Vaskohmezo","state":"Bihor"}'>Vaskohmezo</div>
<div class="option" data='{"value":"Vaskohszeleste","state":"Bihor"}'>Vaskohszeleste</div>
<div class="option" data='{"value":"Vaskohszelistye","state":"Bihor"}'>Vaskohszelistye</div>
<div class="option" id="option_end" data='{"value":"Zsulest","state":"Bihor"}'>Zsulest</div>

