<div class="option" data='{"value":"Aciura","state":"Arad"}'>Aciura</div>
<div class="option" data='{"value":"Aciuta","state":"Arad"}'>Aciuta</div>
<div class="option" data='{"value":"Acsfalva","state":"Arad"}'>Acsfalva</div>
<div class="option" data='{"value":"Acsova","state":"Arad"}'>Acsova</div>
<div class="option" data='{"value":"Acsucza","state":"Arad"}'>Acsucza</div>
<div class="option" data='{"value":"Acsuva","state":"Arad"}'>Acsuva</div>
<div class="option" data='{"value":"Acsva","state":"Arad"}'>Acsva</div>
<div class="option" data='{"value":"Alcsil","state":"Arad"}'>Alcsil</div>
<div class="option" data='{"value":"Aldasos","state":"Arad"}'>Aldasos</div>
<div class="option" data='{"value":"Aldesti","state":"Arad"}'>Aldesti</div>
<div class="option" data='{"value":"Aldofalva","state":"Arad"}'>Aldofalva</div>
<div class="option" data='{"value":"Algya","state":"Arad"}'>Algya</div>
<div class="option" data='{"value":"Algyest","state":"Arad"}'>Algyest</div>
<div class="option" data='{"value":"Almas","state":"Arad"}'>Almas</div>
<div class="option" data='{"value":"Almasel","state":"Arad"}'>Almasel</div>
<div class="option" data='{"value":"Almenes","state":"Arad"}'>Almenes</div>
<div class="option" data='{"value":"Also Koroknya","state":"Arad"}'>Also Koroknya</div>
<div class="option" data='{"value":"Alsodombro","state":"Arad"}'>Alsodombro</div>
<div class="option" data='{"value":"Alsokoves","state":"Arad"}'>Alsokoves</div>
<div class="option" data='{"value":"Alsokristyor","state":"Arad"}'>Alsokristyor</div>
<div class="option" data='{"value":"Alsoszakacs","state":"Arad"}'>Alsoszakacs</div>
<div class="option" data='{"value":"Altarad","state":"Arad"}'>Altarad</div>
<div class="option" data='{"value":"Arad","state":"Arad"}'>Arad</div>
<div class="option" data='{"value":"Aradinum Vetus","state":"Arad"}'>Aradinum Vetus</div>
<div class="option" data='{"value":"Archis","state":"Arad"}'>Archis</div>
<div class="option" data='{"value":"Arkis","state":"Arad"}'>Arkis</div>
<div class="option" data='{"value":"Arkus","state":"Arad"}'>Arkus</div>
<div class="option" data='{"value":"Avram Iancu","state":"Arad"}'>Avram Iancu</div>
<div class="option" data='{"value":"Baia","state":"Arad"}'>Baia</div>
<div class="option" data='{"value":"Baja","state":"Arad"}'>Baja</div>
<div class="option" data='{"value":"Bajnokfalva","state":"Arad"}'>Bajnokfalva</div>
<div class="option" data='{"value":"Balcescu Nicolae","state":"Arad"}'>Balcescu Nicolae</div>
<div class="option" data='{"value":"Baltele","state":"Arad"}'>Baltele</div>
<div class="option" data='{"value":"Baltfalva","state":"Arad"}'>Baltfalva</div>
<div class="option" data='{"value":"Balthelye","state":"Arad"}'>Balthelye</div>
<div class="option" data='{"value":"Baltyele","state":"Arad"}'>Baltyele</div>
<div class="option" data='{"value":"Banesd","state":"Arad"}'>Banesd</div>
<div class="option" data='{"value":"Banesti","state":"Arad"}'>Banesti</div>
<div class="option" data='{"value":"Barsa","state":"Arad"}'>Barsa</div>
<div class="option" data='{"value":"Barza","state":"Arad"}'>Barza</div>
<div class="option" data='{"value":"Barzafalva","state":"Arad"}'>Barzafalva</div>
<div class="option" data='{"value":"Barzasti","state":"Arad"}'>Barzasti</div>
<div class="option" data='{"value":"Barzava","state":"Arad"}'>Barzava</div>
<div class="option" data='{"value":"Barzesd","state":"Arad"}'>Barzesd</div>
<div class="option" data='{"value":"Barzest","state":"Arad"}'>Barzest</div>
<div class="option" data='{"value":"Barzesti","state":"Arad"}'>Barzesti</div>
<div class="option" data='{"value":"Bata","state":"Arad"}'>Bata</div>
<div class="option" data='{"value":"Batta","state":"Arad"}'>Batta</div>
<div class="option" data='{"value":"Battucza","state":"Arad"}'>Battucza</div>
<div class="option" data='{"value":"Batucza","state":"Arad"}'>Batucza</div>
<div class="option" data='{"value":"Batuta","state":"Arad"}'>Batuta</div>
<div class="option" data='{"value":"Batyafalva","state":"Arad"}'>Batyafalva</div>
<div class="option" data='{"value":"Bazava","state":"Arad"}'>Bazava</div>
<div class="option" data='{"value":"Belarkos","state":"Arad"}'>Belarkos</div>
<div class="option" data='{"value":"Belmarkaszek","state":"Arad"}'>Belmarkaszek</div>
<div class="option" data='{"value":"Belnagymaros","state":"Arad"}'>Belnagymaros</div>
<div class="option" data='{"value":"Belorvenyes","state":"Arad"}'>Belorvenyes</div>
<div class="option" data='{"value":"Belrogoz","state":"Arad"}'>Belrogoz</div>
<div class="option" data='{"value":"Benesti","state":"Arad"}'>Benesti</div>
<div class="option" data='{"value":"Benyefalva","state":"Arad"}'>Benyefalva</div>
<div class="option" data='{"value":"Benyesd","state":"Arad"}'>Benyesd</div>
<div class="option" data='{"value":"Berendia","state":"Arad"}'>Berendia</div>
<div class="option" data='{"value":"Berindia","state":"Arad"}'>Berindia</div>
<div class="option" data='{"value":"Bersza","state":"Arad"}'>Bersza</div>
<div class="option" data='{"value":"Berza","state":"Arad"}'>Berza</div>
<div class="option" data='{"value":"Berzava","state":"Arad"}'>Berzava</div>
<div class="option" data='{"value":"Berzova","state":"Arad"}'>Berzova</div>
<div class="option" data='{"value":"Biharkristyor","state":"Arad"}'>Biharkristyor</div>
<div class="option" data='{"value":"Biharmagura","state":"Arad"}'>Biharmagura</div>
<div class="option" data='{"value":"Birsa","state":"Arad"}'>Birsa</div>
<div class="option" data='{"value":"Birzava","state":"Arad"}'>Birzava</div>
<div class="option" data='{"value":"Birzesti","state":"Arad"}'>Birzesti</div>
<div class="option" data='{"value":"Biszindia","state":"Arad"}'>Biszindia</div>
<div class="option" data='{"value":"Bochia","state":"Arad"}'>Bochia</div>
<div class="option" data='{"value":"Bodest","state":"Arad"}'>Bodest</div>
<div class="option" data='{"value":"Bodesti","state":"Arad"}'>Bodesti</div>
<div class="option" data='{"value":"Bogyesd","state":"Arad"}'>Bogyesd</div>
<div class="option" data='{"value":"Bogyest","state":"Arad"}'>Bogyest</div>
<div class="option" data='{"value":"Bogyesty","state":"Arad"}'>Bogyesty</div>
<div class="option" data='{"value":"Bogyfalva","state":"Arad"}'>Bogyfalva</div>
<div class="option" data='{"value":"Bohani","state":"Arad"}'>Bohani</div>
<div class="option" data='{"value":"Bohany","state":"Arad"}'>Bohany</div>
<div class="option" data='{"value":"Bokia","state":"Arad"}'>Bokia</div>
<div class="option" data='{"value":"Bokkia","state":"Arad"}'>Bokkia</div>
<div class="option" data='{"value":"Boklya","state":"Arad"}'>Boklya</div>
<div class="option" data='{"value":"Bokony","state":"Arad"}'>Bokony</div>
<div class="option" data='{"value":"Boncafalva","state":"Arad"}'>Boncafalva</div>
<div class="option" data='{"value":"Bonczafalva","state":"Arad"}'>Bonczafalva</div>
<div class="option" data='{"value":"Bonczesd","state":"Arad"}'>Bonczesd</div>
<div class="option" data='{"value":"Bonczesty","state":"Arad"}'>Bonczesty</div>
<div class="option" data='{"value":"Bontesti","state":"Arad"}'>Bontesti</div>
<div class="option" data='{"value":"Borosberend","state":"Arad"}'>Borosberend</div>
<div class="option" data='{"value":"Borosrozsa","state":"Arad"}'>Borosrozsa</div>
<div class="option" data='{"value":"Borossebes","state":"Arad"}'>Borossebes</div>
<div class="option" data='{"value":"Borosztok","state":"Arad"}'>Borosztok</div>
<div class="option" data='{"value":"Botfei","state":"Arad"}'>Botfei</div>
<div class="option" data='{"value":"Botfein","state":"Arad"}'>Botfein</div>
<div class="option" data='{"value":"Botfeiu","state":"Arad"}'>Botfeiu</div>
<div class="option" data='{"value":"Botfej","state":"Arad"}'>Botfej</div>
<div class="option" data='{"value":"Botfeju","state":"Arad"}'>Botfeju</div>
<div class="option" data='{"value":"Botteiul","state":"Arad"}'>Botteiul</div>
<div class="option" data='{"value":"Bozesti","state":"Arad"}'>Bozesti</div>
<div class="option" data='{"value":"Bozosd","state":"Arad"}'>Bozosd</div>
<div class="option" data='{"value":"Brazii","state":"Arad"}'>Brazii</div>
<div class="option" data='{"value":"Brusturesc","state":"Arad"}'>Brusturesc</div>
<div class="option" data='{"value":"Buceava","state":"Arad"}'>Buceava</div>
<div class="option" data='{"value":"Bucsava","state":"Arad"}'>Bucsava</div>
<div class="option" data='{"value":"Budest","state":"Arad"}'>Budest</div>
<div class="option" data='{"value":"Budesti","state":"Arad"}'>Budesti</div>
<div class="option" data='{"value":"Bugyfalva","state":"Arad"}'>Bugyfalva</div>
<div class="option" data='{"value":"Buhani","state":"Arad"}'>Buhani</div>
<div class="option" data='{"value":"Bulci","state":"Arad"}'>Bulci</div>
<div class="option" data='{"value":"Bulcs","state":"Arad"}'>Bulcs</div>
<div class="option" data='{"value":"Bultsch","state":"Arad"}'>Bultsch</div>
<div class="option" data='{"value":"Bursza","state":"Arad"}'>Bursza</div>
<div class="option" data='{"value":"Buteni","state":"Arad"}'>Buteni</div>
<div class="option" data='{"value":"Buttyen","state":"Arad"}'>Buttyen</div>
<div class="option" data='{"value":"Buttyin","state":"Arad"}'>Buttyin</div>
<div class="option" data='{"value":"Butyen","state":"Arad"}'>Butyen</div>
<div class="option" data='{"value":"Butyin","state":"Arad"}'>Butyin</div>
<div class="option" data='{"value":"Cacarau","state":"Arad"}'>Cacarau</div>
<div class="option" data='{"value":"Capruta","state":"Arad"}'>Capruta</div>
<div class="option" data='{"value":"Carand","state":"Arad"}'>Carand</div>
<div class="option" data='{"value":"Carandu","state":"Arad"}'>Carandu</div>
<div class="option" data='{"value":"Chiscau","state":"Arad"}'>Chiscau</div>
<div class="option" data='{"value":"Chisindia","state":"Arad"}'>Chisindia</div>
<div class="option" data='{"value":"Cil","state":"Arad"}'>Cil</div>
<div class="option" data='{"value":"Clit","state":"Arad"}'>Clit</div>
<div class="option" data='{"value":"Cliti","state":"Arad"}'>Cliti</div>
<div class="option" data='{"value":"Cociuba","state":"Arad"}'>Cociuba</div>
<div class="option" data='{"value":"Comanesti","state":"Arad"}'>Comanesti</div>
<div class="option" data='{"value":"Corbesti","state":"Arad"}'>Corbesti</div>
<div class="option" data='{"value":"Cristesti","state":"Arad"}'>Cristesti</div>
<div class="option" data='{"value":"Cristioru de Jos","state":"Arad"}'>Cristioru de Jos</div>
<div class="option" data='{"value":"Crocna","state":"Arad"}'>Crocna</div>
<div class="option" data='{"value":"Csermura","state":"Arad"}'>Csermura</div>
<div class="option" data='{"value":"Csil","state":"Arad"}'>Csil</div>
<div class="option" data='{"value":"Csohesd","state":"Arad"}'>Csohesd</div>
<div class="option" data='{"value":"Csohosd","state":"Arad"}'>Csohosd</div>
<div class="option" data='{"value":"Csucs","state":"Arad"}'>Csucs</div>
<div class="option" data='{"value":"Csucsmezo","state":"Arad"}'>Csucsmezo</div>
<div class="option" data='{"value":"Cuias","state":"Arad"}'>Cuias</div>
<div class="option" data='{"value":"Cuied","state":"Arad"}'>Cuied</div>
<div class="option" data='{"value":"Cumanesti","state":"Arad"}'>Cumanesti</div>
<div class="option" data='{"value":"Czermura","state":"Arad"}'>Czermura</div>
<div class="option" data='{"value":"Czohesd","state":"Arad"}'>Czohesd</div>
<div class="option" data='{"value":"Dancsfalva","state":"Arad"}'>Dancsfalva</div>
<div class="option" data='{"value":"Deakfalva","state":"Arad"}'>Deakfalva</div>
<div class="option" data='{"value":"Decs","state":"Arad"}'>Decs</div>
<div class="option" data='{"value":"Decse","state":"Arad"}'>Decse</div>
<div class="option" data='{"value":"Dezna","state":"Arad"}'>Dezna</div>
<div class="option" data='{"value":"Deznalaz","state":"Arad"}'>Deznalaz</div>
<div class="option" data='{"value":"Diakfalva","state":"Arad"}'>Diakfalva</div>
<div class="option" data='{"value":"Dieci","state":"Arad"}'>Dieci</div>
<div class="option" data='{"value":"Diecs","state":"Arad"}'>Diecs</div>
<div class="option" data='{"value":"Donceni","state":"Arad"}'>Donceni</div>
<div class="option" data='{"value":"Doncseny","state":"Arad"}'>Doncseny</div>
<div class="option" data='{"value":"Dorndorf","state":"Arad"}'>Dorndorf</div>
<div class="option" data='{"value":"Dulcele","state":"Arad"}'>Dulcele</div>
<div class="option" data='{"value":"Dulcsele","state":"Arad"}'>Dulcsele</div>
<div class="option" data='{"value":"Dumbrava","state":"Arad"}'>Dumbrava</div>
<div class="option" data='{"value":"Dumbravicza","state":"Arad"}'>Dumbravicza</div>
<div class="option" data='{"value":"Dumbravita","state":"Arad"}'>Dumbravita</div>
<div class="option" data='{"value":"Dumbrovicza","state":"Arad"}'>Dumbrovicza</div>
<div class="option" data='{"value":"Edeslak","state":"Arad"}'>Edeslak</div>
<div class="option" data='{"value":"Farkashaza","state":"Arad"}'>Farkashaza</div>
<div class="option" data='{"value":"Fazekastarno","state":"Arad"}'>Fazekastarno</div>
<div class="option" data='{"value":"Felmenes","state":"Arad"}'>Felmenes</div>
<div class="option" data='{"value":"Felsofeketevolgy","state":"Arad"}'>Felsofeketevolgy</div>
<div class="option" data='{"value":"Felsokoves","state":"Arad"}'>Felsokoves</div>
<div class="option" data='{"value":"Felsokristyor","state":"Arad"}'>Felsokristyor</div>
<div class="option" data='{"value":"Felsomenes","state":"Arad"}'>Felsomenes</div>
<div class="option" data='{"value":"Felsoszakacs","state":"Arad"}'>Felsoszakacs</div>
<div class="option" data='{"value":"Fenis","state":"Arad"}'>Fenis</div>
<div class="option" data='{"value":"Fenyes","state":"Arad"}'>Fenyes</div>
<div class="option" data='{"value":"Garassa","state":"Arad"}'>Garassa</div>
<div class="option" data='{"value":"Gavosdia","state":"Arad"}'>Gavosdia</div>
<div class="option" data='{"value":"Ghiulita","state":"Arad"}'>Ghiulita</div>
<div class="option" data='{"value":"Giulita","state":"Arad"}'>Giulita</div>
<div class="option" data='{"value":"Givonesti","state":"Arad"}'>Givonesti</div>
<div class="option" data='{"value":"Gosd","state":"Arad"}'>Gosd</div>
<div class="option" data='{"value":"Govojdia","state":"Arad"}'>Govojdia</div>
<div class="option" data='{"value":"Govosdia","state":"Arad"}'>Govosdia</div>
<div class="option" data='{"value":"Gros","state":"Arad"}'>Gros</div>
<div class="option" data='{"value":"Groseni","state":"Arad"}'>Groseni</div>
<div class="option" data='{"value":"Grosi","state":"Arad"}'>Grosi</div>
<div class="option" data='{"value":"Grosii Noi","state":"Arad"}'>Grosii Noi</div>
<div class="option" data='{"value":"Gross","state":"Arad"}'>Gross</div>
<div class="option" data='{"value":"Grosshalmagen","state":"Arad"}'>Grosshalmagen</div>
<div class="option" data='{"value":"Gura Vaii","state":"Arad"}'>Gura Vaii</div>
<div class="option" data='{"value":"Gurahoncz","state":"Arad"}'>Gurahoncz</div>
<div class="option" data='{"value":"Gurahont","state":"Arad"}'>Gurahont</div>
<div class="option" data='{"value":"Guravai","state":"Arad"}'>Guravai</div>
<div class="option" data='{"value":"Guravoj","state":"Arad"}'>Guravoj</div>
<div class="option" data='{"value":"Gyulato","state":"Arad"}'>Gyulato</div>
<div class="option" data='{"value":"Gyulicza","state":"Arad"}'>Gyulicza</div>
<div class="option" data='{"value":"Halalis","state":"Arad"}'>Halalis</div>
<div class="option" data='{"value":"Halmagel","state":"Arad"}'>Halmagel</div>
<div class="option" data='{"value":"Halmagiu","state":"Arad"}'>Halmagiu</div>
<div class="option" data='{"value":"Halmagy","state":"Arad"}'>Halmagy</div>
<div class="option" data='{"value":"Halmagymezo","state":"Arad"}'>Halmagymezo</div>
<div class="option" data='{"value":"Hamagiul","state":"Arad"}'>Hamagiul</div>
<div class="option" data='{"value":"Haromalmas","state":"Arad"}'>Haromalmas</div>
<div class="option" data='{"value":"Harsesti","state":"Arad"}'>Harsesti</div>
<div class="option" data='{"value":"Harzesti","state":"Arad"}'>Harzesti</div>
<div class="option" data='{"value":"Henkeres","state":"Arad"}'>Henkeres</div>
<div class="option" data='{"value":"Herzafalva","state":"Arad"}'>Herzafalva</div>
<div class="option" data='{"value":"Herzest","state":"Arad"}'>Herzest</div>
<div class="option" data='{"value":"Hevizkarand","state":"Arad"}'>Hevizkarand</div>
<div class="option" data='{"value":"Hinchiris","state":"Arad"}'>Hinchiris</div>
<div class="option" data='{"value":"Hirsesti","state":"Arad"}'>Hirsesti</div>
<div class="option" data='{"value":"Hodis","state":"Arad"}'>Hodis</div>
<div class="option" data='{"value":"Hodos","state":"Arad"}'>Hodos</div>
<div class="option" data='{"value":"Holdmezes","state":"Arad"}'>Holdmezes</div>
<div class="option" data='{"value":"Holdt","state":"Arad"}'>Holdt</div>
<div class="option" data='{"value":"Holt","state":"Arad"}'>Holt</div>
<div class="option" data='{"value":"Honcto","state":"Arad"}'>Honcto</div>
<div class="option" data='{"value":"Hosszusor","state":"Arad"}'>Hosszusor</div>
<div class="option" data='{"value":"Iacobini","state":"Arad"}'>Iacobini</div>
<div class="option" data='{"value":"Ignafalva","state":"Arad"}'>Ignafalva</div>
<div class="option" data='{"value":"Ignest","state":"Arad"}'>Ignest</div>
<div class="option" data='{"value":"Ignesti","state":"Arad"}'>Ignesti</div>
<div class="option" data='{"value":"Ignesty","state":"Arad"}'>Ignesty</div>
<div class="option" data='{"value":"Ilgyo","state":"Arad"}'>Ilgyo</div>
<div class="option" data='{"value":"Ilteu","state":"Arad"}'>Ilteu</div>
<div class="option" data='{"value":"Ilto","state":"Arad"}'>Ilto</div>
<div class="option" data='{"value":"Iltyo","state":"Arad"}'>Iltyo</div>
<div class="option" data='{"value":"Ionesti","state":"Arad"}'>Ionesti</div>
<div class="option" data='{"value":"Iosas","state":"Arad"}'>Iosas</div>
<div class="option" data='{"value":"Iosasel","state":"Arad"}'>Iosasel</div>
<div class="option" data='{"value":"Iosasi","state":"Arad"}'>Iosasi</div>
<div class="option" data='{"value":"Irtasfalu","state":"Arad"}'>Irtasfalu</div>
<div class="option" data='{"value":"Jacobini","state":"Arad"}'>Jacobini</div>
<div class="option" data='{"value":"Joia Mare","state":"Arad"}'>Joia Mare</div>
<div class="option" data='{"value":"Jonesdorf","state":"Arad"}'>Jonesdorf</div>
<div class="option" data='{"value":"Joszas","state":"Arad"}'>Joszas</div>
<div class="option" data='{"value":"Joszashely","state":"Arad"}'>Joszashely</div>
<div class="option" data='{"value":"Judetul Arad","state":"Arad"}'>Judetul Arad</div>
<div class="option" data='{"value":"Julita","state":"Arad"}'>Julita</div>
<div class="option" data='{"value":"Juonesd","state":"Arad"}'>Juonesd</div>
<div class="option" data='{"value":"Kakaro","state":"Arad"}'>Kakaro</div>
<div class="option" data='{"value":"Kaprucza","state":"Arad"}'>Kaprucza</div>
<div class="option" data='{"value":"Karand","state":"Arad"}'>Karand</div>
<div class="option" data='{"value":"Keresztespatak","state":"Arad"}'>Keresztespatak</div>
<div class="option" data='{"value":"Keresztmenes","state":"Arad"}'>Keresztmenes</div>
<div class="option" data='{"value":"Kertes","state":"Arad"}'>Kertes</div>
<div class="option" data='{"value":"Keszend","state":"Arad"}'>Keszend</div>
<div class="option" data='{"value":"Kisbaja","state":"Arad"}'>Kisbaja</div>
<div class="option" data='{"value":"Kisfeketefalu","state":"Arad"}'>Kisfeketefalu</div>
<div class="option" data='{"value":"Kishalmagy","state":"Arad"}'>Kishalmagy</div>
<div class="option" data='{"value":"Kiskoh","state":"Arad"}'>Kiskoh</div>
<div class="option" data='{"value":"Kismaglod","state":"Arad"}'>Kismaglod</div>
<div class="option" data='{"value":"Kisrona","state":"Arad"}'>Kisrona</div>
<div class="option" data='{"value":"Kiszindia","state":"Arad"}'>Kiszindia</div>
<div class="option" data='{"value":"Kocsoba","state":"Arad"}'>Kocsoba</div>
<div class="option" data='{"value":"Kocsuba","state":"Arad"}'>Kocsuba</div>
<div class="option" data='{"value":"Kokaro","state":"Arad"}'>Kokaro</div>
<div class="option" data='{"value":"Komanfalva","state":"Arad"}'>Komanfalva</div>
<div class="option" data='{"value":"Korbest","state":"Arad"}'>Korbest</div>
<div class="option" data='{"value":"Koroknya","state":"Arad"}'>Koroknya</div>
<div class="option" data='{"value":"Korosbokeny","state":"Arad"}'>Korosbokeny</div>
<div class="option" data='{"value":"Korosdombro","state":"Arad"}'>Korosdombro</div>
<div class="option" data='{"value":"Korosfenyes","state":"Arad"}'>Korosfenyes</div>
<div class="option" data='{"value":"Korosivand","state":"Arad"}'>Korosivand</div>
<div class="option" data='{"value":"Koroskocsoba","state":"Arad"}'>Koroskocsoba</div>
<div class="option" data='{"value":"Korosvajda","state":"Arad"}'>Korosvajda</div>
<div class="option" data='{"value":"Koszend","state":"Arad"}'>Koszend</div>
<div class="option" data='{"value":"Koved","state":"Arad"}'>Koved</div>
<div class="option" data='{"value":"Kresztamenes","state":"Arad"}'>Kresztamenes</div>
<div class="option" data='{"value":"Kristyor","state":"Arad"}'>Kristyor</div>
<div class="option" data='{"value":"Krisztesd","state":"Arad"}'>Krisztesd</div>
<div class="option" data='{"value":"Krogna","state":"Arad"}'>Krogna</div>
<div class="option" data='{"value":"Krokna","state":"Arad"}'>Krokna</div>
<div class="option" data='{"value":"Kujas","state":"Arad"}'>Kujas</div>
<div class="option" data='{"value":"Kujed","state":"Arad"}'>Kujed</div>
<div class="option" data='{"value":"Kumanyesd","state":"Arad"}'>Kumanyesd</div>
<div class="option" data='{"value":"Laass","state":"Arad"}'>Laass</div>
<div class="option" data='{"value":"Lalanc","state":"Arad"}'>Lalanc</div>
<div class="option" data='{"value":"Lalancz","state":"Arad"}'>Lalancz</div>
<div class="option" data='{"value":"Lalasincz","state":"Arad"}'>Lalasincz</div>
<div class="option" data='{"value":"Lalasint","state":"Arad"}'>Lalasint</div>
<div class="option" data='{"value":"Lalasinti","state":"Arad"}'>Lalasinti</div>
<div class="option" data='{"value":"Laz","state":"Arad"}'>Laz</div>
<div class="option" data='{"value":"Lazur","state":"Arad"}'>Lazur</div>
<div class="option" data='{"value":"Lazuri","state":"Arad"}'>Lazuri</div>
<div class="option" data='{"value":"Leasa","state":"Arad"}'>Leasa</div>
<div class="option" data='{"value":"Leasza","state":"Arad"}'>Leasza</div>
<div class="option" data='{"value":"Livada","state":"Arad"}'>Livada</div>
<div class="option" data='{"value":"Luncsoara","state":"Arad"}'>Luncsoara</div>
<div class="option" data='{"value":"Lungsora","state":"Arad"}'>Lungsora</div>
<div class="option" data='{"value":"Lunksora","state":"Arad"}'>Lunksora</div>
<div class="option" data='{"value":"Lupest","state":"Arad"}'>Lupest</div>
<div class="option" data='{"value":"Lupesti","state":"Arad"}'>Lupesti</div>
<div class="option" data='{"value":"Madarsak","state":"Arad"}'>Madarsak</div>
<div class="option" data='{"value":"Madrigesti","state":"Arad"}'>Madrigesti</div>
<div class="option" data='{"value":"Madrijesti","state":"Arad"}'>Madrijesti</div>
<div class="option" data='{"value":"Madrizest","state":"Arad"}'>Madrizest</div>
<div class="option" data='{"value":"Madrizestyi","state":"Arad"}'>Madrizestyi</div>
<div class="option" data='{"value":"Magulicea","state":"Arad"}'>Magulicea</div>
<div class="option" data='{"value":"Magulicsa","state":"Arad"}'>Magulicsa</div>
<div class="option" data='{"value":"Magura","state":"Arad"}'>Magura</div>
<div class="option" data='{"value":"Maraus","state":"Arad"}'>Maraus</div>
<div class="option" data='{"value":"Marausi","state":"Arad"}'>Marausi</div>
<div class="option" data='{"value":"Markaszek","state":"Arad"}'>Markaszek</div>
<div class="option" data='{"value":"Markuszek","state":"Arad"}'>Markuszek</div>
<div class="option" data='{"value":"Marosborsa","state":"Arad"}'>Marosborsa</div>
<div class="option" data='{"value":"Maroshollod","state":"Arad"}'>Maroshollod</div>
<div class="option" data='{"value":"Maroskapronca","state":"Arad"}'>Maroskapronca</div>
<div class="option" data='{"value":"Maroskaproncza","state":"Arad"}'>Maroskaproncza</div>
<div class="option" data='{"value":"Marosmonyoro","state":"Arad"}'>Marosmonyoro</div>
<div class="option" data='{"value":"Marosnagyvolgy","state":"Arad"}'>Marosnagyvolgy</div>
<div class="option" data='{"value":"Marospetres","state":"Arad"}'>Marospetres</div>
<div class="option" data='{"value":"Marosszalatna","state":"Arad"}'>Marosszalatna</div>
<div class="option" data='{"value":"Marosszeleste","state":"Arad"}'>Marosszeleste</div>
<div class="option" data='{"value":"Marosszlatina","state":"Arad"}'>Marosszlatina</div>
<div class="option" data='{"value":"Martfalva","state":"Arad"}'>Martfalva</div>
<div class="option" data='{"value":"Megyes","state":"Arad"}'>Megyes</div>
<div class="option" data='{"value":"Menes","state":"Arad"}'>Menes</div>
<div class="option" data='{"value":"Menyed","state":"Arad"}'>Menyed</div>
<div class="option" data='{"value":"Menyhaza","state":"Arad"}'>Menyhaza</div>
<div class="option" data='{"value":"Mermecs","state":"Arad"}'>Mermecs</div>
<div class="option" data='{"value":"Mermesd","state":"Arad"}'>Mermesd</div>
<div class="option" data='{"value":"Mermesti","state":"Arad"}'>Mermesti</div>
<div class="option" data='{"value":"Mezes","state":"Arad"}'>Mezes</div>
<div class="option" data='{"value":"Micalaca","state":"Arad"}'>Micalaca</div>
<div class="option" data='{"value":"Micanesti","state":"Arad"}'>Micanesti</div>
<div class="option" data='{"value":"Mikafalva","state":"Arad"}'>Mikafalva</div>
<div class="option" data='{"value":"Mikanesd","state":"Arad"}'>Mikanesd</div>
<div class="option" data='{"value":"Mikelaka","state":"Arad"}'>Mikelaka</div>
<div class="option" data='{"value":"Mikofalva","state":"Arad"}'>Mikofalva</div>
<div class="option" data='{"value":"Mikoszalatna","state":"Arad"}'>Mikoszalatna</div>
<div class="option" data='{"value":"Minead","state":"Arad"}'>Minead</div>
<div class="option" data='{"value":"Miniad","state":"Arad"}'>Miniad</div>
<div class="option" data='{"value":"Minisel","state":"Arad"}'>Minisel</div>
<div class="option" data='{"value":"Minisu de Sus","state":"Arad"}'>Minisu de Sus</div>
<div class="option" data='{"value":"Minyad","state":"Arad"}'>Minyad</div>
<div class="option" data='{"value":"Mocioni","state":"Arad"}'>Mocioni</div>
<div class="option" data='{"value":"Monarostia","state":"Arad"}'>Monarostia</div>
<div class="option" data='{"value":"Moneasa","state":"Arad"}'>Moneasa</div>
<div class="option" data='{"value":"Monorostia","state":"Arad"}'>Monorostia</div>
<div class="option" data='{"value":"Monorostya","state":"Arad"}'>Monorostya</div>
<div class="option" data='{"value":"Monyad","state":"Arad"}'>Monyad</div>
<div class="option" data='{"value":"Monyahaza","state":"Arad"}'>Monyahaza</div>
<div class="option" data='{"value":"Monyasza","state":"Arad"}'>Monyasza</div>
<div class="option" data='{"value":"Mosztafalva","state":"Arad"}'>Mosztafalva</div>
<div class="option" data='{"value":"Murasel","state":"Arad"}'>Murasel</div>
<div class="option" data='{"value":"Muresel","state":"Arad"}'>Muresel</div>
<div class="option" data='{"value":"Mustesti","state":"Arad"}'>Mustesti</div>
<div class="option" data='{"value":"Musztesd","state":"Arad"}'>Musztesd</div>
<div class="option" data='{"value":"Musztesty","state":"Arad"}'>Musztesty</div>
<div class="option" data='{"value":"Nadalbest","state":"Arad"}'>Nadalbest</div>
<div class="option" data='{"value":"Nadalbesti","state":"Arad"}'>Nadalbesti</div>
<div class="option" data='{"value":"Nadalmas","state":"Arad"}'>Nadalmas</div>
<div class="option" data='{"value":"Nadalmesti","state":"Arad"}'>Nadalmesti</div>
<div class="option" data='{"value":"Nagyhalmagy","state":"Arad"}'>Nagyhalmagy</div>
<div class="option" data='{"value":"Neagra","state":"Arad"}'>Neagra</div>
<div class="option" data='{"value":"Nermegy","state":"Arad"}'>Nermegy</div>
<div class="option" data='{"value":"Nermis","state":"Arad"}'>Nermis</div>
<div class="option" data='{"value":"Nicolae Balcescu","state":"Arad"}'>Nicolae Balcescu</div>
<div class="option" data='{"value":"Nyagra","state":"Arad"}'>Nyagra</div>
<div class="option" data='{"value":"Nyermegy","state":"Arad"}'>Nyermegy</div>
<div class="option" data='{"value":"Ochiuri","state":"Arad"}'>Ochiuri</div>
<div class="option" data='{"value":"Ociu","state":"Arad"}'>Ociu</div>
<div class="option" data='{"value":"Ociul","state":"Arad"}'>Ociul</div>
<div class="option" data='{"value":"Ocs","state":"Arad"}'>Ocs</div>
<div class="option" data='{"value":"Olcs","state":"Arad"}'>Olcs</div>
<div class="option" data='{"value":"Orodinum","state":"Arad"}'>Orodinum</div>
<div class="option" data='{"value":"Orvenyes","state":"Arad"}'>Orvenyes</div>
<div class="option" data='{"value":"Paiusani","state":"Arad"}'>Paiusani</div>
<div class="option" data='{"value":"Paiuseni","state":"Arad"}'>Paiuseni</div>
<div class="option" data='{"value":"Pajsan","state":"Arad"}'>Pajsan</div>
<div class="option" data='{"value":"Pajzs","state":"Arad"}'>Pajzs</div>
<div class="option" data='{"value":"Parnesti","state":"Arad"}'>Parnesti</div>
<div class="option" data='{"value":"Paulian","state":"Arad"}'>Paulian</div>
<div class="option" data='{"value":"Peleskefalva","state":"Arad"}'>Peleskefalva</div>
<div class="option" data='{"value":"Pernesti","state":"Arad"}'>Pernesti</div>
<div class="option" data='{"value":"Pernyefalva","state":"Arad"}'>Pernyefalva</div>
<div class="option" data='{"value":"Pernyest","state":"Arad"}'>Pernyest</div>
<div class="option" data='{"value":"Pescari","state":"Arad"}'>Pescari</div>
<div class="option" data='{"value":"Petris","state":"Arad"}'>Petris</div>
<div class="option" data='{"value":"Pirnesti","state":"Arad"}'>Pirnesti</div>
<div class="option" data='{"value":"Plescuta","state":"Arad"}'>Plescuta</div>
<div class="option" data='{"value":"Pleskucza","state":"Arad"}'>Pleskucza</div>
<div class="option" data='{"value":"Poenari","state":"Arad"}'>Poenari</div>
<div class="option" data='{"value":"Poiana","state":"Arad"}'>Poiana</div>
<div class="option" data='{"value":"Poienari","state":"Arad"}'>Poienari</div>
<div class="option" data='{"value":"Pojana","state":"Arad"}'>Pojana</div>
<div class="option" data='{"value":"Pojenar","state":"Arad"}'>Pojenar</div>
<div class="option" data='{"value":"Polyana","state":"Arad"}'>Polyana</div>
<div class="option" data='{"value":"Prunisor","state":"Arad"}'>Prunisor</div>
<div class="option" data='{"value":"Rabszek","state":"Arad"}'>Rabszek</div>
<div class="option" data='{"value":"Radesti","state":"Arad"}'>Radesti</div>
<div class="option" data='{"value":"Raissendorf","state":"Arad"}'>Raissendorf</div>
<div class="option" data='{"value":"Raitzendorf","state":"Arad"}'>Raitzendorf</div>
<div class="option" data='{"value":"Raj","state":"Arad"}'>Raj</div>
<div class="option" data='{"value":"Ranusa","state":"Arad"}'>Ranusa</div>
<div class="option" data='{"value":"Rapsig","state":"Arad"}'>Rapsig</div>
<div class="option" data='{"value":"Ravna","state":"Arad"}'>Ravna</div>
<div class="option" data='{"value":"Regele Carol","state":"Arad"}'>Regele Carol</div>
<div class="option" data='{"value":"Rekes","state":"Arad"}'>Rekes</div>
<div class="option" data='{"value":"Repsen","state":"Arad"}'>Repsen</div>
<div class="option" data='{"value":"Repszeg","state":"Arad"}'>Repszeg</div>
<div class="option" data='{"value":"Restoci","state":"Arad"}'>Restoci</div>
<div class="option" data='{"value":"Revetis","state":"Arad"}'>Revetis</div>
<div class="option" data='{"value":"Rogoz","state":"Arad"}'>Rogoz</div>
<div class="option" data='{"value":"Rogoz de Beliu","state":"Arad"}'>Rogoz de Beliu</div>
<div class="option" data='{"value":"Rosa","state":"Arad"}'>Rosa</div>
<div class="option" data='{"value":"Rosia","state":"Arad"}'>Rosia</div>
<div class="option" data='{"value":"Rosia Noua","state":"Arad"}'>Rosia Noua</div>
<div class="option" data='{"value":"Rossia","state":"Arad"}'>Rossia</div>
<div class="option" data='{"value":"Rossina","state":"Arad"}'>Rossina</div>
<div class="option" data='{"value":"Rostoci","state":"Arad"}'>Rostoci</div>
<div class="option" data='{"value":"Rostocs","state":"Arad"}'>Rostocs</div>
<div class="option" data='{"value":"Rosztocs","state":"Arad"}'>Rosztocs</div>
<div class="option" data='{"value":"Rosztocz","state":"Arad"}'>Rosztocz</div>
<div class="option" data='{"value":"Sac","state":"Arad"}'>Sac</div>
<div class="option" data='{"value":"Sacaiu","state":"Arad"}'>Sacaiu</div>
<div class="option" data='{"value":"Salajani","state":"Arad"}'>Salajani</div>
<div class="option" data='{"value":"Salajeni","state":"Arad"}'>Salajeni</div>
<div class="option" data='{"value":"Saliste","state":"Arad"}'>Saliste</div>
<div class="option" data='{"value":"Sarbi","state":"Arad"}'>Sarbi</div>
<div class="option" data='{"value":"Saturau","state":"Arad"}'>Saturau</div>
<div class="option" data='{"value":"Sau","state":"Arad"}'>Sau</div>
<div class="option" data='{"value":"Savarsin","state":"Arad"}'>Savarsin</div>
<div class="option" data='{"value":"Savirsin","state":"Arad"}'>Savirsin</div>
<div class="option" data='{"value":"Schoborschin","state":"Arad"}'>Schoborschin</div>
<div class="option" data='{"value":"Sebis","state":"Arad"}'>Sebis</div>
<div class="option" data='{"value":"Secaci","state":"Arad"}'>Secaci</div>
<div class="option" data='{"value":"Secaiu","state":"Arad"}'>Secaiu</div>
<div class="option" data='{"value":"Secas","state":"Arad"}'>Secas</div>
<div class="option" data='{"value":"Seghiste","state":"Arad"}'>Seghiste</div>
<div class="option" data='{"value":"Segyest","state":"Arad"}'>Segyest</div>
<div class="option" data='{"value":"Selejani","state":"Arad"}'>Selejani</div>
<div class="option" data='{"value":"Selejeni","state":"Arad"}'>Selejeni</div>
<div class="option" data='{"value":"Seliste","state":"Arad"}'>Seliste</div>
<div class="option" data='{"value":"Selistea","state":"Arad"}'>Selistea</div>
<div class="option" data='{"value":"Sic","state":"Arad"}'>Sic</div>
<div class="option" data='{"value":"Sirbi","state":"Arad"}'>Sirbi</div>
<div class="option" data='{"value":"Slatina de Cris","state":"Arad"}'>Slatina de Cris</div>
<div class="option" data='{"value":"Slatina de Mures","state":"Arad"}'>Slatina de Mures</div>
<div class="option" data='{"value":"Soborsin","state":"Arad"}'>Soborsin</div>
<div class="option" data='{"value":"Soimus Buciava","state":"Arad"}'>Soimus Buciava</div>
<div class="option" data='{"value":"Solymos","state":"Arad"}'>Solymos</div>
<div class="option" data='{"value":"Solymosbucsa","state":"Arad"}'>Solymosbucsa</div>
<div class="option" data='{"value":"Sovenyes","state":"Arad"}'>Sovenyes</div>
<div class="option" data='{"value":"Stejar","state":"Arad"}'>Stejar</div>
<div class="option" data='{"value":"Stramba","state":"Arad"}'>Stramba</div>
<div class="option" data='{"value":"Strimba","state":"Arad"}'>Strimba</div>
<div class="option" data='{"value":"Stupini","state":"Arad"}'>Stupini</div>
<div class="option" data='{"value":"Szakacs","state":"Arad"}'>Szakacs</div>
<div class="option" data='{"value":"Szarvasag","state":"Arad"}'>Szarvasag</div>
<div class="option" data='{"value":"Szatureo","state":"Arad"}'>Szatureo</div>
<div class="option" data='{"value":"Szaturo","state":"Arad"}'>Szaturo</div>
<div class="option" data='{"value":"Szegyesd","state":"Arad"}'>Szegyesd</div>
<div class="option" data='{"value":"Szek","state":"Arad"}'>Szek</div>
<div class="option" data='{"value":"Szelezsany","state":"Arad"}'>Szelezsany</div>
<div class="option" data='{"value":"Szelezseny","state":"Arad"}'>Szelezseny</div>
<div class="option" data='{"value":"Szelistye","state":"Arad"}'>Szelistye</div>
<div class="option" data='{"value":"Szerb","state":"Arad"}'>Szerb</div>
<div class="option" data='{"value":"Szlatina","state":"Arad"}'>Szlatina</div>
<div class="option" data='{"value":"Szorossag","state":"Arad"}'>Szorossag</div>
<div class="option" data='{"value":"Sztrimba","state":"Arad"}'>Sztrimba</div>
<div class="option" data='{"value":"Tagadau","state":"Arad"}'>Tagadau</div>
<div class="option" data='{"value":"Tagado","state":"Arad"}'>Tagado</div>
<div class="option" data='{"value":"Tagadomegyes","state":"Arad"}'>Tagadomegyes</div>
<div class="option" data='{"value":"Talacs","state":"Arad"}'>Talacs</div>
<div class="option" data='{"value":"Talacsu","state":"Arad"}'>Talacsu</div>
<div class="option" data='{"value":"Talagiu","state":"Arad"}'>Talagiu</div>
<div class="option" data='{"value":"Talagiul","state":"Arad"}'>Talagiul</div>
<div class="option" data='{"value":"Tarmure","state":"Arad"}'>Tarmure</div>
<div class="option" data='{"value":"Tarnavita","state":"Arad"}'>Tarnavita</div>
<div class="option" data='{"value":"Tatarfalva","state":"Arad"}'>Tatarfalva</div>
<div class="option" data='{"value":"Temesd","state":"Arad"}'>Temesd</div>
<div class="option" data='{"value":"Temesesti","state":"Arad"}'>Temesesti</div>
<div class="option" data='{"value":"Temest","state":"Arad"}'>Temest</div>
<div class="option" data='{"value":"Ternavicza","state":"Arad"}'>Ternavicza</div>
<div class="option" data='{"value":"Tirnavita","state":"Arad"}'>Tirnavita</div>
<div class="option" data='{"value":"Tirnovicza","state":"Arad"}'>Tirnovicza</div>
<div class="option" data='{"value":"Tirnovita","state":"Arad"}'>Tirnovita</div>
<div class="option" data='{"value":"Tisa","state":"Arad"}'>Tisa</div>
<div class="option" data='{"value":"Tiszafalva","state":"Arad"}'>Tiszafalva</div>
<div class="option" data='{"value":"Toc","state":"Arad"}'>Toc</div>
<div class="option" data='{"value":"Tohesti","state":"Arad"}'>Tohesti</div>
<div class="option" data='{"value":"Tok","state":"Arad"}'>Tok</div>
<div class="option" data='{"value":"Tonkod","state":"Arad"}'>Tonkod</div>
<div class="option" data='{"value":"Torjas","state":"Arad"}'>Torjas</div>
<div class="option" data='{"value":"Totoreni","state":"Arad"}'>Totoreni</div>
<div class="option" data='{"value":"Totoreny","state":"Arad"}'>Totoreny</div>
<div class="option" data='{"value":"Totvarad","state":"Arad"}'>Totvarad</div>
<div class="option" data='{"value":"Totvaradgya","state":"Arad"}'>Totvaradgya</div>
<div class="option" data='{"value":"Totvaradja","state":"Arad"}'>Totvaradja</div>
<div class="option" data='{"value":"Troas","state":"Arad"}'>Troas</div>
<div class="option" data='{"value":"Troias","state":"Arad"}'>Troias</div>
<div class="option" data='{"value":"Trojas","state":"Arad"}'>Trojas</div>
<div class="option" data='{"value":"Urvis de Beliu","state":"Arad"}'>Urvis de Beliu</div>
<div class="option" data='{"value":"Urvisu de Beliu","state":"Arad"}'>Urvisu de Beliu</div>
<div class="option" data='{"value":"Vajvoda","state":"Arad"}'>Vajvoda</div>
<div class="option" data='{"value":"Valea de Sus","state":"Arad"}'>Valea de Sus</div>
<div class="option" data='{"value":"Valea Mare","state":"Arad"}'>Valea Mare</div>
<div class="option" data='{"value":"Valea Neagra de Sus","state":"Arad"}'>Valea Neagra de Sus</div>
<div class="option" data='{"value":"Valemare","state":"Arad"}'>Valemare</div>
<div class="option" data='{"value":"Vallemare","state":"Arad"}'>Vallemare</div>
<div class="option" data='{"value":"Vam","state":"Arad"}'>Vam</div>
<div class="option" data='{"value":"Varadia de Mures","state":"Arad"}'>Varadia de Mures</div>
<div class="option" data='{"value":"Varfurile","state":"Arad"}'>Varfurile</div>
<div class="option" data='{"value":"Vasioaia","state":"Arad"}'>Vasioaia</div>
<div class="option" data='{"value":"Vasoaia","state":"Arad"}'>Vasoaia</div>
<div class="option" data='{"value":"Vaszoja","state":"Arad"}'>Vaszoja</div>
<div class="option" data='{"value":"Veszalja","state":"Arad"}'>Veszalja</div>
<div class="option" data='{"value":"Vidra","state":"Arad"}'>Vidra</div>
<div class="option" data='{"value":"Vinesti","state":"Arad"}'>Vinesti</div>
<div class="option" data='{"value":"Virfurile","state":"Arad"}'>Virfurile</div>
<div class="option" data='{"value":"Voivodeni","state":"Arad"}'>Voivodeni</div>
<div class="option" data='{"value":"Vojkahaza","state":"Arad"}'>Vojkahaza</div>
<div class="option" data='{"value":"Vojvogyen","state":"Arad"}'>Vojvogyen</div>
<div class="option" data='{"value":"Vosdoci Lungsoara","state":"Arad"}'>Vosdoci Lungsoara</div>
<div class="option" data='{"value":"Zarand","state":"Arad"}'>Zarand</div>
<div class="option" data='{"value":"Zarandbanya","state":"Arad"}'>Zarandbanya</div>
<div class="option" data='{"value":"Zarandhodos","state":"Arad"}'>Zarandhodos</div>
<div class="option" data='{"value":"Zarandpatak","state":"Arad"}'>Zarandpatak</div>
<div class="option" data='{"value":"Zeldis","state":"Arad"}'>Zeldis</div>
<div class="option" data='{"value":"Zimbro","state":"Arad"}'>Zimbro</div>
<div class="option" data='{"value":"Zimbru","state":"Arad"}'>Zimbru</div>
<div class="option" data='{"value":"Zimbrul","state":"Arad"}'>Zimbrul</div>
<div class="option" data='{"value":"Zoldes","state":"Arad"}'>Zoldes</div>
<div class="option" data='{"value":"Zombrad","state":"Arad"}'>Zombrad</div>
<div class="option" id="option_end" data='{"value":"Zsigmondhaza","state":"Arad"}'>Zsigmondhaza</div>

