<div class="option" data='{"value":"Abasar","state":"Heves"}'>Abasar</div>
<div class="option" data='{"value":"Adacs","state":"Heves"}'>Adacs</div>
<div class="option" data='{"value":"Adlerszollos","state":"Heves"}'>Adlerszollos</div>
<div class="option" data='{"value":"Agardidulo","state":"Heves"}'>Agardidulo</div>
<div class="option" data='{"value":"Akolhat","state":"Heves"}'>Akolhat</div>
<div class="option" data='{"value":"Akolhati Puszta","state":"Heves"}'>Akolhati Puszta</div>
<div class="option" data='{"value":"Alatka","state":"Heves"}'>Alatka</div>
<div class="option" data='{"value":"Albertmajor","state":"Heves"}'>Albertmajor</div>
<div class="option" data='{"value":"Aldebro","state":"Heves"}'>Aldebro</div>
<div class="option" data='{"value":"Aldozo","state":"Heves"}'>Aldozo</div>
<div class="option" data='{"value":"Almagyardulo","state":"Heves"}'>Almagyardulo</div>
<div class="option" data='{"value":"Almar","state":"Heves"}'>Almar</div>
<div class="option" data='{"value":"Alsomagyalos","state":"Heves"}'>Alsomagyalos</div>
<div class="option" data='{"value":"Alsonyiget","state":"Heves"}'>Alsonyiget</div>
<div class="option" data='{"value":"Alsorozsnakpuszta","state":"Heves"}'>Alsorozsnakpuszta</div>
<div class="option" data='{"value":"Alsotanya","state":"Heves"}'>Alsotanya</div>
<div class="option" data='{"value":"Andornaktalya","state":"Heves"}'>Andornaktalya</div>
<div class="option" data='{"value":"Andretanya","state":"Heves"}'>Andretanya</div>
<div class="option" data='{"value":"Annamajor","state":"Heves"}'>Annamajor</div>
<div class="option" data='{"value":"Apc","state":"Heves"}'>Apc</div>
<div class="option" data='{"value":"Aranyosi Tanya","state":"Heves"}'>Aranyosi Tanya</div>
<div class="option" data='{"value":"Atany","state":"Heves"}'>Atany</div>
<div class="option" data='{"value":"Atkar","state":"Heves"}'>Atkar</div>
<div class="option" data='{"value":"Atkari Tanyak","state":"Heves"}'>Atkari Tanyak</div>
<div class="option" data='{"value":"Bagolyirtas","state":"Heves"}'>Bagolyirtas</div>
<div class="option" data='{"value":"Bagolyvar","state":"Heves"}'>Bagolyvar</div>
<div class="option" data='{"value":"Bajpuszta","state":"Heves"}'>Bajpuszta</div>
<div class="option" data='{"value":"Baksatanya","state":"Heves"}'>Baksatanya</div>
<div class="option" data='{"value":"Balaton","state":"Heves"}'>Balaton</div>
<div class="option" data='{"value":"Balatoni Tanyak","state":"Heves"}'>Balatoni Tanyak</div>
<div class="option" data='{"value":"Balazshalom","state":"Heves"}'>Balazshalom</div>
<div class="option" data='{"value":"Balinttanya","state":"Heves"}'>Balinttanya</div>
<div class="option" data='{"value":"Ballai Volgy","state":"Heves"}'>Ballai Volgy</div>
<div class="option" data='{"value":"Balpuspokipuszta","state":"Heves"}'>Balpuspokipuszta</div>
<div class="option" data='{"value":"Baluret","state":"Heves"}'>Baluret</div>
<div class="option" data='{"value":"Banktanya","state":"Heves"}'>Banktanya</div>
<div class="option" data='{"value":"Bankut","state":"Heves"}'>Bankut</div>
<div class="option" data='{"value":"Bankuti Menedekhaz","state":"Heves"}'>Bankuti Menedekhaz</div>
<div class="option" data='{"value":"Banomkert","state":"Heves"}'>Banomkert</div>
<div class="option" data='{"value":"Banomszollok","state":"Heves"}'>Banomszollok</div>
<div class="option" data='{"value":"Banvolgyitanya","state":"Heves"}'>Banvolgyitanya</div>
<div class="option" data='{"value":"Banyadomb","state":"Heves"}'>Banyadomb</div>
<div class="option" data='{"value":"Baratkertimalom","state":"Heves"}'>Baratkertimalom</div>
<div class="option" data='{"value":"Barocsitanya","state":"Heves"}'>Barocsitanya</div>
<div class="option" data='{"value":"Basthytag","state":"Heves"}'>Basthytag</div>
<div class="option" data='{"value":"Bator","state":"Heves"}'>Bator</div>
<div class="option" data='{"value":"Battatanya","state":"Heves"}'>Battatanya</div>
<div class="option" data='{"value":"Bekafotanya","state":"Heves"}'>Bekafotanya</div>
<div class="option" data='{"value":"Bekasto","state":"Heves"}'>Bekasto</div>
<div class="option" data='{"value":"Bekolce","state":"Heves"}'>Bekolce</div>
<div class="option" data='{"value":"Belapatfalva","state":"Heves"}'>Belapatfalva</div>
<div class="option" data='{"value":"Belitanya","state":"Heves"}'>Belitanya</div>
<div class="option" data='{"value":"Belsopusztadalla","state":"Heves"}'>Belsopusztadalla</div>
<div class="option" data='{"value":"Belsoretitanyak","state":"Heves"}'>Belsoretitanyak</div>
<div class="option" data='{"value":"Belsosikhegy","state":"Heves"}'>Belsosikhegy</div>
<div class="option" data='{"value":"Benepuszta","state":"Heves"}'>Benepuszta</div>
<div class="option" data='{"value":"Beothytanya","state":"Heves"}'>Beothytanya</div>
<div class="option" data='{"value":"Bereczkitag","state":"Heves"}'>Bereczkitag</div>
<div class="option" data='{"value":"Berek","state":"Heves"}'>Berek</div>
<div class="option" data='{"value":"Berekalja","state":"Heves"}'>Berekalja</div>
<div class="option" data='{"value":"Bernathegy","state":"Heves"}'>Bernathegy</div>
<div class="option" data='{"value":"Bertahaza","state":"Heves"}'>Bertahaza</div>
<div class="option" data='{"value":"Bertamajor","state":"Heves"}'>Bertamajor</div>
<div class="option" data='{"value":"Besenyotelek","state":"Heves"}'>Besenyotelek</div>
<div class="option" data='{"value":"Bikahalom","state":"Heves"}'>Bikahalom</div>
<div class="option" data='{"value":"Bimbostanya","state":"Heves"}'>Bimbostanya</div>
<div class="option" data='{"value":"Bischitztanya","state":"Heves"}'>Bischitztanya</div>
<div class="option" data='{"value":"Bobaktanya","state":"Heves"}'>Bobaktanya</div>
<div class="option" data='{"value":"Boconad","state":"Heves"}'>Boconad</div>
<div class="option" data='{"value":"Bodics","state":"Heves"}'>Bodics</div>
<div class="option" data='{"value":"Bodicsi Tanyak","state":"Heves"}'>Bodicsi Tanyak</div>
<div class="option" data='{"value":"Bodicstanya","state":"Heves"}'>Bodicstanya</div>
<div class="option" data='{"value":"Bodoghtanya","state":"Heves"}'>Bodoghtanya</div>
<div class="option" data='{"value":"Bodony","state":"Heves"}'>Bodony</div>
<div class="option" data='{"value":"Bohacstag","state":"Heves"}'>Bohacstag</div>
<div class="option" data='{"value":"Boldog","state":"Heves"}'>Boldog</div>
<div class="option" data='{"value":"Bolyapuszta","state":"Heves"}'>Bolyapuszta</div>
<div class="option" data='{"value":"Bordastanya","state":"Heves"}'>Bordastanya</div>
<div class="option" data='{"value":"Borhyalsotanya","state":"Heves"}'>Borhyalsotanya</div>
<div class="option" data='{"value":"Borhyfelsotanya","state":"Heves"}'>Borhyfelsotanya</div>
<div class="option" data='{"value":"Borhytanya","state":"Heves"}'>Borhytanya</div>
<div class="option" data='{"value":"Borjajaras","state":"Heves"}'>Borjajaras</div>
<div class="option" data='{"value":"Boroszlotanya","state":"Heves"}'>Boroszlotanya</div>
<div class="option" data='{"value":"Borsodszemere","state":"Heves"}'>Borsodszemere</div>
<div class="option" data='{"value":"Borsodszentmarton","state":"Heves"}'>Borsodszentmarton</div>
<div class="option" data='{"value":"Borsos","state":"Heves"}'>Borsos</div>
<div class="option" data='{"value":"Borytanya","state":"Heves"}'>Borytanya</div>
<div class="option" data='{"value":"Brezovaitanya","state":"Heves"}'>Brezovaitanya</div>
<div class="option" data='{"value":"Brezovatanya","state":"Heves"}'>Brezovatanya</div>
<div class="option" data='{"value":"Brezovaytanya","state":"Heves"}'>Brezovaytanya</div>
<div class="option" data='{"value":"Brindzatanya","state":"Heves"}'>Brindzatanya</div>
<div class="option" data='{"value":"Bucka","state":"Heves"}'>Bucka</div>
<div class="option" data='{"value":"Budahattanya","state":"Heves"}'>Budahattanya</div>
<div class="option" data='{"value":"Bugyitanya","state":"Heves"}'>Bugyitanya</div>
<div class="option" data='{"value":"Bukkszek","state":"Heves"}'>Bukkszek</div>
<div class="option" data='{"value":"Bukkszenterzsebet","state":"Heves"}'>Bukkszenterzsebet</div>
<div class="option" data='{"value":"Bukkszentmarton","state":"Heves"}'>Bukkszentmarton</div>
<div class="option" data='{"value":"Butelek","state":"Heves"}'>Butelek</div>
<div class="option" data='{"value":"Butelektanya","state":"Heves"}'>Butelektanya</div>
<div class="option" data='{"value":"Cegledidulo","state":"Heves"}'>Cegledidulo</div>
<div class="option" data='{"value":"Cifrastanya","state":"Heves"}'>Cifrastanya</div>
<div class="option" data='{"value":"Cifratanya","state":"Heves"}'>Cifratanya</div>
<div class="option" data='{"value":"Csakanyko","state":"Heves"}'>Csakanyko</div>
<div class="option" data='{"value":"Csakanykotanya","state":"Heves"}'>Csakanykotanya</div>
<div class="option" data='{"value":"Csakberektanya","state":"Heves"}'>Csakberektanya</div>
<div class="option" data='{"value":"Csakitanya","state":"Heves"}'>Csakitanya</div>
<div class="option" data='{"value":"Csalatanya","state":"Heves"}'>Csalatanya</div>
<div class="option" data='{"value":"Csany","state":"Heves"}'>Csany</div>
<div class="option" data='{"value":"Csanyi Tanyak","state":"Heves"}'>Csanyi Tanyak</div>
<div class="option" data='{"value":"Csardamajor","state":"Heves"}'>Csardamajor</div>
<div class="option" data='{"value":"Csardatanya","state":"Heves"}'>Csardatanya</div>
<div class="option" data='{"value":"Cselohaza","state":"Heves"}'>Cselohaza</div>
<div class="option" data='{"value":"Csemetekert","state":"Heves"}'>Csemetekert</div>
<div class="option" data='{"value":"Cser","state":"Heves"}'>Cser</div>
<div class="option" data='{"value":"Cseritanya","state":"Heves"}'>Cseritanya</div>
<div class="option" data='{"value":"Csikojaras","state":"Heves"}'>Csikojaras</div>
<div class="option" data='{"value":"Csincsetanyak","state":"Heves"}'>Csincsetanyak</div>
<div class="option" data='{"value":"Csokaspuszta","state":"Heves"}'>Csokaspuszta</div>
<div class="option" data='{"value":"Csokastanya","state":"Heves"}'>Csokastanya</div>
<div class="option" data='{"value":"Csomorresztanya","state":"Heves"}'>Csomorresztanya</div>
<div class="option" data='{"value":"Csonkastanya","state":"Heves"}'>Csonkastanya</div>
<div class="option" data='{"value":"Csukas","state":"Heves"}'>Csukas</div>
<div class="option" data='{"value":"Csukasitanyak","state":"Heves"}'>Csukasitanyak</div>
<div class="option" data='{"value":"Csurgoitanyak","state":"Heves"}'>Csurgoitanyak</div>
<div class="option" data='{"value":"Cziglertanya","state":"Heves"}'>Cziglertanya</div>
<div class="option" data='{"value":"Darabkuttanya","state":"Heves"}'>Darabkuttanya</div>
<div class="option" data='{"value":"Darno","state":"Heves"}'>Darno</div>
<div class="option" data='{"value":"Delitanya","state":"Heves"}'>Delitanya</div>
<div class="option" data='{"value":"Demenytanya","state":"Heves"}'>Demenytanya</div>
<div class="option" data='{"value":"Demjen","state":"Heves"}'>Demjen</div>
<div class="option" data='{"value":"Detaly","state":"Heves"}'>Detaly</div>
<div class="option" data='{"value":"Detk","state":"Heves"}'>Detk</div>
<div class="option" data='{"value":"Dezsomajor","state":"Heves"}'>Dezsomajor</div>
<div class="option" data='{"value":"Dinnyeshat","state":"Heves"}'>Dinnyeshat</div>
<div class="option" data='{"value":"Dinnyeshatitanya","state":"Heves"}'>Dinnyeshatitanya</div>
<div class="option" data='{"value":"Dinyeshati Tanya","state":"Heves"}'>Dinyeshati Tanya</div>
<div class="option" data='{"value":"Dobogotanya","state":"Heves"}'>Dobogotanya</div>
<div class="option" data='{"value":"Dohanyszarito","state":"Heves"}'>Dohanyszarito</div>
<div class="option" data='{"value":"Domoszlo","state":"Heves"}'>Domoszlo</div>
<div class="option" data='{"value":"Dormand","state":"Heves"}'>Dormand</div>
<div class="option" data='{"value":"Duboczkydulo","state":"Heves"}'>Duboczkydulo</div>
<div class="option" data='{"value":"Ecsed","state":"Heves"}'>Ecsed</div>
<div class="option" data='{"value":"Egedidulo","state":"Heves"}'>Egedidulo</div>
<div class="option" data='{"value":"Eger","state":"Heves"}'>Eger</div>
<div class="option" data='{"value":"Egerbakta","state":"Heves"}'>Egerbakta</div>
<div class="option" data='{"value":"Egerbocs","state":"Heves"}'>Egerbocs</div>
<div class="option" data='{"value":"Egercsehi","state":"Heves"}'>Egercsehi</div>
<div class="option" data='{"value":"Egercsehi Banyatelep","state":"Heves"}'>Egercsehi Banyatelep</div>
<div class="option" data='{"value":"Egercsehi Koszenbanyatelep","state":"Heves"}'>Egercsehi Koszenbanyatelep</div>
<div class="option" data='{"value":"Egerfarmos","state":"Heves"}'>Egerfarmos</div>
<div class="option" data='{"value":"Egerszalok","state":"Heves"}'>Egerszalok</div>
<div class="option" data='{"value":"Egerszolat","state":"Heves"}'>Egerszolat</div>
<div class="option" data='{"value":"Egyhaztanya","state":"Heves"}'>Egyhaztanya</div>
<div class="option" data='{"value":"Elektanya","state":"Heves"}'>Elektanya</div>
<div class="option" data='{"value":"Encspuszta","state":"Heves"}'>Encspuszta</div>
<div class="option" data='{"value":"Englermalom","state":"Heves"}'>Englermalom</div>
<div class="option" data='{"value":"Erdokovesd","state":"Heves"}'>Erdokovesd</div>
<div class="option" data='{"value":"Erdotelek","state":"Heves"}'>Erdotelek</div>
<div class="option" data='{"value":"Erk","state":"Heves"}'>Erk</div>
<div class="option" data='{"value":"Erlau","state":"Heves"}'>Erlau</div>
<div class="option" data='{"value":"Eskerennatanya","state":"Heves"}'>Eskerennatanya</div>
<div class="option" data='{"value":"Fabianlakpuszta","state":"Heves"}'>Fabianlakpuszta</div>
<div class="option" data='{"value":"Facanyos","state":"Heves"}'>Facanyos</div>
<div class="option" data='{"value":"Faizat","state":"Heves"}'>Faizat</div>
<div class="option" data='{"value":"Fajcsaktanya","state":"Heves"}'>Fajcsaktanya</div>
<div class="option" data='{"value":"Fajzat","state":"Heves"}'>Fajzat</div>
<div class="option" data='{"value":"Falloskut","state":"Heves"}'>Falloskut</div>
<div class="option" data='{"value":"Falualjadulo","state":"Heves"}'>Falualjadulo</div>
<div class="option" data='{"value":"Faragotanya","state":"Heves"}'>Faragotanya</div>
<div class="option" data='{"value":"Faragotanyak","state":"Heves"}'>Faragotanyak</div>
<div class="option" data='{"value":"Farkasmajor","state":"Heves"}'>Farkasmajor</div>
<div class="option" data='{"value":"Farkasmaly","state":"Heves"}'>Farkasmaly</div>
<div class="option" data='{"value":"Farkastanya","state":"Heves"}'>Farkastanya</div>
<div class="option" data='{"value":"Fatelep","state":"Heves"}'>Fatelep</div>
<div class="option" data='{"value":"Fayfelsotanya","state":"Heves"}'>Fayfelsotanya</div>
<div class="option" data='{"value":"Fayszollo","state":"Heves"}'>Fayszollo</div>
<div class="option" data='{"value":"Fedemes","state":"Heves"}'>Fedemes</div>
<div class="option" data='{"value":"Feldebro","state":"Heves"}'>Feldebro</div>
<div class="option" data='{"value":"Felnemet","state":"Heves"}'>Felnemet</div>
<div class="option" data='{"value":"Felsohuta","state":"Heves"}'>Felsohuta</div>
<div class="option" data='{"value":"Felsonyiget","state":"Heves"}'>Felsonyiget</div>
<div class="option" data='{"value":"Felsorozsnakpuszta","state":"Heves"}'>Felsorozsnakpuszta</div>
<div class="option" data='{"value":"Felsorozsnakvolgy","state":"Heves"}'>Felsorozsnakvolgy</div>
<div class="option" data='{"value":"Felsotarkany","state":"Heves"}'>Felsotarkany</div>
<div class="option" data='{"value":"Fencel","state":"Heves"}'>Fencel</div>
<div class="option" data='{"value":"Fenekestanya","state":"Heves"}'>Fenekestanya</div>
<div class="option" data='{"value":"Fenyesipuszta","state":"Heves"}'>Fenyesipuszta</div>
<div class="option" data='{"value":"Fenyespuszta","state":"Heves"}'>Fenyespuszta</div>
<div class="option" data='{"value":"Ferencmajor","state":"Heves"}'>Ferencmajor</div>
<div class="option" data='{"value":"Feszer","state":"Heves"}'>Feszer</div>
<div class="option" data='{"value":"Fiskalitashuta","state":"Heves"}'>Fiskalitashuta</div>
<div class="option" data='{"value":"Fodortanya","state":"Heves"}'>Fodortanya</div>
<div class="option" data='{"value":"Fodortanyak","state":"Heves"}'>Fodortanyak</div>
<div class="option" data='{"value":"Foldestanya","state":"Heves"}'>Foldestanya</div>
<div class="option" data='{"value":"Fuzesabony","state":"Heves"}'>Fuzesabony</div>
<div class="option" data='{"value":"Galambostanya","state":"Heves"}'>Galambostanya</div>
<div class="option" data='{"value":"Galtanya","state":"Heves"}'>Galtanya</div>
<div class="option" data='{"value":"Galyateto","state":"Heves"}'>Galyateto</div>
<div class="option" data='{"value":"Gardonyitanya","state":"Heves"}'>Gardonyitanya</div>
<div class="option" data='{"value":"Gereg","state":"Heves"}'>Gereg</div>
<div class="option" data='{"value":"Geregitanyak","state":"Heves"}'>Geregitanyak</div>
<div class="option" data='{"value":"Geregtanya","state":"Heves"}'>Geregtanya</div>
<div class="option" data='{"value":"Gergelytelep","state":"Heves"}'>Gergelytelep</div>
<div class="option" data='{"value":"Gilitkapuszta","state":"Heves"}'>Gilitkapuszta</div>
<div class="option" data='{"value":"Gizellatelep","state":"Heves"}'>Gizellatelep</div>
<div class="option" data='{"value":"Golyatanya","state":"Heves"}'>Golyatanya</div>
<div class="option" data='{"value":"Gorbeer","state":"Heves"}'>Gorbeer</div>
<div class="option" data='{"value":"Gorcsvolgy","state":"Heves"}'>Gorcsvolgy</div>
<div class="option" data='{"value":"Gosztonyimajor","state":"Heves"}'>Gosztonyimajor</div>
<div class="option" data='{"value":"Gosztonyitanya","state":"Heves"}'>Gosztonyitanya</div>
<div class="option" data='{"value":"Gubatanya","state":"Heves"}'>Gubatanya</div>
<div class="option" data='{"value":"Gulyastanya","state":"Heves"}'>Gulyastanya</div>
<div class="option" data='{"value":"Gyepestanya","state":"Heves"}'>Gyepestanya</div>
<div class="option" data='{"value":"Gyongyos","state":"Heves"}'>Gyongyos</div>
<div class="option" data='{"value":"Gyongyoshalasz","state":"Heves"}'>Gyongyoshalasz</div>
<div class="option" data='{"value":"Gyongyoshalaszi Tanyak","state":"Heves"}'>Gyongyoshalaszi Tanyak</div>
<div class="option" data='{"value":"Gyongyoshalmaj","state":"Heves"}'>Gyongyoshalmaj</div>
<div class="option" data='{"value":"Gyongyosoroszi","state":"Heves"}'>Gyongyosoroszi</div>
<div class="option" data='{"value":"Gyongyospata","state":"Heves"}'>Gyongyospata</div>
<div class="option" data='{"value":"Gyongyossolymos","state":"Heves"}'>Gyongyossolymos</div>
<div class="option" data='{"value":"Gyongyostarjan","state":"Heves"}'>Gyongyostarjan</div>
<div class="option" data='{"value":"Gyonitanya","state":"Heves"}'>Gyonitanya</div>
<div class="option" data='{"value":"Gyorffytanya","state":"Heves"}'>Gyorffytanya</div>
<div class="option" data='{"value":"Gyorkitanya","state":"Heves"}'>Gyorkitanya</div>
<div class="option" data='{"value":"Gyorknanya","state":"Heves"}'>Gyorknanya</div>
<div class="option" data='{"value":"Gyulamajor","state":"Heves"}'>Gyulamajor</div>
<div class="option" data='{"value":"Hagymaspuszta","state":"Heves"}'>Hagymaspuszta</div>
<div class="option" data='{"value":"Hajduhegy","state":"Heves"}'>Hajduhegy</div>
<div class="option" data='{"value":"Hajduhegydulo","state":"Heves"}'>Hajduhegydulo</div>
<div class="option" data='{"value":"Halaszopuszta","state":"Heves"}'>Halaszopuszta</div>
<div class="option" data='{"value":"Halaszotanya","state":"Heves"}'>Halaszotanya</div>
<div class="option" data='{"value":"Halasztanya","state":"Heves"}'>Halasztanya</div>
<div class="option" data='{"value":"Halmajtanyak","state":"Heves"}'>Halmajtanyak</div>
<div class="option" data='{"value":"Halmajugra","state":"Heves"}'>Halmajugra</div>
<div class="option" data='{"value":"Hanyipuszta","state":"Heves"}'>Hanyipuszta</div>
<div class="option" data='{"value":"Harmastanyak","state":"Heves"}'>Harmastanyak</div>
<div class="option" data='{"value":"Haromhanyas","state":"Heves"}'>Haromhanyas</div>
<div class="option" data='{"value":"Haromhanyastanya","state":"Heves"}'>Haromhanyastanya</div>
<div class="option" data='{"value":"Harsaserdeszlak","state":"Heves"}'>Harsaserdeszlak</div>
<div class="option" data='{"value":"Harsasi Erdeszlak","state":"Heves"}'>Harsasi Erdeszlak</div>
<div class="option" data='{"value":"Hathaz","state":"Heves"}'>Hathaz</div>
<div class="option" data='{"value":"Hathazpuszta","state":"Heves"}'>Hathazpuszta</div>
<div class="option" data='{"value":"Hatrongyos","state":"Heves"}'>Hatrongyos</div>
<div class="option" data='{"value":"Hatvan","state":"Heves"}'>Hatvan</div>
<div class="option" data='{"value":"Hegedostanya","state":"Heves"}'>Hegedostanya</div>
<div class="option" data='{"value":"Hegedustanya","state":"Heves"}'>Hegedustanya</div>
<div class="option" data='{"value":"Hegymegettipuszta","state":"Heves"}'>Hegymegettipuszta</div>
<div class="option" data='{"value":"Hegymegpuszta","state":"Heves"}'>Hegymegpuszta</div>
<div class="option" data='{"value":"Hercegtag","state":"Heves"}'>Hercegtag</div>
<div class="option" data='{"value":"Hered","state":"Heves"}'>Hered</div>
<div class="option" data='{"value":"Herketytanya","state":"Heves"}'>Herketytanya</div>
<div class="option" data='{"value":"Heves","state":"Heves"}'>Heves</div>
<div class="option" data='{"value":"Heves County","state":"Heves"}'>Heves County</div>
<div class="option" data='{"value":"Heves Megye","state":"Heves"}'>Heves Megye</div>
<div class="option" data='{"value":"Hevesaranyos","state":"Heves"}'>Hevesaranyos</div>
<div class="option" data='{"value":"Hevesioldali Tanyak","state":"Heves"}'>Hevesioldali Tanyak</div>
<div class="option" data='{"value":"Hevesugra","state":"Heves"}'>Hevesugra</div>
<div class="option" data='{"value":"Hevesvezekeny","state":"Heves"}'>Hevesvezekeny</div>
<div class="option" data='{"value":"Hevesvezekenyi Tanyak","state":"Heves"}'>Hevesvezekenyi Tanyak</div>
<div class="option" data='{"value":"Hidas","state":"Heves"}'>Hidas</div>
<div class="option" data='{"value":"Hidegkut","state":"Heves"}'>Hidegkut</div>
<div class="option" data='{"value":"Hidegkuttanya","state":"Heves"}'>Hidegkuttanya</div>
<div class="option" data='{"value":"Homok","state":"Heves"}'>Homok</div>
<div class="option" data='{"value":"Hort","state":"Heves"}'>Hort</div>
<div class="option" data='{"value":"Hortolanyipuszta","state":"Heves"}'>Hortolanyipuszta</div>
<div class="option" data='{"value":"Horvathtanya","state":"Heves"}'>Horvathtanya</div>
<div class="option" data='{"value":"Horvattanya","state":"Heves"}'>Horvattanya</div>
<div class="option" data='{"value":"Hosszuveroipuszta","state":"Heves"}'>Hosszuveroipuszta</div>
<div class="option" data='{"value":"Hosszuveropuszta","state":"Heves"}'>Hosszuveropuszta</div>
<div class="option" data='{"value":"Igondatanya","state":"Heves"}'>Igondatanya</div>
<div class="option" data='{"value":"Ilatanya","state":"Heves"}'>Ilatanya</div>
<div class="option" data='{"value":"Irmatanya","state":"Heves"}'>Irmatanya</div>
<div class="option" data='{"value":"Istenmezeje","state":"Heves"}'>Istenmezeje</div>
<div class="option" data='{"value":"Istvantanya","state":"Heves"}'>Istvantanya</div>
<div class="option" data='{"value":"Ivad","state":"Heves"}'>Ivad</div>
<div class="option" data='{"value":"Jaczotanya","state":"Heves"}'>Jaczotanya</div>
<div class="option" data='{"value":"Jager","state":"Heves"}'>Jager</div>
<div class="option" data='{"value":"Jakabdomb","state":"Heves"}'>Jakabdomb</div>
<div class="option" data='{"value":"Jakabdombitanya","state":"Heves"}'>Jakabdombitanya</div>
<div class="option" data='{"value":"Jambor","state":"Heves"}'>Jambor</div>
<div class="option" data='{"value":"Janositanya","state":"Heves"}'>Janositanya</div>
<div class="option" data='{"value":"Jarasi Szeretethaz","state":"Heves"}'>Jarasi Szeretethaz</div>
<div class="option" data='{"value":"Jardantanya","state":"Heves"}'>Jardantanya</div>
<div class="option" data='{"value":"Jokuttanya","state":"Heves"}'>Jokuttanya</div>
<div class="option" data='{"value":"Jozseftanya","state":"Heves"}'>Jozseftanya</div>
<div class="option" data='{"value":"Juhasztanya","state":"Heves"}'>Juhasztanya</div>
<div class="option" data='{"value":"Kabelhaz","state":"Heves"}'>Kabelhaz</div>
<div class="option" data='{"value":"Kabeltelep","state":"Heves"}'>Kabeltelep</div>
<div class="option" data='{"value":"Kal","state":"Heves"}'>Kal</div>
<div class="option" data='{"value":"Kali Tanyak","state":"Heves"}'>Kali Tanyak</div>
<div class="option" data='{"value":"Kalitag","state":"Heves"}'>Kalitag</div>
<div class="option" data='{"value":"Kallaitelep","state":"Heves"}'>Kallaitelep</div>
<div class="option" data='{"value":"Kallomalom","state":"Heves"}'>Kallomalom</div>
<div class="option" data='{"value":"Kalmantanya","state":"Heves"}'>Kalmantanya</div>
<div class="option" data='{"value":"Kamaravolgyi Tanyak","state":"Heves"}'>Kamaravolgyi Tanyak</div>
<div class="option" data='{"value":"Kanyar","state":"Heves"}'>Kanyar</div>
<div class="option" data='{"value":"Kapitanyhegy","state":"Heves"}'>Kapitanyhegy</div>
<div class="option" data='{"value":"Kapolna","state":"Heves"}'>Kapolna</div>
<div class="option" data='{"value":"Karacsond","state":"Heves"}'>Karacsond</div>
<div class="option" data='{"value":"Karolyvar","state":"Heves"}'>Karolyvar</div>
<div class="option" data='{"value":"Kekesteto","state":"Heves"}'>Kekesteto</div>
<div class="option" data='{"value":"Kenyerestanya","state":"Heves"}'>Kenyerestanya</div>
<div class="option" data='{"value":"Kenyervar","state":"Heves"}'>Kenyervar</div>
<div class="option" data='{"value":"Kenyervar Uti Tanyak","state":"Heves"}'>Kenyervar Uti Tanyak</div>
<div class="option" data='{"value":"Kepesfold","state":"Heves"}'>Kepesfold</div>
<div class="option" data='{"value":"Kerecsend","state":"Heves"}'>Kerecsend</div>
<div class="option" data='{"value":"Kerekharaszt","state":"Heves"}'>Kerekharaszt</div>
<div class="option" data='{"value":"Kertaljadulo","state":"Heves"}'>Kertaljadulo</div>
<div class="option" data='{"value":"Ket Ut Koz","state":"Heves"}'>Ket Ut Koz</div>
<div class="option" data='{"value":"Kettoscsarda","state":"Heves"}'>Kettoscsarda</div>
<div class="option" data='{"value":"Kis Hercegtag","state":"Heves"}'>Kis Hercegtag</div>
<div class="option" data='{"value":"Kisasszonyter","state":"Heves"}'>Kisasszonyter</div>
<div class="option" data='{"value":"Kisbator","state":"Heves"}'>Kisbator</div>
<div class="option" data='{"value":"Kisbatortanya","state":"Heves"}'>Kisbatortanya</div>
<div class="option" data='{"value":"Kisciner","state":"Heves"}'>Kisciner</div>
<div class="option" data='{"value":"Kisdomb","state":"Heves"}'>Kisdomb</div>
<div class="option" data='{"value":"Kisebbtanya","state":"Heves"}'>Kisebbtanya</div>
<div class="option" data='{"value":"Kisecser","state":"Heves"}'>Kisecser</div>
<div class="option" data='{"value":"Kisfuzes","state":"Heves"}'>Kisfuzes</div>
<div class="option" data='{"value":"Kisgombos","state":"Heves"}'>Kisgombos</div>
<div class="option" data='{"value":"Kiskore","state":"Heves"}'>Kiskore</div>
<div class="option" data='{"value":"Kisnadas","state":"Heves"}'>Kisnadas</div>
<div class="option" data='{"value":"Kisnana","state":"Heves"}'>Kisnana</div>
<div class="option" data='{"value":"Kistanya","state":"Heves"}'>Kistanya</div>
<div class="option" data='{"value":"Kistelek","state":"Heves"}'>Kistelek</div>
<div class="option" data='{"value":"Kistelep","state":"Heves"}'>Kistelep</div>
<div class="option" data='{"value":"Kisvartanya","state":"Heves"}'>Kisvartanya</div>
<div class="option" data='{"value":"Kivestanya","state":"Heves"}'>Kivestanya</div>
<div class="option" data='{"value":"Kocsistanya","state":"Heves"}'>Kocsistanya</div>
<div class="option" data='{"value":"Kocspuszta","state":"Heves"}'>Kocspuszta</div>
<div class="option" data='{"value":"Kokutpuszta","state":"Heves"}'>Kokutpuszta</div>
<div class="option" data='{"value":"Kolyukteto","state":"Heves"}'>Kolyukteto</div>
<div class="option" data='{"value":"Komlo","state":"Heves"}'>Komlo</div>
<div class="option" data='{"value":"Komoplt","state":"Heves"}'>Komoplt</div>
<div class="option" data='{"value":"Kompolt","state":"Heves"}'>Kompolt</div>
<div class="option" data='{"value":"Konctanya","state":"Heves"}'>Konctanya</div>
<div class="option" data='{"value":"Koporos","state":"Heves"}'>Koporos</div>
<div class="option" data='{"value":"Koros","state":"Heves"}'>Koros</div>
<div class="option" data='{"value":"Korospuszta","state":"Heves"}'>Korospuszta</div>
<div class="option" data='{"value":"Kortvelyes","state":"Heves"}'>Kortvelyes</div>
<div class="option" data='{"value":"Kortvelyesdulo","state":"Heves"}'>Kortvelyesdulo</div>
<div class="option" data='{"value":"Kovacsoczytanya","state":"Heves"}'>Kovacsoczytanya</div>
<div class="option" data='{"value":"Kovacstanya","state":"Heves"}'>Kovacstanya</div>
<div class="option" data='{"value":"Kovago","state":"Heves"}'>Kovago</div>
<div class="option" data='{"value":"Kozepsojaras","state":"Heves"}'>Kozepsojaras</div>
<div class="option" data='{"value":"Kozepsotanya","state":"Heves"}'>Kozepsotanya</div>
<div class="option" data='{"value":"Kozmaritanya","state":"Heves"}'>Kozmaritanya</div>
<div class="option" data='{"value":"Kozsegi Tanya","state":"Heves"}'>Kozsegi Tanya</div>
<div class="option" data='{"value":"Kulcsartanya","state":"Heves"}'>Kulcsartanya</div>
<div class="option" data='{"value":"Kulsojegestelep","state":"Heves"}'>Kulsojegestelep</div>
<div class="option" data='{"value":"Kulsopusztadalla","state":"Heves"}'>Kulsopusztadalla</div>
<div class="option" data='{"value":"Kulsoretdulo","state":"Heves"}'>Kulsoretdulo</div>
<div class="option" data='{"value":"Kuntanya","state":"Heves"}'>Kuntanya</div>
<div class="option" data='{"value":"Kutaspuszta","state":"Heves"}'>Kutaspuszta</div>
<div class="option" data='{"value":"Kutos","state":"Heves"}'>Kutos</div>
<div class="option" data='{"value":"Kutospuszta","state":"Heves"}'>Kutospuszta</div>
<div class="option" data='{"value":"Kutostanya","state":"Heves"}'>Kutostanya</div>
<div class="option" data='{"value":"Kutvolgy","state":"Heves"}'>Kutvolgy</div>
<div class="option" data='{"value":"Lakipuszta","state":"Heves"}'>Lakipuszta</div>
<div class="option" data='{"value":"Laubtanya","state":"Heves"}'>Laubtanya</div>
<div class="option" data='{"value":"Legenytanya","state":"Heves"}'>Legenytanya</div>
<div class="option" data='{"value":"Lengyeltanya","state":"Heves"}'>Lengyeltanya</div>
<div class="option" data='{"value":"Liszko","state":"Heves"}'>Liszko</div>
<div class="option" data='{"value":"Liszkomalom","state":"Heves"}'>Liszkomalom</div>
<div class="option" data='{"value":"Lorinci","state":"Heves"}'>Lorinci</div>
<div class="option" data='{"value":"Lotertanya","state":"Heves"}'>Lotertanya</div>
<div class="option" data='{"value":"Ludas","state":"Heves"}'>Ludas</div>
<div class="option" data='{"value":"Ludasdulo","state":"Heves"}'>Ludasdulo</div>
<div class="option" data='{"value":"Ludastanya","state":"Heves"}'>Ludastanya</div>
<div class="option" data='{"value":"Lyukva","state":"Heves"}'>Lyukva</div>
<div class="option" data='{"value":"Lyukvapuszta","state":"Heves"}'>Lyukvapuszta</div>
<div class="option" data='{"value":"Maczkytag","state":"Heves"}'>Maczkytag</div>
<div class="option" data='{"value":"Magashegy","state":"Heves"}'>Magashegy</div>
<div class="option" data='{"value":"Majkapuszta","state":"Heves"}'>Majkapuszta</div>
<div class="option" data='{"value":"Makaytanya","state":"Heves"}'>Makaytanya</div>
<div class="option" data='{"value":"Makkosdulo","state":"Heves"}'>Makkosdulo</div>
<div class="option" data='{"value":"Maklany","state":"Heves"}'>Maklany</div>
<div class="option" data='{"value":"Maklar","state":"Heves"}'>Maklar</div>
<div class="option" data='{"value":"Maklartalya","state":"Heves"}'>Maklartalya</div>
<div class="option" data='{"value":"Maksatanya","state":"Heves"}'>Maksatanya</div>
<div class="option" data='{"value":"Mallerd Fatelep","state":"Heves"}'>Mallerd Fatelep</div>
<div class="option" data='{"value":"Malomhegytanya","state":"Heves"}'>Malomhegytanya</div>
<div class="option" data='{"value":"Malomitanya","state":"Heves"}'>Malomitanya</div>
<div class="option" data='{"value":"Mariadulo","state":"Heves"}'>Mariadulo</div>
<div class="option" data='{"value":"Markaz","state":"Heves"}'>Markaz</div>
<div class="option" data='{"value":"Markustanya","state":"Heves"}'>Markustanya</div>
<div class="option" data='{"value":"Maspataka","state":"Heves"}'>Maspataka</div>
<div class="option" data='{"value":"Matraaranybanyahaz","state":"Heves"}'>Matraaranybanyahaz</div>
<div class="option" data='{"value":"Matraballa","state":"Heves"}'>Matraballa</div>
<div class="option" data='{"value":"Matrabanya","state":"Heves"}'>Matrabanya</div>
<div class="option" data='{"value":"Matraderecske","state":"Heves"}'>Matraderecske</div>
<div class="option" data='{"value":"Matraeromutelep","state":"Heves"}'>Matraeromutelep</div>
<div class="option" data='{"value":"Matrafured","state":"Heves"}'>Matrafured</div>
<div class="option" data='{"value":"Matrahaza","state":"Heves"}'>Matrahaza</div>
<div class="option" data='{"value":"Matraitanya","state":"Heves"}'>Matraitanya</div>
<div class="option" data='{"value":"Matrakeresztesi Tanya","state":"Heves"}'>Matrakeresztesi Tanya</div>
<div class="option" data='{"value":"Matraszentimre","state":"Heves"}'>Matraszentimre</div>
<div class="option" data='{"value":"Matraszentistvan","state":"Heves"}'>Matraszentistvan</div>
<div class="option" data='{"value":"Matraszentlaszlo","state":"Heves"}'>Matraszentlaszlo</div>
<div class="option" data='{"value":"Matravezekeny","state":"Heves"}'>Matravezekeny</div>
<div class="option" data='{"value":"Matravidek","state":"Heves"}'>Matravidek</div>
<div class="option" data='{"value":"Matravideki Eromutelep","state":"Heves"}'>Matravideki Eromutelep</div>
<div class="option" data='{"value":"Medvetanya","state":"Heves"}'>Medvetanya</div>
<div class="option" data='{"value":"Mesztelep","state":"Heves"}'>Mesztelep</div>
<div class="option" data='{"value":"Mezenyo","state":"Heves"}'>Mezenyo</div>
<div class="option" data='{"value":"Mezeytag","state":"Heves"}'>Mezeytag</div>
<div class="option" data='{"value":"Mezoszemere","state":"Heves"}'>Mezoszemere</div>
<div class="option" data='{"value":"Mezotarkany","state":"Heves"}'>Mezotarkany</div>
<div class="option" data='{"value":"Mihalytanya","state":"Heves"}'>Mihalytanya</div>
<div class="option" data='{"value":"Miklostanya","state":"Heves"}'>Miklostanya</div>
<div class="option" data='{"value":"Mikofalva","state":"Heves"}'>Mikofalva</div>
<div class="option" data='{"value":"Minketanya","state":"Heves"}'>Minketanya</div>
<div class="option" data='{"value":"Miskepuszta","state":"Heves"}'>Miskepuszta</div>
<div class="option" data='{"value":"Misketanyak","state":"Heves"}'>Misketanyak</div>
<div class="option" data='{"value":"Mocsarositanya","state":"Heves"}'>Mocsarositanya</div>
<div class="option" data='{"value":"Mocsarytanya","state":"Heves"}'>Mocsarytanya</div>
<div class="option" data='{"value":"Moczartanya","state":"Heves"}'>Moczartanya</div>
<div class="option" data='{"value":"Molnartanya","state":"Heves"}'>Molnartanya</div>
<div class="option" data='{"value":"Monosbel","state":"Heves"}'>Monosbel</div>
<div class="option" data='{"value":"Monostordombi Tanya","state":"Heves"}'>Monostordombi Tanya</div>
<div class="option" data='{"value":"Nagy Hercegtag","state":"Heves"}'>Nagy Hercegtag</div>
<div class="option" data='{"value":"Nagyallasitanyak","state":"Heves"}'>Nagyallasitanyak</div>
<div class="option" data='{"value":"Nagyeged","state":"Heves"}'>Nagyeged</div>
<div class="option" data='{"value":"Nagyegeddulo","state":"Heves"}'>Nagyegeddulo</div>
<div class="option" data='{"value":"Nagyfuged","state":"Heves"}'>Nagyfuged</div>
<div class="option" data='{"value":"Nagyfugedi Tanyak","state":"Heves"}'>Nagyfugedi Tanyak</div>
<div class="option" data='{"value":"Nagygombos","state":"Heves"}'>Nagygombos</div>
<div class="option" data='{"value":"Nagyharmas","state":"Heves"}'>Nagyharmas</div>
<div class="option" data='{"value":"Nagyharmasitanya","state":"Heves"}'>Nagyharmasitanya</div>
<div class="option" data='{"value":"Nagykocs","state":"Heves"}'>Nagykocs</div>
<div class="option" data='{"value":"Nagykokenyes","state":"Heves"}'>Nagykokenyes</div>
<div class="option" data='{"value":"Nagyparlag","state":"Heves"}'>Nagyparlag</div>
<div class="option" data='{"value":"Nagyrede","state":"Heves"}'>Nagyrede</div>
<div class="option" data='{"value":"Nagyszollotanya","state":"Heves"}'>Nagyszollotanya</div>
<div class="option" data='{"value":"Nagytalya","state":"Heves"}'>Nagytalya</div>
<div class="option" data='{"value":"Nagytamota","state":"Heves"}'>Nagytamota</div>
<div class="option" data='{"value":"Nagytelek","state":"Heves"}'>Nagytelek</div>
<div class="option" data='{"value":"Nagytemplomilak","state":"Heves"}'>Nagytemplomilak</div>
<div class="option" data='{"value":"Nagyut","state":"Heves"}'>Nagyut</div>
<div class="option" data='{"value":"Nagyvisnyo","state":"Heves"}'>Nagyvisnyo</div>
<div class="option" data='{"value":"Nagyvolgy","state":"Heves"}'>Nagyvolgy</div>
<div class="option" data='{"value":"Negyesszollotelep","state":"Heves"}'>Negyesszollotelep</div>
<div class="option" data='{"value":"Negyestelep","state":"Heves"}'>Negyestelep</div>
<div class="option" data='{"value":"Noszvaj","state":"Heves"}'>Noszvaj</div>
<div class="option" data='{"value":"Novaj","state":"Heves"}'>Novaj</div>
<div class="option" data='{"value":"Nyirjes","state":"Heves"}'>Nyirjes</div>
<div class="option" data='{"value":"Nyirjespuszta","state":"Heves"}'>Nyirjespuszta</div>
<div class="option" data='{"value":"Nyirjestanya","state":"Heves"}'>Nyirjestanya</div>
<div class="option" data='{"value":"Nyulasszollo","state":"Heves"}'>Nyulasszollo</div>
<div class="option" data='{"value":"Ocskaitanya","state":"Heves"}'>Ocskaitanya</div>
<div class="option" data='{"value":"Ohalasz","state":"Heves"}'>Ohalasz</div>
<div class="option" data='{"value":"Olgamajor","state":"Heves"}'>Olgamajor</div>
<div class="option" data='{"value":"Ordogfalva","state":"Heves"}'>Ordogfalva</div>
<div class="option" data='{"value":"Orszaguti Tanyak","state":"Heves"}'>Orszaguti Tanyak</div>
<div class="option" data='{"value":"Ostoros","state":"Heves"}'>Ostoros</div>
<div class="option" data='{"value":"Otodresz","state":"Heves"}'>Otodresz</div>
<div class="option" data='{"value":"Otodreszidulo","state":"Heves"}'>Otodreszidulo</div>
<div class="option" data='{"value":"Otodresziszolo","state":"Heves"}'>Otodresziszolo</div>
<div class="option" data='{"value":"Ozsetanya","state":"Heves"}'>Ozsetanya</div>
<div class="option" data='{"value":"Padartanya","state":"Heves"}'>Padartanya</div>
<div class="option" data='{"value":"Palosvorosmart","state":"Heves"}'>Palosvorosmart</div>
<div class="option" data='{"value":"Pampuktelep","state":"Heves"}'>Pampuktelep</div>
<div class="option" data='{"value":"Paptanya","state":"Heves"}'>Paptanya</div>
<div class="option" data='{"value":"Parad","state":"Heves"}'>Parad</div>
<div class="option" data='{"value":"Paradfurdo","state":"Heves"}'>Paradfurdo</div>
<div class="option" data='{"value":"Paradi Tanyak","state":"Heves"}'>Paradi Tanyak</div>
<div class="option" data='{"value":"Paradohuta","state":"Heves"}'>Paradohuta</div>
<div class="option" data='{"value":"Paradsasvar","state":"Heves"}'>Paradsasvar</div>
<div class="option" data='{"value":"Patak","state":"Heves"}'>Patak</div>
<div class="option" data='{"value":"Pely","state":"Heves"}'>Pely</div>
<div class="option" data='{"value":"Pelyhatari Tanyak","state":"Heves"}'>Pelyhatari Tanyak</div>
<div class="option" data='{"value":"Peres","state":"Heves"}'>Peres</div>
<div class="option" data='{"value":"Perespuszta","state":"Heves"}'>Perespuszta</div>
<div class="option" data='{"value":"Petervasara","state":"Heves"}'>Petervasara</div>
<div class="option" data='{"value":"Petofi Banyatelep","state":"Heves"}'>Petofi Banyatelep</div>
<div class="option" data='{"value":"Petofibanya","state":"Heves"}'>Petofibanya</div>
<div class="option" data='{"value":"Poroszlo","state":"Heves"}'>Poroszlo</div>
<div class="option" data='{"value":"Prisztokatanya","state":"Heves"}'>Prisztokatanya</div>
<div class="option" data='{"value":"Pusztabab","state":"Heves"}'>Pusztabab</div>
<div class="option" data='{"value":"Pusztacsasz","state":"Heves"}'>Pusztacsasz</div>
<div class="option" data='{"value":"Pusztacsikojaras","state":"Heves"}'>Pusztacsikojaras</div>
<div class="option" data='{"value":"Pusztafajzat","state":"Heves"}'>Pusztafajzat</div>
<div class="option" data='{"value":"Pusztafogacs","state":"Heves"}'>Pusztafogacs</div>
<div class="option" data='{"value":"Pusztahanyi","state":"Heves"}'>Pusztahanyi</div>
<div class="option" data='{"value":"Pusztahatrongyos","state":"Heves"}'>Pusztahatrongyos</div>
<div class="option" data='{"value":"Pusztakishatrongyos","state":"Heves"}'>Pusztakishatrongyos</div>
<div class="option" data='{"value":"Pusztakokut","state":"Heves"}'>Pusztakokut</div>
<div class="option" data='{"value":"Pusztaordogfalva","state":"Heves"}'>Pusztaordogfalva</div>
<div class="option" data='{"value":"Pusztaraboly","state":"Heves"}'>Pusztaraboly</div>
<div class="option" data='{"value":"Pusztarozsnakfo","state":"Heves"}'>Pusztarozsnakfo</div>
<div class="option" data='{"value":"Pusztaszikszo","state":"Heves"}'>Pusztaszikszo</div>
<div class="option" data='{"value":"Pusztatenk","state":"Heves"}'>Pusztatenk</div>
<div class="option" data='{"value":"Rabcatanya","state":"Heves"}'>Rabcatanya</div>
<div class="option" data='{"value":"Rabolymajor","state":"Heves"}'>Rabolymajor</div>
<div class="option" data='{"value":"Rakhat","state":"Heves"}'>Rakhat</div>
<div class="option" data='{"value":"Rakostanya","state":"Heves"}'>Rakostanya</div>
<div class="option" data='{"value":"Recsk","state":"Heves"}'>Recsk</div>
<div class="option" data='{"value":"Redeitanya","state":"Heves"}'>Redeitanya</div>
<div class="option" data='{"value":"Redeytanya","state":"Heves"}'>Redeytanya</div>
<div class="option" data='{"value":"Remenyiktanya","state":"Heves"}'>Remenyiktanya</div>
<div class="option" data='{"value":"Repavolgypuszta","state":"Heves"}'>Repavolgypuszta</div>
<div class="option" data='{"value":"Retdulo","state":"Heves"}'>Retdulo</div>
<div class="option" data='{"value":"Ringtanya","state":"Heves"}'>Ringtanya</div>
<div class="option" data='{"value":"Rizskasa","state":"Heves"}'>Rizskasa</div>
<div class="option" data='{"value":"Rizskasamalom","state":"Heves"}'>Rizskasamalom</div>
<div class="option" data='{"value":"Rogtontanya","state":"Heves"}'>Rogtontanya</div>
<div class="option" data='{"value":"Rokalyukdulo","state":"Heves"}'>Rokalyukdulo</div>
<div class="option" data='{"value":"Ronalapa","state":"Heves"}'>Ronalapa</div>
<div class="option" data='{"value":"Ronalapatanya","state":"Heves"}'>Ronalapatanya</div>
<div class="option" data='{"value":"Rozsahegy","state":"Heves"}'>Rozsahegy</div>
<div class="option" data='{"value":"Rozsas","state":"Heves"}'>Rozsas</div>
<div class="option" data='{"value":"Rozsastanya","state":"Heves"}'>Rozsastanya</div>
<div class="option" data='{"value":"Rozsaszentmarton","state":"Heves"}'>Rozsaszentmarton</div>
<div class="option" data='{"value":"Rudolftanya","state":"Heves"}'>Rudolftanya</div>
<div class="option" data='{"value":"Ruzsintanya","state":"Heves"}'>Ruzsintanya</div>
<div class="option" data='{"value":"Safariszollo","state":"Heves"}'>Safariszollo</div>
<div class="option" data='{"value":"Safaryszollo","state":"Heves"}'>Safaryszollo</div>
<div class="option" data='{"value":"Sandorret","state":"Heves"}'>Sandorret</div>
<div class="option" data='{"value":"Sandorreti Puszta","state":"Heves"}'>Sandorreti Puszta</div>
<div class="option" data='{"value":"Sandorretpuszta","state":"Heves"}'>Sandorretpuszta</div>
<div class="option" data='{"value":"Sandortanya","state":"Heves"}'>Sandortanya</div>
<div class="option" data='{"value":"Sarga","state":"Heves"}'>Sarga</div>
<div class="option" data='{"value":"Sargapuszta","state":"Heves"}'>Sargapuszta</div>
<div class="option" data='{"value":"Sarud","state":"Heves"}'>Sarud</div>
<div class="option" data='{"value":"Sashalom","state":"Heves"}'>Sashalom</div>
<div class="option" data='{"value":"Schwarctelep","state":"Heves"}'>Schwarctelep</div>
<div class="option" data='{"value":"Schwartztanya","state":"Heves"}'>Schwartztanya</div>
<div class="option" data='{"value":"Selyp","state":"Heves"}'>Selyp</div>
<div class="option" data='{"value":"Selypicukorgyar","state":"Heves"}'>Selypicukorgyar</div>
<div class="option" data='{"value":"Semjentelep","state":"Heves"}'>Semjentelep</div>
<div class="option" data='{"value":"Sirok","state":"Heves"}'>Sirok</div>
<div class="option" data='{"value":"Sisa","state":"Heves"}'>Sisa</div>
<div class="option" data='{"value":"Sosi Ret","state":"Heves"}'>Sosi Ret</div>
<div class="option" data='{"value":"Sosret","state":"Heves"}'>Sosret</div>
<div class="option" data='{"value":"Sosrev","state":"Heves"}'>Sosrev</div>
<div class="option" data='{"value":"Sosrevpuszta","state":"Heves"}'>Sosrevpuszta</div>
<div class="option" data='{"value":"Suranyitanya","state":"Heves"}'>Suranyitanya</div>
<div class="option" data='{"value":"Szabotanya","state":"Heves"}'>Szabotanya</div>
<div class="option" data='{"value":"Szajla","state":"Heves"}'>Szajla</div>
<div class="option" data='{"value":"Szalaitanya","state":"Heves"}'>Szalaitanya</div>
<div class="option" data='{"value":"Szalajkahaz","state":"Heves"}'>Szalajkahaz</div>
<div class="option" data='{"value":"Szalajkahaztanya","state":"Heves"}'>Szalajkahaztanya</div>
<div class="option" data='{"value":"Szalajkavolgy","state":"Heves"}'>Szalajkavolgy</div>
<div class="option" data='{"value":"Szalkaitanya","state":"Heves"}'>Szalkaitanya</div>
<div class="option" data='{"value":"Szantotelep","state":"Heves"}'>Szantotelep</div>
<div class="option" data='{"value":"Szarkas","state":"Heves"}'>Szarkas</div>
<div class="option" data='{"value":"Szarvasko","state":"Heves"}'>Szarvasko</div>
<div class="option" data='{"value":"Szederjespuszta","state":"Heves"}'>Szederjespuszta</div>
<div class="option" data='{"value":"Szederjestanya","state":"Heves"}'>Szederjestanya</div>
<div class="option" data='{"value":"Szederkenypuszta","state":"Heves"}'>Szederkenypuszta</div>
<div class="option" data='{"value":"Szelestanya","state":"Heves"}'>Szelestanya</div>
<div class="option" data='{"value":"Szentdomonkos","state":"Heves"}'>Szentdomonkos</div>
<div class="option" data='{"value":"Szentgyorgytelep","state":"Heves"}'>Szentgyorgytelep</div>
<div class="option" data='{"value":"Szerelemtag","state":"Heves"}'>Szerelemtag</div>
<div class="option" data='{"value":"Szihalom","state":"Heves"}'>Szihalom</div>
<div class="option" data='{"value":"Sziklaforras","state":"Heves"}'>Sziklaforras</div>
<div class="option" data='{"value":"Szikratanya","state":"Heves"}'>Szikratanya</div>
<div class="option" data='{"value":"Szikszo","state":"Heves"}'>Szikszo</div>
<div class="option" data='{"value":"Szilapos","state":"Heves"}'>Szilapos</div>
<div class="option" data='{"value":"Szilfalaposdulo","state":"Heves"}'>Szilfalaposdulo</div>
<div class="option" data='{"value":"Szilvasvarad","state":"Heves"}'>Szilvasvarad</div>
<div class="option" data='{"value":"Szokeszelitanya","state":"Heves"}'>Szokeszelitanya</div>
<div class="option" data='{"value":"Szoketanya","state":"Heves"}'>Szoketanya</div>
<div class="option" data='{"value":"Szolloaljadulo","state":"Heves"}'>Szolloaljadulo</div>
<div class="option" data='{"value":"Szollotelep","state":"Heves"}'>Szollotelep</div>
<div class="option" data='{"value":"Szoloaljadulo","state":"Heves"}'>Szoloaljadulo</div>
<div class="option" data='{"value":"Szoloalji Tanyak","state":"Heves"}'>Szoloalji Tanyak</div>
<div class="option" data='{"value":"Szomoditanya","state":"Heves"}'>Szomoditanya</div>
<div class="option" data='{"value":"Szorvanytanya","state":"Heves"}'>Szorvanytanya</div>
<div class="option" data='{"value":"Szucs","state":"Heves"}'>Szucs</div>
<div class="option" data='{"value":"Szucsi","state":"Heves"}'>Szucsi</div>
<div class="option" data='{"value":"Tabitanya","state":"Heves"}'>Tabitanya</div>
<div class="option" data='{"value":"Tarca","state":"Heves"}'>Tarca</div>
<div class="option" data='{"value":"Tarcapuszta","state":"Heves"}'>Tarcapuszta</div>
<div class="option" data='{"value":"Tarcatanya","state":"Heves"}'>Tarcatanya</div>
<div class="option" data='{"value":"Tardosi Kobanya","state":"Heves"}'>Tardosi Kobanya</div>
<div class="option" data='{"value":"Tarnabod","state":"Heves"}'>Tarnabod</div>
<div class="option" data='{"value":"Tarnalelesz","state":"Heves"}'>Tarnalelesz</div>
<div class="option" data='{"value":"Tarnamera","state":"Heves"}'>Tarnamera</div>
<div class="option" data='{"value":"Tarnaors","state":"Heves"}'>Tarnaors</div>
<div class="option" data='{"value":"Tarnaszentmaria","state":"Heves"}'>Tarnaszentmaria</div>
<div class="option" data='{"value":"Tarnaszentmiklos","state":"Heves"}'>Tarnaszentmiklos</div>
<div class="option" data='{"value":"Tarnaszentmiklosi Tanyak","state":"Heves"}'>Tarnaszentmiklosi Tanyak</div>
<div class="option" data='{"value":"Tarnazsadany","state":"Heves"}'>Tarnazsadany</div>
<div class="option" data='{"value":"Tas","state":"Heves"}'>Tas</div>
<div class="option" data='{"value":"Tass","state":"Heves"}'>Tass</div>
<div class="option" data='{"value":"Tassitanya","state":"Heves"}'>Tassitanya</div>
<div class="option" data='{"value":"Tasspuszta","state":"Heves"}'>Tasspuszta</div>
<div class="option" data='{"value":"Tassytanyak","state":"Heves"}'>Tassytanyak</div>
<div class="option" data='{"value":"Tasypuszta","state":"Heves"}'>Tasypuszta</div>
<div class="option" data='{"value":"Telekidulo","state":"Heves"}'>Telekidulo</div>
<div class="option" data='{"value":"Tenk","state":"Heves"}'>Tenk</div>
<div class="option" data='{"value":"Terpes","state":"Heves"}'>Terpes</div>
<div class="option" data='{"value":"Tibrik","state":"Heves"}'>Tibrik</div>
<div class="option" data='{"value":"Tihamer","state":"Heves"}'>Tihamer</div>
<div class="option" data='{"value":"Tihamerdulo","state":"Heves"}'>Tihamerdulo</div>
<div class="option" data='{"value":"Tipaszo","state":"Heves"}'>Tipaszo</div>
<div class="option" data='{"value":"Tiszad","state":"Heves"}'>Tiszad</div>
<div class="option" data='{"value":"Tiszahid","state":"Heves"}'>Tiszahid</div>
<div class="option" data='{"value":"Tiszanana","state":"Heves"}'>Tiszanana</div>
<div class="option" data='{"value":"Tiszananai Tanyak","state":"Heves"}'>Tiszananai Tanyak</div>
<div class="option" data='{"value":"Tiszaret","state":"Heves"}'>Tiszaret</div>
<div class="option" data='{"value":"Todebro","state":"Heves"}'>Todebro</div>
<div class="option" data='{"value":"Tofalu","state":"Heves"}'>Tofalu</div>
<div class="option" data='{"value":"Togatpuszta","state":"Heves"}'>Togatpuszta</div>
<div class="option" data='{"value":"Tolgyestanya","state":"Heves"}'>Tolgyestanya</div>
<div class="option" data='{"value":"Torbaytanya","state":"Heves"}'>Torbaytanya</div>
<div class="option" data='{"value":"Tothtanya","state":"Heves"}'>Tothtanya</div>
<div class="option" data='{"value":"Toverotanya","state":"Heves"}'>Toverotanya</div>
<div class="option" data='{"value":"Tozsertanya","state":"Heves"}'>Tozsertanya</div>
<div class="option" data='{"value":"Tozsertanyak","state":"Heves"}'>Tozsertanyak</div>
<div class="option" data='{"value":"Ujlorincfalva","state":"Heves"}'>Ujlorincfalva</div>
<div class="option" data='{"value":"Ujmajor","state":"Heves"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujtelep","state":"Heves"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujvarsany","state":"Heves"}'>Ujvarsany</div>
<div class="option" data='{"value":"Ujvarsanypuszta","state":"Heves"}'>Ujvarsanypuszta</div>
<div class="option" data='{"value":"Ujvartanya","state":"Heves"}'>Ujvartanya</div>
<div class="option" data='{"value":"Ungertanya","state":"Heves"}'>Ungertanya</div>
<div class="option" data='{"value":"Ureghuta","state":"Heves"}'>Ureghuta</div>
<div class="option" data='{"value":"Usztato","state":"Heves"}'>Usztato</div>
<div class="option" data='{"value":"Uveghuta","state":"Heves"}'>Uveghuta</div>
<div class="option" data='{"value":"Vajdatanya","state":"Heves"}'>Vajdatanya</div>
<div class="option" data='{"value":"Valkotanya","state":"Heves"}'>Valkotanya</div>
<div class="option" data='{"value":"Vallospuszta","state":"Heves"}'>Vallospuszta</div>
<div class="option" data='{"value":"Vallostanya","state":"Heves"}'>Vallostanya</div>
<div class="option" data='{"value":"Vamosgyork","state":"Heves"}'>Vamosgyork</div>
<div class="option" data='{"value":"Varaszo","state":"Heves"}'>Varaszo</div>
<div class="option" data='{"value":"Vargatanya","state":"Heves"}'>Vargatanya</div>
<div class="option" data='{"value":"Varjas","state":"Heves"}'>Varjas</div>
<div class="option" data='{"value":"Varjastanyak","state":"Heves"}'>Varjastanyak</div>
<div class="option" data='{"value":"Varnyaspuszta","state":"Heves"}'>Varnyaspuszta</div>
<div class="option" data='{"value":"Vecs","state":"Heves"}'>Vecs</div>
<div class="option" data='{"value":"Vecseivolgy","state":"Heves"}'>Vecseivolgy</div>
<div class="option" data='{"value":"Vecseyvolgy","state":"Heves"}'>Vecseyvolgy</div>
<div class="option" data='{"value":"Verebtanya","state":"Heves"}'>Verebtanya</div>
<div class="option" data='{"value":"Verempart","state":"Heves"}'>Verempart</div>
<div class="option" data='{"value":"Veresmajor","state":"Heves"}'>Veresmajor</div>
<div class="option" data='{"value":"Verpelet","state":"Heves"}'>Verpelet</div>
<div class="option" data='{"value":"Vicziantanya","state":"Heves"}'>Vicziantanya</div>
<div class="option" data='{"value":"Vigtanya","state":"Heves"}'>Vigtanya</div>
<div class="option" data='{"value":"Vilagos","state":"Heves"}'>Vilagos</div>
<div class="option" data='{"value":"Vilagostanya","state":"Heves"}'>Vilagostanya</div>
<div class="option" data='{"value":"Vincetanya","state":"Heves"}'>Vincetanya</div>
<div class="option" data='{"value":"Viragtanya","state":"Heves"}'>Viragtanya</div>
<div class="option" data='{"value":"Visonta","state":"Heves"}'>Visonta</div>
<div class="option" data='{"value":"Visontai Szollotelep","state":"Heves"}'>Visontai Szollotelep</div>
<div class="option" data='{"value":"Visontai Szolotelep","state":"Heves"}'>Visontai Szolotelep</div>
<div class="option" data='{"value":"Visznek","state":"Heves"}'>Visznek</div>
<div class="option" data='{"value":"Viszneki Tanyak","state":"Heves"}'>Viszneki Tanyak</div>
<div class="option" data='{"value":"Viztelep","state":"Heves"}'>Viztelep</div>
<div class="option" data='{"value":"Vizvaritanya","state":"Heves"}'>Vizvaritanya</div>
<div class="option" data='{"value":"Volgyitag","state":"Heves"}'>Volgyitag</div>
<div class="option" data='{"value":"Zagyvaitanya","state":"Heves"}'>Zagyvaitanya</div>
<div class="option" data='{"value":"Zagyvaszanto","state":"Heves"}'>Zagyvaszanto</div>
<div class="option" data='{"value":"Zamorszenegeto","state":"Heves"}'>Zamorszenegeto</div>
<div class="option" data='{"value":"Zarank","state":"Heves"}'>Zarank</div>
<div class="option" data='{"value":"Zaranki Tanyak","state":"Heves"}'>Zaranki Tanyak</div>
<div class="option" data='{"value":"Zarankidulo","state":"Heves"}'>Zarankidulo</div>
<div class="option" data='{"value":"Zardatanya","state":"Heves"}'>Zardatanya</div>
<div class="option" data='{"value":"Zolcaiteto","state":"Heves"}'>Zolcaiteto</div>
<div class="option" id="option_end" data='{"value":"Zsilletanya","state":"Heves"}'>Zsilletanya</div>

