<div class="option" data='{"value":"Abaliget","state":"Baranya"}'>Abaliget</div>
<div class="option" data='{"value":"Adorjanpuszta","state":"Baranya"}'>Adorjanpuszta</div>
<div class="option" data='{"value":"Adorjantanya","state":"Baranya"}'>Adorjantanya</div>
<div class="option" data='{"value":"Adorjas","state":"Baranya"}'>Adorjas</div>
<div class="option" data='{"value":"Ag","state":"Baranya"}'>Ag</div>
<div class="option" data='{"value":"Agaserdo","state":"Baranya"}'>Agaserdo</div>
<div class="option" data='{"value":"Akasztofadulo","state":"Baranya"}'>Akasztofadulo</div>
<div class="option" data='{"value":"Akol","state":"Baranya"}'>Akol</div>
<div class="option" data='{"value":"Aligvaritanya","state":"Baranya"}'>Aligvaritanya</div>
<div class="option" data='{"value":"Almamellek","state":"Baranya"}'>Almamellek</div>
<div class="option" data='{"value":"Almas","state":"Baranya"}'>Almas</div>
<div class="option" data='{"value":"Almasgodor","state":"Baranya"}'>Almasgodor</div>
<div class="option" data='{"value":"Almaskeresztur","state":"Baranya"}'>Almaskeresztur</div>
<div class="option" data='{"value":"Almaspuszta","state":"Baranya"}'>Almaspuszta</div>
<div class="option" data='{"value":"Also Horvathmalom","state":"Baranya"}'>Also Horvathmalom</div>
<div class="option" data='{"value":"Alsocun","state":"Baranya"}'>Alsocun</div>
<div class="option" data='{"value":"Alsoerzsebetpuszta","state":"Baranya"}'>Alsoerzsebetpuszta</div>
<div class="option" data='{"value":"Alsokanda","state":"Baranya"}'>Alsokanda</div>
<div class="option" data='{"value":"Alsokovesd","state":"Baranya"}'>Alsokovesd</div>
<div class="option" data='{"value":"Alsolegencse","state":"Baranya"}'>Alsolegencse</div>
<div class="option" data='{"value":"Alsolog","state":"Baranya"}'>Alsolog</div>
<div class="option" data='{"value":"Alsomezo","state":"Baranya"}'>Alsomezo</div>
<div class="option" data='{"value":"Alsomezotanya","state":"Baranya"}'>Alsomezotanya</div>
<div class="option" data='{"value":"Alsomocsolad","state":"Baranya"}'>Alsomocsolad</div>
<div class="option" data='{"value":"Alsopalajpuszta","state":"Baranya"}'>Alsopalajpuszta</div>
<div class="option" data='{"value":"Alsoszallas","state":"Baranya"}'>Alsoszallas</div>
<div class="option" data='{"value":"Alsoszentmarton","state":"Baranya"}'>Alsoszentmarton</div>
<div class="option" data='{"value":"Alsovasarter","state":"Baranya"}'>Alsovasarter</div>
<div class="option" data='{"value":"Altontanya","state":"Baranya"}'>Altontanya</div>
<div class="option" data='{"value":"Angyaloc","state":"Baranya"}'>Angyaloc</div>
<div class="option" data='{"value":"Anos","state":"Baranya"}'>Anos</div>
<div class="option" data='{"value":"Antalfalutelep","state":"Baranya"}'>Antalfalutelep</div>
<div class="option" data='{"value":"Antalmajor","state":"Baranya"}'>Antalmajor</div>
<div class="option" data='{"value":"Antalpuszta","state":"Baranya"}'>Antalpuszta</div>
<div class="option" data='{"value":"Apatvarasd","state":"Baranya"}'>Apatvarasd</div>
<div class="option" data='{"value":"Apatvarasdtelep","state":"Baranya"}'>Apatvarasdtelep</div>
<div class="option" data='{"value":"Aranyhegy","state":"Baranya"}'>Aranyhegy</div>
<div class="option" data='{"value":"Aranyos","state":"Baranya"}'>Aranyos</div>
<div class="option" data='{"value":"Aranyosgadany","state":"Baranya"}'>Aranyosgadany</div>
<div class="option" data='{"value":"Arpadteto","state":"Baranya"}'>Arpadteto</div>
<div class="option" data='{"value":"Ata","state":"Baranya"}'>Ata</div>
<div class="option" data='{"value":"Atakeleti Malom","state":"Baranya"}'>Atakeleti Malom</div>
<div class="option" data='{"value":"Avas","state":"Baranya"}'>Avas</div>
<div class="option" data='{"value":"Avaspuszta","state":"Baranya"}'>Avaspuszta</div>
<div class="option" data='{"value":"Avastanya","state":"Baranya"}'>Avastanya</div>
<div class="option" data='{"value":"Babarc","state":"Baranya"}'>Babarc</div>
<div class="option" data='{"value":"Babarci Puszta","state":"Baranya"}'>Babarci Puszta</div>
<div class="option" data='{"value":"Babarcpuszta","state":"Baranya"}'>Babarcpuszta</div>
<div class="option" data='{"value":"Babarcszollos","state":"Baranya"}'>Babarcszollos</div>
<div class="option" data='{"value":"Babarcszolos","state":"Baranya"}'>Babarcszolos</div>
<div class="option" data='{"value":"Babosmalom","state":"Baranya"}'>Babosmalom</div>
<div class="option" data='{"value":"Bacsfapuszta","state":"Baranya"}'>Bacsfapuszta</div>
<div class="option" data='{"value":"Bacskatanya","state":"Baranya"}'>Bacskatanya</div>
<div class="option" data='{"value":"Bagopuszta","state":"Baranya"}'>Bagopuszta</div>
<div class="option" data='{"value":"Bagotanya","state":"Baranya"}'>Bagotanya</div>
<div class="option" data='{"value":"Bajcsitanya","state":"Baranya"}'>Bajcsitanya</div>
<div class="option" data='{"value":"Bakbuzpuszta","state":"Baranya"}'>Bakbuzpuszta</div>
<div class="option" data='{"value":"Bakistanya","state":"Baranya"}'>Bakistanya</div>
<div class="option" data='{"value":"Bakittyaszollo","state":"Baranya"}'>Bakittyaszollo</div>
<div class="option" data='{"value":"Bakoca","state":"Baranya"}'>Bakoca</div>
<div class="option" data='{"value":"Bakonya","state":"Baranya"}'>Bakonya</div>
<div class="option" data='{"value":"Baksa","state":"Baranya"}'>Baksa</div>
<div class="option" data='{"value":"Balazsszallas","state":"Baranya"}'>Balazsszallas</div>
<div class="option" data='{"value":"Balazstelep","state":"Baranya"}'>Balazstelep</div>
<div class="option" data='{"value":"Banfa","state":"Baranya"}'>Banfa</div>
<div class="option" data='{"value":"Banos","state":"Baranya"}'>Banos</div>
<div class="option" data='{"value":"Banyatelep","state":"Baranya"}'>Banyatelep</div>
<div class="option" data='{"value":"Bar","state":"Baranya"}'>Bar</div>
<div class="option" data='{"value":"Baranya","state":"Baranya"}'>Baranya</div>
<div class="option" data='{"value":"Baranya County","state":"Baranya"}'>Baranya County</div>
<div class="option" data='{"value":"Baranya Megye","state":"Baranya"}'>Baranya Megye</div>
<div class="option" data='{"value":"Baranyahidveg","state":"Baranya"}'>Baranyahidveg</div>
<div class="option" data='{"value":"Baranyajeno","state":"Baranya"}'>Baranyajeno</div>
<div class="option" data='{"value":"Baranyaszentgyorgy","state":"Baranya"}'>Baranyaszentgyorgy</div>
<div class="option" data='{"value":"Baratokmehese","state":"Baranya"}'>Baratokmehese</div>
<div class="option" data='{"value":"Baratur","state":"Baranya"}'>Baratur</div>
<div class="option" data='{"value":"Basal","state":"Baranya"}'>Basal</div>
<div class="option" data='{"value":"Basamalom","state":"Baranya"}'>Basamalom</div>
<div class="option" data='{"value":"Basamalomdulo","state":"Baranya"}'>Basamalomdulo</div>
<div class="option" data='{"value":"Basasarokidulo","state":"Baranya"}'>Basasarokidulo</div>
<div class="option" data='{"value":"Batortanya","state":"Baranya"}'>Batortanya</div>
<div class="option" data='{"value":"Becefa","state":"Baranya"}'>Becefa</div>
<div class="option" data='{"value":"Beda","state":"Baranya"}'>Beda</div>
<div class="option" data='{"value":"Bedai Vadaszlak","state":"Baranya"}'>Bedai Vadaszlak</div>
<div class="option" data='{"value":"Bekaspuszta","state":"Baranya"}'>Bekaspuszta</div>
<div class="option" data='{"value":"Bekatopuszta","state":"Baranya"}'>Bekatopuszta</div>
<div class="option" data='{"value":"Bekefa","state":"Baranya"}'>Bekefa</div>
<div class="option" data='{"value":"Beldvardgyula","state":"Baranya"}'>Beldvardgyula</div>
<div class="option" data='{"value":"Belenfuz","state":"Baranya"}'>Belenfuz</div>
<div class="option" data='{"value":"Belsoret","state":"Baranya"}'>Belsoret</div>
<div class="option" data='{"value":"Belsoriha","state":"Baranya"}'>Belsoriha</div>
<div class="option" data='{"value":"Belsotanyak","state":"Baranya"}'>Belsotanyak</div>
<div class="option" data='{"value":"Belvardgyula","state":"Baranya"}'>Belvardgyula</div>
<div class="option" data='{"value":"Berekaljapuszta","state":"Baranya"}'>Berekaljapuszta</div>
<div class="option" data='{"value":"Berekret","state":"Baranya"}'>Berekret</div>
<div class="option" data='{"value":"Beremend","state":"Baranya"}'>Beremend</div>
<div class="option" data='{"value":"Beremeni Tanya","state":"Baranya"}'>Beremeni Tanya</div>
<div class="option" data='{"value":"Beretvaspuszta","state":"Baranya"}'>Beretvaspuszta</div>
<div class="option" data='{"value":"Berkesd","state":"Baranya"}'>Berkesd</div>
<div class="option" data='{"value":"Berkesdpuszta","state":"Baranya"}'>Berkesdpuszta</div>
<div class="option" data='{"value":"Berkestanya","state":"Baranya"}'>Berkestanya</div>
<div class="option" data='{"value":"Besence","state":"Baranya"}'>Besence</div>
<div class="option" data='{"value":"Besenczitanya","state":"Baranya"}'>Besenczitanya</div>
<div class="option" data='{"value":"Bezedek","state":"Baranya"}'>Bezedek</div>
<div class="option" data='{"value":"Bezedekpuszta","state":"Baranya"}'>Bezedekpuszta</div>
<div class="option" data='{"value":"Bicserd","state":"Baranya"}'>Bicserd</div>
<div class="option" data='{"value":"Bikal","state":"Baranya"}'>Bikal</div>
<div class="option" data='{"value":"Bikapuszta","state":"Baranya"}'>Bikapuszta</div>
<div class="option" data='{"value":"Birjan","state":"Baranya"}'>Birjan</div>
<div class="option" data='{"value":"Bisse","state":"Baranya"}'>Bisse</div>
<div class="option" data='{"value":"Boda","state":"Baranya"}'>Boda</div>
<div class="option" data='{"value":"Boditanya","state":"Baranya"}'>Boditanya</div>
<div class="option" data='{"value":"Bodolyaber","state":"Baranya"}'>Bodolyaber</div>
<div class="option" data='{"value":"Bodorfa","state":"Baranya"}'>Bodorfa</div>
<div class="option" data='{"value":"Bogad","state":"Baranya"}'>Bogad</div>
<div class="option" data='{"value":"Bogadmindszent","state":"Baranya"}'>Bogadmindszent</div>
<div class="option" data='{"value":"Bogdasa","state":"Baranya"}'>Bogdasa</div>
<div class="option" data='{"value":"Bohmhizlalda","state":"Baranya"}'>Bohmhizlalda</div>
<div class="option" data='{"value":"Bokerdo","state":"Baranya"}'>Bokerdo</div>
<div class="option" data='{"value":"Boldogasszonyfa","state":"Baranya"}'>Boldogasszonyfa</div>
<div class="option" data='{"value":"Boly","state":"Baranya"}'>Boly</div>
<div class="option" data='{"value":"Bolyi Tanyak","state":"Baranya"}'>Bolyi Tanyak</div>
<div class="option" data='{"value":"Boog","state":"Baranya"}'>Boog</div>
<div class="option" data='{"value":"Borjad","state":"Baranya"}'>Borjad</div>
<div class="option" data='{"value":"Borosstanya","state":"Baranya"}'>Borosstanya</div>
<div class="option" data='{"value":"Borostyan","state":"Baranya"}'>Borostyan</div>
<div class="option" data='{"value":"Borostyanpuszta","state":"Baranya"}'>Borostyanpuszta</div>
<div class="option" data='{"value":"Borza","state":"Baranya"}'>Borza</div>
<div class="option" data='{"value":"Bosnyaktanya","state":"Baranya"}'>Bosnyaktanya</div>
<div class="option" data='{"value":"Bosta","state":"Baranya"}'>Bosta</div>
<div class="option" data='{"value":"Botykapeterd","state":"Baranya"}'>Botykapeterd</div>
<div class="option" data='{"value":"Brodpuszta","state":"Baranya"}'>Brodpuszta</div>
<div class="option" data='{"value":"Bucsanypuszta","state":"Baranya"}'>Bucsanypuszta</div>
<div class="option" data='{"value":"Bukkosd","state":"Baranya"}'>Bukkosd</div>
<div class="option" data='{"value":"Burus","state":"Baranya"}'>Burus</div>
<div class="option" data='{"value":"Cegledpuszta","state":"Baranya"}'>Cegledpuszta</div>
<div class="option" data='{"value":"Ciframalom","state":"Baranya"}'>Ciframalom</div>
<div class="option" data='{"value":"Csanadikert","state":"Baranya"}'>Csanadikert</div>
<div class="option" data='{"value":"Csanadikert Major","state":"Baranya"}'>Csanadikert Major</div>
<div class="option" data='{"value":"Csanyoszro","state":"Baranya"}'>Csanyoszro</div>
<div class="option" data='{"value":"Csarnota","state":"Baranya"}'>Csarnota</div>
<div class="option" data='{"value":"Csata","state":"Baranya"}'>Csata</div>
<div class="option" data='{"value":"Csatahely","state":"Baranya"}'>Csatahely</div>
<div class="option" data='{"value":"Csebe","state":"Baranya"}'>Csebe</div>
<div class="option" data='{"value":"Csebeny","state":"Baranya"}'>Csebeny</div>
<div class="option" data='{"value":"Csecstanya","state":"Baranya"}'>Csecstanya</div>
<div class="option" data='{"value":"Csehipuszta","state":"Baranya"}'>Csehipuszta</div>
<div class="option" data='{"value":"Cseledoboka","state":"Baranya"}'>Cseledoboka</div>
<div class="option" data='{"value":"Cselegorcsony","state":"Baranya"}'>Cselegorcsony</div>
<div class="option" data='{"value":"Cselehegy","state":"Baranya"}'>Cselehegy</div>
<div class="option" data='{"value":"Cser","state":"Baranya"}'>Cser</div>
<div class="option" data='{"value":"Cserdi","state":"Baranya"}'>Cserdi</div>
<div class="option" data='{"value":"Cserhatdulo","state":"Baranya"}'>Cserhatdulo</div>
<div class="option" data='{"value":"Cseripuszta","state":"Baranya"}'>Cseripuszta</div>
<div class="option" data='{"value":"Cserkut","state":"Baranya"}'>Cserkut</div>
<div class="option" data='{"value":"Cseromkata","state":"Baranya"}'>Cseromkata</div>
<div class="option" data='{"value":"Cserto","state":"Baranya"}'>Cserto</div>
<div class="option" data='{"value":"Csobokapuszta","state":"Baranya"}'>Csobokapuszta</div>
<div class="option" data='{"value":"Csoka","state":"Baranya"}'>Csoka</div>
<div class="option" data='{"value":"Csokolade","state":"Baranya"}'>Csokolade</div>
<div class="option" data='{"value":"Csokoladepuszta","state":"Baranya"}'>Csokoladepuszta</div>
<div class="option" data='{"value":"Csonkamindszent","state":"Baranya"}'>Csonkamindszent</div>
<div class="option" data='{"value":"Csonkaret","state":"Baranya"}'>Csonkaret</div>
<div class="option" data='{"value":"Csontoscsarda","state":"Baranya"}'>Csontoscsarda</div>
<div class="option" data='{"value":"Csontosicsarda","state":"Baranya"}'>Csontosicsarda</div>
<div class="option" data='{"value":"Csukma","state":"Baranya"}'>Csukma</div>
<div class="option" data='{"value":"Csukma Bulgartelep","state":"Baranya"}'>Csukma Bulgartelep</div>
<div class="option" data='{"value":"Csulakmalom","state":"Baranya"}'>Csulakmalom</div>
<div class="option" data='{"value":"Cun","state":"Baranya"}'>Cun</div>
<div class="option" data='{"value":"Danihizlalda","state":"Baranya"}'>Danihizlalda</div>
<div class="option" data='{"value":"Daroczihalma","state":"Baranya"}'>Daroczihalma</div>
<div class="option" data='{"value":"Daruvar","state":"Baranya"}'>Daruvar</div>
<div class="option" data='{"value":"Deli Telep","state":"Baranya"}'>Deli Telep</div>
<div class="option" data='{"value":"Deli Ujtelep","state":"Baranya"}'>Deli Ujtelep</div>
<div class="option" data='{"value":"Dencshaza","state":"Baranya"}'>Dencshaza</div>
<div class="option" data='{"value":"Depo","state":"Baranya"}'>Depo</div>
<div class="option" data='{"value":"Dinnyeberki","state":"Baranya"}'>Dinnyeberki</div>
<div class="option" data='{"value":"Dinnyefold","state":"Baranya"}'>Dinnyefold</div>
<div class="option" data='{"value":"Dios","state":"Baranya"}'>Dios</div>
<div class="option" data='{"value":"Diospuszta","state":"Baranya"}'>Diospuszta</div>
<div class="option" data='{"value":"Diosviszlo","state":"Baranya"}'>Diosviszlo</div>
<div class="option" data='{"value":"Dobina","state":"Baranya"}'>Dobina</div>
<div class="option" data='{"value":"Dobosvolgy","state":"Baranya"}'>Dobosvolgy</div>
<div class="option" data='{"value":"Dobsza","state":"Baranya"}'>Dobsza</div>
<div class="option" data='{"value":"Doczimajor","state":"Baranya"}'>Doczimajor</div>
<div class="option" data='{"value":"Domolospuszta","state":"Baranya"}'>Domolospuszta</div>
<div class="option" data='{"value":"Dravacsehi","state":"Baranya"}'>Dravacsehi</div>
<div class="option" data='{"value":"Dravacsepely","state":"Baranya"}'>Dravacsepely</div>
<div class="option" data='{"value":"Dravafok","state":"Baranya"}'>Dravafok</div>
<div class="option" data='{"value":"Dravaivanyi","state":"Baranya"}'>Dravaivanyi</div>
<div class="option" data='{"value":"Dravakeresztur","state":"Baranya"}'>Dravakeresztur</div>
<div class="option" data='{"value":"Dravapalkonya","state":"Baranya"}'>Dravapalkonya</div>
<div class="option" data='{"value":"Dravapiski","state":"Baranya"}'>Dravapiski</div>
<div class="option" data='{"value":"Dravaszabolcs","state":"Baranya"}'>Dravaszabolcs</div>
<div class="option" data='{"value":"Dravaszerdahely","state":"Baranya"}'>Dravaszerdahely</div>
<div class="option" data='{"value":"Dravasztara","state":"Baranya"}'>Dravasztara</div>
<div class="option" data='{"value":"Dravasztarai Tanya","state":"Baranya"}'>Dravasztarai Tanya</div>
<div class="option" data='{"value":"Dunafalva","state":"Baranya"}'>Dunafalva</div>
<div class="option" data='{"value":"Dunaszekcso","state":"Baranya"}'>Dunaszekcso</div>
<div class="option" data='{"value":"Dunaszeksco","state":"Baranya"}'>Dunaszeksco</div>
<div class="option" data='{"value":"Durgotanya","state":"Baranya"}'>Durgotanya</div>
<div class="option" data='{"value":"Durkotanya","state":"Baranya"}'>Durkotanya</div>
<div class="option" data='{"value":"Egerag","state":"Baranya"}'>Egerag</div>
<div class="option" data='{"value":"Egermalom","state":"Baranya"}'>Egermalom</div>
<div class="option" data='{"value":"Egerszegimalom","state":"Baranya"}'>Egerszegimalom</div>
<div class="option" data='{"value":"Egerszegitanya","state":"Baranya"}'>Egerszegitanya</div>
<div class="option" data='{"value":"Egerszegpuszta","state":"Baranya"}'>Egerszegpuszta</div>
<div class="option" data='{"value":"Egyhazasharaszti","state":"Baranya"}'>Egyhazasharaszti</div>
<div class="option" data='{"value":"Egyhazaskozar","state":"Baranya"}'>Egyhazaskozar</div>
<div class="option" data='{"value":"Egyhazber","state":"Baranya"}'>Egyhazber</div>
<div class="option" data='{"value":"Elekpuszta","state":"Baranya"}'>Elekpuszta</div>
<div class="option" data='{"value":"Elemerpuszta","state":"Baranya"}'>Elemerpuszta</div>
<div class="option" data='{"value":"Elesd","state":"Baranya"}'>Elesd</div>
<div class="option" data='{"value":"Elesd Csarda","state":"Baranya"}'>Elesd Csarda</div>
<div class="option" data='{"value":"Ellend","state":"Baranya"}'>Ellend</div>
<div class="option" data='{"value":"Ellendpuszta","state":"Baranya"}'>Ellendpuszta</div>
<div class="option" data='{"value":"Endroc","state":"Baranya"}'>Endroc</div>
<div class="option" data='{"value":"Endrocpuszta","state":"Baranya"}'>Endrocpuszta</div>
<div class="option" data='{"value":"Eperjes","state":"Baranya"}'>Eperjes</div>
<div class="option" data='{"value":"Eperjespuszta","state":"Baranya"}'>Eperjespuszta</div>
<div class="option" data='{"value":"Erdo","state":"Baranya"}'>Erdo</div>
<div class="option" data='{"value":"Erdoalja","state":"Baranya"}'>Erdoalja</div>
<div class="option" data='{"value":"Erdofold","state":"Baranya"}'>Erdofold</div>
<div class="option" data='{"value":"Erdofu","state":"Baranya"}'>Erdofu</div>
<div class="option" data='{"value":"Erdofupusztai Szivattyutelep","state":"Baranya"}'>Erdofupusztai Szivattyutelep</div>
<div class="option" data='{"value":"Erdosmarok","state":"Baranya"}'>Erdosmarok</div>
<div class="option" data='{"value":"Erdosmecske","state":"Baranya"}'>Erdosmecske</div>
<div class="option" data='{"value":"Erdosmecskei Tanyak","state":"Baranya"}'>Erdosmecskei Tanyak</div>
<div class="option" data='{"value":"Ereszveny","state":"Baranya"}'>Ereszveny</div>
<div class="option" data='{"value":"Ereszvenytanya","state":"Baranya"}'>Ereszvenytanya</div>
<div class="option" data='{"value":"Eritanya","state":"Baranya"}'>Eritanya</div>
<div class="option" data='{"value":"Erzsebet","state":"Baranya"}'>Erzsebet</div>
<div class="option" data='{"value":"Eszaki Telep","state":"Baranya"}'>Eszaki Telep</div>
<div class="option" data='{"value":"Eszeki Orszaguti Tanyak","state":"Baranya"}'>Eszeki Orszaguti Tanyak</div>
<div class="option" data='{"value":"Eszterag","state":"Baranya"}'>Eszterag</div>
<div class="option" data='{"value":"Eszteragpuszta","state":"Baranya"}'>Eszteragpuszta</div>
<div class="option" data='{"value":"Etelmajor","state":"Baranya"}'>Etelmajor</div>
<div class="option" data='{"value":"Euchtanya","state":"Baranya"}'>Euchtanya</div>
<div class="option" data='{"value":"Faluveg","state":"Baranya"}'>Faluveg</div>
<div class="option" data='{"value":"Fanipuszta","state":"Baranya"}'>Fanipuszta</div>
<div class="option" data='{"value":"Fazekasboda","state":"Baranya"}'>Fazekasboda</div>
<div class="option" data='{"value":"Feherfalu","state":"Baranya"}'>Feherfalu</div>
<div class="option" data='{"value":"Feked","state":"Baranya"}'>Feked</div>
<div class="option" data='{"value":"Feketekapu","state":"Baranya"}'>Feketekapu</div>
<div class="option" data='{"value":"Felsocun","state":"Baranya"}'>Felsocun</div>
<div class="option" data='{"value":"Felsoegerszeg","state":"Baranya"}'>Felsoegerszeg</div>
<div class="option" data='{"value":"Felsoerdopuszta","state":"Baranya"}'>Felsoerdopuszta</div>
<div class="option" data='{"value":"Felsohegy","state":"Baranya"}'>Felsohegy</div>
<div class="option" data='{"value":"Felsokanda","state":"Baranya"}'>Felsokanda</div>
<div class="option" data='{"value":"Felsokovesd","state":"Baranya"}'>Felsokovesd</div>
<div class="option" data='{"value":"Felsolegencse","state":"Baranya"}'>Felsolegencse</div>
<div class="option" data='{"value":"Felsolog","state":"Baranya"}'>Felsolog</div>
<div class="option" data='{"value":"Felsomajor","state":"Baranya"}'>Felsomajor</div>
<div class="option" data='{"value":"Felsomalom","state":"Baranya"}'>Felsomalom</div>
<div class="option" data='{"value":"Felsomezo","state":"Baranya"}'>Felsomezo</div>
<div class="option" data='{"value":"Felsomindszent","state":"Baranya"}'>Felsomindszent</div>
<div class="option" data='{"value":"Felsoszentmarton","state":"Baranya"}'>Felsoszentmarton</div>
<div class="option" data='{"value":"Felsotukor","state":"Baranya"}'>Felsotukor</div>
<div class="option" data='{"value":"Fenyos","state":"Baranya"}'>Fenyos</div>
<div class="option" data='{"value":"Fenyospuszta","state":"Baranya"}'>Fenyospuszta</div>
<div class="option" data='{"value":"Fernapuszta","state":"Baranya"}'>Fernapuszta</div>
<div class="option" data='{"value":"Flasitsszollo","state":"Baranya"}'>Flasitsszollo</div>
<div class="option" data='{"value":"Fodortanya","state":"Baranya"}'>Fodortanya</div>
<div class="option" data='{"value":"Foldypuszta","state":"Baranya"}'>Foldypuszta</div>
<div class="option" data='{"value":"Fontanyipuszta","state":"Baranya"}'>Fontanyipuszta</div>
<div class="option" data='{"value":"Fortyogo Vizmu","state":"Baranya"}'>Fortyogo Vizmu</div>
<div class="option" data='{"value":"Frischlerpuszta","state":"Baranya"}'>Frischlerpuszta</div>
<div class="option" data='{"value":"Furesztanya","state":"Baranya"}'>Furesztanya</div>
<div class="option" data='{"value":"Fuzfakutidulo","state":"Baranya"}'>Fuzfakutidulo</div>
<div class="option" data='{"value":"Gaborpuszta","state":"Baranya"}'>Gaborpuszta</div>
<div class="option" data='{"value":"Gafimalom","state":"Baranya"}'>Gafimalom</div>
<div class="option" data='{"value":"Galambos","state":"Baranya"}'>Galambos</div>
<div class="option" data='{"value":"Galfimalom","state":"Baranya"}'>Galfimalom</div>
<div class="option" data='{"value":"Galhegy","state":"Baranya"}'>Galhegy</div>
<div class="option" data='{"value":"Galvolgytanya","state":"Baranya"}'>Galvolgytanya</div>
<div class="option" data='{"value":"Gardian","state":"Baranya"}'>Gardian</div>
<div class="option" data='{"value":"Gare","state":"Baranya"}'>Gare</div>
<div class="option" data='{"value":"Geczimalom","state":"Baranya"}'>Geczimalom</div>
<div class="option" data='{"value":"Gerde","state":"Baranya"}'>Gerde</div>
<div class="option" data='{"value":"Gerechat","state":"Baranya"}'>Gerechat</div>
<div class="option" data='{"value":"Gerechatmajor","state":"Baranya"}'>Gerechatmajor</div>
<div class="option" data='{"value":"Gerenyes","state":"Baranya"}'>Gerenyes</div>
<div class="option" data='{"value":"Geresd","state":"Baranya"}'>Geresd</div>
<div class="option" data='{"value":"Geresdlak","state":"Baranya"}'>Geresdlak</div>
<div class="option" data='{"value":"Gesnyeerdo","state":"Baranya"}'>Gesnyeerdo</div>
<div class="option" data='{"value":"Gesnyei Erdeszhaz","state":"Baranya"}'>Gesnyei Erdeszhaz</div>
<div class="option" data='{"value":"Gilvanfa","state":"Baranya"}'>Gilvanfa</div>
<div class="option" data='{"value":"Godisa","state":"Baranya"}'>Godisa</div>
<div class="option" data='{"value":"Godre","state":"Baranya"}'>Godre</div>
<div class="option" data='{"value":"Godrekeresztur","state":"Baranya"}'>Godrekeresztur</div>
<div class="option" data='{"value":"Godreszentmarton","state":"Baranya"}'>Godreszentmarton</div>
<div class="option" data='{"value":"Godreszentmartonpuszta","state":"Baranya"}'>Godreszentmartonpuszta</div>
<div class="option" data='{"value":"Golyavar","state":"Baranya"}'>Golyavar</div>
<div class="option" data='{"value":"Gombkotoi Malom","state":"Baranya"}'>Gombkotoi Malom</div>
<div class="option" data='{"value":"Gombkotomalom","state":"Baranya"}'>Gombkotomalom</div>
<div class="option" data='{"value":"Gonter","state":"Baranya"}'>Gonter</div>
<div class="option" data='{"value":"Gorcsony","state":"Baranya"}'>Gorcsony</div>
<div class="option" data='{"value":"Gorcsonydoboka","state":"Baranya"}'>Gorcsonydoboka</div>
<div class="option" data='{"value":"Gorcsonydobokai Tanya","state":"Baranya"}'>Gorcsonydobokai Tanya</div>
<div class="option" data='{"value":"Gorcsonyi Puszta","state":"Baranya"}'>Gorcsonyi Puszta</div>
<div class="option" data='{"value":"Gordisa","state":"Baranya"}'>Gordisa</div>
<div class="option" data='{"value":"Gordisai Puszta","state":"Baranya"}'>Gordisai Puszta</div>
<div class="option" data='{"value":"Gorica","state":"Baranya"}'>Gorica</div>
<div class="option" data='{"value":"Gorosgal","state":"Baranya"}'>Gorosgal</div>
<div class="option" data='{"value":"Gorosgalpuszta","state":"Baranya"}'>Gorosgalpuszta</div>
<div class="option" data='{"value":"Grecipuszta","state":"Baranya"}'>Grecipuszta</div>
<div class="option" data='{"value":"Grecpuszta","state":"Baranya"}'>Grecpuszta</div>
<div class="option" data='{"value":"Gusztavmuve","state":"Baranya"}'>Gusztavmuve</div>
<div class="option" data='{"value":"Guttmanntanya","state":"Baranya"}'>Guttmanntanya</div>
<div class="option" data='{"value":"Guzsvanytanya","state":"Baranya"}'>Guzsvanytanya</div>
<div class="option" data='{"value":"Gyepmestertelep","state":"Baranya"}'>Gyepmestertelep</div>
<div class="option" data='{"value":"Gyimoti Tanya","state":"Baranya"}'>Gyimoti Tanya</div>
<div class="option" data='{"value":"Gyod","state":"Baranya"}'>Gyod</div>
<div class="option" data='{"value":"Gyongyfa","state":"Baranya"}'>Gyongyfa</div>
<div class="option" data='{"value":"Gyongyosmellek","state":"Baranya"}'>Gyongyosmellek</div>
<div class="option" data='{"value":"Gyorgyimajor","state":"Baranya"}'>Gyorgyimajor</div>
<div class="option" data='{"value":"Gyorgyipuszta","state":"Baranya"}'>Gyorgyipuszta</div>
<div class="option" data='{"value":"Gyorgypuszta","state":"Baranya"}'>Gyorgypuszta</div>
<div class="option" data='{"value":"Gyulapuszta","state":"Baranya"}'>Gyulapuszta</div>
<div class="option" data='{"value":"Gyumolcseny","state":"Baranya"}'>Gyumolcseny</div>
<div class="option" data='{"value":"Gyumolcsenyi Puszta","state":"Baranya"}'>Gyumolcsenyi Puszta</div>
<div class="option" data='{"value":"Gyumolcsenypuszta","state":"Baranya"}'>Gyumolcsenypuszta</div>
<div class="option" data='{"value":"Gyurufu","state":"Baranya"}'>Gyurufu</div>
<div class="option" data='{"value":"Gyurus","state":"Baranya"}'>Gyurus</div>
<div class="option" data='{"value":"Gyurus Totokfoldje","state":"Baranya"}'>Gyurus Totokfoldje</div>
<div class="option" data='{"value":"Gyuruspuszta","state":"Baranya"}'>Gyuruspuszta</div>
<div class="option" data='{"value":"Gyuszipuszta","state":"Baranya"}'>Gyuszipuszta</div>
<div class="option" data='{"value":"Habihegy","state":"Baranya"}'>Habihegy</div>
<div class="option" data='{"value":"Habpuszta","state":"Baranya"}'>Habpuszta</div>
<div class="option" data='{"value":"Hagyoitanya","state":"Baranya"}'>Hagyoitanya</div>
<div class="option" data='{"value":"Halasto","state":"Baranya"}'>Halasto</div>
<div class="option" data='{"value":"Harkany","state":"Baranya"}'>Harkany</div>
<div class="option" data='{"value":"Harkanyi Tanyak","state":"Baranya"}'>Harkanyi Tanyak</div>
<div class="option" data='{"value":"Haromhaz","state":"Baranya"}'>Haromhaz</div>
<div class="option" data='{"value":"Haromhaza","state":"Baranya"}'>Haromhaza</div>
<div class="option" data='{"value":"Haromhid","state":"Baranya"}'>Haromhid</div>
<div class="option" data='{"value":"Harommalom","state":"Baranya"}'>Harommalom</div>
<div class="option" data='{"value":"Harraymalom","state":"Baranya"}'>Harraymalom</div>
<div class="option" data='{"value":"Harsastelep","state":"Baranya"}'>Harsastelep</div>
<div class="option" data='{"value":"Harsfapuszta","state":"Baranya"}'>Harsfapuszta</div>
<div class="option" data='{"value":"Hassagy","state":"Baranya"}'>Hassagy</div>
<div class="option" data='{"value":"Hattelek","state":"Baranya"}'>Hattelek</div>
<div class="option" data='{"value":"Hegy","state":"Baranya"}'>Hegy</div>
<div class="option" data='{"value":"Hegyhatmaroc","state":"Baranya"}'>Hegyhatmaroc</div>
<div class="option" data='{"value":"Hegyszentmarton","state":"Baranya"}'>Hegyszentmarton</div>
<div class="option" data='{"value":"Helesfa","state":"Baranya"}'>Helesfa</div>
<div class="option" data='{"value":"Hercegmalom","state":"Baranya"}'>Hercegmalom</div>
<div class="option" data='{"value":"Hercegszabar","state":"Baranya"}'>Hercegszabar</div>
<div class="option" data='{"value":"Hercegszentmarton","state":"Baranya"}'>Hercegszentmarton</div>
<div class="option" data='{"value":"Hercegtottos","state":"Baranya"}'>Hercegtottos</div>
<div class="option" data='{"value":"Hetvehely","state":"Baranya"}'>Hetvehely</div>
<div class="option" data='{"value":"Hidas","state":"Baranya"}'>Hidas</div>
<div class="option" data='{"value":"Hidegkut","state":"Baranya"}'>Hidegkut</div>
<div class="option" data='{"value":"Hidegkutidulo","state":"Baranya"}'>Hidegkutidulo</div>
<div class="option" data='{"value":"Hidor","state":"Baranya"}'>Hidor</div>
<div class="option" data='{"value":"Himeshaza","state":"Baranya"}'>Himeshaza</div>
<div class="option" data='{"value":"Himeshazi Puszta","state":"Baranya"}'>Himeshazi Puszta</div>
<div class="option" data='{"value":"Hirics","state":"Baranya"}'>Hirics</div>
<div class="option" data='{"value":"Hobol","state":"Baranya"}'>Hobol</div>
<div class="option" data='{"value":"Hobolpuszta","state":"Baranya"}'>Hobolpuszta</div>
<div class="option" data='{"value":"Hoffmann Malom","state":"Baranya"}'>Hoffmann Malom</div>
<div class="option" data='{"value":"Hohnertanya","state":"Baranya"}'>Hohnertanya</div>
<div class="option" data='{"value":"Homokbanya","state":"Baranya"}'>Homokbanya</div>
<div class="option" data='{"value":"Homokdomb","state":"Baranya"}'>Homokdomb</div>
<div class="option" data='{"value":"Homoki Dulo","state":"Baranya"}'>Homoki Dulo</div>
<div class="option" data='{"value":"Homokmajor","state":"Baranya"}'>Homokmajor</div>
<div class="option" data='{"value":"Homorud","state":"Baranya"}'>Homorud</div>
<div class="option" data='{"value":"Horvathertelend","state":"Baranya"}'>Horvathertelend</div>
<div class="option" data='{"value":"Hosszuheteny","state":"Baranya"}'>Hosszuheteny</div>
<div class="option" data='{"value":"Husztot","state":"Baranya"}'>Husztot</div>
<div class="option" data='{"value":"Ibafa","state":"Baranya"}'>Ibafa</div>
<div class="option" data='{"value":"Idamajor","state":"Baranya"}'>Idamajor</div>
<div class="option" data='{"value":"Idapuszta","state":"Baranya"}'>Idapuszta</div>
<div class="option" data='{"value":"Ilkamajor","state":"Baranya"}'>Ilkamajor</div>
<div class="option" data='{"value":"Ilkapuszta","state":"Baranya"}'>Ilkapuszta</div>
<div class="option" data='{"value":"Illocska","state":"Baranya"}'>Illocska</div>
<div class="option" data='{"value":"Ilmapuszta","state":"Baranya"}'>Ilmapuszta</div>
<div class="option" data='{"value":"Ilonamajor","state":"Baranya"}'>Ilonamajor</div>
<div class="option" data='{"value":"Ipacsfa","state":"Baranya"}'>Ipacsfa</div>
<div class="option" data='{"value":"Irmapuszta","state":"Baranya"}'>Irmapuszta</div>
<div class="option" data='{"value":"Istvandimajor","state":"Baranya"}'>Istvandimajor</div>
<div class="option" data='{"value":"Ivanbattyan","state":"Baranya"}'>Ivanbattyan</div>
<div class="option" data='{"value":"Ivandarda","state":"Baranya"}'>Ivandarda</div>
<div class="option" data='{"value":"Ivanszollos","state":"Baranya"}'>Ivanszollos</div>
<div class="option" data='{"value":"Ivanszolos","state":"Baranya"}'>Ivanszolos</div>
<div class="option" data='{"value":"Izabellafold","state":"Baranya"}'>Izabellafold</div>
<div class="option" data='{"value":"Jagercsarda","state":"Baranya"}'>Jagercsarda</div>
<div class="option" data='{"value":"Jagerszallas","state":"Baranya"}'>Jagerszallas</div>
<div class="option" data='{"value":"Jakabtanya","state":"Baranya"}'>Jakabtanya</div>
<div class="option" data='{"value":"Janosipuszta","state":"Baranya"}'>Janosipuszta</div>
<div class="option" data='{"value":"Jedinka","state":"Baranya"}'>Jedinka</div>
<div class="option" data='{"value":"Jedinkaihegy","state":"Baranya"}'>Jedinkaihegy</div>
<div class="option" data='{"value":"Jedinkaszolo","state":"Baranya"}'>Jedinkaszolo</div>
<div class="option" data='{"value":"Jedinkaszolohegy","state":"Baranya"}'>Jedinkaszolohegy</div>
<div class="option" data='{"value":"Jeneiuti Tanya","state":"Baranya"}'>Jeneiuti Tanya</div>
<div class="option" data='{"value":"Jeneserdopuszta","state":"Baranya"}'>Jeneserdopuszta</div>
<div class="option" data='{"value":"Jeszenik","state":"Baranya"}'>Jeszenik</div>
<div class="option" data='{"value":"Jeszeniktanya","state":"Baranya"}'>Jeszeniktanya</div>
<div class="option" data='{"value":"Jozantelep","state":"Baranya"}'>Jozantelep</div>
<div class="option" data='{"value":"Jozsefmajor","state":"Baranya"}'>Jozsefmajor</div>
<div class="option" data='{"value":"Juliamajor","state":"Baranya"}'>Juliamajor</div>
<div class="option" data='{"value":"Kacsota","state":"Baranya"}'>Kacsota</div>
<div class="option" data='{"value":"Kakics","state":"Baranya"}'>Kakics</div>
<div class="option" data='{"value":"Kan","state":"Baranya"}'>Kan</div>
<div class="option" data='{"value":"Kanda","state":"Baranya"}'>Kanda</div>
<div class="option" data='{"value":"Kapolna","state":"Baranya"}'>Kapolna</div>
<div class="option" data='{"value":"Kaporai Malom","state":"Baranya"}'>Kaporai Malom</div>
<div class="option" data='{"value":"Kaposhomok","state":"Baranya"}'>Kaposhomok</div>
<div class="option" data='{"value":"Kaposztas","state":"Baranya"}'>Kaposztas</div>
<div class="option" data='{"value":"Kaptalani Erdo","state":"Baranya"}'>Kaptalani Erdo</div>
<div class="option" data='{"value":"Karacodfa","state":"Baranya"}'>Karacodfa</div>
<div class="option" data='{"value":"Karasz","state":"Baranya"}'>Karasz</div>
<div class="option" data='{"value":"Karaszpuszta","state":"Baranya"}'>Karaszpuszta</div>
<div class="option" data='{"value":"Karolymajor","state":"Baranya"}'>Karolymajor</div>
<div class="option" data='{"value":"Kasad","state":"Baranya"}'>Kasad</div>
<div class="option" data='{"value":"Katadfa","state":"Baranya"}'>Katadfa</div>
<div class="option" data='{"value":"Katalinmajor","state":"Baranya"}'>Katalinmajor</div>
<div class="option" data='{"value":"Katalinpuszta","state":"Baranya"}'>Katalinpuszta</div>
<div class="option" data='{"value":"Katoly","state":"Baranya"}'>Katoly</div>
<div class="option" data='{"value":"Kekesd","state":"Baranya"}'>Kekesd</div>
<div class="option" data='{"value":"Kelemenliget","state":"Baranya"}'>Kelemenliget</div>
<div class="option" data='{"value":"Kelenyitanya","state":"Baranya"}'>Kelenyitanya</div>
<div class="option" data='{"value":"Kemenygadany","state":"Baranya"}'>Kemenygadany</div>
<div class="option" data='{"value":"Kemes","state":"Baranya"}'>Kemes</div>
<div class="option" data='{"value":"Kemse","state":"Baranya"}'>Kemse</div>
<div class="option" data='{"value":"Kepespuszta","state":"Baranya"}'>Kepespuszta</div>
<div class="option" data='{"value":"Kerecsenyi Tanya","state":"Baranya"}'>Kerecsenyi Tanya</div>
<div class="option" data='{"value":"Kerecsenypuszta","state":"Baranya"}'>Kerecsenypuszta</div>
<div class="option" data='{"value":"Kerektoitanya","state":"Baranya"}'>Kerektoitanya</div>
<div class="option" data='{"value":"Keresnyeitanya","state":"Baranya"}'>Keresnyeitanya</div>
<div class="option" data='{"value":"Keresztes","state":"Baranya"}'>Keresztes</div>
<div class="option" data='{"value":"Keresztespuszta","state":"Baranya"}'>Keresztespuszta</div>
<div class="option" data='{"value":"Keresztestanya","state":"Baranya"}'>Keresztestanya</div>
<div class="option" data='{"value":"Kernercsarda","state":"Baranya"}'>Kernercsarda</div>
<div class="option" data='{"value":"Keselosfa","state":"Baranya"}'>Keselosfa</div>
<div class="option" data='{"value":"Keselyosfapuszta","state":"Baranya"}'>Keselyosfapuszta</div>
<div class="option" data='{"value":"Keskenypuszta","state":"Baranya"}'>Keskenypuszta</div>
<div class="option" data='{"value":"Kesnyekdulo","state":"Baranya"}'>Kesnyekdulo</div>
<div class="option" data='{"value":"Keszenvari","state":"Baranya"}'>Keszenvari</div>
<div class="option" data='{"value":"Keszenvaridulo","state":"Baranya"}'>Keszenvaridulo</div>
<div class="option" data='{"value":"Keszu","state":"Baranya"}'>Keszu</div>
<div class="option" data='{"value":"Ketujfalu","state":"Baranya"}'>Ketujfalu</div>
<div class="option" data='{"value":"Kiralyegyhaza","state":"Baranya"}'>Kiralyegyhaza</div>
<div class="option" data='{"value":"Kisag","state":"Baranya"}'>Kisag</div>
<div class="option" data='{"value":"Kisagpuszta","state":"Baranya"}'>Kisagpuszta</div>
<div class="option" data='{"value":"Kisasszonyfa","state":"Baranya"}'>Kisasszonyfa</div>
<div class="option" data='{"value":"Kisasszonyfai Puszta","state":"Baranya"}'>Kisasszonyfai Puszta</div>
<div class="option" data='{"value":"Kisbattyan","state":"Baranya"}'>Kisbattyan</div>
<div class="option" data='{"value":"Kisbeszterce","state":"Baranya"}'>Kisbeszterce</div>
<div class="option" data='{"value":"Kisbesztercei Tanya","state":"Baranya"}'>Kisbesztercei Tanya</div>
<div class="option" data='{"value":"Kisbicserd","state":"Baranya"}'>Kisbicserd</div>
<div class="option" data='{"value":"Kisbodolya","state":"Baranya"}'>Kisbodolya</div>
<div class="option" data='{"value":"Kisbudmer","state":"Baranya"}'>Kisbudmer</div>
<div class="option" data='{"value":"Kisder","state":"Baranya"}'>Kisder</div>
<div class="option" data='{"value":"Kisdobsza","state":"Baranya"}'>Kisdobsza</div>
<div class="option" data='{"value":"Kisgeresd","state":"Baranya"}'>Kisgeresd</div>
<div class="option" data='{"value":"Kisgorica","state":"Baranya"}'>Kisgorica</div>
<div class="option" data='{"value":"Kisgyula","state":"Baranya"}'>Kisgyula</div>
<div class="option" data='{"value":"Kishajmas","state":"Baranya"}'>Kishajmas</div>
<div class="option" data='{"value":"Kisharany","state":"Baranya"}'>Kisharany</div>
<div class="option" data='{"value":"Kisharsagy","state":"Baranya"}'>Kisharsagy</div>
<div class="option" data='{"value":"Kisharsany","state":"Baranya"}'>Kisharsany</div>
<div class="option" data='{"value":"Kishegy","state":"Baranya"}'>Kishegy</div>
<div class="option" data='{"value":"Kishegydulo","state":"Baranya"}'>Kishegydulo</div>
<div class="option" data='{"value":"Kisherend","state":"Baranya"}'>Kisherend</div>
<div class="option" data='{"value":"Kishertelend","state":"Baranya"}'>Kishertelend</div>
<div class="option" data='{"value":"Kishobol","state":"Baranya"}'>Kishobol</div>
<div class="option" data='{"value":"Kishosszuret","state":"Baranya"}'>Kishosszuret</div>
<div class="option" data='{"value":"Kishosszuretdulo","state":"Baranya"}'>Kishosszuretdulo</div>
<div class="option" data='{"value":"Kisibafa","state":"Baranya"}'>Kisibafa</div>
<div class="option" data='{"value":"Kisjakabfalva","state":"Baranya"}'>Kisjakabfalva</div>
<div class="option" data='{"value":"Kiskassa","state":"Baranya"}'>Kiskassa</div>
<div class="option" data='{"value":"Kiskeresztur","state":"Baranya"}'>Kiskeresztur</div>
<div class="option" data='{"value":"Kislippo","state":"Baranya"}'>Kislippo</div>
<div class="option" data='{"value":"Kismalom","state":"Baranya"}'>Kismalom</div>
<div class="option" data='{"value":"Kismohacs","state":"Baranya"}'>Kismohacs</div>
<div class="option" data='{"value":"Kisnyarad","state":"Baranya"}'>Kisnyarad</div>
<div class="option" data='{"value":"Kispeterd","state":"Baranya"}'>Kispeterd</div>
<div class="option" data='{"value":"Kisstanya","state":"Baranya"}'>Kisstanya</div>
<div class="option" data='{"value":"Kisszentlaszlo","state":"Baranya"}'>Kisszentlaszlo</div>
<div class="option" data='{"value":"Kisszentmarton","state":"Baranya"}'>Kisszentmarton</div>
<div class="option" data='{"value":"Kistamasi","state":"Baranya"}'>Kistamasi</div>
<div class="option" data='{"value":"Kistapolca","state":"Baranya"}'>Kistapolca</div>
<div class="option" data='{"value":"Kistotfalu","state":"Baranya"}'>Kistotfalu</div>
<div class="option" data='{"value":"Kisujbanya","state":"Baranya"}'>Kisujbanya</div>
<div class="option" data='{"value":"Kisvaszar","state":"Baranya"}'>Kisvaszar</div>
<div class="option" data='{"value":"Kisvidakpuszta","state":"Baranya"}'>Kisvidakpuszta</div>
<div class="option" data='{"value":"Kisvizslak","state":"Baranya"}'>Kisvizslak</div>
<div class="option" data='{"value":"Kisvizslaktanya","state":"Baranya"}'>Kisvizslaktanya</div>
<div class="option" data='{"value":"Kobanya","state":"Baranya"}'>Kobanya</div>
<div class="option" data='{"value":"Kobleny","state":"Baranya"}'>Kobleny</div>
<div class="option" data='{"value":"Kokeny","state":"Baranya"}'>Kokeny</div>
<div class="option" data='{"value":"Kokenyi Puszta","state":"Baranya"}'>Kokenyi Puszta</div>
<div class="option" data='{"value":"Kokenypuszta","state":"Baranya"}'>Kokenypuszta</div>
<div class="option" data='{"value":"Kolked","state":"Baranya"}'>Kolked</div>
<div class="option" data='{"value":"Kolkedi Csarda","state":"Baranya"}'>Kolkedi Csarda</div>
<div class="option" data='{"value":"Kolkedi Tanya","state":"Baranya"}'>Kolkedi Tanya</div>
<div class="option" data='{"value":"Komlo","state":"Baranya"}'>Komlo</div>
<div class="option" data='{"value":"Konstanczermalom","state":"Baranya"}'>Konstanczermalom</div>
<div class="option" data='{"value":"Kopalicadulo","state":"Baranya"}'>Kopalicadulo</div>
<div class="option" data='{"value":"Koparhat","state":"Baranya"}'>Koparhat</div>
<div class="option" data='{"value":"Kopaszvolgy","state":"Baranya"}'>Kopaszvolgy</div>
<div class="option" data='{"value":"Korcsanypuszta","state":"Baranya"}'>Korcsanypuszta</div>
<div class="option" data='{"value":"Korcsonye","state":"Baranya"}'>Korcsonye</div>
<div class="option" data='{"value":"Korcsonyepuszta","state":"Baranya"}'>Korcsonyepuszta</div>
<div class="option" data='{"value":"Koros","state":"Baranya"}'>Koros</div>
<div class="option" data='{"value":"Korpad","state":"Baranya"}'>Korpad</div>
<div class="option" data='{"value":"Kovacshida","state":"Baranya"}'>Kovacshida</div>
<div class="option" data='{"value":"Kovacsmalom","state":"Baranya"}'>Kovacsmalom</div>
<div class="option" data='{"value":"Kovacsszenaja","state":"Baranya"}'>Kovacsszenaja</div>
<div class="option" data='{"value":"Kovacstanya","state":"Baranya"}'>Kovacstanya</div>
<div class="option" data='{"value":"Kovagoszollos","state":"Baranya"}'>Kovagoszollos</div>
<div class="option" data='{"value":"Kovagoszolos","state":"Baranya"}'>Kovagoszolos</div>
<div class="option" data='{"value":"Kovagotottos","state":"Baranya"}'>Kovagotottos</div>
<div class="option" data='{"value":"Kovesteto","state":"Baranya"}'>Kovesteto</div>
<div class="option" data='{"value":"Kozarmisleny","state":"Baranya"}'>Kozarmisleny</div>
<div class="option" data='{"value":"Kozepmalom","state":"Baranya"}'>Kozepmalom</div>
<div class="option" data='{"value":"Kozepso Horvathmalom","state":"Baranya"}'>Kozepso Horvathmalom</div>
<div class="option" data='{"value":"Kozepsomalom","state":"Baranya"}'>Kozepsomalom</div>
<div class="option" data='{"value":"Kozepszigeti Tanyak","state":"Baranya"}'>Kozepszigeti Tanyak</div>
<div class="option" data='{"value":"Kremsbergermalom","state":"Baranya"}'>Kremsbergermalom</div>
<div class="option" data='{"value":"Kriksztanya","state":"Baranya"}'>Kriksztanya</div>
<div class="option" data='{"value":"Kulsotanya","state":"Baranya"}'>Kulsotanya</div>
<div class="option" data='{"value":"Kulsotanyak","state":"Baranya"}'>Kulsotanyak</div>
<div class="option" data='{"value":"Kurucpuszta","state":"Baranya"}'>Kurucpuszta</div>
<div class="option" data='{"value":"Kutas","state":"Baranya"}'>Kutas</div>
<div class="option" data='{"value":"Kutjaras","state":"Baranya"}'>Kutjaras</div>
<div class="option" data='{"value":"Kutyanszki","state":"Baranya"}'>Kutyanszki</div>
<div class="option" data='{"value":"Lajosfapuszta","state":"Baranya"}'>Lajosfapuszta</div>
<div class="option" data='{"value":"Lajoshaza","state":"Baranya"}'>Lajoshaza</div>
<div class="option" data='{"value":"Lajosmajor","state":"Baranya"}'>Lajosmajor</div>
<div class="option" data='{"value":"Lajospuszta","state":"Baranya"}'>Lajospuszta</div>
<div class="option" data='{"value":"Lajostanya","state":"Baranya"}'>Lajostanya</div>
<div class="option" data='{"value":"Lakatosmalom","state":"Baranya"}'>Lakatosmalom</div>
<div class="option" data='{"value":"Lampasvolgy","state":"Baranya"}'>Lampasvolgy</div>
<div class="option" data='{"value":"Lanka","state":"Baranya"}'>Lanka</div>
<div class="option" data='{"value":"Lanycsok","state":"Baranya"}'>Lanycsok</div>
<div class="option" data='{"value":"Lapancsa","state":"Baranya"}'>Lapancsa</div>
<div class="option" data='{"value":"Laposmezo","state":"Baranya"}'>Laposmezo</div>
<div class="option" data='{"value":"Laszlomalom","state":"Baranya"}'>Laszlomalom</div>
<div class="option" data='{"value":"Laufercsarda","state":"Baranya"}'>Laufercsarda</div>
<div class="option" data='{"value":"Leneskert","state":"Baranya"}'>Leneskert</div>
<div class="option" data='{"value":"Levenyetanya","state":"Baranya"}'>Levenyetanya</div>
<div class="option" data='{"value":"Liget","state":"Baranya"}'>Liget</div>
<div class="option" data='{"value":"Ligeti Puszta","state":"Baranya"}'>Ligeti Puszta</div>
<div class="option" data='{"value":"Ligettelep","state":"Baranya"}'>Ligettelep</div>
<div class="option" data='{"value":"Lijosmajor","state":"Baranya"}'>Lijosmajor</div>
<div class="option" data='{"value":"Lippo","state":"Baranya"}'>Lippo</div>
<div class="option" data='{"value":"Liptod","state":"Baranya"}'>Liptod</div>
<div class="option" data='{"value":"Liptodpuszta","state":"Baranya"}'>Liptodpuszta</div>
<div class="option" data='{"value":"Lityok","state":"Baranya"}'>Lityok</div>
<div class="option" data='{"value":"Livadapuszta","state":"Baranya"}'>Livadapuszta</div>
<div class="option" data='{"value":"Livodapuszta","state":"Baranya"}'>Livodapuszta</div>
<div class="option" data='{"value":"Lorinctanya","state":"Baranya"}'>Lorinctanya</div>
<div class="option" data='{"value":"Lothard","state":"Baranya"}'>Lothard</div>
<div class="option" data='{"value":"Lovaszhetany","state":"Baranya"}'>Lovaszhetany</div>
<div class="option" data='{"value":"Lovaszheteny","state":"Baranya"}'>Lovaszheteny</div>
<div class="option" data='{"value":"Luischthal","state":"Baranya"}'>Luischthal</div>
<div class="option" data='{"value":"Lulu","state":"Baranya"}'>Lulu</div>
<div class="option" data='{"value":"Lulupuszta","state":"Baranya"}'>Lulupuszta</div>
<div class="option" data='{"value":"Luzsok","state":"Baranya"}'>Luzsok</div>
<div class="option" data='{"value":"Magocs","state":"Baranya"}'>Magocs</div>
<div class="option" data='{"value":"Magyarboly","state":"Baranya"}'>Magyarboly</div>
<div class="option" data='{"value":"Magyaregregy","state":"Baranya"}'>Magyaregregy</div>
<div class="option" data='{"value":"Magyarhertelend","state":"Baranya"}'>Magyarhertelend</div>
<div class="option" data='{"value":"Magyarlukafa","state":"Baranya"}'>Magyarlukafa</div>
<div class="option" data='{"value":"Magyarmecske","state":"Baranya"}'>Magyarmecske</div>
<div class="option" data='{"value":"Magyarsarlos","state":"Baranya"}'>Magyarsarlos</div>
<div class="option" data='{"value":"Magyarszek","state":"Baranya"}'>Magyarszek</div>
<div class="option" data='{"value":"Magyartelek","state":"Baranya"}'>Magyartelek</div>
<div class="option" data='{"value":"Mailathpuszta","state":"Baranya"}'>Mailathpuszta</div>
<div class="option" data='{"value":"Majlathpuszta","state":"Baranya"}'>Majlathpuszta</div>
<div class="option" data='{"value":"Majs","state":"Baranya"}'>Majs</div>
<div class="option" data='{"value":"Makardulo","state":"Baranya"}'>Makardulo</div>
<div class="option" data='{"value":"Malmok","state":"Baranya"}'>Malmok</div>
<div class="option" data='{"value":"Malomber","state":"Baranya"}'>Malomber</div>
<div class="option" data='{"value":"Malomdulo","state":"Baranya"}'>Malomdulo</div>
<div class="option" data='{"value":"Malomhegy","state":"Baranya"}'>Malomhegy</div>
<div class="option" data='{"value":"Malomidulo","state":"Baranya"}'>Malomidulo</div>
<div class="option" data='{"value":"Manfa","state":"Baranya"}'>Manfa</div>
<div class="option" data='{"value":"Maraza","state":"Baranya"}'>Maraza</div>
<div class="option" data='{"value":"Marazapuszta","state":"Baranya"}'>Marazapuszta</div>
<div class="option" data='{"value":"Marevar","state":"Baranya"}'>Marevar</div>
<div class="option" data='{"value":"Marfa","state":"Baranya"}'>Marfa</div>
<div class="option" data='{"value":"Mariagyud","state":"Baranya"}'>Mariagyud</div>
<div class="option" data='{"value":"Mariagyudi Tanya","state":"Baranya"}'>Mariagyudi Tanya</div>
<div class="option" data='{"value":"Mariahegy","state":"Baranya"}'>Mariahegy</div>
<div class="option" data='{"value":"Mariakemend","state":"Baranya"}'>Mariakemend</div>
<div class="option" data='{"value":"Mariamajor","state":"Baranya"}'>Mariamajor</div>
<div class="option" data='{"value":"Markoc","state":"Baranya"}'>Markoc</div>
<div class="option" data='{"value":"Marocsa","state":"Baranya"}'>Marocsa</div>
<div class="option" data='{"value":"Marok","state":"Baranya"}'>Marok</div>
<div class="option" data='{"value":"Marotszentmarton","state":"Baranya"}'>Marotszentmarton</div>
<div class="option" data='{"value":"Martonfa","state":"Baranya"}'>Martonfa</div>
<div class="option" data='{"value":"Martonhegy","state":"Baranya"}'>Martonhegy</div>
<div class="option" data='{"value":"Matildmajor","state":"Baranya"}'>Matildmajor</div>
<div class="option" data='{"value":"Matty","state":"Baranya"}'>Matty</div>
<div class="option" data='{"value":"Mattyi Tanyak","state":"Baranya"}'>Mattyi Tanyak</div>
<div class="option" data='{"value":"Maza","state":"Baranya"}'>Maza</div>
<div class="option" data='{"value":"Mazaszaszvar","state":"Baranya"}'>Mazaszaszvar</div>
<div class="option" data='{"value":"Mecsekfalu","state":"Baranya"}'>Mecsekfalu</div>
<div class="option" data='{"value":"Mecsekjanosi","state":"Baranya"}'>Mecsekjanosi</div>
<div class="option" data='{"value":"Mecsekjanosi Puszta","state":"Baranya"}'>Mecsekjanosi Puszta</div>
<div class="option" data='{"value":"Mecseknadasd","state":"Baranya"}'>Mecseknadasd</div>
<div class="option" data='{"value":"Mecsekpoloske","state":"Baranya"}'>Mecsekpoloske</div>
<div class="option" data='{"value":"Mecsekrakos","state":"Baranya"}'>Mecsekrakos</div>
<div class="option" data='{"value":"Mecsekszakal","state":"Baranya"}'>Mecsekszakal</div>
<div class="option" data='{"value":"Meggyesytanya","state":"Baranya"}'>Meggyesytanya</div>
<div class="option" data='{"value":"Megyefa","state":"Baranya"}'>Megyefa</div>
<div class="option" data='{"value":"Megyefaciganysor","state":"Baranya"}'>Megyefaciganysor</div>
<div class="option" data='{"value":"Mekenyes","state":"Baranya"}'>Mekenyes</div>
<div class="option" data='{"value":"Mekenyesi Tanya","state":"Baranya"}'>Mekenyesi Tanya</div>
<div class="option" data='{"value":"Melegmajdulo","state":"Baranya"}'>Melegmajdulo</div>
<div class="option" data='{"value":"Merenye","state":"Baranya"}'>Merenye</div>
<div class="option" data='{"value":"Messzelato","state":"Baranya"}'>Messzelato</div>
<div class="option" data='{"value":"Meszarosmalom","state":"Baranya"}'>Meszarosmalom</div>
<div class="option" data='{"value":"Mezod","state":"Baranya"}'>Mezod</div>
<div class="option" data='{"value":"Mezodi Tanya","state":"Baranya"}'>Mezodi Tanya</div>
<div class="option" data='{"value":"Mezodipuszta","state":"Baranya"}'>Mezodipuszta</div>
<div class="option" data='{"value":"Mihaly Puszta","state":"Baranya"}'>Mihaly Puszta</div>
<div class="option" data='{"value":"Mihalymajor","state":"Baranya"}'>Mihalymajor</div>
<div class="option" data='{"value":"Miklostanya","state":"Baranya"}'>Miklostanya</div>
<div class="option" data='{"value":"Mikohaza","state":"Baranya"}'>Mikohaza</div>
<div class="option" data='{"value":"Mindszentgodisa","state":"Baranya"}'>Mindszentgodisa</div>
<div class="option" data='{"value":"Miskahaza","state":"Baranya"}'>Miskahaza</div>
<div class="option" data='{"value":"Mitlichtanya","state":"Baranya"}'>Mitlichtanya</div>
<div class="option" data='{"value":"Mogyoros","state":"Baranya"}'>Mogyoros</div>
<div class="option" data='{"value":"Mogyorosdulo","state":"Baranya"}'>Mogyorosdulo</div>
<div class="option" data='{"value":"Mohacs","state":"Baranya"}'>Mohacs</div>
<div class="option" data='{"value":"Mokardulo","state":"Baranya"}'>Mokardulo</div>
<div class="option" data='{"value":"Molnartanya","state":"Baranya"}'>Molnartanya</div>
<div class="option" data='{"value":"Molvany","state":"Baranya"}'>Molvany</div>
<div class="option" data='{"value":"Molvanyhidpuszta","state":"Baranya"}'>Molvanyhidpuszta</div>
<div class="option" data='{"value":"Monosokor","state":"Baranya"}'>Monosokor</div>
<div class="option" data='{"value":"Monosokori Tanya","state":"Baranya"}'>Monosokori Tanya</div>
<div class="option" data='{"value":"Monyorod","state":"Baranya"}'>Monyorod</div>
<div class="option" data='{"value":"Monyorodpuszta","state":"Baranya"}'>Monyorodpuszta</div>
<div class="option" data='{"value":"Monyoroska","state":"Baranya"}'>Monyoroska</div>
<div class="option" data='{"value":"Morevarifurdotelep","state":"Baranya"}'>Morevarifurdotelep</div>
<div class="option" data='{"value":"Mostohatanya","state":"Baranya"}'>Mostohatanya</div>
<div class="option" data='{"value":"Mozsgo","state":"Baranya"}'>Mozsgo</div>
<div class="option" data='{"value":"Nadasytelep","state":"Baranya"}'>Nadasytelep</div>
<div class="option" data='{"value":"Nadosytelep","state":"Baranya"}'>Nadosytelep</div>
<div class="option" data='{"value":"Nagyataditelep","state":"Baranya"}'>Nagyataditelep</div>
<div class="option" data='{"value":"Nagybicserd","state":"Baranya"}'>Nagybicserd</div>
<div class="option" data='{"value":"Nagybudmer","state":"Baranya"}'>Nagybudmer</div>
<div class="option" data='{"value":"Nagycsany","state":"Baranya"}'>Nagycsany</div>
<div class="option" data='{"value":"Nagydobsza","state":"Baranya"}'>Nagydobsza</div>
<div class="option" data='{"value":"Nagyharsany","state":"Baranya"}'>Nagyharsany</div>
<div class="option" data='{"value":"Nagyhosszuret","state":"Baranya"}'>Nagyhosszuret</div>
<div class="option" data='{"value":"Nagykozar","state":"Baranya"}'>Nagykozar</div>
<div class="option" data='{"value":"Nagymatetanya","state":"Baranya"}'>Nagymatetanya</div>
<div class="option" data='{"value":"Nagymezo","state":"Baranya"}'>Nagymezo</div>
<div class="option" data='{"value":"Nagynyarad","state":"Baranya"}'>Nagynyarad</div>
<div class="option" data='{"value":"Nagypall","state":"Baranya"}'>Nagypall</div>
<div class="option" data='{"value":"Nagypeterd","state":"Baranya"}'>Nagypeterd</div>
<div class="option" data='{"value":"Nagysarosto","state":"Baranya"}'>Nagysarosto</div>
<div class="option" data='{"value":"Nagyszigettanya","state":"Baranya"}'>Nagyszigettanya</div>
<div class="option" data='{"value":"Nagytotfalu","state":"Baranya"}'>Nagytotfalu</div>
<div class="option" data='{"value":"Nagyvaty","state":"Baranya"}'>Nagyvaty</div>
<div class="option" data='{"value":"Nandorliget","state":"Baranya"}'>Nandorliget</div>
<div class="option" data='{"value":"Neidharttanya","state":"Baranya"}'>Neidharttanya</div>
<div class="option" data='{"value":"Nemero","state":"Baranya"}'>Nemero</div>
<div class="option" data='{"value":"Nemeropuszta","state":"Baranya"}'>Nemeropuszta</div>
<div class="option" data='{"value":"Nemeske","state":"Baranya"}'>Nemeske</div>
<div class="option" data='{"value":"Nemeskepuszta","state":"Baranya"}'>Nemeskepuszta</div>
<div class="option" data='{"value":"Nemetboly","state":"Baranya"}'>Nemetboly</div>
<div class="option" data='{"value":"Nemeti","state":"Baranya"}'>Nemeti</div>
<div class="option" data='{"value":"Nemetlukafapuszta","state":"Baranya"}'>Nemetlukafapuszta</div>
<div class="option" data='{"value":"Nemetmarok","state":"Baranya"}'>Nemetmarok</div>
<div class="option" data='{"value":"Nemetpalkonya","state":"Baranya"}'>Nemetpalkonya</div>
<div class="option" data='{"value":"Nemetpalkonyai Puszta","state":"Baranya"}'>Nemetpalkonyai Puszta</div>
<div class="option" data='{"value":"Nyerges","state":"Baranya"}'>Nyerges</div>
<div class="option" data='{"value":"Nyergespuszta","state":"Baranya"}'>Nyergespuszta</div>
<div class="option" data='{"value":"Nyomja","state":"Baranya"}'>Nyomja</div>
<div class="option" data='{"value":"Nyugotszenterzsebet","state":"Baranya"}'>Nyugotszenterzsebet</div>
<div class="option" data='{"value":"Obanya","state":"Baranya"}'>Obanya</div>
<div class="option" data='{"value":"Obanyai Tanyak","state":"Baranya"}'>Obanyai Tanyak</div>
<div class="option" data='{"value":"Ocsard","state":"Baranya"}'>Ocsard</div>
<div class="option" data='{"value":"Odonvolgypuszta","state":"Baranya"}'>Odonvolgypuszta</div>
<div class="option" data='{"value":"Odonyvolgy","state":"Baranya"}'>Odonyvolgy</div>
<div class="option" data='{"value":"Ofalu","state":"Baranya"}'>Ofalu</div>
<div class="option" data='{"value":"Okorag","state":"Baranya"}'>Okorag</div>
<div class="option" data='{"value":"Okorvolgy","state":"Baranya"}'>Okorvolgy</div>
<div class="option" data='{"value":"Okovicstanya","state":"Baranya"}'>Okovicstanya</div>
<div class="option" data='{"value":"Olasz","state":"Baranya"}'>Olasz</div>
<div class="option" data='{"value":"Old","state":"Baranya"}'>Old</div>
<div class="option" data='{"value":"Olvolgy","state":"Baranya"}'>Olvolgy</div>
<div class="option" data='{"value":"Ontimajor","state":"Baranya"}'>Ontimajor</div>
<div class="option" data='{"value":"Ontipuszta","state":"Baranya"}'>Ontipuszta</div>
<div class="option" data='{"value":"Ordas","state":"Baranya"}'>Ordas</div>
<div class="option" data='{"value":"Oregbeke","state":"Baranya"}'>Oregbeke</div>
<div class="option" data='{"value":"Oreghegy","state":"Baranya"}'>Oreghegy</div>
<div class="option" data='{"value":"Oregpuszta","state":"Baranya"}'>Oregpuszta</div>
<div class="option" data='{"value":"Oregszollodulo","state":"Baranya"}'>Oregszollodulo</div>
<div class="option" data='{"value":"Orfu","state":"Baranya"}'>Orfu</div>
<div class="option" data='{"value":"Orhegy","state":"Baranya"}'>Orhegy</div>
<div class="option" data='{"value":"Ormanypuszta","state":"Baranya"}'>Ormanypuszta</div>
<div class="option" data='{"value":"Oroszlo","state":"Baranya"}'>Oroszlo</div>
<div class="option" data='{"value":"Ottmajo","state":"Baranya"}'>Ottmajo</div>
<div class="option" data='{"value":"Ottmajor","state":"Baranya"}'>Ottmajor</div>
<div class="option" data='{"value":"Ozdfalu","state":"Baranya"}'>Ozdfalu</div>
<div class="option" data='{"value":"Pafranyos","state":"Baranya"}'>Pafranyos</div>
<div class="option" data='{"value":"Pale","state":"Baranya"}'>Pale</div>
<div class="option" data='{"value":"Palkonya","state":"Baranya"}'>Palkonya</div>
<div class="option" data='{"value":"Palkonyapuszta","state":"Baranya"}'>Palkonyapuszta</div>
<div class="option" data='{"value":"Palmalom","state":"Baranya"}'>Palmalom</div>
<div class="option" data='{"value":"Palotabozsok","state":"Baranya"}'>Palotabozsok</div>
<div class="option" data='{"value":"Papcsarda","state":"Baranya"}'>Papcsarda</div>
<div class="option" data='{"value":"Papkerterdo","state":"Baranya"}'>Papkerterdo</div>
<div class="option" data='{"value":"Pappuszta","state":"Baranya"}'>Pappuszta</div>
<div class="option" data='{"value":"Paprad","state":"Baranya"}'>Paprad</div>
<div class="option" data='{"value":"Papradi Tanya","state":"Baranya"}'>Papradi Tanya</div>
<div class="option" data='{"value":"Papradipuszta","state":"Baranya"}'>Papradipuszta</div>
<div class="option" data='{"value":"Papradpuszta","state":"Baranya"}'>Papradpuszta</div>
<div class="option" data='{"value":"Papret","state":"Baranya"}'>Papret</div>
<div class="option" data='{"value":"Pata","state":"Baranya"}'>Pata</div>
<div class="option" data='{"value":"Patajpuszta","state":"Baranya"}'>Patajpuszta</div>
<div class="option" data='{"value":"Patakmalom","state":"Baranya"}'>Patakmalom</div>
<div class="option" data='{"value":"Patapoklosi","state":"Baranya"}'>Patapoklosi</div>
<div class="option" data='{"value":"Pazdany","state":"Baranya"}'>Pazdany</div>
<div class="option" data='{"value":"Pazseri Malom","state":"Baranya"}'>Pazseri Malom</div>
<div class="option" data='{"value":"Pazsir","state":"Baranya"}'>Pazsir</div>
<div class="option" data='{"value":"Pecsbagota","state":"Baranya"}'>Pecsbagota</div>
<div class="option" data='{"value":"Pecsbudafa","state":"Baranya"}'>Pecsbudafa</div>
<div class="option" data='{"value":"Pecsdevecser","state":"Baranya"}'>Pecsdevecser</div>
<div class="option" data='{"value":"Pecsudvard","state":"Baranya"}'>Pecsudvard</div>
<div class="option" data='{"value":"Pecsvarad","state":"Baranya"}'>Pecsvarad</div>
<div class="option" data='{"value":"Pellerd","state":"Baranya"}'>Pellerd</div>
<div class="option" data='{"value":"Pereked","state":"Baranya"}'>Pereked</div>
<div class="option" data='{"value":"Pergertanya","state":"Baranya"}'>Pergertanya</div>
<div class="option" data='{"value":"Pestimalom","state":"Baranya"}'>Pestimalom</div>
<div class="option" data='{"value":"Peterd","state":"Baranya"}'>Peterd</div>
<div class="option" data='{"value":"Peterdipuszta","state":"Baranya"}'>Peterdipuszta</div>
<div class="option" data='{"value":"Peterdpuszta","state":"Baranya"}'>Peterdpuszta</div>
<div class="option" data='{"value":"Peterfa","state":"Baranya"}'>Peterfa</div>
<div class="option" data='{"value":"Petocz","state":"Baranya"}'>Petocz</div>
<div class="option" data='{"value":"Petoczpuszta","state":"Baranya"}'>Petoczpuszta</div>
<div class="option" data='{"value":"Pettend","state":"Baranya"}'>Pettend</div>
<div class="option" data='{"value":"Pickpuszta","state":"Baranya"}'>Pickpuszta</div>
<div class="option" data='{"value":"Pisko","state":"Baranya"}'>Pisko</div>
<div class="option" data='{"value":"Pocsa","state":"Baranya"}'>Pocsa</div>
<div class="option" data='{"value":"Pogany","state":"Baranya"}'>Pogany</div>
<div class="option" data='{"value":"Poklosi","state":"Baranya"}'>Poklosi</div>
<div class="option" data='{"value":"Polgarpuszta","state":"Baranya"}'>Polgarpuszta</div>
<div class="option" data='{"value":"Poretanya","state":"Baranya"}'>Poretanya</div>
<div class="option" data='{"value":"Porond","state":"Baranya"}'>Porond</div>
<div class="option" data='{"value":"Poroszlodulo","state":"Baranya"}'>Poroszlodulo</div>
<div class="option" data='{"value":"Poroszloidulo","state":"Baranya"}'>Poroszloidulo</div>
<div class="option" data='{"value":"Postaszallas","state":"Baranya"}'>Postaszallas</div>
<div class="option" data='{"value":"Poszeripuszta","state":"Baranya"}'>Poszeripuszta</div>
<div class="option" data='{"value":"Psikpuszta","state":"Baranya"}'>Psikpuszta</div>
<div class="option" data='{"value":"Puspokbogad","state":"Baranya"}'>Puspokbogad</div>
<div class="option" data='{"value":"Puspokboly","state":"Baranya"}'>Puspokboly</div>
<div class="option" data='{"value":"Puspoklak","state":"Baranya"}'>Puspoklak</div>
<div class="option" data='{"value":"Puspokmarok","state":"Baranya"}'>Puspokmarok</div>
<div class="option" data='{"value":"Puspoknadasd","state":"Baranya"}'>Puspoknadasd</div>
<div class="option" data='{"value":"Puspokszenterzsebet","state":"Baranya"}'>Puspokszenterzsebet</div>
<div class="option" data='{"value":"Puspokszentlaszlo","state":"Baranya"}'>Puspokszentlaszlo</div>
<div class="option" data='{"value":"Pusztadulo","state":"Baranya"}'>Pusztadulo</div>
<div class="option" data='{"value":"Pusztakisfalu","state":"Baranya"}'>Pusztakisfalu</div>
<div class="option" data='{"value":"Pusztamalom","state":"Baranya"}'>Pusztamalom</div>
<div class="option" data='{"value":"Rabenschwanz","state":"Baranya"}'>Rabenschwanz</div>
<div class="option" data='{"value":"Raczokszollo","state":"Baranya"}'>Raczokszollo</div>
<div class="option" data='{"value":"Radfa","state":"Baranya"}'>Radfa</div>
<div class="option" data='{"value":"Radfalva","state":"Baranya"}'>Radfalva</div>
<div class="option" data='{"value":"Radfapuszta","state":"Baranya"}'>Radfapuszta</div>
<div class="option" data='{"value":"Raffaitanya","state":"Baranya"}'>Raffaitanya</div>
<div class="option" data='{"value":"Ranodfa","state":"Baranya"}'>Ranodfa</div>
<div class="option" data='{"value":"Ranodfapuszta","state":"Baranya"}'>Ranodfapuszta</div>
<div class="option" data='{"value":"Regenye","state":"Baranya"}'>Regenye</div>
<div class="option" data='{"value":"Rektanya","state":"Baranya"}'>Rektanya</div>
<div class="option" data='{"value":"Retidulo","state":"Baranya"}'>Retidulo</div>
<div class="option" data='{"value":"Retilegelo","state":"Baranya"}'>Retilegelo</div>
<div class="option" data='{"value":"Revfalu","state":"Baranya"}'>Revfalu</div>
<div class="option" data='{"value":"Rigoderdulo","state":"Baranya"}'>Rigoderdulo</div>
<div class="option" data='{"value":"Rigoderteto","state":"Baranya"}'>Rigoderteto</div>
<div class="option" data='{"value":"Rigopuszta","state":"Baranya"}'>Rigopuszta</div>
<div class="option" data='{"value":"Riha","state":"Baranya"}'>Riha</div>
<div class="option" data='{"value":"Riticspuszta","state":"Baranya"}'>Riticspuszta</div>
<div class="option" data='{"value":"Romonya","state":"Baranya"}'>Romonya</div>
<div class="option" data='{"value":"Rozsafa","state":"Baranya"}'>Rozsafa</div>
<div class="option" data='{"value":"Rozsapuszta","state":"Baranya"}'>Rozsapuszta</div>
<div class="option" data='{"value":"Ruckerakna","state":"Baranya"}'>Ruckerakna</div>
<div class="option" data='{"value":"Ruzsama","state":"Baranya"}'>Ruzsama</div>
<div class="option" data='{"value":"Samod","state":"Baranya"}'>Samod</div>
<div class="option" data='{"value":"Sandordulo","state":"Baranya"}'>Sandordulo</div>
<div class="option" data='{"value":"Santamalom","state":"Baranya"}'>Santamalom</div>
<div class="option" data='{"value":"Saras","state":"Baranya"}'>Saras</div>
<div class="option" data='{"value":"Sargodre","state":"Baranya"}'>Sargodre</div>
<div class="option" data='{"value":"Sarhat","state":"Baranya"}'>Sarhat</div>
<div class="option" data='{"value":"Saripuszta","state":"Baranya"}'>Saripuszta</div>
<div class="option" data='{"value":"Sarok","state":"Baranya"}'>Sarok</div>
<div class="option" data='{"value":"Saros","state":"Baranya"}'>Saros</div>
<div class="option" data='{"value":"Sasd","state":"Baranya"}'>Sasd</div>
<div class="option" data='{"value":"Sasretpuszta","state":"Baranya"}'>Sasretpuszta</div>
<div class="option" data='{"value":"Satorhely","state":"Baranya"}'>Satorhely</div>
<div class="option" data='{"value":"Schemelzermalom","state":"Baranya"}'>Schemelzermalom</div>
<div class="option" data='{"value":"Schmelczermalom","state":"Baranya"}'>Schmelczermalom</div>
<div class="option" data='{"value":"Schneeberg","state":"Baranya"}'>Schneeberg</div>
<div class="option" data='{"value":"Schrempfmalom","state":"Baranya"}'>Schrempfmalom</div>
<div class="option" data='{"value":"Schullertanya","state":"Baranya"}'>Schullertanya</div>
<div class="option" data='{"value":"Sebespuszta","state":"Baranya"}'>Sebespuszta</div>
<div class="option" data='{"value":"Sellye","state":"Baranya"}'>Sellye</div>
<div class="option" data='{"value":"Siklos","state":"Baranya"}'>Siklos</div>
<div class="option" data='{"value":"Siklosbodony","state":"Baranya"}'>Siklosbodony</div>
<div class="option" data='{"value":"Siklosnagyfalu","state":"Baranya"}'>Siklosnagyfalu</div>
<div class="option" data='{"value":"Sikonda","state":"Baranya"}'>Sikonda</div>
<div class="option" data='{"value":"Sikondagyogyfurdo","state":"Baranya"}'>Sikondagyogyfurdo</div>
<div class="option" data='{"value":"Sikotapuszta","state":"Baranya"}'>Sikotapuszta</div>
<div class="option" data='{"value":"Sneberg","state":"Baranya"}'>Sneberg</div>
<div class="option" data='{"value":"Somberek","state":"Baranya"}'>Somberek</div>
<div class="option" data='{"value":"Sombereki Tanyak","state":"Baranya"}'>Sombereki Tanyak</div>
<div class="option" data='{"value":"Somleny","state":"Baranya"}'>Somleny</div>
<div class="option" data='{"value":"Somogyapati","state":"Baranya"}'>Somogyapati</div>
<div class="option" data='{"value":"Somogyharsagy","state":"Baranya"}'>Somogyharsagy</div>
<div class="option" data='{"value":"Somogyhatvan","state":"Baranya"}'>Somogyhatvan</div>
<div class="option" data='{"value":"Somogyitanya","state":"Baranya"}'>Somogyitanya</div>
<div class="option" data='{"value":"Somogyviszlo","state":"Baranya"}'>Somogyviszlo</div>
<div class="option" data='{"value":"Sorkad","state":"Baranya"}'>Sorkad</div>
<div class="option" data='{"value":"Sormas","state":"Baranya"}'>Sormas</div>
<div class="option" data='{"value":"Sosvertike","state":"Baranya"}'>Sosvertike</div>
<div class="option" data='{"value":"Stefaniamajor","state":"Baranya"}'>Stefaniamajor</div>
<div class="option" data='{"value":"Sumony","state":"Baranya"}'>Sumony</div>
<div class="option" data='{"value":"Sumonypuszta","state":"Baranya"}'>Sumonypuszta</div>
<div class="option" data='{"value":"Szabad","state":"Baranya"}'>Szabad</div>
<div class="option" data='{"value":"Szabadja","state":"Baranya"}'>Szabadja</div>
<div class="option" data='{"value":"Szabadszallastanya","state":"Baranya"}'>Szabadszallastanya</div>
<div class="option" data='{"value":"Szabadszentkiraly","state":"Baranya"}'>Szabadszentkiraly</div>
<div class="option" data='{"value":"Szabas","state":"Baranya"}'>Szabas</div>
<div class="option" data='{"value":"Szabotanya","state":"Baranya"}'>Szabotanya</div>
<div class="option" data='{"value":"Szagy","state":"Baranya"}'>Szagy</div>
<div class="option" data='{"value":"Szajk","state":"Baranya"}'>Szajk</div>
<div class="option" data='{"value":"Szalanta","state":"Baranya"}'>Szalanta</div>
<div class="option" data='{"value":"Szalantatelep","state":"Baranya"}'>Szalantatelep</div>
<div class="option" data='{"value":"Szalatnak","state":"Baranya"}'>Szalatnak</div>
<div class="option" data='{"value":"Szaporca","state":"Baranya"}'>Szaporca</div>
<div class="option" data='{"value":"Szaporea","state":"Baranya"}'>Szaporea</div>
<div class="option" data='{"value":"Szarasz","state":"Baranya"}'>Szarasz</div>
<div class="option" data='{"value":"Szarazret","state":"Baranya"}'>Szarazret</div>
<div class="option" data='{"value":"Szaszvar","state":"Baranya"}'>Szaszvar</div>
<div class="option" data='{"value":"Szaszvarbanyatelep","state":"Baranya"}'>Szaszvarbanyatelep</div>
<div class="option" data='{"value":"Szaszvari Tanyak","state":"Baranya"}'>Szaszvari Tanyak</div>
<div class="option" data='{"value":"Szaszvolgy","state":"Baranya"}'>Szaszvolgy</div>
<div class="option" data='{"value":"Szatina","state":"Baranya"}'>Szatina</div>
<div class="option" data='{"value":"Szatmaritanya","state":"Baranya"}'>Szatmaritanya</div>
<div class="option" data='{"value":"Szava","state":"Baranya"}'>Szava</div>
<div class="option" data='{"value":"Szebeny","state":"Baranya"}'>Szebeny</div>
<div class="option" data='{"value":"Szederkeny","state":"Baranya"}'>Szederkeny</div>
<div class="option" data='{"value":"Szekelyszabar","state":"Baranya"}'>Szekelyszabar</div>
<div class="option" data='{"value":"Szekerek","state":"Baranya"}'>Szekerek</div>
<div class="option" data='{"value":"Szekerekpuszta","state":"Baranya"}'>Szekerekpuszta</div>
<div class="option" data='{"value":"Szello","state":"Baranya"}'>Szello</div>
<div class="option" data='{"value":"Szemely","state":"Baranya"}'>Szemely</div>
<div class="option" data='{"value":"Szemeretanya","state":"Baranya"}'>Szemeretanya</div>
<div class="option" data='{"value":"Szenas","state":"Baranya"}'>Szenas</div>
<div class="option" data='{"value":"Szenaspuszta","state":"Baranya"}'>Szenaspuszta</div>
<div class="option" data='{"value":"Szentdenes","state":"Baranya"}'>Szentdenes</div>
<div class="option" data='{"value":"Szentdienes","state":"Baranya"}'>Szentdienes</div>
<div class="option" data='{"value":"Szentdomjan","state":"Baranya"}'>Szentdomjan</div>
<div class="option" data='{"value":"Szentdomjan Kulsopuszta","state":"Baranya"}'>Szentdomjan Kulsopuszta</div>
<div class="option" data='{"value":"Szentdomjanpuszta","state":"Baranya"}'>Szentdomjanpuszta</div>
<div class="option" data='{"value":"Szentegat","state":"Baranya"}'>Szentegat</div>
<div class="option" data='{"value":"Szentegyedpuszta","state":"Baranya"}'>Szentegyedpuszta</div>
<div class="option" data='{"value":"Szentelep","state":"Baranya"}'>Szentelep</div>
<div class="option" data='{"value":"Szentimre","state":"Baranya"}'>Szentimre</div>
<div class="option" data='{"value":"Szentimre Alsopuszta","state":"Baranya"}'>Szentimre Alsopuszta</div>
<div class="option" data='{"value":"Szentimre Felsopuszta","state":"Baranya"}'>Szentimre Felsopuszta</div>
<div class="option" data='{"value":"Szentistvanmajor","state":"Baranya"}'>Szentistvanmajor</div>
<div class="option" data='{"value":"Szentkatalin","state":"Baranya"}'>Szentkatalin</div>
<div class="option" data='{"value":"Szentkutipuszta","state":"Baranya"}'>Szentkutipuszta</div>
<div class="option" data='{"value":"Szentkutpuszta","state":"Baranya"}'>Szentkutpuszta</div>
<div class="option" data='{"value":"Szentlaszlo","state":"Baranya"}'>Szentlaszlo</div>
<div class="option" data='{"value":"Szentlelek","state":"Baranya"}'>Szentlelek</div>
<div class="option" data='{"value":"Szentlelekpuszta","state":"Baranya"}'>Szentlelekpuszta</div>
<div class="option" data='{"value":"Szentlorinc","state":"Baranya"}'>Szentlorinc</div>
<div class="option" data='{"value":"Szentmargittapuszta","state":"Baranya"}'>Szentmargittapuszta</div>
<div class="option" data='{"value":"Szentmarton Ujpuszta","state":"Baranya"}'>Szentmarton Ujpuszta</div>
<div class="option" data='{"value":"Szentmartonpuszta","state":"Baranya"}'>Szentmartonpuszta</div>
<div class="option" data='{"value":"Szentmihalyfapuszta","state":"Baranya"}'>Szentmihalyfapuszta</div>
<div class="option" data='{"value":"Szentmiklospuszta","state":"Baranya"}'>Szentmiklospuszta</div>
<div class="option" data='{"value":"Szentpal","state":"Baranya"}'>Szentpal</div>
<div class="option" data='{"value":"Szentpalpuszta","state":"Baranya"}'>Szentpalpuszta</div>
<div class="option" data='{"value":"Sziebertpuszta","state":"Baranya"}'>Sziebertpuszta</div>
<div class="option" data='{"value":"Szigetvar","state":"Baranya"}'>Szigetvar</div>
<div class="option" data='{"value":"Szilagy","state":"Baranya"}'>Szilagy</div>
<div class="option" data='{"value":"Szilagykispuszta","state":"Baranya"}'>Szilagykispuszta</div>
<div class="option" data='{"value":"Szilaspuszta","state":"Baranya"}'>Szilaspuszta</div>
<div class="option" data='{"value":"Szilastanya","state":"Baranya"}'>Szilastanya</div>
<div class="option" data='{"value":"Szilhattelep","state":"Baranya"}'>Szilhattelep</div>
<div class="option" data='{"value":"Szilvas","state":"Baranya"}'>Szilvas</div>
<div class="option" data='{"value":"Szilvasitanya","state":"Baranya"}'>Szilvasitanya</div>
<div class="option" data='{"value":"Szkoko","state":"Baranya"}'>Szkoko</div>
<div class="option" data='{"value":"Szkokodulo","state":"Baranya"}'>Szkokodulo</div>
<div class="option" data='{"value":"Szoke","state":"Baranya"}'>Szoke</div>
<div class="option" data='{"value":"Szoked","state":"Baranya"}'>Szoked</div>
<div class="option" data='{"value":"Szokedi Puszta","state":"Baranya"}'>Szokedi Puszta</div>
<div class="option" data='{"value":"Szokedpuszta","state":"Baranya"}'>Szokedpuszta</div>
<div class="option" data='{"value":"Szopogato","state":"Baranya"}'>Szopogato</div>
<div class="option" data='{"value":"Szoradmalom","state":"Baranya"}'>Szoradmalom</div>
<div class="option" data='{"value":"Szoreny","state":"Baranya"}'>Szoreny</div>
<div class="option" data='{"value":"Sztankovanszkytanya","state":"Baranya"}'>Sztankovanszkytanya</div>
<div class="option" data='{"value":"Szuliman","state":"Baranya"}'>Szuliman</div>
<div class="option" data='{"value":"Szur","state":"Baranya"}'>Szur</div>
<div class="option" data='{"value":"Tarcsa","state":"Baranya"}'>Tarcsa</div>
<div class="option" data='{"value":"Tarcsapuszta","state":"Baranya"}'>Tarcsapuszta</div>
<div class="option" data='{"value":"Tarros","state":"Baranya"}'>Tarros</div>
<div class="option" data='{"value":"Teglahaztanya","state":"Baranya"}'>Teglahaztanya</div>
<div class="option" data='{"value":"Tekeres","state":"Baranya"}'>Tekeres</div>
<div class="option" data='{"value":"Tekes","state":"Baranya"}'>Tekes</div>
<div class="option" data='{"value":"Teklafalu","state":"Baranya"}'>Teklafalu</div>
<div class="option" data='{"value":"Teleger","state":"Baranya"}'>Teleger</div>
<div class="option" data='{"value":"Telek","state":"Baranya"}'>Telek</div>
<div class="option" data='{"value":"Telekipuszta","state":"Baranya"}'>Telekipuszta</div>
<div class="option" data='{"value":"Telekitanya","state":"Baranya"}'>Telekitanya</div>
<div class="option" data='{"value":"Temetodulo","state":"Baranya"}'>Temetodulo</div>
<div class="option" data='{"value":"Tengeri","state":"Baranya"}'>Tengeri</div>
<div class="option" data='{"value":"Terecseny","state":"Baranya"}'>Terecseny</div>
<div class="option" data='{"value":"Terecsenypuszta","state":"Baranya"}'>Terecsenypuszta</div>
<div class="option" data='{"value":"Terehegy","state":"Baranya"}'>Terehegy</div>
<div class="option" data='{"value":"Terehegyi Puszta","state":"Baranya"}'>Terehegyi Puszta</div>
<div class="option" data='{"value":"Tesenfa","state":"Baranya"}'>Tesenfa</div>
<div class="option" data='{"value":"Tischlertanya","state":"Baranya"}'>Tischlertanya</div>
<div class="option" data='{"value":"Tisztasdulo","state":"Baranya"}'>Tisztasdulo</div>
<div class="option" data='{"value":"Tofu","state":"Baranya"}'>Tofu</div>
<div class="option" data='{"value":"Tonimajor","state":"Baranya"}'>Tonimajor</div>
<div class="option" data='{"value":"Tormas","state":"Baranya"}'>Tormas</div>
<div class="option" data='{"value":"Tortyogo","state":"Baranya"}'>Tortyogo</div>
<div class="option" data='{"value":"Totokfoldje","state":"Baranya"}'>Totokfoldje</div>
<div class="option" data='{"value":"Totszentgyogy","state":"Baranya"}'>Totszentgyogy</div>
<div class="option" data='{"value":"Tottos","state":"Baranya"}'>Tottos</div>
<div class="option" data='{"value":"Totvar","state":"Baranya"}'>Totvar</div>
<div class="option" data='{"value":"Tovolgy","state":"Baranya"}'>Tovolgy</div>
<div class="option" data='{"value":"Trefortpuszta","state":"Baranya"}'>Trefortpuszta</div>
<div class="option" data='{"value":"Trinitas","state":"Baranya"}'>Trinitas</div>
<div class="option" data='{"value":"Trischlerpuszta","state":"Baranya"}'>Trischlerpuszta</div>
<div class="option" data='{"value":"Turbek","state":"Baranya"}'>Turbek</div>
<div class="option" data='{"value":"Turbekpuszta","state":"Baranya"}'>Turbekpuszta</div>
<div class="option" data='{"value":"Turony","state":"Baranya"}'>Turony</div>
<div class="option" data='{"value":"Tuskes","state":"Baranya"}'>Tuskes</div>
<div class="option" data='{"value":"Tuskopuszta","state":"Baranya"}'>Tuskopuszta</div>
<div class="option" data='{"value":"Tuskospuszta","state":"Baranya"}'>Tuskospuszta</div>
<div class="option" data='{"value":"Udvar","state":"Baranya"}'>Udvar</div>
<div class="option" data='{"value":"Ujakna","state":"Baranya"}'>Ujakna</div>
<div class="option" data='{"value":"Ujfok","state":"Baranya"}'>Ujfok</div>
<div class="option" data='{"value":"Ujistallo","state":"Baranya"}'>Ujistallo</div>
<div class="option" data='{"value":"Ujistallopuszta","state":"Baranya"}'>Ujistallopuszta</div>
<div class="option" data='{"value":"Ujlivadapuszta","state":"Baranya"}'>Ujlivadapuszta</div>
<div class="option" data='{"value":"Ujmajor","state":"Baranya"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujmohacs","state":"Baranya"}'>Ujmohacs</div>
<div class="option" data='{"value":"Ujpetre","state":"Baranya"}'>Ujpetre</div>
<div class="option" data='{"value":"Ujpogany","state":"Baranya"}'>Ujpogany</div>
<div class="option" data='{"value":"Ujpuszta","state":"Baranya"}'>Ujpuszta</div>
<div class="option" data='{"value":"Ujtelep","state":"Baranya"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujvaritanya","state":"Baranya"}'>Ujvaritanya</div>
<div class="option" data='{"value":"Urbanikmalom","state":"Baranya"}'>Urbanikmalom</div>
<div class="option" data='{"value":"Uszog","state":"Baranya"}'>Uszog</div>
<div class="option" data='{"value":"Uszogpuszta","state":"Baranya"}'>Uszogpuszta</div>
<div class="option" data='{"value":"Vacitanya","state":"Baranya"}'>Vacitanya</div>
<div class="option" data='{"value":"Vaczitanya","state":"Baranya"}'>Vaczitanya</div>
<div class="option" data='{"value":"Vadaszcsarda","state":"Baranya"}'>Vadaszcsarda</div>
<div class="option" data='{"value":"Vagat","state":"Baranya"}'>Vagat</div>
<div class="option" data='{"value":"Vagohid","state":"Baranya"}'>Vagohid</div>
<div class="option" data='{"value":"Vagot","state":"Baranya"}'>Vagot</div>
<div class="option" data='{"value":"Vagotpuszta","state":"Baranya"}'>Vagotpuszta</div>
<div class="option" data='{"value":"Vagott","state":"Baranya"}'>Vagott</div>
<div class="option" data='{"value":"Vajszlo","state":"Baranya"}'>Vajszlo</div>
<div class="option" data='{"value":"Vakcsa","state":"Baranya"}'>Vakcsa</div>
<div class="option" data='{"value":"Varad","state":"Baranya"}'>Varad</div>
<div class="option" data='{"value":"Varasd","state":"Baranya"}'>Varasd</div>
<div class="option" data='{"value":"Varga","state":"Baranya"}'>Varga</div>
<div class="option" data='{"value":"Vargapuszta","state":"Baranya"}'>Vargapuszta</div>
<div class="option" data='{"value":"Varoshegyidulo","state":"Baranya"}'>Varoshegyidulo</div>
<div class="option" data='{"value":"Vasarosbec","state":"Baranya"}'>Vasarosbec</div>
<div class="option" data='{"value":"Vasarosdombo","state":"Baranya"}'>Vasarosdombo</div>
<div class="option" data='{"value":"Vaskapu","state":"Baranya"}'>Vaskapu</div>
<div class="option" data='{"value":"Vaskapupuszta","state":"Baranya"}'>Vaskapupuszta</div>
<div class="option" data='{"value":"Vazsnok","state":"Baranya"}'>Vazsnok</div>
<div class="option" data='{"value":"Vejti","state":"Baranya"}'>Vejti</div>
<div class="option" data='{"value":"Vejtirev","state":"Baranya"}'>Vejtirev</div>
<div class="option" data='{"value":"Vekeny","state":"Baranya"}'>Vekeny</div>
<div class="option" data='{"value":"Veleny","state":"Baranya"}'>Veleny</div>
<div class="option" data='{"value":"Vemend","state":"Baranya"}'>Vemend</div>
<div class="option" data='{"value":"Versend","state":"Baranya"}'>Versend</div>
<div class="option" data='{"value":"Versendi Puszta","state":"Baranya"}'>Versendi Puszta</div>
<div class="option" data='{"value":"Vesszostelep","state":"Baranya"}'>Vesszostelep</div>
<div class="option" data='{"value":"Vidak","state":"Baranya"}'>Vidak</div>
<div class="option" data='{"value":"Vidakpuszta","state":"Baranya"}'>Vidakpuszta</div>
<div class="option" data='{"value":"Vigaszvar","state":"Baranya"}'>Vigaszvar</div>
<div class="option" data='{"value":"Villany","state":"Baranya"}'>Villany</div>
<div class="option" data='{"value":"Villanykovesd","state":"Baranya"}'>Villanykovesd</div>
<div class="option" data='{"value":"Viragos","state":"Baranya"}'>Viragos</div>
<div class="option" data='{"value":"Vitezipuszta","state":"Baranya"}'>Vitezipuszta</div>
<div class="option" data='{"value":"Vitezitelek","state":"Baranya"}'>Vitezitelek</div>
<div class="option" data='{"value":"Viteztelep","state":"Baranya"}'>Viteztelep</div>
<div class="option" data='{"value":"Vittmajor","state":"Baranya"}'>Vittmajor</div>
<div class="option" data='{"value":"Vizfo","state":"Baranya"}'>Vizfo</div>
<div class="option" data='{"value":"Vizkutmalom","state":"Baranya"}'>Vizkutmalom</div>
<div class="option" data='{"value":"Vizmuvek","state":"Baranya"}'>Vizmuvek</div>
<div class="option" data='{"value":"Vizslak","state":"Baranya"}'>Vizslak</div>
<div class="option" data='{"value":"Vo Malom","state":"Baranya"}'>Vo Malom</div>
<div class="option" data='{"value":"Vokany","state":"Baranya"}'>Vokany</div>
<div class="option" data='{"value":"Vokany Hengermalom","state":"Baranya"}'>Vokany Hengermalom</div>
<div class="option" data='{"value":"Vokanyi Hegy","state":"Baranya"}'>Vokanyi Hegy</div>
<div class="option" data='{"value":"Vokanyi Hengermalom","state":"Baranya"}'>Vokanyi Hengermalom</div>
<div class="option" data='{"value":"Voomalom","state":"Baranya"}'>Voomalom</div>
<div class="option" data='{"value":"Vorosakol","state":"Baranya"}'>Vorosakol</div>
<div class="option" data='{"value":"Vorosipuszta","state":"Baranya"}'>Vorosipuszta</div>
<div class="option" data='{"value":"Vorospuszta","state":"Baranya"}'>Vorospuszta</div>
<div class="option" data='{"value":"Vorostelep","state":"Baranya"}'>Vorostelep</div>
<div class="option" data='{"value":"Vorosvolgy","state":"Baranya"}'>Vorosvolgy</div>
<div class="option" data='{"value":"Wagnermalom","state":"Baranya"}'>Wagnermalom</div>
<div class="option" data='{"value":"Webermalom","state":"Baranya"}'>Webermalom</div>
<div class="option" data='{"value":"Wernermajor","state":"Baranya"}'>Wernermajor</div>
<div class="option" data='{"value":"Zador","state":"Baranya"}'>Zador</div>
<div class="option" data='{"value":"Zadorimalom","state":"Baranya"}'>Zadorimalom</div>
<div class="option" data='{"value":"Zadravectanyak","state":"Baranya"}'>Zadravectanyak</div>
<div class="option" data='{"value":"Zadravecztanya","state":"Baranya"}'>Zadravecztanya</div>
<div class="option" data='{"value":"Zalata","state":"Baranya"}'>Zalata</div>
<div class="option" data='{"value":"Zalogos","state":"Baranya"}'>Zalogos</div>
<div class="option" data='{"value":"Zalogospuszta","state":"Baranya"}'>Zalogospuszta</div>
<div class="option" data='{"value":"Zehi","state":"Baranya"}'>Zehi</div>
<div class="option" data='{"value":"Zehipuszta","state":"Baranya"}'>Zehipuszta</div>
<div class="option" data='{"value":"Zengovarkony","state":"Baranya"}'>Zengovarkony</div>
<div class="option" data='{"value":"Zobakpuszta","state":"Baranya"}'>Zobakpuszta</div>
<div class="option" data='{"value":"Zocsketelep","state":"Baranya"}'>Zocsketelep</div>
<div class="option" data='{"value":"Zok","state":"Baranya"}'>Zok</div>
<div class="option" data='{"value":"Zsemenye","state":"Baranya"}'>Zsemenye</div>
<div class="option" data='{"value":"Zsibot","state":"Baranya"}'>Zsibot</div>
<div class="option" data='{"value":"Zsiboti Szolok","state":"Baranya"}'>Zsiboti Szolok</div>
<div class="option" data='{"value":"Zsibotiszolohegy","state":"Baranya"}'>Zsibotiszolohegy</div>
<div class="option" data='{"value":"Zsinko","state":"Baranya"}'>Zsinko</div>
<div class="option" data='{"value":"Zsinko Csarda","state":"Baranya"}'>Zsinko Csarda</div>
<div class="option" data='{"value":"Zsuhoc","state":"Baranya"}'>Zsuhoc</div>
<div class="option" data='{"value":"Zsuhocz","state":"Baranya"}'>Zsuhocz</div>
<div class="option" id="option_end" data='{"value":"Zuhanyadulo","state":"Baranya"}'>Zuhanyadulo</div>

