<div class="option" data='{"value":"Acsas","state":"Hajdu-Bihar"}'>Acsas</div>
<div class="option" data='{"value":"Acsaspuszta","state":"Hajdu-Bihar"}'>Acsaspuszta</div>
<div class="option" data='{"value":"Acstanya","state":"Hajdu-Bihar"}'>Acstanya</div>
<div class="option" data='{"value":"Adamdulo","state":"Hajdu-Bihar"}'>Adamdulo</div>
<div class="option" data='{"value":"Adamtanya","state":"Hajdu-Bihar"}'>Adamtanya</div>
<div class="option" data='{"value":"Agotazug","state":"Hajdu-Bihar"}'>Agotazug</div>
<div class="option" data='{"value":"Akacdulo","state":"Hajdu-Bihar"}'>Akacdulo</div>
<div class="option" data='{"value":"Akasztofahegy","state":"Hajdu-Bihar"}'>Akasztofahegy</div>
<div class="option" data='{"value":"Akoldulo","state":"Hajdu-Bihar"}'>Akoldulo</div>
<div class="option" data='{"value":"Almasitanya","state":"Hajdu-Bihar"}'>Almasitanya</div>
<div class="option" data='{"value":"Almosd","state":"Hajdu-Bihar"}'>Almosd</div>
<div class="option" data='{"value":"Alomzug","state":"Hajdu-Bihar"}'>Alomzug</div>
<div class="option" data='{"value":"Alomzugtanya","state":"Hajdu-Bihar"}'>Alomzugtanya</div>
<div class="option" data='{"value":"Alsodulo","state":"Hajdu-Bihar"}'>Alsodulo</div>
<div class="option" data='{"value":"Alsofutak","state":"Hajdu-Bihar"}'>Alsofutak</div>
<div class="option" data='{"value":"Alsoreti Dulo","state":"Hajdu-Bihar"}'>Alsoreti Dulo</div>
<div class="option" data='{"value":"Alsoreti Tanyak","state":"Hajdu-Bihar"}'>Alsoreti Tanyak</div>
<div class="option" data='{"value":"Alsoszallas","state":"Hajdu-Bihar"}'>Alsoszallas</div>
<div class="option" data='{"value":"Andahazapuszta","state":"Hajdu-Bihar"}'>Andahazapuszta</div>
<div class="option" data='{"value":"Andrashaza","state":"Hajdu-Bihar"}'>Andrashaza</div>
<div class="option" data='{"value":"Andrasitelek","state":"Hajdu-Bihar"}'>Andrasitelek</div>
<div class="option" data='{"value":"Annakert","state":"Hajdu-Bihar"}'>Annakert</div>
<div class="option" data='{"value":"Antaltanya","state":"Hajdu-Bihar"}'>Antaltanya</div>
<div class="option" data='{"value":"Apatsziget","state":"Hajdu-Bihar"}'>Apatsziget</div>
<div class="option" data='{"value":"Aradvanypuszta","state":"Hajdu-Bihar"}'>Aradvanypuszta</div>
<div class="option" data='{"value":"Aranyoscsarda","state":"Hajdu-Bihar"}'>Aranyoscsarda</div>
<div class="option" data='{"value":"Artand","state":"Hajdu-Bihar"}'>Artand</div>
<div class="option" data='{"value":"Artanhazapuszta","state":"Hajdu-Bihar"}'>Artanhazapuszta</div>
<div class="option" data='{"value":"Asszonyreszpuszta","state":"Hajdu-Bihar"}'>Asszonyreszpuszta</div>
<div class="option" data='{"value":"Asvany","state":"Hajdu-Bihar"}'>Asvany</div>
<div class="option" data='{"value":"Ataleso","state":"Hajdu-Bihar"}'>Ataleso</div>
<div class="option" data='{"value":"Azokiret","state":"Hajdu-Bihar"}'>Azokiret</div>
<div class="option" data='{"value":"Bacsohaz","state":"Hajdu-Bihar"}'>Bacsohaz</div>
<div class="option" data='{"value":"Bagamer","state":"Hajdu-Bihar"}'>Bagamer</div>
<div class="option" data='{"value":"Bagditanya","state":"Hajdu-Bihar"}'>Bagditanya</div>
<div class="option" data='{"value":"Bagosi Ut","state":"Hajdu-Bihar"}'>Bagosi Ut</div>
<div class="option" data='{"value":"Bagosiuti Tanyak","state":"Hajdu-Bihar"}'>Bagosiuti Tanyak</div>
<div class="option" data='{"value":"Bagyhalom","state":"Hajdu-Bihar"}'>Bagyhalom</div>
<div class="option" data='{"value":"Bagytelep","state":"Hajdu-Bihar"}'>Bagytelep</div>
<div class="option" data='{"value":"Bajonta Puszta","state":"Hajdu-Bihar"}'>Bajonta Puszta</div>
<div class="option" data='{"value":"Bajontadulo","state":"Hajdu-Bihar"}'>Bajontadulo</div>
<div class="option" data='{"value":"Bajontatanya","state":"Hajdu-Bihar"}'>Bajontatanya</div>
<div class="option" data='{"value":"Bakoc","state":"Hajdu-Bihar"}'>Bakoc</div>
<div class="option" data='{"value":"Bakonszeg","state":"Hajdu-Bihar"}'>Bakonszeg</div>
<div class="option" data='{"value":"Bakotanya","state":"Hajdu-Bihar"}'>Bakotanya</div>
<div class="option" data='{"value":"Balazskert","state":"Hajdu-Bihar"}'>Balazskert</div>
<div class="option" data='{"value":"Balazspuszta","state":"Hajdu-Bihar"}'>Balazspuszta</div>
<div class="option" data='{"value":"Balkanyitanya","state":"Hajdu-Bihar"}'>Balkanyitanya</div>
<div class="option" data='{"value":"Balkotanya","state":"Hajdu-Bihar"}'>Balkotanya</div>
<div class="option" data='{"value":"Balmazujvaros","state":"Hajdu-Bihar"}'>Balmazujvaros</div>
<div class="option" data='{"value":"Baloghdulo","state":"Hajdu-Bihar"}'>Baloghdulo</div>
<div class="option" data='{"value":"Baloghtanya","state":"Hajdu-Bihar"}'>Baloghtanya</div>
<div class="option" data='{"value":"Balogtanya","state":"Hajdu-Bihar"}'>Balogtanya</div>
<div class="option" data='{"value":"Banfi","state":"Hajdu-Bihar"}'>Banfi</div>
<div class="option" data='{"value":"Banhazapuszta","state":"Hajdu-Bihar"}'>Banhazapuszta</div>
<div class="option" data='{"value":"Banhazatelep","state":"Hajdu-Bihar"}'>Banhazatelep</div>
<div class="option" data='{"value":"Bankhegy","state":"Hajdu-Bihar"}'>Bankhegy</div>
<div class="option" data='{"value":"Bankitanyak","state":"Hajdu-Bihar"}'>Bankitanyak</div>
<div class="option" data='{"value":"Banomkert","state":"Hajdu-Bihar"}'>Banomkert</div>
<div class="option" data='{"value":"Barand","state":"Hajdu-Bihar"}'>Barand</div>
<div class="option" data='{"value":"Barandi Tanyak","state":"Hajdu-Bihar"}'>Barandi Tanyak</div>
<div class="option" data='{"value":"Baranyiresz","state":"Hajdu-Bihar"}'>Baranyiresz</div>
<div class="option" data='{"value":"Baranyitanya","state":"Hajdu-Bihar"}'>Baranyitanya</div>
<div class="option" data='{"value":"Barcsatanya","state":"Hajdu-Bihar"}'>Barcsatanya</div>
<div class="option" data='{"value":"Barsikert","state":"Hajdu-Bihar"}'>Barsikert</div>
<div class="option" data='{"value":"Bartatanya","state":"Hajdu-Bihar"}'>Bartatanya</div>
<div class="option" data='{"value":"Barthatanya","state":"Hajdu-Bihar"}'>Barthatanya</div>
<div class="option" data='{"value":"Basatanya","state":"Hajdu-Bihar"}'>Basatanya</div>
<div class="option" data='{"value":"Bathorikert","state":"Hajdu-Bihar"}'>Bathorikert</div>
<div class="option" data='{"value":"Bathorykert","state":"Hajdu-Bihar"}'>Bathorykert</div>
<div class="option" data='{"value":"Battonyas","state":"Hajdu-Bihar"}'>Battonyas</div>
<div class="option" data='{"value":"Baytanya","state":"Hajdu-Bihar"}'>Baytanya</div>
<div class="option" data='{"value":"Bedo","state":"Hajdu-Bihar"}'>Bedo</div>
<div class="option" data='{"value":"Bekkert","state":"Hajdu-Bihar"}'>Bekkert</div>
<div class="option" data='{"value":"Bellankistanya","state":"Hajdu-Bihar"}'>Bellankistanya</div>
<div class="option" data='{"value":"Bellannagytanya","state":"Hajdu-Bihar"}'>Bellannagytanya</div>
<div class="option" data='{"value":"Belsojaras","state":"Hajdu-Bihar"}'>Belsojaras</div>
<div class="option" data='{"value":"Belsoohat","state":"Hajdu-Bihar"}'>Belsoohat</div>
<div class="option" data='{"value":"Beregboszormeny","state":"Hajdu-Bihar"}'>Beregboszormeny</div>
<div class="option" data='{"value":"Berekboszormeny","state":"Hajdu-Bihar"}'>Berekboszormeny</div>
<div class="option" data='{"value":"Berektanya","state":"Hajdu-Bihar"}'>Berektanya</div>
<div class="option" data='{"value":"Berencsitanya","state":"Hajdu-Bihar"}'>Berencsitanya</div>
<div class="option" data='{"value":"Beretanya","state":"Hajdu-Bihar"}'>Beretanya</div>
<div class="option" data='{"value":"Berettyoszentmarton","state":"Hajdu-Bihar"}'>Berettyoszentmarton</div>
<div class="option" data='{"value":"Berettyoujfalu","state":"Hajdu-Bihar"}'>Berettyoujfalu</div>
<div class="option" data='{"value":"Berkestag","state":"Hajdu-Bihar"}'>Berkestag</div>
<div class="option" data='{"value":"Berkester","state":"Hajdu-Bihar"}'>Berkester</div>
<div class="option" data='{"value":"Bernatpuszta","state":"Hajdu-Bihar"}'>Bernatpuszta</div>
<div class="option" data='{"value":"Bernatresz","state":"Hajdu-Bihar"}'>Bernatresz</div>
<div class="option" data='{"value":"Betlehemtanya","state":"Hajdu-Bihar"}'>Betlehemtanya</div>
<div class="option" data='{"value":"Bicopuszta","state":"Hajdu-Bihar"}'>Bicopuszta</div>
<div class="option" data='{"value":"Bihardancshaza","state":"Hajdu-Bihar"}'>Bihardancshaza</div>
<div class="option" data='{"value":"Bihardancshazi Tanyak","state":"Hajdu-Bihar"}'>Bihardancshazi Tanyak</div>
<div class="option" data='{"value":"Biharkeresztes","state":"Hajdu-Bihar"}'>Biharkeresztes</div>
<div class="option" data='{"value":"Biharkeresztesi Tanyak","state":"Hajdu-Bihar"}'>Biharkeresztesi Tanyak</div>
<div class="option" data='{"value":"Biharnagybajom","state":"Hajdu-Bihar"}'>Biharnagybajom</div>
<div class="option" data='{"value":"Biharszentlaszlo","state":"Hajdu-Bihar"}'>Biharszentlaszlo</div>
<div class="option" data='{"value":"Bihartorda","state":"Hajdu-Bihar"}'>Bihartorda</div>
<div class="option" data='{"value":"Bihartordai Tanyak","state":"Hajdu-Bihar"}'>Bihartordai Tanyak</div>
<div class="option" data='{"value":"Bikasdulo","state":"Hajdu-Bihar"}'>Bikasdulo</div>
<div class="option" data='{"value":"Bikatelep","state":"Hajdu-Bihar"}'>Bikatelep</div>
<div class="option" data='{"value":"Bivalhalom","state":"Hajdu-Bihar"}'>Bivalhalom</div>
<div class="option" data='{"value":"Bivalyhalom","state":"Hajdu-Bihar"}'>Bivalyhalom</div>
<div class="option" data='{"value":"Bocskaikert","state":"Hajdu-Bihar"}'>Bocskaikert</div>
<div class="option" data='{"value":"Bocskaykert","state":"Hajdu-Bihar"}'>Bocskaykert</div>
<div class="option" data='{"value":"Bocsutanya","state":"Hajdu-Bihar"}'>Bocsutanya</div>
<div class="option" data='{"value":"Bodahegyes","state":"Hajdu-Bihar"}'>Bodahegyes</div>
<div class="option" data='{"value":"Bodaszollo","state":"Hajdu-Bihar"}'>Bodaszollo</div>
<div class="option" data='{"value":"Bodaszolo","state":"Hajdu-Bihar"}'>Bodaszolo</div>
<div class="option" data='{"value":"Bodohaza","state":"Hajdu-Bihar"}'>Bodohaza</div>
<div class="option" data='{"value":"Bodonhat","state":"Hajdu-Bihar"}'>Bodonhat</div>
<div class="option" data='{"value":"Bogat Koze","state":"Hajdu-Bihar"}'>Bogat Koze</div>
<div class="option" data='{"value":"Bogatkozetanya","state":"Hajdu-Bihar"}'>Bogatkozetanya</div>
<div class="option" data='{"value":"Bogatkozitanya","state":"Hajdu-Bihar"}'>Bogatkozitanya</div>
<div class="option" data='{"value":"Bojadulo","state":"Hajdu-Bihar"}'>Bojadulo</div>
<div class="option" data='{"value":"Bojadulok","state":"Hajdu-Bihar"}'>Bojadulok</div>
<div class="option" data='{"value":"Bojt","state":"Hajdu-Bihar"}'>Bojt</div>
<div class="option" data='{"value":"Bojtortanya","state":"Hajdu-Bihar"}'>Bojtortanya</div>
<div class="option" data='{"value":"Bokoripuszta","state":"Hajdu-Bihar"}'>Bokoripuszta</div>
<div class="option" data='{"value":"Bonnartanya","state":"Hajdu-Bihar"}'>Bonnartanya</div>
<div class="option" data='{"value":"Borbelytanyak","state":"Hajdu-Bihar"}'>Borbelytanyak</div>
<div class="option" data='{"value":"Boriszhazi Dulo","state":"Hajdu-Bihar"}'>Boriszhazi Dulo</div>
<div class="option" data='{"value":"Borockas","state":"Hajdu-Bihar"}'>Borockas</div>
<div class="option" data='{"value":"Borzas","state":"Hajdu-Bihar"}'>Borzas</div>
<div class="option" data='{"value":"Budaabrany","state":"Hajdu-Bihar"}'>Budaabrany</div>
<div class="option" data='{"value":"Budaabranyi Resz","state":"Hajdu-Bihar"}'>Budaabranyi Resz</div>
<div class="option" data='{"value":"Buglyotanya","state":"Hajdu-Bihar"}'>Buglyotanya</div>
<div class="option" data='{"value":"Butetanya","state":"Hajdu-Bihar"}'>Butetanya</div>
<div class="option" data='{"value":"Buzita","state":"Hajdu-Bihar"}'>Buzita</div>
<div class="option" data='{"value":"Buzitatanya","state":"Hajdu-Bihar"}'>Buzitatanya</div>
<div class="option" data='{"value":"Cenzusdulo","state":"Hajdu-Bihar"}'>Cenzusdulo</div>
<div class="option" data='{"value":"Cenzusfold","state":"Hajdu-Bihar"}'>Cenzusfold</div>
<div class="option" data='{"value":"Ciganyto","state":"Hajdu-Bihar"}'>Ciganyto</div>
<div class="option" data='{"value":"Cikkelytanya","state":"Hajdu-Bihar"}'>Cikkelytanya</div>
<div class="option" data='{"value":"Cirko","state":"Hajdu-Bihar"}'>Cirko</div>
<div class="option" data='{"value":"Cirkopuszta","state":"Hajdu-Bihar"}'>Cirkopuszta</div>
<div class="option" data='{"value":"Citrahat","state":"Hajdu-Bihar"}'>Citrahat</div>
<div class="option" data='{"value":"Csanaditag","state":"Hajdu-Bihar"}'>Csanaditag</div>
<div class="option" data='{"value":"Csapodulo","state":"Hajdu-Bihar"}'>Csapodulo</div>
<div class="option" data='{"value":"Csarnadulo","state":"Hajdu-Bihar"}'>Csarnadulo</div>
<div class="option" data='{"value":"Csatoldal","state":"Hajdu-Bihar"}'>Csatoldal</div>
<div class="option" data='{"value":"Csatopuszta","state":"Hajdu-Bihar"}'>Csatopuszta</div>
<div class="option" data='{"value":"Csatotanya","state":"Hajdu-Bihar"}'>Csatotanya</div>
<div class="option" data='{"value":"Csattaghattag","state":"Hajdu-Bihar"}'>Csattaghattag</div>
<div class="option" data='{"value":"Csehtanya","state":"Hajdu-Bihar"}'>Csehtanya</div>
<div class="option" data='{"value":"Csendes","state":"Hajdu-Bihar"}'>Csendes</div>
<div class="option" data='{"value":"Cserealja","state":"Hajdu-Bihar"}'>Cserealja</div>
<div class="option" data='{"value":"Csereerdo","state":"Hajdu-Bihar"}'>Csereerdo</div>
<div class="option" data='{"value":"Cserekert","state":"Hajdu-Bihar"}'>Cserekert</div>
<div class="option" data='{"value":"Cserepes","state":"Hajdu-Bihar"}'>Cserepes</div>
<div class="option" data='{"value":"Cserepuszta","state":"Hajdu-Bihar"}'>Cserepuszta</div>
<div class="option" data='{"value":"Csiff","state":"Hajdu-Bihar"}'>Csiff</div>
<div class="option" data='{"value":"Csiffitanyak","state":"Hajdu-Bihar"}'>Csiffitanyak</div>
<div class="option" data='{"value":"Csikeritanya","state":"Hajdu-Bihar"}'>Csikeritanya</div>
<div class="option" data='{"value":"Csikonyomastanya","state":"Hajdu-Bihar"}'>Csikonyomastanya</div>
<div class="option" data='{"value":"Csillagos","state":"Hajdu-Bihar"}'>Csillagos</div>
<div class="option" data='{"value":"Csillagosdulo","state":"Hajdu-Bihar"}'>Csillagosdulo</div>
<div class="option" data='{"value":"Csillagtanya","state":"Hajdu-Bihar"}'>Csillagtanya</div>
<div class="option" data='{"value":"Csizmaszartanya","state":"Hajdu-Bihar"}'>Csizmaszartanya</div>
<div class="option" data='{"value":"Csokmo","state":"Hajdu-Bihar"}'>Csokmo</div>
<div class="option" data='{"value":"Csoktanya","state":"Hajdu-Bihar"}'>Csoktanya</div>
<div class="option" data='{"value":"Csonkas","state":"Hajdu-Bihar"}'>Csonkas</div>
<div class="option" data='{"value":"Csontoskert","state":"Hajdu-Bihar"}'>Csontoskert</div>
<div class="option" data='{"value":"Csontoskerti Tanyak","state":"Hajdu-Bihar"}'>Csontoskerti Tanyak</div>
<div class="option" data='{"value":"Csuhatanya","state":"Hajdu-Bihar"}'>Csuhatanya</div>
<div class="option" data='{"value":"Csukas","state":"Hajdu-Bihar"}'>Csukas</div>
<div class="option" data='{"value":"Csukas Tanya","state":"Hajdu-Bihar"}'>Csukas Tanya</div>
<div class="option" data='{"value":"Csukasdulo","state":"Hajdu-Bihar"}'>Csukasdulo</div>
<div class="option" data='{"value":"Csurkolesdulo","state":"Hajdu-Bihar"}'>Csurkolesdulo</div>
<div class="option" data='{"value":"Cuca","state":"Hajdu-Bihar"}'>Cuca</div>
<div class="option" data='{"value":"Cucaihatarresz","state":"Hajdu-Bihar"}'>Cucaihatarresz</div>
<div class="option" data='{"value":"Dabotanya","state":"Hajdu-Bihar"}'>Dabotanya</div>
<div class="option" data='{"value":"Dallarresz","state":"Hajdu-Bihar"}'>Dallarresz</div>
<div class="option" data='{"value":"Dancshaza","state":"Hajdu-Bihar"}'>Dancshaza</div>
<div class="option" data='{"value":"Dancshazitanya","state":"Hajdu-Bihar"}'>Dancshazitanya</div>
<div class="option" data='{"value":"Dandetanya","state":"Hajdu-Bihar"}'>Dandetanya</div>
<div class="option" data='{"value":"Darabonttanya","state":"Hajdu-Bihar"}'>Darabonttanya</div>
<div class="option" data='{"value":"Darvas","state":"Hajdu-Bihar"}'>Darvas</div>
<div class="option" data='{"value":"Darvastanya","state":"Hajdu-Bihar"}'>Darvastanya</div>
<div class="option" data='{"value":"Deaktanya","state":"Hajdu-Bihar"}'>Deaktanya</div>
<div class="option" data='{"value":"Delihaz","state":"Hajdu-Bihar"}'>Delihaz</div>
<div class="option" data='{"value":"Delodulo","state":"Hajdu-Bihar"}'>Delodulo</div>
<div class="option" data='{"value":"Derecske","state":"Hajdu-Bihar"}'>Derecske</div>
<div class="option" data='{"value":"Dessewffytanya","state":"Hajdu-Bihar"}'>Dessewffytanya</div>
<div class="option" data='{"value":"Deszkastanya","state":"Hajdu-Bihar"}'>Deszkastanya</div>
<div class="option" data='{"value":"Dezsitanya","state":"Hajdu-Bihar"}'>Dezsitanya</div>
<div class="option" data='{"value":"Dezsytanya","state":"Hajdu-Bihar"}'>Dezsytanya</div>
<div class="option" data='{"value":"Dinnyes","state":"Hajdu-Bihar"}'>Dinnyes</div>
<div class="option" data='{"value":"Dinnyestanya","state":"Hajdu-Bihar"}'>Dinnyestanya</div>
<div class="option" data='{"value":"Dinnyeszug","state":"Hajdu-Bihar"}'>Dinnyeszug</div>
<div class="option" data='{"value":"Disznokut Eszak","state":"Hajdu-Bihar"}'>Disznokut Eszak</div>
<div class="option" data='{"value":"Disznokut Kelet","state":"Hajdu-Bihar"}'>Disznokut Kelet</div>
<div class="option" data='{"value":"Disznokut Nyugat","state":"Hajdu-Bihar"}'>Disznokut Nyugat</div>
<div class="option" data='{"value":"Disznokuti tanyak","state":"Hajdu-Bihar"}'>Disznokuti tanyak</div>
<div class="option" data='{"value":"Dobaipuszta","state":"Hajdu-Bihar"}'>Dobaipuszta</div>
<div class="option" data='{"value":"Dogospuszta","state":"Hajdu-Bihar"}'>Dogospuszta</div>
<div class="option" data='{"value":"Dogter","state":"Hajdu-Bihar"}'>Dogter</div>
<div class="option" data='{"value":"Dohanyfold","state":"Hajdu-Bihar"}'>Dohanyfold</div>
<div class="option" data='{"value":"Doktortanya","state":"Hajdu-Bihar"}'>Doktortanya</div>
<div class="option" data='{"value":"Dollarresz","state":"Hajdu-Bihar"}'>Dollarresz</div>
<div class="option" data='{"value":"Donko","state":"Hajdu-Bihar"}'>Donko</div>
<div class="option" data='{"value":"Dorogiasmezeje","state":"Hajdu-Bihar"}'>Dorogiasmezeje</div>
<div class="option" data='{"value":"Dozsatanya","state":"Hajdu-Bihar"}'>Dozsatanya</div>
<div class="option" data='{"value":"Dudastanya","state":"Hajdu-Bihar"}'>Dudastanya</div>
<div class="option" data='{"value":"Ebes","state":"Hajdu-Bihar"}'>Ebes</div>
<div class="option" data='{"value":"Ecseditanya","state":"Hajdu-Bihar"}'>Ecseditanya</div>
<div class="option" data='{"value":"Egettret","state":"Hajdu-Bihar"}'>Egettret</div>
<div class="option" data='{"value":"Egritanya","state":"Hajdu-Bihar"}'>Egritanya</div>
<div class="option" data='{"value":"Egyek","state":"Hajdu-Bihar"}'>Egyek</div>
<div class="option" data='{"value":"Ekestanya","state":"Hajdu-Bihar"}'>Ekestanya</div>
<div class="option" data='{"value":"Elekestanya","state":"Hajdu-Bihar"}'>Elekestanya</div>
<div class="option" data='{"value":"Elep","state":"Hajdu-Bihar"}'>Elep</div>
<div class="option" data='{"value":"Elohat","state":"Hajdu-Bihar"}'>Elohat</div>
<div class="option" data='{"value":"Elohatitanya","state":"Hajdu-Bihar"}'>Elohatitanya</div>
<div class="option" data='{"value":"Erdohalmi Tanyak","state":"Hajdu-Bihar"}'>Erdohalmi Tanyak</div>
<div class="option" data='{"value":"Esiszik","state":"Hajdu-Bihar"}'>Esiszik</div>
<div class="option" data='{"value":"Esztar","state":"Hajdu-Bihar"}'>Esztar</div>
<div class="option" data='{"value":"Evaakla","state":"Hajdu-Bihar"}'>Evaakla</div>
<div class="option" data='{"value":"Fabrytanya","state":"Hajdu-Bihar"}'>Fabrytanya</div>
<div class="option" data='{"value":"Falashodaly","state":"Hajdu-Bihar"}'>Falashodaly</div>
<div class="option" data='{"value":"Falualja","state":"Hajdu-Bihar"}'>Falualja</div>
<div class="option" data='{"value":"Falusziget","state":"Hajdu-Bihar"}'>Falusziget</div>
<div class="option" data='{"value":"Falyiresz","state":"Hajdu-Bihar"}'>Falyiresz</div>
<div class="option" data='{"value":"Farkasgaz","state":"Hajdu-Bihar"}'>Farkasgaz</div>
<div class="option" data='{"value":"Farkassziget","state":"Hajdu-Bihar"}'>Farkassziget</div>
<div class="option" data='{"value":"Farkasvolgyifurdo","state":"Hajdu-Bihar"}'>Farkasvolgyifurdo</div>
<div class="option" data='{"value":"Feketefold","state":"Hajdu-Bihar"}'>Feketefold</div>
<div class="option" data='{"value":"Feketefoldi Tanyak","state":"Hajdu-Bihar"}'>Feketefoldi Tanyak</div>
<div class="option" data='{"value":"Feketeret","state":"Hajdu-Bihar"}'>Feketeret</div>
<div class="option" data='{"value":"Feketetanya","state":"Hajdu-Bihar"}'>Feketetanya</div>
<div class="option" data='{"value":"Felhalom","state":"Hajdu-Bihar"}'>Felhalom</div>
<div class="option" data='{"value":"Felsofulop","state":"Hajdu-Bihar"}'>Felsofulop</div>
<div class="option" data='{"value":"Felsoreti Dulo","state":"Hajdu-Bihar"}'>Felsoreti Dulo</div>
<div class="option" data='{"value":"Fenekdulo","state":"Hajdu-Bihar"}'>Fenekdulo</div>
<div class="option" data='{"value":"Fenyes Tanya","state":"Hajdu-Bihar"}'>Fenyes Tanya</div>
<div class="option" data='{"value":"Fenyestelep","state":"Hajdu-Bihar"}'>Fenyestelep</div>
<div class="option" data='{"value":"Ferdiktanya","state":"Hajdu-Bihar"}'>Ferdiktanya</div>
<div class="option" data='{"value":"Ferencmajor","state":"Hajdu-Bihar"}'>Ferencmajor</div>
<div class="option" data='{"value":"Fogthuy Dulo","state":"Hajdu-Bihar"}'>Fogthuy Dulo</div>
<div class="option" data='{"value":"Fogthuy Tanya","state":"Hajdu-Bihar"}'>Fogthuy Tanya</div>
<div class="option" data='{"value":"Foldes","state":"Hajdu-Bihar"}'>Foldes</div>
<div class="option" data='{"value":"Foldesi Puszta","state":"Hajdu-Bihar"}'>Foldesi Puszta</div>
<div class="option" data='{"value":"Folyas","state":"Hajdu-Bihar"}'>Folyas</div>
<div class="option" data='{"value":"Forraskert","state":"Hajdu-Bihar"}'>Forraskert</div>
<div class="option" data='{"value":"Forrastanya","state":"Hajdu-Bihar"}'>Forrastanya</div>
<div class="option" data='{"value":"Fulop","state":"Hajdu-Bihar"}'>Fulop</div>
<div class="option" data='{"value":"Fuloptanya","state":"Hajdu-Bihar"}'>Fuloptanya</div>
<div class="option" data='{"value":"Furjhalomjaras","state":"Hajdu-Bihar"}'>Furjhalomjaras</div>
<div class="option" data='{"value":"Furta","state":"Hajdu-Bihar"}'>Furta</div>
<div class="option" data='{"value":"Fustpuszta","state":"Hajdu-Bihar"}'>Fustpuszta</div>
<div class="option" data='{"value":"Fuzfas","state":"Hajdu-Bihar"}'>Fuzfas</div>
<div class="option" data='{"value":"Fuzfasgat","state":"Hajdu-Bihar"}'>Fuzfasgat</div>
<div class="option" data='{"value":"Gaaltanya","state":"Hajdu-Bihar"}'>Gaaltanya</div>
<div class="option" data='{"value":"Gaaltanyak","state":"Hajdu-Bihar"}'>Gaaltanyak</div>
<div class="option" data='{"value":"Gaborjan","state":"Hajdu-Bihar"}'>Gaborjan</div>
<div class="option" data='{"value":"Galtanya","state":"Hajdu-Bihar"}'>Galtanya</div>
<div class="option" data='{"value":"Gasstanya","state":"Hajdu-Bihar"}'>Gasstanya</div>
<div class="option" data='{"value":"Gatalypuszta","state":"Hajdu-Bihar"}'>Gatalypuszta</div>
<div class="option" data='{"value":"Gathalom","state":"Hajdu-Bihar"}'>Gathalom</div>
<div class="option" data='{"value":"Gati Tanyak","state":"Hajdu-Bihar"}'>Gati Tanyak</div>
<div class="option" data='{"value":"Gerebitelep","state":"Hajdu-Bihar"}'>Gerebitelep</div>
<div class="option" data='{"value":"Geretanya","state":"Hajdu-Bihar"}'>Geretanya</div>
<div class="option" data='{"value":"Gogantanya","state":"Hajdu-Bihar"}'>Gogantanya</div>
<div class="option" data='{"value":"Golyastanya","state":"Hajdu-Bihar"}'>Golyastanya</div>
<div class="option" data='{"value":"Gombostanya","state":"Hajdu-Bihar"}'>Gombostanya</div>
<div class="option" data='{"value":"Gorbefold","state":"Hajdu-Bihar"}'>Gorbefold</div>
<div class="option" data='{"value":"Gorbehaza","state":"Hajdu-Bihar"}'>Gorbehaza</div>
<div class="option" data='{"value":"Gorbehazapuszta","state":"Hajdu-Bihar"}'>Gorbehazapuszta</div>
<div class="option" data='{"value":"Gorbetanya","state":"Hajdu-Bihar"}'>Gorbetanya</div>
<div class="option" data='{"value":"Gorbeto","state":"Hajdu-Bihar"}'>Gorbeto</div>
<div class="option" data='{"value":"Gorogkut Del","state":"Hajdu-Bihar"}'>Gorogkut Del</div>
<div class="option" data='{"value":"Gorogkut Deli","state":"Hajdu-Bihar"}'>Gorogkut Deli</div>
<div class="option" data='{"value":"Gorogkut Eszak","state":"Hajdu-Bihar"}'>Gorogkut Eszak</div>
<div class="option" data='{"value":"Gorogkut Eszaki","state":"Hajdu-Bihar"}'>Gorogkut Eszaki</div>
<div class="option" data='{"value":"Gorogkuti Tanyak","state":"Hajdu-Bihar"}'>Gorogkuti Tanyak</div>
<div class="option" data='{"value":"Gorogkuttanyak","state":"Hajdu-Bihar"}'>Gorogkuttanyak</div>
<div class="option" data='{"value":"Gorogtanya","state":"Hajdu-Bihar"}'>Gorogtanya</div>
<div class="option" data='{"value":"Gorzsasdulo","state":"Hajdu-Bihar"}'>Gorzsasdulo</div>
<div class="option" data='{"value":"Grosztanya","state":"Hajdu-Bihar"}'>Grosztanya</div>
<div class="option" data='{"value":"Gyaparos","state":"Hajdu-Bihar"}'>Gyaparos</div>
<div class="option" data='{"value":"Gyepmestertelep","state":"Hajdu-Bihar"}'>Gyepmestertelep</div>
<div class="option" data='{"value":"Gyeptelep","state":"Hajdu-Bihar"}'>Gyeptelep</div>
<div class="option" data='{"value":"Gyulas","state":"Hajdu-Bihar"}'>Gyulas</div>
<div class="option" data='{"value":"Gyulasi Tanyak","state":"Hajdu-Bihar"}'>Gyulasi Tanyak</div>
<div class="option" data='{"value":"Gyulatag","state":"Hajdu-Bihar"}'>Gyulatag</div>
<div class="option" data='{"value":"Hajdubagos","state":"Hajdu-Bihar"}'>Hajdubagos</div>
<div class="option" data='{"value":"Hajduboszormeny","state":"Hajdu-Bihar"}'>Hajduboszormeny</div>
<div class="option" data='{"value":"Hajdudorog","state":"Hajdu-Bihar"}'>Hajdudorog</div>
<div class="option" data='{"value":"Hajduhadhaz","state":"Hajdu-Bihar"}'>Hajduhadhaz</div>
<div class="option" data='{"value":"Hajdunanas","state":"Hajdu-Bihar"}'>Hajdunanas</div>
<div class="option" data='{"value":"Hajdusamson","state":"Hajdu-Bihar"}'>Hajdusamson</div>
<div class="option" data='{"value":"Hajduszoboszlo","state":"Hajdu-Bihar"}'>Hajduszoboszlo</div>
<div class="option" data='{"value":"Hajduszovat","state":"Hajdu-Bihar"}'>Hajduszovat</div>
<div class="option" data='{"value":"Hajduvid","state":"Hajdu-Bihar"}'>Hajduvid</div>
<div class="option" data='{"value":"Halasitanya","state":"Hajdu-Bihar"}'>Halasitanya</div>
<div class="option" data='{"value":"Halaspuszta","state":"Hajdu-Bihar"}'>Halaspuszta</div>
<div class="option" data='{"value":"Haldulo","state":"Hajdu-Bihar"}'>Haldulo</div>
<div class="option" data='{"value":"Hanelek","state":"Hajdu-Bihar"}'>Hanelek</div>
<div class="option" data='{"value":"Harcsas","state":"Hajdu-Bihar"}'>Harcsas</div>
<div class="option" data='{"value":"Harcsasdulo","state":"Hajdu-Bihar"}'>Harcsasdulo</div>
<div class="option" data='{"value":"Harcsaspuszta","state":"Hajdu-Bihar"}'>Harcsaspuszta</div>
<div class="option" data='{"value":"Harmas","state":"Hajdu-Bihar"}'>Harmas</div>
<div class="option" data='{"value":"Harmassziget","state":"Hajdu-Bihar"}'>Harmassziget</div>
<div class="option" data='{"value":"Hatardulo","state":"Hajdu-Bihar"}'>Hatardulo</div>
<div class="option" data='{"value":"Hatartanyak","state":"Hajdu-Bihar"}'>Hatartanyak</div>
<div class="option" data='{"value":"Hatarzug","state":"Hajdu-Bihar"}'>Hatarzug</div>
<div class="option" data='{"value":"Hatostanya","state":"Hajdu-Bihar"}'>Hatostanya</div>
<div class="option" data='{"value":"Hegyeshalmizugdulo","state":"Hajdu-Bihar"}'>Hegyeshalmizugdulo</div>
<div class="option" data='{"value":"Hegyeshalom","state":"Hajdu-Bihar"}'>Hegyeshalom</div>
<div class="option" data='{"value":"Hegyitanya","state":"Hajdu-Bihar"}'>Hegyitanya</div>
<div class="option" data='{"value":"Hencida","state":"Hajdu-Bihar"}'>Hencida</div>
<div class="option" data='{"value":"Hereskert","state":"Hajdu-Bihar"}'>Hereskert</div>
<div class="option" data='{"value":"Herestanya","state":"Hajdu-Bihar"}'>Herestanya</div>
<div class="option" data='{"value":"Herkanpuszta","state":"Hajdu-Bihar"}'>Herkanpuszta</div>
<div class="option" data='{"value":"Herkany","state":"Hajdu-Bihar"}'>Herkany</div>
<div class="option" data='{"value":"Herkanydulo","state":"Hajdu-Bihar"}'>Herkanydulo</div>
<div class="option" data='{"value":"Hidkoz","state":"Hajdu-Bihar"}'>Hidkoz</div>
<div class="option" data='{"value":"Hidlab","state":"Hajdu-Bihar"}'>Hidlab</div>
<div class="option" data='{"value":"Hidret","state":"Hajdu-Bihar"}'>Hidret</div>
<div class="option" data='{"value":"Hogyetanya","state":"Hajdu-Bihar"}'>Hogyetanya</div>
<div class="option" data='{"value":"Homoki Szolloskert","state":"Hajdu-Bihar"}'>Homoki Szolloskert</div>
<div class="option" data='{"value":"Homoki Tanyak","state":"Hajdu-Bihar"}'>Homoki Tanyak</div>
<div class="option" data='{"value":"Homokitanya","state":"Hajdu-Bihar"}'>Homokitanya</div>
<div class="option" data='{"value":"Hort","state":"Hajdu-Bihar"}'>Hort</div>
<div class="option" data='{"value":"Hortobagy","state":"Hajdu-Bihar"}'>Hortobagy</div>
<div class="option" data='{"value":"Hortobagyihalasto","state":"Hajdu-Bihar"}'>Hortobagyihalasto</div>
<div class="option" data='{"value":"Hortyi","state":"Hajdu-Bihar"}'>Hortyi</div>
<div class="option" data='{"value":"Horvathtanya","state":"Hajdu-Bihar"}'>Horvathtanya</div>
<div class="option" data='{"value":"Hosszu Ret","state":"Hajdu-Bihar"}'>Hosszu Ret</div>
<div class="option" data='{"value":"Hosszudulo","state":"Hajdu-Bihar"}'>Hosszudulo</div>
<div class="option" data='{"value":"Hosszuhat","state":"Hajdu-Bihar"}'>Hosszuhat</div>
<div class="option" data='{"value":"Hosszupaly","state":"Hajdu-Bihar"}'>Hosszupaly</div>
<div class="option" data='{"value":"Hosszupalyi","state":"Hajdu-Bihar"}'>Hosszupalyi</div>
<div class="option" data='{"value":"Hosszuretdulo","state":"Hajdu-Bihar"}'>Hosszuretdulo</div>
<div class="option" data='{"value":"Hunyadiszollostelep","state":"Hajdu-Bihar"}'>Hunyadiszollostelep</div>
<div class="option" data='{"value":"Huter","state":"Hajdu-Bihar"}'>Huter</div>
<div class="option" data='{"value":"Huttertanya","state":"Hajdu-Bihar"}'>Huttertanya</div>
<div class="option" data='{"value":"Ilis","state":"Hajdu-Bihar"}'>Ilis</div>
<div class="option" data='{"value":"Ilonatelep","state":"Hajdu-Bihar"}'>Ilonatelep</div>
<div class="option" data='{"value":"Inta","state":"Hajdu-Bihar"}'>Inta</div>
<div class="option" data='{"value":"Intadulo","state":"Hajdu-Bihar"}'>Intadulo</div>
<div class="option" data='{"value":"Iszap","state":"Hajdu-Bihar"}'>Iszap</div>
<div class="option" data='{"value":"Iszappuszta","state":"Hajdu-Bihar"}'>Iszappuszta</div>
<div class="option" data='{"value":"Iszaptanya","state":"Hajdu-Bihar"}'>Iszaptanya</div>
<div class="option" data='{"value":"Ivanyinagynyesta","state":"Hajdu-Bihar"}'>Ivanyinagynyesta</div>
<div class="option" data='{"value":"Ivanyinyesta","state":"Hajdu-Bihar"}'>Ivanyinyesta</div>
<div class="option" data='{"value":"Jankovitstanya","state":"Hajdu-Bihar"}'>Jankovitstanya</div>
<div class="option" data='{"value":"Janostava","state":"Hajdu-Bihar"}'>Janostava</div>
<div class="option" data='{"value":"Janostavadulo","state":"Hajdu-Bihar"}'>Janostavadulo</div>
<div class="option" data='{"value":"Jegyzotag","state":"Hajdu-Bihar"}'>Jegyzotag</div>
<div class="option" data='{"value":"Jencitag","state":"Hajdu-Bihar"}'>Jencitag</div>
<div class="option" data='{"value":"Jeneifurdo","state":"Hajdu-Bihar"}'>Jeneifurdo</div>
<div class="option" data='{"value":"Jeneitanya","state":"Hajdu-Bihar"}'>Jeneitanya</div>
<div class="option" data='{"value":"Jobbagytanya","state":"Hajdu-Bihar"}'>Jobbagytanya</div>
<div class="option" data='{"value":"Jonasresz","state":"Hajdu-Bihar"}'>Jonasresz</div>
<div class="option" data='{"value":"Jozsatanya","state":"Hajdu-Bihar"}'>Jozsatanya</div>
<div class="option" data='{"value":"Jozsefmajor","state":"Hajdu-Bihar"}'>Jozsefmajor</div>
<div class="option" data='{"value":"Juhasztanya","state":"Hajdu-Bihar"}'>Juhasztanya</div>
<div class="option" data='{"value":"Juhosfo","state":"Hajdu-Bihar"}'>Juhosfo</div>
<div class="option" data='{"value":"Jurinatanya","state":"Hajdu-Bihar"}'>Jurinatanya</div>
<div class="option" data='{"value":"Kaba","state":"Hajdu-Bihar"}'>Kaba</div>
<div class="option" data='{"value":"Kacsora","state":"Hajdu-Bihar"}'>Kacsora</div>
<div class="option" data='{"value":"Kacsoratanya","state":"Hajdu-Bihar"}'>Kacsoratanya</div>
<div class="option" data='{"value":"Kadarcsdulo","state":"Hajdu-Bihar"}'>Kadarcsdulo</div>
<div class="option" data='{"value":"Kadarcshat","state":"Hajdu-Bihar"}'>Kadarcshat</div>
<div class="option" data='{"value":"Kalaposd","state":"Hajdu-Bihar"}'>Kalaposd</div>
<div class="option" data='{"value":"Kapocsdulo","state":"Hajdu-Bihar"}'>Kapocsdulo</div>
<div class="option" data='{"value":"Kaposztaskert","state":"Hajdu-Bihar"}'>Kaposztaskert</div>
<div class="option" data='{"value":"Kaptalandulo","state":"Hajdu-Bihar"}'>Kaptalandulo</div>
<div class="option" data='{"value":"Kardosdulo","state":"Hajdu-Bihar"}'>Kardosdulo</div>
<div class="option" data='{"value":"Kardosliget","state":"Hajdu-Bihar"}'>Kardosliget</div>
<div class="option" data='{"value":"Karinko","state":"Hajdu-Bihar"}'>Karinko</div>
<div class="option" data='{"value":"Kaszaitanya","state":"Hajdu-Bihar"}'>Kaszaitanya</div>
<div class="option" data='{"value":"Kaszakutdulo","state":"Hajdu-Bihar"}'>Kaszakutdulo</div>
<div class="option" data='{"value":"Kaszapuszta","state":"Hajdu-Bihar"}'>Kaszapuszta</div>
<div class="option" data='{"value":"Kasziba","state":"Hajdu-Bihar"}'>Kasziba</div>
<div class="option" data='{"value":"Katonatanya","state":"Hajdu-Bihar"}'>Katonatanya</div>
<div class="option" data='{"value":"Kecskekosartanya","state":"Hajdu-Bihar"}'>Kecskekosartanya</div>
<div class="option" data='{"value":"Kecskes","state":"Hajdu-Bihar"}'>Kecskes</div>
<div class="option" data='{"value":"Kekestanya","state":"Hajdu-Bihar"}'>Kekestanya</div>
<div class="option" data='{"value":"Keletdulo","state":"Hajdu-Bihar"}'>Keletdulo</div>
<div class="option" data='{"value":"Keleti Lapos","state":"Hajdu-Bihar"}'>Keleti Lapos</div>
<div class="option" data='{"value":"Kendereskert","state":"Hajdu-Bihar"}'>Kendereskert</div>
<div class="option" data='{"value":"Kenderfold","state":"Hajdu-Bihar"}'>Kenderfold</div>
<div class="option" data='{"value":"Kendergyar","state":"Hajdu-Bihar"}'>Kendergyar</div>
<div class="option" data='{"value":"Kenezpuszta","state":"Hajdu-Bihar"}'>Kenezpuszta</div>
<div class="option" data='{"value":"Kengyeles","state":"Hajdu-Bihar"}'>Kengyeles</div>
<div class="option" data='{"value":"Kengyelesdulo","state":"Hajdu-Bihar"}'>Kengyelesdulo</div>
<div class="option" data='{"value":"Kengyelkoz","state":"Hajdu-Bihar"}'>Kengyelkoz</div>
<div class="option" data='{"value":"Kengyelkoztanya","state":"Hajdu-Bihar"}'>Kengyelkoztanya</div>
<div class="option" data='{"value":"Kengyeloldal","state":"Hajdu-Bihar"}'>Kengyeloldal</div>
<div class="option" data='{"value":"Kerektiszta","state":"Hajdu-Bihar"}'>Kerektiszta</div>
<div class="option" data='{"value":"Keresztdulo","state":"Hajdu-Bihar"}'>Keresztdulo</div>
<div class="option" data='{"value":"Kereszter","state":"Hajdu-Bihar"}'>Kereszter</div>
<div class="option" data='{"value":"Kertalja","state":"Hajdu-Bihar"}'>Kertalja</div>
<div class="option" data='{"value":"Keszlertag","state":"Hajdu-Bihar"}'>Keszlertag</div>
<div class="option" data='{"value":"Keszlertanya","state":"Hajdu-Bihar"}'>Keszlertanya</div>
<div class="option" data='{"value":"Kigyospuszta","state":"Hajdu-Bihar"}'>Kigyospuszta</div>
<div class="option" data='{"value":"Kincsestanya","state":"Hajdu-Bihar"}'>Kincsestanya</div>
<div class="option" data='{"value":"Kinizsiret","state":"Hajdu-Bihar"}'>Kinizsiret</div>
<div class="option" data='{"value":"Kiralyzug","state":"Hajdu-Bihar"}'>Kiralyzug</div>
<div class="option" data='{"value":"Kis Aradvanypuszta","state":"Hajdu-Bihar"}'>Kis Aradvanypuszta</div>
<div class="option" data='{"value":"Kisbocskaykert","state":"Hajdu-Bihar"}'>Kisbocskaykert</div>
<div class="option" data='{"value":"Kisbozsod","state":"Hajdu-Bihar"}'>Kisbozsod</div>
<div class="option" data='{"value":"Kiscseredulo","state":"Hajdu-Bihar"}'>Kiscseredulo</div>
<div class="option" data='{"value":"Kiscserepes","state":"Hajdu-Bihar"}'>Kiscserepes</div>
<div class="option" data='{"value":"Kiscseretanya","state":"Hajdu-Bihar"}'>Kiscseretanya</div>
<div class="option" data='{"value":"Kiscsonkas","state":"Hajdu-Bihar"}'>Kiscsonkas</div>
<div class="option" data='{"value":"Kiserzug","state":"Hajdu-Bihar"}'>Kiserzug</div>
<div class="option" data='{"value":"Kishegyes","state":"Hajdu-Bihar"}'>Kishegyes</div>
<div class="option" data='{"value":"Kishegyesihatar","state":"Hajdu-Bihar"}'>Kishegyesihatar</div>
<div class="option" data='{"value":"Kishidkoz","state":"Hajdu-Bihar"}'>Kishidkoz</div>
<div class="option" data='{"value":"Kishortyi","state":"Hajdu-Bihar"}'>Kishortyi</div>
<div class="option" data='{"value":"Kislegelo","state":"Hajdu-Bihar"}'>Kislegelo</div>
<div class="option" data='{"value":"Kismajor","state":"Hajdu-Bihar"}'>Kismajor</div>
<div class="option" data='{"value":"Kismarja","state":"Hajdu-Bihar"}'>Kismarja</div>
<div class="option" data='{"value":"Kisnyomas","state":"Hajdu-Bihar"}'>Kisnyomas</div>
<div class="option" data='{"value":"Kispoka","state":"Hajdu-Bihar"}'>Kispoka</div>
<div class="option" data='{"value":"Kispokatanya","state":"Hajdu-Bihar"}'>Kispokatanya</div>
<div class="option" data='{"value":"Kisprod","state":"Hajdu-Bihar"}'>Kisprod</div>
<div class="option" data='{"value":"Kispuszta","state":"Hajdu-Bihar"}'>Kispuszta</div>
<div class="option" data='{"value":"Kisstanya","state":"Hajdu-Bihar"}'>Kisstanya</div>
<div class="option" data='{"value":"Kisszalasdulo","state":"Hajdu-Bihar"}'>Kisszalasdulo</div>
<div class="option" data='{"value":"Kisszocskod","state":"Hajdu-Bihar"}'>Kisszocskod</div>
<div class="option" data='{"value":"Kisszollos","state":"Hajdu-Bihar"}'>Kisszollos</div>
<div class="option" data='{"value":"Kistag","state":"Hajdu-Bihar"}'>Kistag</div>
<div class="option" data='{"value":"Kistanya","state":"Hajdu-Bihar"}'>Kistanya</div>
<div class="option" data='{"value":"Kistelek","state":"Hajdu-Bihar"}'>Kistelek</div>
<div class="option" data='{"value":"Kistelekitanyak","state":"Hajdu-Bihar"}'>Kistelekitanyak</div>
<div class="option" data='{"value":"Kistikostanya","state":"Hajdu-Bihar"}'>Kistikostanya</div>
<div class="option" data='{"value":"Kistotipuszta","state":"Hajdu-Bihar"}'>Kistotipuszta</div>
<div class="option" data='{"value":"Kisvokonya","state":"Hajdu-Bihar"}'>Kisvokonya</div>
<div class="option" data='{"value":"Kisztanya","state":"Hajdu-Bihar"}'>Kisztanya</div>
<div class="option" data='{"value":"Kocatelek","state":"Hajdu-Bihar"}'>Kocatelek</div>
<div class="option" data='{"value":"Kocsilapos","state":"Hajdu-Bihar"}'>Kocsilapos</div>
<div class="option" data='{"value":"Kocsortanya","state":"Hajdu-Bihar"}'>Kocsortanya</div>
<div class="option" data='{"value":"Kodomb","state":"Hajdu-Bihar"}'>Kodomb</div>
<div class="option" data='{"value":"Kodormany","state":"Hajdu-Bihar"}'>Kodormany</div>
<div class="option" data='{"value":"Kogyes","state":"Hajdu-Bihar"}'>Kogyes</div>
<div class="option" data='{"value":"Kokad","state":"Hajdu-Bihar"}'>Kokad</div>
<div class="option" data='{"value":"Kolcser","state":"Hajdu-Bihar"}'>Kolcser</div>
<div class="option" data='{"value":"Kolesfold","state":"Hajdu-Bihar"}'>Kolesfold</div>
<div class="option" data='{"value":"Kolesfoldi Tanyak","state":"Hajdu-Bihar"}'>Kolesfoldi Tanyak</div>
<div class="option" data='{"value":"Komadi","state":"Hajdu-Bihar"}'>Komadi</div>
<div class="option" data='{"value":"Komaiti","state":"Hajdu-Bihar"}'>Komaiti</div>
<div class="option" data='{"value":"Konya","state":"Hajdu-Bihar"}'>Konya</div>
<div class="option" data='{"value":"Konyar","state":"Hajdu-Bihar"}'>Konyar</div>
<div class="option" data='{"value":"Korcovagy","state":"Hajdu-Bihar"}'>Korcovagy</div>
<div class="option" data='{"value":"Korhanykert","state":"Hajdu-Bihar"}'>Korhanykert</div>
<div class="option" data='{"value":"Korhanysziget","state":"Hajdu-Bihar"}'>Korhanysziget</div>
<div class="option" data='{"value":"Korhanytanya","state":"Hajdu-Bihar"}'>Korhanytanya</div>
<div class="option" data='{"value":"Korises","state":"Hajdu-Bihar"}'>Korises</div>
<div class="option" data='{"value":"Kormosdpuszta","state":"Hajdu-Bihar"}'>Kormosdpuszta</div>
<div class="option" data='{"value":"Koroserhat","state":"Hajdu-Bihar"}'>Koroserhat</div>
<div class="option" data='{"value":"Korosszakal","state":"Hajdu-Bihar"}'>Korosszakal</div>
<div class="option" data='{"value":"Korosszegapati","state":"Hajdu-Bihar"}'>Korosszegapati</div>
<div class="option" data='{"value":"Korossziget","state":"Hajdu-Bihar"}'>Korossziget</div>
<div class="option" data='{"value":"Korpaddulo","state":"Hajdu-Bihar"}'>Korpaddulo</div>
<div class="option" data='{"value":"Kortefa","state":"Hajdu-Bihar"}'>Kortefa</div>
<div class="option" data='{"value":"Kortvelyestanya","state":"Hajdu-Bihar"}'>Kortvelyestanya</div>
<div class="option" data='{"value":"Koselyszeg","state":"Hajdu-Bihar"}'>Koselyszeg</div>
<div class="option" data='{"value":"Koshodaly","state":"Hajdu-Bihar"}'>Koshodaly</div>
<div class="option" data='{"value":"Kossuthkert","state":"Hajdu-Bihar"}'>Kossuthkert</div>
<div class="option" data='{"value":"Kossuthkertiszollo","state":"Hajdu-Bihar"}'>Kossuthkertiszollo</div>
<div class="option" data='{"value":"Koteles","state":"Hajdu-Bihar"}'>Koteles</div>
<div class="option" data='{"value":"Kotelesdulo","state":"Hajdu-Bihar"}'>Kotelesdulo</div>
<div class="option" data='{"value":"Kovacsdulo","state":"Hajdu-Bihar"}'>Kovacsdulo</div>
<div class="option" data='{"value":"Kovacstanya","state":"Hajdu-Bihar"}'>Kovacstanya</div>
<div class="option" data='{"value":"Kovagasdulo","state":"Hajdu-Bihar"}'>Kovagasdulo</div>
<div class="option" data='{"value":"Kovasznaitanya","state":"Hajdu-Bihar"}'>Kovasznaitanya</div>
<div class="option" data='{"value":"Kovendytanya","state":"Hajdu-Bihar"}'>Kovendytanya</div>
<div class="option" data='{"value":"Kristontanya","state":"Hajdu-Bihar"}'>Kristontanya</div>
<div class="option" data='{"value":"Krucsatanya","state":"Hajdu-Bihar"}'>Krucsatanya</div>
<div class="option" data='{"value":"Krucsatelep","state":"Hajdu-Bihar"}'>Krucsatelep</div>
<div class="option" data='{"value":"Kulsoiszap","state":"Hajdu-Bihar"}'>Kulsoiszap</div>
<div class="option" data='{"value":"Kulsojaras","state":"Hajdu-Bihar"}'>Kulsojaras</div>
<div class="option" data='{"value":"Kulsoohat","state":"Hajdu-Bihar"}'>Kulsoohat</div>
<div class="option" data='{"value":"Kunlapos","state":"Hajdu-Bihar"}'>Kunlapos</div>
<div class="option" data='{"value":"Kunpardulo","state":"Hajdu-Bihar"}'>Kunpardulo</div>
<div class="option" data='{"value":"Kurtadulo","state":"Hajdu-Bihar"}'>Kurtadulo</div>
<div class="option" data='{"value":"Kutas","state":"Hajdu-Bihar"}'>Kutas</div>
<div class="option" data='{"value":"Kutas Erdoorhaz","state":"Hajdu-Bihar"}'>Kutas Erdoorhaz</div>
<div class="option" data='{"value":"Kutaserdo","state":"Hajdu-Bihar"}'>Kutaserdo</div>
<div class="option" data='{"value":"Kutasi Erdoorhaz","state":"Hajdu-Bihar"}'>Kutasi Erdoorhaz</div>
<div class="option" data='{"value":"Kutaspuszta","state":"Hajdu-Bihar"}'>Kutaspuszta</div>
<div class="option" data='{"value":"Lacaytanya","state":"Hajdu-Bihar"}'>Lacaytanya</div>
<div class="option" data='{"value":"Lajoshaza","state":"Hajdu-Bihar"}'>Lajoshaza</div>
<div class="option" data='{"value":"Lakatostanya","state":"Hajdu-Bihar"}'>Lakatostanya</div>
<div class="option" data='{"value":"Lapostanya","state":"Hajdu-Bihar"}'>Lapostanya</div>
<div class="option" data='{"value":"Laro","state":"Hajdu-Bihar"}'>Laro</div>
<div class="option" data='{"value":"Laro Lapos","state":"Hajdu-Bihar"}'>Laro Lapos</div>
<div class="option" data='{"value":"Larotanya","state":"Hajdu-Bihar"}'>Larotanya</div>
<div class="option" data='{"value":"Ledigtanya","state":"Hajdu-Bihar"}'>Ledigtanya</div>
<div class="option" data='{"value":"Legelodulo","state":"Hajdu-Bihar"}'>Legelodulo</div>
<div class="option" data='{"value":"Legeloret","state":"Hajdu-Bihar"}'>Legeloret</div>
<div class="option" data='{"value":"Legeloszel","state":"Hajdu-Bihar"}'>Legeloszel</div>
<div class="option" data='{"value":"Lencztanya","state":"Hajdu-Bihar"}'>Lencztanya</div>
<div class="option" data='{"value":"Lesialja","state":"Hajdu-Bihar"}'>Lesialja</div>
<div class="option" data='{"value":"Letavertes","state":"Hajdu-Bihar"}'>Letavertes</div>
<div class="option" data='{"value":"Liget","state":"Hajdu-Bihar"}'>Liget</div>
<div class="option" data='{"value":"Ligetitag","state":"Hajdu-Bihar"}'>Ligetitag</div>
<div class="option" data='{"value":"Ligetitanya","state":"Hajdu-Bihar"}'>Ligetitanya</div>
<div class="option" data='{"value":"Ligetpuszta","state":"Hajdu-Bihar"}'>Ligetpuszta</div>
<div class="option" data='{"value":"Ligettanyak","state":"Hajdu-Bihar"}'>Ligettanyak</div>
<div class="option" data='{"value":"Linkai Resz","state":"Hajdu-Bihar"}'>Linkai Resz</div>
<div class="option" data='{"value":"Lipcsehat","state":"Hajdu-Bihar"}'>Lipcsehat</div>
<div class="option" data='{"value":"Lipcsei Hat","state":"Hajdu-Bihar"}'>Lipcsei Hat</div>
<div class="option" data='{"value":"Lipcseihattelep","state":"Hajdu-Bihar"}'>Lipcseihattelep</div>
<div class="option" data='{"value":"Lokert","state":"Hajdu-Bihar"}'>Lokert</div>
<div class="option" data='{"value":"Lokerti Tanyak","state":"Hajdu-Bihar"}'>Lokerti Tanyak</div>
<div class="option" data='{"value":"Lopohalom","state":"Hajdu-Bihar"}'>Lopohalom</div>
<div class="option" data='{"value":"Lopohalomjaras","state":"Hajdu-Bihar"}'>Lopohalomjaras</div>
<div class="option" data='{"value":"Lorantffydulo","state":"Hajdu-Bihar"}'>Lorantffydulo</div>
<div class="option" data='{"value":"Lorantffykert","state":"Hajdu-Bihar"}'>Lorantffykert</div>
<div class="option" data='{"value":"Lore","state":"Hajdu-Bihar"}'>Lore</div>
<div class="option" data='{"value":"Ludasiszolo","state":"Hajdu-Bihar"}'>Ludasiszolo</div>
<div class="option" data='{"value":"Ludastanya","state":"Hajdu-Bihar"}'>Ludastanya</div>
<div class="option" data='{"value":"Ludasto","state":"Hajdu-Bihar"}'>Ludasto</div>
<div class="option" data='{"value":"Lukacstanya","state":"Hajdu-Bihar"}'>Lukacstanya</div>
<div class="option" data='{"value":"Maartanya","state":"Hajdu-Bihar"}'>Maartanya</div>
<div class="option" data='{"value":"Magdolna","state":"Hajdu-Bihar"}'>Magdolna</div>
<div class="option" data='{"value":"Magyarhomorog","state":"Hajdu-Bihar"}'>Magyarhomorog</div>
<div class="option" data='{"value":"Magyarkert","state":"Hajdu-Bihar"}'>Magyarkert</div>
<div class="option" data='{"value":"Magyartanya","state":"Hajdu-Bihar"}'>Magyartanya</div>
<div class="option" data='{"value":"Margitaerdo","state":"Hajdu-Bihar"}'>Margitaerdo</div>
<div class="option" data='{"value":"Mariamajor","state":"Hajdu-Bihar"}'>Mariamajor</div>
<div class="option" data='{"value":"Marjaitanya","state":"Hajdu-Bihar"}'>Marjaitanya</div>
<div class="option" data='{"value":"Martinka","state":"Hajdu-Bihar"}'>Martinka</div>
<div class="option" data='{"value":"Mata","state":"Hajdu-Bihar"}'>Mata</div>
<div class="option" data='{"value":"Matelapos","state":"Hajdu-Bihar"}'>Matelapos</div>
<div class="option" data='{"value":"Mathetanya","state":"Hajdu-Bihar"}'>Mathetanya</div>
<div class="option" data='{"value":"Maxitag","state":"Hajdu-Bihar"}'>Maxitag</div>
<div class="option" data='{"value":"Medvetanya","state":"Hajdu-Bihar"}'>Medvetanya</div>
<div class="option" data='{"value":"Melaniatanya","state":"Hajdu-Bihar"}'>Melaniatanya</div>
<div class="option" data='{"value":"Melegoldal","state":"Hajdu-Bihar"}'>Melegoldal</div>
<div class="option" data='{"value":"Mentelep","state":"Hajdu-Bihar"}'>Mentelep</div>
<div class="option" data='{"value":"Merzatanya","state":"Hajdu-Bihar"}'>Merzatanya</div>
<div class="option" data='{"value":"Messzelato","state":"Hajdu-Bihar"}'>Messzelato</div>
<div class="option" data='{"value":"Mezeitag","state":"Hajdu-Bihar"}'>Mezeitag</div>
<div class="option" data='{"value":"Mezopeterd","state":"Hajdu-Bihar"}'>Mezopeterd</div>
<div class="option" data='{"value":"Mezosas","state":"Hajdu-Bihar"}'>Mezosas</div>
<div class="option" data='{"value":"Mezosasi Tanyak","state":"Hajdu-Bihar"}'>Mezosasi Tanyak</div>
<div class="option" data='{"value":"Mezotanya","state":"Hajdu-Bihar"}'>Mezotanya</div>
<div class="option" data='{"value":"Mihalyhalma","state":"Hajdu-Bihar"}'>Mihalyhalma</div>
<div class="option" data='{"value":"Mihalyhalom","state":"Hajdu-Bihar"}'>Mihalyhalom</div>
<div class="option" data='{"value":"Mihalytelep","state":"Hajdu-Bihar"}'>Mihalytelep</div>
<div class="option" data='{"value":"Mikepercs","state":"Hajdu-Bihar"}'>Mikepercs</div>
<div class="option" data='{"value":"Mikepercsi Tanyak","state":"Hajdu-Bihar"}'>Mikepercsi Tanyak</div>
<div class="option" data='{"value":"Mikotelek","state":"Hajdu-Bihar"}'>Mikotelek</div>
<div class="option" data='{"value":"Minkatag","state":"Hajdu-Bihar"}'>Minkatag</div>
<div class="option" data='{"value":"Mokakert","state":"Hajdu-Bihar"}'>Mokakert</div>
<div class="option" data='{"value":"Molnartanya","state":"Hajdu-Bihar"}'>Molnartanya</div>
<div class="option" data='{"value":"Monostor","state":"Hajdu-Bihar"}'>Monostor</div>
<div class="option" data='{"value":"Monostorpalyi","state":"Hajdu-Bihar"}'>Monostorpalyi</div>
<div class="option" data='{"value":"Morgo","state":"Hajdu-Bihar"}'>Morgo</div>
<div class="option" data='{"value":"Morotvakoz","state":"Hajdu-Bihar"}'>Morotvakoz</div>
<div class="option" data='{"value":"Mosontakert","state":"Hajdu-Bihar"}'>Mosontakert</div>
<div class="option" data='{"value":"Munknagytanya","state":"Hajdu-Bihar"}'>Munknagytanya</div>
<div class="option" data='{"value":"Muszaj","state":"Hajdu-Bihar"}'>Muszaj</div>
<div class="option" data='{"value":"Muszaly","state":"Hajdu-Bihar"}'>Muszaly</div>
<div class="option" data='{"value":"Nadudvar","state":"Hajdu-Bihar"}'>Nadudvar</div>
<div class="option" data='{"value":"Nagybajonta","state":"Hajdu-Bihar"}'>Nagybajonta</div>
<div class="option" data='{"value":"Nagybocskaykert","state":"Hajdu-Bihar"}'>Nagybocskaykert</div>
<div class="option" data='{"value":"Nagyborockas","state":"Hajdu-Bihar"}'>Nagyborockas</div>
<div class="option" data='{"value":"Nagybozsod","state":"Hajdu-Bihar"}'>Nagybozsod</div>
<div class="option" data='{"value":"Nagycsonkas","state":"Hajdu-Bihar"}'>Nagycsonkas</div>
<div class="option" data='{"value":"Nagygozhat","state":"Hajdu-Bihar"}'>Nagygozhat</div>
<div class="option" data='{"value":"Nagygyeptanya","state":"Hajdu-Bihar"}'>Nagygyeptanya</div>
<div class="option" data='{"value":"Nagyhat","state":"Hajdu-Bihar"}'>Nagyhat</div>
<div class="option" data='{"value":"Nagyhegydulo","state":"Hajdu-Bihar"}'>Nagyhegydulo</div>
<div class="option" data='{"value":"Nagyhegyes","state":"Hajdu-Bihar"}'>Nagyhegyes</div>
<div class="option" data='{"value":"Nagyhegytanya","state":"Hajdu-Bihar"}'>Nagyhegytanya</div>
<div class="option" data='{"value":"Nagyhortyi","state":"Hajdu-Bihar"}'>Nagyhortyi</div>
<div class="option" data='{"value":"Nagykapros","state":"Hajdu-Bihar"}'>Nagykapros</div>
<div class="option" data='{"value":"Nagykaprostanya","state":"Hajdu-Bihar"}'>Nagykaprostanya</div>
<div class="option" data='{"value":"Nagykasziba","state":"Hajdu-Bihar"}'>Nagykasziba</div>
<div class="option" data='{"value":"Nagykereki","state":"Hajdu-Bihar"}'>Nagykereki</div>
<div class="option" data='{"value":"Nagyleta","state":"Hajdu-Bihar"}'>Nagyleta</div>
<div class="option" data='{"value":"Nagymajor","state":"Hajdu-Bihar"}'>Nagymajor</div>
<div class="option" data='{"value":"Nagymaria","state":"Hajdu-Bihar"}'>Nagymaria</div>
<div class="option" data='{"value":"Nagynyiresdulo","state":"Hajdu-Bihar"}'>Nagynyiresdulo</div>
<div class="option" data='{"value":"Nagyoros","state":"Hajdu-Bihar"}'>Nagyoros</div>
<div class="option" data='{"value":"Nagypoka","state":"Hajdu-Bihar"}'>Nagypoka</div>
<div class="option" data='{"value":"Nagypokatanya","state":"Hajdu-Bihar"}'>Nagypokatanya</div>
<div class="option" data='{"value":"Nagyprod","state":"Hajdu-Bihar"}'>Nagyprod</div>
<div class="option" data='{"value":"Nagyrabe","state":"Hajdu-Bihar"}'>Nagyrabe</div>
<div class="option" data='{"value":"Nagyszog","state":"Hajdu-Bihar"}'>Nagyszog</div>
<div class="option" data='{"value":"Nagyszogtanya","state":"Hajdu-Bihar"}'>Nagyszogtanya</div>
<div class="option" data='{"value":"Nagytanya","state":"Hajdu-Bihar"}'>Nagytanya</div>
<div class="option" data='{"value":"Nagytotipuszta","state":"Hajdu-Bihar"}'>Nagytotipuszta</div>
<div class="option" data='{"value":"Nagytotitanya","state":"Hajdu-Bihar"}'>Nagytotitanya</div>
<div class="option" data='{"value":"Nagyugartanya","state":"Hajdu-Bihar"}'>Nagyugartanya</div>
<div class="option" data='{"value":"Nagyvokonya","state":"Hajdu-Bihar"}'>Nagyvokonya</div>
<div class="option" data='{"value":"Nagyzomlin","state":"Hajdu-Bihar"}'>Nagyzomlin</div>
<div class="option" data='{"value":"Nagyzomlinpuszta","state":"Hajdu-Bihar"}'>Nagyzomlinpuszta</div>
<div class="option" data='{"value":"Nemetdulo","state":"Hajdu-Bihar"}'>Nemetdulo</div>
<div class="option" data='{"value":"Nezodomb","state":"Hajdu-Bihar"}'>Nezodomb</div>
<div class="option" data='{"value":"Nezodombtanya","state":"Hajdu-Bihar"}'>Nezodombtanya</div>
<div class="option" data='{"value":"Niczkyret","state":"Hajdu-Bihar"}'>Niczkyret</div>
<div class="option" data='{"value":"Nyarfadulo","state":"Hajdu-Bihar"}'>Nyarfadulo</div>
<div class="option" data='{"value":"Nyarto","state":"Hajdu-Bihar"}'>Nyarto</div>
<div class="option" data='{"value":"Nyarzug","state":"Hajdu-Bihar"}'>Nyarzug</div>
<div class="option" data='{"value":"Nyergesdulo","state":"Hajdu-Bihar"}'>Nyergesdulo</div>
<div class="option" data='{"value":"Nyestekert","state":"Hajdu-Bihar"}'>Nyestekert</div>
<div class="option" data='{"value":"Nyilas","state":"Hajdu-Bihar"}'>Nyilas</div>
<div class="option" data='{"value":"Nyirabrany","state":"Hajdu-Bihar"}'>Nyirabrany</div>
<div class="option" data='{"value":"Nyiracsad","state":"Hajdu-Bihar"}'>Nyiracsad</div>
<div class="option" data='{"value":"Nyiradony","state":"Hajdu-Bihar"}'>Nyiradony</div>
<div class="option" data='{"value":"Nyirestag","state":"Hajdu-Bihar"}'>Nyirestag</div>
<div class="option" data='{"value":"Nyiritanya","state":"Hajdu-Bihar"}'>Nyiritanya</div>
<div class="option" data='{"value":"Nyirmartonfalva","state":"Hajdu-Bihar"}'>Nyirmartonfalva</div>
<div class="option" data='{"value":"Nyulzug","state":"Hajdu-Bihar"}'>Nyulzug</div>
<div class="option" data='{"value":"Obis","state":"Hajdu-Bihar"}'>Obis</div>
<div class="option" data='{"value":"Ocsa","state":"Hajdu-Bihar"}'>Ocsa</div>
<div class="option" data='{"value":"Ohid","state":"Hajdu-Bihar"}'>Ohid</div>
<div class="option" data='{"value":"Okorjaras","state":"Hajdu-Bihar"}'>Okorjaras</div>
<div class="option" data='{"value":"Olahtanya","state":"Hajdu-Bihar"}'>Olahtanya</div>
<div class="option" data='{"value":"Olasztanya","state":"Hajdu-Bihar"}'>Olasztanya</div>
<div class="option" data='{"value":"Olaszzug","state":"Hajdu-Bihar"}'>Olaszzug</div>
<div class="option" data='{"value":"Olyvostanya","state":"Hajdu-Bihar"}'>Olyvostanya</div>
<div class="option" data='{"value":"Oncsatelep","state":"Hajdu-Bihar"}'>Oncsatelep</div>
<div class="option" data='{"value":"Orbantanya","state":"Hajdu-Bihar"}'>Orbantanya</div>
<div class="option" data='{"value":"Oregszolloskert","state":"Hajdu-Bihar"}'>Oregszolloskert</div>
<div class="option" data='{"value":"Oregszoloskert","state":"Hajdu-Bihar"}'>Oregszoloskert</div>
<div class="option" data='{"value":"Oritanya","state":"Hajdu-Bihar"}'>Oritanya</div>
<div class="option" data='{"value":"Ornsteintanya","state":"Hajdu-Bihar"}'>Ornsteintanya</div>
<div class="option" data='{"value":"Orotveny","state":"Hajdu-Bihar"}'>Orotveny</div>
<div class="option" data='{"value":"Orotveny Koze","state":"Hajdu-Bihar"}'>Orotveny Koze</div>
<div class="option" data='{"value":"Orotvenykoz","state":"Hajdu-Bihar"}'>Orotvenykoz</div>
<div class="option" data='{"value":"Orvenyszog","state":"Hajdu-Bihar"}'>Orvenyszog</div>
<div class="option" data='{"value":"Orvenyszogtanya","state":"Hajdu-Bihar"}'>Orvenyszogtanya</div>
<div class="option" data='{"value":"Ostordulo","state":"Hajdu-Bihar"}'>Ostordulo</div>
<div class="option" data='{"value":"Osveny","state":"Hajdu-Bihar"}'>Osveny</div>
<div class="option" data='{"value":"Ozes","state":"Hajdu-Bihar"}'>Ozes</div>
<div class="option" data='{"value":"Pagettanya","state":"Hajdu-Bihar"}'>Pagettanya</div>
<div class="option" data='{"value":"Pallagdulo","state":"Hajdu-Bihar"}'>Pallagdulo</div>
<div class="option" data='{"value":"Pancel Orokos Tanya","state":"Hajdu-Bihar"}'>Pancel Orokos Tanya</div>
<div class="option" data='{"value":"Panceltanya","state":"Hajdu-Bihar"}'>Panceltanya</div>
<div class="option" data='{"value":"Papfolyodulo","state":"Hajdu-Bihar"}'>Papfolyodulo</div>
<div class="option" data='{"value":"Papfolyojadulo","state":"Hajdu-Bihar"}'>Papfolyojadulo</div>
<div class="option" data='{"value":"Papptanya","state":"Hajdu-Bihar"}'>Papptanya</div>
<div class="option" data='{"value":"Patkossziget","state":"Hajdu-Bihar"}'>Patkossziget</div>
<div class="option" data='{"value":"Pekacsiresz","state":"Hajdu-Bihar"}'>Pekacsiresz</div>
<div class="option" data='{"value":"Pekartanya","state":"Hajdu-Bihar"}'>Pekartanya</div>
<div class="option" data='{"value":"Penzestanya","state":"Hajdu-Bihar"}'>Penzestanya</div>
<div class="option" data='{"value":"Perjes","state":"Hajdu-Bihar"}'>Perjes</div>
<div class="option" data='{"value":"Pernyespuszta","state":"Hajdu-Bihar"}'>Pernyespuszta</div>
<div class="option" data='{"value":"Pernyestanya","state":"Hajdu-Bihar"}'>Pernyestanya</div>
<div class="option" data='{"value":"Peterkert","state":"Hajdu-Bihar"}'>Peterkert</div>
<div class="option" data='{"value":"Pinceshat","state":"Hajdu-Bihar"}'>Pinceshat</div>
<div class="option" data='{"value":"Pinceshattanya","state":"Hajdu-Bihar"}'>Pinceshattanya</div>
<div class="option" data='{"value":"Pocsaj","state":"Hajdu-Bihar"}'>Pocsaj</div>
<div class="option" data='{"value":"Polgar","state":"Hajdu-Bihar"}'>Polgar</div>
<div class="option" data='{"value":"Puskartanya","state":"Hajdu-Bihar"}'>Puskartanya</div>
<div class="option" data='{"value":"Puspokladany","state":"Hajdu-Bihar"}'>Puspokladany</div>
<div class="option" data='{"value":"Puszlikatanya","state":"Hajdu-Bihar"}'>Puszlikatanya</div>
<div class="option" data='{"value":"Pusztatarnokhat","state":"Hajdu-Bihar"}'>Pusztatarnokhat</div>
<div class="option" data='{"value":"Radodulo","state":"Hajdu-Bihar"}'>Radodulo</div>
<div class="option" data='{"value":"Ragali","state":"Hajdu-Bihar"}'>Ragali</div>
<div class="option" data='{"value":"Rakoczikert","state":"Hajdu-Bihar"}'>Rakoczikert</div>
<div class="option" data='{"value":"Rakocziszolloskert","state":"Hajdu-Bihar"}'>Rakocziszolloskert</div>
<div class="option" data='{"value":"Redeyoros","state":"Hajdu-Bihar"}'>Redeyoros</div>
<div class="option" data='{"value":"Regivillanytelep","state":"Hajdu-Bihar"}'>Regivillanytelep</div>
<div class="option" data='{"value":"Repalaposdulo","state":"Hajdu-Bihar"}'>Repalaposdulo</div>
<div class="option" data='{"value":"Ret","state":"Hajdu-Bihar"}'>Ret</div>
<div class="option" data='{"value":"Retitanya","state":"Hajdu-Bihar"}'>Retitanya</div>
<div class="option" data='{"value":"Retitanyak","state":"Hajdu-Bihar"}'>Retitanyak</div>
<div class="option" data='{"value":"Rokalyuk","state":"Hajdu-Bihar"}'>Rokalyuk</div>
<div class="option" data='{"value":"Rozentanya","state":"Hajdu-Bihar"}'>Rozentanya</div>
<div class="option" data='{"value":"Sajtostanya","state":"Hajdu-Bihar"}'>Sajtostanya</div>
<div class="option" data='{"value":"Samsoni Kert","state":"Hajdu-Bihar"}'>Samsoni Kert</div>
<div class="option" data='{"value":"Sandor Puszta","state":"Hajdu-Bihar"}'>Sandor Puszta</div>
<div class="option" data='{"value":"Sandormajor","state":"Hajdu-Bihar"}'>Sandormajor</div>
<div class="option" data='{"value":"Sandortanya","state":"Hajdu-Bihar"}'>Sandortanya</div>
<div class="option" data='{"value":"Sap","state":"Hajdu-Bihar"}'>Sap</div>
<div class="option" data='{"value":"Sapi Tanyak","state":"Hajdu-Bihar"}'>Sapi Tanyak</div>
<div class="option" data='{"value":"Sarand","state":"Hajdu-Bihar"}'>Sarand</div>
<div class="option" data='{"value":"Sarandi Tanya","state":"Hajdu-Bihar"}'>Sarandi Tanya</div>
<div class="option" data='{"value":"Sarretudvari","state":"Hajdu-Bihar"}'>Sarretudvari</div>
<div class="option" data='{"value":"Sarretudvari Tanyak","state":"Hajdu-Bihar"}'>Sarretudvari Tanyak</div>
<div class="option" data='{"value":"Sasdulo","state":"Hajdu-Bihar"}'>Sasdulo</div>
<div class="option" data='{"value":"Schwarcztag","state":"Hajdu-Bihar"}'>Schwarcztag</div>
<div class="option" data='{"value":"Sebestanya","state":"Hajdu-Bihar"}'>Sebestanya</div>
<div class="option" data='{"value":"Siniglatanya","state":"Hajdu-Bihar"}'>Siniglatanya</div>
<div class="option" data='{"value":"Sipostanya","state":"Hajdu-Bihar"}'>Sipostanya</div>
<div class="option" data='{"value":"Soltesztanya","state":"Hajdu-Bihar"}'>Soltesztanya</div>
<div class="option" data='{"value":"Somotatanya","state":"Hajdu-Bihar"}'>Somotatanya</div>
<div class="option" data='{"value":"Soosdulo","state":"Hajdu-Bihar"}'>Soosdulo</div>
<div class="option" data='{"value":"Sore","state":"Hajdu-Bihar"}'>Sore</div>
<div class="option" data='{"value":"Sorefold","state":"Hajdu-Bihar"}'>Sorefold</div>
<div class="option" data='{"value":"Soskas","state":"Hajdu-Bihar"}'>Soskas</div>
<div class="option" data='{"value":"Soskashat","state":"Hajdu-Bihar"}'>Soskashat</div>
<div class="option" data='{"value":"Sovenykut","state":"Hajdu-Bihar"}'>Sovenykut</div>
<div class="option" data='{"value":"Sovenykuttanya","state":"Hajdu-Bihar"}'>Sovenykuttanya</div>
<div class="option" data='{"value":"Sramkotanya","state":"Hajdu-Bihar"}'>Sramkotanya</div>
<div class="option" data='{"value":"Srebenitanya","state":"Hajdu-Bihar"}'>Srebenitanya</div>
<div class="option" data='{"value":"Steiertag","state":"Hajdu-Bihar"}'>Steiertag</div>
<div class="option" data='{"value":"Sterntanya","state":"Hajdu-Bihar"}'>Sterntanya</div>
<div class="option" data='{"value":"Strisstanya","state":"Hajdu-Bihar"}'>Strisstanya</div>
<div class="option" data='{"value":"Sutotag","state":"Hajdu-Bihar"}'>Sutotag</div>
<div class="option" data='{"value":"Szabadsagdulo","state":"Hajdu-Bihar"}'>Szabadsagdulo</div>
<div class="option" data='{"value":"Szabotanya","state":"Hajdu-Bihar"}'>Szabotanya</div>
<div class="option" data='{"value":"Szabotanyak","state":"Hajdu-Bihar"}'>Szabotanyak</div>
<div class="option" data='{"value":"Szabotiszta","state":"Hajdu-Bihar"}'>Szabotiszta</div>
<div class="option" data='{"value":"Szabotiszta Csarda","state":"Hajdu-Bihar"}'>Szabotiszta Csarda</div>
<div class="option" data='{"value":"Szakolyikert","state":"Hajdu-Bihar"}'>Szakolyikert</div>
<div class="option" data='{"value":"Szakolyikert Puszta","state":"Hajdu-Bihar"}'>Szakolyikert Puszta</div>
<div class="option" data='{"value":"Szakolykert","state":"Hajdu-Bihar"}'>Szakolykert</div>
<div class="option" data='{"value":"Szalkahalom","state":"Hajdu-Bihar"}'>Szalkahalom</div>
<div class="option" data='{"value":"Szalkahalomdulo","state":"Hajdu-Bihar"}'>Szalkahalomdulo</div>
<div class="option" data='{"value":"Szallasfoldi Tanyak","state":"Hajdu-Bihar"}'>Szallasfoldi Tanyak</div>
<div class="option" data='{"value":"Szalmas Major","state":"Hajdu-Bihar"}'>Szalmas Major</div>
<div class="option" data='{"value":"Szalmastanya","state":"Hajdu-Bihar"}'>Szalmastanya</div>
<div class="option" data='{"value":"Szandalik","state":"Hajdu-Bihar"}'>Szandalik</div>
<div class="option" data='{"value":"Szantodulo","state":"Hajdu-Bihar"}'>Szantodulo</div>
<div class="option" data='{"value":"Szarcsas","state":"Hajdu-Bihar"}'>Szarcsas</div>
<div class="option" data='{"value":"Szatmariuti Tanyak","state":"Hajdu-Bihar"}'>Szatmariuti Tanyak</div>
<div class="option" data='{"value":"Szegenytanya","state":"Hajdu-Bihar"}'>Szegenytanya</div>
<div class="option" data='{"value":"Szegfudulo","state":"Hajdu-Bihar"}'>Szegfudulo</div>
<div class="option" data='{"value":"Szekelytanya","state":"Hajdu-Bihar"}'>Szekelytanya</div>
<div class="option" data='{"value":"Szekpart","state":"Hajdu-Bihar"}'>Szekpart</div>
<div class="option" data='{"value":"Szentannapuszta","state":"Hajdu-Bihar"}'>Szentannapuszta</div>
<div class="option" data='{"value":"Szentivanhalom","state":"Hajdu-Bihar"}'>Szentivanhalom</div>
<div class="option" data='{"value":"Szentpeterszeg","state":"Hajdu-Bihar"}'>Szentpeterszeg</div>
<div class="option" data='{"value":"Szerep","state":"Hajdu-Bihar"}'>Szerep</div>
<div class="option" data='{"value":"Szeszgyar","state":"Hajdu-Bihar"}'>Szeszgyar</div>
<div class="option" data='{"value":"Szeszgyartanya","state":"Hajdu-Bihar"}'>Szeszgyartanya</div>
<div class="option" data='{"value":"Szigetor","state":"Hajdu-Bihar"}'>Szigetor</div>
<div class="option" data='{"value":"Szigetorr","state":"Hajdu-Bihar"}'>Szigetorr</div>
<div class="option" data='{"value":"Szigettanya","state":"Hajdu-Bihar"}'>Szigettanya</div>
<div class="option" data='{"value":"Szilagy","state":"Hajdu-Bihar"}'>Szilagy</div>
<div class="option" data='{"value":"Szilagyitanya","state":"Hajdu-Bihar"}'>Szilagyitanya</div>
<div class="option" data='{"value":"Szilos","state":"Hajdu-Bihar"}'>Szilos</div>
<div class="option" data='{"value":"Szilota","state":"Hajdu-Bihar"}'>Szilota</div>
<div class="option" data='{"value":"Szilvas","state":"Hajdu-Bihar"}'>Szilvas</div>
<div class="option" data='{"value":"Szilvasdulo","state":"Hajdu-Bihar"}'>Szilvasdulo</div>
<div class="option" data='{"value":"Szivaktanya","state":"Hajdu-Bihar"}'>Szivaktanya</div>
<div class="option" data='{"value":"Szivostanya","state":"Hajdu-Bihar"}'>Szivostanya</div>
<div class="option" data='{"value":"Szlavitanya","state":"Hajdu-Bihar"}'>Szlavitanya</div>
<div class="option" data='{"value":"Szoboszlai Dulo","state":"Hajdu-Bihar"}'>Szoboszlai Dulo</div>
<div class="option" data='{"value":"Szolloalj","state":"Hajdu-Bihar"}'>Szolloalj</div>
<div class="option" data='{"value":"Szolloskert","state":"Hajdu-Bihar"}'>Szolloskert</div>
<div class="option" data='{"value":"Szoloskert","state":"Hajdu-Bihar"}'>Szoloskert</div>
<div class="option" data='{"value":"Szomjasdulo","state":"Hajdu-Bihar"}'>Szomjasdulo</div>
<div class="option" data='{"value":"Szomjuhat","state":"Hajdu-Bihar"}'>Szomjuhat</div>
<div class="option" data='{"value":"Szomolyom","state":"Hajdu-Bihar"}'>Szomolyom</div>
<div class="option" data='{"value":"Szucsdulo","state":"Hajdu-Bihar"}'>Szucsdulo</div>
<div class="option" data='{"value":"Szucstanya","state":"Hajdu-Bihar"}'>Szucstanya</div>
<div class="option" data='{"value":"Szunyoghtanya","state":"Hajdu-Bihar"}'>Szunyoghtanya</div>
<div class="option" data='{"value":"Szunyogtanya","state":"Hajdu-Bihar"}'>Szunyogtanya</div>
<div class="option" data='{"value":"Szurokfozodulo","state":"Hajdu-Bihar"}'>Szurokfozodulo</div>
<div class="option" data='{"value":"Szutortanya","state":"Hajdu-Bihar"}'>Szutortanya</div>
<div class="option" data='{"value":"Tagtanya","state":"Hajdu-Bihar"}'>Tagtanya</div>
<div class="option" data='{"value":"Tajaktanya","state":"Hajdu-Bihar"}'>Tajaktanya</div>
<div class="option" data='{"value":"Taksashaz","state":"Hajdu-Bihar"}'>Taksashaz</div>
<div class="option" data='{"value":"Tarkalovasdulo","state":"Hajdu-Bihar"}'>Tarkalovasdulo</div>
<div class="option" data='{"value":"Tarkert","state":"Hajdu-Bihar"}'>Tarkert</div>
<div class="option" data='{"value":"Tartanya","state":"Hajdu-Bihar"}'>Tartanya</div>
<div class="option" data='{"value":"Tedej","state":"Hajdu-Bihar"}'>Tedej</div>
<div class="option" data='{"value":"Teglahat","state":"Hajdu-Bihar"}'>Teglahat</div>
<div class="option" data='{"value":"Teglas","state":"Hajdu-Bihar"}'>Teglas</div>
<div class="option" data='{"value":"Teglasszollo","state":"Hajdu-Bihar"}'>Teglasszollo</div>
<div class="option" data='{"value":"Telek","state":"Hajdu-Bihar"}'>Telek</div>
<div class="option" data='{"value":"Telekdulo","state":"Hajdu-Bihar"}'>Telekdulo</div>
<div class="option" data='{"value":"Telekfold","state":"Hajdu-Bihar"}'>Telekfold</div>
<div class="option" data='{"value":"Teleki","state":"Hajdu-Bihar"}'>Teleki</div>
<div class="option" data='{"value":"Telekipuszta","state":"Hajdu-Bihar"}'>Telekipuszta</div>
<div class="option" data='{"value":"Tepe","state":"Hajdu-Bihar"}'>Tepe</div>
<div class="option" data='{"value":"Tetetlen","state":"Hajdu-Bihar"}'>Tetetlen</div>
<div class="option" data='{"value":"Tikos","state":"Hajdu-Bihar"}'>Tikos</div>
<div class="option" data='{"value":"Tikostanya","state":"Hajdu-Bihar"}'>Tikostanya</div>
<div class="option" data='{"value":"Tilalmasdulo","state":"Hajdu-Bihar"}'>Tilalmasdulo</div>
<div class="option" data='{"value":"Tilalmastanya","state":"Hajdu-Bihar"}'>Tilalmastanya</div>
<div class="option" data='{"value":"Tipoka","state":"Hajdu-Bihar"}'>Tipoka</div>
<div class="option" data='{"value":"Tiszacsege","state":"Hajdu-Bihar"}'>Tiszacsege</div>
<div class="option" data='{"value":"Tiszagyulahaza","state":"Hajdu-Bihar"}'>Tiszagyulahaza</div>
<div class="option" data='{"value":"Tiszavolgy","state":"Hajdu-Bihar"}'>Tiszavolgy</div>
<div class="option" data='{"value":"Tisztaviz","state":"Hajdu-Bihar"}'>Tisztaviz</div>
<div class="option" data='{"value":"Tivorany","state":"Hajdu-Bihar"}'>Tivorany</div>
<div class="option" data='{"value":"To Koze","state":"Hajdu-Bihar"}'>To Koze</div>
<div class="option" data='{"value":"Tobytelep","state":"Hajdu-Bihar"}'>Tobytelep</div>
<div class="option" data='{"value":"Tofalu","state":"Hajdu-Bihar"}'>Tofalu</div>
<div class="option" data='{"value":"Tohat","state":"Hajdu-Bihar"}'>Tohat</div>
<div class="option" data='{"value":"Tohatartanya","state":"Hajdu-Bihar"}'>Tohatartanya</div>
<div class="option" data='{"value":"Tokostanya","state":"Hajdu-Bihar"}'>Tokostanya</div>
<div class="option" data='{"value":"Tokoz","state":"Hajdu-Bihar"}'>Tokoz</div>
<div class="option" data='{"value":"Told","state":"Hajdu-Bihar"}'>Told</div>
<div class="option" data='{"value":"Toldi Puszta","state":"Hajdu-Bihar"}'>Toldi Puszta</div>
<div class="option" data='{"value":"Tolditanyak","state":"Hajdu-Bihar"}'>Tolditanyak</div>
<div class="option" data='{"value":"Tolvajlapos","state":"Hajdu-Bihar"}'>Tolvajlapos</div>
<div class="option" data='{"value":"Tomaresz","state":"Hajdu-Bihar"}'>Tomaresz</div>
<div class="option" data='{"value":"Topasziget","state":"Hajdu-Bihar"}'>Topasziget</div>
<div class="option" data='{"value":"Tormas","state":"Hajdu-Bihar"}'>Tormas</div>
<div class="option" data='{"value":"Tormasdulo","state":"Hajdu-Bihar"}'>Tormasdulo</div>
<div class="option" data='{"value":"Torokkuttanya","state":"Hajdu-Bihar"}'>Torokkuttanya</div>
<div class="option" data='{"value":"Totfalupuszta","state":"Hajdu-Bihar"}'>Totfalupuszta</div>
<div class="option" data='{"value":"Tothfalu","state":"Hajdu-Bihar"}'>Tothfalu</div>
<div class="option" data='{"value":"Tothtelep","state":"Hajdu-Bihar"}'>Tothtelep</div>
<div class="option" data='{"value":"Toviskes","state":"Hajdu-Bihar"}'>Toviskes</div>
<div class="option" data='{"value":"Toviskeshat","state":"Hajdu-Bihar"}'>Toviskeshat</div>
<div class="option" data='{"value":"Tuskesdulo","state":"Hajdu-Bihar"}'>Tuskesdulo</div>
<div class="option" data='{"value":"Tuzok","state":"Hajdu-Bihar"}'>Tuzok</div>
<div class="option" data='{"value":"Ugartelek","state":"Hajdu-Bihar"}'>Ugartelek</div>
<div class="option" data='{"value":"Ujfalussytanya","state":"Hajdu-Bihar"}'>Ujfalussytanya</div>
<div class="option" data='{"value":"Ujiraz","state":"Hajdu-Bihar"}'>Ujiraz</div>
<div class="option" data='{"value":"Ujkert","state":"Hajdu-Bihar"}'>Ujkert</div>
<div class="option" data='{"value":"Ujleta","state":"Hajdu-Bihar"}'>Ujleta</div>
<div class="option" data='{"value":"Ujletai Tanyak","state":"Hajdu-Bihar"}'>Ujletai Tanyak</div>
<div class="option" data='{"value":"Ujszentmargita","state":"Hajdu-Bihar"}'>Ujszentmargita</div>
<div class="option" data='{"value":"Ujszollo","state":"Hajdu-Bihar"}'>Ujszollo</div>
<div class="option" data='{"value":"Ujszolloskert","state":"Hajdu-Bihar"}'>Ujszolloskert</div>
<div class="option" data='{"value":"Ujtanya","state":"Hajdu-Bihar"}'>Ujtanya</div>
<div class="option" data='{"value":"Ujtelep","state":"Hajdu-Bihar"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujtikos","state":"Hajdu-Bihar"}'>Ujtikos</div>
<div class="option" data='{"value":"Ujtitkos","state":"Hajdu-Bihar"}'>Ujtitkos</div>
<div class="option" data='{"value":"Ujviag","state":"Hajdu-Bihar"}'>Ujviag</div>
<div class="option" data='{"value":"Ujvilag","state":"Hajdu-Bihar"}'>Ujvilag</div>
<div class="option" data='{"value":"Urmoshat","state":"Hajdu-Bihar"}'>Urmoshat</div>
<div class="option" data='{"value":"Vadaszdulo","state":"Hajdu-Bihar"}'>Vadaszdulo</div>
<div class="option" data='{"value":"Vajdadulo","state":"Hajdu-Bihar"}'>Vajdadulo</div>
<div class="option" data='{"value":"Vajnatanya","state":"Hajdu-Bihar"}'>Vajnatanya</div>
<div class="option" data='{"value":"Vakhelydulo","state":"Hajdu-Bihar"}'>Vakhelydulo</div>
<div class="option" data='{"value":"Valeriadulo","state":"Hajdu-Bihar"}'>Valeriadulo</div>
<div class="option" data='{"value":"Vamospercs","state":"Hajdu-Bihar"}'>Vamospercs</div>
<div class="option" data='{"value":"Vancsod","state":"Hajdu-Bihar"}'>Vancsod</div>
<div class="option" data='{"value":"Varaditanya","state":"Hajdu-Bihar"}'>Varaditanya</div>
<div class="option" data='{"value":"Vargatanya","state":"Hajdu-Bihar"}'>Vargatanya</div>
<div class="option" data='{"value":"Varoskert","state":"Hajdu-Bihar"}'>Varoskert</div>
<div class="option" data='{"value":"Varytag","state":"Hajdu-Bihar"}'>Varytag</div>
<div class="option" data='{"value":"Vasarter Fatelep","state":"Hajdu-Bihar"}'>Vasarter Fatelep</div>
<div class="option" data='{"value":"Vaskapu","state":"Hajdu-Bihar"}'>Vaskapu</div>
<div class="option" data='{"value":"Vasstanya","state":"Hajdu-Bihar"}'>Vasstanya</div>
<div class="option" data='{"value":"Vecseytanya","state":"Hajdu-Bihar"}'>Vecseytanya</div>
<div class="option" data='{"value":"Vekerd","state":"Hajdu-Bihar"}'>Vekerd</div>
<div class="option" data='{"value":"Venkert","state":"Hajdu-Bihar"}'>Venkert</div>
<div class="option" data='{"value":"Vereshattanya","state":"Hajdu-Bihar"}'>Vereshattanya</div>
<div class="option" data='{"value":"Veresszikdulo","state":"Hajdu-Bihar"}'>Veresszikdulo</div>
<div class="option" data='{"value":"Verestenger","state":"Hajdu-Bihar"}'>Verestenger</div>
<div class="option" data='{"value":"Vertes","state":"Hajdu-Bihar"}'>Vertes</div>
<div class="option" data='{"value":"Vertesliget","state":"Hajdu-Bihar"}'>Vertesliget</div>
<div class="option" data='{"value":"Vetesitanya","state":"Hajdu-Bihar"}'>Vetesitanya</div>
<div class="option" data='{"value":"Viczmanditanya","state":"Hajdu-Bihar"}'>Viczmanditanya</div>
<div class="option" data='{"value":"Viczmandytanya","state":"Hajdu-Bihar"}'>Viczmandytanya</div>
<div class="option" data='{"value":"Vid","state":"Hajdu-Bihar"}'>Vid</div>
<div class="option" data='{"value":"Vidakert","state":"Hajdu-Bihar"}'>Vidakert</div>
<div class="option" data='{"value":"Vidatanya","state":"Hajdu-Bihar"}'>Vidatanya</div>
<div class="option" data='{"value":"Vidifold","state":"Hajdu-Bihar"}'>Vidifold</div>
<div class="option" data='{"value":"Vidpuszta","state":"Hajdu-Bihar"}'>Vidpuszta</div>
<div class="option" data='{"value":"Vightanya","state":"Hajdu-Bihar"}'>Vightanya</div>
<div class="option" data='{"value":"Villongo","state":"Hajdu-Bihar"}'>Villongo</div>
<div class="option" data='{"value":"Vindispuszta","state":"Hajdu-Bihar"}'>Vindispuszta</div>
<div class="option" data='{"value":"Viragoskut","state":"Hajdu-Bihar"}'>Viragoskut</div>
<div class="option" data='{"value":"Viteztelek","state":"Hajdu-Bihar"}'>Viteztelek</div>
<div class="option" data='{"value":"Viteztelkek","state":"Hajdu-Bihar"}'>Viteztelkek</div>
<div class="option" data='{"value":"Viz Tisztaja","state":"Hajdu-Bihar"}'>Viz Tisztaja</div>
<div class="option" data='{"value":"Vizesdulo","state":"Hajdu-Bihar"}'>Vizesdulo</div>
<div class="option" data='{"value":"Viztisztatanya","state":"Hajdu-Bihar"}'>Viztisztatanya</div>
<div class="option" data='{"value":"Volgyes","state":"Hajdu-Bihar"}'>Volgyes</div>
<div class="option" data='{"value":"Zadokosdulo","state":"Hajdu-Bihar"}'>Zadokosdulo</div>
<div class="option" data='{"value":"Zajgato","state":"Hajdu-Bihar"}'>Zajgato</div>
<div class="option" data='{"value":"Zajgatodulo","state":"Hajdu-Bihar"}'>Zajgatodulo</div>
<div class="option" data='{"value":"Zajgatoitanyak","state":"Hajdu-Bihar"}'>Zajgatoitanyak</div>
<div class="option" data='{"value":"Zelemer","state":"Hajdu-Bihar"}'>Zelemer</div>
<div class="option" data='{"value":"Zodony","state":"Hajdu-Bihar"}'>Zodony</div>
<div class="option" data='{"value":"Zsaka","state":"Hajdu-Bihar"}'>Zsaka</div>
<div class="option" data='{"value":"Zsakos","state":"Hajdu-Bihar"}'>Zsakos</div>
<div class="option" data='{"value":"Zsiphalomdulo","state":"Hajdu-Bihar"}'>Zsiphalomdulo</div>
<div class="option" data='{"value":"Zsoldos","state":"Hajdu-Bihar"}'>Zsoldos</div>
<div class="option" data='{"value":"Zsoldosdulo","state":"Hajdu-Bihar"}'>Zsoldosdulo</div>
<div class="option" data='{"value":"Zsombokos","state":"Hajdu-Bihar"}'>Zsombokos</div>
<div class="option" id="option_end" data='{"value":"Zubogoresz","state":"Hajdu-Bihar"}'>Zubogoresz</div>

