<div class="option" data='{"value":"Acs","state":"Komarom"}'>Acs</div>
<div class="option" data='{"value":"Acsteszer","state":"Komarom"}'>Acsteszer</div>
<div class="option" data='{"value":"Acsteszeripuszta","state":"Komarom"}'>Acsteszeripuszta</div>
<div class="option" data='{"value":"Adammajor","state":"Komarom"}'>Adammajor</div>
<div class="option" data='{"value":"Agnesakna","state":"Komarom"}'>Agnesakna</div>
<div class="option" data='{"value":"Agostyan","state":"Komarom"}'>Agostyan</div>
<div class="option" data='{"value":"Aka","state":"Komarom"}'>Aka</div>
<div class="option" data='{"value":"Almasfuzito","state":"Komarom"}'>Almasfuzito</div>
<div class="option" data='{"value":"Almasneszmely","state":"Komarom"}'>Almasneszmely</div>
<div class="option" data='{"value":"Almaspuszta","state":"Komarom"}'>Almaspuszta</div>
<div class="option" data='{"value":"Alsobanyatelep","state":"Komarom"}'>Alsobanyatelep</div>
<div class="option" data='{"value":"Alsobikol","state":"Komarom"}'>Alsobikol</div>
<div class="option" data='{"value":"Alsoborcshaza","state":"Komarom"}'>Alsoborcshaza</div>
<div class="option" data='{"value":"Alsodulo","state":"Komarom"}'>Alsodulo</div>
<div class="option" data='{"value":"Alsogalla","state":"Komarom"}'>Alsogalla</div>
<div class="option" data='{"value":"Alsohegy","state":"Komarom"}'>Alsohegy</div>
<div class="option" data='{"value":"Alsopuszta","state":"Komarom"}'>Alsopuszta</div>
<div class="option" data='{"value":"Alsoszollo","state":"Komarom"}'>Alsoszollo</div>
<div class="option" data='{"value":"Alsovadacs","state":"Komarom"}'>Alsovadacs</div>
<div class="option" data='{"value":"Alsovasdinnyepuszta","state":"Komarom"}'>Alsovasdinnyepuszta</div>
<div class="option" data='{"value":"Altarobanyatelep","state":"Komarom"}'>Altarobanyatelep</div>
<div class="option" data='{"value":"Andrekakert","state":"Komarom"}'>Andrekakert</div>
<div class="option" data='{"value":"Annamajor","state":"Komarom"}'>Annamajor</div>
<div class="option" data='{"value":"Annavolgyibanya","state":"Komarom"}'>Annavolgyibanya</div>
<div class="option" data='{"value":"Apatipuszta","state":"Komarom"}'>Apatipuszta</div>
<div class="option" data='{"value":"Aranyhegy","state":"Komarom"}'>Aranyhegy</div>
<div class="option" data='{"value":"Aszar","state":"Komarom"}'>Aszar</div>
<div class="option" data='{"value":"Babolna","state":"Komarom"}'>Babolna</div>
<div class="option" data='{"value":"Babolnai Kismajor","state":"Komarom"}'>Babolnai Kismajor</div>
<div class="option" data='{"value":"Babolnapuszta","state":"Komarom"}'>Babolnapuszta</div>
<div class="option" data='{"value":"Baj","state":"Komarom"}'>Baj</div>
<div class="option" data='{"value":"Bajna","state":"Komarom"}'>Bajna</div>
<div class="option" data='{"value":"Bajnatanya","state":"Komarom"}'>Bajnatanya</div>
<div class="option" data='{"value":"Bajot","state":"Komarom"}'>Bajot</div>
<div class="option" data='{"value":"Bajzo","state":"Komarom"}'>Bajzo</div>
<div class="option" data='{"value":"Bakcsanyitanya","state":"Komarom"}'>Bakcsanyitanya</div>
<div class="option" data='{"value":"Bakonybank","state":"Komarom"}'>Bakonybank</div>
<div class="option" data='{"value":"Bakonysarkany","state":"Komarom"}'>Bakonysarkany</div>
<div class="option" data='{"value":"Bakonyszombathely","state":"Komarom"}'>Bakonyszombathely</div>
<div class="option" data='{"value":"Baloghpuszta","state":"Komarom"}'>Baloghpuszta</div>
<div class="option" data='{"value":"Baloghtanya","state":"Komarom"}'>Baloghtanya</div>
<div class="option" data='{"value":"Bana","state":"Komarom"}'>Bana</div>
<div class="option" data='{"value":"Banhida","state":"Komarom"}'>Banhida</div>
<div class="option" data='{"value":"Bankhida","state":"Komarom"}'>Bankhida</div>
<div class="option" data='{"value":"Banomi Dulo","state":"Komarom"}'>Banomi Dulo</div>
<div class="option" data='{"value":"Banyahegy","state":"Komarom"}'>Banyahegy</div>
<div class="option" data='{"value":"Barsonyos","state":"Komarom"}'>Barsonyos</div>
<div class="option" data='{"value":"Basaharc","state":"Komarom"}'>Basaharc</div>
<div class="option" data='{"value":"Battyanpuszta","state":"Komarom"}'>Battyanpuszta</div>
<div class="option" data='{"value":"Beditanya","state":"Komarom"}'>Beditanya</div>
<div class="option" data='{"value":"Belapuszta","state":"Komarom"}'>Belapuszta</div>
<div class="option" data='{"value":"Bellatanya","state":"Komarom"}'>Bellatanya</div>
<div class="option" data='{"value":"Bersekbanya","state":"Komarom"}'>Bersekbanya</div>
<div class="option" data='{"value":"Beszedestanya","state":"Komarom"}'>Beszedestanya</div>
<div class="option" data='{"value":"Bikol","state":"Komarom"}'>Bikol</div>
<div class="option" data='{"value":"Billegpuszta","state":"Komarom"}'>Billegpuszta</div>
<div class="option" data='{"value":"Bindatag","state":"Komarom"}'>Bindatag</div>
<div class="option" data='{"value":"Binderpuszta","state":"Komarom"}'>Binderpuszta</div>
<div class="option" data='{"value":"Bitocivolgy","state":"Komarom"}'>Bitocivolgy</div>
<div class="option" data='{"value":"Bitoczi Volgy","state":"Komarom"}'>Bitoczi Volgy</div>
<div class="option" data='{"value":"Bocskoroskut","state":"Komarom"}'>Bocskoroskut</div>
<div class="option" data='{"value":"Bocskoroskuti Dulo","state":"Komarom"}'>Bocskoroskuti Dulo</div>
<div class="option" data='{"value":"Bodaitanya","state":"Komarom"}'>Bodaitanya</div>
<div class="option" data='{"value":"Bodaytanya","state":"Komarom"}'>Bodaytanya</div>
<div class="option" data='{"value":"Bodzamalom","state":"Komarom"}'>Bodzamalom</div>
<div class="option" data='{"value":"Bokod","state":"Komarom"}'>Bokod</div>
<div class="option" data='{"value":"Boldogasszonypuszta","state":"Komarom"}'>Boldogasszonypuszta</div>
<div class="option" data='{"value":"Bortikuti Dulo","state":"Komarom"}'>Bortikuti Dulo</div>
<div class="option" data='{"value":"Bottkamajor","state":"Komarom"}'>Bottkamajor</div>
<div class="option" data='{"value":"Bukkfej","state":"Komarom"}'>Bukkfej</div>
<div class="option" data='{"value":"Ciganykut","state":"Komarom"}'>Ciganykut</div>
<div class="option" data='{"value":"Coberpuszta","state":"Komarom"}'>Coberpuszta</div>
<div class="option" data='{"value":"Concohat","state":"Komarom"}'>Concohat</div>
<div class="option" data='{"value":"Concohati Mellektanya","state":"Komarom"}'>Concohati Mellektanya</div>
<div class="option" data='{"value":"Csakanyospuszta","state":"Komarom"}'>Csakanyospuszta</div>
<div class="option" data='{"value":"Csakanypuszta","state":"Komarom"}'>Csakanypuszta</div>
<div class="option" data='{"value":"Csaszar","state":"Komarom"}'>Csaszar</div>
<div class="option" data='{"value":"Csatka","state":"Komarom"}'>Csatka</div>
<div class="option" data='{"value":"Csem","state":"Komarom"}'>Csem</div>
<div class="option" data='{"value":"Csemerhaz","state":"Komarom"}'>Csemerhaz</div>
<div class="option" data='{"value":"Csemerhazimajor","state":"Komarom"}'>Csemerhazimajor</div>
<div class="option" data='{"value":"Csemicsarda","state":"Komarom"}'>Csemicsarda</div>
<div class="option" data='{"value":"Csempuszta","state":"Komarom"}'>Csempuszta</div>
<div class="option" data='{"value":"Csep","state":"Komarom"}'>Csep</div>
<div class="option" data='{"value":"Csepieritanya","state":"Komarom"}'>Csepieritanya</div>
<div class="option" data='{"value":"Cservolgy","state":"Komarom"}'>Cservolgy</div>
<div class="option" data='{"value":"Csev","state":"Komarom"}'>Csev</div>
<div class="option" data='{"value":"Csicso","state":"Komarom"}'>Csicso</div>
<div class="option" data='{"value":"Csicsotanya","state":"Komarom"}'>Csicsotanya</div>
<div class="option" data='{"value":"Csikotelep","state":"Komarom"}'>Csikotelep</div>
<div class="option" data='{"value":"Csillapuszta","state":"Komarom"}'>Csillapuszta</div>
<div class="option" data='{"value":"Csokasdulo","state":"Komarom"}'>Csokasdulo</div>
<div class="option" data='{"value":"Csolnok","state":"Komarom"}'>Csolnok</div>
<div class="option" data='{"value":"Csonkatanya","state":"Komarom"}'>Csonkatanya</div>
<div class="option" data='{"value":"Cukorgyar","state":"Komarom"}'>Cukorgyar</div>
<div class="option" data='{"value":"Cukorgyartelep","state":"Komarom"}'>Cukorgyartelep</div>
<div class="option" data='{"value":"Dad","state":"Komarom"}'>Dad</div>
<div class="option" data='{"value":"Dag","state":"Komarom"}'>Dag</div>
<div class="option" data='{"value":"Diospuszta","state":"Komarom"}'>Diospuszta</div>
<div class="option" data='{"value":"Dobonkuti Dulo","state":"Komarom"}'>Dobonkuti Dulo</div>
<div class="option" data='{"value":"Domonkospuszta","state":"Komarom"}'>Domonkospuszta</div>
<div class="option" data='{"value":"Domos","state":"Komarom"}'>Domos</div>
<div class="option" data='{"value":"Domsodi Tanyak","state":"Komarom"}'>Domsodi Tanyak</div>
<div class="option" data='{"value":"Dorog","state":"Komarom"}'>Dorog</div>
<div class="option" data='{"value":"Dorogi Puszta","state":"Komarom"}'>Dorogi Puszta</div>
<div class="option" data='{"value":"Ducztanya","state":"Komarom"}'>Ducztanya</div>
<div class="option" data='{"value":"Dunaalmas","state":"Komarom"}'>Dunaalmas</div>
<div class="option" data='{"value":"Dunaszentmiklos","state":"Komarom"}'>Dunaszentmiklos</div>
<div class="option" data='{"value":"Ebszonybanya","state":"Komarom"}'>Ebszonybanya</div>
<div class="option" data='{"value":"Ecs","state":"Komarom"}'>Ecs</div>
<div class="option" data='{"value":"Egyhazapuszta","state":"Komarom"}'>Egyhazapuszta</div>
<div class="option" data='{"value":"Elohegy","state":"Komarom"}'>Elohegy</div>
<div class="option" data='{"value":"Epol","state":"Komarom"}'>Epol</div>
<div class="option" data='{"value":"Ernomajor","state":"Komarom"}'>Ernomajor</div>
<div class="option" data='{"value":"Eromutelep","state":"Komarom"}'>Eromutelep</div>
<div class="option" data='{"value":"Esztergom","state":"Komarom"}'>Esztergom</div>
<div class="option" data='{"value":"Ete","state":"Komarom"}'>Ete</div>
<div class="option" data='{"value":"Eternitgyar","state":"Komarom"}'>Eternitgyar</div>
<div class="option" data='{"value":"Facankert","state":"Komarom"}'>Facankert</div>
<div class="option" data='{"value":"Facankertmajor","state":"Komarom"}'>Facankertmajor</div>
<div class="option" data='{"value":"Fari Kut","state":"Komarom"}'>Fari Kut</div>
<div class="option" data='{"value":"Farikuti Dulo","state":"Komarom"}'>Farikuti Dulo</div>
<div class="option" data='{"value":"Farkaskut","state":"Komarom"}'>Farkaskut</div>
<div class="option" data='{"value":"Farkaskuti Major","state":"Komarom"}'>Farkaskuti Major</div>
<div class="option" data='{"value":"Farkastorokpuszta","state":"Komarom"}'>Farkastorokpuszta</div>
<div class="option" data='{"value":"Fatelep","state":"Komarom"}'>Fatelep</div>
<div class="option" data='{"value":"Feketevizpuszta","state":"Komarom"}'>Feketevizpuszta</div>
<div class="option" data='{"value":"Felsobanyatelep","state":"Komarom"}'>Felsobanyatelep</div>
<div class="option" data='{"value":"Felsoborcshaza","state":"Komarom"}'>Felsoborcshaza</div>
<div class="option" data='{"value":"Felsoborcshazapuszta","state":"Komarom"}'>Felsoborcshazapuszta</div>
<div class="option" data='{"value":"Felsogalla","state":"Komarom"}'>Felsogalla</div>
<div class="option" data='{"value":"Felsokenderes","state":"Komarom"}'>Felsokenderes</div>
<div class="option" data='{"value":"Felsovasdinnyepuszta","state":"Komarom"}'>Felsovasdinnyepuszta</div>
<div class="option" data='{"value":"Felszabadulas Ut","state":"Komarom"}'>Felszabadulas Ut</div>
<div class="option" data='{"value":"Felszabadulas Utja","state":"Komarom"}'>Felszabadulas Utja</div>
<div class="option" data='{"value":"Fenyesdulo","state":"Komarom"}'>Fenyesdulo</div>
<div class="option" data='{"value":"Ferencmajor","state":"Komarom"}'>Ferencmajor</div>
<div class="option" data='{"value":"Fodortanya","state":"Komarom"}'>Fodortanya</div>
<div class="option" data='{"value":"Frigyesmajor","state":"Komarom"}'>Frigyesmajor</div>
<div class="option" data='{"value":"Fuzihegy","state":"Komarom"}'>Fuzihegy</div>
<div class="option" data='{"value":"Gelegenyespuszta","state":"Komarom"}'>Gelegenyespuszta</div>
<div class="option" data='{"value":"Gerecse","state":"Komarom"}'>Gerecse</div>
<div class="option" data='{"value":"Ghiczipuszta","state":"Komarom"}'>Ghiczipuszta</div>
<div class="option" data='{"value":"Ghyczypuszta","state":"Komarom"}'>Ghyczypuszta</div>
<div class="option" data='{"value":"Gombaspuszta","state":"Komarom"}'>Gombaspuszta</div>
<div class="option" data='{"value":"Gorenyvarpuszta","state":"Komarom"}'>Gorenyvarpuszta</div>
<div class="option" data='{"value":"Gorogto","state":"Komarom"}'>Gorogto</div>
<div class="option" data='{"value":"Gran","state":"Komarom"}'>Gran</div>
<div class="option" data='{"value":"Grebicspuszta","state":"Komarom"}'>Grebicspuszta</div>
<div class="option" data='{"value":"Gyarmatpuszta","state":"Komarom"}'>Gyarmatpuszta</div>
<div class="option" data='{"value":"Gyermely","state":"Komarom"}'>Gyermely</div>
<div class="option" data='{"value":"Gyermelyi Szeszgyar","state":"Komarom"}'>Gyermelyi Szeszgyar</div>
<div class="option" data='{"value":"Gyorgymajor","state":"Komarom"}'>Gyorgymajor</div>
<div class="option" data='{"value":"Gyuruspuszta","state":"Komarom"}'>Gyuruspuszta</div>
<div class="option" data='{"value":"Halasto","state":"Komarom"}'>Halasto</div>
<div class="option" data='{"value":"Hamvasbanya","state":"Komarom"}'>Hamvasbanya</div>
<div class="option" data='{"value":"Hanta","state":"Komarom"}'>Hanta</div>
<div class="option" data='{"value":"Hantospuszta","state":"Komarom"}'>Hantospuszta</div>
<div class="option" data='{"value":"Haraszt","state":"Komarom"}'>Haraszt</div>
<div class="option" data='{"value":"Harasztibanya","state":"Komarom"}'>Harasztibanya</div>
<div class="option" data='{"value":"Harasztitanya","state":"Komarom"}'>Harasztitanya</div>
<div class="option" data='{"value":"Harasztpuszta","state":"Komarom"}'>Harasztpuszta</div>
<div class="option" data='{"value":"Hasztanya","state":"Komarom"}'>Hasztanya</div>
<div class="option" data='{"value":"Hathalom","state":"Komarom"}'>Hathalom</div>
<div class="option" data='{"value":"Hathalompuszta","state":"Komarom"}'>Hathalompuszta</div>
<div class="option" data='{"value":"Hereg","state":"Komarom"}'>Hereg</div>
<div class="option" data='{"value":"Heresdulo","state":"Komarom"}'>Heresdulo</div>
<div class="option" data='{"value":"Holmantag","state":"Komarom"}'>Holmantag</div>
<div class="option" data='{"value":"Homraktanya","state":"Komarom"}'>Homraktanya</div>
<div class="option" data='{"value":"Honvedmajor","state":"Komarom"}'>Honvedmajor</div>
<div class="option" data='{"value":"Horvattanya","state":"Komarom"}'>Horvattanya</div>
<div class="option" data='{"value":"Hosszudulo","state":"Komarom"}'>Hosszudulo</div>
<div class="option" data='{"value":"Irtasmajor","state":"Komarom"}'>Irtasmajor</div>
<div class="option" data='{"value":"Irtaspuszta","state":"Komarom"}'>Irtaspuszta</div>
<div class="option" data='{"value":"Istvanhaz","state":"Komarom"}'>Istvanhaz</div>
<div class="option" data='{"value":"Istvanhaza","state":"Komarom"}'>Istvanhaza</div>
<div class="option" data='{"value":"Istvanmajor","state":"Komarom"}'>Istvanmajor</div>
<div class="option" data='{"value":"Jancsarmajor","state":"Komarom"}'>Jancsarmajor</div>
<div class="option" data='{"value":"Janosmajor","state":"Komarom"}'>Janosmajor</div>
<div class="option" data='{"value":"Jegespuszta","state":"Komarom"}'>Jegespuszta</div>
<div class="option" data='{"value":"Jeneitanya","state":"Komarom"}'>Jeneitanya</div>
<div class="option" data='{"value":"Juhasztag","state":"Komarom"}'>Juhasztag</div>
<div class="option" data='{"value":"Kablasmajor","state":"Komarom"}'>Kablasmajor</div>
<div class="option" data='{"value":"Kajand","state":"Komarom"}'>Kajand</div>
<div class="option" data='{"value":"Kajandi Major","state":"Komarom"}'>Kajandi Major</div>
<div class="option" data='{"value":"Kalvaria Dulo","state":"Komarom"}'>Kalvaria Dulo</div>
<div class="option" data='{"value":"Kapberek","state":"Komarom"}'>Kapberek</div>
<div class="option" data='{"value":"Kapberekpuszta","state":"Komarom"}'>Kapberekpuszta</div>
<div class="option" data='{"value":"Kapocstanya","state":"Komarom"}'>Kapocstanya</div>
<div class="option" data='{"value":"Karpatuspuszta","state":"Komarom"}'>Karpatuspuszta</div>
<div class="option" data='{"value":"Katpuszta","state":"Komarom"}'>Katpuszta</div>
<div class="option" data='{"value":"Katteridulo","state":"Komarom"}'>Katteridulo</div>
<div class="option" data='{"value":"Kecsked","state":"Komarom"}'>Kecsked</div>
<div class="option" data='{"value":"Kenderhegy","state":"Komarom"}'>Kenderhegy</div>
<div class="option" data='{"value":"Kenyermezo","state":"Komarom"}'>Kenyermezo</div>
<div class="option" data='{"value":"Kerekdomb","state":"Komarom"}'>Kerekdomb</div>
<div class="option" data='{"value":"Kerekteleki","state":"Komarom"}'>Kerekteleki</div>
<div class="option" data='{"value":"Kerekto","state":"Komarom"}'>Kerekto</div>
<div class="option" data='{"value":"Kesztolc","state":"Komarom"}'>Kesztolc</div>
<div class="option" data='{"value":"Kettospince","state":"Komarom"}'>Kettospince</div>
<div class="option" data='{"value":"Kettospincedulo","state":"Komarom"}'>Kettospincedulo</div>
<div class="option" data='{"value":"Kinizsimalom","state":"Komarom"}'>Kinizsimalom</div>
<div class="option" data='{"value":"Kisber","state":"Komarom"}'>Kisber</div>
<div class="option" data='{"value":"Kisborcshaza","state":"Komarom"}'>Kisborcshaza</div>
<div class="option" data='{"value":"Kiscsakany","state":"Komarom"}'>Kiscsakany</div>
<div class="option" data='{"value":"Kiscsanak","state":"Komarom"}'>Kiscsanak</div>
<div class="option" data='{"value":"Kiscsevpuszta","state":"Komarom"}'>Kiscsevpuszta</div>
<div class="option" data='{"value":"Kisfari","state":"Komarom"}'>Kisfari</div>
<div class="option" data='{"value":"Kisfaridulo","state":"Komarom"}'>Kisfaridulo</div>
<div class="option" data='{"value":"Kisherkaly","state":"Komarom"}'>Kisherkaly</div>
<div class="option" data='{"value":"Kisigmand","state":"Komarom"}'>Kisigmand</div>
<div class="option" data='{"value":"Kiskuria","state":"Komarom"}'>Kiskuria</div>
<div class="option" data='{"value":"Kisparnakpuszta","state":"Komarom"}'>Kisparnakpuszta</div>
<div class="option" data='{"value":"Kistagyospuszta","state":"Komarom"}'>Kistagyospuszta</div>
<div class="option" data='{"value":"Kistanya","state":"Komarom"}'>Kistanya</div>
<div class="option" data='{"value":"Kistarcspuszta","state":"Komarom"}'>Kistarcspuszta</div>
<div class="option" data='{"value":"Klastrompuszta","state":"Komarom"}'>Klastrompuszta</div>
<div class="option" data='{"value":"Koalja","state":"Komarom"}'>Koalja</div>
<div class="option" data='{"value":"Koaljai Dulo","state":"Komarom"}'>Koaljai Dulo</div>
<div class="option" data='{"value":"Kocs","state":"Komarom"}'>Kocs</div>
<div class="option" data='{"value":"Kocsi Keseruviztelep","state":"Komarom"}'>Kocsi Keseruviztelep</div>
<div class="option" data='{"value":"Kolinatanya","state":"Komarom"}'>Kolinatanya</div>
<div class="option" data='{"value":"Komalom","state":"Komarom"}'>Komalom</div>
<div class="option" data='{"value":"Komarom","state":"Komarom"}'>Komarom</div>
<div class="option" data='{"value":"Komarom County","state":"Komarom"}'>Komarom County</div>
<div class="option" data='{"value":"Komarom Megye","state":"Komarom"}'>Komarom Megye</div>
<div class="option" data='{"value":"Komaromujvaros","state":"Komarom"}'>Komaromujvaros</div>
<div class="option" data='{"value":"Komlod","state":"Komarom"}'>Komlod</div>
<div class="option" data='{"value":"Kopaszhegy","state":"Komarom"}'>Kopaszhegy</div>
<div class="option" data='{"value":"Koppanmonostor","state":"Komarom"}'>Koppanmonostor</div>
<div class="option" data='{"value":"Koppanymonostor","state":"Komarom"}'>Koppanymonostor</div>
<div class="option" data='{"value":"Kornye","state":"Komarom"}'>Kornye</div>
<div class="option" data='{"value":"Kornyebanya","state":"Komarom"}'>Kornyebanya</div>
<div class="option" data='{"value":"Kornyei Major","state":"Komarom"}'>Kornyei Major</div>
<div class="option" data='{"value":"Kornyemajor","state":"Komarom"}'>Kornyemajor</div>
<div class="option" data='{"value":"Koromla","state":"Komarom"}'>Koromla</div>
<div class="option" data='{"value":"Korosimalom","state":"Komarom"}'>Korosimalom</div>
<div class="option" data='{"value":"Kortvelyespuszta","state":"Komarom"}'>Kortvelyespuszta</div>
<div class="option" data='{"value":"Kosztolanyipuszta","state":"Komarom"}'>Kosztolanyipuszta</div>
<div class="option" data='{"value":"Kovacsret","state":"Komarom"}'>Kovacsret</div>
<div class="option" data='{"value":"Kovacstanya","state":"Komarom"}'>Kovacstanya</div>
<div class="option" data='{"value":"Kozepsovasdinnyepuszta","state":"Komarom"}'>Kozepsovasdinnyepuszta</div>
<div class="option" data='{"value":"Kozepvasdinnyepuszta","state":"Komarom"}'>Kozepvasdinnyepuszta</div>
<div class="option" data='{"value":"Kubovicstanya","state":"Komarom"}'>Kubovicstanya</div>
<div class="option" data='{"value":"Kuriadulo","state":"Komarom"}'>Kuriadulo</div>
<div class="option" data='{"value":"Kusztus","state":"Komarom"}'>Kusztus</div>
<div class="option" data='{"value":"Kusztusidulo","state":"Komarom"}'>Kusztusidulo</div>
<div class="option" data='{"value":"Labanctanya","state":"Komarom"}'>Labanctanya</div>
<div class="option" data='{"value":"Labatlan","state":"Komarom"}'>Labatlan</div>
<div class="option" data='{"value":"Lapatari Malom","state":"Komarom"}'>Lapatari Malom</div>
<div class="option" data='{"value":"Laposidulo","state":"Komarom"}'>Laposidulo</div>
<div class="option" data='{"value":"Leanyvar","state":"Komarom"}'>Leanyvar</div>
<div class="option" data='{"value":"Lesaljamajor","state":"Komarom"}'>Lesaljamajor</div>
<div class="option" data='{"value":"Likocsszollo","state":"Komarom"}'>Likocsszollo</div>
<div class="option" data='{"value":"Likocsszolok","state":"Komarom"}'>Likocsszolok</div>
<div class="option" data='{"value":"Lobkovitztanya","state":"Komarom"}'>Lobkovitztanya</div>
<div class="option" data='{"value":"Losonctelep","state":"Komarom"}'>Losonctelep</div>
<div class="option" data='{"value":"Losonczitelep","state":"Komarom"}'>Losonczitelep</div>
<div class="option" data='{"value":"Lovadpuszta","state":"Komarom"}'>Lovadpuszta</div>
<div class="option" data='{"value":"Majkpuszta","state":"Komarom"}'>Majkpuszta</div>
<div class="option" data='{"value":"Makkpuszta","state":"Komarom"}'>Makkpuszta</div>
<div class="option" data='{"value":"Mallertanya","state":"Komarom"}'>Mallertanya</div>
<div class="option" data='{"value":"Malom","state":"Komarom"}'>Malom</div>
<div class="option" data='{"value":"Mariahalom","state":"Komarom"}'>Mariahalom</div>
<div class="option" data='{"value":"Mariahalompuszta","state":"Komarom"}'>Mariahalompuszta</div>
<div class="option" data='{"value":"Mariamagdolnapuszta","state":"Komarom"}'>Mariamagdolnapuszta</div>
<div class="option" data='{"value":"Mariapuszta","state":"Komarom"}'>Mariapuszta</div>
<div class="option" data='{"value":"Markustag","state":"Komarom"}'>Markustag</div>
<div class="option" data='{"value":"Martonkut","state":"Komarom"}'>Martonkut</div>
<div class="option" data='{"value":"Massiktanya","state":"Komarom"}'>Massiktanya</div>
<div class="option" data='{"value":"Mexikoi Dulo","state":"Komarom"}'>Mexikoi Dulo</div>
<div class="option" data='{"value":"Mezoto","state":"Komarom"}'>Mezoto</div>
<div class="option" data='{"value":"Mihalyhazapuszta","state":"Komarom"}'>Mihalyhazapuszta</div>
<div class="option" data='{"value":"Mihalyi","state":"Komarom"}'>Mihalyi</div>
<div class="option" data='{"value":"Mihalyialsopuszta","state":"Komarom"}'>Mihalyialsopuszta</div>
<div class="option" data='{"value":"Mihalyifelsopuszta","state":"Komarom"}'>Mihalyifelsopuszta</div>
<div class="option" data='{"value":"Miklospuszta","state":"Komarom"}'>Miklospuszta</div>
<div class="option" data='{"value":"Mikostanya","state":"Komarom"}'>Mikostanya</div>
<div class="option" data='{"value":"Milkovicstag","state":"Komarom"}'>Milkovicstag</div>
<div class="option" data='{"value":"Mindszentpuszta","state":"Komarom"}'>Mindszentpuszta</div>
<div class="option" data='{"value":"Mocsa","state":"Komarom"}'>Mocsa</div>
<div class="option" data='{"value":"Mocsai Tanyak","state":"Komarom"}'>Mocsai Tanyak</div>
<div class="option" data='{"value":"Mogyorosbanya","state":"Komarom"}'>Mogyorosbanya</div>
<div class="option" data='{"value":"Molaj Telep","state":"Komarom"}'>Molaj Telep</div>
<div class="option" data='{"value":"Moriczpuszta","state":"Komarom"}'>Moriczpuszta</div>
<div class="option" data='{"value":"Morvaimalom","state":"Komarom"}'>Morvaimalom</div>
<div class="option" data='{"value":"Nadadpuszta","state":"Komarom"}'>Nadadpuszta</div>
<div class="option" data='{"value":"Nadasdpuszta","state":"Komarom"}'>Nadasdpuszta</div>
<div class="option" data='{"value":"Nagyberpuszta","state":"Komarom"}'>Nagyberpuszta</div>
<div class="option" data='{"value":"Nagydinnye","state":"Komarom"}'>Nagydinnye</div>
<div class="option" data='{"value":"Nagyherkaly","state":"Komarom"}'>Nagyherkaly</div>
<div class="option" data='{"value":"Nagyigmand","state":"Komarom"}'>Nagyigmand</div>
<div class="option" data='{"value":"Nagyparnakpuszta","state":"Komarom"}'>Nagyparnakpuszta</div>
<div class="option" data='{"value":"Nagypatarpuszta","state":"Komarom"}'>Nagypatarpuszta</div>
<div class="option" data='{"value":"Nagysap","state":"Komarom"}'>Nagysap</div>
<div class="option" data='{"value":"Nagytagyospuszta","state":"Komarom"}'>Nagytagyospuszta</div>
<div class="option" data='{"value":"Nagytarcs","state":"Komarom"}'>Nagytarcs</div>
<div class="option" data='{"value":"Nagytarcspuszta","state":"Komarom"}'>Nagytarcspuszta</div>
<div class="option" data='{"value":"Naplokert","state":"Komarom"}'>Naplokert</div>
<div class="option" data='{"value":"Naszaly","state":"Komarom"}'>Naszaly</div>
<div class="option" data='{"value":"Neszmely","state":"Komarom"}'>Neszmely</div>
<div class="option" data='{"value":"Nyergesujfalu","state":"Komarom"}'>Nyergesujfalu</div>
<div class="option" data='{"value":"Nyeskenye","state":"Komarom"}'>Nyeskenye</div>
<div class="option" data='{"value":"Nyeszkenyepuszta","state":"Komarom"}'>Nyeszkenyepuszta</div>
<div class="option" data='{"value":"Nyika","state":"Komarom"}'>Nyika</div>
<div class="option" data='{"value":"Olbopuszta","state":"Komarom"}'>Olbopuszta</div>
<div class="option" data='{"value":"Oncsatelep","state":"Komarom"}'>Oncsatelep</div>
<div class="option" data='{"value":"Oreghegy","state":"Komarom"}'>Oreghegy</div>
<div class="option" data='{"value":"Oreghegyiszollo","state":"Komarom"}'>Oreghegyiszollo</div>
<div class="option" data='{"value":"Oregkuria","state":"Komarom"}'>Oregkuria</div>
<div class="option" data='{"value":"Oregszollo","state":"Komarom"}'>Oregszollo</div>
<div class="option" data='{"value":"Orisap","state":"Komarom"}'>Orisap</div>
<div class="option" data='{"value":"Oroszlany","state":"Komarom"}'>Oroszlany</div>
<div class="option" data='{"value":"Otarcspuszta","state":"Komarom"}'>Otarcspuszta</div>
<div class="option" data='{"value":"Palfitanya","state":"Komarom"}'>Palfitanya</div>
<div class="option" data='{"value":"Panhida","state":"Komarom"}'>Panhida</div>
<div class="option" data='{"value":"Paulamajor","state":"Komarom"}'>Paulamajor</div>
<div class="option" data='{"value":"Paulinamajor","state":"Komarom"}'>Paulinamajor</div>
<div class="option" data='{"value":"Paulinmajor","state":"Komarom"}'>Paulinmajor</div>
<div class="option" data='{"value":"Pelifoldszentkereszt","state":"Komarom"}'>Pelifoldszentkereszt</div>
<div class="option" data='{"value":"Pentektanya","state":"Komarom"}'>Pentektanya</div>
<div class="option" data='{"value":"Penzasas","state":"Komarom"}'>Penzasas</div>
<div class="option" data='{"value":"Penzasasujtelep","state":"Komarom"}'>Penzasasujtelep</div>
<div class="option" data='{"value":"Perjespuszta","state":"Komarom"}'>Perjespuszta</div>
<div class="option" data='{"value":"Pervatpuszta","state":"Komarom"}'>Pervatpuszta</div>
<div class="option" data='{"value":"Piliscsev","state":"Komarom"}'>Piliscsev</div>
<div class="option" data='{"value":"Pilismarot","state":"Komarom"}'>Pilismarot</div>
<div class="option" data='{"value":"Pilisszentlelek","state":"Komarom"}'>Pilisszentlelek</div>
<div class="option" data='{"value":"Piszke","state":"Komarom"}'>Piszke</div>
<div class="option" data='{"value":"Porjespuszta","state":"Komarom"}'>Porjespuszta</div>
<div class="option" data='{"value":"Pulaitag","state":"Komarom"}'>Pulaitag</div>
<div class="option" data='{"value":"Pulapuszta","state":"Komarom"}'>Pulapuszta</div>
<div class="option" data='{"value":"Pusztaalmas","state":"Komarom"}'>Pusztaalmas</div>
<div class="option" data='{"value":"Pusztamarot","state":"Komarom"}'>Pusztamarot</div>
<div class="option" data='{"value":"Rakoczimajor","state":"Komarom"}'>Rakoczimajor</div>
<div class="option" data='{"value":"Rakosmajor","state":"Komarom"}'>Rakosmajor</div>
<div class="option" data='{"value":"Rakosmalom","state":"Komarom"}'>Rakosmalom</div>
<div class="option" data='{"value":"Rede","state":"Komarom"}'>Rede</div>
<div class="option" data='{"value":"Remeteseg","state":"Komarom"}'>Remeteseg</div>
<div class="option" data='{"value":"Retimalom","state":"Komarom"}'>Retimalom</div>
<div class="option" data='{"value":"Ronaitanya","state":"Komarom"}'>Ronaitanya</div>
<div class="option" data='{"value":"Rostaret","state":"Komarom"}'>Rostaret</div>
<div class="option" data='{"value":"Roviddulo","state":"Komarom"}'>Roviddulo</div>
<div class="option" data='{"value":"Salihaz","state":"Komarom"}'>Salihaz</div>
<div class="option" data='{"value":"Salihaza","state":"Komarom"}'>Salihaza</div>
<div class="option" data='{"value":"Salipuszta","state":"Komarom"}'>Salipuszta</div>
<div class="option" data='{"value":"Sandormajor","state":"Komarom"}'>Sandormajor</div>
<div class="option" data='{"value":"Saras","state":"Komarom"}'>Saras</div>
<div class="option" data='{"value":"Sarisap","state":"Komarom"}'>Sarisap</div>
<div class="option" data='{"value":"Satorkopuszta","state":"Komarom"}'>Satorkopuszta</div>
<div class="option" data='{"value":"Satorkotanya","state":"Komarom"}'>Satorkotanya</div>
<div class="option" data='{"value":"Satorret","state":"Komarom"}'>Satorret</div>
<div class="option" data='{"value":"Schmidtvilla","state":"Komarom"}'>Schmidtvilla</div>
<div class="option" data='{"value":"Segedakna","state":"Komarom"}'>Segedakna</div>
<div class="option" data='{"value":"Selyemgyartelep","state":"Komarom"}'>Selyemgyartelep</div>
<div class="option" data='{"value":"Sikvolgypuszta","state":"Komarom"}'>Sikvolgypuszta</div>
<div class="option" data='{"value":"Somlyodulo","state":"Komarom"}'>Somlyodulo</div>
<div class="option" data='{"value":"Somodorpuszta","state":"Komarom"}'>Somodorpuszta</div>
<div class="option" data='{"value":"Somogyitanya","state":"Komarom"}'>Somogyitanya</div>
<div class="option" data='{"value":"Sur","state":"Komarom"}'>Sur</div>
<div class="option" data='{"value":"Surcsatar","state":"Komarom"}'>Surcsatar</div>
<div class="option" data='{"value":"Sutto","state":"Komarom"}'>Sutto</div>
<div class="option" data='{"value":"Szabadsagter","state":"Komarom"}'>Szabadsagter</div>
<div class="option" data='{"value":"Szagodotanya","state":"Komarom"}'>Szagodotanya</div>
<div class="option" data='{"value":"Szajkotanya","state":"Komarom"}'>Szajkotanya</div>
<div class="option" data='{"value":"Szak","state":"Komarom"}'>Szak</div>
<div class="option" data='{"value":"Szakszend","state":"Komarom"}'>Szakszend</div>
<div class="option" data='{"value":"Szamarhegy","state":"Komarom"}'>Szamarhegy</div>
<div class="option" data='{"value":"Szarkas","state":"Komarom"}'>Szarkas</div>
<div class="option" data='{"value":"Szarkaspuszta","state":"Komarom"}'>Szarkaspuszta</div>
<div class="option" data='{"value":"Szarkatanya","state":"Komarom"}'>Szarkatanya</div>
<div class="option" data='{"value":"Szarvashegy","state":"Komarom"}'>Szarvashegy</div>
<div class="option" data='{"value":"Szend","state":"Komarom"}'>Szend</div>
<div class="option" data='{"value":"Szentgyorgypuszta","state":"Komarom"}'>Szentgyorgypuszta</div>
<div class="option" data='{"value":"Szentimretelep","state":"Komarom"}'>Szentimretelep</div>
<div class="option" data='{"value":"Szentjanoskuti Dulo","state":"Komarom"}'>Szentjanoskuti Dulo</div>
<div class="option" data='{"value":"Szentjozsefpuszta","state":"Komarom"}'>Szentjozsefpuszta</div>
<div class="option" data='{"value":"Szeszgyar","state":"Komarom"}'>Szeszgyar</div>
<div class="option" data='{"value":"Szeszgyarmajor","state":"Komarom"}'>Szeszgyarmajor</div>
<div class="option" data='{"value":"Sziklaitanya","state":"Komarom"}'>Sziklaitanya</div>
<div class="option" data='{"value":"Szkolkadulo","state":"Komarom"}'>Szkolkadulo</div>
<div class="option" data='{"value":"Szokepuszta","state":"Komarom"}'>Szokepuszta</div>
<div class="option" data='{"value":"Szolgagyor","state":"Komarom"}'>Szolgagyor</div>
<div class="option" data='{"value":"Szolgagyorpuszta","state":"Komarom"}'>Szolgagyorpuszta</div>
<div class="option" data='{"value":"Szollohegyek","state":"Komarom"}'>Szollohegyek</div>
<div class="option" data='{"value":"Szollotelek","state":"Komarom"}'>Szollotelek</div>
<div class="option" data='{"value":"Szolohegy","state":"Komarom"}'>Szolohegy</div>
<div class="option" data='{"value":"Szomod","state":"Komarom"}'>Szomod</div>
<div class="option" data='{"value":"Szomor","state":"Komarom"}'>Szomor</div>
<div class="option" data='{"value":"Szony","state":"Komarom"}'>Szony</div>
<div class="option" data='{"value":"Szonyi Tanyak","state":"Komarom"}'>Szonyi Tanyak</div>
<div class="option" data='{"value":"Tagi Dulo","state":"Komarom"}'>Tagi Dulo</div>
<div class="option" data='{"value":"Takacstanya","state":"Komarom"}'>Takacstanya</div>
<div class="option" data='{"value":"Tardos","state":"Komarom"}'>Tardos</div>
<div class="option" data='{"value":"Tardosbanya","state":"Komarom"}'>Tardosbanya</div>
<div class="option" data='{"value":"Tarjan","state":"Komarom"}'>Tarjan</div>
<div class="option" data='{"value":"Tarjani Tanya","state":"Komarom"}'>Tarjani Tanya</div>
<div class="option" data='{"value":"Tarkany","state":"Komarom"}'>Tarkany</div>
<div class="option" data='{"value":"Tat","state":"Komarom"}'>Tat</div>
<div class="option" data='{"value":"Tata","state":"Komarom"}'>Tata</div>
<div class="option" data='{"value":"Tatabanya","state":"Komarom"}'>Tatabanya</div>
<div class="option" data='{"value":"Tatatovaros","state":"Komarom"}'>Tatatovaros</div>
<div class="option" data='{"value":"Teglahazi Dulo","state":"Komarom"}'>Teglahazi Dulo</div>
<div class="option" data='{"value":"Tejhegy","state":"Komarom"}'>Tejhegy</div>
<div class="option" data='{"value":"Temesvaridulo","state":"Komarom"}'>Temesvaridulo</div>
<div class="option" data='{"value":"Thalypuszta","state":"Komarom"}'>Thalypuszta</div>
<div class="option" data='{"value":"Tisztviselotelep","state":"Komarom"}'>Tisztviselotelep</div>
<div class="option" data='{"value":"Tizediktabla","state":"Komarom"}'>Tizediktabla</div>
<div class="option" data='{"value":"Tokod","state":"Komarom"}'>Tokod</div>
<div class="option" data='{"value":"Tokodaltaro","state":"Komarom"}'>Tokodaltaro</div>
<div class="option" data='{"value":"Tokodi Uveggyar","state":"Komarom"}'>Tokodi Uveggyar</div>
<div class="option" data='{"value":"Toltesalja","state":"Komarom"}'>Toltesalja</div>
<div class="option" data='{"value":"Tomedekakna","state":"Komarom"}'>Tomedekakna</div>
<div class="option" data='{"value":"Tomordpuszta","state":"Komarom"}'>Tomordpuszta</div>
<div class="option" data='{"value":"Totrede","state":"Komarom"}'>Totrede</div>
<div class="option" data='{"value":"Turohegy","state":"Komarom"}'>Turohegy</div>
<div class="option" data='{"value":"Ujhegy","state":"Komarom"}'>Ujhegy</div>
<div class="option" data='{"value":"Ujmajor","state":"Komarom"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujpuszta","state":"Komarom"}'>Ujpuszta</div>
<div class="option" data='{"value":"Ujsor","state":"Komarom"}'>Ujsor</div>
<div class="option" data='{"value":"Ujszallaspuszta","state":"Komarom"}'>Ujszallaspuszta</div>
<div class="option" data='{"value":"Ujszollo","state":"Komarom"}'>Ujszollo</div>
<div class="option" data='{"value":"Ujszolo","state":"Komarom"}'>Ujszolo</div>
<div class="option" data='{"value":"Ujszony","state":"Komarom"}'>Ujszony</div>
<div class="option" data='{"value":"Ujtelep","state":"Komarom"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujvaritanya","state":"Komarom"}'>Ujvaritanya</div>
<div class="option" data='{"value":"Ujvaros","state":"Komarom"}'>Ujvaros</div>
<div class="option" data='{"value":"Uny","state":"Komarom"}'>Uny</div>
<div class="option" data='{"value":"Uradalmi Szollotelep","state":"Komarom"}'>Uradalmi Szollotelep</div>
<div class="option" data='{"value":"Urasagi Dulo","state":"Komarom"}'>Urasagi Dulo</div>
<div class="option" data='{"value":"Urgemajor","state":"Komarom"}'>Urgemajor</div>
<div class="option" data='{"value":"Vadaspuszta","state":"Komarom"}'>Vadaspuszta</div>
<div class="option" data='{"value":"Vargatanya","state":"Komarom"}'>Vargatanya</div>
<div class="option" data='{"value":"Vargesztes","state":"Komarom"}'>Vargesztes</div>
<div class="option" data='{"value":"Varhegy","state":"Komarom"}'>Varhegy</div>
<div class="option" data='{"value":"Vasarter","state":"Komarom"}'>Vasarter</div>
<div class="option" data='{"value":"Vaskapu","state":"Komarom"}'>Vaskapu</div>
<div class="option" data='{"value":"Vaskapupuszta","state":"Komarom"}'>Vaskapupuszta</div>
<div class="option" data='{"value":"Vaspuszta","state":"Komarom"}'>Vaspuszta</div>
<div class="option" data='{"value":"Verteskethely","state":"Komarom"}'>Verteskethely</div>
<div class="option" data='{"value":"Vertessomlo","state":"Komarom"}'>Vertessomlo</div>
<div class="option" data='{"value":"Vertesszollos","state":"Komarom"}'>Vertesszollos</div>
<div class="option" data='{"value":"Vertesszolos","state":"Komarom"}'>Vertesszolos</div>
<div class="option" data='{"value":"Vertestolna","state":"Komarom"}'>Vertestolna</div>
<div class="option" data='{"value":"Vilagoshegy","state":"Komarom"}'>Vilagoshegy</div>
<div class="option" data='{"value":"Viraghtanya","state":"Komarom"}'>Viraghtanya</div>
<div class="option" data='{"value":"Voroshid","state":"Komarom"}'>Voroshid</div>
<div class="option" data='{"value":"Wimmertelep","state":"Komarom"}'>Wimmertelep</div>
<div class="option" data='{"value":"Zamorymajor","state":"Komarom"}'>Zamorymajor</div>
<div class="option" data='{"value":"Zoldmalom","state":"Komarom"}'>Zoldmalom</div>
<div class="option" data='{"value":"Zsellertag","state":"Komarom"}'>Zsellertag</div>
<div class="option" data='{"value":"Zsido Puszta","state":"Komarom"}'>Zsido Puszta</div>
<div class="option" data='{"value":"Zsidod","state":"Komarom"}'>Zsidod</div>
<div class="option" id="option_end" data='{"value":"Zsidodipatak","state":"Komarom"}'>Zsidodipatak</div>

