<div class="option" data='{"value":"Abda","state":"Gyor-Moson-Sopron"}'>Abda</div>
<div class="option" data='{"value":"Acsalag","state":"Gyor-Moson-Sopron"}'>Acsalag</div>
<div class="option" data='{"value":"Acstanya","state":"Gyor-Moson-Sopron"}'>Acstanya</div>
<div class="option" data='{"value":"Agfalva","state":"Gyor-Moson-Sopron"}'>Agfalva</div>
<div class="option" data='{"value":"Aghely","state":"Gyor-Moson-Sopron"}'>Aghely</div>
<div class="option" data='{"value":"Agyagosszergeny","state":"Gyor-Moson-Sopron"}'>Agyagosszergeny</div>
<div class="option" data='{"value":"Albertkazmerpuszta","state":"Gyor-Moson-Sopron"}'>Albertkazmerpuszta</div>
<div class="option" data='{"value":"Alfaritanya","state":"Gyor-Moson-Sopron"}'>Alfaritanya</div>
<div class="option" data='{"value":"Alsomajor","state":"Gyor-Moson-Sopron"}'>Alsomajor</div>
<div class="option" data='{"value":"Alsoszapudpuszta","state":"Gyor-Moson-Sopron"}'>Alsoszapudpuszta</div>
<div class="option" data='{"value":"Alsoujtagmajor","state":"Gyor-Moson-Sopron"}'>Alsoujtagmajor</div>
<div class="option" data='{"value":"Alszopor","state":"Gyor-Moson-Sopron"}'>Alszopor</div>
<div class="option" data='{"value":"Altenburg","state":"Gyor-Moson-Sopron"}'>Altenburg</div>
<div class="option" data='{"value":"Amand","state":"Gyor-Moson-Sopron"}'>Amand</div>
<div class="option" data='{"value":"Amerikaipuszta","state":"Gyor-Moson-Sopron"}'>Amerikaipuszta</div>
<div class="option" data='{"value":"Amerikapuszta","state":"Gyor-Moson-Sopron"}'>Amerikapuszta</div>
<div class="option" data='{"value":"Anghely","state":"Gyor-Moson-Sopron"}'>Anghely</div>
<div class="option" data='{"value":"Angyaltanya","state":"Gyor-Moson-Sopron"}'>Angyaltanya</div>
<div class="option" data='{"value":"Antalmajor","state":"Gyor-Moson-Sopron"}'>Antalmajor</div>
<div class="option" data='{"value":"Antoniamajor","state":"Gyor-Moson-Sopron"}'>Antoniamajor</div>
<div class="option" data='{"value":"Arak","state":"Gyor-Moson-Sopron"}'>Arak</div>
<div class="option" data='{"value":"Arankamajor","state":"Gyor-Moson-Sopron"}'>Arankamajor</div>
<div class="option" data='{"value":"Aranyosdomb","state":"Gyor-Moson-Sopron"}'>Aranyosdomb</div>
<div class="option" data='{"value":"Aranyosimajor","state":"Gyor-Moson-Sopron"}'>Aranyosimajor</div>
<div class="option" data='{"value":"Aranyosmajor","state":"Gyor-Moson-Sopron"}'>Aranyosmajor</div>
<div class="option" data='{"value":"Aranyossziget","state":"Gyor-Moson-Sopron"}'>Aranyossziget</div>
<div class="option" data='{"value":"Arpas","state":"Gyor-Moson-Sopron"}'>Arpas</div>
<div class="option" data='{"value":"Asvanyraro","state":"Gyor-Moson-Sopron"}'>Asvanyraro</div>
<div class="option" data='{"value":"Attamajor","state":"Gyor-Moson-Sopron"}'>Attamajor</div>
<div class="option" data='{"value":"Attipuszta","state":"Gyor-Moson-Sopron"}'>Attipuszta</div>
<div class="option" data='{"value":"Babostag","state":"Gyor-Moson-Sopron"}'>Babostag</div>
<div class="option" data='{"value":"Babot","state":"Gyor-Moson-Sopron"}'>Babot</div>
<div class="option" data='{"value":"Bacsa","state":"Gyor-Moson-Sopron"}'>Bacsa</div>
<div class="option" data='{"value":"Baditzmajor","state":"Gyor-Moson-Sopron"}'>Baditzmajor</div>
<div class="option" data='{"value":"Baditztag","state":"Gyor-Moson-Sopron"}'>Baditztag</div>
<div class="option" data='{"value":"Bagyog","state":"Gyor-Moson-Sopron"}'>Bagyog</div>
<div class="option" data='{"value":"Bagyogszovat","state":"Gyor-Moson-Sopron"}'>Bagyogszovat</div>
<div class="option" data='{"value":"Bakonygyirot","state":"Gyor-Moson-Sopron"}'>Bakonygyirot</div>
<div class="option" data='{"value":"Bakonypeterd","state":"Gyor-Moson-Sopron"}'>Bakonypeterd</div>
<div class="option" data='{"value":"Bakonyszentlaszlo","state":"Gyor-Moson-Sopron"}'>Bakonyszentlaszlo</div>
<div class="option" data='{"value":"Balf","state":"Gyor-Moson-Sopron"}'>Balf</div>
<div class="option" data='{"value":"Ballatag","state":"Gyor-Moson-Sopron"}'>Ballatag</div>
<div class="option" data='{"value":"Baloghpuszta","state":"Gyor-Moson-Sopron"}'>Baloghpuszta</div>
<div class="option" data='{"value":"Balogpuszta","state":"Gyor-Moson-Sopron"}'>Balogpuszta</div>
<div class="option" data='{"value":"Baratfold","state":"Gyor-Moson-Sopron"}'>Baratfold</div>
<div class="option" data='{"value":"Barbacs","state":"Gyor-Moson-Sopron"}'>Barbacs</div>
<div class="option" data='{"value":"Barczafelsomajor","state":"Gyor-Moson-Sopron"}'>Barczafelsomajor</div>
<div class="option" data='{"value":"Bartanya","state":"Gyor-Moson-Sopron"}'>Bartanya</div>
<div class="option" data='{"value":"Bartatanya","state":"Gyor-Moson-Sopron"}'>Bartatanya</div>
<div class="option" data='{"value":"Bazitag","state":"Gyor-Moson-Sopron"}'>Bazitag</div>
<div class="option" data='{"value":"Bejczitag","state":"Gyor-Moson-Sopron"}'>Bejczitag</div>
<div class="option" data='{"value":"Bekkpuszta","state":"Gyor-Moson-Sopron"}'>Bekkpuszta</div>
<div class="option" data='{"value":"Beled","state":"Gyor-Moson-Sopron"}'>Beled</div>
<div class="option" data='{"value":"Belso Malom","state":"Gyor-Moson-Sopron"}'>Belso Malom</div>
<div class="option" data='{"value":"Belsolajtamajor","state":"Gyor-Moson-Sopron"}'>Belsolajtamajor</div>
<div class="option" data='{"value":"Belsotag","state":"Gyor-Moson-Sopron"}'>Belsotag</div>
<div class="option" data='{"value":"Berekmajor","state":"Gyor-Moson-Sopron"}'>Berekmajor</div>
<div class="option" data='{"value":"Betlehempuszta","state":"Gyor-Moson-Sopron"}'>Betlehempuszta</div>
<div class="option" data='{"value":"Bezenye","state":"Gyor-Moson-Sopron"}'>Bezenye</div>
<div class="option" data='{"value":"Bezi","state":"Gyor-Moson-Sopron"}'>Bezi</div>
<div class="option" data='{"value":"Birkashaz","state":"Gyor-Moson-Sopron"}'>Birkashaz</div>
<div class="option" data='{"value":"Bodacstelek","state":"Gyor-Moson-Sopron"}'>Bodacstelek</div>
<div class="option" data='{"value":"Bodonhely","state":"Gyor-Moson-Sopron"}'>Bodonhely</div>
<div class="option" data='{"value":"Bodortanya","state":"Gyor-Moson-Sopron"}'>Bodortanya</div>
<div class="option" data='{"value":"Bogyoszlo","state":"Gyor-Moson-Sopron"}'>Bogyoszlo</div>
<div class="option" data='{"value":"Bokrospuszta","state":"Gyor-Moson-Sopron"}'>Bokrospuszta</div>
<div class="option" data='{"value":"Bolganymajor","state":"Gyor-Moson-Sopron"}'>Bolganymajor</div>
<div class="option" data='{"value":"Bolganypuszta","state":"Gyor-Moson-Sopron"}'>Bolganypuszta</div>
<div class="option" data='{"value":"Bony","state":"Gyor-Moson-Sopron"}'>Bony</div>
<div class="option" data='{"value":"Bonyretalap","state":"Gyor-Moson-Sopron"}'>Bonyretalap</div>
<div class="option" data='{"value":"Borbala","state":"Gyor-Moson-Sopron"}'>Borbala</div>
<div class="option" data='{"value":"Borbalatelep","state":"Gyor-Moson-Sopron"}'>Borbalatelep</div>
<div class="option" data='{"value":"Borbapuszta","state":"Gyor-Moson-Sopron"}'>Borbapuszta</div>
<div class="option" data='{"value":"Borcs","state":"Gyor-Moson-Sopron"}'>Borcs</div>
<div class="option" data='{"value":"Borjuduloi Tanyak","state":"Gyor-Moson-Sopron"}'>Borjuduloi Tanyak</div>
<div class="option" data='{"value":"Bormasz","state":"Gyor-Moson-Sopron"}'>Bormasz</div>
<div class="option" data='{"value":"Bormaszpuszta","state":"Gyor-Moson-Sopron"}'>Bormaszpuszta</div>
<div class="option" data='{"value":"Borsoditanya","state":"Gyor-Moson-Sopron"}'>Borsoditanya</div>
<div class="option" data='{"value":"Borsodymajor","state":"Gyor-Moson-Sopron"}'>Borsodymajor</div>
<div class="option" data='{"value":"Bosarkany","state":"Gyor-Moson-Sopron"}'>Bosarkany</div>
<div class="option" data='{"value":"Bothmerpuszta","state":"Gyor-Moson-Sopron"}'>Bothmerpuszta</div>
<div class="option" data='{"value":"Brennbergbanya","state":"Gyor-Moson-Sopron"}'>Brennbergbanya</div>
<div class="option" data='{"value":"Cakohaza","state":"Gyor-Moson-Sopron"}'>Cakohaza</div>
<div class="option" data='{"value":"Capuvar","state":"Gyor-Moson-Sopron"}'>Capuvar</div>
<div class="option" data='{"value":"Cikolasziget","state":"Gyor-Moson-Sopron"}'>Cikolasziget</div>
<div class="option" data='{"value":"Cirak","state":"Gyor-Moson-Sopron"}'>Cirak</div>
<div class="option" data='{"value":"Csafordimalom","state":"Gyor-Moson-Sopron"}'>Csafordimalom</div>
<div class="option" data='{"value":"Csafordjanosfa","state":"Gyor-Moson-Sopron"}'>Csafordjanosfa</div>
<div class="option" data='{"value":"Csaknema","state":"Gyor-Moson-Sopron"}'>Csaknema</div>
<div class="option" data='{"value":"Csangota","state":"Gyor-Moson-Sopron"}'>Csangota</div>
<div class="option" data='{"value":"Csangotapuszta","state":"Gyor-Moson-Sopron"}'>Csangotapuszta</div>
<div class="option" data='{"value":"Csapod","state":"Gyor-Moson-Sopron"}'>Csapod</div>
<div class="option" data='{"value":"Csapotag","state":"Gyor-Moson-Sopron"}'>Csapotag</div>
<div class="option" data='{"value":"Csaszarret","state":"Gyor-Moson-Sopron"}'>Csaszarret</div>
<div class="option" data='{"value":"Csaszarreti Erdo","state":"Gyor-Moson-Sopron"}'>Csaszarreti Erdo</div>
<div class="option" data='{"value":"Csatarimajor","state":"Gyor-Moson-Sopron"}'>Csatarimajor</div>
<div class="option" data='{"value":"Csepete","state":"Gyor-Moson-Sopron"}'>Csepete</div>
<div class="option" data='{"value":"Csepetei Tanya","state":"Gyor-Moson-Sopron"}'>Csepetei Tanya</div>
<div class="option" data='{"value":"Cser","state":"Gyor-Moson-Sopron"}'>Cser</div>
<div class="option" data='{"value":"Cseralja","state":"Gyor-Moson-Sopron"}'>Cseralja</div>
<div class="option" data='{"value":"Cseraljapuszta","state":"Gyor-Moson-Sopron"}'>Cseraljapuszta</div>
<div class="option" data='{"value":"Cserimajor","state":"Gyor-Moson-Sopron"}'>Cserimajor</div>
<div class="option" data='{"value":"Csermajor","state":"Gyor-Moson-Sopron"}'>Csermajor</div>
<div class="option" data='{"value":"Csibatelep","state":"Gyor-Moson-Sopron"}'>Csibatelep</div>
<div class="option" data='{"value":"Csigipuszta","state":"Gyor-Moson-Sopron"}'>Csigipuszta</div>
<div class="option" data='{"value":"Csigitag","state":"Gyor-Moson-Sopron"}'>Csigitag</div>
<div class="option" data='{"value":"Csikolegelo","state":"Gyor-Moson-Sopron"}'>Csikolegelo</div>
<div class="option" data='{"value":"Csikoseger","state":"Gyor-Moson-Sopron"}'>Csikoseger</div>
<div class="option" data='{"value":"Csikvand","state":"Gyor-Moson-Sopron"}'>Csikvand</div>
<div class="option" data='{"value":"Csollanyospuszta","state":"Gyor-Moson-Sopron"}'>Csollanyospuszta</div>
<div class="option" data='{"value":"Csolosztosziget","state":"Gyor-Moson-Sopron"}'>Csolosztosziget</div>
<div class="option" data='{"value":"Csomoridulo","state":"Gyor-Moson-Sopron"}'>Csomoridulo</div>
<div class="option" data='{"value":"Csorgetoi Teglagyar","state":"Gyor-Moson-Sopron"}'>Csorgetoi Teglagyar</div>
<div class="option" data='{"value":"Csorna","state":"Gyor-Moson-Sopron"}'>Csorna</div>
<div class="option" data='{"value":"Darnozseli","state":"Gyor-Moson-Sopron"}'>Darnozseli</div>
<div class="option" data='{"value":"Deakfoldpuszta","state":"Gyor-Moson-Sopron"}'>Deakfoldpuszta</div>
<div class="option" data='{"value":"Denesfa","state":"Gyor-Moson-Sopron"}'>Denesfa</div>
<div class="option" data='{"value":"Denesmajor","state":"Gyor-Moson-Sopron"}'>Denesmajor</div>
<div class="option" data='{"value":"Denestag","state":"Gyor-Moson-Sopron"}'>Denestag</div>
<div class="option" data='{"value":"Diostelep","state":"Gyor-Moson-Sopron"}'>Diostelep</div>
<div class="option" data='{"value":"Doborgazsziget","state":"Gyor-Moson-Sopron"}'>Doborgazsziget</div>
<div class="option" data='{"value":"Dombifold","state":"Gyor-Moson-Sopron"}'>Dombifold</div>
<div class="option" data='{"value":"Dor","state":"Gyor-Moson-Sopron"}'>Dor</div>
<div class="option" data='{"value":"Dorog","state":"Gyor-Moson-Sopron"}'>Dorog</div>
<div class="option" data='{"value":"Dorogpuszta","state":"Gyor-Moson-Sopron"}'>Dorogpuszta</div>
<div class="option" data='{"value":"Dozsatag","state":"Gyor-Moson-Sopron"}'>Dozsatag</div>
<div class="option" data='{"value":"Dunakiliti","state":"Gyor-Moson-Sopron"}'>Dunakiliti</div>
<div class="option" data='{"value":"Dunaremete","state":"Gyor-Moson-Sopron"}'>Dunaremete</div>
<div class="option" data='{"value":"Dunaszeg","state":"Gyor-Moson-Sopron"}'>Dunaszeg</div>
<div class="option" data='{"value":"Dunaszentpal","state":"Gyor-Moson-Sopron"}'>Dunaszentpal</div>
<div class="option" data='{"value":"Dunasziget","state":"Gyor-Moson-Sopron"}'>Dunasziget</div>
<div class="option" data='{"value":"Ebergoc","state":"Gyor-Moson-Sopron"}'>Ebergoc</div>
<div class="option" data='{"value":"Ecs","state":"Gyor-Moson-Sopron"}'>Ecs</div>
<div class="option" data='{"value":"Edve","state":"Gyor-Moson-Sopron"}'>Edve</div>
<div class="option" data='{"value":"Egyed","state":"Gyor-Moson-Sopron"}'>Egyed</div>
<div class="option" data='{"value":"Egyhazasfalu","state":"Gyor-Moson-Sopron"}'>Egyhazasfalu</div>
<div class="option" data='{"value":"Elekpuszta","state":"Gyor-Moson-Sopron"}'>Elekpuszta</div>
<div class="option" data='{"value":"Endredujmajor","state":"Gyor-Moson-Sopron"}'>Endredujmajor</div>
<div class="option" data='{"value":"Enese","state":"Gyor-Moson-Sopron"}'>Enese</div>
<div class="option" data='{"value":"Erdotelep","state":"Gyor-Moson-Sopron"}'>Erdotelep</div>
<div class="option" data='{"value":"Erzsebetmajor","state":"Gyor-Moson-Sopron"}'>Erzsebetmajor</div>
<div class="option" data='{"value":"Erzsebetpuszta","state":"Gyor-Moson-Sopron"}'>Erzsebetpuszta</div>
<div class="option" data='{"value":"Eszterhaza","state":"Gyor-Moson-Sopron"}'>Eszterhaza</div>
<div class="option" data='{"value":"Eszterhazypuszta","state":"Gyor-Moson-Sopron"}'>Eszterhazypuszta</div>
<div class="option" data='{"value":"Faluhelypuszta","state":"Gyor-Moson-Sopron"}'>Faluhelypuszta</div>
<div class="option" data='{"value":"Farad","state":"Gyor-Moson-Sopron"}'>Farad</div>
<div class="option" data='{"value":"Farkastanya","state":"Gyor-Moson-Sopron"}'>Farkastanya</div>
<div class="option" data='{"value":"Fatelep","state":"Gyor-Moson-Sopron"}'>Fatelep</div>
<div class="option" data='{"value":"Feherto","state":"Gyor-Moson-Sopron"}'>Feherto</div>
<div class="option" data='{"value":"Feketebokormajor","state":"Gyor-Moson-Sopron"}'>Feketebokormajor</div>
<div class="option" data='{"value":"Feketeerdo","state":"Gyor-Moson-Sopron"}'>Feketeerdo</div>
<div class="option" data='{"value":"Feketemajor","state":"Gyor-Moson-Sopron"}'>Feketemajor</div>
<div class="option" data='{"value":"Felpec","state":"Gyor-Moson-Sopron"}'>Felpec</div>
<div class="option" data='{"value":"Felsomalom","state":"Gyor-Moson-Sopron"}'>Felsomalom</div>
<div class="option" data='{"value":"Felsoszapud","state":"Gyor-Moson-Sopron"}'>Felsoszapud</div>
<div class="option" data='{"value":"Felsoszapudpuszta","state":"Gyor-Moson-Sopron"}'>Felsoszapudpuszta</div>
<div class="option" data='{"value":"Felsotag","state":"Gyor-Moson-Sopron"}'>Felsotag</div>
<div class="option" data='{"value":"Felszopor","state":"Gyor-Moson-Sopron"}'>Felszopor</div>
<div class="option" data='{"value":"Fenyofo","state":"Gyor-Moson-Sopron"}'>Fenyofo</div>
<div class="option" data='{"value":"Fenyomajor","state":"Gyor-Moson-Sopron"}'>Fenyomajor</div>
<div class="option" data='{"value":"Fenyvespuszta","state":"Gyor-Moson-Sopron"}'>Fenyvespuszta</div>
<div class="option" data='{"value":"Ferenchaza","state":"Gyor-Moson-Sopron"}'>Ferenchaza</div>
<div class="option" data='{"value":"Ferenchazapuszta","state":"Gyor-Moson-Sopron"}'>Ferenchazapuszta</div>
<div class="option" data='{"value":"Fertoboz","state":"Gyor-Moson-Sopron"}'>Fertoboz</div>
<div class="option" data='{"value":"Fertod","state":"Gyor-Moson-Sopron"}'>Fertod</div>
<div class="option" data='{"value":"Fertoendred","state":"Gyor-Moson-Sopron"}'>Fertoendred</div>
<div class="option" data='{"value":"Fertohomok","state":"Gyor-Moson-Sopron"}'>Fertohomok</div>
<div class="option" data='{"value":"Fertopuszta","state":"Gyor-Moson-Sopron"}'>Fertopuszta</div>
<div class="option" data='{"value":"Fertorakos","state":"Gyor-Moson-Sopron"}'>Fertorakos</div>
<div class="option" data='{"value":"Fertoszentmiklos","state":"Gyor-Moson-Sopron"}'>Fertoszentmiklos</div>
<div class="option" data='{"value":"Fertoszeplak","state":"Gyor-Moson-Sopron"}'>Fertoszeplak</div>
<div class="option" data='{"value":"Foldsziget","state":"Gyor-Moson-Sopron"}'>Foldsziget</div>
<div class="option" data='{"value":"Foldvarpuszta","state":"Gyor-Moson-Sopron"}'>Foldvarpuszta</div>
<div class="option" data='{"value":"Folerdomajor","state":"Gyor-Moson-Sopron"}'>Folerdomajor</div>
<div class="option" data='{"value":"Forgachpuszta","state":"Gyor-Moson-Sopron"}'>Forgachpuszta</div>
<div class="option" data='{"value":"Forgacspuszta","state":"Gyor-Moson-Sopron"}'>Forgacspuszta</div>
<div class="option" data='{"value":"Franciskamajor","state":"Gyor-Moson-Sopron"}'>Franciskamajor</div>
<div class="option" data='{"value":"Frankpuszta","state":"Gyor-Moson-Sopron"}'>Frankpuszta</div>
<div class="option" data='{"value":"Fudipuszta","state":"Gyor-Moson-Sopron"}'>Fudipuszta</div>
<div class="option" data='{"value":"Fuditelep","state":"Gyor-Moson-Sopron"}'>Fuditelep</div>
<div class="option" data='{"value":"Fulekitanya","state":"Gyor-Moson-Sopron"}'>Fulekitanya</div>
<div class="option" data='{"value":"Fulekytanya","state":"Gyor-Moson-Sopron"}'>Fulekytanya</div>
<div class="option" data='{"value":"Fuzesdulo","state":"Gyor-Moson-Sopron"}'>Fuzesdulo</div>
<div class="option" data='{"value":"Galambossziget","state":"Gyor-Moson-Sopron"}'>Galambossziget</div>
<div class="option" data='{"value":"Galavicspuszta","state":"Gyor-Moson-Sopron"}'>Galavicspuszta</div>
<div class="option" data='{"value":"Galovicspuszta","state":"Gyor-Moson-Sopron"}'>Galovicspuszta</div>
<div class="option" data='{"value":"Gemesmajor","state":"Gyor-Moson-Sopron"}'>Gemesmajor</div>
<div class="option" data='{"value":"Gemespuszta","state":"Gyor-Moson-Sopron"}'>Gemespuszta</div>
<div class="option" data='{"value":"Gezahaza","state":"Gyor-Moson-Sopron"}'>Gezahaza</div>
<div class="option" data='{"value":"Gizellamajor","state":"Gyor-Moson-Sopron"}'>Gizellamajor</div>
<div class="option" data='{"value":"Gobosmajor","state":"Gyor-Moson-Sopron"}'>Gobosmajor</div>
<div class="option" data='{"value":"Gonyu","state":"Gyor-Moson-Sopron"}'>Gonyu</div>
<div class="option" data='{"value":"Gorbehalom","state":"Gyor-Moson-Sopron"}'>Gorbehalom</div>
<div class="option" data='{"value":"Gorbehalomtelep","state":"Gyor-Moson-Sopron"}'>Gorbehalomtelep</div>
<div class="option" data='{"value":"Gozmalomgyartelep","state":"Gyor-Moson-Sopron"}'>Gozmalomgyartelep</div>
<div class="option" data='{"value":"Gughpuszta","state":"Gyor-Moson-Sopron"}'>Gughpuszta</div>
<div class="option" data='{"value":"Gugpuszta","state":"Gyor-Moson-Sopron"}'>Gugpuszta</div>
<div class="option" data='{"value":"Gyaloka","state":"Gyor-Moson-Sopron"}'>Gyaloka</div>
<div class="option" data='{"value":"Gyarmat","state":"Gyor-Moson-Sopron"}'>Gyarmat</div>
<div class="option" data='{"value":"Gyomore","state":"Gyor-Moson-Sopron"}'>Gyomore</div>
<div class="option" data='{"value":"Gyongyosmajor","state":"Gyor-Moson-Sopron"}'>Gyongyosmajor</div>
<div class="option" data='{"value":"Gyongytanya","state":"Gyor-Moson-Sopron"}'>Gyongytanya</div>
<div class="option" data='{"value":"Gyorasszonyfa","state":"Gyor-Moson-Sopron"}'>Gyorasszonyfa</div>
<div class="option" data='{"value":"Gyorgyhaza","state":"Gyor-Moson-Sopron"}'>Gyorgyhaza</div>
<div class="option" data='{"value":"Gyoritanya","state":"Gyor-Moson-Sopron"}'>Gyoritanya</div>
<div class="option" data='{"value":"Gyorladamer","state":"Gyor-Moson-Sopron"}'>Gyorladamer</div>
<div class="option" data='{"value":"Gyoro","state":"Gyor-Moson-Sopron"}'>Gyoro</div>
<div class="option" data='{"value":"Gyorsag","state":"Gyor-Moson-Sopron"}'>Gyorsag</div>
<div class="option" data='{"value":"Gyorsovenyhaz","state":"Gyor-Moson-Sopron"}'>Gyorsovenyhaz</div>
<div class="option" data='{"value":"Gyorszabadi","state":"Gyor-Moson-Sopron"}'>Gyorszabadi</div>
<div class="option" data='{"value":"Gyorszemere","state":"Gyor-Moson-Sopron"}'>Gyorszemere</div>
<div class="option" data='{"value":"Gyorszemerehegy","state":"Gyor-Moson-Sopron"}'>Gyorszemerehegy</div>
<div class="option" data='{"value":"Gyorszentmarton","state":"Gyor-Moson-Sopron"}'>Gyorszentmarton</div>
<div class="option" data='{"value":"Gyorujbarat","state":"Gyor-Moson-Sopron"}'>Gyorujbarat</div>
<div class="option" data='{"value":"Gyorujfalu","state":"Gyor-Moson-Sopron"}'>Gyorujfalu</div>
<div class="option" data='{"value":"Gyorzamoly","state":"Gyor-Moson-Sopron"}'>Gyorzamoly</div>
<div class="option" data='{"value":"Gyulamajor","state":"Gyor-Moson-Sopron"}'>Gyulamajor</div>
<div class="option" data='{"value":"Gyuruspuszta","state":"Gyor-Moson-Sopron"}'>Gyuruspuszta</div>
<div class="option" data='{"value":"Haidentanya","state":"Gyor-Moson-Sopron"}'>Haidentanya</div>
<div class="option" data='{"value":"Hajospuszta","state":"Gyor-Moson-Sopron"}'>Hajospuszta</div>
<div class="option" data='{"value":"Halaszi","state":"Gyor-Moson-Sopron"}'>Halaszi</div>
<div class="option" data='{"value":"Halipuszta","state":"Gyor-Moson-Sopron"}'>Halipuszta</div>
<div class="option" data='{"value":"Hangyaspuszta","state":"Gyor-Moson-Sopron"}'>Hangyaspuszta</div>
<div class="option" data='{"value":"Hansagi Nagyerdo","state":"Gyor-Moson-Sopron"}'>Hansagi Nagyerdo</div>
<div class="option" data='{"value":"Hansagi Tanyak","state":"Gyor-Moson-Sopron"}'>Hansagi Tanyak</div>
<div class="option" data='{"value":"Hansagi Ujmajor","state":"Gyor-Moson-Sopron"}'>Hansagi Ujmajor</div>
<div class="option" data='{"value":"Hansagnagyerdo","state":"Gyor-Moson-Sopron"}'>Hansagnagyerdo</div>
<div class="option" data='{"value":"Hansagujmajor","state":"Gyor-Moson-Sopron"}'>Hansagujmajor</div>
<div class="option" data='{"value":"Haraszt","state":"Gyor-Moson-Sopron"}'>Haraszt</div>
<div class="option" data='{"value":"Harka","state":"Gyor-Moson-Sopron"}'>Harka</div>
<div class="option" data='{"value":"Harkaimajor","state":"Gyor-Moson-Sopron"}'>Harkaimajor</div>
<div class="option" data='{"value":"Harkakophaza","state":"Gyor-Moson-Sopron"}'>Harkakophaza</div>
<div class="option" data='{"value":"Harmastarjan","state":"Gyor-Moson-Sopron"}'>Harmastarjan</div>
<div class="option" data='{"value":"Harmastarjanpuszta","state":"Gyor-Moson-Sopron"}'>Harmastarjanpuszta</div>
<div class="option" data='{"value":"Hathaz","state":"Gyor-Moson-Sopron"}'>Hathaz</div>
<div class="option" data='{"value":"Hecsepuszta","state":"Gyor-Moson-Sopron"}'>Hecsepuszta</div>
<div class="option" data='{"value":"Hedervar","state":"Gyor-Moson-Sopron"}'>Hedervar</div>
<div class="option" data='{"value":"Hegyeshalom","state":"Gyor-Moson-Sopron"}'>Hegyeshalom</div>
<div class="option" data='{"value":"Hegyitanya","state":"Gyor-Moson-Sopron"}'>Hegyitanya</div>
<div class="option" data='{"value":"Hegyko","state":"Gyor-Moson-Sopron"}'>Hegyko</div>
<div class="option" data='{"value":"Hencztanya","state":"Gyor-Moson-Sopron"}'>Hencztanya</div>
<div class="option" data='{"value":"Hermesitelep","state":"Gyor-Moson-Sopron"}'>Hermesitelep</div>
<div class="option" data='{"value":"Hettestvermajor","state":"Gyor-Moson-Sopron"}'>Hettestvermajor</div>
<div class="option" data='{"value":"Hidegseg","state":"Gyor-Moson-Sopron"}'>Hidegseg</div>
<div class="option" data='{"value":"Himod","state":"Gyor-Moson-Sopron"}'>Himod</div>
<div class="option" data='{"value":"Hodaly","state":"Gyor-Moson-Sopron"}'>Hodaly</div>
<div class="option" data='{"value":"Hogyeszymajor","state":"Gyor-Moson-Sopron"}'>Hogyeszymajor</div>
<div class="option" data='{"value":"Hollomajor","state":"Gyor-Moson-Sopron"}'>Hollomajor</div>
<div class="option" data='{"value":"Homok","state":"Gyor-Moson-Sopron"}'>Homok</div>
<div class="option" data='{"value":"Homokdulo","state":"Gyor-Moson-Sopron"}'>Homokdulo</div>
<div class="option" data='{"value":"Honvedpuszta","state":"Gyor-Moson-Sopron"}'>Honvedpuszta</div>
<div class="option" data='{"value":"Horvathtanya","state":"Gyor-Moson-Sopron"}'>Horvathtanya</div>
<div class="option" data='{"value":"Horvatkimle","state":"Gyor-Moson-Sopron"}'>Horvatkimle</div>
<div class="option" data='{"value":"Hovej","state":"Gyor-Moson-Sopron"}'>Hovej</div>
<div class="option" data='{"value":"Hugotpuszta","state":"Gyor-Moson-Sopron"}'>Hugotpuszta</div>
<div class="option" data='{"value":"Icselytanya","state":"Gyor-Moson-Sopron"}'>Icselytanya</div>
<div class="option" data='{"value":"Iharosmajor","state":"Gyor-Moson-Sopron"}'>Iharosmajor</div>
<div class="option" data='{"value":"Ikreny","state":"Gyor-Moson-Sopron"}'>Ikreny</div>
<div class="option" data='{"value":"Ilmamajor","state":"Gyor-Moson-Sopron"}'>Ilmamajor</div>
<div class="option" data='{"value":"Ilonamajor","state":"Gyor-Moson-Sopron"}'>Ilonamajor</div>
<div class="option" data='{"value":"Ilonkapuszta","state":"Gyor-Moson-Sopron"}'>Ilonkapuszta</div>
<div class="option" data='{"value":"Imre Puszta","state":"Gyor-Moson-Sopron"}'>Imre Puszta</div>
<div class="option" data='{"value":"Imremajor","state":"Gyor-Moson-Sopron"}'>Imremajor</div>
<div class="option" data='{"value":"Irenmajor","state":"Gyor-Moson-Sopron"}'>Irenmajor</div>
<div class="option" data='{"value":"Irmamajor","state":"Gyor-Moson-Sopron"}'>Irmamajor</div>
<div class="option" data='{"value":"Istvanmajor","state":"Gyor-Moson-Sopron"}'>Istvanmajor</div>
<div class="option" data='{"value":"Ivan","state":"Gyor-Moson-Sopron"}'>Ivan</div>
<div class="option" data='{"value":"Ivancsicstanya","state":"Gyor-Moson-Sopron"}'>Ivancsicstanya</div>
<div class="option" data='{"value":"Ivanhaza","state":"Gyor-Moson-Sopron"}'>Ivanhaza</div>
<div class="option" data='{"value":"Ivanhazapuszta","state":"Gyor-Moson-Sopron"}'>Ivanhazapuszta</div>
<div class="option" data='{"value":"Ivanhazatanya","state":"Gyor-Moson-Sopron"}'>Ivanhazatanya</div>
<div class="option" data='{"value":"Ivantelep","state":"Gyor-Moson-Sopron"}'>Ivantelep</div>
<div class="option" data='{"value":"Jancsimajor","state":"Gyor-Moson-Sopron"}'>Jancsimajor</div>
<div class="option" data='{"value":"Janosfaimalom","state":"Gyor-Moson-Sopron"}'>Janosfaimalom</div>
<div class="option" data='{"value":"Janoshaza","state":"Gyor-Moson-Sopron"}'>Janoshaza</div>
<div class="option" data='{"value":"Janoshazapuszta","state":"Gyor-Moson-Sopron"}'>Janoshazapuszta</div>
<div class="option" data='{"value":"Janosmajor","state":"Gyor-Moson-Sopron"}'>Janosmajor</div>
<div class="option" data='{"value":"Janossomorja","state":"Gyor-Moson-Sopron"}'>Janossomorja</div>
<div class="option" data='{"value":"Jobahaza","state":"Gyor-Moson-Sopron"}'>Jobahaza</div>
<div class="option" data='{"value":"Jozsefhaza","state":"Gyor-Moson-Sopron"}'>Jozsefhaza</div>
<div class="option" data='{"value":"Jozsefhazapuszta","state":"Gyor-Moson-Sopron"}'>Jozsefhazapuszta</div>
<div class="option" data='{"value":"Jozsefmajor","state":"Gyor-Moson-Sopron"}'>Jozsefmajor</div>
<div class="option" data='{"value":"Kajar","state":"Gyor-Moson-Sopron"}'>Kajar</div>
<div class="option" data='{"value":"Kajarpec","state":"Gyor-Moson-Sopron"}'>Kajarpec</div>
<div class="option" data='{"value":"Kakasmajor","state":"Gyor-Moson-Sopron"}'>Kakasmajor</div>
<div class="option" data='{"value":"Kalappuszta","state":"Gyor-Moson-Sopron"}'>Kalappuszta</div>
<div class="option" data='{"value":"Kalmanmajor","state":"Gyor-Moson-Sopron"}'>Kalmanmajor</div>
<div class="option" data='{"value":"Kalmanpuszta","state":"Gyor-Moson-Sopron"}'>Kalmanpuszta</div>
<div class="option" data='{"value":"Kalmantag","state":"Gyor-Moson-Sopron"}'>Kalmantag</div>
<div class="option" data='{"value":"Kamvaskutidulo","state":"Gyor-Moson-Sopron"}'>Kamvaskutidulo</div>
<div class="option" data='{"value":"Kanaszhaza","state":"Gyor-Moson-Sopron"}'>Kanaszhaza</div>
<div class="option" data='{"value":"Kaptalanmajor","state":"Gyor-Moson-Sopron"}'>Kaptalanmajor</div>
<div class="option" data='{"value":"Kaptalanpuszta","state":"Gyor-Moson-Sopron"}'>Kaptalanpuszta</div>
<div class="option" data='{"value":"Kapuvar","state":"Gyor-Moson-Sopron"}'>Kapuvar</div>
<div class="option" data='{"value":"Karolyhaza","state":"Gyor-Moson-Sopron"}'>Karolyhaza</div>
<div class="option" data='{"value":"Karolyhazapuszta","state":"Gyor-Moson-Sopron"}'>Karolyhazapuszta</div>
<div class="option" data='{"value":"Karolyhazatanya","state":"Gyor-Moson-Sopron"}'>Karolyhazatanya</div>
<div class="option" data='{"value":"Karolyhazmajor","state":"Gyor-Moson-Sopron"}'>Karolyhazmajor</div>
<div class="option" data='{"value":"Karolymajor","state":"Gyor-Moson-Sopron"}'>Karolymajor</div>
<div class="option" data='{"value":"Karospuszta","state":"Gyor-Moson-Sopron"}'>Karospuszta</div>
<div class="option" data='{"value":"Kecskemet","state":"Gyor-Moson-Sopron"}'>Kecskemet</div>
<div class="option" data='{"value":"Kendergyar","state":"Gyor-Moson-Sopron"}'>Kendergyar</div>
<div class="option" data='{"value":"Kereszteny","state":"Gyor-Moson-Sopron"}'>Kereszteny</div>
<div class="option" data='{"value":"Kertvaros","state":"Gyor-Moson-Sopron"}'>Kertvaros</div>
<div class="option" data='{"value":"Keszolces","state":"Gyor-Moson-Sopron"}'>Keszolces</div>
<div class="option" data='{"value":"Kimle","state":"Gyor-Moson-Sopron"}'>Kimle</div>
<div class="option" data='{"value":"Kiralymajor","state":"Gyor-Moson-Sopron"}'>Kiralymajor</div>
<div class="option" data='{"value":"Kiralytomajor","state":"Gyor-Moson-Sopron"}'>Kiralytomajor</div>
<div class="option" data='{"value":"Kisbabot","state":"Gyor-Moson-Sopron"}'>Kisbabot</div>
<div class="option" data='{"value":"Kisbacsa","state":"Gyor-Moson-Sopron"}'>Kisbacsa</div>
<div class="option" data='{"value":"Kisbajcs","state":"Gyor-Moson-Sopron"}'>Kisbajcs</div>
<div class="option" data='{"value":"Kisbarat","state":"Gyor-Moson-Sopron"}'>Kisbarat</div>
<div class="option" data='{"value":"Kisbarathegy","state":"Gyor-Moson-Sopron"}'>Kisbarathegy</div>
<div class="option" data='{"value":"Kisbarathegy Ujtelep","state":"Gyor-Moson-Sopron"}'>Kisbarathegy Ujtelep</div>
<div class="option" data='{"value":"Kisbaytag","state":"Gyor-Moson-Sopron"}'>Kisbaytag</div>
<div class="option" data='{"value":"Kisbodak","state":"Gyor-Moson-Sopron"}'>Kisbodak</div>
<div class="option" data='{"value":"Kisecs","state":"Gyor-Moson-Sopron"}'>Kisecs</div>
<div class="option" data='{"value":"Kisecstelep","state":"Gyor-Moson-Sopron"}'>Kisecstelep</div>
<div class="option" data='{"value":"Kisfalud","state":"Gyor-Moson-Sopron"}'>Kisfalud</div>
<div class="option" data='{"value":"Kisfertoboz","state":"Gyor-Moson-Sopron"}'>Kisfertoboz</div>
<div class="option" data='{"value":"Kishaz","state":"Gyor-Moson-Sopron"}'>Kishaz</div>
<div class="option" data='{"value":"Kishazasidulo","state":"Gyor-Moson-Sopron"}'>Kishazasidulo</div>
<div class="option" data='{"value":"Kishegy","state":"Gyor-Moson-Sopron"}'>Kishegy</div>
<div class="option" data='{"value":"Kiskarrospuszta","state":"Gyor-Moson-Sopron"}'>Kiskarrospuszta</div>
<div class="option" data='{"value":"Kislesvarmajor","state":"Gyor-Moson-Sopron"}'>Kislesvarmajor</div>
<div class="option" data='{"value":"Kislozs","state":"Gyor-Moson-Sopron"}'>Kislozs</div>
<div class="option" data='{"value":"Kislozsmajor","state":"Gyor-Moson-Sopron"}'>Kislozsmajor</div>
<div class="option" data='{"value":"Kismegyer","state":"Gyor-Moson-Sopron"}'>Kismegyer</div>
<div class="option" data='{"value":"Kisnemapuszta","state":"Gyor-Moson-Sopron"}'>Kisnemapuszta</div>
<div class="option" data='{"value":"Kisnyalkapuszta","state":"Gyor-Moson-Sopron"}'>Kisnyalkapuszta</div>
<div class="option" data='{"value":"Kispec","state":"Gyor-Moson-Sopron"}'>Kispec</div>
<div class="option" data='{"value":"Kispervat","state":"Gyor-Moson-Sopron"}'>Kispervat</div>
<div class="option" data='{"value":"Kispervatpuszta","state":"Gyor-Moson-Sopron"}'>Kispervatpuszta</div>
<div class="option" data='{"value":"Kiss Erno Tag","state":"Gyor-Moson-Sopron"}'>Kiss Erno Tag</div>
<div class="option" data='{"value":"Kisstanya","state":"Gyor-Moson-Sopron"}'>Kisstanya</div>
<div class="option" data='{"value":"Kisszentjanos","state":"Gyor-Moson-Sopron"}'>Kisszentjanos</div>
<div class="option" data='{"value":"Kisszentpal","state":"Gyor-Moson-Sopron"}'>Kisszentpal</div>
<div class="option" data='{"value":"Kisszentpalpuszta","state":"Gyor-Moson-Sopron"}'>Kisszentpalpuszta</div>
<div class="option" data='{"value":"Kistolgyfamajor","state":"Gyor-Moson-Sopron"}'>Kistolgyfamajor</div>
<div class="option" data='{"value":"Kistolgyfapuszta","state":"Gyor-Moson-Sopron"}'>Kistolgyfapuszta</div>
<div class="option" data='{"value":"Kisudvar","state":"Gyor-Moson-Sopron"}'>Kisudvar</div>
<div class="option" data='{"value":"Kisudvarmajor","state":"Gyor-Moson-Sopron"}'>Kisudvarmajor</div>
<div class="option" data='{"value":"Koblosmajor","state":"Gyor-Moson-Sopron"}'>Koblosmajor</div>
<div class="option" data='{"value":"Kochtanya","state":"Gyor-Moson-Sopron"}'>Kochtanya</div>
<div class="option" data='{"value":"Koczytanya","state":"Gyor-Moson-Sopron"}'>Koczytanya</div>
<div class="option" data='{"value":"Kohazimajor","state":"Gyor-Moson-Sopron"}'>Kohazimajor</div>
<div class="option" data='{"value":"Kohidtelep","state":"Gyor-Moson-Sopron"}'>Kohidtelep</div>
<div class="option" data='{"value":"Kolesdulotag","state":"Gyor-Moson-Sopron"}'>Kolesdulotag</div>
<div class="option" data='{"value":"Kolesmajor","state":"Gyor-Moson-Sopron"}'>Kolesmajor</div>
<div class="option" data='{"value":"Kony","state":"Gyor-Moson-Sopron"}'>Kony</div>
<div class="option" data='{"value":"Kophaza","state":"Gyor-Moson-Sopron"}'>Kophaza</div>
<div class="option" data='{"value":"Kophazimajor","state":"Gyor-Moson-Sopron"}'>Kophazimajor</div>
<div class="option" data='{"value":"Kophazipuszta","state":"Gyor-Moson-Sopron"}'>Kophazipuszta</div>
<div class="option" data='{"value":"Korhaztelep","state":"Gyor-Moson-Sopron"}'>Korhaztelep</div>
<div class="option" data='{"value":"Koronco","state":"Gyor-Moson-Sopron"}'>Koronco</div>
<div class="option" data='{"value":"Kortvelyesmajor","state":"Gyor-Moson-Sopron"}'>Kortvelyesmajor</div>
<div class="option" data='{"value":"Kosdombitanya","state":"Gyor-Moson-Sopron"}'>Kosdombitanya</div>
<div class="option" data='{"value":"Kosdombtanya","state":"Gyor-Moson-Sopron"}'>Kosdombtanya</div>
<div class="option" data='{"value":"Kovacstag","state":"Gyor-Moson-Sopron"}'>Kovacstag</div>
<div class="option" data='{"value":"Kovacstanya","state":"Gyor-Moson-Sopron"}'>Kovacstanya</div>
<div class="option" data='{"value":"Kovecses","state":"Gyor-Moson-Sopron"}'>Kovecses</div>
<div class="option" data='{"value":"Kozepmalom","state":"Gyor-Moson-Sopron"}'>Kozepmalom</div>
<div class="option" data='{"value":"Kozlikmajor","state":"Gyor-Moson-Sopron"}'>Kozlikmajor</div>
<div class="option" data='{"value":"Kozliktanya","state":"Gyor-Moson-Sopron"}'>Kozliktanya</div>
<div class="option" data='{"value":"Kremertag","state":"Gyor-Moson-Sopron"}'>Kremertag</div>
<div class="option" data='{"value":"Kroisbach","state":"Gyor-Moson-Sopron"}'>Kroisbach</div>
<div class="option" data='{"value":"Kucserkatanya","state":"Gyor-Moson-Sopron"}'>Kucserkatanya</div>
<div class="option" data='{"value":"Kudelatanya","state":"Gyor-Moson-Sopron"}'>Kudelatanya</div>
<div class="option" data='{"value":"Kulsolajtamajor","state":"Gyor-Moson-Sopron"}'>Kulsolajtamajor</div>
<div class="option" data='{"value":"Kunsziget","state":"Gyor-Moson-Sopron"}'>Kunsziget</div>
<div class="option" data='{"value":"Kuruckereszttelep","state":"Gyor-Moson-Sopron"}'>Kuruckereszttelep</div>
<div class="option" data='{"value":"Ladanyigyumolcsos","state":"Gyor-Moson-Sopron"}'>Ladanyigyumolcsos</div>
<div class="option" data='{"value":"Lajosmajor","state":"Gyor-Moson-Sopron"}'>Lajosmajor</div>
<div class="option" data='{"value":"Landzsas","state":"Gyor-Moson-Sopron"}'>Landzsas</div>
<div class="option" data='{"value":"Lapostanya","state":"Gyor-Moson-Sopron"}'>Lapostanya</div>
<div class="option" data='{"value":"Laszlofoldimajor","state":"Gyor-Moson-Sopron"}'>Laszlofoldimajor</div>
<div class="option" data='{"value":"Laszlomajor","state":"Gyor-Moson-Sopron"}'>Laszlomajor</div>
<div class="option" data='{"value":"Lazi","state":"Gyor-Moson-Sopron"}'>Lazi</div>
<div class="option" data='{"value":"Lebeny","state":"Gyor-Moson-Sopron"}'>Lebeny</div>
<div class="option" data='{"value":"Lebenyi Tanyak","state":"Gyor-Moson-Sopron"}'>Lebenyi Tanyak</div>
<div class="option" data='{"value":"Lebenymiklos","state":"Gyor-Moson-Sopron"}'>Lebenymiklos</div>
<div class="option" data='{"value":"Lengyar","state":"Gyor-Moson-Sopron"}'>Lengyar</div>
<div class="option" data='{"value":"Lesvarpuszta","state":"Gyor-Moson-Sopron"}'>Lesvarpuszta</div>
<div class="option" data='{"value":"Level","state":"Gyor-Moson-Sopron"}'>Level</div>
<div class="option" data='{"value":"Leveluti Tanyak","state":"Gyor-Moson-Sopron"}'>Leveluti Tanyak</div>
<div class="option" data='{"value":"Lickopuszta","state":"Gyor-Moson-Sopron"}'>Lickopuszta</div>
<div class="option" data='{"value":"Likocs","state":"Gyor-Moson-Sopron"}'>Likocs</div>
<div class="option" data='{"value":"Likocspuszta","state":"Gyor-Moson-Sopron"}'>Likocspuszta</div>
<div class="option" data='{"value":"Lipot","state":"Gyor-Moson-Sopron"}'>Lipot</div>
<div class="option" data='{"value":"Losoncihaz","state":"Gyor-Moson-Sopron"}'>Losoncihaz</div>
<div class="option" data='{"value":"Lovo","state":"Gyor-Moson-Sopron"}'>Lovo</div>
<div class="option" data='{"value":"Lujzamajor","state":"Gyor-Moson-Sopron"}'>Lujzamajor</div>
<div class="option" data='{"value":"Magloca","state":"Gyor-Moson-Sopron"}'>Magloca</div>
<div class="option" data='{"value":"Magyaloserdo","state":"Gyor-Moson-Sopron"}'>Magyaloserdo</div>
<div class="option" data='{"value":"Magyalosi Erdo","state":"Gyor-Moson-Sopron"}'>Magyalosi Erdo</div>
<div class="option" data='{"value":"Magyardulo","state":"Gyor-Moson-Sopron"}'>Magyardulo</div>
<div class="option" data='{"value":"Magyarfalva","state":"Gyor-Moson-Sopron"}'>Magyarfalva</div>
<div class="option" data='{"value":"Magyarkeresztur","state":"Gyor-Moson-Sopron"}'>Magyarkeresztur</div>
<div class="option" data='{"value":"Magyarkimle","state":"Gyor-Moson-Sopron"}'>Magyarkimle</div>
<div class="option" data='{"value":"Magyarovar","state":"Gyor-Moson-Sopron"}'>Magyarovar</div>
<div class="option" data='{"value":"Magyartanya","state":"Gyor-Moson-Sopron"}'>Magyartanya</div>
<div class="option" data='{"value":"Majkszentjanos","state":"Gyor-Moson-Sopron"}'>Majkszentjanos</div>
<div class="option" data='{"value":"Majkszentjanospuszta","state":"Gyor-Moson-Sopron"}'>Majkszentjanospuszta</div>
<div class="option" data='{"value":"Major","state":"Gyor-Moson-Sopron"}'>Major</div>
<div class="option" data='{"value":"Malom","state":"Gyor-Moson-Sopron"}'>Malom</div>
<div class="option" data='{"value":"Malomdulo","state":"Gyor-Moson-Sopron"}'>Malomdulo</div>
<div class="option" data='{"value":"Margitmajor","state":"Gyor-Moson-Sopron"}'>Margitmajor</div>
<div class="option" data='{"value":"Margitpuszta","state":"Gyor-Moson-Sopron"}'>Margitpuszta</div>
<div class="option" data='{"value":"Mariakalnok","state":"Gyor-Moson-Sopron"}'>Mariakalnok</div>
<div class="option" data='{"value":"Marialiget","state":"Gyor-Moson-Sopron"}'>Marialiget</div>
<div class="option" data='{"value":"Marialigeti Malom","state":"Gyor-Moson-Sopron"}'>Marialigeti Malom</div>
<div class="option" data='{"value":"Mariamajor","state":"Gyor-Moson-Sopron"}'>Mariamajor</div>
<div class="option" data='{"value":"Markotabodoge","state":"Gyor-Moson-Sopron"}'>Markotabodoge</div>
<div class="option" data='{"value":"Martasor","state":"Gyor-Moson-Sopron"}'>Martasor</div>
<div class="option" data='{"value":"Martonhaza","state":"Gyor-Moson-Sopron"}'>Martonhaza</div>
<div class="option" data='{"value":"Martonhazapuszta","state":"Gyor-Moson-Sopron"}'>Martonhazapuszta</div>
<div class="option" data='{"value":"Mauthnertelep","state":"Gyor-Moson-Sopron"}'>Mauthnertelep</div>
<div class="option" data='{"value":"Mecser","state":"Gyor-Moson-Sopron"}'>Mecser</div>
<div class="option" data='{"value":"Megyimori Tanya","state":"Gyor-Moson-Sopron"}'>Megyimori Tanya</div>
<div class="option" data='{"value":"Meidlingertanya","state":"Gyor-Moson-Sopron"}'>Meidlingertanya</div>
<div class="option" data='{"value":"Mekszikopuszta","state":"Gyor-Moson-Sopron"}'>Mekszikopuszta</div>
<div class="option" data='{"value":"Merges","state":"Gyor-Moson-Sopron"}'>Merges</div>
<div class="option" data='{"value":"Mexikopuszta","state":"Gyor-Moson-Sopron"}'>Mexikopuszta</div>
<div class="option" data='{"value":"Mezoors","state":"Gyor-Moson-Sopron"}'>Mezoors</div>
<div class="option" data='{"value":"Mihalyi","state":"Gyor-Moson-Sopron"}'>Mihalyi</div>
<div class="option" data='{"value":"Mikloshalmi Tanyak","state":"Gyor-Moson-Sopron"}'>Mikloshalmi Tanyak</div>
<div class="option" data='{"value":"Miklosmajor","state":"Gyor-Moson-Sopron"}'>Miklosmajor</div>
<div class="option" data='{"value":"Miksamajor","state":"Gyor-Moson-Sopron"}'>Miksamajor</div>
<div class="option" data='{"value":"Mindszentpuszta","state":"Gyor-Moson-Sopron"}'>Mindszentpuszta</div>
<div class="option" data='{"value":"Modovitstanya","state":"Gyor-Moson-Sopron"}'>Modovitstanya</div>
<div class="option" data='{"value":"Modrovitstag","state":"Gyor-Moson-Sopron"}'>Modrovitstag</div>
<div class="option" data='{"value":"Molcnerhaz","state":"Gyor-Moson-Sopron"}'>Molcnerhaz</div>
<div class="option" data='{"value":"Molcznertanya","state":"Gyor-Moson-Sopron"}'>Molcznertanya</div>
<div class="option" data='{"value":"Morichida","state":"Gyor-Moson-Sopron"}'>Morichida</div>
<div class="option" data='{"value":"Morichidaitanya","state":"Gyor-Moson-Sopron"}'>Morichidaitanya</div>
<div class="option" data='{"value":"Moson","state":"Gyor-Moson-Sopron"}'>Moson</div>
<div class="option" data='{"value":"Mosoniuti Tanyak","state":"Gyor-Moson-Sopron"}'>Mosoniuti Tanyak</div>
<div class="option" data='{"value":"Mosonmagyarovar","state":"Gyor-Moson-Sopron"}'>Mosonmagyarovar</div>
<div class="option" data='{"value":"Mosonszentjanos","state":"Gyor-Moson-Sopron"}'>Mosonszentjanos</div>
<div class="option" data='{"value":"Mosonszentjanosi Tanyak","state":"Gyor-Moson-Sopron"}'>Mosonszentjanosi Tanyak</div>
<div class="option" data='{"value":"Mosonszentmiklos","state":"Gyor-Moson-Sopron"}'>Mosonszentmiklos</div>
<div class="option" data='{"value":"Mosonszentmiklosi Tanyak","state":"Gyor-Moson-Sopron"}'>Mosonszentmiklosi Tanyak</div>
<div class="option" data='{"value":"Mosonszentpeter","state":"Gyor-Moson-Sopron"}'>Mosonszentpeter</div>
<div class="option" data='{"value":"Mosonszolnok","state":"Gyor-Moson-Sopron"}'>Mosonszolnok</div>
<div class="option" data='{"value":"Nadortanya","state":"Gyor-Moson-Sopron"}'>Nadortanya</div>
<div class="option" data='{"value":"Nagybajcs","state":"Gyor-Moson-Sopron"}'>Nagybajcs</div>
<div class="option" data='{"value":"Nagybarat","state":"Gyor-Moson-Sopron"}'>Nagybarat</div>
<div class="option" data='{"value":"Nagycenk","state":"Gyor-Moson-Sopron"}'>Nagycenk</div>
<div class="option" data='{"value":"Nagyhegy","state":"Gyor-Moson-Sopron"}'>Nagyhegy</div>
<div class="option" data='{"value":"Nagykarrospuszta","state":"Gyor-Moson-Sopron"}'>Nagykarrospuszta</div>
<div class="option" data='{"value":"Nagylozs","state":"Gyor-Moson-Sopron"}'>Nagylozs</div>
<div class="option" data='{"value":"Nagyszentjanos","state":"Gyor-Moson-Sopron"}'>Nagyszentjanos</div>
<div class="option" data='{"value":"Nagysziget","state":"Gyor-Moson-Sopron"}'>Nagysziget</div>
<div class="option" data='{"value":"Nagytanya","state":"Gyor-Moson-Sopron"}'>Nagytanya</div>
<div class="option" data='{"value":"Naplomajor","state":"Gyor-Moson-Sopron"}'>Naplomajor</div>
<div class="option" data='{"value":"Nemesker","state":"Gyor-Moson-Sopron"}'>Nemesker</div>
<div class="option" data='{"value":"Nemestag","state":"Gyor-Moson-Sopron"}'>Nemestag</div>
<div class="option" data='{"value":"Nemethmajor","state":"Gyor-Moson-Sopron"}'>Nemethmajor</div>
<div class="option" data='{"value":"Nemethtanya","state":"Gyor-Moson-Sopron"}'>Nemethtanya</div>
<div class="option" data='{"value":"Nyalka","state":"Gyor-Moson-Sopron"}'>Nyalka</div>
<div class="option" data='{"value":"Nyarosimajor","state":"Gyor-Moson-Sopron"}'>Nyarosimajor</div>
<div class="option" data='{"value":"Nyul","state":"Gyor-Moson-Sopron"}'>Nyul</div>
<div class="option" data='{"value":"Odenburg","state":"Gyor-Moson-Sopron"}'>Odenburg</div>
<div class="option" data='{"value":"Oltvanyi Tanya","state":"Gyor-Moson-Sopron"}'>Oltvanyi Tanya</div>
<div class="option" data='{"value":"Ontesmajor","state":"Gyor-Moson-Sopron"}'>Ontesmajor</div>
<div class="option" data='{"value":"Oregfoldi Tanya","state":"Gyor-Moson-Sopron"}'>Oregfoldi Tanya</div>
<div class="option" data='{"value":"Oregnemapuszta","state":"Gyor-Moson-Sopron"}'>Oregnemapuszta</div>
<div class="option" data='{"value":"Oregszollo","state":"Gyor-Moson-Sopron"}'>Oregszollo</div>
<div class="option" data='{"value":"Oregszollok","state":"Gyor-Moson-Sopron"}'>Oregszollok</div>
<div class="option" data='{"value":"Orkenyi Tagsor","state":"Gyor-Moson-Sopron"}'>Orkenyi Tagsor</div>
<div class="option" data='{"value":"Orkenypuszta","state":"Gyor-Moson-Sopron"}'>Orkenypuszta</div>
<div class="option" data='{"value":"Orospuszta","state":"Gyor-Moson-Sopron"}'>Orospuszta</div>
<div class="option" data='{"value":"Orszagosfegyhaz","state":"Gyor-Moson-Sopron"}'>Orszagosfegyhaz</div>
<div class="option" data='{"value":"Orszagosfegyintezet","state":"Gyor-Moson-Sopron"}'>Orszagosfegyintezet</div>
<div class="option" data='{"value":"Osli","state":"Gyor-Moson-Sopron"}'>Osli</div>
<div class="option" data='{"value":"Ostffymajor","state":"Gyor-Moson-Sopron"}'>Ostffymajor</div>
<div class="option" data='{"value":"Oszhelylesvar","state":"Gyor-Moson-Sopron"}'>Oszhelylesvar</div>
<div class="option" data='{"value":"Oszhelypuszta","state":"Gyor-Moson-Sopron"}'>Oszhelypuszta</div>
<div class="option" data='{"value":"Oszvaldmalom","state":"Gyor-Moson-Sopron"}'>Oszvaldmalom</div>
<div class="option" data='{"value":"Otteveny","state":"Gyor-Moson-Sopron"}'>Otteveny</div>
<div class="option" data='{"value":"Ottomajor","state":"Gyor-Moson-Sopron"}'>Ottomajor</div>
<div class="option" data='{"value":"Pagony","state":"Gyor-Moson-Sopron"}'>Pagony</div>
<div class="option" data='{"value":"Palaczkipuszta","state":"Gyor-Moson-Sopron"}'>Palaczkipuszta</div>
<div class="option" data='{"value":"Pali","state":"Gyor-Moson-Sopron"}'>Pali</div>
<div class="option" data='{"value":"Palmajor","state":"Gyor-Moson-Sopron"}'>Palmajor</div>
<div class="option" data='{"value":"Pannonhalma","state":"Gyor-Moson-Sopron"}'>Pannonhalma</div>
<div class="option" data='{"value":"Papret","state":"Gyor-Moson-Sopron"}'>Papret</div>
<div class="option" data='{"value":"Parrag","state":"Gyor-Moson-Sopron"}'>Parrag</div>
<div class="option" data='{"value":"Paskum","state":"Gyor-Moson-Sopron"}'>Paskum</div>
<div class="option" data='{"value":"Pasztori","state":"Gyor-Moson-Sopron"}'>Pasztori</div>
<div class="option" data='{"value":"Pasztoruti Dulo","state":"Gyor-Moson-Sopron"}'>Pasztoruti Dulo</div>
<div class="option" data='{"value":"Patonaihaz","state":"Gyor-Moson-Sopron"}'>Patonaihaz</div>
<div class="option" data='{"value":"Patyihaz","state":"Gyor-Moson-Sopron"}'>Patyihaz</div>
<div class="option" data='{"value":"Paulamajor","state":"Gyor-Moson-Sopron"}'>Paulamajor</div>
<div class="option" data='{"value":"Paulaudvar","state":"Gyor-Moson-Sopron"}'>Paulaudvar</div>
<div class="option" data='{"value":"Pazmandfalu","state":"Gyor-Moson-Sopron"}'>Pazmandfalu</div>
<div class="option" data='{"value":"Pazmandfalui Tanyak","state":"Gyor-Moson-Sopron"}'>Pazmandfalui Tanyak</div>
<div class="option" data='{"value":"Pazmandhegy","state":"Gyor-Moson-Sopron"}'>Pazmandhegy</div>
<div class="option" data='{"value":"Per","state":"Gyor-Moson-Sopron"}'>Per</div>
<div class="option" data='{"value":"Pereszteg","state":"Gyor-Moson-Sopron"}'>Pereszteg</div>
<div class="option" data='{"value":"Pesitanya","state":"Gyor-Moson-Sopron"}'>Pesitanya</div>
<div class="option" data='{"value":"Peterhazapuszta","state":"Gyor-Moson-Sopron"}'>Peterhazapuszta</div>
<div class="option" data='{"value":"Petermajor","state":"Gyor-Moson-Sopron"}'>Petermajor</div>
<div class="option" data='{"value":"Petoctag","state":"Gyor-Moson-Sopron"}'>Petoctag</div>
<div class="option" data='{"value":"Petocztag","state":"Gyor-Moson-Sopron"}'>Petocztag</div>
<div class="option" data='{"value":"Petohaza","state":"Gyor-Moson-Sopron"}'>Petohaza</div>
<div class="option" data='{"value":"Piheno","state":"Gyor-Moson-Sopron"}'>Piheno</div>
<div class="option" data='{"value":"Pihenopuszta","state":"Gyor-Moson-Sopron"}'>Pihenopuszta</div>
<div class="option" data='{"value":"Pillingerpuszta","state":"Gyor-Moson-Sopron"}'>Pillingerpuszta</div>
<div class="option" data='{"value":"Pinnye","state":"Gyor-Moson-Sopron"}'>Pinnye</div>
<div class="option" data='{"value":"Pistakut","state":"Gyor-Moson-Sopron"}'>Pistakut</div>
<div class="option" data='{"value":"Piuspuszta","state":"Gyor-Moson-Sopron"}'>Piuspuszta</div>
<div class="option" data='{"value":"Piuszpuszta","state":"Gyor-Moson-Sopron"}'>Piuszpuszta</div>
<div class="option" data='{"value":"Pokvar","state":"Gyor-Moson-Sopron"}'>Pokvar</div>
<div class="option" data='{"value":"Pokvarpuszta","state":"Gyor-Moson-Sopron"}'>Pokvarpuszta</div>
<div class="option" data='{"value":"Potyond","state":"Gyor-Moson-Sopron"}'>Potyond</div>
<div class="option" data='{"value":"Pozsgaitanyak","state":"Gyor-Moson-Sopron"}'>Pozsgaitanyak</div>
<div class="option" data='{"value":"Prepostmajor","state":"Gyor-Moson-Sopron"}'>Prepostmajor</div>
<div class="option" data='{"value":"Presznyaktag","state":"Gyor-Moson-Sopron"}'>Presznyaktag</div>
<div class="option" data='{"value":"Priglitanya","state":"Gyor-Moson-Sopron"}'>Priglitanya</div>
<div class="option" data='{"value":"Puski","state":"Gyor-Moson-Sopron"}'>Puski</div>
<div class="option" data='{"value":"Puski Tanyak","state":"Gyor-Moson-Sopron"}'>Puski Tanyak</div>
<div class="option" data='{"value":"Puspokalap","state":"Gyor-Moson-Sopron"}'>Puspokalap</div>
<div class="option" data='{"value":"Pusztacsalad","state":"Gyor-Moson-Sopron"}'>Pusztacsalad</div>
<div class="option" data='{"value":"Pusztapatka","state":"Gyor-Moson-Sopron"}'>Pusztapatka</div>
<div class="option" data='{"value":"Pusztasomorja","state":"Gyor-Moson-Sopron"}'>Pusztasomorja</div>
<div class="option" data='{"value":"Raba Keczol","state":"Gyor-Moson-Sopron"}'>Raba Keczol</div>
<div class="option" data='{"value":"Rabacsanak","state":"Gyor-Moson-Sopron"}'>Rabacsanak</div>
<div class="option" data='{"value":"Rabacsecseny","state":"Gyor-Moson-Sopron"}'>Rabacsecseny</div>
<div class="option" data='{"value":"Rabakecol","state":"Gyor-Moson-Sopron"}'>Rabakecol</div>
<div class="option" data='{"value":"Rabapatona","state":"Gyor-Moson-Sopron"}'>Rabapatona</div>
<div class="option" data='{"value":"Rabapordany","state":"Gyor-Moson-Sopron"}'>Rabapordany</div>
<div class="option" data='{"value":"Rabaretmajor","state":"Gyor-Moson-Sopron"}'>Rabaretmajor</div>
<div class="option" data='{"value":"Rabasebes","state":"Gyor-Moson-Sopron"}'>Rabasebes</div>
<div class="option" data='{"value":"Rabaszentandras","state":"Gyor-Moson-Sopron"}'>Rabaszentandras</div>
<div class="option" data='{"value":"Rabaszentmihaly","state":"Gyor-Moson-Sopron"}'>Rabaszentmihaly</div>
<div class="option" data='{"value":"Rabaszentmiklos","state":"Gyor-Moson-Sopron"}'>Rabaszentmiklos</div>
<div class="option" data='{"value":"Rabaszovat","state":"Gyor-Moson-Sopron"}'>Rabaszovat</div>
<div class="option" data='{"value":"Rabatamasi","state":"Gyor-Moson-Sopron"}'>Rabatamasi</div>
<div class="option" data='{"value":"Rabaujfalu","state":"Gyor-Moson-Sopron"}'>Rabaujfalu</div>
<div class="option" data='{"value":"Rabcakapi","state":"Gyor-Moson-Sopron"}'>Rabcakapi</div>
<div class="option" data='{"value":"Rablmajor","state":"Gyor-Moson-Sopron"}'>Rablmajor</div>
<div class="option" data='{"value":"Rajka","state":"Gyor-Moson-Sopron"}'>Rajka</div>
<div class="option" data='{"value":"Rakoczitelep","state":"Gyor-Moson-Sopron"}'>Rakoczitelep</div>
<div class="option" data='{"value":"Rakoserei Tanya","state":"Gyor-Moson-Sopron"}'>Rakoserei Tanya</div>
<div class="option" data='{"value":"Ravazd","state":"Gyor-Moson-Sopron"}'>Ravazd</div>
<div class="option" data='{"value":"Redbergertanya","state":"Gyor-Moson-Sopron"}'>Redbergertanya</div>
<div class="option" data='{"value":"Reformatustanya","state":"Gyor-Moson-Sopron"}'>Reformatustanya</div>
<div class="option" data='{"value":"Rendekpuszta","state":"Gyor-Moson-Sopron"}'>Rendekpuszta</div>
<div class="option" data='{"value":"Repceszemere","state":"Gyor-Moson-Sopron"}'>Repceszemere</div>
<div class="option" data='{"value":"Repcevis","state":"Gyor-Moson-Sopron"}'>Repcevis</div>
<div class="option" data='{"value":"Retalap","state":"Gyor-Moson-Sopron"}'>Retalap</div>
<div class="option" data='{"value":"Rigopuszta","state":"Gyor-Moson-Sopron"}'>Rigopuszta</div>
<div class="option" data='{"value":"Rigotanya","state":"Gyor-Moson-Sopron"}'>Rigotanya</div>
<div class="option" data='{"value":"Rojtokmuzsaj","state":"Gyor-Moson-Sopron"}'>Rojtokmuzsaj</div>
<div class="option" data='{"value":"Romand","state":"Gyor-Moson-Sopron"}'>Romand</div>
<div class="option" data='{"value":"Ronafo","state":"Gyor-Moson-Sopron"}'>Ronafo</div>
<div class="option" data='{"value":"Rozaliamajor","state":"Gyor-Moson-Sopron"}'>Rozaliamajor</div>
<div class="option" data='{"value":"Rozsastelep","state":"Gyor-Moson-Sopron"}'>Rozsastelep</div>
<div class="option" data='{"value":"Ruzsitsmalom","state":"Gyor-Moson-Sopron"}'>Ruzsitsmalom</div>
<div class="option" data='{"value":"Sagikut","state":"Gyor-Moson-Sopron"}'>Sagikut</div>
<div class="option" data='{"value":"Sagitanya","state":"Gyor-Moson-Sopron"}'>Sagitanya</div>
<div class="option" data='{"value":"Samsontanya","state":"Gyor-Moson-Sopron"}'>Samsontanya</div>
<div class="option" data='{"value":"Sandorhaza","state":"Gyor-Moson-Sopron"}'>Sandorhaza</div>
<div class="option" data='{"value":"Sandorhazamajor","state":"Gyor-Moson-Sopron"}'>Sandorhazamajor</div>
<div class="option" data='{"value":"Sandorhazapuszta","state":"Gyor-Moson-Sopron"}'>Sandorhazapuszta</div>
<div class="option" data='{"value":"Sandorpuszta","state":"Gyor-Moson-Sopron"}'>Sandorpuszta</div>
<div class="option" data='{"value":"Saras","state":"Gyor-Moson-Sopron"}'>Saras</div>
<div class="option" data='{"value":"Saraspuszta","state":"Gyor-Moson-Sopron"}'>Saraspuszta</div>
<div class="option" data='{"value":"Sardos","state":"Gyor-Moson-Sopron"}'>Sardos</div>
<div class="option" data='{"value":"Sargahaz","state":"Gyor-Moson-Sopron"}'>Sargahaz</div>
<div class="option" data='{"value":"Sarkanymajor","state":"Gyor-Moson-Sopron"}'>Sarkanymajor</div>
<div class="option" data='{"value":"Sarlaymajor","state":"Gyor-Moson-Sopron"}'>Sarlaymajor</div>
<div class="option" data='{"value":"Saroltapuszta","state":"Gyor-Moson-Sopron"}'>Saroltapuszta</div>
<div class="option" data='{"value":"Sarrod","state":"Gyor-Moson-Sopron"}'>Sarrod</div>
<div class="option" data='{"value":"Sashegypuszta","state":"Gyor-Moson-Sopron"}'>Sashegypuszta</div>
<div class="option" data='{"value":"Scarabantia","state":"Gyor-Moson-Sopron"}'>Scarabantia</div>
<div class="option" data='{"value":"Scarbantia","state":"Gyor-Moson-Sopron"}'>Scarbantia</div>
<div class="option" data='{"value":"Scheidertag","state":"Gyor-Moson-Sopron"}'>Scheidertag</div>
<div class="option" data='{"value":"Scherbhaz","state":"Gyor-Moson-Sopron"}'>Scherbhaz</div>
<div class="option" data='{"value":"Selyemtelek","state":"Gyor-Moson-Sopron"}'>Selyemtelek</div>
<div class="option" data='{"value":"Selyemtelekpuszta","state":"Gyor-Moson-Sopron"}'>Selyemtelekpuszta</div>
<div class="option" data='{"value":"Semjensuka","state":"Gyor-Moson-Sopron"}'>Semjensuka</div>
<div class="option" data='{"value":"Serfenyosziget","state":"Gyor-Moson-Sopron"}'>Serfenyosziget</div>
<div class="option" data='{"value":"Sikator","state":"Gyor-Moson-Sopron"}'>Sikator</div>
<div class="option" data='{"value":"Sipostanya","state":"Gyor-Moson-Sopron"}'>Sipostanya</div>
<div class="option" data='{"value":"Sobor","state":"Gyor-Moson-Sopron"}'>Sobor</div>
<div class="option" data='{"value":"Sokoropatka","state":"Gyor-Moson-Sopron"}'>Sokoropatka</div>
<div class="option" data='{"value":"Solinka","state":"Gyor-Moson-Sopron"}'>Solinka</div>
<div class="option" data='{"value":"Solinko","state":"Gyor-Moson-Sopron"}'>Solinko</div>
<div class="option" data='{"value":"Somorjasziget","state":"Gyor-Moson-Sopron"}'>Somorjasziget</div>
<div class="option" data='{"value":"Sopron","state":"Gyor-Moson-Sopron"}'>Sopron</div>
<div class="option" data='{"value":"Sopronbanfalva","state":"Gyor-Moson-Sopron"}'>Sopronbanfalva</div>
<div class="option" data='{"value":"Sopronhorpacs","state":"Gyor-Moson-Sopron"}'>Sopronhorpacs</div>
<div class="option" data='{"value":"Soproni Puszta","state":"Gyor-Moson-Sopron"}'>Soproni Puszta</div>
<div class="option" data='{"value":"Sopronkohida","state":"Gyor-Moson-Sopron"}'>Sopronkohida</div>
<div class="option" data='{"value":"Sopronkovesd","state":"Gyor-Moson-Sopron"}'>Sopronkovesd</div>
<div class="option" data='{"value":"Sopronnemeti","state":"Gyor-Moson-Sopron"}'>Sopronnemeti</div>
<div class="option" data='{"value":"Sopronpuszta","state":"Gyor-Moson-Sopron"}'>Sopronpuszta</div>
<div class="option" data='{"value":"Sopronszecseny","state":"Gyor-Moson-Sopron"}'>Sopronszecseny</div>
<div class="option" data='{"value":"Sopter","state":"Gyor-Moson-Sopron"}'>Sopter</div>
<div class="option" data='{"value":"Sopteri Dulo","state":"Gyor-Moson-Sopron"}'>Sopteri Dulo</div>
<div class="option" data='{"value":"Sopterihatari Dulo","state":"Gyor-Moson-Sopron"}'>Sopterihatari Dulo</div>
<div class="option" data='{"value":"Sopterpuszta","state":"Gyor-Moson-Sopron"}'>Sopterpuszta</div>
<div class="option" data='{"value":"Soskutere","state":"Gyor-Moson-Sopron"}'>Soskutere</div>
<div class="option" data='{"value":"Soskuterepuszta","state":"Gyor-Moson-Sopron"}'>Soskuterepuszta</div>
<div class="option" data='{"value":"Sulysziget","state":"Gyor-Moson-Sopron"}'>Sulysziget</div>
<div class="option" data='{"value":"Suttor","state":"Gyor-Moson-Sopron"}'>Suttor</div>
<div class="option" data='{"value":"Szabohaz","state":"Gyor-Moson-Sopron"}'>Szabohaz</div>
<div class="option" data='{"value":"Szabotag","state":"Gyor-Moson-Sopron"}'>Szabotag</div>
<div class="option" data='{"value":"Szabotanya","state":"Gyor-Moson-Sopron"}'>Szabotanya</div>
<div class="option" data='{"value":"Szakony","state":"Gyor-Moson-Sopron"}'>Szakony</div>
<div class="option" data='{"value":"Szalaicsarda","state":"Gyor-Moson-Sopron"}'>Szalaicsarda</div>
<div class="option" data='{"value":"Szalaimajor","state":"Gyor-Moson-Sopron"}'>Szalaimajor</div>
<div class="option" data='{"value":"Szalaipuszta","state":"Gyor-Moson-Sopron"}'>Szalaipuszta</div>
<div class="option" data='{"value":"Szalaitanya","state":"Gyor-Moson-Sopron"}'>Szalaitanya</div>
<div class="option" data='{"value":"Szalaypuszta","state":"Gyor-Moson-Sopron"}'>Szalaypuszta</div>
<div class="option" data='{"value":"Szany","state":"Gyor-Moson-Sopron"}'>Szany</div>
<div class="option" data='{"value":"Szarfold","state":"Gyor-Moson-Sopron"}'>Szarfold</div>
<div class="option" data='{"value":"Szarkavar","state":"Gyor-Moson-Sopron"}'>Szarkavar</div>
<div class="option" data='{"value":"Szentimrepuszta","state":"Gyor-Moson-Sopron"}'>Szentimrepuszta</div>
<div class="option" data='{"value":"Szentimretelep","state":"Gyor-Moson-Sopron"}'>Szentimretelep</div>
<div class="option" data='{"value":"Szentistvanmajor","state":"Gyor-Moson-Sopron"}'>Szentistvanmajor</div>
<div class="option" data='{"value":"Szentistvanpuszta","state":"Gyor-Moson-Sopron"}'>Szentistvanpuszta</div>
<div class="option" data='{"value":"Szentkeresztpuszta","state":"Gyor-Moson-Sopron"}'>Szentkeresztpuszta</div>
<div class="option" data='{"value":"Szentkut","state":"Gyor-Moson-Sopron"}'>Szentkut</div>
<div class="option" data='{"value":"Szentkutpuszta","state":"Gyor-Moson-Sopron"}'>Szentkutpuszta</div>
<div class="option" data='{"value":"Szentpalpuszta","state":"Gyor-Moson-Sopron"}'>Szentpalpuszta</div>
<div class="option" data='{"value":"Szerecseny","state":"Gyor-Moson-Sopron"}'>Szerecseny</div>
<div class="option" data='{"value":"Szikramajor","state":"Gyor-Moson-Sopron"}'>Szikramajor</div>
<div class="option" data='{"value":"Szil","state":"Gyor-Moson-Sopron"}'>Szil</div>
<div class="option" data='{"value":"Szilagyimajor","state":"Gyor-Moson-Sopron"}'>Szilagyimajor</div>
<div class="option" data='{"value":"Szilagyitanya","state":"Gyor-Moson-Sopron"}'>Szilagyitanya</div>
<div class="option" data='{"value":"Szilipuszta","state":"Gyor-Moson-Sopron"}'>Szilipuszta</div>
<div class="option" data='{"value":"Szilsarkany","state":"Gyor-Moson-Sopron"}'>Szilsarkany</div>
<div class="option" data='{"value":"Szivattyutelep","state":"Gyor-Moson-Sopron"}'>Szivattyutelep</div>
<div class="option" data='{"value":"Szogye","state":"Gyor-Moson-Sopron"}'>Szogye</div>
<div class="option" data='{"value":"Szolgagyor","state":"Gyor-Moson-Sopron"}'>Szolgagyor</div>
<div class="option" data='{"value":"Szorpron","state":"Gyor-Moson-Sopron"}'>Szorpron</div>
<div class="option" data='{"value":"Szunyoghaz","state":"Gyor-Moson-Sopron"}'>Szunyoghaz</div>
<div class="option" data='{"value":"Szunyoghaza","state":"Gyor-Moson-Sopron"}'>Szunyoghaza</div>
<div class="option" data='{"value":"Taborhely","state":"Gyor-Moson-Sopron"}'>Taborhely</div>
<div class="option" data='{"value":"Tap","state":"Gyor-Moson-Sopron"}'>Tap</div>
<div class="option" data='{"value":"Taplany","state":"Gyor-Moson-Sopron"}'>Taplany</div>
<div class="option" data='{"value":"Taplanypuszta","state":"Gyor-Moson-Sopron"}'>Taplanypuszta</div>
<div class="option" data='{"value":"Tapszentmiklos","state":"Gyor-Moson-Sopron"}'>Tapszentmiklos</div>
<div class="option" data='{"value":"Tarjanpuszta","state":"Gyor-Moson-Sopron"}'>Tarjanpuszta</div>
<div class="option" data='{"value":"Tarnokreti","state":"Gyor-Moson-Sopron"}'>Tarnokreti</div>
<div class="option" data='{"value":"Tatarfoldimajor","state":"Gyor-Moson-Sopron"}'>Tatarfoldimajor</div>
<div class="option" data='{"value":"Tejfalusziget","state":"Gyor-Moson-Sopron"}'>Tejfalusziget</div>
<div class="option" data='{"value":"Tekepuszta","state":"Gyor-Moson-Sopron"}'>Tekepuszta</div>
<div class="option" data='{"value":"Tenyo","state":"Gyor-Moson-Sopron"}'>Tenyo</div>
<div class="option" data='{"value":"Terezmajor","state":"Gyor-Moson-Sopron"}'>Terezmajor</div>
<div class="option" data='{"value":"Termeloszovetkezeti Major","state":"Gyor-Moson-Sopron"}'>Termeloszovetkezeti Major</div>
<div class="option" data='{"value":"Tet","state":"Gyor-Moson-Sopron"}'>Tet</div>
<div class="option" data='{"value":"Tetlesvar","state":"Gyor-Moson-Sopron"}'>Tetlesvar</div>
<div class="option" data='{"value":"Thullnertanya","state":"Gyor-Moson-Sopron"}'>Thullnertanya</div>
<div class="option" data='{"value":"Tibormajor","state":"Gyor-Moson-Sopron"}'>Tibormajor</div>
<div class="option" data='{"value":"Tolos","state":"Gyor-Moson-Sopron"}'>Tolos</div>
<div class="option" data='{"value":"Tolosaljai Puszta","state":"Gyor-Moson-Sopron"}'>Tolosaljai Puszta</div>
<div class="option" data='{"value":"Tolosmajor","state":"Gyor-Moson-Sopron"}'>Tolosmajor</div>
<div class="option" data='{"value":"Toltestava","state":"Gyor-Moson-Sopron"}'>Toltestava</div>
<div class="option" data='{"value":"Torokmajor","state":"Gyor-Moson-Sopron"}'>Torokmajor</div>
<div class="option" data='{"value":"Tothtag","state":"Gyor-Moson-Sopron"}'>Tothtag</div>
<div class="option" data='{"value":"Tozeggyarmajor","state":"Gyor-Moson-Sopron"}'>Tozeggyarmajor</div>
<div class="option" data='{"value":"Tschurlmajor","state":"Gyor-Moson-Sopron"}'>Tschurlmajor</div>
<div class="option" data='{"value":"Tuskomajor","state":"Gyor-Moson-Sopron"}'>Tuskomajor</div>
<div class="option" data='{"value":"Tuskos","state":"Gyor-Moson-Sopron"}'>Tuskos</div>
<div class="option" data='{"value":"Tuskosmajor","state":"Gyor-Moson-Sopron"}'>Tuskosmajor</div>
<div class="option" data='{"value":"Tuskospuszta","state":"Gyor-Moson-Sopron"}'>Tuskospuszta</div>
<div class="option" data='{"value":"Ujballatag","state":"Gyor-Moson-Sopron"}'>Ujballatag</div>
<div class="option" data='{"value":"Ujhazhely","state":"Gyor-Moson-Sopron"}'>Ujhazhely</div>
<div class="option" data='{"value":"Ujhazmajor","state":"Gyor-Moson-Sopron"}'>Ujhazmajor</div>
<div class="option" data='{"value":"Ujhidmajor","state":"Gyor-Moson-Sopron"}'>Ujhidmajor</div>
<div class="option" data='{"value":"Ujker","state":"Gyor-Moson-Sopron"}'>Ujker</div>
<div class="option" data='{"value":"Ujmajor","state":"Gyor-Moson-Sopron"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujmalom","state":"Gyor-Moson-Sopron"}'>Ujmalom</div>
<div class="option" data='{"value":"Ujronafo","state":"Gyor-Moson-Sopron"}'>Ujronafo</div>
<div class="option" data='{"value":"Ujszajdamajor","state":"Gyor-Moson-Sopron"}'>Ujszajdamajor</div>
<div class="option" data='{"value":"Ujtagmajor","state":"Gyor-Moson-Sopron"}'>Ujtagmajor</div>
<div class="option" data='{"value":"Ujtelep","state":"Gyor-Moson-Sopron"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujudvar","state":"Gyor-Moson-Sopron"}'>Ujudvar</div>
<div class="option" data='{"value":"Und","state":"Gyor-Moson-Sopron"}'>Und</div>
<div class="option" data='{"value":"Urgehegy","state":"Gyor-Moson-Sopron"}'>Urgehegy</div>
<div class="option" data='{"value":"Urgemajor","state":"Gyor-Moson-Sopron"}'>Urgemajor</div>
<div class="option" data='{"value":"Vadalmas","state":"Gyor-Moson-Sopron"}'>Vadalmas</div>
<div class="option" data='{"value":"Vadosfa","state":"Gyor-Moson-Sopron"}'>Vadosfa</div>
<div class="option" data='{"value":"Vag","state":"Gyor-Moson-Sopron"}'>Vag</div>
<div class="option" data='{"value":"Vagohid","state":"Gyor-Moson-Sopron"}'>Vagohid</div>
<div class="option" data='{"value":"Vamos","state":"Gyor-Moson-Sopron"}'>Vamos</div>
<div class="option" data='{"value":"Vamosszabadi","state":"Gyor-Moson-Sopron"}'>Vamosszabadi</div>
<div class="option" data='{"value":"Vararosfalu","state":"Gyor-Moson-Sopron"}'>Vararosfalu</div>
<div class="option" data='{"value":"Varbalog","state":"Gyor-Moson-Sopron"}'>Varbalog</div>
<div class="option" data='{"value":"Vargatanya","state":"Gyor-Moson-Sopron"}'>Vargatanya</div>
<div class="option" data='{"value":"Vasarosfalu","state":"Gyor-Moson-Sopron"}'>Vasarosfalu</div>
<div class="option" data='{"value":"Vejke","state":"Gyor-Moson-Sopron"}'>Vejke</div>
<div class="option" data='{"value":"Vejkemajor","state":"Gyor-Moson-Sopron"}'>Vejkemajor</div>
<div class="option" data='{"value":"Venek","state":"Gyor-Moson-Sopron"}'>Venek</div>
<div class="option" data='{"value":"Veszkeny","state":"Gyor-Moson-Sopron"}'>Veszkeny</div>
<div class="option" data='{"value":"Veszpremvarsany","state":"Gyor-Moson-Sopron"}'>Veszpremvarsany</div>
<div class="option" data='{"value":"Vica","state":"Gyor-Moson-Sopron"}'>Vica</div>
<div class="option" data='{"value":"Villanytelep","state":"Gyor-Moson-Sopron"}'>Villanytelep</div>
<div class="option" data='{"value":"Vincefopuszta","state":"Gyor-Moson-Sopron"}'>Vincefopuszta</div>
<div class="option" data='{"value":"Violamajor","state":"Gyor-Moson-Sopron"}'>Violamajor</div>
<div class="option" data='{"value":"Violatag","state":"Gyor-Moson-Sopron"}'>Violatag</div>
<div class="option" data='{"value":"Viragosmajor","state":"Gyor-Moson-Sopron"}'>Viragosmajor</div>
<div class="option" data='{"value":"Viragtanya","state":"Gyor-Moson-Sopron"}'>Viragtanya</div>
<div class="option" data='{"value":"Viragvolgy","state":"Gyor-Moson-Sopron"}'>Viragvolgy</div>
<div class="option" data='{"value":"Visztamajor","state":"Gyor-Moson-Sopron"}'>Visztamajor</div>
<div class="option" data='{"value":"Vitezitelek","state":"Gyor-Moson-Sopron"}'>Vitezitelek</div>
<div class="option" data='{"value":"Viteztelek","state":"Gyor-Moson-Sopron"}'>Viteztelek</div>
<div class="option" data='{"value":"Vitnyed","state":"Gyor-Moson-Sopron"}'>Vitnyed</div>
<div class="option" data='{"value":"Vizmutelep","state":"Gyor-Moson-Sopron"}'>Vizmutelep</div>
<div class="option" data='{"value":"Vizmuvek","state":"Gyor-Moson-Sopron"}'>Vizmuvek</div>
<div class="option" data='{"value":"Volcsej","state":"Gyor-Moson-Sopron"}'>Volcsej</div>
<div class="option" data='{"value":"Vorosmajor","state":"Gyor-Moson-Sopron"}'>Vorosmajor</div>
<div class="option" data='{"value":"Vorostelep","state":"Gyor-Moson-Sopron"}'>Vorostelep</div>
<div class="option" data='{"value":"Wittmanntag","state":"Gyor-Moson-Sopron"}'>Wittmanntag</div>
<div class="option" data='{"value":"Zamolyitanya","state":"Gyor-Moson-Sopron"}'>Zamolyitanya</div>
<div class="option" data='{"value":"Zichypuszta","state":"Gyor-Moson-Sopron"}'>Zichypuszta</div>
<div class="option" data='{"value":"Zoldmajor","state":"Gyor-Moson-Sopron"}'>Zoldmajor</div>
<div class="option" data='{"value":"Zoltanhaza","state":"Gyor-Moson-Sopron"}'>Zoltanhaza</div>
<div class="option" data='{"value":"Zsebehaza","state":"Gyor-Moson-Sopron"}'>Zsebehaza</div>
<div class="option" data='{"value":"Zsejke","state":"Gyor-Moson-Sopron"}'>Zsejke</div>
<div class="option" data='{"value":"Zsejkepuszta","state":"Gyor-Moson-Sopron"}'>Zsejkepuszta</div>
<div class="option" id="option_end" data='{"value":"Zsira","state":"Gyor-Moson-Sopron"}'>Zsira</div>

