<div class="option" data='{"value":"Adand","state":"Somogy"}'>Adand</div>
<div class="option" data='{"value":"Aggato","state":"Somogy"}'>Aggato</div>
<div class="option" data='{"value":"Akacaslok","state":"Somogy"}'>Akacaslok</div>
<div class="option" data='{"value":"Alekszandrapuszta","state":"Somogy"}'>Alekszandrapuszta</div>
<div class="option" data='{"value":"Aligvarom","state":"Somogy"}'>Aligvarom</div>
<div class="option" data='{"value":"Aligvaromhegy","state":"Somogy"}'>Aligvaromhegy</div>
<div class="option" data='{"value":"Aligvaromi Szollo","state":"Somogy"}'>Aligvaromi Szollo</div>
<div class="option" data='{"value":"Alivar","state":"Somogy"}'>Alivar</div>
<div class="option" data='{"value":"Allaskut","state":"Somogy"}'>Allaskut</div>
<div class="option" data='{"value":"Almahegy","state":"Somogy"}'>Almahegy</div>
<div class="option" data='{"value":"Alsoberecska","state":"Somogy"}'>Alsoberecska</div>
<div class="option" data='{"value":"Alsobogat","state":"Somogy"}'>Alsobogat</div>
<div class="option" data='{"value":"Alsobogatpuszta","state":"Somogy"}'>Alsobogatpuszta</div>
<div class="option" data='{"value":"Alsocserpuszta","state":"Somogy"}'>Alsocserpuszta</div>
<div class="option" data='{"value":"Alsocsesztapuszta","state":"Somogy"}'>Alsocsesztapuszta</div>
<div class="option" data='{"value":"Alsofutyemajor","state":"Somogy"}'>Alsofutyemajor</div>
<div class="option" data='{"value":"Alsogaicspuszta","state":"Somogy"}'>Alsogaicspuszta</div>
<div class="option" data='{"value":"Alsogola","state":"Somogy"}'>Alsogola</div>
<div class="option" data='{"value":"Alsogolapuszta","state":"Somogy"}'>Alsogolapuszta</div>
<div class="option" data='{"value":"Alsogyocs","state":"Somogy"}'>Alsogyocs</div>
<div class="option" data='{"value":"Alsogyorgyos","state":"Somogy"}'>Alsogyorgyos</div>
<div class="option" data='{"value":"Alsogyotapuszta","state":"Somogy"}'>Alsogyotapuszta</div>
<div class="option" data='{"value":"Alsohegy","state":"Somogy"}'>Alsohegy</div>
<div class="option" data='{"value":"Alsohesteny","state":"Somogy"}'>Alsohesteny</div>
<div class="option" data='{"value":"Alsoheteny","state":"Somogy"}'>Alsoheteny</div>
<div class="option" data='{"value":"Alsok","state":"Somogy"}'>Alsok</div>
<div class="option" data='{"value":"Alsokolked","state":"Somogy"}'>Alsokolked</div>
<div class="option" data='{"value":"Alsomajor","state":"Somogy"}'>Alsomajor</div>
<div class="option" data='{"value":"Alsomalom","state":"Somogy"}'>Alsomalom</div>
<div class="option" data='{"value":"Alsomarosd","state":"Somogy"}'>Alsomarosd</div>
<div class="option" data='{"value":"Alsonyires","state":"Somogy"}'>Alsonyires</div>
<div class="option" data='{"value":"Alsopaskum","state":"Somogy"}'>Alsopaskum</div>
<div class="option" data='{"value":"Alsosegesd","state":"Somogy"}'>Alsosegesd</div>
<div class="option" data='{"value":"Alsoszollo","state":"Somogy"}'>Alsoszollo</div>
<div class="option" data='{"value":"Alsotapazd","state":"Somogy"}'>Alsotapazd</div>
<div class="option" data='{"value":"Alsoujhegy","state":"Somogy"}'>Alsoujhegy</div>
<div class="option" data='{"value":"Amaliapuszta","state":"Somogy"}'>Amaliapuszta</div>
<div class="option" data='{"value":"Andocs","state":"Somogy"}'>Andocs</div>
<div class="option" data='{"value":"Andormajor","state":"Somogy"}'>Andormajor</div>
<div class="option" data='{"value":"Annavolgy","state":"Somogy"}'>Annavolgy</div>
<div class="option" data='{"value":"Antalmajor","state":"Somogy"}'>Antalmajor</div>
<div class="option" data='{"value":"Antalpuszta","state":"Somogy"}'>Antalpuszta</div>
<div class="option" data='{"value":"Antalszallas","state":"Somogy"}'>Antalszallas</div>
<div class="option" data='{"value":"Aradpuszta","state":"Somogy"}'>Aradpuszta</div>
<div class="option" data='{"value":"Aranyosi Foldek","state":"Somogy"}'>Aranyosi Foldek</div>
<div class="option" data='{"value":"Aranyoskastely","state":"Somogy"}'>Aranyoskastely</div>
<div class="option" data='{"value":"Aranyospuszta","state":"Somogy"}'>Aranyospuszta</div>
<div class="option" data='{"value":"Asszonyvar","state":"Somogy"}'>Asszonyvar</div>
<div class="option" data='{"value":"Asszonyvari","state":"Somogy"}'>Asszonyvari</div>
<div class="option" data='{"value":"Aszohegy","state":"Somogy"}'>Aszohegy</div>
<div class="option" data='{"value":"Attala","state":"Somogy"}'>Attala</div>
<div class="option" data='{"value":"Avaspuszta","state":"Somogy"}'>Avaspuszta</div>
<div class="option" data='{"value":"Babocsa","state":"Somogy"}'>Babocsa</div>
<div class="option" data='{"value":"Babod Puszta","state":"Somogy"}'>Babod Puszta</div>
<div class="option" data='{"value":"Babodraki","state":"Somogy"}'>Babodraki</div>
<div class="option" data='{"value":"Babonymegyer","state":"Somogy"}'>Babonymegyer</div>
<div class="option" data='{"value":"Baglyashegy","state":"Somogy"}'>Baglyashegy</div>
<div class="option" data='{"value":"Bagohegypuszta","state":"Somogy"}'>Bagohegypuszta</div>
<div class="option" data='{"value":"Bagolai Erdoshaz","state":"Somogy"}'>Bagolai Erdoshaz</div>
<div class="option" data='{"value":"Bagolaierdohaz","state":"Somogy"}'>Bagolaierdohaz</div>
<div class="option" data='{"value":"Bagyaritanya","state":"Somogy"}'>Bagyaritanya</div>
<div class="option" data='{"value":"Bajaidulo","state":"Somogy"}'>Bajaidulo</div>
<div class="option" data='{"value":"Bajcihegy","state":"Somogy"}'>Bajcihegy</div>
<div class="option" data='{"value":"Bajnicska","state":"Somogy"}'>Bajnicska</div>
<div class="option" data='{"value":"Bajnicskatanya","state":"Somogy"}'>Bajnicskatanya</div>
<div class="option" data='{"value":"Bakhaza","state":"Somogy"}'>Bakhaza</div>
<div class="option" data='{"value":"Balaton Foldvar Furdotelep","state":"Somogy"}'>Balaton Foldvar Furdotelep</div>
<div class="option" data='{"value":"Balatonbereny","state":"Somogy"}'>Balatonbereny</div>
<div class="option" data='{"value":"Balatonboglar","state":"Somogy"}'>Balatonboglar</div>
<div class="option" data='{"value":"Balatonendred","state":"Somogy"}'>Balatonendred</div>
<div class="option" data='{"value":"Balatonendredi Tanyak","state":"Somogy"}'>Balatonendredi Tanyak</div>
<div class="option" data='{"value":"Balatonfenyves","state":"Somogy"}'>Balatonfenyves</div>
<div class="option" data='{"value":"Balatonfoldvar","state":"Somogy"}'>Balatonfoldvar</div>
<div class="option" data='{"value":"Balatonkeresztur","state":"Somogy"}'>Balatonkeresztur</div>
<div class="option" data='{"value":"Balatonkiliti","state":"Somogy"}'>Balatonkiliti</div>
<div class="option" data='{"value":"Balatonlelle","state":"Somogy"}'>Balatonlelle</div>
<div class="option" data='{"value":"Balatonmariafurdo","state":"Somogy"}'>Balatonmariafurdo</div>
<div class="option" data='{"value":"Balatonoszod","state":"Somogy"}'>Balatonoszod</div>
<div class="option" data='{"value":"Balatonsomos","state":"Somogy"}'>Balatonsomos</div>
<div class="option" data='{"value":"Balatonszabadi","state":"Somogy"}'>Balatonszabadi</div>
<div class="option" data='{"value":"Balatonszabadi Furdotelep","state":"Somogy"}'>Balatonszabadi Furdotelep</div>
<div class="option" data='{"value":"Balatonszarszo","state":"Somogy"}'>Balatonszarszo</div>
<div class="option" data='{"value":"Balatonszemes","state":"Somogy"}'>Balatonszemes</div>
<div class="option" data='{"value":"Balatonszentgyorgy","state":"Somogy"}'>Balatonszentgyorgy</div>
<div class="option" data='{"value":"Balatonujhely","state":"Somogy"}'>Balatonujhely</div>
<div class="option" data='{"value":"Balatonujlak","state":"Somogy"}'>Balatonujlak</div>
<div class="option" data='{"value":"Balatonzamardi","state":"Somogy"}'>Balatonzamardi</div>
<div class="option" data='{"value":"Balazstanya","state":"Somogy"}'>Balazstanya</div>
<div class="option" data='{"value":"Balvanyos","state":"Somogy"}'>Balvanyos</div>
<div class="option" data='{"value":"Banomhegy","state":"Somogy"}'>Banomhegy</div>
<div class="option" data='{"value":"Banomhegyszollo","state":"Somogy"}'>Banomhegyszollo</div>
<div class="option" data='{"value":"Banya","state":"Somogy"}'>Banya</div>
<div class="option" data='{"value":"Banyaitanya","state":"Somogy"}'>Banyaitanya</div>
<div class="option" data='{"value":"Banyaszo","state":"Somogy"}'>Banyaszo</div>
<div class="option" data='{"value":"Baranyjaras","state":"Somogy"}'>Baranyjaras</div>
<div class="option" data='{"value":"Barapuszta","state":"Somogy"}'>Barapuszta</div>
<div class="option" data='{"value":"Baratipuszta","state":"Somogy"}'>Baratipuszta</div>
<div class="option" data='{"value":"Baratok","state":"Somogy"}'>Baratok</div>
<div class="option" data='{"value":"Barcs","state":"Somogy"}'>Barcs</div>
<div class="option" data='{"value":"Bardibukk","state":"Somogy"}'>Bardibukk</div>
<div class="option" data='{"value":"Bardudvarnok","state":"Somogy"}'>Bardudvarnok</div>
<div class="option" data='{"value":"Baripuszta","state":"Somogy"}'>Baripuszta</div>
<div class="option" data='{"value":"Baromfitelep","state":"Somogy"}'>Baromfitelep</div>
<div class="option" data='{"value":"Bartko","state":"Somogy"}'>Bartko</div>
<div class="option" data='{"value":"Batatanya","state":"Somogy"}'>Batatanya</div>
<div class="option" data='{"value":"Bate","state":"Somogy"}'>Bate</div>
<div class="option" data='{"value":"Batehegy","state":"Somogy"}'>Batehegy</div>
<div class="option" data='{"value":"Battyanpuszta","state":"Somogy"}'>Battyanpuszta</div>
<div class="option" data='{"value":"Battyanyimajor","state":"Somogy"}'>Battyanyimajor</div>
<div class="option" data='{"value":"Bedegker","state":"Somogy"}'>Bedegker</div>
<div class="option" data='{"value":"Bedegpuszta","state":"Somogy"}'>Bedegpuszta</div>
<div class="option" data='{"value":"Belahazapuszta","state":"Somogy"}'>Belahazapuszta</div>
<div class="option" data='{"value":"Belamajor","state":"Somogy"}'>Belamajor</div>
<div class="option" data='{"value":"Belavar","state":"Somogy"}'>Belavar</div>
<div class="option" data='{"value":"Beleg","state":"Somogy"}'>Beleg</div>
<div class="option" data='{"value":"Belmajor","state":"Somogy"}'>Belmajor</div>
<div class="option" data='{"value":"Bendekpuszta","state":"Somogy"}'>Bendekpuszta</div>
<div class="option" data='{"value":"Bendepuszta","state":"Somogy"}'>Bendepuszta</div>
<div class="option" data='{"value":"Berci Hegy","state":"Somogy"}'>Berci Hegy</div>
<div class="option" data='{"value":"Berencsepuszta","state":"Somogy"}'>Berencsepuszta</div>
<div class="option" data='{"value":"Bereny Puszta","state":"Somogy"}'>Bereny Puszta</div>
<div class="option" data='{"value":"Bertalanmajor","state":"Somogy"}'>Bertalanmajor</div>
<div class="option" data='{"value":"Bertalanpuszta","state":"Somogy"}'>Bertalanpuszta</div>
<div class="option" data='{"value":"Berzence","state":"Somogy"}'>Berzence</div>
<div class="option" data='{"value":"Besliahegy","state":"Somogy"}'>Besliahegy</div>
<div class="option" data='{"value":"Bezeredypuszta","state":"Somogy"}'>Bezeredypuszta</div>
<div class="option" data='{"value":"Birkahazmajor","state":"Somogy"}'>Birkahazmajor</div>
<div class="option" data='{"value":"Birkamajor","state":"Somogy"}'>Birkamajor</div>
<div class="option" data='{"value":"Birkashazimajor","state":"Somogy"}'>Birkashazimajor</div>
<div class="option" data='{"value":"Bitkafalui Tanyak","state":"Somogy"}'>Bitkafalui Tanyak</div>
<div class="option" data='{"value":"Bize","state":"Somogy"}'>Bize</div>
<div class="option" data='{"value":"Bocorpuszta","state":"Somogy"}'>Bocorpuszta</div>
<div class="option" data='{"value":"Boditanya","state":"Somogy"}'>Boditanya</div>
<div class="option" data='{"value":"Bodocok","state":"Somogy"}'>Bodocok</div>
<div class="option" data='{"value":"Bodocokpuszta","state":"Somogy"}'>Bodocokpuszta</div>
<div class="option" data='{"value":"Bodrog","state":"Somogy"}'>Bodrog</div>
<div class="option" data='{"value":"Bodvica","state":"Somogy"}'>Bodvica</div>
<div class="option" data='{"value":"Boglarlelle","state":"Somogy"}'>Boglarlelle</div>
<div class="option" data='{"value":"Bohonye","state":"Somogy"}'>Bohonye</div>
<div class="option" data='{"value":"Bolhas","state":"Somogy"}'>Bolhas</div>
<div class="option" data='{"value":"Bolho","state":"Somogy"}'>Bolho</div>
<div class="option" data='{"value":"Bonnya","state":"Somogy"}'>Bonnya</div>
<div class="option" data='{"value":"Bonnyapuszta","state":"Somogy"}'>Bonnyapuszta</div>
<div class="option" data='{"value":"Borbelytanya","state":"Somogy"}'>Borbelytanya</div>
<div class="option" data='{"value":"Boronka","state":"Somogy"}'>Boronka</div>
<div class="option" data='{"value":"Borzasmajor","state":"Somogy"}'>Borzasmajor</div>
<div class="option" data='{"value":"Borzaspuszta","state":"Somogy"}'>Borzaspuszta</div>
<div class="option" data='{"value":"Boszenfa","state":"Somogy"}'>Boszenfa</div>
<div class="option" data='{"value":"Boszintotanya","state":"Somogy"}'>Boszintotanya</div>
<div class="option" data='{"value":"Botapuszta","state":"Somogy"}'>Botapuszta</div>
<div class="option" data='{"value":"Bozsokertidulo","state":"Somogy"}'>Bozsokertidulo</div>
<div class="option" data='{"value":"Bukkpuszta","state":"Somogy"}'>Bukkpuszta</div>
<div class="option" data='{"value":"Bukut","state":"Somogy"}'>Bukut</div>
<div class="option" data='{"value":"Bussu","state":"Somogy"}'>Bussu</div>
<div class="option" data='{"value":"Busvar","state":"Somogy"}'>Busvar</div>
<div class="option" data='{"value":"Busvari Orhaz","state":"Somogy"}'>Busvari Orhaz</div>
<div class="option" data='{"value":"Buvaritanya","state":"Somogy"}'>Buvaritanya</div>
<div class="option" data='{"value":"Buzsak","state":"Somogy"}'>Buzsak</div>
<div class="option" data='{"value":"Cegledi Tanyak","state":"Somogy"}'>Cegledi Tanyak</div>
<div class="option" data='{"value":"Ciframalom","state":"Somogy"}'>Ciframalom</div>
<div class="option" data='{"value":"Ciframalompuszta","state":"Somogy"}'>Ciframalompuszta</div>
<div class="option" data='{"value":"Cilipuszta","state":"Somogy"}'>Cilipuszta</div>
<div class="option" data='{"value":"Cinegemajor","state":"Somogy"}'>Cinegemajor</div>
<div class="option" data='{"value":"Cinegepuszta","state":"Somogy"}'>Cinegepuszta</div>
<div class="option" data='{"value":"Ciperes","state":"Somogy"}'>Ciperes</div>
<div class="option" data='{"value":"Csabapuszta","state":"Somogy"}'>Csabapuszta</div>
<div class="option" data='{"value":"Csakany","state":"Somogy"}'>Csakany</div>
<div class="option" data='{"value":"Csakszegpuszta","state":"Somogy"}'>Csakszegpuszta</div>
<div class="option" data='{"value":"Csaktanya","state":"Somogy"}'>Csaktanya</div>
<div class="option" data='{"value":"Csaphegy","state":"Somogy"}'>Csaphegy</div>
<div class="option" data='{"value":"Csardamajor","state":"Somogy"}'>Csardamajor</div>
<div class="option" data='{"value":"Csardapuszta","state":"Somogy"}'>Csardapuszta</div>
<div class="option" data='{"value":"Csatartopuszta","state":"Somogy"}'>Csatartopuszta</div>
<div class="option" data='{"value":"Cseberkipuszta","state":"Somogy"}'>Cseberkipuszta</div>
<div class="option" data='{"value":"Csegepuszta","state":"Somogy"}'>Csegepuszta</div>
<div class="option" data='{"value":"Csegold","state":"Somogy"}'>Csegold</div>
<div class="option" data='{"value":"Csekepuszta","state":"Somogy"}'>Csekepuszta</div>
<div class="option" data='{"value":"Cser","state":"Somogy"}'>Cser</div>
<div class="option" data='{"value":"Cseralja","state":"Somogy"}'>Cseralja</div>
<div class="option" data='{"value":"Cserebokpuszta","state":"Somogy"}'>Cserebokpuszta</div>
<div class="option" data='{"value":"Cserenfa","state":"Somogy"}'>Cserenfa</div>
<div class="option" data='{"value":"Cserenypuszta","state":"Somogy"}'>Cserenypuszta</div>
<div class="option" data='{"value":"Cserepespuszta","state":"Somogy"}'>Cserepespuszta</div>
<div class="option" data='{"value":"Cserfekves","state":"Somogy"}'>Cserfekves</div>
<div class="option" data='{"value":"Cserfekvesmajor","state":"Somogy"}'>Cserfekvesmajor</div>
<div class="option" data='{"value":"Cserhatpuszta","state":"Somogy"}'>Cserhatpuszta</div>
<div class="option" data='{"value":"Cseriakol","state":"Somogy"}'>Cseriakol</div>
<div class="option" data='{"value":"Cserihegy","state":"Somogy"}'>Cserihegy</div>
<div class="option" data='{"value":"Cserimajor","state":"Somogy"}'>Cserimajor</div>
<div class="option" data='{"value":"Cseripuszta","state":"Somogy"}'>Cseripuszta</div>
<div class="option" data='{"value":"Csermajor","state":"Somogy"}'>Csermajor</div>
<div class="option" data='{"value":"Csermanyihegy","state":"Somogy"}'>Csermanyihegy</div>
<div class="option" data='{"value":"Cserpuszta","state":"Somogy"}'>Cserpuszta</div>
<div class="option" data='{"value":"Csertelek","state":"Somogy"}'>Csertelek</div>
<div class="option" data='{"value":"Cseszme Puszta","state":"Somogy"}'>Cseszme Puszta</div>
<div class="option" data='{"value":"Cseszmemajor","state":"Somogy"}'>Cseszmemajor</div>
<div class="option" data='{"value":"Csibehegypuszta","state":"Somogy"}'>Csibehegypuszta</div>
<div class="option" data='{"value":"Csicsopuszta","state":"Somogy"}'>Csicsopuszta</div>
<div class="option" data='{"value":"Csigevar","state":"Somogy"}'>Csigevar</div>
<div class="option" data='{"value":"Csikoshaz","state":"Somogy"}'>Csikoshaz</div>
<div class="option" data='{"value":"Csikoshaza","state":"Somogy"}'>Csikoshaza</div>
<div class="option" data='{"value":"Csikotapuszta","state":"Somogy"}'>Csikotapuszta</div>
<div class="option" data='{"value":"Csillagcsarda","state":"Somogy"}'>Csillagcsarda</div>
<div class="option" data='{"value":"Csillagmajor","state":"Somogy"}'>Csillagmajor</div>
<div class="option" data='{"value":"Csillagpuszta","state":"Somogy"}'>Csillagpuszta</div>
<div class="option" data='{"value":"Csinapuszta","state":"Somogy"}'>Csinapuszta</div>
<div class="option" data='{"value":"Csiszarhegy","state":"Somogy"}'>Csiszarhegy</div>
<div class="option" data='{"value":"Csisztapuszta","state":"Somogy"}'>Csisztapuszta</div>
<div class="option" data='{"value":"Csokoly","state":"Somogy"}'>Csokoly</div>
<div class="option" data='{"value":"Csokonyavisonta","state":"Somogy"}'>Csokonyavisonta</div>
<div class="option" data='{"value":"Csokonyavisontai Tanya","state":"Somogy"}'>Csokonyavisontai Tanya</div>
<div class="option" data='{"value":"Csoma","state":"Somogy"}'>Csoma</div>
<div class="option" data='{"value":"Csomastanya","state":"Somogy"}'>Csomastanya</div>
<div class="option" data='{"value":"Csombard","state":"Somogy"}'>Csombard</div>
<div class="option" data='{"value":"Csomend","state":"Somogy"}'>Csomend</div>
<div class="option" data='{"value":"Csonkakotanya","state":"Somogy"}'>Csonkakotanya</div>
<div class="option" data='{"value":"Csoprond","state":"Somogy"}'>Csoprond</div>
<div class="option" data='{"value":"Csorbalok","state":"Somogy"}'>Csorbalok</div>
<div class="option" data='{"value":"Csordastanya","state":"Somogy"}'>Csordastanya</div>
<div class="option" data='{"value":"Csurgo","state":"Somogy"}'>Csurgo</div>
<div class="option" data='{"value":"Csurgonagymarton","state":"Somogy"}'>Csurgonagymarton</div>
<div class="option" data='{"value":"Daralomalom","state":"Somogy"}'>Daralomalom</div>
<div class="option" data='{"value":"Darany","state":"Somogy"}'>Darany</div>
<div class="option" data='{"value":"Daranypuszta","state":"Somogy"}'>Daranypuszta</div>
<div class="option" data='{"value":"Darvaspuszta","state":"Somogy"}'>Darvaspuszta</div>
<div class="option" data='{"value":"Davodpuszta","state":"Somogy"}'>Davodpuszta</div>
<div class="option" data='{"value":"Demjenpuszta","state":"Somogy"}'>Demjenpuszta</div>
<div class="option" data='{"value":"Deneskastely","state":"Somogy"}'>Deneskastely</div>
<div class="option" data='{"value":"Denesmajor","state":"Somogy"}'>Denesmajor</div>
<div class="option" data='{"value":"Dennapuszta","state":"Somogy"}'>Dennapuszta</div>
<div class="option" data='{"value":"Deshida","state":"Somogy"}'>Deshida</div>
<div class="option" data='{"value":"Deshidai Orhaz","state":"Somogy"}'>Deshidai Orhaz</div>
<div class="option" data='{"value":"Devenyitanya","state":"Somogy"}'>Devenyitanya</div>
<div class="option" data='{"value":"Dios","state":"Somogy"}'>Dios</div>
<div class="option" data='{"value":"Diospuszta","state":"Somogy"}'>Diospuszta</div>
<div class="option" data='{"value":"Diostelep","state":"Somogy"}'>Diostelep</div>
<div class="option" data='{"value":"Diosvolgymajor","state":"Somogy"}'>Diosvolgymajor</div>
<div class="option" data='{"value":"Dobontapuszta","state":"Somogy"}'>Dobontapuszta</div>
<div class="option" data='{"value":"Dobrogpuszta","state":"Somogy"}'>Dobrogpuszta</div>
<div class="option" data='{"value":"Dravagardony","state":"Somogy"}'>Dravagardony</div>
<div class="option" data='{"value":"Dravaszentes","state":"Somogy"}'>Dravaszentes</div>
<div class="option" data='{"value":"Dravatamasi","state":"Somogy"}'>Dravatamasi</div>
<div class="option" data='{"value":"Dreschertanya","state":"Somogy"}'>Dreschertanya</div>
<div class="option" data='{"value":"Ebedvesztopuszta","state":"Somogy"}'>Ebedvesztopuszta</div>
<div class="option" data='{"value":"Ebhegy","state":"Somogy"}'>Ebhegy</div>
<div class="option" data='{"value":"Ecseny","state":"Somogy"}'>Ecseny</div>
<div class="option" data='{"value":"Edde","state":"Somogy"}'>Edde</div>
<div class="option" data='{"value":"Eger","state":"Somogy"}'>Eger</div>
<div class="option" data='{"value":"Emlekmajor","state":"Somogy"}'>Emlekmajor</div>
<div class="option" data='{"value":"Emmatanya","state":"Somogy"}'>Emmatanya</div>
<div class="option" data='{"value":"Erdocsokonya","state":"Somogy"}'>Erdocsokonya</div>
<div class="option" data='{"value":"Erdoi Major","state":"Somogy"}'>Erdoi Major</div>
<div class="option" data='{"value":"Erdomajor","state":"Somogy"}'>Erdomajor</div>
<div class="option" data='{"value":"Erdoshaz","state":"Somogy"}'>Erdoshaz</div>
<div class="option" data='{"value":"Erosmajor","state":"Somogy"}'>Erosmajor</div>
<div class="option" data='{"value":"Erzsebetpuszta","state":"Somogy"}'>Erzsebetpuszta</div>
<div class="option" data='{"value":"Fancsihegy","state":"Somogy"}'>Fancsihegy</div>
<div class="option" data='{"value":"Fanimajor","state":"Somogy"}'>Fanimajor</div>
<div class="option" data='{"value":"Faragotanya","state":"Somogy"}'>Faragotanya</div>
<div class="option" data='{"value":"Farkaspuszta","state":"Somogy"}'>Farkaspuszta</div>
<div class="option" data='{"value":"Fazekasdencs","state":"Somogy"}'>Fazekasdencs</div>
<div class="option" data='{"value":"Feherbezseny","state":"Somogy"}'>Feherbezseny</div>
<div class="option" data='{"value":"Feheregyhazapuszta","state":"Somogy"}'>Feheregyhazapuszta</div>
<div class="option" data='{"value":"Feherpart","state":"Somogy"}'>Feherpart</div>
<div class="option" data='{"value":"Feketebezseny","state":"Somogy"}'>Feketebezseny</div>
<div class="option" data='{"value":"Feketepuszta","state":"Somogy"}'>Feketepuszta</div>
<div class="option" data='{"value":"Feljarodulo","state":"Somogy"}'>Feljarodulo</div>
<div class="option" data='{"value":"Felsoagazaspuszta","state":"Somogy"}'>Felsoagazaspuszta</div>
<div class="option" data='{"value":"Felsoakol","state":"Somogy"}'>Felsoakol</div>
<div class="option" data='{"value":"Felsobendek","state":"Somogy"}'>Felsobendek</div>
<div class="option" data='{"value":"Felsoberecska","state":"Somogy"}'>Felsoberecska</div>
<div class="option" data='{"value":"Felsobogat","state":"Somogy"}'>Felsobogat</div>
<div class="option" data='{"value":"Felsobogatpuszta","state":"Somogy"}'>Felsobogatpuszta</div>
<div class="option" data='{"value":"Felsocserpuszta","state":"Somogy"}'>Felsocserpuszta</div>
<div class="option" data='{"value":"Felsocsesztapuszta","state":"Somogy"}'>Felsocsesztapuszta</div>
<div class="option" data='{"value":"Felsoerzsebetpuszta","state":"Somogy"}'>Felsoerzsebetpuszta</div>
<div class="option" data='{"value":"Felsofutyemajor","state":"Somogy"}'>Felsofutyemajor</div>
<div class="option" data='{"value":"Felsogaicspuszta","state":"Somogy"}'>Felsogaicspuszta</div>
<div class="option" data='{"value":"Felsogola","state":"Somogy"}'>Felsogola</div>
<div class="option" data='{"value":"Felsogyocs","state":"Somogy"}'>Felsogyocs</div>
<div class="option" data='{"value":"Felsogyorgyos","state":"Somogy"}'>Felsogyorgyos</div>
<div class="option" data='{"value":"Felsogyotapuszta","state":"Somogy"}'>Felsogyotapuszta</div>
<div class="option" data='{"value":"Felsohegy","state":"Somogy"}'>Felsohegy</div>
<div class="option" data='{"value":"Felsohek","state":"Somogy"}'>Felsohek</div>
<div class="option" data='{"value":"Felsoheteny","state":"Somogy"}'>Felsoheteny</div>
<div class="option" data='{"value":"Felsokakpuszta","state":"Somogy"}'>Felsokakpuszta</div>
<div class="option" data='{"value":"Felsokolked","state":"Somogy"}'>Felsokolked</div>
<div class="option" data='{"value":"Felsomajor","state":"Somogy"}'>Felsomajor</div>
<div class="option" data='{"value":"Felsomalom","state":"Somogy"}'>Felsomalom</div>
<div class="option" data='{"value":"Felsomocsolad","state":"Somogy"}'>Felsomocsolad</div>
<div class="option" data='{"value":"Felsonyires","state":"Somogy"}'>Felsonyires</div>
<div class="option" data='{"value":"Felsonyirespuszta","state":"Somogy"}'>Felsonyirespuszta</div>
<div class="option" data='{"value":"Felsopaskum","state":"Somogy"}'>Felsopaskum</div>
<div class="option" data='{"value":"Felsopoczapuszta","state":"Somogy"}'>Felsopoczapuszta</div>
<div class="option" data='{"value":"Felsopuszta","state":"Somogy"}'>Felsopuszta</div>
<div class="option" data='{"value":"Felsosegesd","state":"Somogy"}'>Felsosegesd</div>
<div class="option" data='{"value":"Felsoszollo","state":"Somogy"}'>Felsoszollo</div>
<div class="option" data='{"value":"Felsotapazd","state":"Somogy"}'>Felsotapazd</div>
<div class="option" data='{"value":"Felsozsitfa","state":"Somogy"}'>Felsozsitfa</div>
<div class="option" data='{"value":"Ferenctelep","state":"Somogy"}'>Ferenctelep</div>
<div class="option" data='{"value":"Feszerlakpuszta","state":"Somogy"}'>Feszerlakpuszta</div>
<div class="option" data='{"value":"Fiad","state":"Somogy"}'>Fiad</div>
<div class="option" data='{"value":"Fischerpuszta","state":"Somogy"}'>Fischerpuszta</div>
<div class="option" data='{"value":"Fokivolgy","state":"Somogy"}'>Fokivolgy</div>
<div class="option" data='{"value":"Foldhidpuszta","state":"Somogy"}'>Foldhidpuszta</div>
<div class="option" data='{"value":"Foldvar","state":"Somogy"}'>Foldvar</div>
<div class="option" data='{"value":"Foldvari","state":"Somogy"}'>Foldvari</div>
<div class="option" data='{"value":"Foldvaritanya","state":"Somogy"}'>Foldvaritanya</div>
<div class="option" data='{"value":"Fono","state":"Somogy"}'>Fono</div>
<div class="option" data='{"value":"Fonyed","state":"Somogy"}'>Fonyed</div>
<div class="option" data='{"value":"Fonyod","state":"Somogy"}'>Fonyod</div>
<div class="option" data='{"value":"Frigyesytanya","state":"Somogy"}'>Frigyesytanya</div>
<div class="option" data='{"value":"Fulecspuszta","state":"Somogy"}'>Fulecspuszta</div>
<div class="option" data='{"value":"Furtelek","state":"Somogy"}'>Furtelek</div>
<div class="option" data='{"value":"Furtoshegy","state":"Somogy"}'>Furtoshegy</div>
<div class="option" data='{"value":"Gadacs","state":"Somogy"}'>Gadacs</div>
<div class="option" data='{"value":"Gadany","state":"Somogy"}'>Gadany</div>
<div class="option" data='{"value":"Gaj","state":"Somogy"}'>Gaj</div>
<div class="option" data='{"value":"Galabard","state":"Somogy"}'>Galabard</div>
<div class="option" data='{"value":"Galabardpuszta","state":"Somogy"}'>Galabardpuszta</div>
<div class="option" data='{"value":"Galambospuszta","state":"Somogy"}'>Galambospuszta</div>
<div class="option" data='{"value":"Galosfa","state":"Somogy"}'>Galosfa</div>
<div class="option" data='{"value":"Gamas","state":"Somogy"}'>Gamas</div>
<div class="option" data='{"value":"Gamastuskos","state":"Somogy"}'>Gamastuskos</div>
<div class="option" data='{"value":"Gamipuszta","state":"Somogy"}'>Gamipuszta</div>
<div class="option" data='{"value":"Ganajospuszta","state":"Somogy"}'>Ganajospuszta</div>
<div class="option" data='{"value":"Gardonyhegy","state":"Somogy"}'>Gardonyhegy</div>
<div class="option" data='{"value":"Gardonypuszta","state":"Somogy"}'>Gardonypuszta</div>
<div class="option" data='{"value":"Gardospuszta","state":"Somogy"}'>Gardospuszta</div>
<div class="option" data='{"value":"Gazlopuszta","state":"Somogy"}'>Gazlopuszta</div>
<div class="option" data='{"value":"Gellerttanya","state":"Somogy"}'>Gellerttanya</div>
<div class="option" data='{"value":"Gerebmalom","state":"Somogy"}'>Gerebmalom</div>
<div class="option" data='{"value":"Gerezd","state":"Somogy"}'>Gerezd</div>
<div class="option" data='{"value":"Gerezdpuszta","state":"Somogy"}'>Gerezdpuszta</div>
<div class="option" data='{"value":"Gerihegy","state":"Somogy"}'>Gerihegy</div>
<div class="option" data='{"value":"Gezapuszta","state":"Somogy"}'>Gezapuszta</div>
<div class="option" data='{"value":"Gige","state":"Somogy"}'>Gige</div>
<div class="option" data='{"value":"Gigei Szollo","state":"Somogy"}'>Gigei Szollo</div>
<div class="option" data='{"value":"Gilye","state":"Somogy"}'>Gilye</div>
<div class="option" data='{"value":"Glabarpuszta","state":"Somogy"}'>Glabarpuszta</div>
<div class="option" data='{"value":"Gog Tanya","state":"Somogy"}'>Gog Tanya</div>
<div class="option" data='{"value":"Gogtanyak","state":"Somogy"}'>Gogtanyak</div>
<div class="option" data='{"value":"Golle","state":"Somogy"}'>Golle</div>
<div class="option" data='{"value":"Gollenfa","state":"Somogy"}'>Gollenfa</div>
<div class="option" data='{"value":"Gombocpuszta","state":"Somogy"}'>Gombocpuszta</div>
<div class="option" data='{"value":"Gondoczdulo","state":"Somogy"}'>Gondoczdulo</div>
<div class="option" data='{"value":"Gorgeteg","state":"Somogy"}'>Gorgeteg</div>
<div class="option" data='{"value":"Gudova","state":"Somogy"}'>Gudova</div>
<div class="option" data='{"value":"Gusztavmajor","state":"Somogy"}'>Gusztavmajor</div>
<div class="option" data='{"value":"Gyaludpuszta","state":"Somogy"}'>Gyaludpuszta</div>
<div class="option" data='{"value":"Gyarmajor","state":"Somogy"}'>Gyarmajor</div>
<div class="option" data='{"value":"Gyekenyes","state":"Somogy"}'>Gyekenyes</div>
<div class="option" data='{"value":"Gyekenyeshegy","state":"Somogy"}'>Gyekenyeshegy</div>
<div class="option" data='{"value":"Gyertyamos","state":"Somogy"}'>Gyertyamos</div>
<div class="option" data='{"value":"Gyertyanos Akol","state":"Somogy"}'>Gyertyanos Akol</div>
<div class="option" data='{"value":"Gyertyanospuszta","state":"Somogy"}'>Gyertyanospuszta</div>
<div class="option" data='{"value":"Gyongyospuszta","state":"Somogy"}'>Gyongyospuszta</div>
<div class="option" data='{"value":"Gyongyostapazd","state":"Somogy"}'>Gyongyostapazd</div>
<div class="option" data='{"value":"Gyotapuszta","state":"Somogy"}'>Gyotapuszta</div>
<div class="option" data='{"value":"Gyugy","state":"Somogy"}'>Gyugy</div>
<div class="option" data='{"value":"Gyugypuszta","state":"Somogy"}'>Gyugypuszta</div>
<div class="option" data='{"value":"Gyuladtelep","state":"Somogy"}'>Gyuladtelep</div>
<div class="option" data='{"value":"Gyulapuszta","state":"Somogy"}'>Gyulapuszta</div>
<div class="option" data='{"value":"Hacs","state":"Somogy"}'>Hacs</div>
<div class="option" data='{"value":"Hajmas","state":"Somogy"}'>Hajmas</div>
<div class="option" data='{"value":"Halasgat","state":"Somogy"}'>Halasgat</div>
<div class="option" data='{"value":"Halasgatpuszta","state":"Somogy"}'>Halasgatpuszta</div>
<div class="option" data='{"value":"Halasitanya","state":"Somogy"}'>Halasitanya</div>
<div class="option" data='{"value":"Halasto","state":"Somogy"}'>Halasto</div>
<div class="option" data='{"value":"Halastoipuszta","state":"Somogy"}'>Halastoipuszta</div>
<div class="option" data='{"value":"Halastopuszta","state":"Somogy"}'>Halastopuszta</div>
<div class="option" data='{"value":"Halaszhaz","state":"Somogy"}'>Halaszhaz</div>
<div class="option" data='{"value":"Halaszopuszta","state":"Somogy"}'>Halaszopuszta</div>
<div class="option" data='{"value":"Halasztanya","state":"Somogy"}'>Halasztanya</div>
<div class="option" data='{"value":"Halasztelep","state":"Somogy"}'>Halasztelep</div>
<div class="option" data='{"value":"Hangyas","state":"Somogy"}'>Hangyas</div>
<div class="option" data='{"value":"Hangyasmal","state":"Somogy"}'>Hangyasmal</div>
<div class="option" data='{"value":"Harihegy","state":"Somogy"}'>Harihegy</div>
<div class="option" data='{"value":"Haromfa","state":"Somogy"}'>Haromfa</div>
<div class="option" data='{"value":"Haromhaz","state":"Somogy"}'>Haromhaz</div>
<div class="option" data='{"value":"Haromhazdulo","state":"Somogy"}'>Haromhazdulo</div>
<div class="option" data='{"value":"Harsanyszollo","state":"Somogy"}'>Harsanyszollo</div>
<div class="option" data='{"value":"Harsanyszolo","state":"Somogy"}'>Harsanyszolo</div>
<div class="option" data='{"value":"Harsaspuszta","state":"Somogy"}'>Harsaspuszta</div>
<div class="option" data='{"value":"Harserdo","state":"Somogy"}'>Harserdo</div>
<div class="option" data='{"value":"Harserdopuszta","state":"Somogy"}'>Harserdopuszta</div>
<div class="option" data='{"value":"Harserdotelep","state":"Somogy"}'>Harserdotelep</div>
<div class="option" data='{"value":"Hedrehely","state":"Somogy"}'>Hedrehely</div>
<div class="option" data='{"value":"Hegy","state":"Somogy"}'>Hegy</div>
<div class="option" data='{"value":"Hekut","state":"Somogy"}'>Hekut</div>
<div class="option" data='{"value":"Hekutpuszta","state":"Somogy"}'>Hekutpuszta</div>
<div class="option" data='{"value":"Hencse","state":"Somogy"}'>Hencse</div>
<div class="option" data='{"value":"Henesz","state":"Somogy"}'>Henesz</div>
<div class="option" data='{"value":"Heresznye","state":"Somogy"}'>Heresznye</div>
<div class="option" data='{"value":"Hetes","state":"Somogy"}'>Hetes</div>
<div class="option" data='{"value":"Hodoshat","state":"Somogy"}'>Hodoshat</div>
<div class="option" data='{"value":"Hodoshatihegy","state":"Somogy"}'>Hodoshatihegy</div>
<div class="option" data='{"value":"Hodospuszta","state":"Somogy"}'>Hodospuszta</div>
<div class="option" data='{"value":"Hokamalom","state":"Somogy"}'>Hokamalom</div>
<div class="option" data='{"value":"Hollad","state":"Somogy"}'>Hollad</div>
<div class="option" data='{"value":"Holyeghegy","state":"Somogy"}'>Holyeghegy</div>
<div class="option" data='{"value":"Homok","state":"Somogy"}'>Homok</div>
<div class="option" data='{"value":"Homokpuszta","state":"Somogy"}'>Homokpuszta</div>
<div class="option" data='{"value":"Homokszentgyorgy","state":"Somogy"}'>Homokszentgyorgy</div>
<div class="option" data='{"value":"Homokszollo","state":"Somogy"}'>Homokszollo</div>
<div class="option" data='{"value":"Horvatkut","state":"Somogy"}'>Horvatkut</div>
<div class="option" data='{"value":"Hossuviz","state":"Somogy"}'>Hossuviz</div>
<div class="option" data='{"value":"Hosszuhegy","state":"Somogy"}'>Hosszuhegy</div>
<div class="option" data='{"value":"Hosszuhegyalja","state":"Somogy"}'>Hosszuhegyalja</div>
<div class="option" data='{"value":"Hosszuviz","state":"Somogy"}'>Hosszuviz</div>
<div class="option" data='{"value":"Hoszsuhegy","state":"Somogy"}'>Hoszsuhegy</div>
<div class="option" data='{"value":"Hugahegy","state":"Somogy"}'>Hugahegy</div>
<div class="option" data='{"value":"Idapuszta","state":"Somogy"}'>Idapuszta</div>
<div class="option" data='{"value":"Igal","state":"Somogy"}'>Igal</div>
<div class="option" data='{"value":"Igalipuszta","state":"Somogy"}'>Igalipuszta</div>
<div class="option" data='{"value":"Igalpuszta","state":"Somogy"}'>Igalpuszta</div>
<div class="option" data='{"value":"Ignactelep","state":"Somogy"}'>Ignactelep</div>
<div class="option" data='{"value":"Iharos","state":"Somogy"}'>Iharos</div>
<div class="option" data='{"value":"Iharosbereny","state":"Somogy"}'>Iharosbereny</div>
<div class="option" data='{"value":"Illesmajor","state":"Somogy"}'>Illesmajor</div>
<div class="option" data='{"value":"Imredi","state":"Somogy"}'>Imredi</div>
<div class="option" data='{"value":"Imremajor","state":"Somogy"}'>Imremajor</div>
<div class="option" data='{"value":"Inampuszta","state":"Somogy"}'>Inampuszta</div>
<div class="option" data='{"value":"Ince","state":"Somogy"}'>Ince</div>
<div class="option" data='{"value":"Inke","state":"Somogy"}'>Inke</div>
<div class="option" data='{"value":"Inkelepled","state":"Somogy"}'>Inkelepled</div>
<div class="option" data='{"value":"Irenmajor","state":"Somogy"}'>Irenmajor</div>
<div class="option" data='{"value":"Irmamajor","state":"Somogy"}'>Irmamajor</div>
<div class="option" data='{"value":"Irmapuszta","state":"Somogy"}'>Irmapuszta</div>
<div class="option" data='{"value":"Istvandi","state":"Somogy"}'>Istvandi</div>
<div class="option" data='{"value":"Istvanvolgypuszta","state":"Somogy"}'>Istvanvolgypuszta</div>
<div class="option" data='{"value":"Ivanfaret","state":"Somogy"}'>Ivanfaret</div>
<div class="option" data='{"value":"Ivankapuszta","state":"Somogy"}'>Ivankapuszta</div>
<div class="option" data='{"value":"Jaba","state":"Somogy"}'>Jaba</div>
<div class="option" data='{"value":"Jabapuszta","state":"Somogy"}'>Jabapuszta</div>
<div class="option" data='{"value":"Jadipuszta","state":"Somogy"}'>Jadipuszta</div>
<div class="option" data='{"value":"Jaditanya","state":"Somogy"}'>Jaditanya</div>
<div class="option" data='{"value":"Jako","state":"Somogy"}'>Jako</div>
<div class="option" data='{"value":"Jamapuszta","state":"Somogy"}'>Jamapuszta</div>
<div class="option" data='{"value":"Jankovicskolked","state":"Somogy"}'>Jankovicskolked</div>
<div class="option" data='{"value":"Janoshazapuszta","state":"Somogy"}'>Janoshazapuszta</div>
<div class="option" data='{"value":"Janosmajor","state":"Somogy"}'>Janosmajor</div>
<div class="option" data='{"value":"Jazvinapuszta","state":"Somogy"}'>Jazvinapuszta</div>
<div class="option" data='{"value":"Jegfatelep","state":"Somogy"}'>Jegfatelep</div>
<div class="option" data='{"value":"Jolanka","state":"Somogy"}'>Jolanka</div>
<div class="option" data='{"value":"Jolantapuszta","state":"Somogy"}'>Jolantapuszta</div>
<div class="option" data='{"value":"Jozsapuszta","state":"Somogy"}'>Jozsapuszta</div>
<div class="option" data='{"value":"Jozsefmajor","state":"Somogy"}'>Jozsefmajor</div>
<div class="option" data='{"value":"Jozseftelep","state":"Somogy"}'>Jozseftelep</div>
<div class="option" data='{"value":"Juhaszpuszta","state":"Somogy"}'>Juhaszpuszta</div>
<div class="option" data='{"value":"Jut","state":"Somogy"}'>Jut</div>
<div class="option" data='{"value":"Juta","state":"Somogy"}'>Juta</div>
<div class="option" data='{"value":"Juti Puszta","state":"Somogy"}'>Juti Puszta</div>
<div class="option" data='{"value":"Jutompuszta","state":"Somogy"}'>Jutompuszta</div>
<div class="option" data='{"value":"Kadarkut","state":"Somogy"}'>Kadarkut</div>
<div class="option" data='{"value":"Kak","state":"Somogy"}'>Kak</div>
<div class="option" data='{"value":"Kakashegy","state":"Somogy"}'>Kakashegy</div>
<div class="option" data='{"value":"Kalistapuszta","state":"Somogy"}'>Kalistapuszta</div>
<div class="option" data='{"value":"Kalmacsa","state":"Somogy"}'>Kalmacsa</div>
<div class="option" data='{"value":"Kalmancsa","state":"Somogy"}'>Kalmancsa</div>
<div class="option" data='{"value":"Kalvaria","state":"Somogy"}'>Kalvaria</div>
<div class="option" data='{"value":"Kanizsaberek","state":"Somogy"}'>Kanizsaberek</div>
<div class="option" data='{"value":"Kanya","state":"Somogy"}'>Kanya</div>
<div class="option" data='{"value":"Kapolnahegy","state":"Somogy"}'>Kapolnahegy</div>
<div class="option" data='{"value":"Kapolnasvisnye","state":"Somogy"}'>Kapolnasvisnye</div>
<div class="option" data='{"value":"Kapoly","state":"Somogy"}'>Kapoly</div>
<div class="option" data='{"value":"Kapolyi Puszta","state":"Somogy"}'>Kapolyi Puszta</div>
<div class="option" data='{"value":"Kapolypuszta","state":"Somogy"}'>Kapolypuszta</div>
<div class="option" data='{"value":"Kaposdada","state":"Somogy"}'>Kaposdada</div>
<div class="option" data='{"value":"Kaposfo","state":"Somogy"}'>Kaposfo</div>
<div class="option" data='{"value":"Kaposfured","state":"Somogy"}'>Kaposfured</div>
<div class="option" data='{"value":"Kaposgyarmat","state":"Somogy"}'>Kaposgyarmat</div>
<div class="option" data='{"value":"Kaposhegy","state":"Somogy"}'>Kaposhegy</div>
<div class="option" data='{"value":"Kaposhomok","state":"Somogy"}'>Kaposhomok</div>
<div class="option" data='{"value":"Kaposkeresztur","state":"Somogy"}'>Kaposkeresztur</div>
<div class="option" data='{"value":"Kaposmero","state":"Somogy"}'>Kaposmero</div>
<div class="option" data='{"value":"Kapospula","state":"Somogy"}'>Kapospula</div>
<div class="option" data='{"value":"Kaposszentbenedek","state":"Somogy"}'>Kaposszentbenedek</div>
<div class="option" data='{"value":"Kaposszentjakab","state":"Somogy"}'>Kaposszentjakab</div>
<div class="option" data='{"value":"Kaposszeplak","state":"Somogy"}'>Kaposszeplak</div>
<div class="option" data='{"value":"Kaposszerdahely","state":"Somogy"}'>Kaposszerdahely</div>
<div class="option" data='{"value":"Kaposujlak","state":"Somogy"}'>Kaposujlak</div>
<div class="option" data='{"value":"Kaposvar","state":"Somogy"}'>Kaposvar</div>
<div class="option" data='{"value":"Kaptalanterebezd","state":"Somogy"}'>Kaptalanterebezd</div>
<div class="option" data='{"value":"Kara","state":"Somogy"}'>Kara</div>
<div class="option" data='{"value":"Karacsonypuszta","state":"Somogy"}'>Karacsonypuszta</div>
<div class="option" data='{"value":"Karad","state":"Somogy"}'>Karad</div>
<div class="option" data='{"value":"Karadi Erdo","state":"Somogy"}'>Karadi Erdo</div>
<div class="option" data='{"value":"Karaitanya","state":"Somogy"}'>Karaitanya</div>
<div class="option" data='{"value":"Karakut","state":"Somogy"}'>Karakut</div>
<div class="option" data='{"value":"Kardosfa","state":"Somogy"}'>Kardosfa</div>
<div class="option" data='{"value":"Kardosfapuszta","state":"Somogy"}'>Kardosfapuszta</div>
<div class="option" data='{"value":"Kasahegy","state":"Somogy"}'>Kasahegy</div>
<div class="option" data='{"value":"Kasipuszta","state":"Somogy"}'>Kasipuszta</div>
<div class="option" data='{"value":"Kastelykert","state":"Somogy"}'>Kastelykert</div>
<div class="option" data='{"value":"Kastelyosdombo","state":"Somogy"}'>Kastelyosdombo</div>
<div class="option" data='{"value":"Kaszopuszta","state":"Somogy"}'>Kaszopuszta</div>
<div class="option" data='{"value":"Katahegy","state":"Somogy"}'>Katahegy</div>
<div class="option" data='{"value":"Katalinmajor","state":"Somogy"}'>Katalinmajor</div>
<div class="option" data='{"value":"Katalinpuszta","state":"Somogy"}'>Katalinpuszta</div>
<div class="option" data='{"value":"Katyoilapos","state":"Somogy"}'>Katyoilapos</div>
<div class="option" data='{"value":"Kazsok","state":"Somogy"}'>Kazsok</div>
<div class="option" data='{"value":"Kazsok Puszta","state":"Somogy"}'>Kazsok Puszta</div>
<div class="option" data='{"value":"Kazsoki Tanyak","state":"Somogy"}'>Kazsoki Tanyak</div>
<div class="option" data='{"value":"Kekapuszta","state":"Somogy"}'>Kekapuszta</div>
<div class="option" data='{"value":"Keletikapolnashegy","state":"Somogy"}'>Keletikapolnashegy</div>
<div class="option" data='{"value":"Keletimajor","state":"Somogy"}'>Keletimajor</div>
<div class="option" data='{"value":"Keleviz","state":"Somogy"}'>Keleviz</div>
<div class="option" data='{"value":"Keneseihegy","state":"Somogy"}'>Keneseihegy</div>
<div class="option" data='{"value":"Keneszhegy","state":"Somogy"}'>Keneszhegy</div>
<div class="option" data='{"value":"Kercseliget","state":"Somogy"}'>Kercseliget</div>
<div class="option" data='{"value":"Kereki","state":"Somogy"}'>Kereki</div>
<div class="option" data='{"value":"Kerekiszollo","state":"Somogy"}'>Kerekiszollo</div>
<div class="option" data='{"value":"Kerekiszolo","state":"Somogy"}'>Kerekiszolo</div>
<div class="option" data='{"value":"Kerekpuszta","state":"Somogy"}'>Kerekpuszta</div>
<div class="option" data='{"value":"Keresztelymajor","state":"Somogy"}'>Keresztelymajor</div>
<div class="option" data='{"value":"Keresztfai Puszta","state":"Somogy"}'>Keresztfai Puszta</div>
<div class="option" data='{"value":"Kerpuszta","state":"Somogy"}'>Kerpuszta</div>
<div class="option" data='{"value":"Kertesztanya","state":"Somogy"}'>Kertesztanya</div>
<div class="option" data='{"value":"Kesellos","state":"Somogy"}'>Kesellos</div>
<div class="option" data='{"value":"Kesellosszollo","state":"Somogy"}'>Kesellosszollo</div>
<div class="option" data='{"value":"Kethely","state":"Somogy"}'>Kethely</div>
<div class="option" data='{"value":"Kethelyihegy","state":"Somogy"}'>Kethelyihegy</div>
<div class="option" data='{"value":"Kiralyrev","state":"Somogy"}'>Kiralyrev</div>
<div class="option" data='{"value":"Kis Puszta","state":"Somogy"}'>Kis Puszta</div>
<div class="option" data='{"value":"Kisasszond","state":"Somogy"}'>Kisasszond</div>
<div class="option" data='{"value":"Kisbabapuszta","state":"Somogy"}'>Kisbabapuszta</div>
<div class="option" data='{"value":"Kisbabod","state":"Somogy"}'>Kisbabod</div>
<div class="option" data='{"value":"Kisbajom","state":"Somogy"}'>Kisbajom</div>
<div class="option" data='{"value":"Kisbarapati","state":"Somogy"}'>Kisbarapati</div>
<div class="option" data='{"value":"Kisbartfapuszta","state":"Somogy"}'>Kisbartfapuszta</div>
<div class="option" data='{"value":"Kisbereny","state":"Somogy"}'>Kisbereny</div>
<div class="option" data='{"value":"Kisberki","state":"Somogy"}'>Kisberki</div>
<div class="option" data='{"value":"Kiscser","state":"Somogy"}'>Kiscser</div>
<div class="option" data='{"value":"Kisded","state":"Somogy"}'>Kisded</div>
<div class="option" data='{"value":"Kisdios","state":"Somogy"}'>Kisdios</div>
<div class="option" data='{"value":"Kisdiospuszta","state":"Somogy"}'>Kisdiospuszta</div>
<div class="option" data='{"value":"Kisecseny","state":"Somogy"}'>Kisecseny</div>
<div class="option" data='{"value":"Kisegres","state":"Somogy"}'>Kisegres</div>
<div class="option" data='{"value":"Kiserdopuszta","state":"Somogy"}'>Kiserdopuszta</div>
<div class="option" data='{"value":"Kisgatidulo","state":"Somogy"}'>Kisgatidulo</div>
<div class="option" data='{"value":"Kisgatpuszta","state":"Somogy"}'>Kisgatpuszta</div>
<div class="option" data='{"value":"Kisgyalan","state":"Somogy"}'>Kisgyalan</div>
<div class="option" data='{"value":"Kishacs","state":"Somogy"}'>Kishacs</div>
<div class="option" data='{"value":"Kishegy","state":"Somogy"}'>Kishegy</div>
<div class="option" data='{"value":"Kishegyszollo","state":"Somogy"}'>Kishegyszollo</div>
<div class="option" data='{"value":"Kishomok","state":"Somogy"}'>Kishomok</div>
<div class="option" data='{"value":"Kishomokpuszta","state":"Somogy"}'>Kishomokpuszta</div>
<div class="option" data='{"value":"Kisivanmajor","state":"Somogy"}'>Kisivanmajor</div>
<div class="option" data='{"value":"Kisivanpuszta","state":"Somogy"}'>Kisivanpuszta</div>
<div class="option" data='{"value":"Kiskanya","state":"Somogy"}'>Kiskanya</div>
<div class="option" data='{"value":"Kiskorpad","state":"Somogy"}'>Kiskorpad</div>
<div class="option" data='{"value":"Kiskustyan","state":"Somogy"}'>Kiskustyan</div>
<div class="option" data='{"value":"Kiskutitelek","state":"Somogy"}'>Kiskutitelek</div>
<div class="option" data='{"value":"Kispart","state":"Somogy"}'>Kispart</div>
<div class="option" data='{"value":"Kisperjes","state":"Somogy"}'>Kisperjes</div>
<div class="option" data='{"value":"Kispoczapuszta","state":"Somogy"}'>Kispoczapuszta</div>
<div class="option" data='{"value":"Kispuszta","state":"Somogy"}'>Kispuszta</div>
<div class="option" data='{"value":"Kisspuszta","state":"Somogy"}'>Kisspuszta</div>
<div class="option" data='{"value":"Kistarnoca","state":"Somogy"}'>Kistarnoca</div>
<div class="option" data='{"value":"Kistatarvar","state":"Somogy"}'>Kistatarvar</div>
<div class="option" data='{"value":"Kistikos","state":"Somogy"}'>Kistikos</div>
<div class="option" data='{"value":"Kistotvaros","state":"Somogy"}'>Kistotvaros</div>
<div class="option" data='{"value":"Kisvid","state":"Somogy"}'>Kisvid</div>
<div class="option" data='{"value":"Kisvidpuszta","state":"Somogy"}'>Kisvidpuszta</div>
<div class="option" data='{"value":"Kivadar","state":"Somogy"}'>Kivadar</div>
<div class="option" data='{"value":"Koblos","state":"Somogy"}'>Koblos</div>
<div class="option" data='{"value":"Kode","state":"Somogy"}'>Kode</div>
<div class="option" data='{"value":"Kokashegy","state":"Somogy"}'>Kokashegy</div>
<div class="option" data='{"value":"Kokenyespuszta","state":"Somogy"}'>Kokenyespuszta</div>
<div class="option" data='{"value":"Kokut","state":"Somogy"}'>Kokut</div>
<div class="option" data='{"value":"Kolesdpuszta","state":"Somogy"}'>Kolesdpuszta</div>
<div class="option" data='{"value":"Kolomperoscsarda","state":"Somogy"}'>Kolomperoscsarda</div>
<div class="option" data='{"value":"Komlosd","state":"Somogy"}'>Komlosd</div>
<div class="option" data='{"value":"Kondashalom","state":"Somogy"}'>Kondashalom</div>
<div class="option" data='{"value":"Kondaszhalom","state":"Somogy"}'>Kondaszhalom</div>
<div class="option" data='{"value":"Koparpuszta","state":"Somogy"}'>Koparpuszta</div>
<div class="option" data='{"value":"Kopaszhegy","state":"Somogy"}'>Kopaszhegy</div>
<div class="option" data='{"value":"Kopi Puszta","state":"Somogy"}'>Kopi Puszta</div>
<div class="option" data='{"value":"Koplalo","state":"Somogy"}'>Koplalo</div>
<div class="option" data='{"value":"Koppanymegyer","state":"Somogy"}'>Koppanymegyer</div>
<div class="option" data='{"value":"Koptanya","state":"Somogy"}'>Koptanya</div>
<div class="option" data='{"value":"Korkemence","state":"Somogy"}'>Korkemence</div>
<div class="option" data='{"value":"Koroshegy","state":"Somogy"}'>Koroshegy</div>
<div class="option" data='{"value":"Kortonyeibukk","state":"Somogy"}'>Kortonyeibukk</div>
<div class="option" data='{"value":"Kotcse","state":"Somogy"}'>Kotcse</div>
<div class="option" data='{"value":"Kotesimalom","state":"Somogy"}'>Kotesimalom</div>
<div class="option" data='{"value":"Kozepkolked","state":"Somogy"}'>Kozepkolked</div>
<div class="option" data='{"value":"Kozepmalom","state":"Somogy"}'>Kozepmalom</div>
<div class="option" data='{"value":"Kozepmarosd","state":"Somogy"}'>Kozepmarosd</div>
<div class="option" data='{"value":"Kozepnyires","state":"Somogy"}'>Kozepnyires</div>
<div class="option" data='{"value":"Kozepnyirespuszta","state":"Somogy"}'>Kozepnyirespuszta</div>
<div class="option" data='{"value":"Kozeprigoc","state":"Somogy"}'>Kozeprigoc</div>
<div class="option" data='{"value":"Kozeprigoc Vasutallomas","state":"Somogy"}'>Kozeprigoc Vasutallomas</div>
<div class="option" data='{"value":"Kozepsocser","state":"Somogy"}'>Kozepsocser</div>
<div class="option" data='{"value":"Kozepsocsesztapuszta","state":"Somogy"}'>Kozepsocsesztapuszta</div>
<div class="option" data='{"value":"Krajapuszta","state":"Somogy"}'>Krajapuszta</div>
<div class="option" data='{"value":"Krazsovicspuszta","state":"Somogy"}'>Krazsovicspuszta</div>
<div class="option" data='{"value":"Kulsoakol","state":"Somogy"}'>Kulsoakol</div>
<div class="option" data='{"value":"Kulsohegy","state":"Somogy"}'>Kulsohegy</div>
<div class="option" data='{"value":"Kulvolgyipuszta","state":"Somogy"}'>Kulvolgyipuszta</div>
<div class="option" data='{"value":"Kuntelep","state":"Somogy"}'>Kuntelep</div>
<div class="option" data='{"value":"Kuria","state":"Somogy"}'>Kuria</div>
<div class="option" data='{"value":"Kurtos","state":"Somogy"}'>Kurtos</div>
<div class="option" data='{"value":"Kurtospuszta","state":"Somogy"}'>Kurtospuszta</div>
<div class="option" data='{"value":"Kusnyamajor","state":"Somogy"}'>Kusnyamajor</div>
<div class="option" data='{"value":"Kutas","state":"Somogy"}'>Kutas</div>
<div class="option" data='{"value":"Kutaskozma","state":"Somogy"}'>Kutaskozma</div>
<div class="option" data='{"value":"Kuteri","state":"Somogy"}'>Kuteri</div>
<div class="option" data='{"value":"Kutfopuszta","state":"Somogy"}'>Kutfopuszta</div>
<div class="option" data='{"value":"Kutvolgyidulo","state":"Somogy"}'>Kutvolgyidulo</div>
<div class="option" data='{"value":"Labod","state":"Somogy"}'>Labod</div>
<div class="option" data='{"value":"Lad","state":"Somogy"}'>Lad</div>
<div class="option" data='{"value":"Lajoshaza","state":"Somogy"}'>Lajoshaza</div>
<div class="option" data='{"value":"Lajoshazapuszta","state":"Somogy"}'>Lajoshazapuszta</div>
<div class="option" data='{"value":"Lajosmajor","state":"Somogy"}'>Lajosmajor</div>
<div class="option" data='{"value":"Lakocsa","state":"Somogy"}'>Lakocsa</div>
<div class="option" data='{"value":"Landitanya","state":"Somogy"}'>Landitanya</div>
<div class="option" data='{"value":"Landord","state":"Somogy"}'>Landord</div>
<div class="option" data='{"value":"Landordpuszta","state":"Somogy"}'>Landordpuszta</div>
<div class="option" data='{"value":"Lankocpuszta","state":"Somogy"}'>Lankocpuszta</div>
<div class="option" data='{"value":"Lapapuszta","state":"Somogy"}'>Lapapuszta</div>
<div class="option" data='{"value":"Laposcser","state":"Somogy"}'>Laposcser</div>
<div class="option" data='{"value":"Laposcserpuszta","state":"Somogy"}'>Laposcserpuszta</div>
<div class="option" data='{"value":"Laszkastanya","state":"Somogy"}'>Laszkastanya</div>
<div class="option" data='{"value":"Laszlomajor","state":"Somogy"}'>Laszlomajor</div>
<div class="option" data='{"value":"Latohegy","state":"Somogy"}'>Latohegy</div>
<div class="option" data='{"value":"Latrany","state":"Somogy"}'>Latrany</div>
<div class="option" data='{"value":"Lehnerpuszta","state":"Somogy"}'>Lehnerpuszta</div>
<div class="option" data='{"value":"Lencipuszta","state":"Somogy"}'>Lencipuszta</div>
<div class="option" data='{"value":"Lencsen","state":"Somogy"}'>Lencsen</div>
<div class="option" data='{"value":"Lencsenpuszta","state":"Somogy"}'>Lencsenpuszta</div>
<div class="option" data='{"value":"Lenczipuszta","state":"Somogy"}'>Lenczipuszta</div>
<div class="option" data='{"value":"Lengyeltoti","state":"Somogy"}'>Lengyeltoti</div>
<div class="option" data='{"value":"Letapuszta","state":"Somogy"}'>Letapuszta</div>
<div class="option" data='{"value":"Leves","state":"Somogy"}'>Leves</div>
<div class="option" data='{"value":"Libbentoitanya","state":"Somogy"}'>Libbentoitanya</div>
<div class="option" data='{"value":"Libickozma","state":"Somogy"}'>Libickozma</div>
<div class="option" data='{"value":"Lipotfa","state":"Somogy"}'>Lipotfa</div>
<div class="option" data='{"value":"Lippapuszta","state":"Somogy"}'>Lippapuszta</div>
<div class="option" data='{"value":"Loka","state":"Somogy"}'>Loka</div>
<div class="option" data='{"value":"Lokpuszta","state":"Somogy"}'>Lokpuszta</div>
<div class="option" data='{"value":"Lonkacser","state":"Somogy"}'>Lonkacser</div>
<div class="option" data='{"value":"Lonkahegy","state":"Somogy"}'>Lonkahegy</div>
<div class="option" data='{"value":"Lulla","state":"Somogy"}'>Lulla</div>
<div class="option" data='{"value":"Lullahegy","state":"Somogy"}'>Lullahegy</div>
<div class="option" data='{"value":"Lullapuszta","state":"Somogy"}'>Lullapuszta</div>
<div class="option" data='{"value":"Lusanidulo","state":"Somogy"}'>Lusanidulo</div>
<div class="option" data='{"value":"Madarsarapuszta","state":"Somogy"}'>Madarsarapuszta</div>
<div class="option" data='{"value":"Magasd","state":"Somogy"}'>Magasd</div>
<div class="option" data='{"value":"Magasdpuszta","state":"Somogy"}'>Magasdpuszta</div>
<div class="option" data='{"value":"Magashegypuszta","state":"Somogy"}'>Magashegypuszta</div>
<div class="option" data='{"value":"Magyal","state":"Somogy"}'>Magyal</div>
<div class="option" data='{"value":"Magyalpuszta","state":"Somogy"}'>Magyalpuszta</div>
<div class="option" data='{"value":"Magyaratad","state":"Somogy"}'>Magyaratad</div>
<div class="option" data='{"value":"Magyaregres","state":"Somogy"}'>Magyaregres</div>
<div class="option" data='{"value":"Magyarker","state":"Somogy"}'>Magyarker</div>
<div class="option" data='{"value":"Magyarlad","state":"Somogy"}'>Magyarlad</div>
<div class="option" data='{"value":"Magyarodpuszta","state":"Somogy"}'>Magyarodpuszta</div>
<div class="option" data='{"value":"Magyarovolgy","state":"Somogy"}'>Magyarovolgy</div>
<div class="option" data='{"value":"Makkpuszta","state":"Somogy"}'>Makkpuszta</div>
<div class="option" data='{"value":"Makktelep","state":"Somogy"}'>Makktelep</div>
<div class="option" data='{"value":"Malomhely","state":"Somogy"}'>Malomhely</div>
<div class="option" data='{"value":"Mamocspuszta","state":"Somogy"}'>Mamocspuszta</div>
<div class="option" data='{"value":"Marcali","state":"Somogy"}'>Marcali</div>
<div class="option" data='{"value":"Mariamajor","state":"Somogy"}'>Mariamajor</div>
<div class="option" data='{"value":"Mariapuszta","state":"Somogy"}'>Mariapuszta</div>
<div class="option" data='{"value":"Mariatanya","state":"Somogy"}'>Mariatanya</div>
<div class="option" data='{"value":"Mariettapuszta","state":"Somogy"}'>Mariettapuszta</div>
<div class="option" data='{"value":"Marotpuszta","state":"Somogy"}'>Marotpuszta</div>
<div class="option" data='{"value":"Mathetanya","state":"Somogy"}'>Mathetanya</div>
<div class="option" data='{"value":"Matildmajor","state":"Somogy"}'>Matildmajor</div>
<div class="option" data='{"value":"Matildpuszta","state":"Somogy"}'>Matildpuszta</div>
<div class="option" data='{"value":"Mecsek","state":"Somogy"}'>Mecsek</div>
<div class="option" data='{"value":"Mernye","state":"Somogy"}'>Mernye</div>
<div class="option" data='{"value":"Mernyeszentmiklos","state":"Somogy"}'>Mernyeszentmiklos</div>
<div class="option" data='{"value":"Mesztegnyo","state":"Somogy"}'>Mesztegnyo</div>
<div class="option" data='{"value":"Mezocsokonya","state":"Somogy"}'>Mezocsokonya</div>
<div class="option" data='{"value":"Mezokeresztesi Tanya","state":"Somogy"}'>Mezokeresztesi Tanya</div>
<div class="option" data='{"value":"Mihalymajor","state":"Somogy"}'>Mihalymajor</div>
<div class="option" data='{"value":"Mike","state":"Somogy"}'>Mike</div>
<div class="option" data='{"value":"Mikepuszta","state":"Somogy"}'>Mikepuszta</div>
<div class="option" data='{"value":"Miketelep","state":"Somogy"}'>Miketelep</div>
<div class="option" data='{"value":"Miklosi","state":"Somogy"}'>Miklosi</div>
<div class="option" data='{"value":"Miklospuszta","state":"Somogy"}'>Miklospuszta</div>
<div class="option" data='{"value":"Mohacsiszolo","state":"Somogy"}'>Mohacsiszolo</div>
<div class="option" data='{"value":"Moricfapuszta","state":"Somogy"}'>Moricfapuszta</div>
<div class="option" data='{"value":"Moriczpuszta","state":"Somogy"}'>Moriczpuszta</div>
<div class="option" data='{"value":"Mosdos","state":"Somogy"}'>Mosdos</div>
<div class="option" data='{"value":"Mucipuszta","state":"Somogy"}'>Mucipuszta</div>
<div class="option" data='{"value":"Nadasakol","state":"Somogy"}'>Nadasakol</div>
<div class="option" data='{"value":"Nagocs","state":"Somogy"}'>Nagocs</div>
<div class="option" data='{"value":"Nagocsi Tanyak","state":"Somogy"}'>Nagocsi Tanyak</div>
<div class="option" data='{"value":"Nagy Szakasi","state":"Somogy"}'>Nagy Szakasi</div>
<div class="option" data='{"value":"Nagyallas","state":"Somogy"}'>Nagyallas</div>
<div class="option" data='{"value":"Nagyallaspuszta","state":"Somogy"}'>Nagyallaspuszta</div>
<div class="option" data='{"value":"Nagyasszony","state":"Somogy"}'>Nagyasszony</div>
<div class="option" data='{"value":"Nagyatad","state":"Somogy"}'>Nagyatad</div>
<div class="option" data='{"value":"Nagybabony","state":"Somogy"}'>Nagybabony</div>
<div class="option" data='{"value":"Nagybajom","state":"Somogy"}'>Nagybajom</div>
<div class="option" data='{"value":"Nagybalogdpuszta","state":"Somogy"}'>Nagybalogdpuszta</div>
<div class="option" data='{"value":"Nagybaratipuszta","state":"Somogy"}'>Nagybaratipuszta</div>
<div class="option" data='{"value":"Nagyberekpuszta","state":"Somogy"}'>Nagyberekpuszta</div>
<div class="option" data='{"value":"Nagybereny","state":"Somogy"}'>Nagybereny</div>
<div class="option" data='{"value":"Nagyberenyi Puszta","state":"Somogy"}'>Nagyberenyi Puszta</div>
<div class="option" data='{"value":"Nagyberki","state":"Somogy"}'>Nagyberki</div>
<div class="option" data='{"value":"Nagycsepely","state":"Somogy"}'>Nagycsepely</div>
<div class="option" data='{"value":"Nagycsepelyi Tanyak","state":"Somogy"}'>Nagycsepelyi Tanyak</div>
<div class="option" data='{"value":"Nagyerdopuszta","state":"Somogy"}'>Nagyerdopuszta</div>
<div class="option" data='{"value":"Nagyhaz","state":"Somogy"}'>Nagyhaz</div>
<div class="option" data='{"value":"Nagyhegyszollo","state":"Somogy"}'>Nagyhegyszollo</div>
<div class="option" data='{"value":"Nagyhegyszolo","state":"Somogy"}'>Nagyhegyszolo</div>
<div class="option" data='{"value":"Nagyhomoki Szollo","state":"Somogy"}'>Nagyhomoki Szollo</div>
<div class="option" data='{"value":"Nagyhomokpuszta","state":"Somogy"}'>Nagyhomokpuszta</div>
<div class="option" data='{"value":"Nagykorpad","state":"Somogy"}'>Nagykorpad</div>
<div class="option" data='{"value":"Nagykurtospuszta","state":"Somogy"}'>Nagykurtospuszta</div>
<div class="option" data='{"value":"Nagypoczapuszta","state":"Somogy"}'>Nagypoczapuszta</div>
<div class="option" data='{"value":"Nagypuszta","state":"Somogy"}'>Nagypuszta</div>
<div class="option" data='{"value":"Nagyrinya Puszta","state":"Somogy"}'>Nagyrinya Puszta</div>
<div class="option" data='{"value":"Nagysallerpuszta","state":"Somogy"}'>Nagysallerpuszta</div>
<div class="option" data='{"value":"Nagysari Puszta","state":"Somogy"}'>Nagysari Puszta</div>
<div class="option" data='{"value":"Nagysarpuszta","state":"Somogy"}'>Nagysarpuszta</div>
<div class="option" data='{"value":"Nagyszakacsi","state":"Somogy"}'>Nagyszakacsi</div>
<div class="option" data='{"value":"Nagytatarvar","state":"Somogy"}'>Nagytatarvar</div>
<div class="option" data='{"value":"Nagytoldipuszta","state":"Somogy"}'>Nagytoldipuszta</div>
<div class="option" data='{"value":"Nagytotvaros","state":"Somogy"}'>Nagytotvaros</div>
<div class="option" data='{"value":"Negyfoldespuszta","state":"Somogy"}'>Negyfoldespuszta</div>
<div class="option" data='{"value":"Nemesded","state":"Somogy"}'>Nemesded</div>
<div class="option" data='{"value":"Nemeskisfalud","state":"Somogy"}'>Nemeskisfalud</div>
<div class="option" data='{"value":"Nemesvid","state":"Somogy"}'>Nemesvid</div>
<div class="option" data='{"value":"Nemethtanya","state":"Somogy"}'>Nemethtanya</div>
<div class="option" data='{"value":"Nemetlad","state":"Somogy"}'>Nemetlad</div>
<div class="option" data='{"value":"Nemettanya","state":"Somogy"}'>Nemettanya</div>
<div class="option" data='{"value":"Nezde","state":"Somogy"}'>Nezde</div>
<div class="option" data='{"value":"Nezdepuszta","state":"Somogy"}'>Nezdepuszta</div>
<div class="option" data='{"value":"Nikla","state":"Somogy"}'>Nikla</div>
<div class="option" data='{"value":"Noszlopitag","state":"Somogy"}'>Noszlopitag</div>
<div class="option" data='{"value":"Nyariakolmajor","state":"Somogy"}'>Nyariakolmajor</div>
<div class="option" data='{"value":"Nyarosalja","state":"Somogy"}'>Nyarosalja</div>
<div class="option" data='{"value":"Nyesthegypuszta","state":"Somogy"}'>Nyesthegypuszta</div>
<div class="option" data='{"value":"Nyim","state":"Somogy"}'>Nyim</div>
<div class="option" data='{"value":"Nyimitanya","state":"Somogy"}'>Nyimitanya</div>
<div class="option" data='{"value":"Nyugatikapolnashegy","state":"Somogy"}'>Nyugatikapolnashegy</div>
<div class="option" data='{"value":"Nyugoti Major","state":"Somogy"}'>Nyugoti Major</div>
<div class="option" data='{"value":"Obbastanya","state":"Somogy"}'>Obbastanya</div>
<div class="option" data='{"value":"Okorjaras","state":"Somogy"}'>Okorjaras</div>
<div class="option" data='{"value":"Okrad","state":"Somogy"}'>Okrad</div>
<div class="option" data='{"value":"Okradpuszta","state":"Somogy"}'>Okradpuszta</div>
<div class="option" data='{"value":"Olajhegy","state":"Somogy"}'>Olajhegy</div>
<div class="option" data='{"value":"Oncsatelep","state":"Somogy"}'>Oncsatelep</div>
<div class="option" data='{"value":"Orci","state":"Somogy"}'>Orci</div>
<div class="option" data='{"value":"Ordacsehi","state":"Somogy"}'>Ordacsehi</div>
<div class="option" data='{"value":"Oreghegy","state":"Somogy"}'>Oreghegy</div>
<div class="option" data='{"value":"Oreghegyi Szollok","state":"Somogy"}'>Oreghegyi Szollok</div>
<div class="option" data='{"value":"Oreghegyiszolok","state":"Somogy"}'>Oreghegyiszolok</div>
<div class="option" data='{"value":"Oreglak","state":"Somogy"}'>Oreglak</div>
<div class="option" data='{"value":"Oreglakpuszta","state":"Somogy"}'>Oreglakpuszta</div>
<div class="option" data='{"value":"Ortilos","state":"Somogy"}'>Ortilos</div>
<div class="option" data='{"value":"Oszpote","state":"Somogy"}'>Oszpote</div>
<div class="option" data='{"value":"Oszpotei Erdoshaz","state":"Somogy"}'>Oszpotei Erdoshaz</div>
<div class="option" data='{"value":"Osztopan","state":"Somogy"}'>Osztopan</div>
<div class="option" data='{"value":"Otelek","state":"Somogy"}'>Otelek</div>
<div class="option" data='{"value":"Otvos","state":"Somogy"}'>Otvos</div>
<div class="option" data='{"value":"Otvoskonyi","state":"Somogy"}'>Otvoskonyi</div>
<div class="option" data='{"value":"Pacservisnye","state":"Somogy"}'>Pacservisnye</div>
<div class="option" data='{"value":"Padpuszta","state":"Somogy"}'>Padpuszta</div>
<div class="option" data='{"value":"Paisspuszta","state":"Somogy"}'>Paisspuszta</div>
<div class="option" data='{"value":"Palajpuszta","state":"Somogy"}'>Palajpuszta</div>
<div class="option" data='{"value":"Palmajor","state":"Somogy"}'>Palmajor</div>
<div class="option" data='{"value":"Palvargadulo","state":"Somogy"}'>Palvargadulo</div>
<div class="option" data='{"value":"Pamuk","state":"Somogy"}'>Pamuk</div>
<div class="option" data='{"value":"Papkutapuszta","state":"Somogy"}'>Papkutapuszta</div>
<div class="option" data='{"value":"Papmalompuszta","state":"Somogy"}'>Papmalompuszta</div>
<div class="option" data='{"value":"Papptanya","state":"Somogy"}'>Papptanya</div>
<div class="option" data='{"value":"Papragypuszta","state":"Somogy"}'>Papragypuszta</div>
<div class="option" data='{"value":"Part","state":"Somogy"}'>Part</div>
<div class="option" data='{"value":"Partfoidulo","state":"Somogy"}'>Partfoidulo</div>
<div class="option" data='{"value":"Partfoledulo","state":"Somogy"}'>Partfoledulo</div>
<div class="option" data='{"value":"Paskom","state":"Somogy"}'>Paskom</div>
<div class="option" data='{"value":"Paskum","state":"Somogy"}'>Paskum</div>
<div class="option" data='{"value":"Patakipuszta","state":"Somogy"}'>Patakipuszta</div>
<div class="option" data='{"value":"Patalom","state":"Somogy"}'>Patalom</div>
<div class="option" data='{"value":"Patalomi Major","state":"Somogy"}'>Patalomi Major</div>
<div class="option" data='{"value":"Patca","state":"Somogy"}'>Patca</div>
<div class="option" data='{"value":"Patihidpuszta","state":"Somogy"}'>Patihidpuszta</div>
<div class="option" data='{"value":"Patosfa","state":"Somogy"}'>Patosfa</div>
<div class="option" data='{"value":"Patpuszta","state":"Somogy"}'>Patpuszta</div>
<div class="option" data='{"value":"Paulinapuszta","state":"Somogy"}'>Paulinapuszta</div>
<div class="option" data='{"value":"Perdocmajor","state":"Somogy"}'>Perdocmajor</div>
<div class="option" data='{"value":"Perecsenypuszta","state":"Somogy"}'>Perecsenypuszta</div>
<div class="option" data='{"value":"Petenyepuszta","state":"Somogy"}'>Petenyepuszta</div>
<div class="option" data='{"value":"Peterhida","state":"Somogy"}'>Peterhida</div>
<div class="option" data='{"value":"Peterpuszta","state":"Somogy"}'>Peterpuszta</div>
<div class="option" data='{"value":"Petesmalom","state":"Somogy"}'>Petesmalom</div>
<div class="option" data='{"value":"Pethesmalom","state":"Somogy"}'>Pethesmalom</div>
<div class="option" data='{"value":"Pipahegy","state":"Somogy"}'>Pipahegy</div>
<div class="option" data='{"value":"Piroshaz","state":"Somogy"}'>Piroshaz</div>
<div class="option" data='{"value":"Piroskahat","state":"Somogy"}'>Piroskahat</div>
<div class="option" data='{"value":"Piroskahaz","state":"Somogy"}'>Piroskahaz</div>
<div class="option" data='{"value":"Pirosmajor","state":"Somogy"}'>Pirosmajor</div>
<div class="option" data='{"value":"Pirostanya","state":"Somogy"}'>Pirostanya</div>
<div class="option" data='{"value":"Pocapuszta","state":"Somogy"}'>Pocapuszta</div>
<div class="option" data='{"value":"Poganyszentpeter","state":"Somogy"}'>Poganyszentpeter</div>
<div class="option" data='{"value":"Polany","state":"Somogy"}'>Polany</div>
<div class="option" data='{"value":"Polavolgy","state":"Somogy"}'>Polavolgy</div>
<div class="option" data='{"value":"Porospuszta","state":"Somogy"}'>Porospuszta</div>
<div class="option" data='{"value":"Porrog","state":"Somogy"}'>Porrog</div>
<div class="option" data='{"value":"Porrogszentkiraly","state":"Somogy"}'>Porrogszentkiraly</div>
<div class="option" data='{"value":"Porrogszentpal","state":"Somogy"}'>Porrogszentpal</div>
<div class="option" data='{"value":"Postelek","state":"Somogy"}'>Postelek</div>
<div class="option" data='{"value":"Potony","state":"Somogy"}'>Potony</div>
<div class="option" data='{"value":"Potonypuszta","state":"Somogy"}'>Potonypuszta</div>
<div class="option" data='{"value":"Proszapuszta","state":"Somogy"}'>Proszapuszta</div>
<div class="option" data='{"value":"Pucokszallas","state":"Somogy"}'>Pucokszallas</div>
<div class="option" data='{"value":"Puhahazmajor","state":"Somogy"}'>Puhahazmajor</div>
<div class="option" data='{"value":"Pusztabereny","state":"Somogy"}'>Pusztabereny</div>
<div class="option" data='{"value":"Pusztagat","state":"Somogy"}'>Pusztagat</div>
<div class="option" data='{"value":"Pusztakovacsi","state":"Somogy"}'>Pusztakovacsi</div>
<div class="option" data='{"value":"Pusztamezotelep","state":"Somogy"}'>Pusztamezotelep</div>
<div class="option" data='{"value":"Pusztasomodor","state":"Somogy"}'>Pusztasomodor</div>
<div class="option" data='{"value":"Pusztaszemes","state":"Somogy"}'>Pusztaszemes</div>
<div class="option" data='{"value":"Pusztaszentgyorgy","state":"Somogy"}'>Pusztaszentgyorgy</div>
<div class="option" data='{"value":"Putripuszta","state":"Somogy"}'>Putripuszta</div>
<div class="option" data='{"value":"Racegres","state":"Somogy"}'>Racegres</div>
<div class="option" data='{"value":"Racors","state":"Somogy"}'>Racors</div>
<div class="option" data='{"value":"Radpuszta","state":"Somogy"}'>Radpuszta</div>
<div class="option" data='{"value":"Rajnicstanya","state":"Somogy"}'>Rajnicstanya</div>
<div class="option" data='{"value":"Rakipuszta","state":"Somogy"}'>Rakipuszta</div>
<div class="option" data='{"value":"Raknyipuszta","state":"Somogy"}'>Raknyipuszta</div>
<div class="option" data='{"value":"Rakopuszta","state":"Somogy"}'>Rakopuszta</div>
<div class="option" data='{"value":"Raksi","state":"Somogy"}'>Raksi</div>
<div class="option" data='{"value":"Raksipuszta","state":"Somogy"}'>Raksipuszta</div>
<div class="option" data='{"value":"Regimalomhaz","state":"Somogy"}'>Regimalomhaz</div>
<div class="option" data='{"value":"Remete","state":"Somogy"}'>Remete</div>
<div class="option" data='{"value":"Remetepuszta","state":"Somogy"}'>Remetepuszta</div>
<div class="option" data='{"value":"Repaspuszta","state":"Somogy"}'>Repaspuszta</div>
<div class="option" data='{"value":"Ricepuszta","state":"Somogy"}'>Ricepuszta</div>
<div class="option" data='{"value":"Riczepuszta","state":"Somogy"}'>Riczepuszta</div>
<div class="option" data='{"value":"Rigocikastely","state":"Somogy"}'>Rigocikastely</div>
<div class="option" data='{"value":"Rinyabesenyo","state":"Somogy"}'>Rinyabesenyo</div>
<div class="option" data='{"value":"Rinyabesnyo","state":"Somogy"}'>Rinyabesnyo</div>
<div class="option" data='{"value":"Rinyahosszufalu","state":"Somogy"}'>Rinyahosszufalu</div>
<div class="option" data='{"value":"Rinyakovacsi","state":"Somogy"}'>Rinyakovacsi</div>
<div class="option" data='{"value":"Rinyapuszta","state":"Somogy"}'>Rinyapuszta</div>
<div class="option" data='{"value":"Rinyaszentkiraly","state":"Somogy"}'>Rinyaszentkiraly</div>
<div class="option" data='{"value":"Rinyatamasi","state":"Somogy"}'>Rinyatamasi</div>
<div class="option" data='{"value":"Rinyaujlak","state":"Somogy"}'>Rinyaujlak</div>
<div class="option" data='{"value":"Rinyaujnep","state":"Somogy"}'>Rinyaujnep</div>
<div class="option" data='{"value":"Rocsildszollo","state":"Somogy"}'>Rocsildszollo</div>
<div class="option" data='{"value":"Romahegy","state":"Somogy"}'>Romahegy</div>
<div class="option" data='{"value":"Ropolpuszta","state":"Somogy"}'>Ropolpuszta</div>
<div class="option" data='{"value":"Rotschildszolo","state":"Somogy"}'>Rotschildszolo</div>
<div class="option" data='{"value":"Rozsahegy","state":"Somogy"}'>Rozsahegy</div>
<div class="option" data='{"value":"Rozsamajor","state":"Somogy"}'>Rozsamajor</div>
<div class="option" data='{"value":"Rozsapuszta","state":"Somogy"}'>Rozsapuszta</div>
<div class="option" data='{"value":"Rozsas","state":"Somogy"}'>Rozsas</div>
<div class="option" data='{"value":"Sagvar","state":"Somogy"}'>Sagvar</div>
<div class="option" data='{"value":"Sandipuszta","state":"Somogy"}'>Sandipuszta</div>
<div class="option" data='{"value":"Sandorpuszta","state":"Somogy"}'>Sandorpuszta</div>
<div class="option" data='{"value":"Santos","state":"Somogy"}'>Santos</div>
<div class="option" data='{"value":"Santosi Tanyak","state":"Somogy"}'>Santosi Tanyak</div>
<div class="option" data='{"value":"Sarihegy","state":"Somogy"}'>Sarihegy</div>
<div class="option" data='{"value":"Saripuszta","state":"Somogy"}'>Saripuszta</div>
<div class="option" data='{"value":"Sarkanytopuszta","state":"Somogy"}'>Sarkanytopuszta</div>
<div class="option" data='{"value":"Saroltapuszta","state":"Somogy"}'>Saroltapuszta</div>
<div class="option" data='{"value":"Sarosgodor","state":"Somogy"}'>Sarosgodor</div>
<div class="option" data='{"value":"Sasierdo","state":"Somogy"}'>Sasierdo</div>
<div class="option" data='{"value":"Savoly","state":"Somogy"}'>Savoly</div>
<div class="option" data='{"value":"Savolyi Major","state":"Somogy"}'>Savolyi Major</div>
<div class="option" data='{"value":"Segesd","state":"Somogy"}'>Segesd</div>
<div class="option" data='{"value":"Sersek","state":"Somogy"}'>Sersek</div>
<div class="option" data='{"value":"Serseki Tanyak","state":"Somogy"}'>Serseki Tanyak</div>
<div class="option" data='{"value":"Sersekszollos","state":"Somogy"}'>Sersekszollos</div>
<div class="option" data='{"value":"Sersekszollosi Tanyak","state":"Somogy"}'>Sersekszollosi Tanyak</div>
<div class="option" data='{"value":"Sersekszolos","state":"Somogy"}'>Sersekszolos</div>
<div class="option" data='{"value":"Simonfa","state":"Somogy"}'>Simonfa</div>
<div class="option" data='{"value":"Simonmajor","state":"Somogy"}'>Simonmajor</div>
<div class="option" data='{"value":"Siofok","state":"Somogy"}'>Siofok</div>
<div class="option" data='{"value":"Siojut","state":"Somogy"}'>Siojut</div>
<div class="option" data='{"value":"Siomaros","state":"Somogy"}'>Siomaros</div>
<div class="option" data='{"value":"Siopuszta","state":"Somogy"}'>Siopuszta</div>
<div class="option" data='{"value":"Sodakpuszta","state":"Somogy"}'>Sodakpuszta</div>
<div class="option" data='{"value":"Sodarpuszta","state":"Somogy"}'>Sodarpuszta</div>
<div class="option" data='{"value":"Som","state":"Somogy"}'>Som</div>
<div class="option" data='{"value":"Somodor","state":"Somogy"}'>Somodor</div>
<div class="option" data='{"value":"Somodorpuszta","state":"Somogy"}'>Somodorpuszta</div>
<div class="option" data='{"value":"Somogy","state":"Somogy"}'>Somogy</div>
<div class="option" data='{"value":"Somogy County","state":"Somogy"}'>Somogy County</div>
<div class="option" data='{"value":"Somogy Megye","state":"Somogy"}'>Somogy Megye</div>
<div class="option" data='{"value":"Somogy Szent Imrepuszta","state":"Somogy"}'>Somogy Szent Imrepuszta</div>
<div class="option" data='{"value":"Somogy Tarnocza","state":"Somogy"}'>Somogy Tarnocza</div>
<div class="option" data='{"value":"Somogyacsa","state":"Somogy"}'>Somogyacsa</div>
<div class="option" data='{"value":"Somogyaracs","state":"Somogy"}'>Somogyaracs</div>
<div class="option" data='{"value":"Somogyaszalo","state":"Somogy"}'>Somogyaszalo</div>
<div class="option" data='{"value":"Somogybabod","state":"Somogy"}'>Somogybabod</div>
<div class="option" data='{"value":"Somogybukkosd","state":"Somogy"}'>Somogybukkosd</div>
<div class="option" data='{"value":"Somogycsicso","state":"Somogy"}'>Somogycsicso</div>
<div class="option" data='{"value":"Somogydorocske","state":"Somogy"}'>Somogydorocske</div>
<div class="option" data='{"value":"Somogyegres","state":"Somogy"}'>Somogyegres</div>
<div class="option" data='{"value":"Somogyfajsz","state":"Somogy"}'>Somogyfajsz</div>
<div class="option" data='{"value":"Somogyfeheregyhaz","state":"Somogy"}'>Somogyfeheregyhaz</div>
<div class="option" data='{"value":"Somogyfok","state":"Somogy"}'>Somogyfok</div>
<div class="option" data='{"value":"Somogyfok Szolloskert","state":"Somogy"}'>Somogyfok Szolloskert</div>
<div class="option" data='{"value":"Somogygeszti","state":"Somogy"}'>Somogygeszti</div>
<div class="option" data='{"value":"Somogyjad","state":"Somogy"}'>Somogyjad</div>
<div class="option" data='{"value":"Somogymeggyes","state":"Somogy"}'>Somogymeggyes</div>
<div class="option" data='{"value":"Somogysamson","state":"Somogy"}'>Somogysamson</div>
<div class="option" data='{"value":"Somogysard","state":"Somogy"}'>Somogysard</div>
<div class="option" data='{"value":"Somogysimonyi","state":"Somogy"}'>Somogysimonyi</div>
<div class="option" data='{"value":"Somogyszentimre","state":"Somogy"}'>Somogyszentimre</div>
<div class="option" data='{"value":"Somogyszentpal","state":"Somogy"}'>Somogyszentpal</div>
<div class="option" data='{"value":"Somogyszil","state":"Somogy"}'>Somogyszil</div>
<div class="option" data='{"value":"Somogyszob","state":"Somogy"}'>Somogyszob</div>
<div class="option" data='{"value":"Somogytarnoca","state":"Somogy"}'>Somogytarnoca</div>
<div class="option" data='{"value":"Somogytur","state":"Somogy"}'>Somogytur</div>
<div class="option" data='{"value":"Somogyudvarhely","state":"Somogy"}'>Somogyudvarhely</div>
<div class="option" data='{"value":"Somogyvamos","state":"Somogy"}'>Somogyvamos</div>
<div class="option" data='{"value":"Somogyvar","state":"Somogy"}'>Somogyvar</div>
<div class="option" data='{"value":"Somogyvisonta","state":"Somogy"}'>Somogyvisonta</div>
<div class="option" data='{"value":"Somogyzsitfa","state":"Somogy"}'>Somogyzsitfa</div>
<div class="option" data='{"value":"Somretidulo","state":"Somogy"}'>Somretidulo</div>
<div class="option" data='{"value":"Soospuszta","state":"Somogy"}'>Soospuszta</div>
<div class="option" data='{"value":"Soostanya","state":"Somogy"}'>Soostanya</div>
<div class="option" data='{"value":"Soponyapuszta","state":"Somogy"}'>Soponyapuszta</div>
<div class="option" data='{"value":"Sornyepuszta","state":"Somogy"}'>Sornyepuszta</div>
<div class="option" data='{"value":"Sosto","state":"Somogy"}'>Sosto</div>
<div class="option" data='{"value":"Sostoi Major","state":"Somogy"}'>Sostoi Major</div>
<div class="option" data='{"value":"Szabadi","state":"Somogy"}'>Szabadi</div>
<div class="option" data='{"value":"Szabas","state":"Somogy"}'>Szabas</div>
<div class="option" data='{"value":"Szabohaz","state":"Somogy"}'>Szabohaz</div>
<div class="option" data='{"value":"Szabotanya","state":"Somogy"}'>Szabotanya</div>
<div class="option" data='{"value":"Szalacskapuszta","state":"Somogy"}'>Szalacskapuszta</div>
<div class="option" data='{"value":"Szalasztopuszta","state":"Somogy"}'>Szalasztopuszta</div>
<div class="option" data='{"value":"Szanacsitelep","state":"Somogy"}'>Szanacsitelep</div>
<div class="option" data='{"value":"Szantod","state":"Somogy"}'>Szantod</div>
<div class="option" data='{"value":"Szantodpuszta","state":"Somogy"}'>Szantodpuszta</div>
<div class="option" data='{"value":"Szarkastopuszta","state":"Somogy"}'>Szarkastopuszta</div>
<div class="option" data='{"value":"Szarkavar","state":"Somogy"}'>Szarkavar</div>
<div class="option" data='{"value":"Szavica","state":"Somogy"}'>Szavica</div>
<div class="option" data='{"value":"Szechenyilepled","state":"Somogy"}'>Szechenyilepled</div>
<div class="option" data='{"value":"Szederjesihegy","state":"Somogy"}'>Szederjesihegy</div>
<div class="option" data='{"value":"Szegerdo","state":"Somogy"}'>Szegerdo</div>
<div class="option" data='{"value":"Szegerdotelep","state":"Somogy"}'>Szegerdotelep</div>
<div class="option" data='{"value":"Szendihegy","state":"Somogy"}'>Szendihegy</div>
<div class="option" data='{"value":"Szendpuszta","state":"Somogy"}'>Szendpuszta</div>
<div class="option" data='{"value":"Szenna","state":"Somogy"}'>Szenna</div>
<div class="option" data='{"value":"Szent Mihaly","state":"Somogy"}'>Szent Mihaly</div>
<div class="option" data='{"value":"Szenta","state":"Somogy"}'>Szenta</div>
<div class="option" data='{"value":"Szentaujmajor","state":"Somogy"}'>Szentaujmajor</div>
<div class="option" data='{"value":"Szentbalazs","state":"Somogy"}'>Szentbalazs</div>
<div class="option" data='{"value":"Szentborbas","state":"Somogy"}'>Szentborbas</div>
<div class="option" data='{"value":"Szentespuszta","state":"Somogy"}'>Szentespuszta</div>
<div class="option" data='{"value":"Szentgalosker","state":"Somogy"}'>Szentgalosker</div>
<div class="option" data='{"value":"Szentivanpuszta","state":"Somogy"}'>Szentivanpuszta</div>
<div class="option" data='{"value":"Szentkeresztpuszta","state":"Somogy"}'>Szentkeresztpuszta</div>
<div class="option" data='{"value":"Szentlaszlomonostora","state":"Somogy"}'>Szentlaszlomonostora</div>
<div class="option" data='{"value":"Szentlaszlopuszta","state":"Somogy"}'>Szentlaszlopuszta</div>
<div class="option" data='{"value":"Szentmihalyhegy","state":"Somogy"}'>Szentmihalyhegy</div>
<div class="option" data='{"value":"Szentmihalypuszta","state":"Somogy"}'>Szentmihalypuszta</div>
<div class="option" data='{"value":"Szentmihalytanya","state":"Somogy"}'>Szentmihalytanya</div>
<div class="option" data='{"value":"Szenttamaspuszta","state":"Somogy"}'>Szenttamaspuszta</div>
<div class="option" data='{"value":"Szenyer","state":"Somogy"}'>Szenyer</div>
<div class="option" data='{"value":"Szeplak","state":"Somogy"}'>Szeplak</div>
<div class="option" data='{"value":"Sziagypuszta","state":"Somogy"}'>Sziagypuszta</div>
<div class="option" data='{"value":"Szigetmajor","state":"Somogy"}'>Szigetmajor</div>
<div class="option" data='{"value":"Szilos","state":"Somogy"}'>Szilos</div>
<div class="option" data='{"value":"Szilospuszta","state":"Somogy"}'>Szilospuszta</div>
<div class="option" data='{"value":"Szilvas","state":"Somogy"}'>Szilvas</div>
<div class="option" data='{"value":"Szilvaspuszta","state":"Somogy"}'>Szilvaspuszta</div>
<div class="option" data='{"value":"Szilvasszentmarton","state":"Somogy"}'>Szilvasszentmarton</div>
<div class="option" data='{"value":"Szocsenypuszta","state":"Somogy"}'>Szocsenypuszta</div>
<div class="option" data='{"value":"Szokedencs","state":"Somogy"}'>Szokedencs</div>
<div class="option" data='{"value":"Szokepuszta","state":"Somogy"}'>Szokepuszta</div>
<div class="option" data='{"value":"Szokolics","state":"Somogy"}'>Szokolics</div>
<div class="option" data='{"value":"Szokolicstanya","state":"Somogy"}'>Szokolicstanya</div>
<div class="option" data='{"value":"Szolad","state":"Somogy"}'>Szolad</div>
<div class="option" data='{"value":"Szoladimajor","state":"Somogy"}'>Szoladimajor</div>
<div class="option" data='{"value":"Szollosgyorok","state":"Somogy"}'>Szollosgyorok</div>
<div class="option" data='{"value":"Szolloskislak","state":"Somogy"}'>Szolloskislak</div>
<div class="option" data='{"value":"Szolosgyorok","state":"Somogy"}'>Szolosgyorok</div>
<div class="option" data='{"value":"Szoloskislak","state":"Somogy"}'>Szoloskislak</div>
<div class="option" data='{"value":"Szomajom","state":"Somogy"}'>Szomajom</div>
<div class="option" data='{"value":"Szomorupuszta","state":"Somogy"}'>Szomorupuszta</div>
<div class="option" data='{"value":"Szornyugodor","state":"Somogy"}'>Szornyugodor</div>
<div class="option" data='{"value":"Szornyupuszta","state":"Somogy"}'>Szornyupuszta</div>
<div class="option" data='{"value":"Szorosad","state":"Somogy"}'>Szorosad</div>
<div class="option" data='{"value":"Szovecspuszta","state":"Somogy"}'>Szovecspuszta</div>
<div class="option" data='{"value":"Szulok","state":"Somogy"}'>Szulok</div>
<div class="option" data='{"value":"Tab","state":"Somogy"}'>Tab</div>
<div class="option" data='{"value":"Takacshegy","state":"Somogy"}'>Takacshegy</div>
<div class="option" data='{"value":"Tangazdasag","state":"Somogy"}'>Tangazdasag</div>
<div class="option" data='{"value":"Tapsony","state":"Somogy"}'>Tapsony</div>
<div class="option" data='{"value":"Tarany","state":"Somogy"}'>Tarany</div>
<div class="option" data='{"value":"Tarcsapuszta","state":"Somogy"}'>Tarcsapuszta</div>
<div class="option" data='{"value":"Tardpuszta","state":"Somogy"}'>Tardpuszta</div>
<div class="option" data='{"value":"Taska","state":"Somogy"}'>Taska</div>
<div class="option" data='{"value":"Taszar","state":"Somogy"}'>Taszar</div>
<div class="option" data='{"value":"Tatikapuszta","state":"Somogy"}'>Tatikapuszta</div>
<div class="option" data='{"value":"Tatomhegy","state":"Somogy"}'>Tatomhegy</div>
<div class="option" data='{"value":"Tatompuszta","state":"Somogy"}'>Tatompuszta</div>
<div class="option" data='{"value":"Tazar","state":"Somogy"}'>Tazar</div>
<div class="option" data='{"value":"Teglahazitanya","state":"Somogy"}'>Teglahazitanya</div>
<div class="option" data='{"value":"Tekerespuszta","state":"Somogy"}'>Tekerespuszta</div>
<div class="option" data='{"value":"Tekespuszta","state":"Somogy"}'>Tekespuszta</div>
<div class="option" data='{"value":"Teleki","state":"Somogy"}'>Teleki</div>
<div class="option" data='{"value":"Teleki Tanyak","state":"Somogy"}'>Teleki Tanyak</div>
<div class="option" data='{"value":"Telekipuszta","state":"Somogy"}'>Telekipuszta</div>
<div class="option" data='{"value":"Tengod","state":"Somogy"}'>Tengod</div>
<div class="option" data='{"value":"Terebezd","state":"Somogy"}'>Terebezd</div>
<div class="option" data='{"value":"Terebezdi Hegy","state":"Somogy"}'>Terebezdi Hegy</div>
<div class="option" data='{"value":"Terebezdpuszta","state":"Somogy"}'>Terebezdpuszta</div>
<div class="option" data='{"value":"Terezlak","state":"Somogy"}'>Terezlak</div>
<div class="option" data='{"value":"Terezmajor","state":"Somogy"}'>Terezmajor</div>
<div class="option" data='{"value":"Tibolamajor","state":"Somogy"}'>Tibolamajor</div>
<div class="option" data='{"value":"Tibolapuszta","state":"Somogy"}'>Tibolapuszta</div>
<div class="option" data='{"value":"Tikos","state":"Somogy"}'>Tikos</div>
<div class="option" data='{"value":"Tiltvanypuszta","state":"Somogy"}'>Tiltvanypuszta</div>
<div class="option" data='{"value":"Tisztaviz","state":"Somogy"}'>Tisztaviz</div>
<div class="option" data='{"value":"Tokozibejaro","state":"Somogy"}'>Tokozibejaro</div>
<div class="option" data='{"value":"Tokozpuszta","state":"Somogy"}'>Tokozpuszta</div>
<div class="option" data='{"value":"Tollospuszta","state":"Somogy"}'>Tollospuszta</div>
<div class="option" data='{"value":"Tolos","state":"Somogy"}'>Tolos</div>
<div class="option" data='{"value":"Toloshegy","state":"Somogy"}'>Toloshegy</div>
<div class="option" data='{"value":"Tolospuszta","state":"Somogy"}'>Tolospuszta</div>
<div class="option" data='{"value":"Tomepuszta","state":"Somogy"}'>Tomepuszta</div>
<div class="option" data='{"value":"Toponar","state":"Somogy"}'>Toponar</div>
<div class="option" data='{"value":"Toreki","state":"Somogy"}'>Toreki</div>
<div class="option" data='{"value":"Torekihegy","state":"Somogy"}'>Torekihegy</div>
<div class="option" data='{"value":"Torekipuszta","state":"Somogy"}'>Torekipuszta</div>
<div class="option" data='{"value":"Tornafodulo","state":"Somogy"}'>Tornafodulo</div>
<div class="option" data='{"value":"Torocske","state":"Somogy"}'>Torocske</div>
<div class="option" data='{"value":"Torokkoppany","state":"Somogy"}'>Torokkoppany</div>
<div class="option" data='{"value":"Torokkoppanyi Tanya","state":"Somogy"}'>Torokkoppanyi Tanya</div>
<div class="option" data='{"value":"Torokmajor","state":"Somogy"}'>Torokmajor</div>
<div class="option" data='{"value":"Torokretpuszta","state":"Somogy"}'>Torokretpuszta</div>
<div class="option" data='{"value":"Toroktanya","state":"Somogy"}'>Toroktanya</div>
<div class="option" data='{"value":"Torvaj","state":"Somogy"}'>Torvaj</div>
<div class="option" data='{"value":"Totfalupuszta","state":"Somogy"}'>Totfalupuszta</div>
<div class="option" data='{"value":"Tothegy","state":"Somogy"}'>Tothegy</div>
<div class="option" data='{"value":"Totokilap","state":"Somogy"}'>Totokilap</div>
<div class="option" data='{"value":"Totujfalu","state":"Somogy"}'>Totujfalu</div>
<div class="option" data='{"value":"Tozegtelep","state":"Somogy"}'>Tozegtelep</div>
<div class="option" data='{"value":"Tuskos","state":"Somogy"}'>Tuskos</div>
<div class="option" data='{"value":"Tuskospuszta","state":"Somogy"}'>Tuskospuszta</div>
<div class="option" data='{"value":"Ugajpuszta","state":"Somogy"}'>Ugajpuszta</div>
<div class="option" data='{"value":"Ujhangyasi Szollo","state":"Somogy"}'>Ujhangyasi Szollo</div>
<div class="option" data='{"value":"Ujhazhelyek","state":"Somogy"}'>Ujhazhelyek</div>
<div class="option" data='{"value":"Ujhazpuszta","state":"Somogy"}'>Ujhazpuszta</div>
<div class="option" data='{"value":"Ujhedrehely","state":"Somogy"}'>Ujhedrehely</div>
<div class="option" data='{"value":"Ujhegy","state":"Somogy"}'>Ujhegy</div>
<div class="option" data='{"value":"Ujhegyi Szollok","state":"Somogy"}'>Ujhegyi Szollok</div>
<div class="option" data='{"value":"Ujkutpuszta","state":"Somogy"}'>Ujkutpuszta</div>
<div class="option" data='{"value":"Ujmajor","state":"Somogy"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujpuszta","state":"Somogy"}'>Ujpuszta</div>
<div class="option" data='{"value":"Ujsor","state":"Somogy"}'>Ujsor</div>
<div class="option" data='{"value":"Ujsornyepuszta","state":"Somogy"}'>Ujsornyepuszta</div>
<div class="option" data='{"value":"Ujtelep","state":"Somogy"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujvarfalva","state":"Somogy"}'>Ujvarfalva</div>
<div class="option" data='{"value":"Ujvillasor","state":"Somogy"}'>Ujvillasor</div>
<div class="option" data='{"value":"Ujzoborpuszta","state":"Somogy"}'>Ujzoborpuszta</div>
<div class="option" data='{"value":"Ujzsippo","state":"Somogy"}'>Ujzsippo</div>
<div class="option" data='{"value":"Urhegyipuszta","state":"Somogy"}'>Urhegyipuszta</div>
<div class="option" data='{"value":"Urumajor","state":"Somogy"}'>Urumajor</div>
<div class="option" data='{"value":"Uzdpuszta","state":"Somogy"}'>Uzdpuszta</div>
<div class="option" data='{"value":"Vadaskert","state":"Somogy"}'>Vadaskert</div>
<div class="option" data='{"value":"Vadaspuszta","state":"Somogy"}'>Vadaspuszta</div>
<div class="option" data='{"value":"Vadepuszta","state":"Somogy"}'>Vadepuszta</div>
<div class="option" data='{"value":"Vagottnyires","state":"Somogy"}'>Vagottnyires</div>
<div class="option" data='{"value":"Vagottnyiresdulo","state":"Somogy"}'>Vagottnyiresdulo</div>
<div class="option" data='{"value":"Vakmalom","state":"Somogy"}'>Vakmalom</div>
<div class="option" data='{"value":"Varaljapuszta","state":"Somogy"}'>Varaljapuszta</div>
<div class="option" data='{"value":"Varaszlo","state":"Somogy"}'>Varaszlo</div>
<div class="option" data='{"value":"Varda","state":"Somogy"}'>Varda</div>
<div class="option" data='{"value":"Varhegytanya","state":"Somogy"}'>Varhegytanya</div>
<div class="option" data='{"value":"Varszo","state":"Somogy"}'>Varszo</div>
<div class="option" data='{"value":"Vasadihegy","state":"Somogy"}'>Vasadihegy</div>
<div class="option" data='{"value":"Vazsonypuszta","state":"Somogy"}'>Vazsonypuszta</div>
<div class="option" data='{"value":"Vermes","state":"Somogy"}'>Vermes</div>
<div class="option" data='{"value":"Vese","state":"Somogy"}'>Vese</div>
<div class="option" data='{"value":"Viktorpuszta","state":"Somogy"}'>Viktorpuszta</div>
<div class="option" data='{"value":"Vilagospuszta","state":"Somogy"}'>Vilagospuszta</div>
<div class="option" data='{"value":"Vincetanya","state":"Somogy"}'>Vincetanya</div>
<div class="option" data='{"value":"Viragospuszta","state":"Somogy"}'>Viragospuszta</div>
<div class="option" data='{"value":"Visitag","state":"Somogy"}'>Visitag</div>
<div class="option" data='{"value":"Visitagpuszta","state":"Somogy"}'>Visitagpuszta</div>
<div class="option" data='{"value":"Visnye","state":"Somogy"}'>Visnye</div>
<div class="option" data='{"value":"Visnyeszeplak","state":"Somogy"}'>Visnyeszeplak</div>
<div class="option" data='{"value":"Visz","state":"Somogy"}'>Visz</div>
<div class="option" data='{"value":"Viszakpuszta","state":"Somogy"}'>Viszakpuszta</div>
<div class="option" data='{"value":"Viszi Puszta","state":"Somogy"}'>Viszi Puszta</div>
<div class="option" data='{"value":"Vitezitanya","state":"Somogy"}'>Vitezitanya</div>
<div class="option" data='{"value":"Vitezitelek","state":"Somogy"}'>Vitezitelek</div>
<div class="option" data='{"value":"Vitezitelep","state":"Somogy"}'>Vitezitelep</div>
<div class="option" data='{"value":"Viteztelep","state":"Somogy"}'>Viteztelep</div>
<div class="option" data='{"value":"Vityapuszta","state":"Somogy"}'>Vityapuszta</div>
<div class="option" data='{"value":"Vizesmalom","state":"Somogy"}'>Vizesmalom</div>
<div class="option" data='{"value":"Vizvar","state":"Somogy"}'>Vizvar</div>
<div class="option" data='{"value":"Vizvari Tanya","state":"Somogy"}'>Vizvari Tanya</div>
<div class="option" data='{"value":"Vonyitapuszta","state":"Somogy"}'>Vonyitapuszta</div>
<div class="option" data='{"value":"Vorosakol","state":"Somogy"}'>Vorosakol</div>
<div class="option" data='{"value":"Vorosakolpuszta","state":"Somogy"}'>Vorosakolpuszta</div>
<div class="option" data='{"value":"Vorosakolypuszta","state":"Somogy"}'>Vorosakolypuszta</div>
<div class="option" data='{"value":"Vorosalmapuszta","state":"Somogy"}'>Vorosalmapuszta</div>
<div class="option" data='{"value":"Vorosihegy","state":"Somogy"}'>Vorosihegy</div>
<div class="option" data='{"value":"Vors","state":"Somogy"}'>Vors</div>
<div class="option" data='{"value":"Votapuszta","state":"Somogy"}'>Votapuszta</div>
<div class="option" data='{"value":"Zakany","state":"Somogy"}'>Zakany</div>
<div class="option" data='{"value":"Zakanytelep","state":"Somogy"}'>Zakanytelep</div>
<div class="option" data='{"value":"Zala","state":"Somogy"}'>Zala</div>
<div class="option" data='{"value":"Zalai Tanyak","state":"Somogy"}'>Zalai Tanyak</div>
<div class="option" data='{"value":"Zamardi","state":"Somogy"}'>Zamardi</div>
<div class="option" data='{"value":"Zamardi Tanyak","state":"Somogy"}'>Zamardi Tanyak</div>
<div class="option" data='{"value":"Zaranypuszta","state":"Somogy"}'>Zaranypuszta</div>
<div class="option" data='{"value":"Zatonytelep","state":"Somogy"}'>Zatonytelep</div>
<div class="option" data='{"value":"Zics","state":"Somogy"}'>Zics</div>
<div class="option" data='{"value":"Zicsi Tanyak","state":"Somogy"}'>Zicsi Tanyak</div>
<div class="option" data='{"value":"Zimany","state":"Somogy"}'>Zimany</div>
<div class="option" data='{"value":"Zimmerteto","state":"Somogy"}'>Zimmerteto</div>
<div class="option" data='{"value":"Zimona","state":"Somogy"}'>Zimona</div>
<div class="option" data='{"value":"Zselickisfalud","state":"Somogy"}'>Zselickisfalud</div>
<div class="option" data='{"value":"Zselickislak","state":"Somogy"}'>Zselickislak</div>
<div class="option" data='{"value":"Zselicszentpal","state":"Somogy"}'>Zselicszentpal</div>
<div class="option" data='{"value":"Zselicszentpali Puszta","state":"Somogy"}'>Zselicszentpali Puszta</div>
<div class="option" data='{"value":"Zsigmond","state":"Somogy"}'>Zsigmond</div>
<div class="option" data='{"value":"Zsigmondpuszta","state":"Somogy"}'>Zsigmondpuszta</div>
<div class="option" data='{"value":"Zsippo","state":"Somogy"}'>Zsippo</div>
<div class="option" data='{"value":"Zsippoihegy","state":"Somogy"}'>Zsippoihegy</div>
<div class="option" data='{"value":"Zsippopuszta","state":"Somogy"}'>Zsippopuszta</div>
<div class="option" data='{"value":"Zsitfapuszta","state":"Somogy"}'>Zsitfapuszta</div>
<div class="option" id="option_end" data='{"value":"Zsitvapuszta","state":"Somogy"}'>Zsitvapuszta</div>

