<div class="option" data='{"value":"Abrahamhegy","state":"Veszprem"}'>Abrahamhegy</div>
<div class="option" data='{"value":"Adasztevel","state":"Veszprem"}'>Adasztevel</div>
<div class="option" data='{"value":"Agostonmajor","state":"Veszprem"}'>Agostonmajor</div>
<div class="option" data='{"value":"Agyaglik","state":"Veszprem"}'>Agyaglik</div>
<div class="option" data='{"value":"Agyaglika","state":"Veszprem"}'>Agyaglika</div>
<div class="option" data='{"value":"Ajka","state":"Veszprem"}'>Ajka</div>
<div class="option" data='{"value":"Ajkai Tanyak","state":"Veszprem"}'>Ajkai Tanyak</div>
<div class="option" data='{"value":"Ajkarendek","state":"Veszprem"}'>Ajkarendek</div>
<div class="option" data='{"value":"Ajkarendek Tanyak","state":"Veszprem"}'>Ajkarendek Tanyak</div>
<div class="option" data='{"value":"Ajkarendeki Tanyak","state":"Veszprem"}'>Ajkarendeki Tanyak</div>
<div class="option" data='{"value":"Akacasmajor","state":"Veszprem"}'>Akacasmajor</div>
<div class="option" data='{"value":"Akali","state":"Veszprem"}'>Akali</div>
<div class="option" data='{"value":"Akarattya","state":"Veszprem"}'>Akarattya</div>
<div class="option" data='{"value":"Akasztodomb","state":"Veszprem"}'>Akasztodomb</div>
<div class="option" data='{"value":"Aklipuszta","state":"Veszprem"}'>Aklipuszta</div>
<div class="option" data='{"value":"Akna","state":"Veszprem"}'>Akna</div>
<div class="option" data='{"value":"Aligvarimajor","state":"Veszprem"}'>Aligvarimajor</div>
<div class="option" data='{"value":"Aligvarmajor","state":"Veszprem"}'>Aligvarmajor</div>
<div class="option" data='{"value":"Allami Szollotelep","state":"Veszprem"}'>Allami Szollotelep</div>
<div class="option" data='{"value":"Alsobaricska","state":"Veszprem"}'>Alsobaricska</div>
<div class="option" data='{"value":"Alsobocsar","state":"Veszprem"}'>Alsobocsar</div>
<div class="option" data='{"value":"Alsoborsod","state":"Veszprem"}'>Alsoborsod</div>
<div class="option" data='{"value":"Alsocsinger","state":"Veszprem"}'>Alsocsinger</div>
<div class="option" data='{"value":"Alsocsingervolgy","state":"Veszprem"}'>Alsocsingervolgy</div>
<div class="option" data='{"value":"Alsodobospuszta","state":"Veszprem"}'>Alsodobospuszta</div>
<div class="option" data='{"value":"Alsodorgicse","state":"Veszprem"}'>Alsodorgicse</div>
<div class="option" data='{"value":"Alsoerdo","state":"Veszprem"}'>Alsoerdo</div>
<div class="option" data='{"value":"Alsoerdopuszta","state":"Veszprem"}'>Alsoerdopuszta</div>
<div class="option" data='{"value":"Alsogorzsony","state":"Veszprem"}'>Alsogorzsony</div>
<div class="option" data='{"value":"Alsoiszkaz","state":"Veszprem"}'>Alsoiszkaz</div>
<div class="option" data='{"value":"Alsomajor","state":"Veszprem"}'>Alsomajor</div>
<div class="option" data='{"value":"Alsomama","state":"Veszprem"}'>Alsomama</div>
<div class="option" data='{"value":"Alsomandpuszta","state":"Veszprem"}'>Alsomandpuszta</div>
<div class="option" data='{"value":"Alsomezo","state":"Veszprem"}'>Alsomezo</div>
<div class="option" data='{"value":"Alsomozsar","state":"Veszprem"}'>Alsomozsar</div>
<div class="option" data='{"value":"Alsoors","state":"Veszprem"}'>Alsoors</div>
<div class="option" data='{"value":"Alsopere","state":"Veszprem"}'>Alsopere</div>
<div class="option" data='{"value":"Alsoret","state":"Veszprem"}'>Alsoret</div>
<div class="option" data='{"value":"Alsoszalmavar","state":"Veszprem"}'>Alsoszalmavar</div>
<div class="option" data='{"value":"Alsotundermajor","state":"Veszprem"}'>Alsotundermajor</div>
<div class="option" data='{"value":"Alsovonyarc","state":"Veszprem"}'>Alsovonyarc</div>
<div class="option" data='{"value":"Ambrustanya","state":"Veszprem"}'>Ambrustanya</div>
<div class="option" data='{"value":"Antalfaimajor","state":"Veszprem"}'>Antalfaimajor</div>
<div class="option" data='{"value":"Antalfopuszta","state":"Veszprem"}'>Antalfopuszta</div>
<div class="option" data='{"value":"Antalhegy","state":"Veszprem"}'>Antalhegy</div>
<div class="option" data='{"value":"Apacatorna","state":"Veszprem"}'>Apacatorna</div>
<div class="option" data='{"value":"Apaczatorna","state":"Veszprem"}'>Apaczatorna</div>
<div class="option" data='{"value":"Aprobel","state":"Veszprem"}'>Aprobel</div>
<div class="option" data='{"value":"Ardapuszta","state":"Veszprem"}'>Ardapuszta</div>
<div class="option" data='{"value":"Arminakna","state":"Veszprem"}'>Arminakna</div>
<div class="option" data='{"value":"Arpadmajor","state":"Veszprem"}'>Arpadmajor</div>
<div class="option" data='{"value":"Arpadtelep","state":"Veszprem"}'>Arpadtelep</div>
<div class="option" data='{"value":"Asszonyfa","state":"Veszprem"}'>Asszonyfa</div>
<div class="option" data='{"value":"Aszofo","state":"Veszprem"}'>Aszofo</div>
<div class="option" data='{"value":"Attyamajor","state":"Veszprem"}'>Attyamajor</div>
<div class="option" data='{"value":"Attyapuszta","state":"Veszprem"}'>Attyapuszta</div>
<div class="option" data='{"value":"Auerbachtanya","state":"Veszprem"}'>Auerbachtanya</div>
<div class="option" data='{"value":"Bacspuszta","state":"Veszprem"}'>Bacspuszta</div>
<div class="option" data='{"value":"Badacsony","state":"Veszprem"}'>Badacsony</div>
<div class="option" data='{"value":"Badacsonyors","state":"Veszprem"}'>Badacsonyors</div>
<div class="option" data='{"value":"Badacsonytomaj","state":"Veszprem"}'>Badacsonytomaj</div>
<div class="option" data='{"value":"Badacsonytordemic","state":"Veszprem"}'>Badacsonytordemic</div>
<div class="option" data='{"value":"Bagolyvarpuszta","state":"Veszprem"}'>Bagolyvarpuszta</div>
<div class="option" data='{"value":"Bakonybel","state":"Veszprem"}'>Bakonybel</div>
<div class="option" data='{"value":"Bakonygyepes","state":"Veszprem"}'>Bakonygyepes</div>
<div class="option" data='{"value":"Bakonygyepesi Tanyak","state":"Veszprem"}'>Bakonygyepesi Tanyak</div>
<div class="option" data='{"value":"Bakonyjako","state":"Veszprem"}'>Bakonyjako</div>
<div class="option" data='{"value":"Bakonyjakoi Tanyak","state":"Veszprem"}'>Bakonyjakoi Tanyak</div>
<div class="option" data='{"value":"Bakonykoppany","state":"Veszprem"}'>Bakonykoppany</div>
<div class="option" data='{"value":"Bakonynana","state":"Veszprem"}'>Bakonynana</div>
<div class="option" data='{"value":"Bakonynanai Tanya","state":"Veszprem"}'>Bakonynanai Tanya</div>
<div class="option" data='{"value":"Bakonyoszlop","state":"Veszprem"}'>Bakonyoszlop</div>
<div class="option" data='{"value":"Bakonypoloske","state":"Veszprem"}'>Bakonypoloske</div>
<div class="option" data='{"value":"Bakonysag","state":"Veszprem"}'>Bakonysag</div>
<div class="option" data='{"value":"Bakonyszentivan","state":"Veszprem"}'>Bakonyszentivan</div>
<div class="option" data='{"value":"Bakonyszentkiraly","state":"Veszprem"}'>Bakonyszentkiraly</div>
<div class="option" data='{"value":"Bakonyszucs","state":"Veszprem"}'>Bakonyszucs</div>
<div class="option" data='{"value":"Bakonytamasi","state":"Veszprem"}'>Bakonytamasi</div>
<div class="option" data='{"value":"Balaczaidulo","state":"Veszprem"}'>Balaczaidulo</div>
<div class="option" data='{"value":"Balatonakali","state":"Veszprem"}'>Balatonakali</div>
<div class="option" data='{"value":"Balatonakarattya","state":"Veszprem"}'>Balatonakarattya</div>
<div class="option" data='{"value":"Balatonaliga","state":"Veszprem"}'>Balatonaliga</div>
<div class="option" data='{"value":"Balatonalmadi","state":"Veszprem"}'>Balatonalmadi</div>
<div class="option" data='{"value":"Balatonaracs","state":"Veszprem"}'>Balatonaracs</div>
<div class="option" data='{"value":"Balatoncsicso","state":"Veszprem"}'>Balatoncsicso</div>
<div class="option" data='{"value":"Balatonederics","state":"Veszprem"}'>Balatonederics</div>
<div class="option" data='{"value":"Balatonfokajar","state":"Veszprem"}'>Balatonfokajar</div>
<div class="option" data='{"value":"Balatonfokajari Tanyak","state":"Veszprem"}'>Balatonfokajari Tanyak</div>
<div class="option" data='{"value":"Balatonfured","state":"Veszprem"}'>Balatonfured</div>
<div class="option" data='{"value":"Balatonfuzfo","state":"Veszprem"}'>Balatonfuzfo</div>
<div class="option" data='{"value":"Balatonhenye","state":"Veszprem"}'>Balatonhenye</div>
<div class="option" data='{"value":"Balatonkenese","state":"Veszprem"}'>Balatonkenese</div>
<div class="option" data='{"value":"Balatonradulo","state":"Veszprem"}'>Balatonradulo</div>
<div class="option" data='{"value":"Balatonrendes","state":"Veszprem"}'>Balatonrendes</div>
<div class="option" data='{"value":"Balatonszentmihaly","state":"Veszprem"}'>Balatonszentmihaly</div>
<div class="option" data='{"value":"Balatonszepezd","state":"Veszprem"}'>Balatonszepezd</div>
<div class="option" data='{"value":"Balatonszollos","state":"Veszprem"}'>Balatonszollos</div>
<div class="option" data='{"value":"Balatonszolos","state":"Veszprem"}'>Balatonszolos</div>
<div class="option" data='{"value":"Balatonudvari","state":"Veszprem"}'>Balatonudvari</div>
<div class="option" data='{"value":"Balatonvilag Furdotelep","state":"Veszprem"}'>Balatonvilag Furdotelep</div>
<div class="option" data='{"value":"Balatonvilagos","state":"Veszprem"}'>Balatonvilagos</div>
<div class="option" data='{"value":"Balatonvilagosfurdo","state":"Veszprem"}'>Balatonvilagosfurdo</div>
<div class="option" data='{"value":"Balatonvilagospuszta","state":"Veszprem"}'>Balatonvilagospuszta</div>
<div class="option" data='{"value":"Balinthegy","state":"Veszprem"}'>Balinthegy</div>
<div class="option" data='{"value":"Band","state":"Veszprem"}'>Band</div>
<div class="option" data='{"value":"Banhalma","state":"Veszprem"}'>Banhalma</div>
<div class="option" data='{"value":"Banoczymajor","state":"Veszprem"}'>Banoczymajor</div>
<div class="option" data='{"value":"Banoczypuszta","state":"Veszprem"}'>Banoczypuszta</div>
<div class="option" data='{"value":"Bantapuszta","state":"Veszprem"}'>Bantapuszta</div>
<div class="option" data='{"value":"Bantopuszta","state":"Veszprem"}'>Bantopuszta</div>
<div class="option" data='{"value":"Banyatelep","state":"Veszprem"}'>Banyatelep</div>
<div class="option" data='{"value":"Baranyas","state":"Veszprem"}'>Baranyas</div>
<div class="option" data='{"value":"Baratfapuszta","state":"Veszprem"}'>Baratfapuszta</div>
<div class="option" data='{"value":"Baratmajor","state":"Veszprem"}'>Baratmajor</div>
<div class="option" data='{"value":"Barczamajor","state":"Veszprem"}'>Barczamajor</div>
<div class="option" data='{"value":"Bardiotag","state":"Veszprem"}'>Bardiotag</div>
<div class="option" data='{"value":"Baricska","state":"Veszprem"}'>Baricska</div>
<div class="option" data='{"value":"Barnag","state":"Veszprem"}'>Barnag</div>
<div class="option" data='{"value":"Baroczhegy","state":"Veszprem"}'>Baroczhegy</div>
<div class="option" data='{"value":"Barossmajor","state":"Veszprem"}'>Barossmajor</div>
<div class="option" data='{"value":"Barragret","state":"Veszprem"}'>Barragret</div>
<div class="option" data='{"value":"Battyanmajor","state":"Veszprem"}'>Battyanmajor</div>
<div class="option" data='{"value":"Bauxitbanya","state":"Veszprem"}'>Bauxitbanya</div>
<div class="option" data='{"value":"Bazaltbanya","state":"Veszprem"}'>Bazaltbanya</div>
<div class="option" data='{"value":"Bazsi","state":"Veszprem"}'>Bazsi</div>
<div class="option" data='{"value":"Beb","state":"Veszprem"}'>Beb</div>
<div class="option" data='{"value":"Bebic","state":"Veszprem"}'>Bebic</div>
<div class="option" data='{"value":"Beccehegy","state":"Veszprem"}'>Beccehegy</div>
<div class="option" data='{"value":"Becehegy","state":"Veszprem"}'>Becehegy</div>
<div class="option" data='{"value":"Becserpuszta","state":"Veszprem"}'>Becserpuszta</div>
<div class="option" data='{"value":"Bedia","state":"Veszprem"}'>Bedia</div>
<div class="option" data='{"value":"Bejcgyertyanos","state":"Veszprem"}'>Bejcgyertyanos</div>
<div class="option" data='{"value":"Bekas","state":"Veszprem"}'>Bekas</div>
<div class="option" data='{"value":"Bekenypuszta","state":"Veszprem"}'>Bekenypuszta</div>
<div class="option" data='{"value":"Bekesmajor","state":"Veszprem"}'>Bekesmajor</div>
<div class="option" data='{"value":"Belato","state":"Veszprem"}'>Belato</div>
<div class="option" data='{"value":"Belsoabrahamhegy","state":"Veszprem"}'>Belsoabrahamhegy</div>
<div class="option" data='{"value":"Belsomajor","state":"Veszprem"}'>Belsomajor</div>
<div class="option" data='{"value":"Bene","state":"Veszprem"}'>Bene</div>
<div class="option" data='{"value":"Berectanya","state":"Veszprem"}'>Berectanya</div>
<div class="option" data='{"value":"Bereczpuszta","state":"Veszprem"}'>Bereczpuszta</div>
<div class="option" data='{"value":"Bereg","state":"Veszprem"}'>Bereg</div>
<div class="option" data='{"value":"Berek","state":"Veszprem"}'>Berek</div>
<div class="option" data='{"value":"Berekhat","state":"Veszprem"}'>Berekhat</div>
<div class="option" data='{"value":"Berencztanya","state":"Veszprem"}'>Berencztanya</div>
<div class="option" data='{"value":"Berhida","state":"Veszprem"}'>Berhida</div>
<div class="option" data='{"value":"Berkenyes","state":"Veszprem"}'>Berkenyes</div>
<div class="option" data='{"value":"Bertalanffymajor","state":"Veszprem"}'>Bertalanffymajor</div>
<div class="option" data='{"value":"Bertalanffypuszta","state":"Veszprem"}'>Bertalanffypuszta</div>
<div class="option" data='{"value":"Billege","state":"Veszprem"}'>Billege</div>
<div class="option" data='{"value":"Billegepuszta","state":"Veszprem"}'>Billegepuszta</div>
<div class="option" data='{"value":"Birkaakoli Major","state":"Veszprem"}'>Birkaakoli Major</div>
<div class="option" data='{"value":"Birkasmajor","state":"Veszprem"}'>Birkasmajor</div>
<div class="option" data='{"value":"Biromalom","state":"Veszprem"}'>Biromalom</div>
<div class="option" data='{"value":"Biroret","state":"Veszprem"}'>Biroret</div>
<div class="option" data='{"value":"Bo","state":"Veszprem"}'>Bo</div>
<div class="option" data='{"value":"Boba","state":"Veszprem"}'>Boba</div>
<div class="option" data='{"value":"Bodacstanya","state":"Veszprem"}'>Bodacstanya</div>
<div class="option" data='{"value":"Bode","state":"Veszprem"}'>Bode</div>
<div class="option" data='{"value":"Boditanya","state":"Veszprem"}'>Boditanya</div>
<div class="option" data='{"value":"Bodonkut","state":"Veszprem"}'>Bodonkut</div>
<div class="option" data='{"value":"Bodorfa","state":"Veszprem"}'>Bodorfa</div>
<div class="option" data='{"value":"Bogot","state":"Veszprem"}'>Bogot</div>
<div class="option" data='{"value":"Bogote","state":"Veszprem"}'>Bogote</div>
<div class="option" data='{"value":"Bogotimajor","state":"Veszprem"}'>Bogotimajor</div>
<div class="option" data='{"value":"Bogotmajor","state":"Veszprem"}'>Bogotmajor</div>
<div class="option" data='{"value":"Bokatanya","state":"Veszprem"}'>Bokatanya</div>
<div class="option" data='{"value":"Bokod","state":"Veszprem"}'>Bokod</div>
<div class="option" data='{"value":"Bokodpuszta","state":"Veszprem"}'>Bokodpuszta</div>
<div class="option" data='{"value":"Bolgarkert","state":"Veszprem"}'>Bolgarkert</div>
<div class="option" data='{"value":"Boncsod","state":"Veszprem"}'>Boncsod</div>
<div class="option" data='{"value":"Boncsodpuszta","state":"Veszprem"}'>Boncsodpuszta</div>
<div class="option" data='{"value":"Borkoskut","state":"Veszprem"}'>Borkoskut</div>
<div class="option" data='{"value":"Borollo","state":"Veszprem"}'>Borollo</div>
<div class="option" data='{"value":"Borollopuszta","state":"Veszprem"}'>Borollopuszta</div>
<div class="option" data='{"value":"Borsodpuszta","state":"Veszprem"}'>Borsodpuszta</div>
<div class="option" data='{"value":"Borsosgyor","state":"Veszprem"}'>Borsosgyor</div>
<div class="option" data='{"value":"Borszorcsok","state":"Veszprem"}'>Borszorcsok</div>
<div class="option" data='{"value":"Borzavar","state":"Veszprem"}'>Borzavar</div>
<div class="option" data='{"value":"Borzavari Major","state":"Veszprem"}'>Borzavari Major</div>
<div class="option" data='{"value":"Budatava","state":"Veszprem"}'>Budatava</div>
<div class="option" data='{"value":"Budoskutmajor","state":"Veszprem"}'>Budoskutmajor</div>
<div class="option" data='{"value":"Buricsmalom","state":"Veszprem"}'>Buricsmalom</div>
<div class="option" data='{"value":"Ciframajor","state":"Veszprem"}'>Ciframajor</div>
<div class="option" data='{"value":"Cilinko","state":"Veszprem"}'>Cilinko</div>
<div class="option" data='{"value":"Cinahegy","state":"Veszprem"}'>Cinahegy</div>
<div class="option" data='{"value":"Cirfuszmajor","state":"Veszprem"}'>Cirfuszmajor</div>
<div class="option" data='{"value":"Csabberek","state":"Veszprem"}'>Csabberek</div>
<div class="option" data='{"value":"Csabberekpuszta","state":"Veszprem"}'>Csabberekpuszta</div>
<div class="option" data='{"value":"Csabpuszta","state":"Veszprem"}'>Csabpuszta</div>
<div class="option" data='{"value":"Csabrendek","state":"Veszprem"}'>Csabrendek</div>
<div class="option" data='{"value":"Csajag","state":"Veszprem"}'>Csajag</div>
<div class="option" data='{"value":"Csalanos","state":"Veszprem"}'>Csalanos</div>
<div class="option" data='{"value":"Csalanostanya","state":"Veszprem"}'>Csalanostanya</div>
<div class="option" data='{"value":"Csalit","state":"Veszprem"}'>Csalit</div>
<div class="option" data='{"value":"Csango","state":"Veszprem"}'>Csango</div>
<div class="option" data='{"value":"Csanig","state":"Veszprem"}'>Csanig</div>
<div class="option" data='{"value":"Csapasut","state":"Veszprem"}'>Csapasut</div>
<div class="option" data='{"value":"Csarda","state":"Veszprem"}'>Csarda</div>
<div class="option" data='{"value":"Csardamajor","state":"Veszprem"}'>Csardamajor</div>
<div class="option" data='{"value":"Csardapuszta","state":"Veszprem"}'>Csardapuszta</div>
<div class="option" data='{"value":"Csaszta","state":"Veszprem"}'>Csaszta</div>
<div class="option" data='{"value":"Csasztai Furdo","state":"Veszprem"}'>Csasztai Furdo</div>
<div class="option" data='{"value":"Csatarimalom","state":"Veszprem"}'>Csatarimalom</div>
<div class="option" data='{"value":"Csatarmalom","state":"Veszprem"}'>Csatarmalom</div>
<div class="option" data='{"value":"Csatarpuszta","state":"Veszprem"}'>Csatarpuszta</div>
<div class="option" data='{"value":"Csatarymajor","state":"Veszprem"}'>Csatarymajor</div>
<div class="option" data='{"value":"Csecsi Puszta","state":"Veszprem"}'>Csecsi Puszta</div>
<div class="option" data='{"value":"Csehbanya","state":"Veszprem"}'>Csehbanya</div>
<div class="option" data='{"value":"Csehbanyai Major","state":"Veszprem"}'>Csehbanyai Major</div>
<div class="option" data='{"value":"Csehipuszta","state":"Veszprem"}'>Csehipuszta</div>
<div class="option" data='{"value":"Csekut","state":"Veszprem"}'>Csekut</div>
<div class="option" data='{"value":"Cser","state":"Veszprem"}'>Cser</div>
<div class="option" data='{"value":"Cserdomb","state":"Veszprem"}'>Cserdomb</div>
<div class="option" data='{"value":"Cserhatpuszta","state":"Veszprem"}'>Cserhatpuszta</div>
<div class="option" data='{"value":"Cseridulo","state":"Veszprem"}'>Cseridulo</div>
<div class="option" data='{"value":"Cserimalom","state":"Veszprem"}'>Cserimalom</div>
<div class="option" data='{"value":"Cseripuszta","state":"Veszprem"}'>Cseripuszta</div>
<div class="option" data='{"value":"Cseroldal","state":"Veszprem"}'>Cseroldal</div>
<div class="option" data='{"value":"Cservarpuszta","state":"Veszprem"}'>Cservarpuszta</div>
<div class="option" data='{"value":"Cservolgyi Gazdasag","state":"Veszprem"}'>Cservolgyi Gazdasag</div>
<div class="option" data='{"value":"Cservolgymajor","state":"Veszprem"}'>Cservolgymajor</div>
<div class="option" data='{"value":"Csesznek","state":"Veszprem"}'>Csesznek</div>
<div class="option" data='{"value":"Cseteny","state":"Veszprem"}'>Cseteny</div>
<div class="option" data='{"value":"Csetetag","state":"Veszprem"}'>Csetetag</div>
<div class="option" data='{"value":"Csibehegy","state":"Veszprem"}'>Csibehegy</div>
<div class="option" data='{"value":"Csicsoierdo","state":"Veszprem"}'>Csicsoierdo</div>
<div class="option" data='{"value":"Csigahegy","state":"Veszprem"}'>Csigahegy</div>
<div class="option" data='{"value":"Csigeihegy","state":"Veszprem"}'>Csigeihegy</div>
<div class="option" data='{"value":"Csikvandi Telep","state":"Veszprem"}'>Csikvandi Telep</div>
<div class="option" data='{"value":"Csipanhaza","state":"Veszprem"}'>Csipanhaza</div>
<div class="option" data='{"value":"Csippanhaza","state":"Veszprem"}'>Csippanhaza</div>
<div class="option" data='{"value":"Csobanc","state":"Veszprem"}'>Csobanc</div>
<div class="option" data='{"value":"Csobanchegy","state":"Veszprem"}'>Csobanchegy</div>
<div class="option" data='{"value":"Csocsahegy","state":"Veszprem"}'>Csocsahegy</div>
<div class="option" data='{"value":"Csogimajor","state":"Veszprem"}'>Csogimajor</div>
<div class="option" data='{"value":"Csogle","state":"Veszprem"}'>Csogle</div>
<div class="option" data='{"value":"Csokanyszollo","state":"Veszprem"}'>Csokanyszollo</div>
<div class="option" data='{"value":"Csonge","state":"Veszprem"}'>Csonge</div>
<div class="option" data='{"value":"Csopak","state":"Veszprem"}'>Csopak</div>
<div class="option" data='{"value":"Csornakutipuszta","state":"Veszprem"}'>Csornakutipuszta</div>
<div class="option" data='{"value":"Csorompuszta","state":"Veszprem"}'>Csorompuszta</div>
<div class="option" data='{"value":"Csoszpuszta","state":"Veszprem"}'>Csoszpuszta</div>
<div class="option" data='{"value":"Csot","state":"Veszprem"}'>Csot</div>
<div class="option" data='{"value":"Csota","state":"Veszprem"}'>Csota</div>
<div class="option" data='{"value":"Csotapuszta","state":"Veszprem"}'>Csotapuszta</div>
<div class="option" data='{"value":"Csoti Malom","state":"Veszprem"}'>Csoti Malom</div>
<div class="option" data='{"value":"Csoti Ujmajor","state":"Veszprem"}'>Csoti Ujmajor</div>
<div class="option" data='{"value":"Csukidulo","state":"Veszprem"}'>Csukidulo</div>
<div class="option" data='{"value":"Csurgomalom","state":"Veszprem"}'>Csurgomalom</div>
<div class="option" data='{"value":"Cuhamajor","state":"Veszprem"}'>Cuhamajor</div>
<div class="option" data='{"value":"Czirfuszmajor","state":"Veszprem"}'>Czirfuszmajor</div>
<div class="option" data='{"value":"Dabroka","state":"Veszprem"}'>Dabroka</div>
<div class="option" data='{"value":"Dabrokaicsarda","state":"Veszprem"}'>Dabrokaicsarda</div>
<div class="option" data='{"value":"Dabronc","state":"Veszprem"}'>Dabronc</div>
<div class="option" data='{"value":"Dabrony","state":"Veszprem"}'>Dabrony</div>
<div class="option" data='{"value":"Daka","state":"Veszprem"}'>Daka</div>
<div class="option" data='{"value":"Daraboshegy","state":"Veszprem"}'>Daraboshegy</div>
<div class="option" data='{"value":"Deakipuszta","state":"Veszprem"}'>Deakipuszta</div>
<div class="option" data='{"value":"Denesmajor","state":"Veszprem"}'>Denesmajor</div>
<div class="option" data='{"value":"Dergecs","state":"Veszprem"}'>Dergecs</div>
<div class="option" data='{"value":"Dergecspuszta","state":"Veszprem"}'>Dergecspuszta</div>
<div class="option" data='{"value":"Devecser","state":"Veszprem"}'>Devecser</div>
<div class="option" data='{"value":"Devecserihegy","state":"Veszprem"}'>Devecserihegy</div>
<div class="option" data='{"value":"Diospuszta","state":"Veszprem"}'>Diospuszta</div>
<div class="option" data='{"value":"Diskahegy","state":"Veszprem"}'>Diskahegy</div>
<div class="option" data='{"value":"Diskamajor","state":"Veszprem"}'>Diskamajor</div>
<div class="option" data='{"value":"Diskapuszta","state":"Veszprem"}'>Diskapuszta</div>
<div class="option" data='{"value":"Diszel","state":"Veszprem"}'>Diszel</div>
<div class="option" data='{"value":"Doba","state":"Veszprem"}'>Doba</div>
<div class="option" data='{"value":"Dobogomajor","state":"Veszprem"}'>Dobogomajor</div>
<div class="option" data='{"value":"Dobospuszta","state":"Veszprem"}'>Dobospuszta</div>
<div class="option" data='{"value":"Dobresimalom","state":"Veszprem"}'>Dobresimalom</div>
<div class="option" data='{"value":"Dobronte","state":"Veszprem"}'>Dobronte</div>
<div class="option" data='{"value":"Dochegy","state":"Veszprem"}'>Dochegy</div>
<div class="option" data='{"value":"Dorgicse","state":"Veszprem"}'>Dorgicse</div>
<div class="option" data='{"value":"Dorzemenypuszta","state":"Veszprem"}'>Dorzemenypuszta</div>
<div class="option" data='{"value":"Drucskomalom","state":"Veszprem"}'>Drucskomalom</div>
<div class="option" data='{"value":"Dudar","state":"Veszprem"}'>Dudar</div>
<div class="option" data='{"value":"Duka","state":"Veszprem"}'>Duka</div>
<div class="option" data='{"value":"Ebhegy","state":"Veszprem"}'>Ebhegy</div>
<div class="option" data='{"value":"Ecser","state":"Veszprem"}'>Ecser</div>
<div class="option" data='{"value":"Ecseri Major","state":"Veszprem"}'>Ecseri Major</div>
<div class="option" data='{"value":"Ecserpuszta","state":"Veszprem"}'>Ecserpuszta</div>
<div class="option" data='{"value":"Egeralja","state":"Veszprem"}'>Egeralja</div>
<div class="option" data='{"value":"Egyhazaskeszo","state":"Veszprem"}'>Egyhazaskeszo</div>
<div class="option" data='{"value":"Eklezsiamalom","state":"Veszprem"}'>Eklezsiamalom</div>
<div class="option" data='{"value":"Elemermajor","state":"Veszprem"}'>Elemermajor</div>
<div class="option" data='{"value":"Elemerpuszta","state":"Veszprem"}'>Elemerpuszta</div>
<div class="option" data='{"value":"Emilhaza","state":"Veszprem"}'>Emilhaza</div>
<div class="option" data='{"value":"Epleny","state":"Veszprem"}'>Epleny</div>
<div class="option" data='{"value":"Erdeihegy","state":"Veszprem"}'>Erdeihegy</div>
<div class="option" data='{"value":"Erdositanya","state":"Veszprem"}'>Erdositanya</div>
<div class="option" data='{"value":"Erdoslak","state":"Veszprem"}'>Erdoslak</div>
<div class="option" data='{"value":"Ernotanya","state":"Veszprem"}'>Ernotanya</div>
<div class="option" data='{"value":"Erzsebetmajor","state":"Veszprem"}'>Erzsebetmajor</div>
<div class="option" data='{"value":"Erzsebetpuszta","state":"Veszprem"}'>Erzsebetpuszta</div>
<div class="option" data='{"value":"Farkasgyepu","state":"Veszprem"}'>Farkasgyepu</div>
<div class="option" data='{"value":"Farkashegy","state":"Veszprem"}'>Farkashegy</div>
<div class="option" data='{"value":"Fecskefarkidulo","state":"Veszprem"}'>Fecskefarkidulo</div>
<div class="option" data='{"value":"Fehervizidulo","state":"Veszprem"}'>Fehervizidulo</div>
<div class="option" data='{"value":"Felso Ponyvad","state":"Veszprem"}'>Felso Ponyvad</div>
<div class="option" data='{"value":"Felsobocsardulo","state":"Veszprem"}'>Felsobocsardulo</div>
<div class="option" data='{"value":"Felsocsinger","state":"Veszprem"}'>Felsocsinger</div>
<div class="option" data='{"value":"Felsocsingervolgy","state":"Veszprem"}'>Felsocsingervolgy</div>
<div class="option" data='{"value":"Felsodorgicse","state":"Veszprem"}'>Felsodorgicse</div>
<div class="option" data='{"value":"Felsogorzsony","state":"Veszprem"}'>Felsogorzsony</div>
<div class="option" data='{"value":"Felsoiszkaz","state":"Veszprem"}'>Felsoiszkaz</div>
<div class="option" data='{"value":"Felsokolonia","state":"Veszprem"}'>Felsokolonia</div>
<div class="option" data='{"value":"Felsomalom","state":"Veszprem"}'>Felsomalom</div>
<div class="option" data='{"value":"Felsomama","state":"Veszprem"}'>Felsomama</div>
<div class="option" data='{"value":"Felsomezo","state":"Veszprem"}'>Felsomezo</div>
<div class="option" data='{"value":"Felsoors","state":"Veszprem"}'>Felsoors</div>
<div class="option" data='{"value":"Felsopere","state":"Veszprem"}'>Felsopere</div>
<div class="option" data='{"value":"Felsoperepuszta","state":"Veszprem"}'>Felsoperepuszta</div>
<div class="option" data='{"value":"Felszabadulas Uti Lakotelep","state":"Veszprem"}'>Felszabadulas Uti Lakotelep</div>
<div class="option" data='{"value":"Felszabadulas Utja","state":"Veszprem"}'>Felszabadulas Utja</div>
<div class="option" data='{"value":"Fenekdulo","state":"Veszprem"}'>Fenekdulo</div>
<div class="option" data='{"value":"Fenyeshegy","state":"Veszprem"}'>Fenyeshegy</div>
<div class="option" data='{"value":"Fenyos","state":"Veszprem"}'>Fenyos</div>
<div class="option" data='{"value":"Fenyosdomb","state":"Veszprem"}'>Fenyosdomb</div>
<div class="option" data='{"value":"Fenyves","state":"Veszprem"}'>Fenyves</div>
<div class="option" data='{"value":"Fenyveshegy","state":"Veszprem"}'>Fenyveshegy</div>
<div class="option" data='{"value":"Ferencmajor","state":"Veszprem"}'>Ferencmajor</div>
<div class="option" data='{"value":"Ferenctelek","state":"Veszprem"}'>Ferenctelek</div>
<div class="option" data='{"value":"Flinkmalom","state":"Veszprem"}'>Flinkmalom</div>
<div class="option" data='{"value":"Foglalas","state":"Veszprem"}'>Foglalas</div>
<div class="option" data='{"value":"Fokszodpuszta","state":"Veszprem"}'>Fokszodpuszta</div>
<div class="option" data='{"value":"Fovenyfurdo","state":"Veszprem"}'>Fovenyfurdo</div>
<div class="option" data='{"value":"Franciavagas","state":"Veszprem"}'>Franciavagas</div>
<div class="option" data='{"value":"Fulopi Szolo","state":"Veszprem"}'>Fulopi Szolo</div>
<div class="option" data='{"value":"Fulopiszollohegy","state":"Veszprem"}'>Fulopiszollohegy</div>
<div class="option" data='{"value":"Fulopmalom","state":"Veszprem"}'>Fulopmalom</div>
<div class="option" data='{"value":"Furdotelep","state":"Veszprem"}'>Furdotelep</div>
<div class="option" data='{"value":"Furesztelep","state":"Veszprem"}'>Furesztelep</div>
<div class="option" data='{"value":"Fuzfegyardelep","state":"Veszprem"}'>Fuzfegyardelep</div>
<div class="option" data='{"value":"Fuzfofurdo","state":"Veszprem"}'>Fuzfofurdo</div>
<div class="option" data='{"value":"Fuzfogyartelep","state":"Veszprem"}'>Fuzfogyartelep</div>
<div class="option" data='{"value":"Fuzilap","state":"Veszprem"}'>Fuzilap</div>
<div class="option" data='{"value":"Fuztopuszta","state":"Veszprem"}'>Fuztopuszta</div>
<div class="option" data='{"value":"Ganna","state":"Veszprem"}'>Ganna</div>
<div class="option" data='{"value":"Gardonyi Hegy","state":"Veszprem"}'>Gardonyi Hegy</div>
<div class="option" data='{"value":"Gaspartelep","state":"Veszprem"}'>Gaspartelep</div>
<div class="option" data='{"value":"Gasztonyitelep","state":"Veszprem"}'>Gasztonyitelep</div>
<div class="option" data='{"value":"Gecse","state":"Veszprem"}'>Gecse</div>
<div class="option" data='{"value":"Gelencserkut","state":"Veszprem"}'>Gelencserkut</div>
<div class="option" data='{"value":"Gellapuszta","state":"Veszprem"}'>Gellapuszta</div>
<div class="option" data='{"value":"Gelyevolgy","state":"Veszprem"}'>Gelyevolgy</div>
<div class="option" data='{"value":"Gerencepuszta","state":"Veszprem"}'>Gerencepuszta</div>
<div class="option" data='{"value":"Gezahaza","state":"Veszprem"}'>Gezahaza</div>
<div class="option" data='{"value":"Gezahazapuszta","state":"Veszprem"}'>Gezahazapuszta</div>
<div class="option" data='{"value":"Gic","state":"Veszprem"}'>Gic</div>
<div class="option" data='{"value":"Goganfa","state":"Veszprem"}'>Goganfa</div>
<div class="option" data='{"value":"Gombaspuszta","state":"Veszprem"}'>Gombaspuszta</div>
<div class="option" data='{"value":"Grofimalom","state":"Veszprem"}'>Grofimalom</div>
<div class="option" data='{"value":"Gyaripuszta","state":"Veszprem"}'>Gyaripuszta</div>
<div class="option" data='{"value":"Gyartelep","state":"Veszprem"}'>Gyartelep</div>
<div class="option" data='{"value":"Gyepukajan","state":"Veszprem"}'>Gyepukajan</div>
<div class="option" data='{"value":"Gyertyankut","state":"Veszprem"}'>Gyertyankut</div>
<div class="option" data='{"value":"Gyorimalom","state":"Veszprem"}'>Gyorimalom</div>
<div class="option" data='{"value":"Gyulafiratot","state":"Veszprem"}'>Gyulafiratot</div>
<div class="option" data='{"value":"Gyulahegy","state":"Veszprem"}'>Gyulahegy</div>
<div class="option" data='{"value":"Gyulakeszi","state":"Veszprem"}'>Gyulakeszi</div>
<div class="option" data='{"value":"Gyulamajor","state":"Veszprem"}'>Gyulamajor</div>
<div class="option" data='{"value":"Hajmasker","state":"Veszprem"}'>Hajmasker</div>
<div class="option" data='{"value":"Hajmaspuszta","state":"Veszprem"}'>Hajmaspuszta</div>
<div class="option" data='{"value":"Hajnalhegy","state":"Veszprem"}'>Hajnalhegy</div>
<div class="option" data='{"value":"Halacs","state":"Veszprem"}'>Halacs</div>
<div class="option" data='{"value":"Halacsdulo","state":"Veszprem"}'>Halacsdulo</div>
<div class="option" data='{"value":"Halacsidulo","state":"Veszprem"}'>Halacsidulo</div>
<div class="option" data='{"value":"Halagosi Szollok","state":"Veszprem"}'>Halagosi Szollok</div>
<div class="option" data='{"value":"Halastopuszta","state":"Veszprem"}'>Halastopuszta</div>
<div class="option" data='{"value":"Halimba","state":"Veszprem"}'>Halimba</div>
<div class="option" data='{"value":"Halomhegy","state":"Veszprem"}'>Halomhegy</div>
<div class="option" data='{"value":"Hamori Malom","state":"Veszprem"}'>Hamori Malom</div>
<div class="option" data='{"value":"Hangyalostanya","state":"Veszprem"}'>Hangyalostanya</div>
<div class="option" data='{"value":"Harasztoshegy","state":"Veszprem"}'>Harasztoshegy</div>
<div class="option" data='{"value":"Harsagypuszta","state":"Veszprem"}'>Harsagypuszta</div>
<div class="option" data='{"value":"Harskut","state":"Veszprem"}'>Harskut</div>
<div class="option" data='{"value":"Hatarvolgypuszta","state":"Veszprem"}'>Hatarvolgypuszta</div>
<div class="option" data='{"value":"Hathalmi Szollok","state":"Veszprem"}'>Hathalmi Szollok</div>
<div class="option" data='{"value":"Hathalom","state":"Veszprem"}'>Hathalom</div>
<div class="option" data='{"value":"Hathhalom","state":"Veszprem"}'>Hathhalom</div>
<div class="option" data='{"value":"Hegedusmalom","state":"Veszprem"}'>Hegedusmalom</div>
<div class="option" data='{"value":"Hegy","state":"Veszprem"}'>Hegy</div>
<div class="option" data='{"value":"Hegyalja","state":"Veszprem"}'>Hegyalja</div>
<div class="option" data='{"value":"Hegyaljai Dulo","state":"Veszprem"}'>Hegyaljai Dulo</div>
<div class="option" data='{"value":"Hegyesd","state":"Veszprem"}'>Hegyesd</div>
<div class="option" data='{"value":"Hegyesteto","state":"Veszprem"}'>Hegyesteto</div>
<div class="option" data='{"value":"Hegyesto","state":"Veszprem"}'>Hegyesto</div>
<div class="option" data='{"value":"Hegymagas","state":"Veszprem"}'>Hegymagas</div>
<div class="option" data='{"value":"Hegymegszollohegy","state":"Veszprem"}'>Hegymegszollohegy</div>
<div class="option" data='{"value":"Hegymogiszolo","state":"Veszprem"}'>Hegymogiszolo</div>
<div class="option" data='{"value":"Heitermajor","state":"Veszprem"}'>Heitermajor</div>
<div class="option" data='{"value":"Heiterpuszta","state":"Veszprem"}'>Heiterpuszta</div>
<div class="option" data='{"value":"Herend","state":"Veszprem"}'>Herend</div>
<div class="option" data='{"value":"Hermanmajor","state":"Veszprem"}'>Hermanmajor</div>
<div class="option" data='{"value":"Hermannpuszta","state":"Veszprem"}'>Hermannpuszta</div>
<div class="option" data='{"value":"Hermanpuszta","state":"Veszprem"}'>Hermanpuszta</div>
<div class="option" data='{"value":"Hertelendymajor","state":"Veszprem"}'>Hertelendymajor</div>
<div class="option" data='{"value":"Hertelendyujhely","state":"Veszprem"}'>Hertelendyujhely</div>
<div class="option" data='{"value":"Hetyefo","state":"Veszprem"}'>Hetyefo</div>
<div class="option" data='{"value":"Heviz","state":"Veszprem"}'>Heviz</div>
<div class="option" data='{"value":"Heviz Szent Andras","state":"Veszprem"}'>Heviz Szent Andras</div>
<div class="option" data='{"value":"Hidegkut","state":"Veszprem"}'>Hidegkut</div>
<div class="option" data='{"value":"Hidegvolgymajor","state":"Veszprem"}'>Hidegvolgymajor</div>
<div class="option" data='{"value":"Himfode","state":"Veszprem"}'>Himfode</div>
<div class="option" data='{"value":"Hirschtelep","state":"Veszprem"}'>Hirschtelep</div>
<div class="option" data='{"value":"Hobajmalom","state":"Veszprem"}'>Hobajmalom</div>
<div class="option" data='{"value":"Hobajpuszta","state":"Veszprem"}'>Hobajpuszta</div>
<div class="option" data='{"value":"Hodoser","state":"Veszprem"}'>Hodoser</div>
<div class="option" data='{"value":"Hodoska","state":"Veszprem"}'>Hodoska</div>
<div class="option" data='{"value":"Hodoskamajor","state":"Veszprem"}'>Hodoskamajor</div>
<div class="option" data='{"value":"Hodoskapuszta","state":"Veszprem"}'>Hodoskapuszta</div>
<div class="option" data='{"value":"Homokbodoge","state":"Veszprem"}'>Homokbodoge</div>
<div class="option" data='{"value":"Hompaszkut","state":"Veszprem"}'>Hompaszkut</div>
<div class="option" data='{"value":"Honimalom","state":"Veszprem"}'>Honimalom</div>
<div class="option" data='{"value":"Horgaserimajor","state":"Veszprem"}'>Horgaserimajor</div>
<div class="option" data='{"value":"Horogidulo","state":"Veszprem"}'>Horogidulo</div>
<div class="option" data='{"value":"Horogpuszta","state":"Veszprem"}'>Horogpuszta</div>
<div class="option" data='{"value":"Horvathtanya","state":"Veszprem"}'>Horvathtanya</div>
<div class="option" data='{"value":"Hosszuberek","state":"Veszprem"}'>Hosszuberek</div>
<div class="option" data='{"value":"Hosszudulo","state":"Veszprem"}'>Hosszudulo</div>
<div class="option" data='{"value":"Hosszufoldi Dulo","state":"Veszprem"}'>Hosszufoldi Dulo</div>
<div class="option" data='{"value":"Hosszumezo","state":"Veszprem"}'>Hosszumezo</div>
<div class="option" data='{"value":"Hosszumezopuszta","state":"Veszprem"}'>Hosszumezopuszta</div>
<div class="option" data='{"value":"Hosztot","state":"Veszprem"}'>Hosztot</div>
<div class="option" data='{"value":"Hubertlak","state":"Veszprem"}'>Hubertlak</div>
<div class="option" data='{"value":"Huszarokelopuszta","state":"Veszprem"}'>Huszarokelopuszta</div>
<div class="option" data='{"value":"Igaloreghegy","state":"Veszprem"}'>Igaloreghegy</div>
<div class="option" data='{"value":"Igalpuszta","state":"Veszprem"}'>Igalpuszta</div>
<div class="option" data='{"value":"Iharkut","state":"Veszprem"}'>Iharkut</div>
<div class="option" data='{"value":"Iharos","state":"Veszprem"}'>Iharos</div>
<div class="option" data='{"value":"Iharosi Dulo","state":"Veszprem"}'>Iharosi Dulo</div>
<div class="option" data='{"value":"Ihasz","state":"Veszprem"}'>Ihasz</div>
<div class="option" data='{"value":"Ilkapuszta","state":"Veszprem"}'>Ilkapuszta</div>
<div class="option" data='{"value":"Ilonamajor","state":"Veszprem"}'>Ilonamajor</div>
<div class="option" data='{"value":"Ilonamalom","state":"Veszprem"}'>Ilonamalom</div>
<div class="option" data='{"value":"Imremajor","state":"Veszprem"}'>Imremajor</div>
<div class="option" data='{"value":"Inota","state":"Veszprem"}'>Inota</div>
<div class="option" data='{"value":"Inotai Tanya","state":"Veszprem"}'>Inotai Tanya</div>
<div class="option" data='{"value":"Irtaspuszta","state":"Veszprem"}'>Irtaspuszta</div>
<div class="option" data='{"value":"Istvanmajor","state":"Veszprem"}'>Istvanmajor</div>
<div class="option" data='{"value":"Iszkaz","state":"Veszprem"}'>Iszkaz</div>
<div class="option" data='{"value":"Izsotelep","state":"Veszprem"}'>Izsotelep</div>
<div class="option" data='{"value":"Janmajor","state":"Veszprem"}'>Janmajor</div>
<div class="option" data='{"value":"Janoshazidulo","state":"Veszprem"}'>Janoshazidulo</div>
<div class="option" data='{"value":"Janosmajor","state":"Veszprem"}'>Janosmajor</div>
<div class="option" data='{"value":"Jarifold","state":"Veszprem"}'>Jarifold</div>
<div class="option" data='{"value":"Jarohaza","state":"Veszprem"}'>Jarohaza</div>
<div class="option" data='{"value":"Jasd","state":"Veszprem"}'>Jasd</div>
<div class="option" data='{"value":"Jasdi Tanyak","state":"Veszprem"}'>Jasdi Tanyak</div>
<div class="option" data='{"value":"Jenotelek","state":"Veszprem"}'>Jenotelek</div>
<div class="option" data='{"value":"Jenotelekpuszta","state":"Veszprem"}'>Jenotelekpuszta</div>
<div class="option" data='{"value":"Jolanakna","state":"Veszprem"}'>Jolanakna</div>
<div class="option" data='{"value":"Jonasmajor","state":"Veszprem"}'>Jonasmajor</div>
<div class="option" data='{"value":"Jonaspuszta","state":"Veszprem"}'>Jonaspuszta</div>
<div class="option" data='{"value":"Juliamajor","state":"Veszprem"}'>Juliamajor</div>
<div class="option" data='{"value":"Jutas","state":"Veszprem"}'>Jutas</div>
<div class="option" data='{"value":"Kacsajtos","state":"Veszprem"}'>Kacsajtos</div>
<div class="option" data='{"value":"Kacsajtosdulo","state":"Veszprem"}'>Kacsajtosdulo</div>
<div class="option" data='{"value":"Kadarta","state":"Veszprem"}'>Kadarta</div>
<div class="option" data='{"value":"Kakasmajor","state":"Veszprem"}'>Kakasmajor</div>
<div class="option" data='{"value":"Kalicsmajor","state":"Veszprem"}'>Kalicsmajor</div>
<div class="option" data='{"value":"Kalmanberek","state":"Veszprem"}'>Kalmanberek</div>
<div class="option" data='{"value":"Kamonberek","state":"Veszprem"}'>Kamonberek</div>
<div class="option" data='{"value":"Kamond","state":"Veszprem"}'>Kamond</div>
<div class="option" data='{"value":"Kamonya","state":"Veszprem"}'>Kamonya</div>
<div class="option" data='{"value":"Kapolcs","state":"Veszprem"}'>Kapolcs</div>
<div class="option" data='{"value":"Kaptalanfa","state":"Veszprem"}'>Kaptalanfa</div>
<div class="option" data='{"value":"Kaptalanfured","state":"Veszprem"}'>Kaptalanfured</div>
<div class="option" data='{"value":"Kaptalantoti","state":"Veszprem"}'>Kaptalantoti</div>
<div class="option" data='{"value":"Karako","state":"Veszprem"}'>Karako</div>
<div class="option" data='{"value":"Karakoszorcsok","state":"Veszprem"}'>Karakoszorcsok</div>
<div class="option" data='{"value":"Kardosret","state":"Veszprem"}'>Kardosret</div>
<div class="option" data='{"value":"Karolyhaza","state":"Veszprem"}'>Karolyhaza</div>
<div class="option" data='{"value":"Karolyhazapuszta","state":"Veszprem"}'>Karolyhazapuszta</div>
<div class="option" data='{"value":"Karolyitanya","state":"Veszprem"}'>Karolyitanya</div>
<div class="option" data='{"value":"Katlankut","state":"Veszprem"}'>Katlankut</div>
<div class="option" data='{"value":"Kekidulo","state":"Veszprem"}'>Kekidulo</div>
<div class="option" data='{"value":"Kekkut","state":"Veszprem"}'>Kekkut</div>
<div class="option" data='{"value":"Kekkutihegy","state":"Veszprem"}'>Kekkutihegy</div>
<div class="option" data='{"value":"Kemeneshogyesz","state":"Veszprem"}'>Kemeneshogyesz</div>
<div class="option" data='{"value":"Kemeneshogyez","state":"Veszprem"}'>Kemeneshogyez</div>
<div class="option" data='{"value":"Kemenespuszta","state":"Veszprem"}'>Kemenespuszta</div>
<div class="option" data='{"value":"Kemenesszentpeter","state":"Veszprem"}'>Kemenesszentpeter</div>
<div class="option" data='{"value":"Kenyerimajor","state":"Veszprem"}'>Kenyerimajor</div>
<div class="option" data='{"value":"Kerekimajor","state":"Veszprem"}'>Kerekimajor</div>
<div class="option" data='{"value":"Kerekipuszta","state":"Veszprem"}'>Kerekipuszta</div>
<div class="option" data='{"value":"Keresztmajor","state":"Veszprem"}'>Keresztmajor</div>
<div class="option" data='{"value":"Keresztur","state":"Veszprem"}'>Keresztur</div>
<div class="option" data='{"value":"Kerta","state":"Veszprem"}'>Kerta</div>
<div class="option" data='{"value":"Kertalja","state":"Veszprem"}'>Kertalja</div>
<div class="option" data='{"value":"Kertesko","state":"Veszprem"}'>Kertesko</div>
<div class="option" data='{"value":"Keszlertanya","state":"Veszprem"}'>Keszlertanya</div>
<div class="option" data='{"value":"Kettornyulak","state":"Veszprem"}'>Kettornyulak</div>
<div class="option" data='{"value":"Kiliantelep","state":"Veszprem"}'>Kiliantelep</div>
<div class="option" data='{"value":"Kincseshaz","state":"Veszprem"}'>Kincseshaz</div>
<div class="option" data='{"value":"Kinota","state":"Veszprem"}'>Kinota</div>
<div class="option" data='{"value":"Kinotadulo","state":"Veszprem"}'>Kinotadulo</div>
<div class="option" data='{"value":"Kiralyszentistvan","state":"Veszprem"}'>Kiralyszentistvan</div>
<div class="option" data='{"value":"Kisacsad Allami Gazdasag","state":"Veszprem"}'>Kisacsad Allami Gazdasag</div>
<div class="option" data='{"value":"Kisacsadmajor","state":"Veszprem"}'>Kisacsadmajor</div>
<div class="option" data='{"value":"Kisapati","state":"Veszprem"}'>Kisapati</div>
<div class="option" data='{"value":"Kisapati Tanyak","state":"Veszprem"}'>Kisapati Tanyak</div>
<div class="option" data='{"value":"Kisapatihegy","state":"Veszprem"}'>Kisapatihegy</div>
<div class="option" data='{"value":"Kisbaratipuszta","state":"Veszprem"}'>Kisbaratipuszta</div>
<div class="option" data='{"value":"Kisberendpuszta","state":"Veszprem"}'>Kisberendpuszta</div>
<div class="option" data='{"value":"Kisberzseny","state":"Veszprem"}'>Kisberzseny</div>
<div class="option" data='{"value":"Kisbogdany","state":"Veszprem"}'>Kisbogdany</div>
<div class="option" data='{"value":"Kiscsosz","state":"Veszprem"}'>Kiscsosz</div>
<div class="option" data='{"value":"Kiscsoszi Tanya","state":"Veszprem"}'>Kiscsoszi Tanya</div>
<div class="option" data='{"value":"Kisdem","state":"Veszprem"}'>Kisdem</div>
<div class="option" data='{"value":"Kisdempuszta","state":"Veszprem"}'>Kisdempuszta</div>
<div class="option" data='{"value":"Kisdorgicse","state":"Veszprem"}'>Kisdorgicse</div>
<div class="option" data='{"value":"Kisdudar","state":"Veszprem"}'>Kisdudar</div>
<div class="option" data='{"value":"Kiserdo","state":"Veszprem"}'>Kiserdo</div>
<div class="option" data='{"value":"Kisganna","state":"Veszprem"}'>Kisganna</div>
<div class="option" data='{"value":"Kishaz","state":"Veszprem"}'>Kishaz</div>
<div class="option" data='{"value":"Kishazapuszta","state":"Veszprem"}'>Kishazapuszta</div>
<div class="option" data='{"value":"Kishegy","state":"Veszprem"}'>Kishegy</div>
<div class="option" data='{"value":"Kiskamond","state":"Veszprem"}'>Kiskamond</div>
<div class="option" data='{"value":"Kiskovacsimajor","state":"Veszprem"}'>Kiskovacsimajor</div>
<div class="option" data='{"value":"Kiskut","state":"Veszprem"}'>Kiskut</div>
<div class="option" data='{"value":"Kislod","state":"Veszprem"}'>Kislod</div>
<div class="option" data='{"value":"Kislodi Tanyak","state":"Veszprem"}'>Kislodi Tanyak</div>
<div class="option" data='{"value":"Kismalom","state":"Veszprem"}'>Kismalom</div>
<div class="option" data='{"value":"Kismatyushaza","state":"Veszprem"}'>Kismatyushaza</div>
<div class="option" data='{"value":"Kisorspuszta","state":"Veszprem"}'>Kisorspuszta</div>
<div class="option" data='{"value":"Kisotvospuszta","state":"Veszprem"}'>Kisotvospuszta</div>
<div class="option" data='{"value":"Kispart","state":"Veszprem"}'>Kispart</div>
<div class="option" data='{"value":"Kispirit","state":"Veszprem"}'>Kispirit</div>
<div class="option" data='{"value":"Kispodarpuszta","state":"Veszprem"}'>Kispodarpuszta</div>
<div class="option" data='{"value":"Kispuszta","state":"Veszprem"}'>Kispuszta</div>
<div class="option" data='{"value":"Kisszepalma","state":"Veszprem"}'>Kisszepalma</div>
<div class="option" data='{"value":"Kisszepalmapuszta","state":"Veszprem"}'>Kisszepalmapuszta</div>
<div class="option" data='{"value":"Kisszollos","state":"Veszprem"}'>Kisszollos</div>
<div class="option" data='{"value":"Kisszolos","state":"Veszprem"}'>Kisszolos</div>
<div class="option" data='{"value":"Kistarkanypuszta","state":"Veszprem"}'>Kistarkanypuszta</div>
<div class="option" data='{"value":"Kistes","state":"Veszprem"}'>Kistes</div>
<div class="option" data='{"value":"Kistespuszta","state":"Veszprem"}'>Kistespuszta</div>
<div class="option" data='{"value":"Kistima","state":"Veszprem"}'>Kistima</div>
<div class="option" data='{"value":"Kistimapuszta","state":"Veszprem"}'>Kistimapuszta</div>
<div class="option" data='{"value":"Kistoidulo","state":"Veszprem"}'>Kistoidulo</div>
<div class="option" data='{"value":"Kisvagas","state":"Veszprem"}'>Kisvagas</div>
<div class="option" data='{"value":"Klaratelep","state":"Veszprem"}'>Klaratelep</div>
<div class="option" data='{"value":"Kobolkut","state":"Veszprem"}'>Kobolkut</div>
<div class="option" data='{"value":"Koharimalom","state":"Veszprem"}'>Koharimalom</div>
<div class="option" data='{"value":"Kohegypuszta","state":"Veszprem"}'>Kohegypuszta</div>
<div class="option" data='{"value":"Kokoporso","state":"Veszprem"}'>Kokoporso</div>
<div class="option" data='{"value":"Kolonia","state":"Veszprem"}'>Kolonia</div>
<div class="option" data='{"value":"Kolontar","state":"Veszprem"}'>Kolontar</div>
<div class="option" data='{"value":"Komalom","state":"Veszprem"}'>Komalom</div>
<div class="option" data='{"value":"Komalomirtas","state":"Veszprem"}'>Komalomirtas</div>
<div class="option" data='{"value":"Kopaszhegy","state":"Veszprem"}'>Kopaszhegy</div>
<div class="option" data='{"value":"Korisgyor","state":"Veszprem"}'>Korisgyor</div>
<div class="option" data='{"value":"Kovagoors","state":"Veszprem"}'>Kovagoors</div>
<div class="option" data='{"value":"Kovesgyur","state":"Veszprem"}'>Kovesgyur</div>
<div class="option" data='{"value":"Kovesgyurpuszta","state":"Veszprem"}'>Kovesgyurpuszta</div>
<div class="option" data='{"value":"Koveshegy","state":"Veszprem"}'>Koveshegy</div>
<div class="option" data='{"value":"Koveskal","state":"Veszprem"}'>Koveskal</div>
<div class="option" data='{"value":"Koveskutpuszta","state":"Veszprem"}'>Koveskutpuszta</div>
<div class="option" data='{"value":"Kozbirtokossagi Tanya","state":"Veszprem"}'>Kozbirtokossagi Tanya</div>
<div class="option" data='{"value":"Kozepiszkaz","state":"Veszprem"}'>Kozepiszkaz</div>
<div class="option" data='{"value":"Kozepzok","state":"Veszprem"}'>Kozepzok</div>
<div class="option" data='{"value":"Kryptontelep","state":"Veszprem"}'>Kryptontelep</div>
<div class="option" data='{"value":"Kulsovat","state":"Veszprem"}'>Kulsovat</div>
<div class="option" data='{"value":"Kungos","state":"Veszprem"}'>Kungos</div>
<div class="option" data='{"value":"Kup","state":"Veszprem"}'>Kup</div>
<div class="option" data='{"value":"Labdi","state":"Veszprem"}'>Labdi</div>
<div class="option" data='{"value":"Lajosmajor","state":"Veszprem"}'>Lajosmajor</div>
<div class="option" data='{"value":"Lakatmajor","state":"Veszprem"}'>Lakatmajor</div>
<div class="option" data='{"value":"Lakdulo","state":"Veszprem"}'>Lakdulo</div>
<div class="option" data='{"value":"Lampartmajor","state":"Veszprem"}'>Lampartmajor</div>
<div class="option" data='{"value":"Lampertmajor","state":"Veszprem"}'>Lampertmajor</div>
<div class="option" data='{"value":"Laszlomajor","state":"Veszprem"}'>Laszlomajor</div>
<div class="option" data='{"value":"Lehertihegy","state":"Veszprem"}'>Lehertihegy</div>
<div class="option" data='{"value":"Lesencefalu","state":"Veszprem"}'>Lesencefalu</div>
<div class="option" data='{"value":"Lesenceistvand","state":"Veszprem"}'>Lesenceistvand</div>
<div class="option" data='{"value":"Lesencetomaj","state":"Veszprem"}'>Lesencetomaj</div>
<div class="option" data='{"value":"Liter","state":"Veszprem"}'>Liter</div>
<div class="option" data='{"value":"Lofflermalom","state":"Veszprem"}'>Lofflermalom</div>
<div class="option" data='{"value":"Lokut","state":"Veszprem"}'>Lokut</div>
<div class="option" data='{"value":"Lorinte","state":"Veszprem"}'>Lorinte</div>
<div class="option" data='{"value":"Lorintepuszta","state":"Veszprem"}'>Lorintepuszta</div>
<div class="option" data='{"value":"Lovas","state":"Veszprem"}'>Lovas</div>
<div class="option" data='{"value":"Lovaszpatona","state":"Veszprem"}'>Lovaszpatona</div>
<div class="option" data='{"value":"Lucernas","state":"Veszprem"}'>Lucernas</div>
<div class="option" data='{"value":"Lukahaza","state":"Veszprem"}'>Lukahaza</div>
<div class="option" data='{"value":"Lukatanya","state":"Veszprem"}'>Lukatanya</div>
<div class="option" data='{"value":"Lukod","state":"Veszprem"}'>Lukod</div>
<div class="option" data='{"value":"Magyarbarnag","state":"Veszprem"}'>Magyarbarnag</div>
<div class="option" data='{"value":"Magyargencs","state":"Veszprem"}'>Magyargencs</div>
<div class="option" data='{"value":"Magyarosdomb","state":"Veszprem"}'>Magyarosdomb</div>
<div class="option" data='{"value":"Magyarpolany","state":"Veszprem"}'>Magyarpolany</div>
<div class="option" data='{"value":"Makra","state":"Veszprem"}'>Makra</div>
<div class="option" data='{"value":"Maldulo","state":"Veszprem"}'>Maldulo</div>
<div class="option" data='{"value":"Malmok","state":"Veszprem"}'>Malmok</div>
<div class="option" data='{"value":"Malom","state":"Veszprem"}'>Malom</div>
<div class="option" data='{"value":"Malomkoz","state":"Veszprem"}'>Malomkoz</div>
<div class="option" data='{"value":"Malommelletti Dulo","state":"Veszprem"}'>Malommelletti Dulo</div>
<div class="option" data='{"value":"Malomret","state":"Veszprem"}'>Malomret</div>
<div class="option" data='{"value":"Malomsok","state":"Veszprem"}'>Malomsok</div>
<div class="option" data='{"value":"Mama","state":"Veszprem"}'>Mama</div>
<div class="option" data='{"value":"Mamapuszta","state":"Veszprem"}'>Mamapuszta</div>
<div class="option" data='{"value":"Marcalgergelyi","state":"Veszprem"}'>Marcalgergelyi</div>
<div class="option" data='{"value":"Marcaltelep","state":"Veszprem"}'>Marcaltelep</div>
<div class="option" data='{"value":"Marcalto","state":"Veszprem"}'>Marcalto</div>
<div class="option" data='{"value":"Mariamajor","state":"Veszprem"}'>Mariamajor</div>
<div class="option" data='{"value":"Mariapuszta","state":"Veszprem"}'>Mariapuszta</div>
<div class="option" data='{"value":"Marko","state":"Veszprem"}'>Marko</div>
<div class="option" data='{"value":"Matehegy","state":"Veszprem"}'>Matehegy</div>
<div class="option" data='{"value":"Matyushaza","state":"Veszprem"}'>Matyushaza</div>
<div class="option" data='{"value":"Mauertanya","state":"Veszprem"}'>Mauertanya</div>
<div class="option" data='{"value":"Meggyeserdo","state":"Veszprem"}'>Meggyeserdo</div>
<div class="option" data='{"value":"Meggyespuszta","state":"Veszprem"}'>Meggyespuszta</div>
<div class="option" data='{"value":"Megyer","state":"Veszprem"}'>Megyer</div>
<div class="option" data='{"value":"Megyes Erdo","state":"Veszprem"}'>Megyes Erdo</div>
<div class="option" data='{"value":"Meleghegy","state":"Veszprem"}'>Meleghegy</div>
<div class="option" data='{"value":"Melittamajor","state":"Veszprem"}'>Melittamajor</div>
<div class="option" data='{"value":"Mencshely","state":"Veszprem"}'>Mencshely</div>
<div class="option" data='{"value":"Menesjaras","state":"Veszprem"}'>Menesjaras</div>
<div class="option" data='{"value":"Menesjaraspuszta","state":"Veszprem"}'>Menesjaraspuszta</div>
<div class="option" data='{"value":"Meszmu","state":"Veszprem"}'>Meszmu</div>
<div class="option" data='{"value":"Mesztelep","state":"Veszprem"}'>Mesztelep</div>
<div class="option" data='{"value":"Mezeshegy","state":"Veszprem"}'>Mezeshegy</div>
<div class="option" data='{"value":"Mezodidulo","state":"Veszprem"}'>Mezodidulo</div>
<div class="option" data='{"value":"Mezolak","state":"Veszprem"}'>Mezolak</div>
<div class="option" data='{"value":"Mihalyhaza","state":"Veszprem"}'>Mihalyhaza</div>
<div class="option" data='{"value":"Mikloshaza","state":"Veszprem"}'>Mikloshaza</div>
<div class="option" data='{"value":"Miklosmajor","state":"Veszprem"}'>Miklosmajor</div>
<div class="option" data='{"value":"Mindszentkalla","state":"Veszprem"}'>Mindszentkalla</div>
<div class="option" data='{"value":"Mogszeg","state":"Veszprem"}'>Mogszeg</div>
<div class="option" data='{"value":"Mogyoroshegy","state":"Veszprem"}'>Mogyoroshegy</div>
<div class="option" data='{"value":"Molnartanya","state":"Veszprem"}'>Molnartanya</div>
<div class="option" data='{"value":"Monostorapati","state":"Veszprem"}'>Monostorapati</div>
<div class="option" data='{"value":"Monoszlo","state":"Veszprem"}'>Monoszlo</div>
<div class="option" data='{"value":"Mullermalom","state":"Veszprem"}'>Mullermalom</div>
<div class="option" data='{"value":"Munkastelep","state":"Veszprem"}'>Munkastelep</div>
<div class="option" data='{"value":"Nadas","state":"Veszprem"}'>Nadas</div>
<div class="option" data='{"value":"Nagyacsad","state":"Veszprem"}'>Nagyacsad</div>
<div class="option" data='{"value":"Nagyalasony","state":"Veszprem"}'>Nagyalasony</div>
<div class="option" data='{"value":"Nagyberzseny","state":"Veszprem"}'>Nagyberzseny</div>
<div class="option" data='{"value":"Nagyberzsenypuszta","state":"Veszprem"}'>Nagyberzsenypuszta</div>
<div class="option" data='{"value":"Nagybogdany","state":"Veszprem"}'>Nagybogdany</div>
<div class="option" data='{"value":"Nagydem","state":"Veszprem"}'>Nagydem</div>
<div class="option" data='{"value":"Nagyesztergar","state":"Veszprem"}'>Nagyesztergar</div>
<div class="option" data='{"value":"Nagyfenyo","state":"Veszprem"}'>Nagyfenyo</div>
<div class="option" data='{"value":"Nagyfenyodulo","state":"Veszprem"}'>Nagyfenyodulo</div>
<div class="option" data='{"value":"Nagyganna","state":"Veszprem"}'>Nagyganna</div>
<div class="option" data='{"value":"Nagygyimot","state":"Veszprem"}'>Nagygyimot</div>
<div class="option" data='{"value":"Nagyigalmajor","state":"Veszprem"}'>Nagyigalmajor</div>
<div class="option" data='{"value":"Nagykamond","state":"Veszprem"}'>Nagykamond</div>
<div class="option" data='{"value":"Nagykutdulo","state":"Veszprem"}'>Nagykutdulo</div>
<div class="option" data='{"value":"Nagypirit","state":"Veszprem"}'>Nagypirit</div>
<div class="option" data='{"value":"Nagyretidulo","state":"Veszprem"}'>Nagyretidulo</div>
<div class="option" data='{"value":"Nagytarkanypuszta","state":"Veszprem"}'>Nagytarkanypuszta</div>
<div class="option" data='{"value":"Nagytelep","state":"Veszprem"}'>Nagytelep</div>
<div class="option" data='{"value":"Nagytevel","state":"Veszprem"}'>Nagytevel</div>
<div class="option" data='{"value":"Nagyvazsony","state":"Veszprem"}'>Nagyvazsony</div>
<div class="option" data='{"value":"Nandormajor","state":"Veszprem"}'>Nandormajor</div>
<div class="option" data='{"value":"Nemesgorzsony","state":"Veszprem"}'>Nemesgorzsony</div>
<div class="option" data='{"value":"Nemesgulacs","state":"Veszprem"}'>Nemesgulacs</div>
<div class="option" data='{"value":"Nemeshany","state":"Veszprem"}'>Nemeshany</div>
<div class="option" data='{"value":"Nemeshanyi Tanya","state":"Veszprem"}'>Nemeshanyi Tanya</div>
<div class="option" data='{"value":"Nemesleanyfalu","state":"Veszprem"}'>Nemesleanyfalu</div>
<div class="option" data='{"value":"Nemespecsely","state":"Veszprem"}'>Nemespecsely</div>
<div class="option" data='{"value":"Nemespecselyi Puszta","state":"Veszprem"}'>Nemespecselyi Puszta</div>
<div class="option" data='{"value":"Nemesszalok","state":"Veszprem"}'>Nemesszalok</div>
<div class="option" data='{"value":"Nemestordemic","state":"Veszprem"}'>Nemestordemic</div>
<div class="option" data='{"value":"Nemesvamos","state":"Veszprem"}'>Nemesvamos</div>
<div class="option" data='{"value":"Nemesvamosi Tanyak","state":"Veszprem"}'>Nemesvamosi Tanyak</div>
<div class="option" data='{"value":"Nemesvita","state":"Veszprem"}'>Nemesvita</div>
<div class="option" data='{"value":"Nemeszalok","state":"Veszprem"}'>Nemeszalok</div>
<div class="option" data='{"value":"Nemetbanya","state":"Veszprem"}'>Nemetbanya</div>
<div class="option" data='{"value":"Nemetbarnag","state":"Veszprem"}'>Nemetbarnag</div>
<div class="option" data='{"value":"Nemetipuszta","state":"Veszprem"}'>Nemetipuszta</div>
<div class="option" data='{"value":"Norap","state":"Veszprem"}'>Norap</div>
<div class="option" data='{"value":"Noszlop","state":"Veszprem"}'>Noszlop</div>
<div class="option" data='{"value":"Noszlopi Tanya","state":"Veszprem"}'>Noszlopi Tanya</div>
<div class="option" data='{"value":"Novak","state":"Veszprem"}'>Novak</div>
<div class="option" data='{"value":"Nyarad","state":"Veszprem"}'>Nyarad</div>
<div class="option" data='{"value":"Nyirad","state":"Veszprem"}'>Nyirad</div>
<div class="option" data='{"value":"Nyiresitanya","state":"Veszprem"}'>Nyiresitanya</div>
<div class="option" data='{"value":"Nyirespuszta","state":"Veszprem"}'>Nyirespuszta</div>
<div class="option" data='{"value":"Nyirestanya","state":"Veszprem"}'>Nyirestanya</div>
<div class="option" data='{"value":"Nyirlak","state":"Veszprem"}'>Nyirlak</div>
<div class="option" data='{"value":"Nyirlakpuszta","state":"Veszprem"}'>Nyirlakpuszta</div>
<div class="option" data='{"value":"Nyirma","state":"Veszprem"}'>Nyirma</div>
<div class="option" data='{"value":"Obanyapuszta","state":"Veszprem"}'>Obanyapuszta</div>
<div class="option" data='{"value":"Obudavar","state":"Veszprem"}'>Obudavar</div>
<div class="option" data='{"value":"Ocs","state":"Veszprem"}'>Ocs</div>
<div class="option" data='{"value":"Odobronte","state":"Veszprem"}'>Odobronte</div>
<div class="option" data='{"value":"Odorogd","state":"Veszprem"}'>Odorogd</div>
<div class="option" data='{"value":"Odorogdpuszta","state":"Veszprem"}'>Odorogdpuszta</div>
<div class="option" data='{"value":"Olaszfalu","state":"Veszprem"}'>Olaszfalu</div>
<div class="option" data='{"value":"Omalomsok","state":"Veszprem"}'>Omalomsok</div>
<div class="option" data='{"value":"Oreg Dobronte","state":"Veszprem"}'>Oreg Dobronte</div>
<div class="option" data='{"value":"Oreghalas","state":"Veszprem"}'>Oreghalas</div>
<div class="option" data='{"value":"Oreghegy","state":"Veszprem"}'>Oreghegy</div>
<div class="option" data='{"value":"Oreghegydulo","state":"Veszprem"}'>Oreghegydulo</div>
<div class="option" data='{"value":"Oregtima","state":"Veszprem"}'>Oregtima</div>
<div class="option" data='{"value":"Oroszi","state":"Veszprem"}'>Oroszi</div>
<div class="option" data='{"value":"Orvenyes","state":"Veszprem"}'>Orvenyes</div>
<div class="option" data='{"value":"Osi","state":"Veszprem"}'>Osi</div>
<div class="option" data='{"value":"Osku","state":"Veszprem"}'>Osku</div>
<div class="option" data='{"value":"Otvos","state":"Veszprem"}'>Otvos</div>
<div class="option" data='{"value":"Padrag","state":"Veszprem"}'>Padrag</div>
<div class="option" data='{"value":"Padragkut","state":"Veszprem"}'>Padragkut</div>
<div class="option" data='{"value":"Palffytanya","state":"Veszprem"}'>Palffytanya</div>
<div class="option" data='{"value":"Palhazapuszta","state":"Veszprem"}'>Palhazapuszta</div>
<div class="option" data='{"value":"Palihalas","state":"Veszprem"}'>Palihalas</div>
<div class="option" data='{"value":"Palihalaspuszta","state":"Veszprem"}'>Palihalaspuszta</div>
<div class="option" data='{"value":"Palinkahaz","state":"Veszprem"}'>Palinkahaz</div>
<div class="option" data='{"value":"Palinkahaza","state":"Veszprem"}'>Palinkahaza</div>
<div class="option" data='{"value":"Palinkahazpuszta","state":"Veszprem"}'>Palinkahazpuszta</div>
<div class="option" data='{"value":"Palkove","state":"Veszprem"}'>Palkove</div>
<div class="option" data='{"value":"Palmajor","state":"Veszprem"}'>Palmajor</div>
<div class="option" data='{"value":"Palotaaljadulo","state":"Veszprem"}'>Palotaaljadulo</div>
<div class="option" data='{"value":"Paloznak","state":"Veszprem"}'>Paloznak</div>
<div class="option" data='{"value":"Pantlika","state":"Veszprem"}'>Pantlika</div>
<div class="option" data='{"value":"Pantlikamajor","state":"Veszprem"}'>Pantlikamajor</div>
<div class="option" data='{"value":"Papa","state":"Veszprem"}'>Papa</div>
<div class="option" data='{"value":"Papadereske","state":"Veszprem"}'>Papadereske</div>
<div class="option" data='{"value":"Papaimajor","state":"Veszprem"}'>Papaimajor</div>
<div class="option" data='{"value":"Papakovacsi","state":"Veszprem"}'>Papakovacsi</div>
<div class="option" data='{"value":"Papanyoger","state":"Veszprem"}'>Papanyoger</div>
<div class="option" data='{"value":"Papasalamon","state":"Veszprem"}'>Papasalamon</div>
<div class="option" data='{"value":"Papateszer","state":"Veszprem"}'>Papateszer</div>
<div class="option" data='{"value":"Paphegy","state":"Veszprem"}'>Paphegy</div>
<div class="option" data='{"value":"Papirgyari Lakotelep","state":"Veszprem"}'>Papirgyari Lakotelep</div>
<div class="option" data='{"value":"Papkeszi","state":"Veszprem"}'>Papkeszi</div>
<div class="option" data='{"value":"Paresborc","state":"Veszprem"}'>Paresborc</div>
<div class="option" data='{"value":"Patacspuszta","state":"Veszprem"}'>Patacspuszta</div>
<div class="option" data='{"value":"Pecsely","state":"Veszprem"}'>Pecsely</div>
<div class="option" data='{"value":"Pecselyipuszta","state":"Veszprem"}'>Pecselyipuszta</div>
<div class="option" data='{"value":"Penzesgyor","state":"Veszprem"}'>Penzesgyor</div>
<div class="option" data='{"value":"Penzeskut","state":"Veszprem"}'>Penzeskut</div>
<div class="option" data='{"value":"Peremarton","state":"Veszprem"}'>Peremarton</div>
<div class="option" data='{"value":"Perlakimajor","state":"Veszprem"}'>Perlakimajor</div>
<div class="option" data='{"value":"Peterhegy","state":"Veszprem"}'>Peterhegy</div>
<div class="option" data='{"value":"Peterhegydulo","state":"Veszprem"}'>Peterhegydulo</div>
<div class="option" data='{"value":"Petfurdo","state":"Veszprem"}'>Petfurdo</div>
<div class="option" data='{"value":"Pincelakas","state":"Veszprem"}'>Pincelakas</div>
<div class="option" data='{"value":"Pincesor","state":"Veszprem"}'>Pincesor</div>
<div class="option" data='{"value":"Pityomajor","state":"Veszprem"}'>Pityomajor</div>
<div class="option" data='{"value":"Pokahegy","state":"Veszprem"}'>Pokahegy</div>
<div class="option" data='{"value":"Polgartanya","state":"Veszprem"}'>Polgartanya</div>
<div class="option" data='{"value":"Poloskeitanya","state":"Veszprem"}'>Poloskeitanya</div>
<div class="option" data='{"value":"Ponyvad","state":"Veszprem"}'>Ponyvad</div>
<div class="option" data='{"value":"Porszalok","state":"Veszprem"}'>Porszalok</div>
<div class="option" data='{"value":"Porva","state":"Veszprem"}'>Porva</div>
<div class="option" data='{"value":"Potyapaltelek","state":"Veszprem"}'>Potyapaltelek</div>
<div class="option" data='{"value":"Potyogotanya","state":"Veszprem"}'>Potyogotanya</div>
<div class="option" data='{"value":"Pula","state":"Veszprem"}'>Pula</div>
<div class="option" data='{"value":"Pusztagyimot","state":"Veszprem"}'>Pusztagyimot</div>
<div class="option" data='{"value":"Pusztagyimot Also","state":"Veszprem"}'>Pusztagyimot Also</div>
<div class="option" data='{"value":"Pusztagyimot Felso","state":"Veszprem"}'>Pusztagyimot Felso</div>
<div class="option" data='{"value":"Pusztamiske","state":"Veszprem"}'>Pusztamiske</div>
<div class="option" data='{"value":"Putrimajor","state":"Veszprem"}'>Putrimajor</div>
<div class="option" data='{"value":"Rabkerteszet","state":"Veszprem"}'>Rabkerteszet</div>
<div class="option" data='{"value":"Raczmajor","state":"Veszprem"}'>Raczmajor</div>
<div class="option" data='{"value":"Radopuszta","state":"Veszprem"}'>Radopuszta</div>
<div class="option" data='{"value":"Raposka","state":"Veszprem"}'>Raposka</div>
<div class="option" data='{"value":"Raposkai Major","state":"Veszprem"}'>Raposkai Major</div>
<div class="option" data='{"value":"Raskopuszta","state":"Veszprem"}'>Raskopuszta</div>
<div class="option" data='{"value":"Remecse","state":"Veszprem"}'>Remecse</div>
<div class="option" data='{"value":"Remecsetanya","state":"Veszprem"}'>Remecsetanya</div>
<div class="option" data='{"value":"Remegtanya","state":"Veszprem"}'>Remegtanya</div>
<div class="option" data='{"value":"Remenytelep","state":"Veszprem"}'>Remenytelep</div>
<div class="option" data='{"value":"Remete","state":"Veszprem"}'>Remete</div>
<div class="option" data='{"value":"Remigpuszta","state":"Veszprem"}'>Remigpuszta</div>
<div class="option" data='{"value":"Rendeki Malom","state":"Veszprem"}'>Rendeki Malom</div>
<div class="option" data='{"value":"Repasmajor","state":"Veszprem"}'>Repasmajor</div>
<div class="option" data='{"value":"Retimalom","state":"Veszprem"}'>Retimalom</div>
<div class="option" data='{"value":"Retipuszta","state":"Veszprem"}'>Retipuszta</div>
<div class="option" data='{"value":"Retredulo","state":"Veszprem"}'>Retredulo</div>
<div class="option" data='{"value":"Retsarok","state":"Veszprem"}'>Retsarok</div>
<div class="option" data='{"value":"Retsarokmajor","state":"Veszprem"}'>Retsarokmajor</div>
<div class="option" data='{"value":"Revfulop","state":"Veszprem"}'>Revfulop</div>
<div class="option" data='{"value":"Rigacs","state":"Veszprem"}'>Rigacs</div>
<div class="option" data='{"value":"Rizapuszta","state":"Veszprem"}'>Rizapuszta</div>
<div class="option" data='{"value":"Rokalikok","state":"Veszprem"}'>Rokalikok</div>
<div class="option" data='{"value":"Rokapuszta","state":"Veszprem"}'>Rokapuszta</div>
<div class="option" data='{"value":"Rostaspuszta","state":"Veszprem"}'>Rostaspuszta</div>
<div class="option" data='{"value":"Rozsamajor","state":"Veszprem"}'>Rozsamajor</div>
<div class="option" data='{"value":"Sabar","state":"Veszprem"}'>Sabar</div>
<div class="option" data='{"value":"Sabarhegy","state":"Veszprem"}'>Sabarhegy</div>
<div class="option" data='{"value":"Sabariszolo","state":"Veszprem"}'>Sabariszolo</div>
<div class="option" data='{"value":"Safrankert","state":"Veszprem"}'>Safrankert</div>
<div class="option" data='{"value":"Sagpuszta","state":"Veszprem"}'>Sagpuszta</div>
<div class="option" data='{"value":"Salfold","state":"Veszprem"}'>Salfold</div>
<div class="option" data='{"value":"Sandormajor","state":"Veszprem"}'>Sandormajor</div>
<div class="option" data='{"value":"Sandortanya","state":"Veszprem"}'>Sandortanya</div>
<div class="option" data='{"value":"Saripuszta","state":"Veszprem"}'>Saripuszta</div>
<div class="option" data='{"value":"Sarkanypuszta","state":"Veszprem"}'>Sarkanypuszta</div>
<div class="option" data='{"value":"Sarlaymajor","state":"Veszprem"}'>Sarlaymajor</div>
<div class="option" data='{"value":"Sarosfomajor","state":"Veszprem"}'>Sarosfomajor</div>
<div class="option" data='{"value":"Sarosfopuszta","state":"Veszprem"}'>Sarosfopuszta</div>
<div class="option" data='{"value":"Sarvaly","state":"Veszprem"}'>Sarvaly</div>
<div class="option" data='{"value":"Sarvalypuszta","state":"Veszprem"}'>Sarvalypuszta</div>
<div class="option" data='{"value":"Saska","state":"Veszprem"}'>Saska</div>
<div class="option" data='{"value":"Satorhegy","state":"Veszprem"}'>Satorhegy</div>
<div class="option" data='{"value":"Satormapuszta","state":"Veszprem"}'>Satormapuszta</div>
<div class="option" data='{"value":"Savanyukut","state":"Veszprem"}'>Savanyukut</div>
<div class="option" data='{"value":"Savolypuszta","state":"Veszprem"}'>Savolypuszta</div>
<div class="option" data='{"value":"Schellermalom","state":"Veszprem"}'>Schellermalom</div>
<div class="option" data='{"value":"Sedredulo","state":"Veszprem"}'>Sedredulo</div>
<div class="option" data='{"value":"Sedvolgy","state":"Veszprem"}'>Sedvolgy</div>
<div class="option" data='{"value":"Simahazapuszta","state":"Veszprem"}'>Simahazapuszta</div>
<div class="option" data='{"value":"Simontanya","state":"Veszprem"}'>Simontanya</div>
<div class="option" data='{"value":"Soderbanya","state":"Veszprem"}'>Soderbanya</div>
<div class="option" data='{"value":"Soly","state":"Veszprem"}'>Soly</div>
<div class="option" data='{"value":"Somhegy","state":"Veszprem"}'>Somhegy</div>
<div class="option" data='{"value":"Somhegypuszta","state":"Veszprem"}'>Somhegypuszta</div>
<div class="option" data='{"value":"Somlohegy","state":"Veszprem"}'>Somlohegy</div>
<div class="option" data='{"value":"Somlojeno","state":"Veszprem"}'>Somlojeno</div>
<div class="option" data='{"value":"Somloszollos","state":"Veszprem"}'>Somloszollos</div>
<div class="option" data='{"value":"Somloszolos","state":"Veszprem"}'>Somloszolos</div>
<div class="option" data='{"value":"Somlovar","state":"Veszprem"}'>Somlovar</div>
<div class="option" data='{"value":"Somlovasarhely","state":"Veszprem"}'>Somlovasarhely</div>
<div class="option" data='{"value":"Somlovecse","state":"Veszprem"}'>Somlovecse</div>
<div class="option" data='{"value":"Sovenykut","state":"Veszprem"}'>Sovenykut</div>
<div class="option" data='{"value":"Stefanovicsmajor","state":"Veszprem"}'>Stefanovicsmajor</div>
<div class="option" data='{"value":"Sumeg","state":"Veszprem"}'>Sumeg</div>
<div class="option" data='{"value":"Sumegi Bazaltbanya","state":"Veszprem"}'>Sumegi Bazaltbanya</div>
<div class="option" data='{"value":"Sumegpraga","state":"Veszprem"}'>Sumegpraga</div>
<div class="option" data='{"value":"Szabadsagpuszta","state":"Veszprem"}'>Szabadsagpuszta</div>
<div class="option" data='{"value":"Szabomalom","state":"Veszprem"}'>Szabomalom</div>
<div class="option" data='{"value":"Szalkadulo","state":"Veszprem"}'>Szalkadulo</div>
<div class="option" data='{"value":"Szalmassytelep","state":"Veszprem"}'>Szalmassytelep</div>
<div class="option" data='{"value":"Szapar","state":"Veszprem"}'>Szapar</div>
<div class="option" data='{"value":"Szedertanya","state":"Veszprem"}'>Szedertanya</div>
<div class="option" data='{"value":"Szekfumajor","state":"Veszprem"}'>Szekfumajor</div>
<div class="option" data='{"value":"Szekpuszta","state":"Veszprem"}'>Szekpuszta</div>
<div class="option" data='{"value":"Szekrenyvolgy","state":"Veszprem"}'>Szekrenyvolgy</div>
<div class="option" data='{"value":"Szelmezopuszta","state":"Veszprem"}'>Szelmezopuszta</div>
<div class="option" data='{"value":"Szenegeto","state":"Veszprem"}'>Szenegeto</div>
<div class="option" data='{"value":"Szenegetopuszta","state":"Veszprem"}'>Szenegetopuszta</div>
<div class="option" data='{"value":"Szent Mihaly","state":"Veszprem"}'>Szent Mihaly</div>
<div class="option" data='{"value":"Szentantalfa","state":"Veszprem"}'>Szentantalfa</div>
<div class="option" data='{"value":"Szentbekkala","state":"Veszprem"}'>Szentbekkala</div>
<div class="option" data='{"value":"Szentbekkalla","state":"Veszprem"}'>Szentbekkalla</div>
<div class="option" data='{"value":"Szentgal","state":"Veszprem"}'>Szentgal</div>
<div class="option" data='{"value":"Szentgali Tanyak","state":"Veszprem"}'>Szentgali Tanyak</div>
<div class="option" data='{"value":"Szentgyorgyhegy","state":"Veszprem"}'>Szentgyorgyhegy</div>
<div class="option" data='{"value":"Szentimrefalva","state":"Veszprem"}'>Szentimrefalva</div>
<div class="option" data='{"value":"Szentimrepuszta","state":"Veszprem"}'>Szentimrepuszta</div>
<div class="option" data='{"value":"Szentjakabfa","state":"Veszprem"}'>Szentjakabfa</div>
<div class="option" data='{"value":"Szentkiralyszabadja","state":"Veszprem"}'>Szentkiralyszabadja</div>
<div class="option" data='{"value":"Szentkut","state":"Veszprem"}'>Szentkut</div>
<div class="option" data='{"value":"Szentkutpuszta","state":"Veszprem"}'>Szentkutpuszta</div>
<div class="option" data='{"value":"Szentmihalypuszta","state":"Veszprem"}'>Szentmihalypuszta</div>
<div class="option" data='{"value":"Szepalmapuszta","state":"Veszprem"}'>Szepalmapuszta</div>
<div class="option" data='{"value":"Szepezdfurdo","state":"Veszprem"}'>Szepezdfurdo</div>
<div class="option" data='{"value":"Szeplabi Major","state":"Veszprem"}'>Szeplabi Major</div>
<div class="option" data='{"value":"Szeplabitanya","state":"Veszprem"}'>Szeplabitanya</div>
<div class="option" data='{"value":"Szepmagas","state":"Veszprem"}'>Szepmagas</div>
<div class="option" data='{"value":"Szeredihegy","state":"Veszprem"}'>Szeredihegy</div>
<div class="option" data='{"value":"Szeszgyar","state":"Veszprem"}'>Szeszgyar</div>
<div class="option" data='{"value":"Sziget","state":"Veszprem"}'>Sziget</div>
<div class="option" data='{"value":"Szigetpuszta","state":"Veszprem"}'>Szigetpuszta</div>
<div class="option" data='{"value":"Szigetszer","state":"Veszprem"}'>Szigetszer</div>
<div class="option" data='{"value":"Szigliget","state":"Veszprem"}'>Szigliget</div>
<div class="option" data='{"value":"Szilos","state":"Veszprem"}'>Szilos</div>
<div class="option" data='{"value":"Szilvasitanya","state":"Veszprem"}'>Szilvasitanya</div>
<div class="option" data='{"value":"Szitasmalom","state":"Veszprem"}'>Szitasmalom</div>
<div class="option" data='{"value":"Szoc","state":"Veszprem"}'>Szoc</div>
<div class="option" data='{"value":"Szoci Tanya","state":"Veszprem"}'>Szoci Tanya</div>
<div class="option" data='{"value":"Szollokalja","state":"Veszprem"}'>Szollokalja</div>
<div class="option" data='{"value":"Szolokalja","state":"Veszprem"}'>Szolokalja</div>
<div class="option" data='{"value":"Szolotelep","state":"Veszprem"}'>Szolotelep</div>
<div class="option" data='{"value":"Szucs","state":"Veszprem"}'>Szucs</div>
<div class="option" data='{"value":"Szucstanya","state":"Veszprem"}'>Szucstanya</div>
<div class="option" data='{"value":"Szula","state":"Veszprem"}'>Szula</div>
<div class="option" data='{"value":"Szulaiszolo","state":"Veszprem"}'>Szulaiszolo</div>
<div class="option" data='{"value":"Szulaszollohegy","state":"Veszprem"}'>Szulaszollohegy</div>
<div class="option" data='{"value":"Szunyogmajor","state":"Veszprem"}'>Szunyogmajor</div>
<div class="option" data='{"value":"Taborhely","state":"Veszprem"}'>Taborhely</div>
<div class="option" data='{"value":"Tagyon","state":"Veszprem"}'>Tagyon</div>
<div class="option" data='{"value":"Tagyonhegy","state":"Veszprem"}'>Tagyonhegy</div>
<div class="option" data='{"value":"Takacsi","state":"Veszprem"}'>Takacsi</div>
<div class="option" data='{"value":"Taliandorogd","state":"Veszprem"}'>Taliandorogd</div>
<div class="option" data='{"value":"Tamashegy","state":"Veszprem"}'>Tamashegy</div>
<div class="option" data='{"value":"Tamashegydulo","state":"Veszprem"}'>Tamashegydulo</div>
<div class="option" data='{"value":"Tapolca","state":"Veszprem"}'>Tapolca</div>
<div class="option" data='{"value":"Tapolcafo","state":"Veszprem"}'>Tapolcafo</div>
<div class="option" data='{"value":"Tapolcai Tanyak","state":"Veszprem"}'>Tapolcai Tanyak</div>
<div class="option" data='{"value":"Tapolcza","state":"Veszprem"}'>Tapolcza</div>
<div class="option" data='{"value":"Tapolezai","state":"Veszprem"}'>Tapolezai</div>
<div class="option" data='{"value":"Tatikahidegkut","state":"Veszprem"}'>Tatikahidegkut</div>
<div class="option" data='{"value":"Tecsipuszta","state":"Veszprem"}'>Tecsipuszta</div>
<div class="option" data='{"value":"Teglagyar","state":"Veszprem"}'>Teglagyar</div>
<div class="option" data='{"value":"Teglavetodulo","state":"Veszprem"}'>Teglavetodulo</div>
<div class="option" data='{"value":"Telekito","state":"Veszprem"}'>Telekito</div>
<div class="option" data='{"value":"Tepecs","state":"Veszprem"}'>Tepecs</div>
<div class="option" data='{"value":"Tepecshegy","state":"Veszprem"}'>Tepecshegy</div>
<div class="option" data='{"value":"Tes","state":"Veszprem"}'>Tes</div>
<div class="option" data='{"value":"Tihany","state":"Veszprem"}'>Tihany</div>
<div class="option" data='{"value":"Tikhegy","state":"Veszprem"}'>Tikhegy</div>
<div class="option" data='{"value":"Tisztviselotelep","state":"Veszprem"}'>Tisztviselotelep</div>
<div class="option" data='{"value":"Torekpuszta","state":"Veszprem"}'>Torekpuszta</div>
<div class="option" data='{"value":"Torzsokhegy","state":"Veszprem"}'>Torzsokhegy</div>
<div class="option" data='{"value":"Tosok","state":"Veszprem"}'>Tosok</div>
<div class="option" data='{"value":"Tosokberend","state":"Veszprem"}'>Tosokberend</div>
<div class="option" data='{"value":"Totihegy","state":"Veszprem"}'>Totihegy</div>
<div class="option" data='{"value":"Totvazsony","state":"Veszprem"}'>Totvazsony</div>
<div class="option" data='{"value":"Tripoliszlakotelep","state":"Veszprem"}'>Tripoliszlakotelep</div>
<div class="option" data='{"value":"Tundermajor","state":"Veszprem"}'>Tundermajor</div>
<div class="option" data='{"value":"Turcsanyimalom","state":"Veszprem"}'>Turcsanyimalom</div>
<div class="option" data='{"value":"Tusakos","state":"Veszprem"}'>Tusakos</div>
<div class="option" data='{"value":"Tuskesmajor","state":"Veszprem"}'>Tuskesmajor</div>
<div class="option" data='{"value":"Tuskespuszta","state":"Veszprem"}'>Tuskespuszta</div>
<div class="option" data='{"value":"Tuskevar","state":"Veszprem"}'>Tuskevar</div>
<div class="option" data='{"value":"Tuzerlaktanya","state":"Veszprem"}'>Tuzerlaktanya</div>
<div class="option" data='{"value":"Tyukhegy","state":"Veszprem"}'>Tyukhegy</div>
<div class="option" data='{"value":"Tyuktelep","state":"Veszprem"}'>Tyuktelep</div>
<div class="option" data='{"value":"Udulotelep","state":"Veszprem"}'>Udulotelep</div>
<div class="option" data='{"value":"Ugod","state":"Veszprem"}'>Ugod</div>
<div class="option" data='{"value":"Ujdorogd","state":"Veszprem"}'>Ujdorogd</div>
<div class="option" data='{"value":"Ujdorogdpuszta","state":"Veszprem"}'>Ujdorogdpuszta</div>
<div class="option" data='{"value":"Ujfoldek","state":"Veszprem"}'>Ujfoldek</div>
<div class="option" data='{"value":"Ujhegy","state":"Veszprem"}'>Ujhegy</div>
<div class="option" data='{"value":"Ujmajor","state":"Veszprem"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujmalomsok","state":"Veszprem"}'>Ujmalomsok</div>
<div class="option" data='{"value":"Ujpuszta","state":"Veszprem"}'>Ujpuszta</div>
<div class="option" data='{"value":"Ujsomlo","state":"Veszprem"}'>Ujsomlo</div>
<div class="option" data='{"value":"Ujtelep","state":"Veszprem"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujtotanya","state":"Veszprem"}'>Ujtotanya</div>
<div class="option" data='{"value":"Ukk","state":"Veszprem"}'>Ukk</div>
<div class="option" data='{"value":"Urberpuszta","state":"Veszprem"}'>Urberpuszta</div>
<div class="option" data='{"value":"Urhazimalom","state":"Veszprem"}'>Urhazimalom</div>
<div class="option" data='{"value":"Urkut","state":"Veszprem"}'>Urkut</div>
<div class="option" data='{"value":"Ustihegyalja","state":"Veszprem"}'>Ustihegyalja</div>
<div class="option" data='{"value":"Usztatomajor","state":"Veszprem"}'>Usztatomajor</div>
<div class="option" data='{"value":"Uzsa","state":"Veszprem"}'>Uzsa</div>
<div class="option" data='{"value":"Uzsalpuszta","state":"Veszprem"}'>Uzsalpuszta</div>
<div class="option" data='{"value":"Vadszollotelep","state":"Veszprem"}'>Vadszollotelep</div>
<div class="option" data='{"value":"Vadtelep","state":"Veszprem"}'>Vadtelep</div>
<div class="option" data='{"value":"Vamosmajor","state":"Veszprem"}'>Vamosmajor</div>
<div class="option" data='{"value":"Vanyola","state":"Veszprem"}'>Vanyola</div>
<div class="option" data='{"value":"Varcsalit","state":"Veszprem"}'>Varcsalit</div>
<div class="option" data='{"value":"Varcsalitpuszta","state":"Veszprem"}'>Varcsalitpuszta</div>
<div class="option" data='{"value":"Vardapuszta","state":"Veszprem"}'>Vardapuszta</div>
<div class="option" data='{"value":"Vargatanya","state":"Veszprem"}'>Vargatanya</div>
<div class="option" data='{"value":"Varhegy","state":"Veszprem"}'>Varhegy</div>
<div class="option" data='{"value":"Varkeszo","state":"Veszprem"}'>Varkeszo</div>
<div class="option" data='{"value":"Varoslod","state":"Veszprem"}'>Varoslod</div>
<div class="option" data='{"value":"Varoslodi Tanyak","state":"Veszprem"}'>Varoslodi Tanyak</div>
<div class="option" data='{"value":"Varpalota","state":"Veszprem"}'>Varpalota</div>
<div class="option" data='{"value":"Vashamori Malom","state":"Veszprem"}'>Vashamori Malom</div>
<div class="option" data='{"value":"Vaszar","state":"Veszprem"}'>Vaszar</div>
<div class="option" data='{"value":"Vaszari Tanya","state":"Veszprem"}'>Vaszari Tanya</div>
<div class="option" data='{"value":"Vaszoly","state":"Veszprem"}'>Vaszoly</div>
<div class="option" data='{"value":"Vecseny","state":"Veszprem"}'>Vecseny</div>
<div class="option" data='{"value":"Vecsenypuszta","state":"Veszprem"}'>Vecsenypuszta</div>
<div class="option" data='{"value":"Veimpuszta","state":"Veszprem"}'>Veimpuszta</div>
<div class="option" data='{"value":"Velete","state":"Veszprem"}'>Velete</div>
<div class="option" data='{"value":"Vendekhegy","state":"Veszprem"}'>Vendekhegy</div>
<div class="option" data='{"value":"Vessprem","state":"Veszprem"}'>Vessprem</div>
<div class="option" data='{"value":"Veszprem","state":"Veszprem"}'>Veszprem</div>
<div class="option" data='{"value":"Veszprem County","state":"Veszprem"}'>Veszprem County</div>
<div class="option" data='{"value":"Veszprem Megye","state":"Veszprem"}'>Veszprem Megye</div>
<div class="option" data='{"value":"Veszprem Megyei Varos","state":"Veszprem"}'>Veszprem Megyei Varos</div>
<div class="option" data='{"value":"Veszpremfajsz","state":"Veszprem"}'>Veszpremfajsz</div>
<div class="option" data='{"value":"Veszpremgalsa","state":"Veszprem"}'>Veszpremgalsa</div>
<div class="option" data='{"value":"Veszprempinkoc","state":"Veszprem"}'>Veszprempinkoc</div>
<div class="option" data='{"value":"Veszveres","state":"Veszprem"}'>Veszveres</div>
<div class="option" data='{"value":"Vid","state":"Veszprem"}'>Vid</div>
<div class="option" data='{"value":"Vigant","state":"Veszprem"}'>Vigant</div>
<div class="option" data='{"value":"Vigantpetend","state":"Veszprem"}'>Vigantpetend</div>
<div class="option" data='{"value":"Viktortelep","state":"Veszprem"}'>Viktortelep</div>
<div class="option" data='{"value":"Vilmapuszta","state":"Veszprem"}'>Vilmapuszta</div>
<div class="option" data='{"value":"Vilonya","state":"Veszprem"}'>Vilonya</div>
<div class="option" data='{"value":"Vinar","state":"Veszprem"}'>Vinar</div>
<div class="option" data='{"value":"Vinye","state":"Veszprem"}'>Vinye</div>
<div class="option" data='{"value":"Vinyesandormajor","state":"Veszprem"}'>Vinyesandormajor</div>
<div class="option" data='{"value":"Viriusztelep","state":"Veszprem"}'>Viriusztelep</div>
<div class="option" data='{"value":"Viszlopuszta","state":"Veszprem"}'>Viszlopuszta</div>
<div class="option" data='{"value":"Vorosbereny","state":"Veszprem"}'>Vorosbereny</div>
<div class="option" data='{"value":"Vorosdomb","state":"Veszprem"}'>Vorosdomb</div>
<div class="option" data='{"value":"Voroshegy","state":"Veszprem"}'>Voroshegy</div>
<div class="option" data='{"value":"Voroskastely","state":"Veszprem"}'>Voroskastely</div>
<div class="option" data='{"value":"Vorosmajor","state":"Veszprem"}'>Vorosmajor</div>
<div class="option" data='{"value":"Vorosszeldulo","state":"Veszprem"}'>Vorosszeldulo</div>
<div class="option" data='{"value":"Vorosto","state":"Veszprem"}'>Vorosto</div>
<div class="option" data='{"value":"Wagnertanya","state":"Veszprem"}'>Wagnertanya</div>
<div class="option" data='{"value":"Zadordulo","state":"Veszprem"}'>Zadordulo</div>
<div class="option" data='{"value":"Zadoridulo","state":"Veszprem"}'>Zadoridulo</div>
<div class="option" data='{"value":"Zalaerdod","state":"Veszprem"}'>Zalaerdod</div>
<div class="option" data='{"value":"Zalagalsa","state":"Veszprem"}'>Zalagalsa</div>
<div class="option" data='{"value":"Zalagyomoro","state":"Veszprem"}'>Zalagyomoro</div>
<div class="option" data='{"value":"Zalagyomro","state":"Veszprem"}'>Zalagyomro</div>
<div class="option" data='{"value":"Zalahalap","state":"Veszprem"}'>Zalahalap</div>
<div class="option" data='{"value":"Zalameggyes","state":"Veszprem"}'>Zalameggyes</div>
<div class="option" data='{"value":"Zalapetend","state":"Veszprem"}'>Zalapetend</div>
<div class="option" data='{"value":"Zalaszegvar","state":"Veszprem"}'>Zalaszegvar</div>
<div class="option" data='{"value":"Zanka","state":"Veszprem"}'>Zanka</div>
<div class="option" data='{"value":"Zirc","state":"Veszprem"}'>Zirc</div>
<div class="option" data='{"value":"Zsellehat","state":"Veszprem"}'>Zsellehat</div>
<div class="option" data='{"value":"Zsellererdo","state":"Veszprem"}'>Zsellererdo</div>
<div class="option" data='{"value":"Zsigahaza","state":"Veszprem"}'>Zsigahaza</div>
<div class="option" data='{"value":"Zsigahazapuszta","state":"Veszprem"}'>Zsigahazapuszta</div>
<div class="option" data='{"value":"Zsigmondhazapuszta","state":"Veszprem"}'>Zsigmondhazapuszta</div>
<div class="option" data='{"value":"Zsofiamajor","state":"Veszprem"}'>Zsofiamajor</div>
<div class="option" data='{"value":"Zsofiapuszta","state":"Veszprem"}'>Zsofiapuszta</div>
<div class="option" data='{"value":"Zsork","state":"Veszprem"}'>Zsork</div>
<div class="option" id="option_end" data='{"value":"Zsorki","state":"Veszprem"}'>Zsorki</div>

