<div class="option" data='{"value":"Adamhegy","state":"Zala"}'>Adamhegy</div>
<div class="option" data='{"value":"Adolfmajor","state":"Zala"}'>Adolfmajor</div>
<div class="option" data='{"value":"Alibanfa","state":"Zala"}'>Alibanfa</div>
<div class="option" data='{"value":"Aligvarhegy","state":"Zala"}'>Aligvarhegy</div>
<div class="option" data='{"value":"Aligvarihegy","state":"Zala"}'>Aligvarihegy</div>
<div class="option" data='{"value":"Aligvarmajor","state":"Zala"}'>Aligvarmajor</div>
<div class="option" data='{"value":"Alimantanya","state":"Zala"}'>Alimantanya</div>
<div class="option" data='{"value":"Alizmajor","state":"Zala"}'>Alizmajor</div>
<div class="option" data='{"value":"Almashaza","state":"Zala"}'>Almashaza</div>
<div class="option" data='{"value":"Also Szenasvolgy","state":"Zala"}'>Also Szenasvolgy</div>
<div class="option" data='{"value":"Alsoaranyod","state":"Zala"}'>Alsoaranyod</div>
<div class="option" data='{"value":"Alsobebespuszta","state":"Zala"}'>Alsobebespuszta</div>
<div class="option" data='{"value":"Alsocserpuszta","state":"Zala"}'>Alsocserpuszta</div>
<div class="option" data='{"value":"Alsocsonget","state":"Zala"}'>Alsocsonget</div>
<div class="option" data='{"value":"Alsodabrony","state":"Zala"}'>Alsodabrony</div>
<div class="option" data='{"value":"Alsoerdo","state":"Zala"}'>Alsoerdo</div>
<div class="option" data='{"value":"Alsofakos","state":"Zala"}'>Alsofakos</div>
<div class="option" data='{"value":"Alsohegy","state":"Zala"}'>Alsohegy</div>
<div class="option" data='{"value":"Alsoistvand","state":"Zala"}'>Alsoistvand</div>
<div class="option" data='{"value":"Alsokustany","state":"Zala"}'>Alsokustany</div>
<div class="option" data='{"value":"Alsomajor","state":"Zala"}'>Alsomajor</div>
<div class="option" data='{"value":"Alsomalom","state":"Zala"}'>Alsomalom</div>
<div class="option" data='{"value":"Alsonemesapati","state":"Zala"}'>Alsonemesapati</div>
<div class="option" data='{"value":"Alsopahok","state":"Zala"}'>Alsopahok</div>
<div class="option" data='{"value":"Alsorajk","state":"Zala"}'>Alsorajk</div>
<div class="option" data='{"value":"Alsosanc","state":"Zala"}'>Alsosanc</div>
<div class="option" data='{"value":"Alsosotetmajor","state":"Zala"}'>Alsosotetmajor</div>
<div class="option" data='{"value":"Alsoszenterzsebet","state":"Zala"}'>Alsoszenterzsebet</div>
<div class="option" data='{"value":"Alsotollosmajor","state":"Zala"}'>Alsotollosmajor</div>
<div class="option" data='{"value":"Alsotollospuszta","state":"Zala"}'>Alsotollospuszta</div>
<div class="option" data='{"value":"Andorhazamajor","state":"Zala"}'>Andorhazamajor</div>
<div class="option" data='{"value":"Andrashida","state":"Zala"}'>Andrashida</div>
<div class="option" data='{"value":"Angelamajor","state":"Zala"}'>Angelamajor</div>
<div class="option" data='{"value":"Annamajor","state":"Zala"}'>Annamajor</div>
<div class="option" data='{"value":"Antalhegy","state":"Zala"}'>Antalhegy</div>
<div class="option" data='{"value":"Apatfa","state":"Zala"}'>Apatfa</div>
<div class="option" data='{"value":"Apati Puszta","state":"Zala"}'>Apati Puszta</div>
<div class="option" data='{"value":"Apsamajor","state":"Zala"}'>Apsamajor</div>
<div class="option" data='{"value":"Aranyhegy","state":"Zala"}'>Aranyhegy</div>
<div class="option" data='{"value":"Aranyod","state":"Zala"}'>Aranyod</div>
<div class="option" data='{"value":"Arkoshazapuszta","state":"Zala"}'>Arkoshazapuszta</div>
<div class="option" data='{"value":"Asszonyvar","state":"Zala"}'>Asszonyvar</div>
<div class="option" data='{"value":"Asszonyvariszollo","state":"Zala"}'>Asszonyvariszollo</div>
<div class="option" data='{"value":"Asszonyvariszolo","state":"Zala"}'>Asszonyvariszolo</div>
<div class="option" data='{"value":"Asszuvolgyimajor","state":"Zala"}'>Asszuvolgyimajor</div>
<div class="option" data='{"value":"Aszopuszta","state":"Zala"}'>Aszopuszta</div>
<div class="option" data='{"value":"Avashegy","state":"Zala"}'>Avashegy</div>
<div class="option" data='{"value":"Babosdobrete","state":"Zala"}'>Babosdobrete</div>
<div class="option" data='{"value":"Baconakhegy","state":"Zala"}'>Baconakhegy</div>
<div class="option" data='{"value":"Badacsahegy","state":"Zala"}'>Badacsahegy</div>
<div class="option" data='{"value":"Baglad","state":"Zala"}'>Baglad</div>
<div class="option" data='{"value":"Baglaszamajor","state":"Zala"}'>Baglaszamajor</div>
<div class="option" data='{"value":"Baglaszo","state":"Zala"}'>Baglaszo</div>
<div class="option" data='{"value":"Bagod","state":"Zala"}'>Bagod</div>
<div class="option" data='{"value":"Bagodvitenyed","state":"Zala"}'>Bagodvitenyed</div>
<div class="option" data='{"value":"Bagola","state":"Zala"}'>Bagola</div>
<div class="option" data='{"value":"Bagolasanc","state":"Zala"}'>Bagolasanc</div>
<div class="option" data='{"value":"Bagotapuszta","state":"Zala"}'>Bagotapuszta</div>
<div class="option" data='{"value":"Bagovar","state":"Zala"}'>Bagovar</div>
<div class="option" data='{"value":"Bajcsa","state":"Zala"}'>Bajcsa</div>
<div class="option" data='{"value":"Bak","state":"Zala"}'>Bak</div>
<div class="option" data='{"value":"Bakarend","state":"Zala"}'>Bakarend</div>
<div class="option" data='{"value":"Baktuttos","state":"Zala"}'>Baktuttos</div>
<div class="option" data='{"value":"Balatongyorok","state":"Zala"}'>Balatongyorok</div>
<div class="option" data='{"value":"Balatonhidveg","state":"Zala"}'>Balatonhidveg</div>
<div class="option" data='{"value":"Balatonhidvegpuszta","state":"Zala"}'>Balatonhidvegpuszta</div>
<div class="option" data='{"value":"Balatonmagyarod","state":"Zala"}'>Balatonmagyarod</div>
<div class="option" data='{"value":"Balikas","state":"Zala"}'>Balikas</div>
<div class="option" data='{"value":"Balikaspuszta","state":"Zala"}'>Balikaspuszta</div>
<div class="option" data='{"value":"Banfamajor","state":"Zala"}'>Banfamajor</div>
<div class="option" data='{"value":"Banfapuszta","state":"Zala"}'>Banfapuszta</div>
<div class="option" data='{"value":"Banmajor","state":"Zala"}'>Banmajor</div>
<div class="option" data='{"value":"Banokszentgyorgy","state":"Zala"}'>Banokszentgyorgy</div>
<div class="option" data='{"value":"Banom","state":"Zala"}'>Banom</div>
<div class="option" data='{"value":"Banyatelep","state":"Zala"}'>Banyatelep</div>
<div class="option" data='{"value":"Banyavolgy","state":"Zala"}'>Banyavolgy</div>
<div class="option" data='{"value":"Barabashegy","state":"Zala"}'>Barabashegy</div>
<div class="option" data='{"value":"Barabaspuszta","state":"Zala"}'>Barabaspuszta</div>
<div class="option" data='{"value":"Barandpuszta","state":"Zala"}'>Barandpuszta</div>
<div class="option" data='{"value":"Baranytilos","state":"Zala"}'>Baranytilos</div>
<div class="option" data='{"value":"Baratokfapuszta","state":"Zala"}'>Baratokfapuszta</div>
<div class="option" data='{"value":"Baratsziget","state":"Zala"}'>Baratsziget</div>
<div class="option" data='{"value":"Barcaimajor","state":"Zala"}'>Barcaimajor</div>
<div class="option" data='{"value":"Bardos","state":"Zala"}'>Bardos</div>
<div class="option" data='{"value":"Barhely","state":"Zala"}'>Barhely</div>
<div class="option" data='{"value":"Barkocas","state":"Zala"}'>Barkocas</div>
<div class="option" data='{"value":"Barlahida","state":"Zala"}'>Barlahida</div>
<div class="option" data='{"value":"Barnakpuszta","state":"Zala"}'>Barnakpuszta</div>
<div class="option" data='{"value":"Barnek","state":"Zala"}'>Barnek</div>
<div class="option" data='{"value":"Baromajor","state":"Zala"}'>Baromajor</div>
<div class="option" data='{"value":"Barszentmihalyfa","state":"Zala"}'>Barszentmihalyfa</div>
<div class="option" data='{"value":"Bartulahegy","state":"Zala"}'>Bartulahegy</div>
<div class="option" data='{"value":"Batyk","state":"Zala"}'>Batyk</div>
<div class="option" data='{"value":"Baza","state":"Zala"}'>Baza</div>
<div class="option" data='{"value":"Bazakerettye","state":"Zala"}'>Bazakerettye</div>
<div class="option" data='{"value":"Bazita","state":"Zala"}'>Bazita</div>
<div class="option" data='{"value":"Bebespuszta","state":"Zala"}'>Bebespuszta</div>
<div class="option" data='{"value":"Bec","state":"Zala"}'>Bec</div>
<div class="option" data='{"value":"Becimajor","state":"Zala"}'>Becimajor</div>
<div class="option" data='{"value":"Becsalihegy","state":"Zala"}'>Becsalihegy</div>
<div class="option" data='{"value":"Becsehely","state":"Zala"}'>Becsehely</div>
<div class="option" data='{"value":"Becsvolgye","state":"Zala"}'>Becsvolgye</div>
<div class="option" data='{"value":"Behiakpuszta","state":"Zala"}'>Behiakpuszta</div>
<div class="option" data='{"value":"Bekcsenypolya","state":"Zala"}'>Bekcsenypolya</div>
<div class="option" data='{"value":"Bekehaza","state":"Zala"}'>Bekehaza</div>
<div class="option" data='{"value":"Belamajor","state":"Zala"}'>Belamajor</div>
<div class="option" data='{"value":"Belatanya","state":"Zala"}'>Belatanya</div>
<div class="option" data='{"value":"Belezna","state":"Zala"}'>Belezna</div>
<div class="option" data='{"value":"Belmajor","state":"Zala"}'>Belmajor</div>
<div class="option" data='{"value":"Belsoberek","state":"Zala"}'>Belsoberek</div>
<div class="option" data='{"value":"Belsohegy","state":"Zala"}'>Belsohegy</div>
<div class="option" data='{"value":"Belsomajor","state":"Zala"}'>Belsomajor</div>
<div class="option" data='{"value":"Belsosard","state":"Zala"}'>Belsosard</div>
<div class="option" data='{"value":"Bezered","state":"Zala"}'>Bezered</div>
<div class="option" data='{"value":"Bezsento","state":"Zala"}'>Bezsento</div>
<div class="option" data='{"value":"Bezsentoi Malom","state":"Zala"}'>Bezsentoi Malom</div>
<div class="option" data='{"value":"Biklerfold","state":"Zala"}'>Biklerfold</div>
<div class="option" data='{"value":"Biroszel","state":"Zala"}'>Biroszel</div>
<div class="option" data='{"value":"Bocfolde","state":"Zala"}'>Bocfolde</div>
<div class="option" data='{"value":"Bocska","state":"Zala"}'>Bocska</div>
<div class="option" data='{"value":"Bocsota","state":"Zala"}'>Bocsota</div>
<div class="option" data='{"value":"Bocsotamajor","state":"Zala"}'>Bocsotamajor</div>
<div class="option" data='{"value":"Bode","state":"Zala"}'>Bode</div>
<div class="option" data='{"value":"Bodehaza","state":"Zala"}'>Bodehaza</div>
<div class="option" data='{"value":"Bodemajor","state":"Zala"}'>Bodemajor</div>
<div class="option" data='{"value":"Bodonkut","state":"Zala"}'>Bodonkut</div>
<div class="option" data='{"value":"Bokahaza","state":"Zala"}'>Bokahaza</div>
<div class="option" data='{"value":"Bolcsfoldpuszta","state":"Zala"}'>Bolcsfoldpuszta</div>
<div class="option" data='{"value":"Bolypart","state":"Zala"}'>Bolypart</div>
<div class="option" data='{"value":"Bolypuszta","state":"Zala"}'>Bolypuszta</div>
<div class="option" data='{"value":"Boncodfolde","state":"Zala"}'>Boncodfolde</div>
<div class="option" data='{"value":"Bonczodfolde","state":"Zala"}'>Bonczodfolde</div>
<div class="option" data='{"value":"Borbelyret","state":"Zala"}'>Borbelyret</div>
<div class="option" data='{"value":"Bordocze","state":"Zala"}'>Bordocze</div>
<div class="option" data='{"value":"Borond","state":"Zala"}'>Borond</div>
<div class="option" data='{"value":"Borsfa","state":"Zala"}'>Borsfa</div>
<div class="option" data='{"value":"Borsosoldal","state":"Zala"}'>Borsosoldal</div>
<div class="option" data='{"value":"Borzonce","state":"Zala"}'>Borzonce</div>
<div class="option" data='{"value":"Boszorkanyhanyas","state":"Zala"}'>Boszorkanyhanyas</div>
<div class="option" data='{"value":"Botfa","state":"Zala"}'>Botfa</div>
<div class="option" data='{"value":"Bozsok","state":"Zala"}'>Bozsok</div>
<div class="option" data='{"value":"Bozsokihegy","state":"Zala"}'>Bozsokihegy</div>
<div class="option" data='{"value":"Bucsuszentlaszlo","state":"Zala"}'>Bucsuszentlaszlo</div>
<div class="option" data='{"value":"Bucsuta","state":"Zala"}'>Bucsuta</div>
<div class="option" data='{"value":"Budafa","state":"Zala"}'>Budafa</div>
<div class="option" data='{"value":"Budafapuszta","state":"Zala"}'>Budafapuszta</div>
<div class="option" data='{"value":"Budaihegy","state":"Zala"}'>Budaihegy</div>
<div class="option" data='{"value":"Budaivolgy","state":"Zala"}'>Budaivolgy</div>
<div class="option" data='{"value":"Budnya","state":"Zala"}'>Budnya</div>
<div class="option" data='{"value":"Budnyapuszta","state":"Zala"}'>Budnyapuszta</div>
<div class="option" data='{"value":"Bukkihaz","state":"Zala"}'>Bukkihaz</div>
<div class="option" data='{"value":"Bukkpuszta","state":"Zala"}'>Bukkpuszta</div>
<div class="option" data='{"value":"Buslakmajor","state":"Zala"}'>Buslakmajor</div>
<div class="option" data='{"value":"Buslakpuszta","state":"Zala"}'>Buslakpuszta</div>
<div class="option" data='{"value":"Ciganygodor","state":"Zala"}'>Ciganygodor</div>
<div class="option" data='{"value":"Ciganyhegy","state":"Zala"}'>Ciganyhegy</div>
<div class="option" data='{"value":"Ciganyszer","state":"Zala"}'>Ciganyszer</div>
<div class="option" data='{"value":"Csacs","state":"Zala"}'>Csacs</div>
<div class="option" data='{"value":"Csacsbozsok","state":"Zala"}'>Csacsbozsok</div>
<div class="option" data='{"value":"Csacsihegy","state":"Zala"}'>Csacsihegy</div>
<div class="option" data='{"value":"Csadepuszta","state":"Zala"}'>Csadepuszta</div>
<div class="option" data='{"value":"Csaford","state":"Zala"}'>Csaford</div>
<div class="option" data='{"value":"Csalanyos","state":"Zala"}'>Csalanyos</div>
<div class="option" data='{"value":"Csalit","state":"Zala"}'>Csalit</div>
<div class="option" data='{"value":"Csalitmajor","state":"Zala"}'>Csalitmajor</div>
<div class="option" data='{"value":"Csapi","state":"Zala"}'>Csapi</div>
<div class="option" data='{"value":"Csapomalom","state":"Zala"}'>Csapomalom</div>
<div class="option" data='{"value":"Csarda","state":"Zala"}'>Csarda</div>
<div class="option" data='{"value":"Csatar","state":"Zala"}'>Csatar</div>
<div class="option" data='{"value":"Csatarhegy","state":"Zala"}'>Csatarhegy</div>
<div class="option" data='{"value":"Csatlostanya","state":"Zala"}'>Csatlostanya</div>
<div class="option" data='{"value":"Csehi","state":"Zala"}'>Csehi</div>
<div class="option" data='{"value":"Csehipuszta","state":"Zala"}'>Csehipuszta</div>
<div class="option" data='{"value":"Csekek","state":"Zala"}'>Csekek</div>
<div class="option" data='{"value":"Csentericfa","state":"Zala"}'>Csentericfa</div>
<div class="option" data='{"value":"Cserfo","state":"Zala"}'>Cserfo</div>
<div class="option" data='{"value":"Cserhatmajor","state":"Zala"}'>Cserhatmajor</div>
<div class="option" data='{"value":"Cserhegy","state":"Zala"}'>Cserhegy</div>
<div class="option" data='{"value":"Cserlap","state":"Zala"}'>Cserlap</div>
<div class="option" data='{"value":"Csermajor","state":"Zala"}'>Csermajor</div>
<div class="option" data='{"value":"Csernec","state":"Zala"}'>Csernec</div>
<div class="option" data='{"value":"Cseroldaldulo","state":"Zala"}'>Cseroldaldulo</div>
<div class="option" data='{"value":"Cserszegtomaj","state":"Zala"}'>Cserszegtomaj</div>
<div class="option" data='{"value":"Csertalakos","state":"Zala"}'>Csertalakos</div>
<div class="option" data='{"value":"Csesztreg","state":"Zala"}'>Csesztreg</div>
<div class="option" data='{"value":"Cseteny","state":"Zala"}'>Cseteny</div>
<div class="option" data='{"value":"Csikotilospuszta","state":"Zala"}'>Csikotilospuszta</div>
<div class="option" data='{"value":"Csilladulo","state":"Zala"}'>Csilladulo</div>
<div class="option" data='{"value":"Csillaghegy","state":"Zala"}'>Csillaghegy</div>
<div class="option" data='{"value":"Csillagmajor","state":"Zala"}'>Csillagmajor</div>
<div class="option" data='{"value":"Csirkehegyalja","state":"Zala"}'>Csirkehegyalja</div>
<div class="option" data='{"value":"Csoborpuszta","state":"Zala"}'>Csoborpuszta</div>
<div class="option" data='{"value":"Csode","state":"Zala"}'>Csode</div>
<div class="option" data='{"value":"Csokmai Hegy","state":"Zala"}'>Csokmai Hegy</div>
<div class="option" data='{"value":"Csokmai Ujhegy","state":"Zala"}'>Csokmai Ujhegy</div>
<div class="option" data='{"value":"Csollanyosi Malom","state":"Zala"}'>Csollanyosi Malom</div>
<div class="option" data='{"value":"Csomoder","state":"Zala"}'>Csomoder</div>
<div class="option" data='{"value":"Csonkahegyhat","state":"Zala"}'>Csonkahegyhat</div>
<div class="option" data='{"value":"Csontemajor","state":"Zala"}'>Csontemajor</div>
<div class="option" data='{"value":"Csontepuszta","state":"Zala"}'>Csontepuszta</div>
<div class="option" data='{"value":"Csontosmajor","state":"Zala"}'>Csontosmajor</div>
<div class="option" data='{"value":"Csontteto","state":"Zala"}'>Csontteto</div>
<div class="option" data='{"value":"Csornyefold","state":"Zala"}'>Csornyefold</div>
<div class="option" data='{"value":"Csortan","state":"Zala"}'>Csortan</div>
<div class="option" data='{"value":"Csurgopuszta","state":"Zala"}'>Csurgopuszta</div>
<div class="option" data='{"value":"Deakhegy","state":"Zala"}'>Deakhegy</div>
<div class="option" data='{"value":"Dedeskecskes","state":"Zala"}'>Dedeskecskes</div>
<div class="option" data='{"value":"Deneslak","state":"Zala"}'>Deneslak</div>
<div class="option" data='{"value":"Derekhegy","state":"Zala"}'>Derekhegy</div>
<div class="option" data='{"value":"Derhastanya","state":"Zala"}'>Derhastanya</div>
<div class="option" data='{"value":"Diaszo","state":"Zala"}'>Diaszo</div>
<div class="option" data='{"value":"Dioskal","state":"Zala"}'>Dioskal</div>
<div class="option" data='{"value":"Dobri","state":"Zala"}'>Dobri</div>
<div class="option" data='{"value":"Dobroce","state":"Zala"}'>Dobroce</div>
<div class="option" data='{"value":"Dobronhegy","state":"Zala"}'>Dobronhegy</div>
<div class="option" data='{"value":"Dombi Szollok","state":"Zala"}'>Dombi Szollok</div>
<div class="option" data='{"value":"Domefolde","state":"Zala"}'>Domefolde</div>
<div class="option" data='{"value":"Dongovar","state":"Zala"}'>Dongovar</div>
<div class="option" data='{"value":"Dotk","state":"Zala"}'>Dotk</div>
<div class="option" data='{"value":"Dozsahegy","state":"Zala"}'>Dozsahegy</div>
<div class="option" data='{"value":"Dusnok","state":"Zala"}'>Dusnok</div>
<div class="option" data='{"value":"Ebergeny","state":"Zala"}'>Ebergeny</div>
<div class="option" data='{"value":"Egenfold","state":"Zala"}'>Egenfold</div>
<div class="option" data='{"value":"Egeraracsa","state":"Zala"}'>Egeraracsa</div>
<div class="option" data='{"value":"Egerszeghegy","state":"Zala"}'>Egerszeghegy</div>
<div class="option" data='{"value":"Egervar","state":"Zala"}'>Egervar</div>
<div class="option" data='{"value":"Egervari Hegy","state":"Zala"}'>Egervari Hegy</div>
<div class="option" data='{"value":"Egrihegyalja","state":"Zala"}'>Egrihegyalja</div>
<div class="option" data='{"value":"Egyedhazamajor","state":"Zala"}'>Egyedhazamajor</div>
<div class="option" data='{"value":"Egyedtelek","state":"Zala"}'>Egyedtelek</div>
<div class="option" data='{"value":"Egyeduta","state":"Zala"}'>Egyeduta</div>
<div class="option" data='{"value":"Elohegy","state":"Zala"}'>Elohegy</div>
<div class="option" data='{"value":"Endesmajor","state":"Zala"}'>Endesmajor</div>
<div class="option" data='{"value":"Erdeifalu","state":"Zala"}'>Erdeifalu</div>
<div class="option" data='{"value":"Erdeimajor","state":"Zala"}'>Erdeimajor</div>
<div class="option" data='{"value":"Erdoslak","state":"Zala"}'>Erdoslak</div>
<div class="option" data='{"value":"Erzsebethegy","state":"Zala"}'>Erzsebethegy</div>
<div class="option" data='{"value":"Erzsebetmajor","state":"Zala"}'>Erzsebetmajor</div>
<div class="option" data='{"value":"Erzsebetpuszta","state":"Zala"}'>Erzsebetpuszta</div>
<div class="option" data='{"value":"Erzsebettelep","state":"Zala"}'>Erzsebettelep</div>
<div class="option" data='{"value":"Eszteregnye","state":"Zala"}'>Eszteregnye</div>
<div class="option" data='{"value":"Esztergaly","state":"Zala"}'>Esztergaly</div>
<div class="option" data='{"value":"Esztergalyhorvati","state":"Zala"}'>Esztergalyhorvati</div>
<div class="option" data='{"value":"Fakos","state":"Zala"}'>Fakos</div>
<div class="option" data='{"value":"Fakospuszta","state":"Zala"}'>Fakospuszta</div>
<div class="option" data='{"value":"Falumalom","state":"Zala"}'>Falumalom</div>
<div class="option" data='{"value":"Faluveg","state":"Zala"}'>Faluveg</div>
<div class="option" data='{"value":"Feherbacko","state":"Zala"}'>Feherbacko</div>
<div class="option" data='{"value":"Feherbackomajor","state":"Zala"}'>Feherbackomajor</div>
<div class="option" data='{"value":"Fejermajor","state":"Zala"}'>Fejermajor</div>
<div class="option" data='{"value":"Feketesar","state":"Zala"}'>Feketesar</div>
<div class="option" data='{"value":"Feketesarpuszta","state":"Zala"}'>Feketesarpuszta</div>
<div class="option" data='{"value":"Felso Szenasvolgy","state":"Zala"}'>Felso Szenasvolgy</div>
<div class="option" data='{"value":"Felsoaranyod","state":"Zala"}'>Felsoaranyod</div>
<div class="option" data='{"value":"Felsobagod","state":"Zala"}'>Felsobagod</div>
<div class="option" data='{"value":"Felsobarkocas","state":"Zala"}'>Felsobarkocas</div>
<div class="option" data='{"value":"Felsobuberek","state":"Zala"}'>Felsobuberek</div>
<div class="option" data='{"value":"Felsocseteny","state":"Zala"}'>Felsocseteny</div>
<div class="option" data='{"value":"Felsodabrony","state":"Zala"}'>Felsodabrony</div>
<div class="option" data='{"value":"Felsoerdo","state":"Zala"}'>Felsoerdo</div>
<div class="option" data='{"value":"Felsofakos","state":"Zala"}'>Felsofakos</div>
<div class="option" data='{"value":"Felsohegy","state":"Zala"}'>Felsohegy</div>
<div class="option" data='{"value":"Felsoistvand","state":"Zala"}'>Felsoistvand</div>
<div class="option" data='{"value":"Felsomajor","state":"Zala"}'>Felsomajor</div>
<div class="option" data='{"value":"Felsomandpuszta","state":"Zala"}'>Felsomandpuszta</div>
<div class="option" data='{"value":"Felsopahok","state":"Zala"}'>Felsopahok</div>
<div class="option" data='{"value":"Felsorajk","state":"Zala"}'>Felsorajk</div>
<div class="option" data='{"value":"Felsosotetmajor","state":"Zala"}'>Felsosotetmajor</div>
<div class="option" data='{"value":"Felsoszemenye","state":"Zala"}'>Felsoszemenye</div>
<div class="option" data='{"value":"Felsoszenterzsebet","state":"Zala"}'>Felsoszenterzsebet</div>
<div class="option" data='{"value":"Felsotollospuszta","state":"Zala"}'>Felsotollospuszta</div>
<div class="option" data='{"value":"Felsovonyarc","state":"Zala"}'>Felsovonyarc</div>
<div class="option" data='{"value":"Fenekpuszta","state":"Zala"}'>Fenekpuszta</div>
<div class="option" data='{"value":"Fenyvesmajor","state":"Zala"}'>Fenyvesmajor</div>
<div class="option" data='{"value":"Ferencmajor","state":"Zala"}'>Ferencmajor</div>
<div class="option" data='{"value":"Fernekag","state":"Zala"}'>Fernekag</div>
<div class="option" data='{"value":"Fiatalosmajor","state":"Zala"}'>Fiatalosmajor</div>
<div class="option" data='{"value":"Fiatalospuszta","state":"Zala"}'>Fiatalospuszta</div>
<div class="option" data='{"value":"Firmanhaz","state":"Zala"}'>Firmanhaz</div>
<div class="option" data='{"value":"Fityehaz","state":"Zala"}'>Fityehaz</div>
<div class="option" data='{"value":"Fityehaza","state":"Zala"}'>Fityehaza</div>
<div class="option" data='{"value":"Forhenchegy","state":"Zala"}'>Forhenchegy</div>
<div class="option" data='{"value":"Forintoshaza","state":"Zala"}'>Forintoshaza</div>
<div class="option" data='{"value":"Forintoshazapuszta","state":"Zala"}'>Forintoshazapuszta</div>
<div class="option" data='{"value":"Forras","state":"Zala"}'>Forras</div>
<div class="option" data='{"value":"Frimanhaz","state":"Zala"}'>Frimanhaz</div>
<div class="option" data='{"value":"Fulopmajor","state":"Zala"}'>Fulopmajor</div>
<div class="option" data='{"value":"Furjanpuszta","state":"Zala"}'>Furjanpuszta</div>
<div class="option" data='{"value":"Fuzvolgy","state":"Zala"}'>Fuzvolgy</div>
<div class="option" data='{"value":"Gaborjanhaza","state":"Zala"}'>Gaborjanhaza</div>
<div class="option" data='{"value":"Galafejmajor","state":"Zala"}'>Galafejmajor</div>
<div class="option" data='{"value":"Galafejpuszta","state":"Zala"}'>Galafejpuszta</div>
<div class="option" data='{"value":"Galambok","state":"Zala"}'>Galambok</div>
<div class="option" data='{"value":"Ganihegy","state":"Zala"}'>Ganihegy</div>
<div class="option" data='{"value":"Garabonc","state":"Zala"}'>Garabonc</div>
<div class="option" data='{"value":"Gasparhegy","state":"Zala"}'>Gasparhegy</div>
<div class="option" data='{"value":"Gellenhaza","state":"Zala"}'>Gellenhaza</div>
<div class="option" data='{"value":"Gelse","state":"Zala"}'>Gelse</div>
<div class="option" data='{"value":"Gelsesziget","state":"Zala"}'>Gelsesziget</div>
<div class="option" data='{"value":"Gergelymalom","state":"Zala"}'>Gergelymalom</div>
<div class="option" data='{"value":"Gesztenyehegy","state":"Zala"}'>Gesztenyehegy</div>
<div class="option" data='{"value":"Gesztenyes","state":"Zala"}'>Gesztenyes</div>
<div class="option" data='{"value":"Gesztenyesmajor","state":"Zala"}'>Gesztenyesmajor</div>
<div class="option" data='{"value":"Getye","state":"Zala"}'>Getye</div>
<div class="option" data='{"value":"Gevahegy","state":"Zala"}'>Gevahegy</div>
<div class="option" data='{"value":"Gizellamajor","state":"Zala"}'>Gizellamajor</div>
<div class="option" data='{"value":"Gizellapuszta","state":"Zala"}'>Gizellapuszta</div>
<div class="option" data='{"value":"Goganhegy","state":"Zala"}'>Goganhegy</div>
<div class="option" data='{"value":"Goldmarkdulo","state":"Zala"}'>Goldmarkdulo</div>
<div class="option" data='{"value":"Golicamajor","state":"Zala"}'>Golicamajor</div>
<div class="option" data='{"value":"Goliczamajor","state":"Zala"}'>Goliczamajor</div>
<div class="option" data='{"value":"Gombosszeg","state":"Zala"}'>Gombosszeg</div>
<div class="option" data='{"value":"Gombostanya","state":"Zala"}'>Gombostanya</div>
<div class="option" data='{"value":"Gondotahegy","state":"Zala"}'>Gondotahegy</div>
<div class="option" data='{"value":"Gorbopuszta","state":"Zala"}'>Gorbopuszta</div>
<div class="option" data='{"value":"Gosfa","state":"Zala"}'>Gosfa</div>
<div class="option" data='{"value":"Gosztola","state":"Zala"}'>Gosztola</div>
<div class="option" data='{"value":"Gosztolla","state":"Zala"}'>Gosztolla</div>
<div class="option" data='{"value":"Gradicska","state":"Zala"}'>Gradicska</div>
<div class="option" data='{"value":"Gradiskahegy","state":"Zala"}'>Gradiskahegy</div>
<div class="option" data='{"value":"Gross Kanischa","state":"Zala"}'>Gross Kanischa</div>
<div class="option" data='{"value":"Grosz Kanischa","state":"Zala"}'>Grosz Kanischa</div>
<div class="option" data='{"value":"Gudorvolgy","state":"Zala"}'>Gudorvolgy</div>
<div class="option" data='{"value":"Gutorfolde","state":"Zala"}'>Gutorfolde</div>
<div class="option" data='{"value":"Gyenesdias","state":"Zala"}'>Gyenesdias</div>
<div class="option" data='{"value":"Gyopihegy","state":"Zala"}'>Gyopihegy</div>
<div class="option" data='{"value":"Gyorfiszeg","state":"Zala"}'>Gyorfiszeg</div>
<div class="option" data='{"value":"Gyorkefa","state":"Zala"}'>Gyorkefa</div>
<div class="option" data='{"value":"Gyorokhaza","state":"Zala"}'>Gyorokhaza</div>
<div class="option" data='{"value":"Gyorokhazitanya","state":"Zala"}'>Gyorokhazitanya</div>
<div class="option" data='{"value":"Gyotamajor","state":"Zala"}'>Gyotamajor</div>
<div class="option" data='{"value":"Gyotapuszta","state":"Zala"}'>Gyotapuszta</div>
<div class="option" data='{"value":"Gyulevesz","state":"Zala"}'>Gyulevesz</div>
<div class="option" data='{"value":"Gyuleveszimajor","state":"Zala"}'>Gyuleveszimajor</div>
<div class="option" data='{"value":"Gyurgyancpuszta","state":"Zala"}'>Gyurgyancpuszta</div>
<div class="option" data='{"value":"Gyurus","state":"Zala"}'>Gyurus</div>
<div class="option" data='{"value":"Hagyaros","state":"Zala"}'>Hagyaros</div>
<div class="option" data='{"value":"Hagyarosborond","state":"Zala"}'>Hagyarosborond</div>
<div class="option" data='{"value":"Hagyarosimajor","state":"Zala"}'>Hagyarosimajor</div>
<div class="option" data='{"value":"Hahot","state":"Zala"}'>Hahot</div>
<div class="option" data='{"value":"Halcsontmajor","state":"Zala"}'>Halcsontmajor</div>
<div class="option" data='{"value":"Hamuszinmajor","state":"Zala"}'>Hamuszinmajor</div>
<div class="option" data='{"value":"Hannamajor","state":"Zala"}'>Hannamajor</div>
<div class="option" data='{"value":"Haraszti","state":"Zala"}'>Haraszti</div>
<div class="option" data='{"value":"Haraszti Erdoohaz","state":"Zala"}'>Haraszti Erdoohaz</div>
<div class="option" data='{"value":"Harkalyhegy","state":"Zala"}'>Harkalyhegy</div>
<div class="option" data='{"value":"Haromhaz","state":"Zala"}'>Haromhaz</div>
<div class="option" data='{"value":"Hegy","state":"Zala"}'>Hegy</div>
<div class="option" data='{"value":"Hencse","state":"Zala"}'>Hencse</div>
<div class="option" data='{"value":"Hencsepuszta","state":"Zala"}'>Hencsepuszta</div>
<div class="option" data='{"value":"Henese","state":"Zala"}'>Henese</div>
<div class="option" data='{"value":"Herbatfa","state":"Zala"}'>Herbatfa</div>
<div class="option" data='{"value":"Hernyek","state":"Zala"}'>Hernyek</div>
<div class="option" data='{"value":"Hervadtfa","state":"Zala"}'>Hervadtfa</div>
<div class="option" data='{"value":"Hidegkut","state":"Zala"}'>Hidegkut</div>
<div class="option" data='{"value":"Hidegmajor","state":"Zala"}'>Hidegmajor</div>
<div class="option" data='{"value":"Himfold","state":"Zala"}'>Himfold</div>
<div class="option" data='{"value":"Homokkomarom","state":"Zala"}'>Homokkomarom</div>
<div class="option" data='{"value":"Hosszuhegy","state":"Zala"}'>Hosszuhegy</div>
<div class="option" data='{"value":"Hosszujanka","state":"Zala"}'>Hosszujanka</div>
<div class="option" data='{"value":"Hosszuret","state":"Zala"}'>Hosszuret</div>
<div class="option" data='{"value":"Hosszuvolgy","state":"Zala"}'>Hosszuvolgy</div>
<div class="option" data='{"value":"Hotto","state":"Zala"}'>Hotto</div>
<div class="option" data='{"value":"Huszonya","state":"Zala"}'>Huszonya</div>
<div class="option" data='{"value":"Huszonyahegy","state":"Zala"}'>Huszonyahegy</div>
<div class="option" data='{"value":"Iborfia","state":"Zala"}'>Iborfia</div>
<div class="option" data='{"value":"Iklodbordoce","state":"Zala"}'>Iklodbordoce</div>
<div class="option" data='{"value":"Iklodi Malom","state":"Zala"}'>Iklodi Malom</div>
<div class="option" data='{"value":"Ilonamajor","state":"Zala"}'>Ilonamajor</div>
<div class="option" data='{"value":"Ipartelep","state":"Zala"}'>Ipartelep</div>
<div class="option" data='{"value":"Irsapuszta","state":"Zala"}'>Irsapuszta</div>
<div class="option" data='{"value":"Irtastanya","state":"Zala"}'>Irtastanya</div>
<div class="option" data='{"value":"Istvanmajor","state":"Zala"}'>Istvanmajor</div>
<div class="option" data='{"value":"Jahompuszta","state":"Zala"}'>Jahompuszta</div>
<div class="option" data='{"value":"Jahumpuszta","state":"Zala"}'>Jahumpuszta</div>
<div class="option" data='{"value":"Jankahaza","state":"Zala"}'>Jankahaza</div>
<div class="option" data='{"value":"Jankahazamajor","state":"Zala"}'>Jankahazamajor</div>
<div class="option" data='{"value":"Jankahegy","state":"Zala"}'>Jankahegy</div>
<div class="option" data='{"value":"Jankapuszta","state":"Zala"}'>Jankapuszta</div>
<div class="option" data='{"value":"Janosmajor","state":"Zala"}'>Janosmajor</div>
<div class="option" data='{"value":"Janospuszta","state":"Zala"}'>Janospuszta</div>
<div class="option" data='{"value":"Jovolgy","state":"Zala"}'>Jovolgy</div>
<div class="option" data='{"value":"Jozsalakpuszta","state":"Zala"}'>Jozsalakpuszta</div>
<div class="option" data='{"value":"Jozsefhegy","state":"Zala"}'>Jozsefhegy</div>
<div class="option" data='{"value":"Jozsefmajor","state":"Zala"}'>Jozsefmajor</div>
<div class="option" data='{"value":"Juhaszmajor","state":"Zala"}'>Juhaszmajor</div>
<div class="option" data='{"value":"Julianhegy","state":"Zala"}'>Julianhegy</div>
<div class="option" data='{"value":"Kacorlak","state":"Zala"}'>Kacorlak</div>
<div class="option" data='{"value":"Kakonyapuszta","state":"Zala"}'>Kakonyapuszta</div>
<div class="option" data='{"value":"Kallosd","state":"Zala"}'>Kallosd</div>
<div class="option" data='{"value":"Kalmanmajor","state":"Zala"}'>Kalmanmajor</div>
<div class="option" data='{"value":"Kalocfa","state":"Zala"}'>Kalocfa</div>
<div class="option" data='{"value":"Kalocfapuszta","state":"Zala"}'>Kalocfapuszta</div>
<div class="option" data='{"value":"Kaloczfa","state":"Zala"}'>Kaloczfa</div>
<div class="option" data='{"value":"Kamahaza","state":"Zala"}'>Kamahaza</div>
<div class="option" data='{"value":"Kamahazapuszta","state":"Zala"}'>Kamahazapuszta</div>
<div class="option" data='{"value":"Kamancspuszta","state":"Zala"}'>Kamancspuszta</div>
<div class="option" data='{"value":"Kameralistanya","state":"Zala"}'>Kameralistanya</div>
<div class="option" data='{"value":"Kanadapuszta","state":"Zala"}'>Kanadapuszta</div>
<div class="option" data='{"value":"Kandiko","state":"Zala"}'>Kandiko</div>
<div class="option" data='{"value":"Kanyavar","state":"Zala"}'>Kanyavar</div>
<div class="option" data='{"value":"Kapolnahegy","state":"Zala"}'>Kapolnahegy</div>
<div class="option" data='{"value":"Kapolnapuszta","state":"Zala"}'>Kapolnapuszta</div>
<div class="option" data='{"value":"Karacsonyfa","state":"Zala"}'>Karacsonyfa</div>
<div class="option" data='{"value":"Karacsonyhegy","state":"Zala"}'>Karacsonyhegy</div>
<div class="option" data='{"value":"Karajpuszta","state":"Zala"}'>Karajpuszta</div>
<div class="option" data='{"value":"Karmacs","state":"Zala"}'>Karmacs</div>
<div class="option" data='{"value":"Karmacsi Alsomajor","state":"Zala"}'>Karmacsi Alsomajor</div>
<div class="option" data='{"value":"Kastely","state":"Zala"}'>Kastely</div>
<div class="option" data='{"value":"Kaszahaza","state":"Zala"}'>Kaszahaza</div>
<div class="option" data='{"value":"Kaszalomajor","state":"Zala"}'>Kaszalomajor</div>
<div class="option" data='{"value":"Katranyos","state":"Zala"}'>Katranyos</div>
<div class="option" data='{"value":"Kavas","state":"Zala"}'>Kavas</div>
<div class="option" data='{"value":"Kavolgy","state":"Zala"}'>Kavolgy</div>
<div class="option" data='{"value":"Kehida","state":"Zala"}'>Kehida</div>
<div class="option" data='{"value":"Kehidakustany","state":"Zala"}'>Kehidakustany</div>
<div class="option" data='{"value":"Kemend","state":"Zala"}'>Kemend</div>
<div class="option" data='{"value":"Kemendhegy","state":"Zala"}'>Kemendhegy</div>
<div class="option" data='{"value":"Kemendollar","state":"Zala"}'>Kemendollar</div>
<div class="option" data='{"value":"Kemenfa","state":"Zala"}'>Kemenfa</div>
<div class="option" data='{"value":"Kerecseny","state":"Zala"}'>Kerecseny</div>
<div class="option" data='{"value":"Kereseszeg","state":"Zala"}'>Kereseszeg</div>
<div class="option" data='{"value":"Kereszturpuszta","state":"Zala"}'>Kereszturpuszta</div>
<div class="option" data='{"value":"Kerettye","state":"Zala"}'>Kerettye</div>
<div class="option" data='{"value":"Kerka Szent Miklos","state":"Zala"}'>Kerka Szent Miklos</div>
<div class="option" data='{"value":"Kerkabarabas","state":"Zala"}'>Kerkabarabas</div>
<div class="option" data='{"value":"Kerkafalva","state":"Zala"}'>Kerkafalva</div>
<div class="option" data='{"value":"Kerkaiklod","state":"Zala"}'>Kerkaiklod</div>
<div class="option" data='{"value":"Kerkakutas","state":"Zala"}'>Kerkakutas</div>
<div class="option" data='{"value":"Kerkanemetfalu","state":"Zala"}'>Kerkanemetfalu</div>
<div class="option" data='{"value":"Kerkapentekfalu","state":"Zala"}'>Kerkapentekfalu</div>
<div class="option" data='{"value":"Kerkaszentkiraly","state":"Zala"}'>Kerkaszentkiraly</div>
<div class="option" data='{"value":"Kerkaszentmihaly","state":"Zala"}'>Kerkaszentmihaly</div>
<div class="option" data='{"value":"Kerkateskand","state":"Zala"}'>Kerkateskand</div>
<div class="option" data='{"value":"Kerkatotfalu","state":"Zala"}'>Kerkatotfalu</div>
<div class="option" data='{"value":"Kerkaujfalu","state":"Zala"}'>Kerkaujfalu</div>
<div class="option" data='{"value":"Kerulopuszta","state":"Zala"}'>Kerulopuszta</div>
<div class="option" data='{"value":"Keszthely","state":"Zala"}'>Keszthely</div>
<div class="option" data='{"value":"Keszthelyi","state":"Zala"}'>Keszthelyi</div>
<div class="option" data='{"value":"Ketbukkikoz","state":"Zala"}'>Ketbukkikoz</div>
<div class="option" data='{"value":"Kigyospuszta","state":"Zala"}'>Kigyospuszta</div>
<div class="option" data='{"value":"Kiliman","state":"Zala"}'>Kiliman</div>
<div class="option" data='{"value":"Kis Bagolai Hegy","state":"Zala"}'>Kis Bagolai Hegy</div>
<div class="option" data='{"value":"Kisbagola","state":"Zala"}'>Kisbagola</div>
<div class="option" data='{"value":"Kisbucsa","state":"Zala"}'>Kisbucsa</div>
<div class="option" data='{"value":"Kiscsehi","state":"Zala"}'>Kiscsehi</div>
<div class="option" data='{"value":"Kiscserpuszta","state":"Zala"}'>Kiscserpuszta</div>
<div class="option" data='{"value":"Kisfakos","state":"Zala"}'>Kisfakos</div>
<div class="option" data='{"value":"Kisfaludpuszta","state":"Zala"}'>Kisfaludpuszta</div>
<div class="option" data='{"value":"Kisfernekag","state":"Zala"}'>Kisfernekag</div>
<div class="option" data='{"value":"Kisfolyasidulo","state":"Zala"}'>Kisfolyasidulo</div>
<div class="option" data='{"value":"Kisgorbo","state":"Zala"}'>Kisgorbo</div>
<div class="option" data='{"value":"Kishegy","state":"Zala"}'>Kishegy</div>
<div class="option" data='{"value":"Kishegyhatitag","state":"Zala"}'>Kishegyhatitag</div>
<div class="option" data='{"value":"Kishidi Dulo","state":"Zala"}'>Kishidi Dulo</div>
<div class="option" data='{"value":"Kiskanizsa","state":"Zala"}'>Kiskanizsa</div>
<div class="option" data='{"value":"Kiskapornak","state":"Zala"}'>Kiskapornak</div>
<div class="option" data='{"value":"Kiskomarom","state":"Zala"}'>Kiskomarom</div>
<div class="option" data='{"value":"Kiskomaromi Hegy","state":"Zala"}'>Kiskomaromi Hegy</div>
<div class="option" data='{"value":"Kiskutas","state":"Zala"}'>Kiskutas</div>
<div class="option" data='{"value":"Kiskutihegy","state":"Zala"}'>Kiskutihegy</div>
<div class="option" data='{"value":"Kislakos","state":"Zala"}'>Kislakos</div>
<div class="option" data='{"value":"Kislakpuszta","state":"Zala"}'>Kislakpuszta</div>
<div class="option" data='{"value":"Kismalom","state":"Zala"}'>Kismalom</div>
<div class="option" data='{"value":"Kismezopuszta","state":"Zala"}'>Kismezopuszta</div>
<div class="option" data='{"value":"Kispali","state":"Zala"}'>Kispali</div>
<div class="option" data='{"value":"Kispatak","state":"Zala"}'>Kispatak</div>
<div class="option" data='{"value":"Kispuszta","state":"Zala"}'>Kispuszta</div>
<div class="option" data='{"value":"Kisrada","state":"Zala"}'>Kisrada</div>
<div class="option" data='{"value":"Kisrecse","state":"Zala"}'>Kisrecse</div>
<div class="option" data='{"value":"Kisrocse","state":"Zala"}'>Kisrocse</div>
<div class="option" data='{"value":"Kisszabar","state":"Zala"}'>Kisszabar</div>
<div class="option" data='{"value":"Kisszentgrot","state":"Zala"}'>Kisszentgrot</div>
<div class="option" data='{"value":"Kisszerdahely","state":"Zala"}'>Kisszerdahely</div>
<div class="option" data='{"value":"Kissziget","state":"Zala"}'>Kissziget</div>
<div class="option" data='{"value":"Kisszollos","state":"Zala"}'>Kisszollos</div>
<div class="option" data='{"value":"Kisszolos","state":"Zala"}'>Kisszolos</div>
<div class="option" data='{"value":"Kistolmacs","state":"Zala"}'>Kistolmacs</div>
<div class="option" data='{"value":"Kisvasarhely","state":"Zala"}'>Kisvasarhely</div>
<div class="option" data='{"value":"Kisvorcsok","state":"Zala"}'>Kisvorcsok</div>
<div class="option" data='{"value":"Kofejto","state":"Zala"}'>Kofejto</div>
<div class="option" data='{"value":"Kohat","state":"Zala"}'>Kohat</div>
<div class="option" data='{"value":"Kohegy","state":"Zala"}'>Kohegy</div>
<div class="option" data='{"value":"Kokenyesmindszent","state":"Zala"}'>Kokenyesmindszent</div>
<div class="option" data='{"value":"Kokonyapuszta","state":"Zala"}'>Kokonyapuszta</div>
<div class="option" data='{"value":"Kolbaszhegy","state":"Zala"}'>Kolbaszhegy</div>
<div class="option" data='{"value":"Komarvaros","state":"Zala"}'>Komarvaros</div>
<div class="option" data='{"value":"Kondorirtas","state":"Zala"}'>Kondorirtas</div>
<div class="option" data='{"value":"Kondorirtasdulo","state":"Zala"}'>Kondorirtasdulo</div>
<div class="option" data='{"value":"Konzarmajor","state":"Zala"}'>Konzarmajor</div>
<div class="option" data='{"value":"Korpavar","state":"Zala"}'>Korpavar</div>
<div class="option" data='{"value":"Koszorushegy","state":"Zala"}'>Koszorushegy</div>
<div class="option" data='{"value":"Kovecses","state":"Zala"}'>Kovecses</div>
<div class="option" data='{"value":"Kozepdabrony","state":"Zala"}'>Kozepdabrony</div>
<div class="option" data='{"value":"Kozephegyhat","state":"Zala"}'>Kozephegyhat</div>
<div class="option" data='{"value":"Kozepmajor","state":"Zala"}'>Kozepmajor</div>
<div class="option" data='{"value":"Kozepsomalom","state":"Zala"}'>Kozepsomalom</div>
<div class="option" data='{"value":"Kozmadombja","state":"Zala"}'>Kozmadombja</div>
<div class="option" data='{"value":"Kozvagohid","state":"Zala"}'>Kozvagohid</div>
<div class="option" data='{"value":"Krisztinamajor","state":"Zala"}'>Krisztinamajor</div>
<div class="option" data='{"value":"Krumplistanya","state":"Zala"}'>Krumplistanya</div>
<div class="option" data='{"value":"Kulsohegy","state":"Zala"}'>Kulsohegy</div>
<div class="option" data='{"value":"Kulsomajor","state":"Zala"}'>Kulsomajor</div>
<div class="option" data='{"value":"Kulsosard","state":"Zala"}'>Kulsosard</div>
<div class="option" data='{"value":"Kulsotanya","state":"Zala"}'>Kulsotanya</div>
<div class="option" data='{"value":"Kurjamajor","state":"Zala"}'>Kurjamajor</div>
<div class="option" data='{"value":"Kurjapuszta","state":"Zala"}'>Kurjapuszta</div>
<div class="option" data='{"value":"Kurtamajor","state":"Zala"}'>Kurtamajor</div>
<div class="option" data='{"value":"Kustanszeg","state":"Zala"}'>Kustanszeg</div>
<div class="option" data='{"value":"Kustany","state":"Zala"}'>Kustany</div>
<div class="option" data='{"value":"Kutfej","state":"Zala"}'>Kutfej</div>
<div class="option" data='{"value":"Kutfeji Hegy","state":"Zala"}'>Kutfeji Hegy</div>
<div class="option" data='{"value":"Lajoshazimajor","state":"Zala"}'>Lajoshazimajor</div>
<div class="option" data='{"value":"Lajoshazipuszta","state":"Zala"}'>Lajoshazipuszta</div>
<div class="option" data='{"value":"Lajosmajor","state":"Zala"}'>Lajosmajor</div>
<div class="option" data='{"value":"Lakhegy","state":"Zala"}'>Lakhegy</div>
<div class="option" data='{"value":"Landorhegy","state":"Zala"}'>Landorhegy</div>
<div class="option" data='{"value":"Laszlomajor","state":"Zala"}'>Laszlomajor</div>
<div class="option" data='{"value":"Lasztonya","state":"Zala"}'>Lasztonya</div>
<div class="option" data='{"value":"Lasztonyatag","state":"Zala"}'>Lasztonyatag</div>
<div class="option" data='{"value":"Latohegy","state":"Zala"}'>Latohegy</div>
<div class="option" data='{"value":"Lavaszi","state":"Zala"}'>Lavaszi</div>
<div class="option" data='{"value":"Lazsnakpuszta","state":"Zala"}'>Lazsnakpuszta</div>
<div class="option" data='{"value":"Lendvadedes","state":"Zala"}'>Lendvadedes</div>
<div class="option" data='{"value":"Lendvajakabfa","state":"Zala"}'>Lendvajakabfa</div>
<div class="option" data='{"value":"Lendvakecskes","state":"Zala"}'>Lendvakecskes</div>
<div class="option" data='{"value":"Lendvaujfalu","state":"Zala"}'>Lendvaujfalu</div>
<div class="option" data='{"value":"Lenti","state":"Zala"}'>Lenti</div>
<div class="option" data='{"value":"Lentihegy","state":"Zala"}'>Lentihegy</div>
<div class="option" data='{"value":"Lentikapolna","state":"Zala"}'>Lentikapolna</div>
<div class="option" data='{"value":"Lentikapolnaimajor","state":"Zala"}'>Lentikapolnaimajor</div>
<div class="option" data='{"value":"Lentiszombathely","state":"Zala"}'>Lentiszombathely</div>
<div class="option" data='{"value":"Letenye","state":"Zala"}'>Letenye</div>
<div class="option" data='{"value":"Levelespuszta","state":"Zala"}'>Levelespuszta</div>
<div class="option" data='{"value":"Lickovadamos","state":"Zala"}'>Lickovadamos</div>
<div class="option" data='{"value":"Liczkovadamos","state":"Zala"}'>Liczkovadamos</div>
<div class="option" data='{"value":"Ligetfalva","state":"Zala"}'>Ligetfalva</div>
<div class="option" data='{"value":"Lispe","state":"Zala"}'>Lispe</div>
<div class="option" data='{"value":"Lispeszentadorjan","state":"Zala"}'>Lispeszentadorjan</div>
<div class="option" data='{"value":"Liszo","state":"Zala"}'>Liszo</div>
<div class="option" data='{"value":"Loranthaza","state":"Zala"}'>Loranthaza</div>
<div class="option" data='{"value":"Lorincmajor","state":"Zala"}'>Lorincmajor</div>
<div class="option" data='{"value":"Lovasovic","state":"Zala"}'>Lovasovic</div>
<div class="option" data='{"value":"Lovaszi","state":"Zala"}'>Lovaszi</div>
<div class="option" data='{"value":"Lukahegy","state":"Zala"}'>Lukahegy</div>
<div class="option" data='{"value":"Luko","state":"Zala"}'>Luko</div>
<div class="option" data='{"value":"Magyarfold","state":"Zala"}'>Magyarfold</div>
<div class="option" data='{"value":"Magyarszentmiklos","state":"Zala"}'>Magyarszentmiklos</div>
<div class="option" data='{"value":"Magyarszerdahely","state":"Zala"}'>Magyarszerdahely</div>
<div class="option" data='{"value":"Mahomfa","state":"Zala"}'>Mahomfa</div>
<div class="option" data='{"value":"Malomretdulo","state":"Zala"}'>Malomretdulo</div>
<div class="option" data='{"value":"Malomtelep","state":"Zala"}'>Malomtelep</div>
<div class="option" data='{"value":"Maort Centrale","state":"Zala"}'>Maort Centrale</div>
<div class="option" data='{"value":"Margitmajor","state":"Zala"}'>Margitmajor</div>
<div class="option" data='{"value":"Mariahegy","state":"Zala"}'>Mariahegy</div>
<div class="option" data='{"value":"Mariskapuszta","state":"Zala"}'>Mariskapuszta</div>
<div class="option" data='{"value":"Markierdo","state":"Zala"}'>Markierdo</div>
<div class="option" data='{"value":"Markus","state":"Zala"}'>Markus</div>
<div class="option" data='{"value":"Maroc","state":"Zala"}'>Maroc</div>
<div class="option" data='{"value":"Marokfold","state":"Zala"}'>Marokfold</div>
<div class="option" data='{"value":"Martonfa","state":"Zala"}'>Martonfa</div>
<div class="option" data='{"value":"Martonfa Malom","state":"Zala"}'>Martonfa Malom</div>
<div class="option" data='{"value":"Martonfapuszta","state":"Zala"}'>Martonfapuszta</div>
<div class="option" data='{"value":"Meleghegy","state":"Zala"}'>Meleghegy</div>
<div class="option" data='{"value":"Mereta","state":"Zala"}'>Mereta</div>
<div class="option" data='{"value":"Mezeimalom","state":"Zala"}'>Mezeimalom</div>
<div class="option" data='{"value":"Mezohegy","state":"Zala"}'>Mezohegy</div>
<div class="option" data='{"value":"Mihald","state":"Zala"}'>Mihald</div>
<div class="option" data='{"value":"Mihalyfa","state":"Zala"}'>Mihalyfa</div>
<div class="option" data='{"value":"Mihalyhaza","state":"Zala"}'>Mihalyhaza</div>
<div class="option" data='{"value":"Mihalyhazapuszta","state":"Zala"}'>Mihalyhazapuszta</div>
<div class="option" data='{"value":"Mihompuszta","state":"Zala"}'>Mihompuszta</div>
<div class="option" data='{"value":"Mikefa","state":"Zala"}'>Mikefa</div>
<div class="option" data='{"value":"Mikekaracsonyfa","state":"Zala"}'>Mikekaracsonyfa</div>
<div class="option" data='{"value":"Miklosfa","state":"Zala"}'>Miklosfa</div>
<div class="option" data='{"value":"Miklosmajor","state":"Zala"}'>Miklosmajor</div>
<div class="option" data='{"value":"Miksamajor","state":"Zala"}'>Miksamajor</div>
<div class="option" data='{"value":"Milej","state":"Zala"}'>Milej</div>
<div class="option" data='{"value":"Milejszeg","state":"Zala"}'>Milejszeg</div>
<div class="option" data='{"value":"Misefa","state":"Zala"}'>Misefa</div>
<div class="option" data='{"value":"Miskehegy","state":"Zala"}'>Miskehegy</div>
<div class="option" data='{"value":"Mollermajor","state":"Zala"}'>Mollermajor</div>
<div class="option" data='{"value":"Molnari","state":"Zala"}'>Molnari</div>
<div class="option" data='{"value":"Morganypuszta","state":"Zala"}'>Morganypuszta</div>
<div class="option" data='{"value":"Morichely","state":"Zala"}'>Morichely</div>
<div class="option" data='{"value":"Morichelypuszta","state":"Zala"}'>Morichelypuszta</div>
<div class="option" data='{"value":"Mumor","state":"Zala"}'>Mumor</div>
<div class="option" data='{"value":"Murahid","state":"Zala"}'>Murahid</div>
<div class="option" data='{"value":"Murakeresztur","state":"Zala"}'>Murakeresztur</div>
<div class="option" data='{"value":"Muraratka","state":"Zala"}'>Muraratka</div>
<div class="option" data='{"value":"Muraszemenye","state":"Zala"}'>Muraszemenye</div>
<div class="option" data='{"value":"Nagybagola","state":"Zala"}'>Nagybagola</div>
<div class="option" data='{"value":"Nagybagolai Hegy","state":"Zala"}'>Nagybagolai Hegy</div>
<div class="option" data='{"value":"Nagybakonak","state":"Zala"}'>Nagybakonak</div>
<div class="option" data='{"value":"Nagydomb","state":"Zala"}'>Nagydomb</div>
<div class="option" data='{"value":"Nagydombiszollo","state":"Zala"}'>Nagydombiszollo</div>
<div class="option" data='{"value":"Nagyerdo","state":"Zala"}'>Nagyerdo</div>
<div class="option" data='{"value":"Nagyfakos","state":"Zala"}'>Nagyfakos</div>
<div class="option" data='{"value":"Nagyfaludpuszta","state":"Zala"}'>Nagyfaludpuszta</div>
<div class="option" data='{"value":"Nagyfernekag","state":"Zala"}'>Nagyfernekag</div>
<div class="option" data='{"value":"Nagygorbo","state":"Zala"}'>Nagygorbo</div>
<div class="option" data='{"value":"Nagyhegy","state":"Zala"}'>Nagyhegy</div>
<div class="option" data='{"value":"Nagyhegypuszta","state":"Zala"}'>Nagyhegypuszta</div>
<div class="option" data='{"value":"Nagyhorvati","state":"Zala"}'>Nagyhorvati</div>
<div class="option" data='{"value":"Nagykanizsa","state":"Zala"}'>Nagykanizsa</div>
<div class="option" data='{"value":"Nagykapornak","state":"Zala"}'>Nagykapornak</div>
<div class="option" data='{"value":"Nagykapornok","state":"Zala"}'>Nagykapornok</div>
<div class="option" data='{"value":"Nagykutas","state":"Zala"}'>Nagykutas</div>
<div class="option" data='{"value":"Nagylengyel","state":"Zala"}'>Nagylengyel</div>
<div class="option" data='{"value":"Nagypali","state":"Zala"}'>Nagypali</div>
<div class="option" data='{"value":"Nagyrada","state":"Zala"}'>Nagyrada</div>
<div class="option" data='{"value":"Nagyrecse","state":"Zala"}'>Nagyrecse</div>
<div class="option" data='{"value":"Nagyvolgy","state":"Zala"}'>Nagyvolgy</div>
<div class="option" data='{"value":"Nandormajor","state":"Zala"}'>Nandormajor</div>
<div class="option" data='{"value":"Napradfa","state":"Zala"}'>Napradfa</div>
<div class="option" data='{"value":"Negyszegmajor","state":"Zala"}'>Negyszegmajor</div>
<div class="option" data='{"value":"Negyszogmajor","state":"Zala"}'>Negyszogmajor</div>
<div class="option" data='{"value":"Nekeresd","state":"Zala"}'>Nekeresd</div>
<div class="option" data='{"value":"Nekeresdmajor","state":"Zala"}'>Nekeresdmajor</div>
<div class="option" data='{"value":"Nemesapati","state":"Zala"}'>Nemesapati</div>
<div class="option" data='{"value":"Nemesboldogasszonyfa","state":"Zala"}'>Nemesboldogasszonyfa</div>
<div class="option" data='{"value":"Nemesbuk","state":"Zala"}'>Nemesbuk</div>
<div class="option" data='{"value":"Nemesbukk","state":"Zala"}'>Nemesbukk</div>
<div class="option" data='{"value":"Nemeshetes","state":"Zala"}'>Nemeshetes</div>
<div class="option" data='{"value":"Nemesnep","state":"Zala"}'>Nemesnep</div>
<div class="option" data='{"value":"Nemespatro","state":"Zala"}'>Nemespatro</div>
<div class="option" data='{"value":"Nemesrado","state":"Zala"}'>Nemesrado</div>
<div class="option" data='{"value":"Nemessandorhaza","state":"Zala"}'>Nemessandorhaza</div>
<div class="option" data='{"value":"Nemesszentandras","state":"Zala"}'>Nemesszentandras</div>
<div class="option" data='{"value":"Nemesszer","state":"Zala"}'>Nemesszer</div>
<div class="option" data='{"value":"Nemetfalu","state":"Zala"}'>Nemetfalu</div>
<div class="option" data='{"value":"Nena","state":"Zala"}'>Nena</div>
<div class="option" data='{"value":"Nenai Erdeszlak","state":"Zala"}'>Nenai Erdeszlak</div>
<div class="option" data='{"value":"Neszele","state":"Zala"}'>Neszele</div>
<div class="option" data='{"value":"Nova","state":"Zala"}'>Nova</div>
<div class="option" data='{"value":"Nyakashaza","state":"Zala"}'>Nyakashaza</div>
<div class="option" data='{"value":"Nyakashazapuszta","state":"Zala"}'>Nyakashazapuszta</div>
<div class="option" data='{"value":"Nyiresimalom","state":"Zala"}'>Nyiresimalom</div>
<div class="option" data='{"value":"Nyiresmajor","state":"Zala"}'>Nyiresmajor</div>
<div class="option" data='{"value":"Nyirlakosa","state":"Zala"}'>Nyirlakosa</div>
<div class="option" data='{"value":"Obornak","state":"Zala"}'>Obornak</div>
<div class="option" data='{"value":"Ohid","state":"Zala"}'>Ohid</div>
<div class="option" data='{"value":"Olgamajor","state":"Zala"}'>Olgamajor</div>
<div class="option" data='{"value":"Oltarc","state":"Zala"}'>Oltarc</div>
<div class="option" data='{"value":"Orbanyosfa","state":"Zala"}'>Orbanyosfa</div>
<div class="option" data='{"value":"Oreghegy","state":"Zala"}'>Oreghegy</div>
<div class="option" data='{"value":"Oreghosszuhegy","state":"Zala"}'>Oreghosszuhegy</div>
<div class="option" data='{"value":"Ormand","state":"Zala"}'>Ormand</div>
<div class="option" data='{"value":"Ormandlak","state":"Zala"}'>Ormandlak</div>
<div class="option" data='{"value":"Ormandpuszta","state":"Zala"}'>Ormandpuszta</div>
<div class="option" data='{"value":"Oroklan","state":"Zala"}'>Oroklan</div>
<div class="option" data='{"value":"Oromhegy","state":"Zala"}'>Oromhegy</div>
<div class="option" data='{"value":"Orosztony","state":"Zala"}'>Orosztony</div>
<div class="option" data='{"value":"Orosztonyi Tanyak","state":"Zala"}'>Orosztonyi Tanyak</div>
<div class="option" data='{"value":"Ortahaza","state":"Zala"}'>Ortahaza</div>
<div class="option" data='{"value":"Orvenyes","state":"Zala"}'>Orvenyes</div>
<div class="option" data='{"value":"Orvenyeshegy","state":"Zala"}'>Orvenyeshegy</div>
<div class="option" data='{"value":"Ozmanbuk","state":"Zala"}'>Ozmanbuk</div>
<div class="option" data='{"value":"Pacodpuszta","state":"Zala"}'>Pacodpuszta</div>
<div class="option" data='{"value":"Pacsa","state":"Zala"}'>Pacsa</div>
<div class="option" data='{"value":"Pacsahegy","state":"Zala"}'>Pacsahegy</div>
<div class="option" data='{"value":"Pacsai Malom","state":"Zala"}'>Pacsai Malom</div>
<div class="option" data='{"value":"Pacsamalom","state":"Zala"}'>Pacsamalom</div>
<div class="option" data='{"value":"Pacsapuszta","state":"Zala"}'>Pacsapuszta</div>
<div class="option" data='{"value":"Pacsatuttos","state":"Zala"}'>Pacsatuttos</div>
<div class="option" data='{"value":"Padar","state":"Zala"}'>Padar</div>
<div class="option" data='{"value":"Pajhegy","state":"Zala"}'>Pajhegy</div>
<div class="option" data='{"value":"Paka","state":"Zala"}'>Paka</div>
<div class="option" data='{"value":"Pakaricshegy","state":"Zala"}'>Pakaricshegy</div>
<div class="option" data='{"value":"Pakod","state":"Zala"}'>Pakod</div>
<div class="option" data='{"value":"Pakodhegy","state":"Zala"}'>Pakodhegy</div>
<div class="option" data='{"value":"Palankosmajor","state":"Zala"}'>Palankosmajor</div>
<div class="option" data='{"value":"Palankospuszta","state":"Zala"}'>Palankospuszta</div>
<div class="option" data='{"value":"Palfiszeg","state":"Zala"}'>Palfiszeg</div>
<div class="option" data='{"value":"Palin","state":"Zala"}'>Palin</div>
<div class="option" data='{"value":"Palosmalom","state":"Zala"}'>Palosmalom</div>
<div class="option" data='{"value":"Paphegy","state":"Zala"}'>Paphegy</div>
<div class="option" data='{"value":"Papucshegy","state":"Zala"}'>Papucshegy</div>
<div class="option" data='{"value":"Paragvarpuszta","state":"Zala"}'>Paragvarpuszta</div>
<div class="option" data='{"value":"Parasza","state":"Zala"}'>Parasza</div>
<div class="option" data='{"value":"Paraszatelep","state":"Zala"}'>Paraszatelep</div>
<div class="option" data='{"value":"Parraghegy","state":"Zala"}'>Parraghegy</div>
<div class="option" data='{"value":"Parragvarpuszta","state":"Zala"}'>Parragvarpuszta</div>
<div class="option" data='{"value":"Part","state":"Zala"}'>Part</div>
<div class="option" data='{"value":"Pat","state":"Zala"}'>Pat</div>
<div class="option" data='{"value":"Pataikurtos","state":"Zala"}'>Pataikurtos</div>
<div class="option" data='{"value":"Patro","state":"Zala"}'>Patro</div>
<div class="option" data='{"value":"Patroi Tanya","state":"Zala"}'>Patroi Tanya</div>
<div class="option" data='{"value":"Petendpuszta","state":"Zala"}'>Petendpuszta</div>
<div class="option" data='{"value":"Pethohenye","state":"Zala"}'>Pethohenye</div>
<div class="option" data='{"value":"Petohenye","state":"Zala"}'>Petohenye</div>
<div class="option" data='{"value":"Petrikeresztur","state":"Zala"}'>Petrikeresztur</div>
<div class="option" data='{"value":"Petrivente","state":"Zala"}'>Petrivente</div>
<div class="option" data='{"value":"Petrocpuszta","state":"Zala"}'>Petrocpuszta</div>
<div class="option" data='{"value":"Petroczpuszta","state":"Zala"}'>Petroczpuszta</div>
<div class="option" data='{"value":"Pinkocimajor","state":"Zala"}'>Pinkocimajor</div>
<div class="option" data='{"value":"Piripocspuszta","state":"Zala"}'>Piripocspuszta</div>
<div class="option" data='{"value":"Pirosmajor","state":"Zala"}'>Pirosmajor</div>
<div class="option" data='{"value":"Pogacsahegy","state":"Zala"}'>Pogacsahegy</div>
<div class="option" data='{"value":"Pokaszepetk","state":"Zala"}'>Pokaszepetk</div>
<div class="option" data='{"value":"Pola","state":"Zala"}'>Pola</div>
<div class="option" data='{"value":"Poloske","state":"Zala"}'>Poloske</div>
<div class="option" data='{"value":"Poloskefo","state":"Zala"}'>Poloskefo</div>
<div class="option" data='{"value":"Pordefolde","state":"Zala"}'>Pordefolde</div>
<div class="option" data='{"value":"Porgoleny","state":"Zala"}'>Porgoleny</div>
<div class="option" data='{"value":"Porgolin","state":"Zala"}'>Porgolin</div>
<div class="option" data='{"value":"Porszombat","state":"Zala"}'>Porszombat</div>
<div class="option" data='{"value":"Potrete","state":"Zala"}'>Potrete</div>
<div class="option" data='{"value":"Pozva","state":"Zala"}'>Pozva</div>
<div class="option" data='{"value":"Puszta","state":"Zala"}'>Puszta</div>
<div class="option" data='{"value":"Pusztaapati","state":"Zala"}'>Pusztaapati</div>
<div class="option" data='{"value":"Pusztaederics","state":"Zala"}'>Pusztaederics</div>
<div class="option" data='{"value":"Pusztamagyarod","state":"Zala"}'>Pusztamagyarod</div>
<div class="option" data='{"value":"Pusztamagyorod","state":"Zala"}'>Pusztamagyorod</div>
<div class="option" data='{"value":"Pusztamezo","state":"Zala"}'>Pusztamezo</div>
<div class="option" data='{"value":"Pusztaszentlaszlo","state":"Zala"}'>Pusztaszentlaszlo</div>
<div class="option" data='{"value":"Pusztaszentpeter","state":"Zala"}'>Pusztaszentpeter</div>
<div class="option" data='{"value":"Rabgazdasag","state":"Zala"}'>Rabgazdasag</div>
<div class="option" data='{"value":"Radihaza","state":"Zala"}'>Radihaza</div>
<div class="option" data='{"value":"Radihazapuszta","state":"Zala"}'>Radihazapuszta</div>
<div class="option" data='{"value":"Rado","state":"Zala"}'>Rado</div>
<div class="option" data='{"value":"Raganpuszta","state":"Zala"}'>Raganpuszta</div>
<div class="option" data='{"value":"Rakoczitelep","state":"Zala"}'>Rakoczitelep</div>
<div class="option" data='{"value":"Ram","state":"Zala"}'>Ram</div>
<div class="option" data='{"value":"Ramocsa","state":"Zala"}'>Ramocsa</div>
<div class="option" data='{"value":"Rapacs","state":"Zala"}'>Rapacs</div>
<div class="option" data='{"value":"Ratka","state":"Zala"}'>Ratka</div>
<div class="option" data='{"value":"Redics","state":"Zala"}'>Redics</div>
<div class="option" data='{"value":"Resznek","state":"Zala"}'>Resznek</div>
<div class="option" data='{"value":"Rezi","state":"Zala"}'>Rezi</div>
<div class="option" data='{"value":"Rigohegyalja","state":"Zala"}'>Rigohegyalja</div>
<div class="option" data='{"value":"Rigyac","state":"Zala"}'>Rigyac</div>
<div class="option" data='{"value":"Rinszkymajor","state":"Zala"}'>Rinszkymajor</div>
<div class="option" data='{"value":"Rokahazamajor","state":"Zala"}'>Rokahazamajor</div>
<div class="option" data='{"value":"Rovidjanka","state":"Zala"}'>Rovidjanka</div>
<div class="option" data='{"value":"Rozsasszeg","state":"Zala"}'>Rozsasszeg</div>
<div class="option" data='{"value":"Sagod","state":"Zala"}'>Sagod</div>
<div class="option" data='{"value":"Sagot Puszta","state":"Zala"}'>Sagot Puszta</div>
<div class="option" data='{"value":"Sagpuszta","state":"Zala"}'>Sagpuszta</div>
<div class="option" data='{"value":"Salomvar","state":"Zala"}'>Salomvar</div>
<div class="option" data='{"value":"Sanc","state":"Zala"}'>Sanc</div>
<div class="option" data='{"value":"Sanci Major","state":"Zala"}'>Sanci Major</div>
<div class="option" data='{"value":"Sand","state":"Zala"}'>Sand</div>
<div class="option" data='{"value":"Sandormajor","state":"Zala"}'>Sandormajor</div>
<div class="option" data='{"value":"Sandorpuszta","state":"Zala"}'>Sandorpuszta</div>
<div class="option" data='{"value":"Sardirend","state":"Zala"}'>Sardirend</div>
<div class="option" data='{"value":"Sarhida","state":"Zala"}'>Sarhida</div>
<div class="option" data='{"value":"Sarmellek","state":"Zala"}'>Sarmellek</div>
<div class="option" data='{"value":"Semjenhaza","state":"Zala"}'>Semjenhaza</div>
<div class="option" data='{"value":"Senye","state":"Zala"}'>Senye</div>
<div class="option" data='{"value":"Sojtor","state":"Zala"}'>Sojtor</div>
<div class="option" data='{"value":"Somogyszentmiklos","state":"Zala"}'>Somogyszentmiklos</div>
<div class="option" data='{"value":"Sormas","state":"Zala"}'>Sormas</div>
<div class="option" data='{"value":"Sumegcsehi","state":"Zala"}'>Sumegcsehi</div>
<div class="option" data='{"value":"Surd","state":"Zala"}'>Surd</div>
<div class="option" data='{"value":"Szabadhegy","state":"Zala"}'>Szabadhegy</div>
<div class="option" data='{"value":"Szabohegy","state":"Zala"}'>Szabohegy</div>
<div class="option" data='{"value":"Szakahegy","state":"Zala"}'>Szakahegy</div>
<div class="option" data='{"value":"Szalapa","state":"Zala"}'>Szalapa</div>
<div class="option" data='{"value":"Szaplanyos","state":"Zala"}'>Szaplanyos</div>
<div class="option" data='{"value":"Szarkahegy","state":"Zala"}'>Szarkahegy</div>
<div class="option" data='{"value":"Szecsisziget","state":"Zala"}'>Szecsisziget</div>
<div class="option" data='{"value":"Szegfalusihegy","state":"Zala"}'>Szegfalusihegy</div>
<div class="option" data='{"value":"Szekeresszeri Dulo","state":"Zala"}'>Szekeresszeri Dulo</div>
<div class="option" data='{"value":"Szelgyep","state":"Zala"}'>Szelgyep</div>
<div class="option" data='{"value":"Szelgyop","state":"Zala"}'>Szelgyop</div>
<div class="option" data='{"value":"Szelgyopmajor","state":"Zala"}'>Szelgyopmajor</div>
<div class="option" data='{"value":"Szemenyecsornye","state":"Zala"}'>Szemenyecsornye</div>
<div class="option" data='{"value":"Szenasvolgy","state":"Zala"}'>Szenasvolgy</div>
<div class="option" data='{"value":"Szenasvolgypuszta","state":"Zala"}'>Szenasvolgypuszta</div>
<div class="option" data='{"value":"Szent Andrasi Puszta","state":"Zala"}'>Szent Andrasi Puszta</div>
<div class="option" data='{"value":"Szentadorjan","state":"Zala"}'>Szentadorjan</div>
<div class="option" data='{"value":"Szentandraspuszta","state":"Zala"}'>Szentandraspuszta</div>
<div class="option" data='{"value":"Szenterzsebethegy","state":"Zala"}'>Szenterzsebethegy</div>
<div class="option" data='{"value":"Szentgyorgyvar","state":"Zala"}'>Szentgyorgyvar</div>
<div class="option" data='{"value":"Szentgyorgyvarihegy","state":"Zala"}'>Szentgyorgyvarihegy</div>
<div class="option" data='{"value":"Szentgyorgyvolgy","state":"Zala"}'>Szentgyorgyvolgy</div>
<div class="option" data='{"value":"Szentharomsagpuszta","state":"Zala"}'>Szentharomsagpuszta</div>
<div class="option" data='{"value":"Szentistvanlak","state":"Zala"}'>Szentistvanlak</div>
<div class="option" data='{"value":"Szentjanoshegy","state":"Zala"}'>Szentjanoshegy</div>
<div class="option" data='{"value":"Szentkozmadombja","state":"Zala"}'>Szentkozmadombja</div>
<div class="option" data='{"value":"Szentliszlo","state":"Zala"}'>Szentliszlo</div>
<div class="option" data='{"value":"Szentmargitfalva","state":"Zala"}'>Szentmargitfalva</div>
<div class="option" data='{"value":"Szentmartonmajor","state":"Zala"}'>Szentmartonmajor</div>
<div class="option" data='{"value":"Szentmartonpuszta","state":"Zala"}'>Szentmartonpuszta</div>
<div class="option" data='{"value":"Szentmihalymalom","state":"Zala"}'>Szentmihalymalom</div>
<div class="option" data='{"value":"Szentmihalypuszta","state":"Zala"}'>Szentmihalypuszta</div>
<div class="option" data='{"value":"Szentpal","state":"Zala"}'>Szentpal</div>
<div class="option" data='{"value":"Szentpeterfolde","state":"Zala"}'>Szentpeterfolde</div>
<div class="option" data='{"value":"Szentpeterur","state":"Zala"}'>Szentpeterur</div>
<div class="option" data='{"value":"Szenttamaspuszta","state":"Zala"}'>Szenttamaspuszta</div>
<div class="option" data='{"value":"Szepetk","state":"Zala"}'>Szepetk</div>
<div class="option" data='{"value":"Szepetkpuszta","state":"Zala"}'>Szepetkpuszta</div>
<div class="option" data='{"value":"Szepetnek","state":"Zala"}'>Szepetnek</div>
<div class="option" data='{"value":"Szijartohaza","state":"Zala"}'>Szijartohaza</div>
<div class="option" data='{"value":"Szilvagy","state":"Zala"}'>Szilvagy</div>
<div class="option" data='{"value":"Szivhegy","state":"Zala"}'>Szivhegy</div>
<div class="option" data='{"value":"Szoboszlo","state":"Zala"}'>Szoboszlo</div>
<div class="option" data='{"value":"Szocehegy","state":"Zala"}'>Szocehegy</div>
<div class="option" data='{"value":"Szollospuszta","state":"Zala"}'>Szollospuszta</div>
<div class="option" data='{"value":"Szompacspuszta","state":"Zala"}'>Szompacspuszta</div>
<div class="option" data='{"value":"Szorosihegy","state":"Zala"}'>Szorosihegy</div>
<div class="option" data='{"value":"Sztaszikovszkymajor","state":"Zala"}'>Sztaszikovszkymajor</div>
<div class="option" data='{"value":"Szucsmajor","state":"Zala"}'>Szucsmajor</div>
<div class="option" data='{"value":"Szunyogvar","state":"Zala"}'>Szunyogvar</div>
<div class="option" data='{"value":"Szurdapuszta","state":"Zala"}'>Szurdapuszta</div>
<div class="option" data='{"value":"Tagi Major","state":"Zala"}'>Tagi Major</div>
<div class="option" data='{"value":"Tagipuszta","state":"Zala"}'>Tagipuszta</div>
<div class="option" data='{"value":"Taranyimajor","state":"Zala"}'>Taranyimajor</div>
<div class="option" data='{"value":"Tarnokhegy","state":"Zala"}'>Tarnokhegy</div>
<div class="option" data='{"value":"Teglaegeto","state":"Zala"}'>Teglaegeto</div>
<div class="option" data='{"value":"Tekenye","state":"Zala"}'>Tekenye</div>
<div class="option" data='{"value":"Terezmajor","state":"Zala"}'>Terezmajor</div>
<div class="option" data='{"value":"Teskand","state":"Zala"}'>Teskand</div>
<div class="option" data='{"value":"Teskandi Malom","state":"Zala"}'>Teskandi Malom</div>
<div class="option" data='{"value":"Teskandi Tanyak","state":"Zala"}'>Teskandi Tanyak</div>
<div class="option" data='{"value":"Tilaj","state":"Zala"}'>Tilaj</div>
<div class="option" data='{"value":"Tilajujhegy","state":"Zala"}'>Tilajujhegy</div>
<div class="option" data='{"value":"Toberek","state":"Zala"}'>Toberek</div>
<div class="option" data='{"value":"Toberki Malom","state":"Zala"}'>Toberki Malom</div>
<div class="option" data='{"value":"Tofej","state":"Zala"}'>Tofej</div>
<div class="option" data='{"value":"Tolosipuszta","state":"Zala"}'>Tolosipuszta</div>
<div class="option" data='{"value":"Tordahegy","state":"Zala"}'>Tordahegy</div>
<div class="option" data='{"value":"Tormafolde","state":"Zala"}'>Tormafolde</div>
<div class="option" data='{"value":"Tormahegy","state":"Zala"}'>Tormahegy</div>
<div class="option" data='{"value":"Tornyiszentmiklos","state":"Zala"}'>Tornyiszentmiklos</div>
<div class="option" data='{"value":"Torokcsapashegy","state":"Zala"}'>Torokcsapashegy</div>
<div class="option" data='{"value":"Totfalu","state":"Zala"}'>Totfalu</div>
<div class="option" data='{"value":"Tothegy","state":"Zala"}'>Tothegy</div>
<div class="option" data='{"value":"Toti Allami Gazdasag","state":"Zala"}'>Toti Allami Gazdasag</div>
<div class="option" data='{"value":"Totimajor","state":"Zala"}'>Totimajor</div>
<div class="option" data='{"value":"Totszentmarton","state":"Zala"}'>Totszentmarton</div>
<div class="option" data='{"value":"Totszerdahely","state":"Zala"}'>Totszerdahely</div>
<div class="option" data='{"value":"Totvarmajor","state":"Zala"}'>Totvarmajor</div>
<div class="option" data='{"value":"Totvarpuszta","state":"Zala"}'>Totvarpuszta</div>
<div class="option" data='{"value":"Tozegtelep","state":"Zala"}'>Tozegtelep</div>
<div class="option" data='{"value":"Turje","state":"Zala"}'>Turje</div>
<div class="option" data='{"value":"Tuskeszentpeter","state":"Zala"}'>Tuskeszentpeter</div>
<div class="option" data='{"value":"Tuskevarimajor","state":"Zala"}'>Tuskevarimajor</div>
<div class="option" data='{"value":"Tuskospuszta","state":"Zala"}'>Tuskospuszta</div>
<div class="option" data='{"value":"Tuttos","state":"Zala"}'>Tuttos</div>
<div class="option" data='{"value":"Ujavaspuszta","state":"Zala"}'>Ujavaspuszta</div>
<div class="option" data='{"value":"Ujcsaford","state":"Zala"}'>Ujcsaford</div>
<div class="option" data='{"value":"Ujfalu","state":"Zala"}'>Ujfalu</div>
<div class="option" data='{"value":"Ujfenyos","state":"Zala"}'>Ujfenyos</div>
<div class="option" data='{"value":"Ujhegy","state":"Zala"}'>Ujhegy</div>
<div class="option" data='{"value":"Ujmajor","state":"Zala"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujneppuszta","state":"Zala"}'>Ujneppuszta</div>
<div class="option" data='{"value":"Ujszabar","state":"Zala"}'>Ujszabar</div>
<div class="option" data='{"value":"Ujtelep","state":"Zala"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujudvar","state":"Zala"}'>Ujudvar</div>
<div class="option" data='{"value":"Ungjakabfa","state":"Zala"}'>Ungjakabfa</div>
<div class="option" data='{"value":"Ungortanya","state":"Zala"}'>Ungortanya</div>
<div class="option" data='{"value":"Uszthegy","state":"Zala"}'>Uszthegy</div>
<div class="option" data='{"value":"Vajdamajor","state":"Zala"}'>Vajdamajor</div>
<div class="option" data='{"value":"Vakaroshegy","state":"Zala"}'>Vakaroshegy</div>
<div class="option" data='{"value":"Vakola","state":"Zala"}'>Vakola</div>
<div class="option" data='{"value":"Valeriamajor","state":"Zala"}'>Valeriamajor</div>
<div class="option" data='{"value":"Valeriapuszta","state":"Zala"}'>Valeriapuszta</div>
<div class="option" data='{"value":"Valickapuszta","state":"Zala"}'>Valickapuszta</div>
<div class="option" data='{"value":"Valickatanya","state":"Zala"}'>Valickatanya</div>
<div class="option" data='{"value":"Valkonya","state":"Zala"}'>Valkonya</div>
<div class="option" data='{"value":"Vallus","state":"Zala"}'>Vallus</div>
<div class="option" data='{"value":"Vallusimajor","state":"Zala"}'>Vallusimajor</div>
<div class="option" data='{"value":"Vallusmajor","state":"Zala"}'>Vallusmajor</div>
<div class="option" data='{"value":"Varfolde","state":"Zala"}'>Varfolde</div>
<div class="option" data='{"value":"Vargaszeg","state":"Zala"}'>Vargaszeg</div>
<div class="option" data='{"value":"Vargatanya","state":"Zala"}'>Vargatanya</div>
<div class="option" data='{"value":"Vargyaspuszta","state":"Zala"}'>Vargyaspuszta</div>
<div class="option" data='{"value":"Varhelypuszta","state":"Zala"}'>Varhelypuszta</div>
<div class="option" data='{"value":"Varoshegy","state":"Zala"}'>Varoshegy</div>
<div class="option" data='{"value":"Varvolgy","state":"Zala"}'>Varvolgy</div>
<div class="option" data='{"value":"Varvolgyi Alsoszollo","state":"Zala"}'>Varvolgyi Alsoszollo</div>
<div class="option" data='{"value":"Varvolgyi Alsoszolohegy","state":"Zala"}'>Varvolgyi Alsoszolohegy</div>
<div class="option" data='{"value":"Vasboldogasszony","state":"Zala"}'>Vasboldogasszony</div>
<div class="option" data='{"value":"Vashegy","state":"Zala"}'>Vashegy</div>
<div class="option" data='{"value":"Vaspor","state":"Zala"}'>Vaspor</div>
<div class="option" data='{"value":"Velence","state":"Zala"}'>Velence</div>
<div class="option" data='{"value":"Velenceszel","state":"Zala"}'>Velenceszel</div>
<div class="option" data='{"value":"Ventepuszta","state":"Zala"}'>Ventepuszta</div>
<div class="option" data='{"value":"Vergyalom","state":"Zala"}'>Vergyalom</div>
<div class="option" data='{"value":"Vergyalomdulo","state":"Zala"}'>Vergyalomdulo</div>
<div class="option" data='{"value":"Vetyempuszta","state":"Zala"}'>Vetyempuszta</div>
<div class="option" data='{"value":"Vilagosvar","state":"Zala"}'>Vilagosvar</div>
<div class="option" data='{"value":"Vilmamajor","state":"Zala"}'>Vilmamajor</div>
<div class="option" data='{"value":"Vincemajor","state":"Zala"}'>Vincemajor</div>
<div class="option" data='{"value":"Vindornyafok","state":"Zala"}'>Vindornyafok</div>
<div class="option" data='{"value":"Vindornyalak","state":"Zala"}'>Vindornyalak</div>
<div class="option" data='{"value":"Vindornyaszollos","state":"Zala"}'>Vindornyaszollos</div>
<div class="option" data='{"value":"Vindornyaszolos","state":"Zala"}'>Vindornyaszolos</div>
<div class="option" data='{"value":"Viraghegy","state":"Zala"}'>Viraghegy</div>
<div class="option" data='{"value":"Vizallodulo","state":"Zala"}'>Vizallodulo</div>
<div class="option" data='{"value":"Vockond","state":"Zala"}'>Vockond</div>
<div class="option" data='{"value":"Vockondi Major","state":"Zala"}'>Vockondi Major</div>
<div class="option" data='{"value":"Vockondmajor","state":"Zala"}'>Vockondmajor</div>
<div class="option" data='{"value":"Volgy","state":"Zala"}'>Volgy</div>
<div class="option" data='{"value":"Volgykozihegy","state":"Zala"}'>Volgykozihegy</div>
<div class="option" data='{"value":"Vonyarcvashegy","state":"Zala"}'>Vonyarcvashegy</div>
<div class="option" data='{"value":"Vorcsok","state":"Zala"}'>Vorcsok</div>
<div class="option" data='{"value":"Vorcsokpuszta","state":"Zala"}'>Vorcsokpuszta</div>
<div class="option" data='{"value":"Vorhota","state":"Zala"}'>Vorhota</div>
<div class="option" data='{"value":"Voroserdodulo","state":"Zala"}'>Voroserdodulo</div>
<div class="option" data='{"value":"Vorosmezo","state":"Zala"}'>Vorosmezo</div>
<div class="option" data='{"value":"Vorospatak","state":"Zala"}'>Vorospatak</div>
<div class="option" data='{"value":"Vorospataki Tanya","state":"Zala"}'>Vorospataki Tanya</div>
<div class="option" data='{"value":"Vorosszeg","state":"Zala"}'>Vorosszeg</div>
<div class="option" data='{"value":"Vorru","state":"Zala"}'>Vorru</div>
<div class="option" data='{"value":"Zagorhida","state":"Zala"}'>Zagorhida</div>
<div class="option" data='{"value":"Zajda","state":"Zala"}'>Zajda</div>
<div class="option" data='{"value":"Zajdamajor","state":"Zala"}'>Zajdamajor</div>
<div class="option" data='{"value":"Zajdapuszta","state":"Zala"}'>Zajdapuszta</div>
<div class="option" data='{"value":"Zajk","state":"Zala"}'>Zajk</div>
<div class="option" data='{"value":"Zala","state":"Zala"}'>Zala</div>
<div class="option" data='{"value":"Zala County","state":"Zala"}'>Zala County</div>
<div class="option" data='{"value":"Zala Megye","state":"Zala"}'>Zala Megye</div>
<div class="option" data='{"value":"Zalaapati","state":"Zala"}'>Zalaapati</div>
<div class="option" data='{"value":"Zalabaksa","state":"Zala"}'>Zalabaksa</div>
<div class="option" data='{"value":"Zalaber","state":"Zala"}'>Zalaber</div>
<div class="option" data='{"value":"Zalabesenyo","state":"Zala"}'>Zalabesenyo</div>
<div class="option" data='{"value":"Zalaboldogfa","state":"Zala"}'>Zalaboldogfa</div>
<div class="option" data='{"value":"Zalacsany","state":"Zala"}'>Zalacsany</div>
<div class="option" data='{"value":"Zalacseb","state":"Zala"}'>Zalacseb</div>
<div class="option" data='{"value":"Zalaegerszeg","state":"Zala"}'>Zalaegerszeg</div>
<div class="option" data='{"value":"Zalahashagy","state":"Zala"}'>Zalahashagy</div>
<div class="option" data='{"value":"Zalahosszufalu","state":"Zala"}'>Zalahosszufalu</div>
<div class="option" data='{"value":"Zalaigrice","state":"Zala"}'>Zalaigrice</div>
<div class="option" data='{"value":"Zalaistvand","state":"Zala"}'>Zalaistvand</div>
<div class="option" data='{"value":"Zalakaros","state":"Zala"}'>Zalakaros</div>
<div class="option" data='{"value":"Zalakarosi Puszta","state":"Zala"}'>Zalakarosi Puszta</div>
<div class="option" data='{"value":"Zalakomar","state":"Zala"}'>Zalakomar</div>
<div class="option" data='{"value":"Zalakoppany","state":"Zala"}'>Zalakoppany</div>
<div class="option" data='{"value":"Zalakoszvenyes","state":"Zala"}'>Zalakoszvenyes</div>
<div class="option" data='{"value":"Zalakoveskut","state":"Zala"}'>Zalakoveskut</div>
<div class="option" data='{"value":"Zalalovo","state":"Zala"}'>Zalalovo</div>
<div class="option" data='{"value":"Zalalovoi Tanyak","state":"Zala"}'>Zalalovoi Tanyak</div>
<div class="option" data='{"value":"Zalamerenye","state":"Zala"}'>Zalamerenye</div>
<div class="option" data='{"value":"Zalanemetfalu","state":"Zala"}'>Zalanemetfalu</div>
<div class="option" data='{"value":"Zalasarszeg","state":"Zala"}'>Zalasarszeg</div>
<div class="option" data='{"value":"Zalaszabar","state":"Zala"}'>Zalaszabar</div>
<div class="option" data='{"value":"Zalaszanto","state":"Zala"}'>Zalaszanto</div>
<div class="option" data='{"value":"Zalaszentbalazs","state":"Zala"}'>Zalaszentbalazs</div>
<div class="option" data='{"value":"Zalaszentbalazsi Tanyak","state":"Zala"}'>Zalaszentbalazsi Tanyak</div>
<div class="option" data='{"value":"Zalaszentgrot","state":"Zala"}'>Zalaszentgrot</div>
<div class="option" data='{"value":"Zalaszentgroti Tanyak","state":"Zala"}'>Zalaszentgroti Tanyak</div>
<div class="option" data='{"value":"Zalaszentgyorgy","state":"Zala"}'>Zalaszentgyorgy</div>
<div class="option" data='{"value":"Zalaszentivan","state":"Zala"}'>Zalaszentivan</div>
<div class="option" data='{"value":"Zalaszentjakab","state":"Zala"}'>Zalaszentjakab</div>
<div class="option" data='{"value":"Zalaszentlaszlo","state":"Zala"}'>Zalaszentlaszlo</div>
<div class="option" data='{"value":"Zalaszentlorinc","state":"Zala"}'>Zalaszentlorinc</div>
<div class="option" data='{"value":"Zalaszentmarton","state":"Zala"}'>Zalaszentmarton</div>
<div class="option" data='{"value":"Zalaszentmihaly","state":"Zala"}'>Zalaszentmihaly</div>
<div class="option" data='{"value":"Zalaszentmihalyfa","state":"Zala"}'>Zalaszentmihalyfa</div>
<div class="option" data='{"value":"Zalaszombatfa","state":"Zala"}'>Zalaszombatfa</div>
<div class="option" data='{"value":"Zalatarnok","state":"Zala"}'>Zalatarnok</div>
<div class="option" data='{"value":"Zalaudvarnok","state":"Zala"}'>Zalaudvarnok</div>
<div class="option" data='{"value":"Zalaujlak","state":"Zala"}'>Zalaujlak</div>
<div class="option" data='{"value":"Zalavar","state":"Zala"}'>Zalavar</div>
<div class="option" data='{"value":"Zalaveg","state":"Zala"}'>Zalaveg</div>
<div class="option" data='{"value":"Zebecke","state":"Zala"}'>Zebecke</div>
<div class="option" data='{"value":"Zebeczke","state":"Zala"}'>Zebeczke</div>
<div class="option" data='{"value":"Zelpuszta","state":"Zala"}'>Zelpuszta</div>
<div class="option" data='{"value":"Zimanyitanya","state":"Zala"}'>Zimanyitanya</div>
<div class="option" data='{"value":"Zrinyimajor","state":"Zala"}'>Zrinyimajor</div>
<div class="option" data='{"value":"Zsigardimajor","state":"Zala"}'>Zsigardimajor</div>
<div class="option" data='{"value":"Zsigardmajor","state":"Zala"}'>Zsigardmajor</div>
<div class="option" data='{"value":"Zsigmondhaza","state":"Zala"}'>Zsigmondhaza</div>
<div class="option" data='{"value":"Zsofiahegy","state":"Zala"}'>Zsofiahegy</div>
<div class="option" id="option_end" data='{"value":"Zsuphegy","state":"Zala"}'>Zsuphegy</div>

