<div class="option" data='{"value":""}'>[ please select ]</div>
<div class="option" data='{"value":"Bacs-Kiskun"}'>Bacs-Kiskun</div>
<div class="option" data='{"value":"Baranya"}'>Baranya</div>
<div class="option" data='{"value":"Bekes"}'>Bekes</div>
<div class="option" data='{"value":"Bekescsaba"}'>Bekescsaba</div>
<div class="option" data='{"value":"Borsod-Abauj-Zemplen"}'>Borsod-Abauj-Zemplen</div>
<div class="option" data='{"value":"Budapest"}'>Budapest</div>
<div class="option" data='{"value":"Csongrad"}'>Csongrad</div>
<div class="option" data='{"value":"Debrecen"}'>Debrecen</div>
<div class="option" data='{"value":"Dunaujvaros"}'>Dunaujvaros</div>
<div class="option" data='{"value":"Eger"}'>Eger</div>
<div class="option" data='{"value":"Fejer"}'>Fejer</div>
<div class="option" data='{"value":"Gyor"}'>Gyor</div>
<div class="option" data='{"value":"Gyor-Moson-Sopron"}'>Gyor-Moson-Sopron</div>
<div class="option" data='{"value":"Hajdu-Bihar"}'>Hajdu-Bihar</div>
<div class="option" data='{"value":"Heves"}'>Heves</div>
<div class="option" data='{"value":"Hodmezovasarhely"}'>Hodmezovasarhely</div>
<div class="option" data='{"value":"Jasz-Nagykun-Szolnok"}'>Jasz-Nagykun-Szolnok</div>
<div class="option" data='{"value":"Kaposvar"}'>Kaposvar</div>
<div class="option" data='{"value":"Kecskemet"}'>Kecskemet</div>
<div class="option" data='{"value":"Komarom"}'>Komarom</div>
<div class="option" data='{"value":"Miskolc"}'>Miskolc</div>
<div class="option" data='{"value":"Nagykanizsa"}'>Nagykanizsa</div>
<div class="option" data='{"value":"Nograd"}'>Nograd</div>
<div class="option" data='{"value":"Nyiregyhaza"}'>Nyiregyhaza</div>
<div class="option" data='{"value":"Pecs"}'>Pecs</div>
<div class="option" data='{"value":"Pest"}'>Pest</div>
<div class="option" data='{"value":"Somogy"}'>Somogy</div>
<div class="option" data='{"value":"Sopron"}'>Sopron</div>
<div class="option" data='{"value":"Szabolcs-Szatmar-Bereg"}'>Szabolcs-Szatmar-Bereg</div>
<div class="option" data='{"value":"Szeged"}'>Szeged</div>
<div class="option" data='{"value":"Szekesfehervar"}'>Szekesfehervar</div>
<div class="option" data='{"value":"Szolnok Megyei Varos"}'>Szolnok Megyei Varos</div>
<div class="option" data='{"value":"Szombathely"}'>Szombathely</div>
<div class="option" data='{"value":"Tatabanya"}'>Tatabanya</div>
<div class="option" data='{"value":"Tolna"}'>Tolna</div>
<div class="option" data='{"value":"Vas"}'>Vas</div>
<div class="option" data='{"value":"Veszprem"}'>Veszprem</div>
<div class="option" data='{"value":"Zala"}'>Zala</div>
<div id="option_end" class="option" data='{"value":"Zalaegerszeg"}'>Zalaegerszeg</div>