<div class="option" data='{"value":"Albertakna","state":"Nograd"}'>Albertakna</div>
<div class="option" data='{"value":"Almaskuttanya","state":"Nograd"}'>Almaskuttanya</div>
<div class="option" data='{"value":"Almaspuszta","state":"Nograd"}'>Almaspuszta</div>
<div class="option" data='{"value":"Almastanya","state":"Nograd"}'>Almastanya</div>
<div class="option" data='{"value":"Almavolgypuszta","state":"Nograd"}'>Almavolgypuszta</div>
<div class="option" data='{"value":"Alsoegrespuszta","state":"Nograd"}'>Alsoegrespuszta</div>
<div class="option" data='{"value":"Alsohuta","state":"Nograd"}'>Alsohuta</div>
<div class="option" data='{"value":"Alsoivanpuszta","state":"Nograd"}'>Alsoivanpuszta</div>
<div class="option" data='{"value":"Alsolengyend","state":"Nograd"}'>Alsolengyend</div>
<div class="option" data='{"value":"Alsomajor","state":"Nograd"}'>Alsomajor</div>
<div class="option" data='{"value":"Alsomalomtelep","state":"Nograd"}'>Alsomalomtelep</div>
<div class="option" data='{"value":"Alsonadasd","state":"Nograd"}'>Alsonadasd</div>
<div class="option" data='{"value":"Alsopeteny","state":"Nograd"}'>Alsopeteny</div>
<div class="option" data='{"value":"Alsosarlospuszta","state":"Nograd"}'>Alsosarlospuszta</div>
<div class="option" data='{"value":"Alsoszanaspuszta","state":"Nograd"}'>Alsoszanaspuszta</div>
<div class="option" data='{"value":"Alsotabpuszta","state":"Nograd"}'>Alsotabpuszta</div>
<div class="option" data='{"value":"Alsotold","state":"Nograd"}'>Alsotold</div>
<div class="option" data='{"value":"Alsoutaspuszta","state":"Nograd"}'>Alsoutaspuszta</div>
<div class="option" data='{"value":"Alsozsukma","state":"Nograd"}'>Alsozsukma</div>
<div class="option" data='{"value":"Alsozsunypuszta","state":"Nograd"}'>Alsozsunypuszta</div>
<div class="option" data='{"value":"Amaliatelep","state":"Nograd"}'>Amaliatelep</div>
<div class="option" data='{"value":"Apacapuszta","state":"Nograd"}'>Apacapuszta</div>
<div class="option" data='{"value":"Apatipuszta","state":"Nograd"}'>Apatipuszta</div>
<div class="option" data='{"value":"Aranyosipuszta","state":"Nograd"}'>Aranyosipuszta</div>
<div class="option" data='{"value":"Aranyospuszta","state":"Nograd"}'>Aranyospuszta</div>
<div class="option" data='{"value":"Arnyekvolgypuszta","state":"Nograd"}'>Arnyekvolgypuszta</div>
<div class="option" data='{"value":"Augusztatelep","state":"Nograd"}'>Augusztatelep</div>
<div class="option" data='{"value":"Babat","state":"Nograd"}'>Babat</div>
<div class="option" data='{"value":"Baglyasalja","state":"Nograd"}'>Baglyasalja</div>
<div class="option" data='{"value":"Baglyaspuszta","state":"Nograd"}'>Baglyaspuszta</div>
<div class="option" data='{"value":"Bakopuszta","state":"Nograd"}'>Bakopuszta</div>
<div class="option" data='{"value":"Bakospuszta","state":"Nograd"}'>Bakospuszta</div>
<div class="option" data='{"value":"Baksahaza","state":"Nograd"}'>Baksahaza</div>
<div class="option" data='{"value":"Balassagyarmat","state":"Nograd"}'>Balassagyarmat</div>
<div class="option" data='{"value":"Balazstanya","state":"Nograd"}'>Balazstanya</div>
<div class="option" data='{"value":"Banfele Tanya","state":"Nograd"}'>Banfele Tanya</div>
<div class="option" data='{"value":"Bank","state":"Nograd"}'>Bank</div>
<div class="option" data='{"value":"Banyapuszta","state":"Nograd"}'>Banyapuszta</div>
<div class="option" data='{"value":"Banyatelep","state":"Nograd"}'>Banyatelep</div>
<div class="option" data='{"value":"Baratonypuszta","state":"Nograd"}'>Baratonypuszta</div>
<div class="option" data='{"value":"Barkanyitanya","state":"Nograd"}'>Barkanyitanya</div>
<div class="option" data='{"value":"Barna","state":"Nograd"}'>Barna</div>
<div class="option" data='{"value":"Baroktanya","state":"Nograd"}'>Baroktanya</div>
<div class="option" data='{"value":"Batkapuszta","state":"Nograd"}'>Batkapuszta</div>
<div class="option" data='{"value":"Batonyterenye","state":"Nograd"}'>Batonyterenye</div>
<div class="option" data='{"value":"Becske","state":"Nograd"}'>Becske</div>
<div class="option" data='{"value":"Bedabanya","state":"Nograd"}'>Bedabanya</div>
<div class="option" data='{"value":"Bedepuszta","state":"Nograd"}'>Bedepuszta</div>
<div class="option" data='{"value":"Belahalompuszta","state":"Nograd"}'>Belahalompuszta</div>
<div class="option" data='{"value":"Bencurfalva","state":"Nograd"}'>Bencurfalva</div>
<div class="option" data='{"value":"Benczurfalva","state":"Nograd"}'>Benczurfalva</div>
<div class="option" data='{"value":"Ber","state":"Nograd"}'>Ber</div>
<div class="option" data='{"value":"Bercel","state":"Nograd"}'>Bercel</div>
<div class="option" data='{"value":"Beretvaspuszta","state":"Nograd"}'>Beretvaspuszta</div>
<div class="option" data='{"value":"Berezina","state":"Nograd"}'>Berezina</div>
<div class="option" data='{"value":"Berkenye","state":"Nograd"}'>Berkenye</div>
<div class="option" data='{"value":"Berzaktanya","state":"Nograd"}'>Berzaktanya</div>
<div class="option" data='{"value":"Bezmagodre","state":"Nograd"}'>Bezmagodre</div>
<div class="option" data='{"value":"Bezmalapja","state":"Nograd"}'>Bezmalapja</div>
<div class="option" data='{"value":"Bikavaripuszta","state":"Nograd"}'>Bikavaripuszta</div>
<div class="option" data='{"value":"Bikkpuszta","state":"Nograd"}'>Bikkpuszta</div>
<div class="option" data='{"value":"Bikkvolgy","state":"Nograd"}'>Bikkvolgy</div>
<div class="option" data='{"value":"Bobonyerpuszta","state":"Nograd"}'>Bobonyerpuszta</div>
<div class="option" data='{"value":"Bochidjapuszta","state":"Nograd"}'>Bochidjapuszta</div>
<div class="option" data='{"value":"Bocsarlapujto","state":"Nograd"}'>Bocsarlapujto</div>
<div class="option" data='{"value":"Bodovolgy","state":"Nograd"}'>Bodovolgy</div>
<div class="option" data='{"value":"Boglyaspuszta","state":"Nograd"}'>Boglyaspuszta</div>
<div class="option" data='{"value":"Bokor","state":"Nograd"}'>Bokor</div>
<div class="option" data='{"value":"Bolyok","state":"Nograd"}'>Bolyok</div>
<div class="option" data='{"value":"Bolyokpuszta","state":"Nograd"}'>Bolyokpuszta</div>
<div class="option" data='{"value":"Borokaspuszta","state":"Nograd"}'>Borokaspuszta</div>
<div class="option" data='{"value":"Borsosbereny","state":"Nograd"}'>Borsosbereny</div>
<div class="option" data='{"value":"Brenzalja","state":"Nograd"}'>Brenzalja</div>
<div class="option" data='{"value":"Brenzaljatelep","state":"Nograd"}'>Brenzaljatelep</div>
<div class="option" data='{"value":"Budoskutpuszta","state":"Nograd"}'>Budoskutpuszta</div>
<div class="option" data='{"value":"Bugattanya","state":"Nograd"}'>Bugattanya</div>
<div class="option" data='{"value":"Buge","state":"Nograd"}'>Buge</div>
<div class="option" data='{"value":"Bugedulo","state":"Nograd"}'>Bugedulo</div>
<div class="option" data='{"value":"Bujak","state":"Nograd"}'>Bujak</div>
<div class="option" data='{"value":"Burospuszta","state":"Nograd"}'>Burospuszta</div>
<div class="option" data='{"value":"Cered","state":"Nograd"}'>Cered</div>
<div class="option" data='{"value":"Cerinapuszta","state":"Nograd"}'>Cerinapuszta</div>
<div class="option" data='{"value":"Ciframajor","state":"Nograd"}'>Ciframajor</div>
<div class="option" data='{"value":"Colhanypuszta","state":"Nograd"}'>Colhanypuszta</div>
<div class="option" data='{"value":"Csardapuszta","state":"Nograd"}'>Csardapuszta</div>
<div class="option" data='{"value":"Csecse","state":"Nograd"}'>Csecse</div>
<div class="option" data='{"value":"Csendespuszta","state":"Nograd"}'>Csendespuszta</div>
<div class="option" data='{"value":"Csengerhaza","state":"Nograd"}'>Csengerhaza</div>
<div class="option" data='{"value":"Cserbikkpuszta","state":"Nograd"}'>Cserbikkpuszta</div>
<div class="option" data='{"value":"Cserbikpuszta","state":"Nograd"}'>Cserbikpuszta</div>
<div class="option" data='{"value":"Cserespuszta","state":"Nograd"}'>Cserespuszta</div>
<div class="option" data='{"value":"Cserhathalap","state":"Nograd"}'>Cserhathalap</div>
<div class="option" data='{"value":"Cserhatpuszta","state":"Nograd"}'>Cserhatpuszta</div>
<div class="option" data='{"value":"Cserhatsurany","state":"Nograd"}'>Cserhatsurany</div>
<div class="option" data='{"value":"Cserhatszentivan","state":"Nograd"}'>Cserhatszentivan</div>
<div class="option" data='{"value":"Cserkutpuszta","state":"Nograd"}'>Cserkutpuszta</div>
<div class="option" data='{"value":"Cserkuttelep","state":"Nograd"}'>Cserkuttelep</div>
<div class="option" data='{"value":"Csernyikvolgy","state":"Nograd"}'>Csernyikvolgy</div>
<div class="option" data='{"value":"Cservolgypuszta","state":"Nograd"}'>Cservolgypuszta</div>
<div class="option" data='{"value":"Csesztve","state":"Nograd"}'>Csesztve</div>
<div class="option" data='{"value":"Csevice","state":"Nograd"}'>Csevice</div>
<div class="option" data='{"value":"Csevicekutpuszta","state":"Nograd"}'>Csevicekutpuszta</div>
<div class="option" data='{"value":"Csikorpuszta","state":"Nograd"}'>Csikorpuszta</div>
<div class="option" data='{"value":"Csitar","state":"Nograd"}'>Csitar</div>
<div class="option" data='{"value":"Csobankapuszta","state":"Nograd"}'>Csobankapuszta</div>
<div class="option" data='{"value":"Csokapuszta","state":"Nograd"}'>Csokapuszta</div>
<div class="option" data='{"value":"Csokasbanyatelep","state":"Nograd"}'>Csokasbanyatelep</div>
<div class="option" data='{"value":"Csomapuszta","state":"Nograd"}'>Csomapuszta</div>
<div class="option" data='{"value":"Csontfalu","state":"Nograd"}'>Csontfalu</div>
<div class="option" data='{"value":"Csorgopuszta","state":"Nograd"}'>Csorgopuszta</div>
<div class="option" data='{"value":"Csukorpuszta","state":"Nograd"}'>Csukorpuszta</div>
<div class="option" data='{"value":"Darasdo","state":"Nograd"}'>Darasdo</div>
<div class="option" data='{"value":"Darazsdopuszta","state":"Nograd"}'>Darazsdopuszta</div>
<div class="option" data='{"value":"Darazsikpuszta","state":"Nograd"}'>Darazsikpuszta</div>
<div class="option" data='{"value":"Debercseny","state":"Nograd"}'>Debercseny</div>
<div class="option" data='{"value":"Dejtar","state":"Nograd"}'>Dejtar</div>
<div class="option" data='{"value":"Delkutpuszta","state":"Nograd"}'>Delkutpuszta</div>
<div class="option" data='{"value":"Deszkaspuszta","state":"Nograd"}'>Deszkaspuszta</div>
<div class="option" data='{"value":"Dezsopuszta","state":"Nograd"}'>Dezsopuszta</div>
<div class="option" data='{"value":"Dezsotelep","state":"Nograd"}'>Dezsotelep</div>
<div class="option" data='{"value":"Dimitrovkispuszta","state":"Nograd"}'>Dimitrovkispuszta</div>
<div class="option" data='{"value":"Dimitrovpuszta","state":"Nograd"}'>Dimitrovpuszta</div>
<div class="option" data='{"value":"Diosjeno","state":"Nograd"}'>Diosjeno</div>
<div class="option" data='{"value":"Diospuszta","state":"Nograd"}'>Diospuszta</div>
<div class="option" data='{"value":"Dobospuszta","state":"Nograd"}'>Dobospuszta</div>
<div class="option" data='{"value":"Dohanyospuszta","state":"Nograd"}'>Dohanyospuszta</div>
<div class="option" data='{"value":"Dolinapuszta","state":"Nograd"}'>Dolinapuszta</div>
<div class="option" data='{"value":"Dolinkapuszta","state":"Nograd"}'>Dolinkapuszta</div>
<div class="option" data='{"value":"Doroghaza","state":"Nograd"}'>Doroghaza</div>
<div class="option" data='{"value":"Dorogpuszta","state":"Nograd"}'>Dorogpuszta</div>
<div class="option" data='{"value":"Dregelypalank","state":"Nograd"}'>Dregelypalank</div>
<div class="option" data='{"value":"Dugdelpuszta","state":"Nograd"}'>Dugdelpuszta</div>
<div class="option" data='{"value":"Ecseg","state":"Nograd"}'>Ecseg</div>
<div class="option" data='{"value":"Egyhazasdengeleg","state":"Nograd"}'>Egyhazasdengeleg</div>
<div class="option" data='{"value":"Egyhazasgerge","state":"Nograd"}'>Egyhazasgerge</div>
<div class="option" data='{"value":"Egyhazasgergei Tanya","state":"Nograd"}'>Egyhazasgergei Tanya</div>
<div class="option" data='{"value":"Endrefalva","state":"Nograd"}'>Endrefalva</div>
<div class="option" data='{"value":"Eperjesmajor","state":"Nograd"}'>Eperjesmajor</div>
<div class="option" data='{"value":"Epresmajor","state":"Nograd"}'>Epresmajor</div>
<div class="option" data='{"value":"Erdokurt","state":"Nograd"}'>Erdokurt</div>
<div class="option" data='{"value":"Erdotarcsa","state":"Nograd"}'>Erdotarcsa</div>
<div class="option" data='{"value":"Eresztveny","state":"Nograd"}'>Eresztveny</div>
<div class="option" data='{"value":"Eresztvenybanya","state":"Nograd"}'>Eresztvenybanya</div>
<div class="option" data='{"value":"Eresztvenycsorgo","state":"Nograd"}'>Eresztvenycsorgo</div>
<div class="option" data='{"value":"Ersekvadkert","state":"Nograd"}'>Ersekvadkert</div>
<div class="option" data='{"value":"Erzsebetpuszta","state":"Nograd"}'>Erzsebetpuszta</div>
<div class="option" data='{"value":"Etes","state":"Nograd"}'>Etes</div>
<div class="option" data='{"value":"Etesi Akna","state":"Nograd"}'>Etesi Akna</div>
<div class="option" data='{"value":"Evapuszta","state":"Nograd"}'>Evapuszta</div>
<div class="option" data='{"value":"Faluhely","state":"Nograd"}'>Faluhely</div>
<div class="option" data='{"value":"Farkasalmas","state":"Nograd"}'>Farkasalmas</div>
<div class="option" data='{"value":"Farkasberekpuszta","state":"Nograd"}'>Farkasberekpuszta</div>
<div class="option" data='{"value":"Farkasbukk","state":"Nograd"}'>Farkasbukk</div>
<div class="option" data='{"value":"Farkasvolgypuszta","state":"Nograd"}'>Farkasvolgypuszta</div>
<div class="option" data='{"value":"Farkasvolgytanya","state":"Nograd"}'>Farkasvolgytanya</div>
<div class="option" data='{"value":"Felsobikkvolgy","state":"Nograd"}'>Felsobikkvolgy</div>
<div class="option" data='{"value":"Felsoegrespuszta","state":"Nograd"}'>Felsoegrespuszta</div>
<div class="option" data='{"value":"Felsoivanpuszta","state":"Nograd"}'>Felsoivanpuszta</div>
<div class="option" data='{"value":"Felsolengyend","state":"Nograd"}'>Felsolengyend</div>
<div class="option" data='{"value":"Felsomajor","state":"Nograd"}'>Felsomajor</div>
<div class="option" data='{"value":"Felsonadasd","state":"Nograd"}'>Felsonadasd</div>
<div class="option" data='{"value":"Felsopeteny","state":"Nograd"}'>Felsopeteny</div>
<div class="option" data='{"value":"Felsoponyipuszta","state":"Nograd"}'>Felsoponyipuszta</div>
<div class="option" data='{"value":"Felsosarlospuszta","state":"Nograd"}'>Felsosarlospuszta</div>
<div class="option" data='{"value":"Felsotabpuszta","state":"Nograd"}'>Felsotabpuszta</div>
<div class="option" data='{"value":"Felsotold","state":"Nograd"}'>Felsotold</div>
<div class="option" data='{"value":"Felsoutaspuszta","state":"Nograd"}'>Felsoutaspuszta</div>
<div class="option" data='{"value":"Felsozsunypuszta","state":"Nograd"}'>Felsozsunypuszta</div>
<div class="option" data='{"value":"Fenykopuszta","state":"Nograd"}'>Fenykopuszta</div>
<div class="option" data='{"value":"Fenyves","state":"Nograd"}'>Fenyves</div>
<div class="option" data='{"value":"Fenyvespuszta","state":"Nograd"}'>Fenyvespuszta</div>
<div class="option" data='{"value":"Ferenckert","state":"Nograd"}'>Ferenckert</div>
<div class="option" data='{"value":"Filimes","state":"Nograd"}'>Filimes</div>
<div class="option" data='{"value":"Fityemajor","state":"Nograd"}'>Fityemajor</div>
<div class="option" data='{"value":"Fogacspuszta","state":"Nograd"}'>Fogacspuszta</div>
<div class="option" data='{"value":"Forraspuszta","state":"Nograd"}'>Forraspuszta</div>
<div class="option" data='{"value":"Franciapuszta","state":"Nograd"}'>Franciapuszta</div>
<div class="option" data='{"value":"Frigyes Akna","state":"Nograd"}'>Frigyes Akna</div>
<div class="option" data='{"value":"Fuleki Volgy","state":"Nograd"}'>Fuleki Volgy</div>
<div class="option" data='{"value":"Fulevolgytanya","state":"Nograd"}'>Fulevolgytanya</div>
<div class="option" data='{"value":"Fundusalja","state":"Nograd"}'>Fundusalja</div>
<div class="option" data='{"value":"Fuzespuszta","state":"Nograd"}'>Fuzespuszta</div>
<div class="option" data='{"value":"Galambospuszta","state":"Nograd"}'>Galambospuszta</div>
<div class="option" data='{"value":"Galambostelep","state":"Nograd"}'>Galambostelep</div>
<div class="option" data='{"value":"Galgaguta","state":"Nograd"}'>Galgaguta</div>
<div class="option" data='{"value":"Galibapuszta","state":"Nograd"}'>Galibapuszta</div>
<div class="option" data='{"value":"Galmajor","state":"Nograd"}'>Galmajor</div>
<div class="option" data='{"value":"Garab","state":"Nograd"}'>Garab</div>
<div class="option" data='{"value":"Gecilapos","state":"Nograd"}'>Gecilapos</div>
<div class="option" data='{"value":"Gedoczpuszta","state":"Nograd"}'>Gedoczpuszta</div>
<div class="option" data='{"value":"Gemlaposdulo","state":"Nograd"}'>Gemlaposdulo</div>
<div class="option" data='{"value":"Gindeletanya","state":"Nograd"}'>Gindeletanya</div>
<div class="option" data='{"value":"Golyagaz","state":"Nograd"}'>Golyagaz</div>
<div class="option" data='{"value":"Gorocpuszta","state":"Nograd"}'>Gorocpuszta</div>
<div class="option" data='{"value":"Gurdzsalypuszta","state":"Nograd"}'>Gurdzsalypuszta</div>
<div class="option" data='{"value":"Gurzsalypuszta","state":"Nograd"}'>Gurzsalypuszta</div>
<div class="option" data='{"value":"Gusztavakna","state":"Nograd"}'>Gusztavakna</div>
<div class="option" data='{"value":"Gyaporvolgy","state":"Nograd"}'>Gyaporvolgy</div>
<div class="option" data='{"value":"Gyertyanospuszta","state":"Nograd"}'>Gyertyanospuszta</div>
<div class="option" data='{"value":"Gyulataro","state":"Nograd"}'>Gyulataro</div>
<div class="option" data='{"value":"Gyulatarolo","state":"Nograd"}'>Gyulatarolo</div>
<div class="option" data='{"value":"Hajduarokpuszta","state":"Nograd"}'>Hajduarokpuszta</div>
<div class="option" data='{"value":"Halasto","state":"Nograd"}'>Halasto</div>
<div class="option" data='{"value":"Hanzelytanya","state":"Nograd"}'>Hanzelytanya</div>
<div class="option" data='{"value":"Harasztipuszta","state":"Nograd"}'>Harasztipuszta</div>
<div class="option" data='{"value":"Harasztitanya","state":"Nograd"}'>Harasztitanya</div>
<div class="option" data='{"value":"Harmaskutpuszta","state":"Nograd"}'>Harmaskutpuszta</div>
<div class="option" data='{"value":"Harsvolgypuszta","state":"Nograd"}'>Harsvolgypuszta</div>
<div class="option" data='{"value":"Hasznos","state":"Nograd"}'>Hasznos</div>
<div class="option" data='{"value":"Havaspuszta","state":"Nograd"}'>Havaspuszta</div>
<div class="option" data='{"value":"Hegyesbukk","state":"Nograd"}'>Hegyesbukk</div>
<div class="option" data='{"value":"Hegyipuszta","state":"Nograd"}'>Hegyipuszta</div>
<div class="option" data='{"value":"Hegymegipuszta","state":"Nograd"}'>Hegymegipuszta</div>
<div class="option" data='{"value":"Hehalom","state":"Nograd"}'>Hehalom</div>
<div class="option" data='{"value":"Henyelpuszta","state":"Nograd"}'>Henyelpuszta</div>
<div class="option" data='{"value":"Herencseny","state":"Nograd"}'>Herencseny</div>
<div class="option" data='{"value":"Herminapuszta","state":"Nograd"}'>Herminapuszta</div>
<div class="option" data='{"value":"Holloko","state":"Nograd"}'>Holloko</div>
<div class="option" data='{"value":"Holyapuszta","state":"Nograd"}'>Holyapuszta</div>
<div class="option" data='{"value":"Homoki Szollo","state":"Nograd"}'>Homoki Szollo</div>
<div class="option" data='{"value":"Homokiszolok","state":"Nograd"}'>Homokiszolok</div>
<div class="option" data='{"value":"Homokterenye","state":"Nograd"}'>Homokterenye</div>
<div class="option" data='{"value":"Hont","state":"Nograd"}'>Hont</div>
<div class="option" data='{"value":"Honti Tanya","state":"Nograd"}'>Honti Tanya</div>
<div class="option" data='{"value":"Horpacs","state":"Nograd"}'>Horpacs</div>
<div class="option" data='{"value":"Horvathtanya","state":"Nograd"}'>Horvathtanya</div>
<div class="option" data='{"value":"Hosszuvolgypuszta","state":"Nograd"}'>Hosszuvolgypuszta</div>
<div class="option" data='{"value":"Hugyag","state":"Nograd"}'>Hugyag</div>
<div class="option" data='{"value":"Hutyantanya","state":"Nograd"}'>Hutyantanya</div>
<div class="option" data='{"value":"Iliny","state":"Nograd"}'>Iliny</div>
<div class="option" data='{"value":"Ilkamajor","state":"Nograd"}'>Ilkamajor</div>
<div class="option" data='{"value":"Ilonabanya","state":"Nograd"}'>Ilonabanya</div>
<div class="option" data='{"value":"Ilonamajor","state":"Nograd"}'>Ilonamajor</div>
<div class="option" data='{"value":"Ilonapuszta","state":"Nograd"}'>Ilonapuszta</div>
<div class="option" data='{"value":"Inaszobanya","state":"Nograd"}'>Inaszobanya</div>
<div class="option" data='{"value":"Inaszobanyatelep","state":"Nograd"}'>Inaszobanyatelep</div>
<div class="option" data='{"value":"Ipolyszog","state":"Nograd"}'>Ipolyszog</div>
<div class="option" data='{"value":"Ipolytarnoc","state":"Nograd"}'>Ipolytarnoc</div>
<div class="option" data='{"value":"Ipolyvece","state":"Nograd"}'>Ipolyvece</div>
<div class="option" data='{"value":"Irtvanypuszta","state":"Nograd"}'>Irtvanypuszta</div>
<div class="option" data='{"value":"Istvanpuszta","state":"Nograd"}'>Istvanpuszta</div>
<div class="option" data='{"value":"Ivanpuszta","state":"Nograd"}'>Ivanpuszta</div>
<div class="option" data='{"value":"Ivantagpuszta","state":"Nograd"}'>Ivantagpuszta</div>
<div class="option" data='{"value":"Ivanypuszta","state":"Nograd"}'>Ivanypuszta</div>
<div class="option" data='{"value":"Jakotpuszta","state":"Nograd"}'>Jakotpuszta</div>
<div class="option" data='{"value":"Janosaknai Barakhaz","state":"Nograd"}'>Janosaknai Barakhaz</div>
<div class="option" data='{"value":"Jasztelek","state":"Nograd"}'>Jasztelek</div>
<div class="option" data='{"value":"Jasztelekpuszta","state":"Nograd"}'>Jasztelekpuszta</div>
<div class="option" data='{"value":"Jegrestanya","state":"Nograd"}'>Jegrestanya</div>
<div class="option" data='{"value":"Jobbagyi","state":"Nograd"}'>Jobbagyi</div>
<div class="option" data='{"value":"Juhasztanya","state":"Nograd"}'>Juhasztanya</div>
<div class="option" data='{"value":"Kacsastopuszta","state":"Nograd"}'>Kacsastopuszta</div>
<div class="option" data='{"value":"Kaldymajor","state":"Nograd"}'>Kaldymajor</div>
<div class="option" data='{"value":"Kaldytanya","state":"Nograd"}'>Kaldytanya</div>
<div class="option" data='{"value":"Kallo","state":"Nograd"}'>Kallo</div>
<div class="option" data='{"value":"Kamor","state":"Nograd"}'>Kamor</div>
<div class="option" data='{"value":"Kamori Also","state":"Nograd"}'>Kamori Also</div>
<div class="option" data='{"value":"Kanyaspuszta","state":"Nograd"}'>Kanyaspuszta</div>
<div class="option" data='{"value":"Kaparopuszta","state":"Nograd"}'>Kaparopuszta</div>
<div class="option" data='{"value":"Kapaskut","state":"Nograd"}'>Kapaskut</div>
<div class="option" data='{"value":"Kapaskutpuszta","state":"Nograd"}'>Kapaskutpuszta</div>
<div class="option" data='{"value":"Kaposztaspuszta","state":"Nograd"}'>Kaposztaspuszta</div>
<div class="option" data='{"value":"Kapraspuszta","state":"Nograd"}'>Kapraspuszta</div>
<div class="option" data='{"value":"Karancapatfalva","state":"Nograd"}'>Karancapatfalva</div>
<div class="option" data='{"value":"Karancsalja","state":"Nograd"}'>Karancsalja</div>
<div class="option" data='{"value":"Karancsbereny","state":"Nograd"}'>Karancsbereny</div>
<div class="option" data='{"value":"Karancshegy","state":"Nograd"}'>Karancshegy</div>
<div class="option" data='{"value":"Karancskeszi","state":"Nograd"}'>Karancskeszi</div>
<div class="option" data='{"value":"Karancslapujto","state":"Nograd"}'>Karancslapujto</div>
<div class="option" data='{"value":"Karancssag","state":"Nograd"}'>Karancssag</div>
<div class="option" data='{"value":"Karolyakna","state":"Nograd"}'>Karolyakna</div>
<div class="option" data='{"value":"Karpegec","state":"Nograd"}'>Karpegec</div>
<div class="option" data='{"value":"Katalinpuszta","state":"Nograd"}'>Katalinpuszta</div>
<div class="option" data='{"value":"Katalintelep","state":"Nograd"}'>Katalintelep</div>
<div class="option" data='{"value":"Kavicsbanya","state":"Nograd"}'>Kavicsbanya</div>
<div class="option" data='{"value":"Kavicsos","state":"Nograd"}'>Kavicsos</div>
<div class="option" data='{"value":"Kazar","state":"Nograd"}'>Kazar</div>
<div class="option" data='{"value":"Kecskedpuszta","state":"Nograd"}'>Kecskedpuszta</div>
<div class="option" data='{"value":"Kelecsenypuszta","state":"Nograd"}'>Kelecsenypuszta</div>
<div class="option" data='{"value":"Kerekagpuszta","state":"Nograd"}'>Kerekagpuszta</div>
<div class="option" data='{"value":"Keresztipuszta","state":"Nograd"}'>Keresztipuszta</div>
<div class="option" data='{"value":"Keresztvolgypuszta","state":"Nograd"}'>Keresztvolgypuszta</div>
<div class="option" data='{"value":"Keselyret","state":"Nograd"}'>Keselyret</div>
<div class="option" data='{"value":"Keselyretpuszta","state":"Nograd"}'>Keselyretpuszta</div>
<div class="option" data='{"value":"Keszeg","state":"Nograd"}'>Keszeg</div>
<div class="option" data='{"value":"Ketbodony","state":"Nograd"}'>Ketbodony</div>
<div class="option" data='{"value":"Kijaropuszta","state":"Nograd"}'>Kijaropuszta</div>
<div class="option" data='{"value":"Kincsempuszta","state":"Nograd"}'>Kincsempuszta</div>
<div class="option" data='{"value":"Kincsemtelep","state":"Nograd"}'>Kincsemtelep</div>
<div class="option" data='{"value":"Kincsespuszta","state":"Nograd"}'>Kincsespuszta</div>
<div class="option" data='{"value":"Kisaranyi","state":"Nograd"}'>Kisaranyi</div>
<div class="option" data='{"value":"Kisbagyon","state":"Nograd"}'>Kisbagyon</div>
<div class="option" data='{"value":"Kisbaksahaza","state":"Nograd"}'>Kisbaksahaza</div>
<div class="option" data='{"value":"Kisbarkany","state":"Nograd"}'>Kisbarkany</div>
<div class="option" data='{"value":"Kisbatony","state":"Nograd"}'>Kisbatony</div>
<div class="option" data='{"value":"Kisecset","state":"Nograd"}'>Kisecset</div>
<div class="option" data='{"value":"Kisfalud","state":"Nograd"}'>Kisfalud</div>
<div class="option" data='{"value":"Kisfaludpuszta","state":"Nograd"}'>Kisfaludpuszta</div>
<div class="option" data='{"value":"Kisgec","state":"Nograd"}'>Kisgec</div>
<div class="option" data='{"value":"Kishartyan","state":"Nograd"}'>Kishartyan</div>
<div class="option" data='{"value":"Kishegy","state":"Nograd"}'>Kishegy</div>
<div class="option" data='{"value":"Kiskeresztur","state":"Nograd"}'>Kiskeresztur</div>
<div class="option" data='{"value":"Kiskerpuszta","state":"Nograd"}'>Kiskerpuszta</div>
<div class="option" data='{"value":"Kismedves","state":"Nograd"}'>Kismedves</div>
<div class="option" data='{"value":"Kispuszta","state":"Nograd"}'>Kispuszta</div>
<div class="option" data='{"value":"Kisretpuszta","state":"Nograd"}'>Kisretpuszta</div>
<div class="option" data='{"value":"Kistanya","state":"Nograd"}'>Kistanya</div>
<div class="option" data='{"value":"Kisterenye","state":"Nograd"}'>Kisterenye</div>
<div class="option" data='{"value":"Kisuzsapuszta","state":"Nograd"}'>Kisuzsapuszta</div>
<div class="option" data='{"value":"Klatyiktanya","state":"Nograd"}'>Klatyiktanya</div>
<div class="option" data='{"value":"Kobanyatelep","state":"Nograd"}'>Kobanyatelep</div>
<div class="option" data='{"value":"Kohegyalja","state":"Nograd"}'>Kohegyalja</div>
<div class="option" data='{"value":"Kohegyaljapuszta","state":"Nograd"}'>Kohegyaljapuszta</div>
<div class="option" data='{"value":"Kokavicstanya","state":"Nograd"}'>Kokavicstanya</div>
<div class="option" data='{"value":"Kokenyes","state":"Nograd"}'>Kokenyes</div>
<div class="option" data='{"value":"Kokenyespuszta","state":"Nograd"}'>Kokenyespuszta</div>
<div class="option" data='{"value":"Kokutpuszta","state":"Nograd"}'>Kokutpuszta</div>
<div class="option" data='{"value":"Kolapapuszta","state":"Nograd"}'>Kolapapuszta</div>
<div class="option" data='{"value":"Komaj","state":"Nograd"}'>Komaj</div>
<div class="option" data='{"value":"Koplalo","state":"Nograd"}'>Koplalo</div>
<div class="option" data='{"value":"Koplalotanya","state":"Nograd"}'>Koplalotanya</div>
<div class="option" data='{"value":"Korbasstanya","state":"Nograd"}'>Korbasstanya</div>
<div class="option" data='{"value":"Kormoshazipuszta","state":"Nograd"}'>Kormoshazipuszta</div>
<div class="option" data='{"value":"Kormospuszta","state":"Nograd"}'>Kormospuszta</div>
<div class="option" data='{"value":"Kosiktanya","state":"Nograd"}'>Kosiktanya</div>
<div class="option" data='{"value":"Koszoru","state":"Nograd"}'>Koszoru</div>
<div class="option" data='{"value":"Koszorupuszta","state":"Nograd"}'>Koszorupuszta</div>
<div class="option" data='{"value":"Koszorutanya","state":"Nograd"}'>Koszorutanya</div>
<div class="option" data='{"value":"Kotrocopuszta","state":"Nograd"}'>Kotrocopuszta</div>
<div class="option" data='{"value":"Kotyhaza","state":"Nograd"}'>Kotyhaza</div>
<div class="option" data='{"value":"Kotyhazatelep","state":"Nograd"}'>Kotyhazatelep</div>
<div class="option" data='{"value":"Kovacspuszta","state":"Nograd"}'>Kovacspuszta</div>
<div class="option" data='{"value":"Kovaralja","state":"Nograd"}'>Kovaralja</div>
<div class="option" data='{"value":"Kozard","state":"Nograd"}'>Kozard</div>
<div class="option" data='{"value":"Krakko","state":"Nograd"}'>Krakko</div>
<div class="option" data='{"value":"Krakkopuszta","state":"Nograd"}'>Krakkopuszta</div>
<div class="option" data='{"value":"Krivachypuszta","state":"Nograd"}'>Krivachypuszta</div>
<div class="option" data='{"value":"Kutagapuszta","state":"Nograd"}'>Kutagapuszta</div>
<div class="option" data='{"value":"Kutaso","state":"Nograd"}'>Kutaso</div>
<div class="option" data='{"value":"Lajosmajor","state":"Nograd"}'>Lajosmajor</div>
<div class="option" data='{"value":"Lajostanya","state":"Nograd"}'>Lajostanya</div>
<div class="option" data='{"value":"Lapasdpuszta","state":"Nograd"}'>Lapasdpuszta</div>
<div class="option" data='{"value":"Laszlotanya","state":"Nograd"}'>Laszlotanya</div>
<div class="option" data='{"value":"Laszlovolgy","state":"Nograd"}'>Laszlovolgy</div>
<div class="option" data='{"value":"Laszlovolgypuszta","state":"Nograd"}'>Laszlovolgypuszta</div>
<div class="option" data='{"value":"Lazonyapuszta","state":"Nograd"}'>Lazonyapuszta</div>
<div class="option" data='{"value":"Legend","state":"Nograd"}'>Legend</div>
<div class="option" data='{"value":"Litke","state":"Nograd"}'>Litke</div>
<div class="option" data='{"value":"Lokostelep","state":"Nograd"}'>Lokostelep</div>
<div class="option" data='{"value":"Loszegpuszta","state":"Nograd"}'>Loszegpuszta</div>
<div class="option" data='{"value":"Lucfalva","state":"Nograd"}'>Lucfalva</div>
<div class="option" data='{"value":"Lucskapuszta","state":"Nograd"}'>Lucskapuszta</div>
<div class="option" data='{"value":"Ludany","state":"Nograd"}'>Ludany</div>
<div class="option" data='{"value":"Ludanyhalaszi","state":"Nograd"}'>Ludanyhalaszi</div>
<div class="option" data='{"value":"Lyukvolgy","state":"Nograd"}'>Lyukvolgy</div>
<div class="option" data='{"value":"Lyukvolgypuszta","state":"Nograd"}'>Lyukvolgypuszta</div>
<div class="option" data='{"value":"Maconka","state":"Nograd"}'>Maconka</div>
<div class="option" data='{"value":"Madachtanya","state":"Nograd"}'>Madachtanya</div>
<div class="option" data='{"value":"Madachtelep","state":"Nograd"}'>Madachtelep</div>
<div class="option" data='{"value":"Magyargec","state":"Nograd"}'>Magyargec</div>
<div class="option" data='{"value":"Magyarnandor","state":"Nograd"}'>Magyarnandor</div>
<div class="option" data='{"value":"Mailathgardony","state":"Nograd"}'>Mailathgardony</div>
<div class="option" data='{"value":"Makopuszta","state":"Nograd"}'>Makopuszta</div>
<div class="option" data='{"value":"Malmostelep","state":"Nograd"}'>Malmostelep</div>
<div class="option" data='{"value":"Marakodipuszta","state":"Nograd"}'>Marakodipuszta</div>
<div class="option" data='{"value":"Mariamajor","state":"Nograd"}'>Mariamajor</div>
<div class="option" data='{"value":"Mariatanya","state":"Nograd"}'>Mariatanya</div>
<div class="option" data='{"value":"Markhaza","state":"Nograd"}'>Markhaza</div>
<div class="option" data='{"value":"Markhazapuszta","state":"Nograd"}'>Markhazapuszta</div>
<div class="option" data='{"value":"Martamajor","state":"Nograd"}'>Martamajor</div>
<div class="option" data='{"value":"Martonkutpuszta","state":"Nograd"}'>Martonkutpuszta</div>
<div class="option" data='{"value":"Mateulespuszta","state":"Nograd"}'>Mateulespuszta</div>
<div class="option" data='{"value":"Mateulestanya","state":"Nograd"}'>Mateulestanya</div>
<div class="option" data='{"value":"Matracser","state":"Nograd"}'>Matracser</div>
<div class="option" data='{"value":"Matracserpuszta","state":"Nograd"}'>Matracserpuszta</div>
<div class="option" data='{"value":"Matrakeresztes","state":"Nograd"}'>Matrakeresztes</div>
<div class="option" data='{"value":"Matramindszent","state":"Nograd"}'>Matramindszent</div>
<div class="option" data='{"value":"Matranovak","state":"Nograd"}'>Matranovak</div>
<div class="option" data='{"value":"Matraszele","state":"Nograd"}'>Matraszele</div>
<div class="option" data='{"value":"Matraszollos","state":"Nograd"}'>Matraszollos</div>
<div class="option" data='{"value":"Matraszolos","state":"Nograd"}'>Matraszolos</div>
<div class="option" data='{"value":"Matraterenye","state":"Nograd"}'>Matraterenye</div>
<div class="option" data='{"value":"Matraverebely","state":"Nograd"}'>Matraverebely</div>
<div class="option" data='{"value":"Medimajor","state":"Nograd"}'>Medimajor</div>
<div class="option" data='{"value":"Medvespuszta","state":"Nograd"}'>Medvespuszta</div>
<div class="option" data='{"value":"Meszpesttanya","state":"Nograd"}'>Meszpesttanya</div>
<div class="option" data='{"value":"Mihalygerge","state":"Nograd"}'>Mihalygerge</div>
<div class="option" data='{"value":"Miklosvolgy","state":"Nograd"}'>Miklosvolgy</div>
<div class="option" data='{"value":"Miklosvolgytelep","state":"Nograd"}'>Miklosvolgytelep</div>
<div class="option" data='{"value":"Mikovolgy","state":"Nograd"}'>Mikovolgy</div>
<div class="option" data='{"value":"Minalygerge","state":"Nograd"}'>Minalygerge</div>
<div class="option" data='{"value":"Mizserfabanya","state":"Nograd"}'>Mizserfabanya</div>
<div class="option" data='{"value":"Mocsarospuszta","state":"Nograd"}'>Mocsarospuszta</div>
<div class="option" data='{"value":"Mocsarostanya","state":"Nograd"}'>Mocsarostanya</div>
<div class="option" data='{"value":"Mocsolyavolgypuszta","state":"Nograd"}'>Mocsolyavolgypuszta</div>
<div class="option" data='{"value":"Mogyoroska","state":"Nograd"}'>Mogyoroska</div>
<div class="option" data='{"value":"Mohora","state":"Nograd"}'>Mohora</div>
<div class="option" data='{"value":"Morgospuszta","state":"Nograd"}'>Morgospuszta</div>
<div class="option" data='{"value":"Muzslapuszta","state":"Nograd"}'>Muzslapuszta</div>
<div class="option" data='{"value":"Nadastelep","state":"Nograd"}'>Nadastelep</div>
<div class="option" data='{"value":"Nadujfalu","state":"Nograd"}'>Nadujfalu</div>
<div class="option" data='{"value":"Nagyaranyi","state":"Nograd"}'>Nagyaranyi</div>
<div class="option" data='{"value":"Nagyaranypuszta","state":"Nograd"}'>Nagyaranypuszta</div>
<div class="option" data='{"value":"Nagybarkany","state":"Nograd"}'>Nagybarkany</div>
<div class="option" data='{"value":"Nagybatony","state":"Nograd"}'>Nagybatony</div>
<div class="option" data='{"value":"Nagykeresztur","state":"Nograd"}'>Nagykeresztur</div>
<div class="option" data='{"value":"Nagyloc","state":"Nograd"}'>Nagyloc</div>
<div class="option" data='{"value":"Nagymezo","state":"Nograd"}'>Nagymezo</div>
<div class="option" data='{"value":"Nagymezopuszta","state":"Nograd"}'>Nagymezopuszta</div>
<div class="option" data='{"value":"Nagyoldalpuszta","state":"Nograd"}'>Nagyoldalpuszta</div>
<div class="option" data='{"value":"Nagyoroszi","state":"Nograd"}'>Nagyoroszi</div>
<div class="option" data='{"value":"Nagyponyipuszta","state":"Nograd"}'>Nagyponyipuszta</div>
<div class="option" data='{"value":"Nagyretdulo","state":"Nograd"}'>Nagyretdulo</div>
<div class="option" data='{"value":"Nagyrot","state":"Nograd"}'>Nagyrot</div>
<div class="option" data='{"value":"Nagyszollo","state":"Nograd"}'>Nagyszollo</div>
<div class="option" data='{"value":"Nagyuzsapuszta","state":"Nograd"}'>Nagyuzsapuszta</div>
<div class="option" data='{"value":"Nagyvolgypuszta","state":"Nograd"}'>Nagyvolgypuszta</div>
<div class="option" data='{"value":"Nagyvolgytanya","state":"Nograd"}'>Nagyvolgytanya</div>
<div class="option" data='{"value":"Nelasd","state":"Nograd"}'>Nelasd</div>
<div class="option" data='{"value":"Nelasdpuszta","state":"Nograd"}'>Nelasdpuszta</div>
<div class="option" data='{"value":"Nemestanya","state":"Nograd"}'>Nemestanya</div>
<div class="option" data='{"value":"Nemti","state":"Nograd"}'>Nemti</div>
<div class="option" data='{"value":"Nemtipuszta","state":"Nograd"}'>Nemtipuszta</div>
<div class="option" data='{"value":"Nezsa","state":"Nograd"}'>Nezsa</div>
<div class="option" data='{"value":"Nograd","state":"Nograd"}'>Nograd</div>
<div class="option" data='{"value":"Nograd County","state":"Nograd"}'>Nograd County</div>
<div class="option" data='{"value":"Nograd Megye","state":"Nograd"}'>Nograd Megye</div>
<div class="option" data='{"value":"Nogradgardony","state":"Nograd"}'>Nogradgardony</div>
<div class="option" data='{"value":"Nogradkovesd","state":"Nograd"}'>Nogradkovesd</div>
<div class="option" data='{"value":"Nogradmarcal","state":"Nograd"}'>Nogradmarcal</div>
<div class="option" data='{"value":"Nogradmegyer","state":"Nograd"}'>Nogradmegyer</div>
<div class="option" data='{"value":"Nogradsap","state":"Nograd"}'>Nogradsap</div>
<div class="option" data='{"value":"Nogradsipek","state":"Nograd"}'>Nogradsipek</div>
<div class="option" data='{"value":"Nogradszakal","state":"Nograd"}'>Nogradszakal</div>
<div class="option" data='{"value":"Notincs","state":"Nograd"}'>Notincs</div>
<div class="option" data='{"value":"Nyarjasvolgy","state":"Nograd"}'>Nyarjasvolgy</div>
<div class="option" data='{"value":"Nyergespuszta","state":"Nograd"}'>Nyergespuszta</div>
<div class="option" data='{"value":"Nyiresmajor","state":"Nograd"}'>Nyiresmajor</div>
<div class="option" data='{"value":"Nyirjes","state":"Nograd"}'>Nyirjes</div>
<div class="option" data='{"value":"Nyirjespuszta","state":"Nograd"}'>Nyirjespuszta</div>
<div class="option" data='{"value":"Nyirmedpuszta","state":"Nograd"}'>Nyirmedpuszta</div>
<div class="option" data='{"value":"Nyirmegyipuszta","state":"Nograd"}'>Nyirmegyipuszta</div>
<div class="option" data='{"value":"Ordaspuszta","state":"Nograd"}'>Ordaspuszta</div>
<div class="option" data='{"value":"Oreghegyi Szollok","state":"Nograd"}'>Oreghegyi Szollok</div>
<div class="option" data='{"value":"Oreghegypuszta","state":"Nograd"}'>Oreghegypuszta</div>
<div class="option" data='{"value":"Orhalom","state":"Nograd"}'>Orhalom</div>
<div class="option" data='{"value":"Osagard","state":"Nograd"}'>Osagard</div>
<div class="option" data='{"value":"Pajtapuszta","state":"Nograd"}'>Pajtapuszta</div>
<div class="option" data='{"value":"Paksypuszta","state":"Nograd"}'>Paksypuszta</div>
<div class="option" data='{"value":"Palhaza","state":"Nograd"}'>Palhaza</div>
<div class="option" data='{"value":"Palhazapuszta","state":"Nograd"}'>Palhazapuszta</div>
<div class="option" data='{"value":"Palhazipuszta","state":"Nograd"}'>Palhazipuszta</div>
<div class="option" data='{"value":"Pallagpuszta","state":"Nograd"}'>Pallagpuszta</div>
<div class="option" data='{"value":"Palmajor","state":"Nograd"}'>Palmajor</div>
<div class="option" data='{"value":"Palotas","state":"Nograd"}'>Palotas</div>
<div class="option" data='{"value":"Palotashalom","state":"Nograd"}'>Palotashalom</div>
<div class="option" data='{"value":"Paltelek","state":"Nograd"}'>Paltelek</div>
<div class="option" data='{"value":"Papret","state":"Nograd"}'>Papret</div>
<div class="option" data='{"value":"Parassapuszta","state":"Nograd"}'>Parassapuszta</div>
<div class="option" data='{"value":"Parraghpuszta","state":"Nograd"}'>Parraghpuszta</div>
<div class="option" data='{"value":"Parragpuszta","state":"Nograd"}'>Parragpuszta</div>
<div class="option" data='{"value":"Paszto","state":"Nograd"}'>Paszto</div>
<div class="option" data='{"value":"Patak","state":"Nograd"}'>Patak</div>
<div class="option" data='{"value":"Patkanyospuszta","state":"Nograd"}'>Patkanyospuszta</div>
<div class="option" data='{"value":"Patvarc","state":"Nograd"}'>Patvarc</div>
<div class="option" data='{"value":"Pecskopuszta","state":"Nograd"}'>Pecskopuszta</div>
<div class="option" data='{"value":"Perespuszta","state":"Nograd"}'>Perespuszta</div>
<div class="option" data='{"value":"Piliny","state":"Nograd"}'>Piliny</div>
<div class="option" data='{"value":"Piroskapuszta","state":"Nograd"}'>Piroskapuszta</div>
<div class="option" data='{"value":"Plachypuszta","state":"Nograd"}'>Plachypuszta</div>
<div class="option" data='{"value":"Poganyvar","state":"Nograd"}'>Poganyvar</div>
<div class="option" data='{"value":"Pogony","state":"Nograd"}'>Pogony</div>
<div class="option" data='{"value":"Ponyipuszta","state":"Nograd"}'>Ponyipuszta</div>
<div class="option" data='{"value":"Postenypuszta","state":"Nograd"}'>Postenypuszta</div>
<div class="option" data='{"value":"Pruvosznya","state":"Nograd"}'>Pruvosznya</div>
<div class="option" data='{"value":"Puspokmagyalos","state":"Nograd"}'>Puspokmagyalos</div>
<div class="option" data='{"value":"Pusztaalsoivan","state":"Nograd"}'>Pusztaalsoivan</div>
<div class="option" data='{"value":"Pusztaberki","state":"Nograd"}'>Pusztaberki</div>
<div class="option" data='{"value":"Pusztadulo","state":"Nograd"}'>Pusztadulo</div>
<div class="option" data='{"value":"Pusztafelsoivan","state":"Nograd"}'>Pusztafelsoivan</div>
<div class="option" data='{"value":"Pusztakisker","state":"Nograd"}'>Pusztakisker</div>
<div class="option" data='{"value":"Pusztamarkhaza","state":"Nograd"}'>Pusztamarkhaza</div>
<div class="option" data='{"value":"Pusztaszanto","state":"Nograd"}'>Pusztaszanto</div>
<div class="option" data='{"value":"Pusztatiribes","state":"Nograd"}'>Pusztatiribes</div>
<div class="option" data='{"value":"Ractanya","state":"Nograd"}'>Ractanya</div>
<div class="option" data='{"value":"Racztanya","state":"Nograd"}'>Racztanya</div>
<div class="option" data='{"value":"Rauakna","state":"Nograd"}'>Rauakna</div>
<div class="option" data='{"value":"Rautelep","state":"Nograd"}'>Rautelep</div>
<div class="option" data='{"value":"Ravaszlyuk","state":"Nograd"}'>Ravaszlyuk</div>
<div class="option" data='{"value":"Retsag","state":"Nograd"}'>Retsag</div>
<div class="option" data='{"value":"Rimoc","state":"Nograd"}'>Rimoc</div>
<div class="option" data='{"value":"Romhany","state":"Nograd"}'>Romhany</div>
<div class="option" data='{"value":"Ronabanya","state":"Nograd"}'>Ronabanya</div>
<div class="option" data='{"value":"Rozsadomb","state":"Nograd"}'>Rozsadomb</div>
<div class="option" data='{"value":"Rozsahegyi Puszta","state":"Nograd"}'>Rozsahegyi Puszta</div>
<div class="option" data='{"value":"Rozsahegyitanya","state":"Nograd"}'>Rozsahegyitanya</div>
<div class="option" data='{"value":"Rozsamajor","state":"Nograd"}'>Rozsamajor</div>
<div class="option" data='{"value":"Safartanya","state":"Nograd"}'>Safartanya</div>
<div class="option" data='{"value":"Sagujfalu","state":"Nograd"}'>Sagujfalu</div>
<div class="option" data='{"value":"Salgopuszta","state":"Nograd"}'>Salgopuszta</div>
<div class="option" data='{"value":"Salgotarjan","state":"Nograd"}'>Salgotarjan</div>
<div class="option" data='{"value":"Salgotarjani Szenbankyak","state":"Nograd"}'>Salgotarjani Szenbankyak</div>
<div class="option" data='{"value":"Salgotarjani Szenbanyak","state":"Nograd"}'>Salgotarjani Szenbanyak</div>
<div class="option" data='{"value":"Samsonhaza","state":"Nograd"}'>Samsonhaza</div>
<div class="option" data='{"value":"Sandormajor","state":"Nograd"}'>Sandormajor</div>
<div class="option" data='{"value":"Sandortanya","state":"Nograd"}'>Sandortanya</div>
<div class="option" data='{"value":"Sasbercpuszta","state":"Nograd"}'>Sasbercpuszta</div>
<div class="option" data='{"value":"Schwarcszollo","state":"Nograd"}'>Schwarcszollo</div>
<div class="option" data='{"value":"Sebesfapuszta","state":"Nograd"}'>Sebesfapuszta</div>
<div class="option" data='{"value":"Serestanya","state":"Nograd"}'>Serestanya</div>
<div class="option" data='{"value":"Simonpuszta","state":"Nograd"}'>Simonpuszta</div>
<div class="option" data='{"value":"Simontanya","state":"Nograd"}'>Simontanya</div>
<div class="option" data='{"value":"Sojpuszta","state":"Nograd"}'>Sojpuszta</div>
<div class="option" data='{"value":"Solyombanyatelep","state":"Nograd"}'>Solyombanyatelep</div>
<div class="option" data='{"value":"Solyombatelep","state":"Nograd"}'>Solyombatelep</div>
<div class="option" data='{"value":"Somlyo Banya","state":"Nograd"}'>Somlyo Banya</div>
<div class="option" data='{"value":"Somlyo Banyatelep","state":"Nograd"}'>Somlyo Banyatelep</div>
<div class="option" data='{"value":"Somlyopuszta","state":"Nograd"}'>Somlyopuszta</div>
<div class="option" data='{"value":"Somlyotelep","state":"Nograd"}'>Somlyotelep</div>
<div class="option" data='{"value":"Somoska","state":"Nograd"}'>Somoska</div>
<div class="option" data='{"value":"Somosko","state":"Nograd"}'>Somosko</div>
<div class="option" data='{"value":"Somoskoujfalu","state":"Nograd"}'>Somoskoujfalu</div>
<div class="option" data='{"value":"Soshartyan","state":"Nograd"}'>Soshartyan</div>
<div class="option" data='{"value":"Soskadomb","state":"Nograd"}'>Soskadomb</div>
<div class="option" data='{"value":"Sospuszta","state":"Nograd"}'>Sospuszta</div>
<div class="option" data='{"value":"Sostanya","state":"Nograd"}'>Sostanya</div>
<div class="option" data='{"value":"Sotetlapapuszta","state":"Nograd"}'>Sotetlapapuszta</div>
<div class="option" data='{"value":"Sotopuszta","state":"Nograd"}'>Sotopuszta</div>
<div class="option" data='{"value":"Sulyonalja","state":"Nograd"}'>Sulyonalja</div>
<div class="option" data='{"value":"Surupuszta","state":"Nograd"}'>Surupuszta</div>
<div class="option" data='{"value":"Szabadpuszta","state":"Nograd"}'>Szabadpuszta</div>
<div class="option" data='{"value":"Szalaskapuszta","state":"Nograd"}'>Szalaskapuszta</div>
<div class="option" data='{"value":"Szallaspuszta","state":"Nograd"}'>Szallaspuszta</div>
<div class="option" data='{"value":"Szalmatercs","state":"Nograd"}'>Szalmatercs</div>
<div class="option" data='{"value":"Szalokapuszta","state":"Nograd"}'>Szalokapuszta</div>
<div class="option" data='{"value":"Szanas","state":"Nograd"}'>Szanas</div>
<div class="option" data='{"value":"Szanasalja","state":"Nograd"}'>Szanasalja</div>
<div class="option" data='{"value":"Szanaspuszta","state":"Nograd"}'>Szanaspuszta</div>
<div class="option" data='{"value":"Szanda","state":"Nograd"}'>Szanda</div>
<div class="option" data='{"value":"Szandaaljapuszta","state":"Nograd"}'>Szandaaljapuszta</div>
<div class="option" data='{"value":"Szandavaralja","state":"Nograd"}'>Szandavaralja</div>
<div class="option" data='{"value":"Szarazret","state":"Nograd"}'>Szarazret</div>
<div class="option" data='{"value":"Szarvasgede","state":"Nograd"}'>Szarvasgede</div>
<div class="option" data='{"value":"Szarvashegy","state":"Nograd"}'>Szarvashegy</div>
<div class="option" data='{"value":"Szarvaskutpuszta","state":"Nograd"}'>Szarvaskutpuszta</div>
<div class="option" data='{"value":"Szatok","state":"Nograd"}'>Szatok</div>
<div class="option" data='{"value":"Szecheny","state":"Nograd"}'>Szecheny</div>
<div class="option" data='{"value":"Szecsenke","state":"Nograd"}'>Szecsenke</div>
<div class="option" data='{"value":"Szecseny","state":"Nograd"}'>Szecseny</div>
<div class="option" data='{"value":"Szecsenyfelfalu","state":"Nograd"}'>Szecsenyfelfalu</div>
<div class="option" data='{"value":"Szecsenyhalaszi","state":"Nograd"}'>Szecsenyhalaszi</div>
<div class="option" data='{"value":"Szekrenykepuszta","state":"Nograd"}'>Szekrenykepuszta</div>
<div class="option" data='{"value":"Szekvolgypuszta","state":"Nograd"}'>Szekvolgypuszta</div>
<div class="option" data='{"value":"Szelesvolgy","state":"Nograd"}'>Szelesvolgy</div>
<div class="option" data='{"value":"Szendehely","state":"Nograd"}'>Szendehely</div>
<div class="option" data='{"value":"Szenegetopuszta","state":"Nograd"}'>Szenegetopuszta</div>
<div class="option" data='{"value":"Szente","state":"Nograd"}'>Szente</div>
<div class="option" data='{"value":"Szentivanyi Puszta","state":"Nograd"}'>Szentivanyi Puszta</div>
<div class="option" data='{"value":"Szentivanyimajor","state":"Nograd"}'>Szentivanyimajor</div>
<div class="option" data='{"value":"Szentjanospuszta","state":"Nograd"}'>Szentjanospuszta</div>
<div class="option" data='{"value":"Szentkut","state":"Nograd"}'>Szentkut</div>
<div class="option" data='{"value":"Szentkutpuszta","state":"Nograd"}'>Szentkutpuszta</div>
<div class="option" data='{"value":"Szigetpuszta","state":"Nograd"}'>Szigetpuszta</div>
<div class="option" data='{"value":"Szilaspogony","state":"Nograd"}'>Szilaspogony</div>
<div class="option" data='{"value":"Sziluskapuszta","state":"Nograd"}'>Sziluskapuszta</div>
<div class="option" data='{"value":"Szilvasgodorpuszta","state":"Nograd"}'>Szilvasgodorpuszta</div>
<div class="option" data='{"value":"Szilvasgodortanya","state":"Nograd"}'>Szilvasgodortanya</div>
<div class="option" data='{"value":"Szilvaskopuszta","state":"Nograd"}'>Szilvaskopuszta</div>
<div class="option" data='{"value":"Szirak","state":"Nograd"}'>Szirak</div>
<div class="option" data='{"value":"Szivadalpuszta","state":"Nograd"}'>Szivadalpuszta</div>
<div class="option" data='{"value":"Szollokaljapuszta","state":"Nograd"}'>Szollokaljapuszta</div>
<div class="option" data='{"value":"Szollotelep","state":"Nograd"}'>Szollotelep</div>
<div class="option" data='{"value":"Szolloveropuszta","state":"Nograd"}'>Szolloveropuszta</div>
<div class="option" data='{"value":"Szolokaljapuszta","state":"Nograd"}'>Szolokaljapuszta</div>
<div class="option" data='{"value":"Szolotelep","state":"Nograd"}'>Szolotelep</div>
<div class="option" data='{"value":"Szomolyapuszta","state":"Nograd"}'>Szomolyapuszta</div>
<div class="option" data='{"value":"Szondymajor","state":"Nograd"}'>Szondymajor</div>
<div class="option" data='{"value":"Szorosipuszta","state":"Nograd"}'>Szorosipuszta</div>
<div class="option" data='{"value":"Szoroslapapuszta","state":"Nograd"}'>Szoroslapapuszta</div>
<div class="option" data='{"value":"Szorospatak","state":"Nograd"}'>Szorospatak</div>
<div class="option" data='{"value":"Szorospatakbanyatelep","state":"Nograd"}'>Szorospatakbanyatelep</div>
<div class="option" data='{"value":"Szorospataki Banyatelep","state":"Nograd"}'>Szorospataki Banyatelep</div>
<div class="option" data='{"value":"Szorospuszta","state":"Nograd"}'>Szorospuszta</div>
<div class="option" data='{"value":"Szugy","state":"Nograd"}'>Szugy</div>
<div class="option" data='{"value":"Szuha","state":"Nograd"}'>Szuha</div>
<div class="option" data='{"value":"Szuhahuta","state":"Nograd"}'>Szuhahuta</div>
<div class="option" data='{"value":"Szuhapuszta","state":"Nograd"}'>Szuhapuszta</div>
<div class="option" data='{"value":"Szupatak","state":"Nograd"}'>Szupatak</div>
<div class="option" data='{"value":"Szupukatanya","state":"Nograd"}'>Szupukatanya</div>
<div class="option" data='{"value":"Szurdok","state":"Nograd"}'>Szurdok</div>
<div class="option" data='{"value":"Szurdokpuspoki","state":"Nograd"}'>Szurdokpuspoki</div>
<div class="option" data='{"value":"Szvitajka","state":"Nograd"}'>Szvitajka</div>
<div class="option" data='{"value":"Szvitajkapuszta","state":"Nograd"}'>Szvitajkapuszta</div>
<div class="option" data='{"value":"Takacshazapuszta","state":"Nograd"}'>Takacshazapuszta</div>
<div class="option" data='{"value":"Tar","state":"Nograd"}'>Tar</div>
<div class="option" data='{"value":"Tarvolgy","state":"Nograd"}'>Tarvolgy</div>
<div class="option" data='{"value":"Telekpuszta","state":"Nograd"}'>Telekpuszta</div>
<div class="option" data='{"value":"Tepke","state":"Nograd"}'>Tepke</div>
<div class="option" data='{"value":"Tereny","state":"Nograd"}'>Tereny</div>
<div class="option" data='{"value":"Tereske","state":"Nograd"}'>Tereske</div>
<div class="option" data='{"value":"Tereziatelep","state":"Nograd"}'>Tereziatelep</div>
<div class="option" data='{"value":"Terzlaktanya","state":"Nograd"}'>Terzlaktanya</div>
<div class="option" data='{"value":"Tiribespuszta","state":"Nograd"}'>Tiribespuszta</div>
<div class="option" data='{"value":"Tofarka","state":"Nograd"}'>Tofarka</div>
<div class="option" data='{"value":"Tokespuszta","state":"Nograd"}'>Tokespuszta</div>
<div class="option" data='{"value":"Tolgyespuszta","state":"Nograd"}'>Tolgyespuszta</div>
<div class="option" data='{"value":"Tolmacs","state":"Nograd"}'>Tolmacs</div>
<div class="option" data='{"value":"Tomacs","state":"Nograd"}'>Tomacs</div>
<div class="option" data='{"value":"Totujfalu","state":"Nograd"}'>Totujfalu</div>
<div class="option" data='{"value":"Tozsertanya","state":"Nograd"}'>Tozsertanya</div>
<div class="option" data='{"value":"Udvarhelypuszta","state":"Nograd"}'>Udvarhelypuszta</div>
<div class="option" data='{"value":"Ujhegyi Szollok","state":"Nograd"}'>Ujhegyi Szollok</div>
<div class="option" data='{"value":"Ujhidegkutpuszta","state":"Nograd"}'>Ujhidegkutpuszta</div>
<div class="option" data='{"value":"Ujkovar","state":"Nograd"}'>Ujkovar</div>
<div class="option" data='{"value":"Ujlakpuszta","state":"Nograd"}'>Ujlakpuszta</div>
<div class="option" data='{"value":"Ujmajor","state":"Nograd"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujtelep","state":"Nograd"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujzsunypuszta","state":"Nograd"}'>Ujzsunypuszta</div>
<div class="option" data='{"value":"Urgespuszta","state":"Nograd"}'>Urgespuszta</div>
<div class="option" data='{"value":"Vadaskert","state":"Nograd"}'>Vadaskert</div>
<div class="option" data='{"value":"Vadaskertpuszta","state":"Nograd"}'>Vadaskertpuszta</div>
<div class="option" data='{"value":"Vadicsapuszta","state":"Nograd"}'>Vadicsapuszta</div>
<div class="option" data='{"value":"Vagaspuszta","state":"Nograd"}'>Vagaspuszta</div>
<div class="option" data='{"value":"Vancsopuszta","state":"Nograd"}'>Vancsopuszta</div>
<div class="option" data='{"value":"Vanyarc","state":"Nograd"}'>Vanyarc</div>
<div class="option" data='{"value":"Varadvolgyitanya","state":"Nograd"}'>Varadvolgyitanya</div>
<div class="option" data='{"value":"Varoserdo","state":"Nograd"}'>Varoserdo</div>
<div class="option" data='{"value":"Varsany","state":"Nograd"}'>Varsany</div>
<div class="option" data='{"value":"Vilagos","state":"Nograd"}'>Vilagos</div>
<div class="option" data='{"value":"Vilagospuszta","state":"Nograd"}'>Vilagospuszta</div>
<div class="option" data='{"value":"Vincetanya","state":"Nograd"}'>Vincetanya</div>
<div class="option" data='{"value":"Viragospuszta","state":"Nograd"}'>Viragospuszta</div>
<div class="option" data='{"value":"Vitezitelektanya","state":"Nograd"}'>Vitezitelektanya</div>
<div class="option" data='{"value":"Vizslas","state":"Nograd"}'>Vizslas</div>
<div class="option" data='{"value":"Vizvalaszto","state":"Nograd"}'>Vizvalaszto</div>
<div class="option" data='{"value":"Vizvolgypuszta","state":"Nograd"}'>Vizvolgypuszta</div>
<div class="option" data='{"value":"Volgyfopuszta","state":"Nograd"}'>Volgyfopuszta</div>
<div class="option" data='{"value":"Zabar","state":"Nograd"}'>Zabar</div>
<div class="option" data='{"value":"Zagyvapalfalva","state":"Nograd"}'>Zagyvapalfalva</div>
<div class="option" data='{"value":"Zagyvarona","state":"Nograd"}'>Zagyvarona</div>
<div class="option" data='{"value":"Zarandok","state":"Nograd"}'>Zarandok</div>
<div class="option" data='{"value":"Zsadanypuszta","state":"Nograd"}'>Zsadanypuszta</div>
<div class="option" data='{"value":"Zsillo","state":"Nograd"}'>Zsillo</div>
<div class="option" data='{"value":"Zsillotanya","state":"Nograd"}'>Zsillotanya</div>
<div class="option" data='{"value":"Zsiva","state":"Nograd"}'>Zsiva</div>
<div class="option" data='{"value":"Zsovolgypuszta","state":"Nograd"}'>Zsovolgypuszta</div>
<div class="option" id="option_end" data='{"value":"Zsunypuszta","state":"Nograd"}'>Zsunypuszta</div>

