<div class="option" data='{"value":"Adorjanpuszta","state":"Tolna"}'>Adorjanpuszta</div>
<div class="option" data='{"value":"Adorjanujtelep","state":"Tolna"}'>Adorjanujtelep</div>
<div class="option" data='{"value":"Agardivolgy","state":"Tolna"}'>Agardivolgy</div>
<div class="option" data='{"value":"Agasto","state":"Tolna"}'>Agasto</div>
<div class="option" data='{"value":"Agasvar","state":"Tolna"}'>Agasvar</div>
<div class="option" data='{"value":"Agostonpuszta","state":"Tolna"}'>Agostonpuszta</div>
<div class="option" data='{"value":"Akalacs","state":"Tolna"}'>Akalacs</div>
<div class="option" data='{"value":"Alfoldszallas","state":"Tolna"}'>Alfoldszallas</div>
<div class="option" data='{"value":"Alfoldszallasok","state":"Tolna"}'>Alfoldszallasok</div>
<div class="option" data='{"value":"Almas","state":"Tolna"}'>Almas</div>
<div class="option" data='{"value":"Almas Puszta","state":"Tolna"}'>Almas Puszta</div>
<div class="option" data='{"value":"Alsoavas","state":"Tolna"}'>Alsoavas</div>
<div class="option" data='{"value":"Alsobikad","state":"Tolna"}'>Alsobikad</div>
<div class="option" data='{"value":"Alsoborzsony","state":"Tolna"}'>Alsoborzsony</div>
<div class="option" data='{"value":"Alsocsampa","state":"Tolna"}'>Alsocsampa</div>
<div class="option" data='{"value":"Alsocsillag","state":"Tolna"}'>Alsocsillag</div>
<div class="option" data='{"value":"Alsocsurgo","state":"Tolna"}'>Alsocsurgo</div>
<div class="option" data='{"value":"Alsodolina","state":"Tolna"}'>Alsodolina</div>
<div class="option" data='{"value":"Alsofarkasd","state":"Tolna"}'>Alsofarkasd</div>
<div class="option" data='{"value":"Alsohard","state":"Tolna"}'>Alsohard</div>
<div class="option" data='{"value":"Alsohegy","state":"Tolna"}'>Alsohegy</div>
<div class="option" data='{"value":"Alsohidveg","state":"Tolna"}'>Alsohidveg</div>
<div class="option" data='{"value":"Alsohomokerdo","state":"Tolna"}'>Alsohomokerdo</div>
<div class="option" data='{"value":"Alsokovacsmajor","state":"Tolna"}'>Alsokovacsmajor</div>
<div class="option" data='{"value":"Alsoleperd","state":"Tolna"}'>Alsoleperd</div>
<div class="option" data='{"value":"Alsomajsa","state":"Tolna"}'>Alsomajsa</div>
<div class="option" data='{"value":"Alsomegyes","state":"Tolna"}'>Alsomegyes</div>
<div class="option" data='{"value":"Alsomocsarasdulo","state":"Tolna"}'>Alsomocsarasdulo</div>
<div class="option" data='{"value":"Alsonana","state":"Tolna"}'>Alsonana</div>
<div class="option" data='{"value":"Alsonanai Laiver","state":"Tolna"}'>Alsonanai Laiver</div>
<div class="option" data='{"value":"Alsonanai Mauszcsarda","state":"Tolna"}'>Alsonanai Mauszcsarda</div>
<div class="option" data='{"value":"Alsonyek","state":"Tolna"}'>Alsonyek</div>
<div class="option" data='{"value":"Alsooreghegy","state":"Tolna"}'>Alsooreghegy</div>
<div class="option" data='{"value":"Alsopatlan","state":"Tolna"}'>Alsopatlan</div>
<div class="option" data='{"value":"Alsopel","state":"Tolna"}'>Alsopel</div>
<div class="option" data='{"value":"Alsopuszta","state":"Tolna"}'>Alsopuszta</div>
<div class="option" data='{"value":"Alsoracegres","state":"Tolna"}'>Alsoracegres</div>
<div class="option" data='{"value":"Alsorev","state":"Tolna"}'>Alsorev</div>
<div class="option" data='{"value":"Alsoszigeti Major","state":"Tolna"}'>Alsoszigeti Major</div>
<div class="option" data='{"value":"Alsotengelic","state":"Tolna"}'>Alsotengelic</div>
<div class="option" data='{"value":"Alsoto","state":"Tolna"}'>Alsoto</div>
<div class="option" data='{"value":"Andormajor","state":"Tolna"}'>Andormajor</div>
<div class="option" data='{"value":"Andraspuszta","state":"Tolna"}'>Andraspuszta</div>
<div class="option" data='{"value":"Angyaldomb","state":"Tolna"}'>Angyaldomb</div>
<div class="option" data='{"value":"Annafurdo","state":"Tolna"}'>Annafurdo</div>
<div class="option" data='{"value":"Annahegy","state":"Tolna"}'>Annahegy</div>
<div class="option" data='{"value":"Annamajor","state":"Tolna"}'>Annamajor</div>
<div class="option" data='{"value":"Aparhant","state":"Tolna"}'>Aparhant</div>
<div class="option" data='{"value":"Apatipuszta","state":"Tolna"}'>Apatipuszta</div>
<div class="option" data='{"value":"Aranga","state":"Tolna"}'>Aranga</div>
<div class="option" data='{"value":"Aranyto","state":"Tolna"}'>Aranyto</div>
<div class="option" data='{"value":"Asvany","state":"Tolna"}'>Asvany</div>
<div class="option" data='{"value":"Avas","state":"Tolna"}'>Avas</div>
<div class="option" data='{"value":"Avaspuszta","state":"Tolna"}'>Avaspuszta</div>
<div class="option" data='{"value":"Badivolgy","state":"Tolna"}'>Badivolgy</div>
<div class="option" data='{"value":"Bagovolgy","state":"Tolna"}'>Bagovolgy</div>
<div class="option" data='{"value":"Bakaszallas","state":"Tolna"}'>Bakaszallas</div>
<div class="option" data='{"value":"Bali Major","state":"Tolna"}'>Bali Major</div>
<div class="option" data='{"value":"Balitanya","state":"Tolna"}'>Balitanya</div>
<div class="option" data='{"value":"Banierdo","state":"Tolna"}'>Banierdo</div>
<div class="option" data='{"value":"Banyatelep","state":"Tolna"}'>Banyatelep</div>
<div class="option" data='{"value":"Baranyfok","state":"Tolna"}'>Baranyfok</div>
<div class="option" data='{"value":"Barnahat","state":"Tolna"}'>Barnahat</div>
<div class="option" data='{"value":"Barnahatpuszta","state":"Tolna"}'>Barnahatpuszta</div>
<div class="option" data='{"value":"Barossdulo","state":"Tolna"}'>Barossdulo</div>
<div class="option" data='{"value":"Barotakoz","state":"Tolna"}'>Barotakoz</div>
<div class="option" data='{"value":"Barotapuszta","state":"Tolna"}'>Barotapuszta</div>
<div class="option" data='{"value":"Bartina","state":"Tolna"}'>Bartina</div>
<div class="option" data='{"value":"Bata","state":"Tolna"}'>Bata</div>
<div class="option" data='{"value":"Bataapati","state":"Tolna"}'>Bataapati</div>
<div class="option" data='{"value":"Bataszek","state":"Tolna"}'>Bataszek</div>
<div class="option" data='{"value":"Beldoromlas","state":"Tolna"}'>Beldoromlas</div>
<div class="option" data='{"value":"Belecska","state":"Tolna"}'>Belecska</div>
<div class="option" data='{"value":"Bencepuszta","state":"Tolna"}'>Bencepuszta</div>
<div class="option" data='{"value":"Bencevolgy","state":"Tolna"}'>Bencevolgy</div>
<div class="option" data='{"value":"Benedekvolgy","state":"Tolna"}'>Benedekvolgy</div>
<div class="option" data='{"value":"Betekincspuszta","state":"Tolna"}'>Betekincspuszta</div>
<div class="option" data='{"value":"Betekintspuszta","state":"Tolna"}'>Betekintspuszta</div>
<div class="option" data='{"value":"Bezeredj","state":"Tolna"}'>Bezeredj</div>
<div class="option" data='{"value":"Bezzegimajor","state":"Tolna"}'>Bezzegimajor</div>
<div class="option" data='{"value":"Bezzegpuszta","state":"Tolna"}'>Bezzegpuszta</div>
<div class="option" data='{"value":"Bikacs","state":"Tolna"}'>Bikacs</div>
<div class="option" data='{"value":"Bikad","state":"Tolna"}'>Bikad</div>
<div class="option" data='{"value":"Birito","state":"Tolna"}'>Birito</div>
<div class="option" data='{"value":"Biritopuszta","state":"Tolna"}'>Biritopuszta</div>
<div class="option" data='{"value":"Birkamajor","state":"Tolna"}'>Birkamajor</div>
<div class="option" data='{"value":"Birod","state":"Tolna"}'>Birod</div>
<div class="option" data='{"value":"Bleszermalom","state":"Tolna"}'>Bleszermalom</div>
<div class="option" data='{"value":"Bodatanya","state":"Tolna"}'>Bodatanya</div>
<div class="option" data='{"value":"Bodohegy","state":"Tolna"}'>Bodohegy</div>
<div class="option" data='{"value":"Bodzas","state":"Tolna"}'>Bodzas</div>
<div class="option" data='{"value":"Bogaras","state":"Tolna"}'>Bogaras</div>
<div class="option" data='{"value":"Bograihatar","state":"Tolna"}'>Bograihatar</div>
<div class="option" data='{"value":"Bograoldal","state":"Tolna"}'>Bograoldal</div>
<div class="option" data='{"value":"Bograpuszta","state":"Tolna"}'>Bograpuszta</div>
<div class="option" data='{"value":"Bogyiszlo","state":"Tolna"}'>Bogyiszlo</div>
<div class="option" data='{"value":"Bokod","state":"Tolna"}'>Bokod</div>
<div class="option" data='{"value":"Bolcske","state":"Tolna"}'>Bolcske</div>
<div class="option" data='{"value":"Bonyhad","state":"Tolna"}'>Bonyhad</div>
<div class="option" data='{"value":"Bonyhadszerdahely","state":"Tolna"}'>Bonyhadszerdahely</div>
<div class="option" data='{"value":"Bonyhadvarasd","state":"Tolna"}'>Bonyhadvarasd</div>
<div class="option" data='{"value":"Borjad","state":"Tolna"}'>Borjad</div>
<div class="option" data='{"value":"Borjukut","state":"Tolna"}'>Borjukut</div>
<div class="option" data='{"value":"Borkut","state":"Tolna"}'>Borkut</div>
<div class="option" data='{"value":"Borzsony","state":"Tolna"}'>Borzsony</div>
<div class="option" data='{"value":"Bukkvolgy","state":"Tolna"}'>Bukkvolgy</div>
<div class="option" data='{"value":"Buvat","state":"Tolna"}'>Buvat</div>
<div class="option" data='{"value":"Cedulahaz","state":"Tolna"}'>Cedulahaz</div>
<div class="option" data='{"value":"Cel","state":"Tolna"}'>Cel</div>
<div class="option" data='{"value":"Celpuszta","state":"Tolna"}'>Celpuszta</div>
<div class="option" data='{"value":"Ciko","state":"Tolna"}'>Ciko</div>
<div class="option" data='{"value":"Cinegevolgy","state":"Tolna"}'>Cinegevolgy</div>
<div class="option" data='{"value":"Cinka","state":"Tolna"}'>Cinka</div>
<div class="option" data='{"value":"Csabagodor","state":"Tolna"}'>Csabagodor</div>
<div class="option" data='{"value":"Csampa","state":"Tolna"}'>Csampa</div>
<div class="option" data='{"value":"Csapotengelic","state":"Tolna"}'>Csapotengelic</div>
<div class="option" data='{"value":"Csardahegy","state":"Tolna"}'>Csardahegy</div>
<div class="option" data='{"value":"Csardamalom","state":"Tolna"}'>Csardamalom</div>
<div class="option" data='{"value":"Csataritelep","state":"Tolna"}'>Csataritelep</div>
<div class="option" data='{"value":"Csehipuszta","state":"Tolna"}'>Csehipuszta</div>
<div class="option" data='{"value":"Csencsevar","state":"Tolna"}'>Csencsevar</div>
<div class="option" data='{"value":"Cserengati Malom","state":"Tolna"}'>Cserengati Malom</div>
<div class="option" data='{"value":"Cserepesmajor","state":"Tolna"}'>Cserepesmajor</div>
<div class="option" data='{"value":"Cseresnyes","state":"Tolna"}'>Cseresnyes</div>
<div class="option" data='{"value":"Cseresznyes","state":"Tolna"}'>Cseresznyes</div>
<div class="option" data='{"value":"Cserhat","state":"Tolna"}'>Cserhat</div>
<div class="option" data='{"value":"Cseringat","state":"Tolna"}'>Cseringat</div>
<div class="option" data='{"value":"Csernyed","state":"Tolna"}'>Csernyed</div>
<div class="option" data='{"value":"Cservolgy","state":"Tolna"}'>Cservolgy</div>
<div class="option" data='{"value":"Csibrak","state":"Tolna"}'>Csibrak</div>
<div class="option" data='{"value":"Csicso","state":"Tolna"}'>Csicso</div>
<div class="option" data='{"value":"Csihar","state":"Tolna"}'>Csihar</div>
<div class="option" data='{"value":"Csikomajor","state":"Tolna"}'>Csikomajor</div>
<div class="option" data='{"value":"Csikostottos","state":"Tolna"}'>Csikostottos</div>
<div class="option" data='{"value":"Csiripmajor","state":"Tolna"}'>Csiripmajor</div>
<div class="option" data='{"value":"Csirka","state":"Tolna"}'>Csirka</div>
<div class="option" data='{"value":"Csocskepuszta","state":"Tolna"}'>Csocskepuszta</div>
<div class="option" data='{"value":"Csokas","state":"Tolna"}'>Csokas</div>
<div class="option" data='{"value":"Csokaspuszta","state":"Tolna"}'>Csokaspuszta</div>
<div class="option" data='{"value":"Csollanyos","state":"Tolna"}'>Csollanyos</div>
<div class="option" data='{"value":"Csollanyospuszta","state":"Tolna"}'>Csollanyospuszta</div>
<div class="option" data='{"value":"Csongohegy","state":"Tolna"}'>Csongohegy</div>
<div class="option" data='{"value":"Csonkavolgy","state":"Tolna"}'>Csonkavolgy</div>
<div class="option" data='{"value":"Csotonyivolgy","state":"Tolna"}'>Csotonyivolgy</div>
<div class="option" data='{"value":"Csurgo","state":"Tolna"}'>Csurgo</div>
<div class="option" data='{"value":"Csurgopuszta","state":"Tolna"}'>Csurgopuszta</div>
<div class="option" data='{"value":"Dalmand","state":"Tolna"}'>Dalmand</div>
<div class="option" data='{"value":"Daroczymajor","state":"Tolna"}'>Daroczymajor</div>
<div class="option" data='{"value":"Decs","state":"Tolna"}'>Decs</div>
<div class="option" data='{"value":"Delimajor","state":"Tolna"}'>Delimajor</div>
<div class="option" data='{"value":"Delivolgy","state":"Tolna"}'>Delivolgy</div>
<div class="option" data='{"value":"Dios","state":"Tolna"}'>Dios</div>
<div class="option" data='{"value":"Diosbereny","state":"Tolna"}'>Diosbereny</div>
<div class="option" data='{"value":"Dobrokoz","state":"Tolna"}'>Dobrokoz</div>
<div class="option" data='{"value":"Dobronte","state":"Tolna"}'>Dobronte</div>
<div class="option" data='{"value":"Dobronteihegy","state":"Tolna"}'>Dobronteihegy</div>
<div class="option" data='{"value":"Dobrontepuszta","state":"Tolna"}'>Dobrontepuszta</div>
<div class="option" data='{"value":"Dobronteszolohegy","state":"Tolna"}'>Dobronteszolohegy</div>
<div class="option" data='{"value":"Dobronteujtelep","state":"Tolna"}'>Dobronteujtelep</div>
<div class="option" data='{"value":"Dolina","state":"Tolna"}'>Dolina</div>
<div class="option" data='{"value":"Dolinapuszta","state":"Tolna"}'>Dolinapuszta</div>
<div class="option" data='{"value":"Domboripuszta","state":"Tolna"}'>Domboripuszta</div>
<div class="option" data='{"value":"Dombovar","state":"Tolna"}'>Dombovar</div>
<div class="option" data='{"value":"Donattanya","state":"Tolna"}'>Donattanya</div>
<div class="option" data='{"value":"Dorog","state":"Tolna"}'>Dorog</div>
<div class="option" data='{"value":"Dorogpuszta","state":"Tolna"}'>Dorogpuszta</div>
<div class="option" data='{"value":"Doromlas Puszta","state":"Tolna"}'>Doromlas Puszta</div>
<div class="option" data='{"value":"Dorytabod","state":"Tolna"}'>Dorytabod</div>
<div class="option" data='{"value":"Dunaerdei Dulo","state":"Tolna"}'>Dunaerdei Dulo</div>
<div class="option" data='{"value":"Dunafoldvar","state":"Tolna"}'>Dunafoldvar</div>
<div class="option" data='{"value":"Dunairev","state":"Tolna"}'>Dunairev</div>
<div class="option" data='{"value":"Dunakomlod","state":"Tolna"}'>Dunakomlod</div>
<div class="option" data='{"value":"Dunaszel","state":"Tolna"}'>Dunaszel</div>
<div class="option" data='{"value":"Dunaszentgyorgy","state":"Tolna"}'>Dunaszentgyorgy</div>
<div class="option" data='{"value":"Duzs","state":"Tolna"}'>Duzs</div>
<div class="option" data='{"value":"Ebestanya","state":"Tolna"}'>Ebestanya</div>
<div class="option" data='{"value":"Egestanya","state":"Tolna"}'>Egestanya</div>
<div class="option" data='{"value":"Elohegy","state":"Tolna"}'>Elohegy</div>
<div class="option" data='{"value":"Emmamajor","state":"Tolna"}'>Emmamajor</div>
<div class="option" data='{"value":"Erdotelek","state":"Tolna"}'>Erdotelek</div>
<div class="option" data='{"value":"Ernomajor","state":"Tolna"}'>Ernomajor</div>
<div class="option" data='{"value":"Erosmezodulo","state":"Tolna"}'>Erosmezodulo</div>
<div class="option" data='{"value":"Erteny","state":"Tolna"}'>Erteny</div>
<div class="option" data='{"value":"Erzsebetmajor","state":"Tolna"}'>Erzsebetmajor</div>
<div class="option" data='{"value":"Eszteripuszta","state":"Tolna"}'>Eszteripuszta</div>
<div class="option" data='{"value":"Eszterpuszta","state":"Tolna"}'>Eszterpuszta</div>
<div class="option" data='{"value":"Facankert","state":"Tolna"}'>Facankert</div>
<div class="option" data='{"value":"Facankerti Major","state":"Tolna"}'>Facankerti Major</div>
<div class="option" data='{"value":"Facankertpuszta","state":"Tolna"}'>Facankertpuszta</div>
<div class="option" data='{"value":"Fadd","state":"Tolna"}'>Fadd</div>
<div class="option" data='{"value":"Faluberki","state":"Tolna"}'>Faluberki</div>
<div class="option" data='{"value":"Faluhely","state":"Tolna"}'>Faluhely</div>
<div class="option" data='{"value":"Farkaserdotanya","state":"Tolna"}'>Farkaserdotanya</div>
<div class="option" data='{"value":"Farkasvolgy","state":"Tolna"}'>Farkasvolgy</div>
<div class="option" data='{"value":"Feketo","state":"Tolna"}'>Feketo</div>
<div class="option" data='{"value":"Felhago","state":"Tolna"}'>Felhago</div>
<div class="option" data='{"value":"Felhagopuszta","state":"Tolna"}'>Felhagopuszta</div>
<div class="option" data='{"value":"Felso Hullo","state":"Tolna"}'>Felso Hullo</div>
<div class="option" data='{"value":"Felsocsernyed","state":"Tolna"}'>Felsocsernyed</div>
<div class="option" data='{"value":"Felsocsurgo","state":"Tolna"}'>Felsocsurgo</div>
<div class="option" data='{"value":"Felsofarkasd","state":"Tolna"}'>Felsofarkasd</div>
<div class="option" data='{"value":"Felsogyant","state":"Tolna"}'>Felsogyant</div>
<div class="option" data='{"value":"Felsogyantpuszta","state":"Tolna"}'>Felsogyantpuszta</div>
<div class="option" data='{"value":"Felsohard","state":"Tolna"}'>Felsohard</div>
<div class="option" data='{"value":"Felsohidveg","state":"Tolna"}'>Felsohidveg</div>
<div class="option" data='{"value":"Felsohidvegpuszta","state":"Tolna"}'>Felsohidvegpuszta</div>
<div class="option" data='{"value":"Felsohomokerdo","state":"Tolna"}'>Felsohomokerdo</div>
<div class="option" data='{"value":"Felsoleperd","state":"Tolna"}'>Felsoleperd</div>
<div class="option" data='{"value":"Felsomegyes","state":"Tolna"}'>Felsomegyes</div>
<div class="option" data='{"value":"Felsonana","state":"Tolna"}'>Felsonana</div>
<div class="option" data='{"value":"Felsonyek","state":"Tolna"}'>Felsonyek</div>
<div class="option" data='{"value":"Felsooreghegy","state":"Tolna"}'>Felsooreghegy</div>
<div class="option" data='{"value":"Felsopatlan","state":"Tolna"}'>Felsopatlan</div>
<div class="option" data='{"value":"Felsopel","state":"Tolna"}'>Felsopel</div>
<div class="option" data='{"value":"Felsopelpuszta","state":"Tolna"}'>Felsopelpuszta</div>
<div class="option" data='{"value":"Felsopuszta","state":"Tolna"}'>Felsopuszta</div>
<div class="option" data='{"value":"Felsoracegres","state":"Tolna"}'>Felsoracegres</div>
<div class="option" data='{"value":"Felsorev","state":"Tolna"}'>Felsorev</div>
<div class="option" data='{"value":"Felsoszigettanya","state":"Tolna"}'>Felsoszigettanya</div>
<div class="option" data='{"value":"Felsotengelic","state":"Tolna"}'>Felsotengelic</div>
<div class="option" data='{"value":"Fenyersor","state":"Tolna"}'>Fenyersor</div>
<div class="option" data='{"value":"Ferenckut","state":"Tolna"}'>Ferenckut</div>
<div class="option" data='{"value":"Ferenckut Puszta","state":"Tolna"}'>Ferenckut Puszta</div>
<div class="option" data='{"value":"Ferenczimajor","state":"Tolna"}'>Ferenczimajor</div>
<div class="option" data='{"value":"Fintaallas","state":"Tolna"}'>Fintaallas</div>
<div class="option" data='{"value":"Floramajor","state":"Tolna"}'>Floramajor</div>
<div class="option" data='{"value":"Foldes","state":"Tolna"}'>Foldes</div>
<div class="option" data='{"value":"Foldespuszta","state":"Tolna"}'>Foldespuszta</div>
<div class="option" data='{"value":"Fornad","state":"Tolna"}'>Fornad</div>
<div class="option" data='{"value":"Fornadpuszta","state":"Tolna"}'>Fornadpuszta</div>
<div class="option" data='{"value":"Forras","state":"Tolna"}'>Forras</div>
<div class="option" data='{"value":"Furged","state":"Tolna"}'>Furged</div>
<div class="option" data='{"value":"Furko","state":"Tolna"}'>Furko</div>
<div class="option" data='{"value":"Furkopuszta","state":"Tolna"}'>Furkopuszta</div>
<div class="option" data='{"value":"Furkotelep","state":"Tolna"}'>Furkotelep</div>
<div class="option" data='{"value":"Fuzycsarda","state":"Tolna"}'>Fuzycsarda</div>
<div class="option" data='{"value":"Gabonas","state":"Tolna"}'>Gabonas</div>
<div class="option" data='{"value":"Gabormajor","state":"Tolna"}'>Gabormajor</div>
<div class="option" data='{"value":"Gaborpuszta","state":"Tolna"}'>Gaborpuszta</div>
<div class="option" data='{"value":"Gabortanya","state":"Tolna"}'>Gabortanya</div>
<div class="option" data='{"value":"Gebhardt Major","state":"Tolna"}'>Gebhardt Major</div>
<div class="option" data='{"value":"Gebhardtpuszta","state":"Tolna"}'>Gebhardtpuszta</div>
<div class="option" data='{"value":"Geimermalom","state":"Tolna"}'>Geimermalom</div>
<div class="option" data='{"value":"Gerenyas","state":"Tolna"}'>Gerenyas</div>
<div class="option" data='{"value":"Gerenyaspuszta","state":"Tolna"}'>Gerenyaspuszta</div>
<div class="option" data='{"value":"Gerjen","state":"Tolna"}'>Gerjen</div>
<div class="option" data='{"value":"Gesztenyes","state":"Tolna"}'>Gesztenyes</div>
<div class="option" data='{"value":"Glimermalom","state":"Tolna"}'>Glimermalom</div>
<div class="option" data='{"value":"Goga","state":"Tolna"}'>Goga</div>
<div class="option" data='{"value":"Gogatanya","state":"Tolna"}'>Gogatanya</div>
<div class="option" data='{"value":"Gonoszdpuszta","state":"Tolna"}'>Gonoszdpuszta</div>
<div class="option" data='{"value":"Gonozd","state":"Tolna"}'>Gonozd</div>
<div class="option" data='{"value":"Gonozdpuszta","state":"Tolna"}'>Gonozdpuszta</div>
<div class="option" data='{"value":"Gorogszo","state":"Tolna"}'>Gorogszo</div>
<div class="option" data='{"value":"Gozsypuszta","state":"Tolna"}'>Gozsypuszta</div>
<div class="option" data='{"value":"Graboc","state":"Tolna"}'>Graboc</div>
<div class="option" data='{"value":"Griesenwald","state":"Tolna"}'>Griesenwald</div>
<div class="option" data='{"value":"Griesewald","state":"Tolna"}'>Griesewald</div>
<div class="option" data='{"value":"Grizenvald","state":"Tolna"}'>Grizenvald</div>
<div class="option" data='{"value":"Gubacor","state":"Tolna"}'>Gubacor</div>
<div class="option" data='{"value":"Gubacorr","state":"Tolna"}'>Gubacorr</div>
<div class="option" data='{"value":"Gubarc","state":"Tolna"}'>Gubarc</div>
<div class="option" data='{"value":"Gubarci Szollok","state":"Tolna"}'>Gubarci Szollok</div>
<div class="option" data='{"value":"Gubarci Szolohegy","state":"Tolna"}'>Gubarci Szolohegy</div>
<div class="option" data='{"value":"Gulyasvolgy","state":"Tolna"}'>Gulyasvolgy</div>
<div class="option" data='{"value":"Gurovica","state":"Tolna"}'>Gurovica</div>
<div class="option" data='{"value":"Gutaipuszta","state":"Tolna"}'>Gutaipuszta</div>
<div class="option" data='{"value":"Gutaypuszta","state":"Tolna"}'>Gutaypuszta</div>
<div class="option" data='{"value":"Gyapa","state":"Tolna"}'>Gyapa</div>
<div class="option" data='{"value":"Gyongyosoldal","state":"Tolna"}'>Gyongyosoldal</div>
<div class="option" data='{"value":"Gyonk","state":"Tolna"}'>Gyonk</div>
<div class="option" data='{"value":"Gyore","state":"Tolna"}'>Gyore</div>
<div class="option" data='{"value":"Gyorgymajor","state":"Tolna"}'>Gyorgymajor</div>
<div class="option" data='{"value":"Gyorimajor","state":"Tolna"}'>Gyorimajor</div>
<div class="option" data='{"value":"Gyorkony","state":"Tolna"}'>Gyorkony</div>
<div class="option" data='{"value":"Gyorymajor","state":"Tolna"}'>Gyorymajor</div>
<div class="option" data='{"value":"Gyulahegy","state":"Tolna"}'>Gyulahegy</div>
<div class="option" data='{"value":"Gyulaj","state":"Tolna"}'>Gyulaj</div>
<div class="option" data='{"value":"Gyuszuvolgy","state":"Tolna"}'>Gyuszuvolgy</div>
<div class="option" data='{"value":"Hajdules","state":"Tolna"}'>Hajdules</div>
<div class="option" data='{"value":"Hajpalpuszta","state":"Tolna"}'>Hajpalpuszta</div>
<div class="option" data='{"value":"Halasto","state":"Tolna"}'>Halasto</div>
<div class="option" data='{"value":"Hamuhaz","state":"Tolna"}'>Hamuhaz</div>
<div class="option" data='{"value":"Hangos","state":"Tolna"}'>Hangos</div>
<div class="option" data='{"value":"Hangospuszta","state":"Tolna"}'>Hangospuszta</div>
<div class="option" data='{"value":"Hankpuszta","state":"Tolna"}'>Hankpuszta</div>
<div class="option" data='{"value":"Harc","state":"Tolna"}'>Harc</div>
<div class="option" data='{"value":"Hard","state":"Tolna"}'>Hard</div>
<div class="option" data='{"value":"Haromhaz","state":"Tolna"}'>Haromhaz</div>
<div class="option" data='{"value":"Hatarmajor","state":"Tolna"}'>Hatarmajor</div>
<div class="option" data='{"value":"Hatfo","state":"Tolna"}'>Hatfo</div>
<div class="option" data='{"value":"Havas","state":"Tolna"}'>Havas</div>
<div class="option" data='{"value":"Hegyes","state":"Tolna"}'>Hegyes</div>
<div class="option" data='{"value":"Hegyespuszta","state":"Tolna"}'>Hegyespuszta</div>
<div class="option" data='{"value":"Heislerpuszta","state":"Tolna"}'>Heislerpuszta</div>
<div class="option" data='{"value":"Herczoghtanya","state":"Tolna"}'>Herczoghtanya</div>
<div class="option" data='{"value":"Hidaspetre","state":"Tolna"}'>Hidaspetre</div>
<div class="option" data='{"value":"Hidja","state":"Tolna"}'>Hidja</div>
<div class="option" data='{"value":"Hidjapuszta","state":"Tolna"}'>Hidjapuszta</div>
<div class="option" data='{"value":"Hogyesz","state":"Tolna"}'>Hogyesz</div>
<div class="option" data='{"value":"Holtdunaag","state":"Tolna"}'>Holtdunaag</div>
<div class="option" data='{"value":"Homokhaz","state":"Tolna"}'>Homokhaz</div>
<div class="option" data='{"value":"Homokhegy","state":"Tolna"}'>Homokhegy</div>
<div class="option" data='{"value":"Honigpuszta","state":"Tolna"}'>Honigpuszta</div>
<div class="option" data='{"value":"Horgas","state":"Tolna"}'>Horgas</div>
<div class="option" data='{"value":"Hosszuvolgy","state":"Tolna"}'>Hosszuvolgy</div>
<div class="option" data='{"value":"Hullo","state":"Tolna"}'>Hullo</div>
<div class="option" data='{"value":"Ifigeniamajor","state":"Tolna"}'>Ifigeniamajor</div>
<div class="option" data='{"value":"Ifigeniapuszta","state":"Tolna"}'>Ifigeniapuszta</div>
<div class="option" data='{"value":"Inoka","state":"Tolna"}'>Inoka</div>
<div class="option" data='{"value":"Iregpuszta","state":"Tolna"}'>Iregpuszta</div>
<div class="option" data='{"value":"Iregszemcse","state":"Tolna"}'>Iregszemcse</div>
<div class="option" data='{"value":"Istvanmajor","state":"Tolna"}'>Istvanmajor</div>
<div class="option" data='{"value":"Ivanvolgy","state":"Tolna"}'>Ivanvolgy</div>
<div class="option" data='{"value":"Izguntanya","state":"Tolna"}'>Izguntanya</div>
<div class="option" data='{"value":"Izmeny","state":"Tolna"}'>Izmeny</div>
<div class="option" data='{"value":"Jagonak","state":"Tolna"}'>Jagonak</div>
<div class="option" data='{"value":"Jajtanya","state":"Tolna"}'>Jajtanya</div>
<div class="option" data='{"value":"Janoshegy","state":"Tolna"}'>Janoshegy</div>
<div class="option" data='{"value":"Janosmajor","state":"Tolna"}'>Janosmajor</div>
<div class="option" data='{"value":"Janyapuszta","state":"Tolna"}'>Janyapuszta</div>
<div class="option" data='{"value":"Jasztelepszallas","state":"Tolna"}'>Jasztelepszallas</div>
<div class="option" data='{"value":"Jegenyes","state":"Tolna"}'>Jegenyes</div>
<div class="option" data='{"value":"Jegenyes Puszta","state":"Tolna"}'>Jegenyes Puszta</div>
<div class="option" data='{"value":"Jegenyessziget","state":"Tolna"}'>Jegenyessziget</div>
<div class="option" data='{"value":"Jobbparaszta","state":"Tolna"}'>Jobbparaszta</div>
<div class="option" data='{"value":"Jozsefhegy","state":"Tolna"}'>Jozsefhegy</div>
<div class="option" data='{"value":"Jozsefmajor","state":"Tolna"}'>Jozsefmajor</div>
<div class="option" data='{"value":"Jozsefpuszta","state":"Tolna"}'>Jozsefpuszta</div>
<div class="option" data='{"value":"Juhasztanya","state":"Tolna"}'>Juhasztanya</div>
<div class="option" data='{"value":"Juhe","state":"Tolna"}'>Juhe</div>
<div class="option" data='{"value":"Juhepuszta","state":"Tolna"}'>Juhepuszta</div>
<div class="option" data='{"value":"Juliamajor","state":"Tolna"}'>Juliamajor</div>
<div class="option" data='{"value":"Kajdacs","state":"Tolna"}'>Kajdacs</div>
<div class="option" data='{"value":"Kajmadpuszta","state":"Tolna"}'>Kajmadpuszta</div>
<div class="option" data='{"value":"Kakasd","state":"Tolna"}'>Kakasd</div>
<div class="option" data='{"value":"Kakaso","state":"Tolna"}'>Kakaso</div>
<div class="option" data='{"value":"Kalazno","state":"Tolna"}'>Kalazno</div>
<div class="option" data='{"value":"Kalaznopuszta","state":"Tolna"}'>Kalaznopuszta</div>
<div class="option" data='{"value":"Kalvaria","state":"Tolna"}'>Kalvaria</div>
<div class="option" data='{"value":"Kaposszekcso","state":"Tolna"}'>Kaposszekcso</div>
<div class="option" data='{"value":"Karasz","state":"Tolna"}'>Karasz</div>
<div class="option" data='{"value":"Katalin","state":"Tolna"}'>Katalin</div>
<div class="option" data='{"value":"Katalinpuszta","state":"Tolna"}'>Katalinpuszta</div>
<div class="option" data='{"value":"Kecsege","state":"Tolna"}'>Kecsege</div>
<div class="option" data='{"value":"Kecsegepuszta","state":"Tolna"}'>Kecsegepuszta</div>
<div class="option" data='{"value":"Kecskespuszta","state":"Tolna"}'>Kecskespuszta</div>
<div class="option" data='{"value":"Kecskesziget","state":"Tolna"}'>Kecskesziget</div>
<div class="option" data='{"value":"Kendergyar","state":"Tolna"}'>Kendergyar</div>
<div class="option" data='{"value":"Kendergyartelep","state":"Tolna"}'>Kendergyartelep</div>
<div class="option" data='{"value":"Keresztvolgyi Puszta","state":"Tolna"}'>Keresztvolgyi Puszta</div>
<div class="option" data='{"value":"Kerikereszt","state":"Tolna"}'>Kerikereszt</div>
<div class="option" data='{"value":"Kesello","state":"Tolna"}'>Kesello</div>
<div class="option" data='{"value":"Kesellodulo","state":"Tolna"}'>Kesellodulo</div>
<div class="option" data='{"value":"Keszohidegkut","state":"Tolna"}'>Keszohidegkut</div>
<div class="option" data='{"value":"Kety","state":"Tolna"}'>Kety</div>
<div class="option" data='{"value":"Khontanya","state":"Tolna"}'>Khontanya</div>
<div class="option" data='{"value":"Kisag","state":"Tolna"}'>Kisag</div>
<div class="option" data='{"value":"Kisbaranya","state":"Tolna"}'>Kisbaranya</div>
<div class="option" data='{"value":"Kisbukk","state":"Tolna"}'>Kisbukk</div>
<div class="option" data='{"value":"Kisder","state":"Tolna"}'>Kisder</div>
<div class="option" data='{"value":"Kisdorog","state":"Tolna"}'>Kisdorog</div>
<div class="option" data='{"value":"Kiserdo","state":"Tolna"}'>Kiserdo</div>
<div class="option" data='{"value":"Kiserdopuszta","state":"Tolna"}'>Kiserdopuszta</div>
<div class="option" data='{"value":"Kishegy","state":"Tolna"}'>Kishegy</div>
<div class="option" data='{"value":"Kishenye","state":"Tolna"}'>Kishenye</div>
<div class="option" data='{"value":"Kishidja","state":"Tolna"}'>Kishidja</div>
<div class="option" data='{"value":"Kiskajdacs","state":"Tolna"}'>Kiskajdacs</div>
<div class="option" data='{"value":"Kiskonda","state":"Tolna"}'>Kiskonda</div>
<div class="option" data='{"value":"Kiskoz","state":"Tolna"}'>Kiskoz</div>
<div class="option" data='{"value":"Kismalom","state":"Tolna"}'>Kismalom</div>
<div class="option" data='{"value":"Kismanyok","state":"Tolna"}'>Kismanyok</div>
<div class="option" data='{"value":"Kismoragy","state":"Tolna"}'>Kismoragy</div>
<div class="option" data='{"value":"Kispalank","state":"Tolna"}'>Kispalank</div>
<div class="option" data='{"value":"Kispalankpuszta","state":"Tolna"}'>Kispalankpuszta</div>
<div class="option" data='{"value":"Kispilis","state":"Tolna"}'>Kispilis</div>
<div class="option" data='{"value":"Kispuszta","state":"Tolna"}'>Kispuszta</div>
<div class="option" data='{"value":"Kisszekely","state":"Tolna"}'>Kisszekely</div>
<div class="option" data='{"value":"Kissziget","state":"Tolna"}'>Kissziget</div>
<div class="option" data='{"value":"Kistabod","state":"Tolna"}'>Kistabod</div>
<div class="option" data='{"value":"Kistape","state":"Tolna"}'>Kistape</div>
<div class="option" data='{"value":"Kistava","state":"Tolna"}'>Kistava</div>
<div class="option" data='{"value":"Kistavapuszta","state":"Tolna"}'>Kistavapuszta</div>
<div class="option" data='{"value":"Kistormas","state":"Tolna"}'>Kistormas</div>
<div class="option" data='{"value":"Kisvejke","state":"Tolna"}'>Kisvejke</div>
<div class="option" data='{"value":"Kobakhegy","state":"Tolna"}'>Kobakhegy</div>
<div class="option" data='{"value":"Kochpuszta","state":"Tolna"}'>Kochpuszta</div>
<div class="option" data='{"value":"Kocsola","state":"Tolna"}'>Kocsola</div>
<div class="option" data='{"value":"Kocsolai Tanya","state":"Tolna"}'>Kocsolai Tanya</div>
<div class="option" data='{"value":"Kohntanya","state":"Tolna"}'>Kohntanya</div>
<div class="option" data='{"value":"Kokut","state":"Tolna"}'>Kokut</div>
<div class="option" data='{"value":"Kolesd","state":"Tolna"}'>Kolesd</div>
<div class="option" data='{"value":"Kolesdimajor","state":"Tolna"}'>Kolesdimajor</div>
<div class="option" data='{"value":"Koleszartanya","state":"Tolna"}'>Koleszartanya</div>
<div class="option" data='{"value":"Koppanyszanto","state":"Tolna"}'>Koppanyszanto</div>
<div class="option" data='{"value":"Kormadpuszta","state":"Tolna"}'>Kormadpuszta</div>
<div class="option" data='{"value":"Kormo","state":"Tolna"}'>Kormo</div>
<div class="option" data='{"value":"Kormodpuszta","state":"Tolna"}'>Kormodpuszta</div>
<div class="option" data='{"value":"Korosztvolgy","state":"Tolna"}'>Korosztvolgy</div>
<div class="option" data='{"value":"Kosba","state":"Tolna"}'>Kosba</div>
<div class="option" data='{"value":"Kovacsmajor","state":"Tolna"}'>Kovacsmajor</div>
<div class="option" data='{"value":"Kovesd","state":"Tolna"}'>Kovesd</div>
<div class="option" data='{"value":"Kovesdpuszta","state":"Tolna"}'>Kovesdpuszta</div>
<div class="option" data='{"value":"Kozepbikad","state":"Tolna"}'>Kozepbikad</div>
<div class="option" data='{"value":"Kozephard","state":"Tolna"}'>Kozephard</div>
<div class="option" data='{"value":"Kozephidveg","state":"Tolna"}'>Kozephidveg</div>
<div class="option" data='{"value":"Kozephomokerdo","state":"Tolna"}'>Kozephomokerdo</div>
<div class="option" data='{"value":"Kozepret","state":"Tolna"}'>Kozepret</div>
<div class="option" data='{"value":"Kozeptabod","state":"Tolna"}'>Kozeptabod</div>
<div class="option" data='{"value":"Kozsegkert","state":"Tolna"}'>Kozsegkert</div>
<div class="option" data='{"value":"Kukuk","state":"Tolna"}'>Kukuk</div>
<div class="option" data='{"value":"Kulcsarmajor","state":"Tolna"}'>Kulcsarmajor</div>
<div class="option" data='{"value":"Kulmajor","state":"Tolna"}'>Kulmajor</div>
<div class="option" data='{"value":"Kurd","state":"Tolna"}'>Kurd</div>
<div class="option" data='{"value":"Kurzhegy","state":"Tolna"}'>Kurzhegy</div>
<div class="option" data='{"value":"Ladomany","state":"Tolna"}'>Ladomany</div>
<div class="option" data='{"value":"Lajosmajor","state":"Tolna"}'>Lajosmajor</div>
<div class="option" data='{"value":"Lajver","state":"Tolna"}'>Lajver</div>
<div class="option" data='{"value":"Lajverpuszta","state":"Tolna"}'>Lajverpuszta</div>
<div class="option" data='{"value":"Lapafo","state":"Tolna"}'>Lapafo</div>
<div class="option" data='{"value":"Lapisto","state":"Tolna"}'>Lapisto</div>
<div class="option" data='{"value":"Lassi","state":"Tolna"}'>Lassi</div>
<div class="option" data='{"value":"Laszlomajor","state":"Tolna"}'>Laszlomajor</div>
<div class="option" data='{"value":"Leanyvar","state":"Tolna"}'>Leanyvar</div>
<div class="option" data='{"value":"Ledneckipuszta","state":"Tolna"}'>Ledneckipuszta</div>
<div class="option" data='{"value":"Ledneczkipuszta","state":"Tolna"}'>Ledneczkipuszta</div>
<div class="option" data='{"value":"Lengyel","state":"Tolna"}'>Lengyel</div>
<div class="option" data='{"value":"Leokadiapuszta","state":"Tolna"}'>Leokadiapuszta</div>
<div class="option" data='{"value":"Leokadipuszta","state":"Tolna"}'>Leokadipuszta</div>
<div class="option" data='{"value":"Leperd","state":"Tolna"}'>Leperd</div>
<div class="option" data='{"value":"Leperdpuszta","state":"Tolna"}'>Leperdpuszta</div>
<div class="option" data='{"value":"Lepomalom","state":"Tolna"}'>Lepomalom</div>
<div class="option" data='{"value":"Lepotya","state":"Tolna"}'>Lepotya</div>
<div class="option" data='{"value":"Lhjosmajor","state":"Tolna"}'>Lhjosmajor</div>
<div class="option" data='{"value":"Lisztes","state":"Tolna"}'>Lisztes</div>
<div class="option" data='{"value":"Lohegy","state":"Tolna"}'>Lohegy</div>
<div class="option" data='{"value":"Lohegypuszta","state":"Tolna"}'>Lohegypuszta</div>
<div class="option" data='{"value":"Ludmillapuszta","state":"Tolna"}'>Ludmillapuszta</div>
<div class="option" data='{"value":"Madocsa","state":"Tolna"}'>Madocsa</div>
<div class="option" data='{"value":"Magyari","state":"Tolna"}'>Magyari</div>
<div class="option" data='{"value":"Magyaripuszta","state":"Tolna"}'>Magyaripuszta</div>
<div class="option" data='{"value":"Magyarkeszi","state":"Tolna"}'>Magyarkeszi</div>
<div class="option" data='{"value":"Magyva","state":"Tolna"}'>Magyva</div>
<div class="option" data='{"value":"Majos","state":"Tolna"}'>Majos</div>
<div class="option" data='{"value":"Majsamiklosvar","state":"Tolna"}'>Majsamiklosvar</div>
<div class="option" data='{"value":"Majsapuszta","state":"Tolna"}'>Majsapuszta</div>
<div class="option" data='{"value":"Malomfa","state":"Tolna"}'>Malomfa</div>
<div class="option" data='{"value":"Marczpuszta","state":"Tolna"}'>Marczpuszta</div>
<div class="option" data='{"value":"Margitmajor","state":"Tolna"}'>Margitmajor</div>
<div class="option" data='{"value":"Mariamajor","state":"Tolna"}'>Mariamajor</div>
<div class="option" data='{"value":"Mariatelep","state":"Tolna"}'>Mariatelep</div>
<div class="option" data='{"value":"Martinca","state":"Tolna"}'>Martinca</div>
<div class="option" data='{"value":"Maszlony","state":"Tolna"}'>Maszlony</div>
<div class="option" data='{"value":"Matildhegy","state":"Tolna"}'>Matildhegy</div>
<div class="option" data='{"value":"Matildmajor","state":"Tolna"}'>Matildmajor</div>
<div class="option" data='{"value":"Matildpuszta","state":"Tolna"}'>Matildpuszta</div>
<div class="option" data='{"value":"Matildsargahaz","state":"Tolna"}'>Matildsargahaz</div>
<div class="option" data='{"value":"Mazsolashat","state":"Tolna"}'>Mazsolashat</div>
<div class="option" data='{"value":"Medina","state":"Tolna"}'>Medina</div>
<div class="option" data='{"value":"Mehesek","state":"Tolna"}'>Mehesek</div>
<div class="option" data='{"value":"Mihalydomb","state":"Tolna"}'>Mihalydomb</div>
<div class="option" data='{"value":"Miklitanya","state":"Tolna"}'>Miklitanya</div>
<div class="option" data='{"value":"Miklosmajor","state":"Tolna"}'>Miklosmajor</div>
<div class="option" data='{"value":"Miklostanya","state":"Tolna"}'>Miklostanya</div>
<div class="option" data='{"value":"Miklosvar","state":"Tolna"}'>Miklosvar</div>
<div class="option" data='{"value":"Miszla","state":"Tolna"}'>Miszla</div>
<div class="option" data='{"value":"Mocfa","state":"Tolna"}'>Mocfa</div>
<div class="option" data='{"value":"Mocfa Csarda","state":"Tolna"}'>Mocfa Csarda</div>
<div class="option" data='{"value":"Mocseny","state":"Tolna"}'>Mocseny</div>
<div class="option" data='{"value":"Mohartelek","state":"Tolna"}'>Mohartelek</div>
<div class="option" data='{"value":"Molnartanya","state":"Tolna"}'>Molnartanya</div>
<div class="option" data='{"value":"Moragy","state":"Tolna"}'>Moragy</div>
<div class="option" data='{"value":"Mozs","state":"Tolna"}'>Mozs</div>
<div class="option" data='{"value":"Mozsi Tanyak","state":"Tolna"}'>Mozsi Tanyak</div>
<div class="option" data='{"value":"Mozsola","state":"Tolna"}'>Mozsola</div>
<div class="option" data='{"value":"Mucsfa","state":"Tolna"}'>Mucsfa</div>
<div class="option" data='{"value":"Mucsi","state":"Tolna"}'>Mucsi</div>
<div class="option" data='{"value":"Murga","state":"Tolna"}'>Murga</div>
<div class="option" data='{"value":"Nadlas","state":"Tolna"}'>Nadlas</div>
<div class="option" data='{"value":"Nagy Pal Telep","state":"Tolna"}'>Nagy Pal Telep</div>
<div class="option" data='{"value":"Nagybaranya","state":"Tolna"}'>Nagybaranya</div>
<div class="option" data='{"value":"Nagydorog","state":"Tolna"}'>Nagydorog</div>
<div class="option" data='{"value":"Nagyhegy","state":"Tolna"}'>Nagyhegy</div>
<div class="option" data='{"value":"Nagykonda","state":"Tolna"}'>Nagykonda</div>
<div class="option" data='{"value":"Nagykonyi","state":"Tolna"}'>Nagykonyi</div>
<div class="option" data='{"value":"Nagymanyok","state":"Tolna"}'>Nagymanyok</div>
<div class="option" data='{"value":"Nagypalankpuszta","state":"Tolna"}'>Nagypalankpuszta</div>
<div class="option" data='{"value":"Nagyszekely","state":"Tolna"}'>Nagyszekely</div>
<div class="option" data='{"value":"Nagyszokoly","state":"Tolna"}'>Nagyszokoly</div>
<div class="option" data='{"value":"Nagyszokolyi Tanyak","state":"Tolna"}'>Nagyszokolyi Tanyak</div>
<div class="option" data='{"value":"Nagytormas","state":"Tolna"}'>Nagytormas</div>
<div class="option" data='{"value":"Nagytormaspuszta","state":"Tolna"}'>Nagytormaspuszta</div>
<div class="option" data='{"value":"Nagyvejke","state":"Tolna"}'>Nagyvejke</div>
<div class="option" data='{"value":"Nak","state":"Tolna"}'>Nak</div>
<div class="option" data='{"value":"Naki Major","state":"Tolna"}'>Naki Major</div>
<div class="option" data='{"value":"Nemedi Ut","state":"Tolna"}'>Nemedi Ut</div>
<div class="option" data='{"value":"Nemedimajor","state":"Tolna"}'>Nemedimajor</div>
<div class="option" data='{"value":"Nemetker","state":"Tolna"}'>Nemetker</div>
<div class="option" data='{"value":"Noszlop","state":"Tolna"}'>Noszlop</div>
<div class="option" data='{"value":"Nosztany","state":"Tolna"}'>Nosztany</div>
<div class="option" data='{"value":"Novakpuszta","state":"Tolna"}'>Novakpuszta</div>
<div class="option" data='{"value":"Nyamand","state":"Tolna"}'>Nyamand</div>
<div class="option" data='{"value":"Nyamandpuszta","state":"Tolna"}'>Nyamandpuszta</div>
<div class="option" data='{"value":"Nyekipuszta","state":"Tolna"}'>Nyekipuszta</div>
<div class="option" data='{"value":"Nyugosgyep","state":"Tolna"}'>Nyugosgyep</div>
<div class="option" data='{"value":"Oberek","state":"Tolna"}'>Oberek</div>
<div class="option" data='{"value":"Oberekpuszta","state":"Tolna"}'>Oberekpuszta</div>
<div class="option" data='{"value":"Obirod","state":"Tolna"}'>Obirod</div>
<div class="option" data='{"value":"Ocseny","state":"Tolna"}'>Ocseny</div>
<div class="option" data='{"value":"Ocsmad","state":"Tolna"}'>Ocsmad</div>
<div class="option" data='{"value":"Ocsmand","state":"Tolna"}'>Ocsmand</div>
<div class="option" data='{"value":"Odalmand","state":"Tolna"}'>Odalmand</div>
<div class="option" data='{"value":"Odany","state":"Tolna"}'>Odany</div>
<div class="option" data='{"value":"Odanypuszta","state":"Tolna"}'>Odanypuszta</div>
<div class="option" data='{"value":"Ohegy","state":"Tolna"}'>Ohegy</div>
<div class="option" data='{"value":"Okraddulo","state":"Tolna"}'>Okraddulo</div>
<div class="option" data='{"value":"Okradi Puszta","state":"Tolna"}'>Okradi Puszta</div>
<div class="option" data='{"value":"Okradpuszta","state":"Tolna"}'>Okradpuszta</div>
<div class="option" data='{"value":"Oltovany","state":"Tolna"}'>Oltovany</div>
<div class="option" data='{"value":"Onana","state":"Tolna"}'>Onana</div>
<div class="option" data='{"value":"Oncsatelep","state":"Tolna"}'>Oncsatelep</div>
<div class="option" data='{"value":"Orbo","state":"Tolna"}'>Orbo</div>
<div class="option" data='{"value":"Orbopuszta","state":"Tolna"}'>Orbopuszta</div>
<div class="option" data='{"value":"Ordogmalom","state":"Tolna"}'>Ordogmalom</div>
<div class="option" data='{"value":"Ordogmalompuszta","state":"Tolna"}'>Ordogmalompuszta</div>
<div class="option" data='{"value":"Oregerdo","state":"Tolna"}'>Oregerdo</div>
<div class="option" data='{"value":"Oreghegy","state":"Tolna"}'>Oreghegy</div>
<div class="option" data='{"value":"Oreghenye","state":"Tolna"}'>Oreghenye</div>
<div class="option" data='{"value":"Oregsziget","state":"Tolna"}'>Oregsziget</div>
<div class="option" data='{"value":"Oregvajka","state":"Tolna"}'>Oregvajka</div>
<div class="option" data='{"value":"Ornagybirtok","state":"Tolna"}'>Ornagybirtok</div>
<div class="option" data='{"value":"Orsihegy","state":"Tolna"}'>Orsihegy</div>
<div class="option" data='{"value":"Orszagutdulo","state":"Tolna"}'>Orszagutdulo</div>
<div class="option" data='{"value":"Osakpuszta","state":"Tolna"}'>Osakpuszta</div>
<div class="option" data='{"value":"Otvospuszta","state":"Tolna"}'>Otvospuszta</div>
<div class="option" data='{"value":"Otvostanya","state":"Tolna"}'>Otvostanya</div>
<div class="option" data='{"value":"Ozora","state":"Tolna"}'>Ozora</div>
<div class="option" data='{"value":"Ozors","state":"Tolna"}'>Ozors</div>
<div class="option" data='{"value":"Pacanydulo","state":"Tolna"}'>Pacanydulo</div>
<div class="option" data='{"value":"Paks","state":"Tolna"}'>Paks</div>
<div class="option" data='{"value":"Palankihegy","state":"Tolna"}'>Palankihegy</div>
<div class="option" data='{"value":"Palatinca","state":"Tolna"}'>Palatinca</div>
<div class="option" data='{"value":"Palfa","state":"Tolna"}'>Palfa</div>
<div class="option" data='{"value":"Papd","state":"Tolna"}'>Papd</div>
<div class="option" data='{"value":"Papptanya","state":"Tolna"}'>Papptanya</div>
<div class="option" data='{"value":"Pappuszta","state":"Tolna"}'>Pappuszta</div>
<div class="option" data='{"value":"Paptava","state":"Tolna"}'>Paptava</div>
<div class="option" data='{"value":"Paradicsompuszta","state":"Tolna"}'>Paradicsompuszta</div>
<div class="option" data='{"value":"Pari","state":"Tolna"}'>Pari</div>
<div class="option" data='{"value":"Parraghegy","state":"Tolna"}'>Parraghegy</div>
<div class="option" data='{"value":"Partalja","state":"Tolna"}'>Partalja</div>
<div class="option" data='{"value":"Paskom","state":"Tolna"}'>Paskom</div>
<div class="option" data='{"value":"Paskum","state":"Tolna"}'>Paskum</div>
<div class="option" data='{"value":"Patkanyos","state":"Tolna"}'>Patkanyos</div>
<div class="option" data='{"value":"Pincehely","state":"Tolna"}'>Pincehely</div>
<div class="option" data='{"value":"Pincesor","state":"Tolna"}'>Pincesor</div>
<div class="option" data='{"value":"Plannerdok","state":"Tolna"}'>Plannerdok</div>
<div class="option" data='{"value":"Poganyvar","state":"Tolna"}'>Poganyvar</div>
<div class="option" data='{"value":"Porbol","state":"Tolna"}'>Porbol</div>
<div class="option" data='{"value":"Porboly","state":"Tolna"}'>Porboly</div>
<div class="option" data='{"value":"Porkolabvolgy","state":"Tolna"}'>Porkolabvolgy</div>
<div class="option" data='{"value":"Poszesugo","state":"Tolna"}'>Poszesugo</div>
<div class="option" data='{"value":"Potlek","state":"Tolna"}'>Potlek</div>
<div class="option" data='{"value":"Pusztaapati","state":"Tolna"}'>Pusztaapati</div>
<div class="option" data='{"value":"Pusztadorog","state":"Tolna"}'>Pusztadorog</div>
<div class="option" data='{"value":"Pusztafacankert","state":"Tolna"}'>Pusztafacankert</div>
<div class="option" data='{"value":"Pusztahencse","state":"Tolna"}'>Pusztahencse</div>
<div class="option" data='{"value":"Pusztakajmad","state":"Tolna"}'>Pusztakajmad</div>
<div class="option" data='{"value":"Pusztakalazno","state":"Tolna"}'>Pusztakalazno</div>
<div class="option" data='{"value":"Rackeresztdulo","state":"Tolna"}'>Rackeresztdulo</div>
<div class="option" data='{"value":"Racvolgy","state":"Tolna"}'>Racvolgy</div>
<div class="option" data='{"value":"Regivagohid","state":"Tolna"}'>Regivagohid</div>
<div class="option" data='{"value":"Regoly","state":"Tolna"}'>Regoly</div>
<div class="option" data='{"value":"Rekettyepuszta","state":"Tolna"}'>Rekettyepuszta</div>
<div class="option" data='{"value":"Revesztanya","state":"Tolna"}'>Revesztanya</div>
<div class="option" data='{"value":"Rigotanya","state":"Tolna"}'>Rigotanya</div>
<div class="option" data='{"value":"Rolzmalom","state":"Tolna"}'>Rolzmalom</div>
<div class="option" data='{"value":"Rothpuszta","state":"Tolna"}'>Rothpuszta</div>
<div class="option" data='{"value":"Rovidvolgy","state":"Tolna"}'>Rovidvolgy</div>
<div class="option" data='{"value":"Rozsamaj","state":"Tolna"}'>Rozsamaj</div>
<div class="option" data='{"value":"Rozsdasserpenyo","state":"Tolna"}'>Rozsdasserpenyo</div>
<div class="option" data='{"value":"Rudolfmajor","state":"Tolna"}'>Rudolfmajor</div>
<div class="option" data='{"value":"Ruzsaberek","state":"Tolna"}'>Ruzsaberek</div>
<div class="option" data='{"value":"Sag","state":"Tolna"}'>Sag</div>
<div class="option" data='{"value":"Sagalja","state":"Tolna"}'>Sagalja</div>
<div class="option" data='{"value":"Saghegy","state":"Tolna"}'>Saghegy</div>
<div class="option" data='{"value":"Sagpuszta","state":"Tolna"}'>Sagpuszta</div>
<div class="option" data='{"value":"Sanc","state":"Tolna"}'>Sanc</div>
<div class="option" data='{"value":"Sandorhat","state":"Tolna"}'>Sandorhat</div>
<div class="option" data='{"value":"Sandormajor","state":"Tolna"}'>Sandormajor</div>
<div class="option" data='{"value":"Sarallas","state":"Tolna"}'>Sarallas</div>
<div class="option" data='{"value":"Sarmanpuszta","state":"Tolna"}'>Sarmanpuszta</div>
<div class="option" data='{"value":"Sarmezo","state":"Tolna"}'>Sarmezo</div>
<div class="option" data='{"value":"Sarosdulo","state":"Tolna"}'>Sarosdulo</div>
<div class="option" data='{"value":"Sarpilis","state":"Tolna"}'>Sarpilis</div>
<div class="option" data='{"value":"Sarszentlorinc","state":"Tolna"}'>Sarszentlorinc</div>
<div class="option" data='{"value":"Sasos","state":"Tolna"}'>Sasos</div>
<div class="option" data='{"value":"Schranzbergdulo","state":"Tolna"}'>Schranzbergdulo</div>
<div class="option" data='{"value":"Simonmajor","state":"Tolna"}'>Simonmajor</div>
<div class="option" data='{"value":"Simontornya","state":"Tolna"}'>Simontornya</div>
<div class="option" data='{"value":"Sioagard","state":"Tolna"}'>Sioagard</div>
<div class="option" data='{"value":"Sipsa","state":"Tolna"}'>Sipsa</div>
<div class="option" data='{"value":"Sipsadulo","state":"Tolna"}'>Sipsadulo</div>
<div class="option" data='{"value":"Solosimalom","state":"Tolna"}'>Solosimalom</div>
<div class="option" data='{"value":"Somoshegy","state":"Tolna"}'>Somoshegy</div>
<div class="option" data='{"value":"Spargahaz","state":"Tolna"}'>Spargahaz</div>
<div class="option" data='{"value":"Staukert","state":"Tolna"}'>Staukert</div>
<div class="option" data='{"value":"Sutveny","state":"Tolna"}'>Sutveny</div>
<div class="option" data='{"value":"Sutvenypuszta","state":"Tolna"}'>Sutvenypuszta</div>
<div class="option" data='{"value":"Szabaton","state":"Tolna"}'>Szabaton</div>
<div class="option" data='{"value":"Szabatonpuszta","state":"Tolna"}'>Szabatonpuszta</div>
<div class="option" data='{"value":"Szakadat","state":"Tolna"}'>Szakadat</div>
<div class="option" data='{"value":"Szakaly","state":"Tolna"}'>Szakaly</div>
<div class="option" data='{"value":"Szakcsimajor","state":"Tolna"}'>Szakcsimajor</div>
<div class="option" data='{"value":"Szakes","state":"Tolna"}'>Szakes</div>
<div class="option" data='{"value":"Szalka","state":"Tolna"}'>Szalka</div>
<div class="option" data='{"value":"Szallas","state":"Tolna"}'>Szallas</div>
<div class="option" data='{"value":"Szallaspuszta","state":"Tolna"}'>Szallaspuszta</div>
<div class="option" data='{"value":"Szarazd","state":"Tolna"}'>Szarazd</div>
<div class="option" data='{"value":"Szarkahegy","state":"Tolna"}'>Szarkahegy</div>
<div class="option" data='{"value":"Szarvasd","state":"Tolna"}'>Szarvasd</div>
<div class="option" data='{"value":"Szaszipuszta","state":"Tolna"}'>Szaszipuszta</div>
<div class="option" data='{"value":"Szedres","state":"Tolna"}'>Szedres</div>
<div class="option" data='{"value":"Szedresi Telep","state":"Tolna"}'>Szedresi Telep</div>
<div class="option" data='{"value":"Szekszard","state":"Tolna"}'>Szekszard</div>
<div class="option" data='{"value":"Szelresz","state":"Tolna"}'>Szelresz</div>
<div class="option" data='{"value":"Szelsopoganyvar","state":"Tolna"}'>Szelsopoganyvar</div>
<div class="option" data='{"value":"Szemcse","state":"Tolna"}'>Szemcse</div>
<div class="option" data='{"value":"Szemcsepuszta","state":"Tolna"}'>Szemcsepuszta</div>
<div class="option" data='{"value":"Szentandras","state":"Tolna"}'>Szentandras</div>
<div class="option" data='{"value":"Szentantalhegy","state":"Tolna"}'>Szentantalhegy</div>
<div class="option" data='{"value":"Szentgal","state":"Tolna"}'>Szentgal</div>
<div class="option" data='{"value":"Szentgalpuszta","state":"Tolna"}'>Szentgalpuszta</div>
<div class="option" data='{"value":"Szentgyorgy","state":"Tolna"}'>Szentgyorgy</div>
<div class="option" data='{"value":"Szentistvanhegy","state":"Tolna"}'>Szentistvanhegy</div>
<div class="option" data='{"value":"Szentlaszlohegy","state":"Tolna"}'>Szentlaszlohegy</div>
<div class="option" data='{"value":"Szentmartonpuszta","state":"Tolna"}'>Szentmartonpuszta</div>
<div class="option" data='{"value":"Szentmihalydulo","state":"Tolna"}'>Szentmihalydulo</div>
<div class="option" data='{"value":"Szeptolgyes","state":"Tolna"}'>Szeptolgyes</div>
<div class="option" data='{"value":"Sziget","state":"Tolna"}'>Sziget</div>
<div class="option" data='{"value":"Szilfas","state":"Tolna"}'>Szilfas</div>
<div class="option" data='{"value":"Szluhahard","state":"Tolna"}'>Szluhahard</div>
<div class="option" data='{"value":"Szluhapuszta","state":"Tolna"}'>Szluhapuszta</div>
<div class="option" data='{"value":"Szomfova","state":"Tolna"}'>Szomfova</div>
<div class="option" data='{"value":"Szovetkezetitanya","state":"Tolna"}'>Szovetkezetitanya</div>
<div class="option" data='{"value":"Szucsenyvolgy","state":"Tolna"}'>Szucsenyvolgy</div>
<div class="option" data='{"value":"Szunyogcsarda","state":"Tolna"}'>Szunyogcsarda</div>
<div class="option" data='{"value":"Szurokhegy","state":"Tolna"}'>Szurokhegy</div>
<div class="option" data='{"value":"Tabod","state":"Tolna"}'>Tabod</div>
<div class="option" data='{"value":"Tabodszerdahely","state":"Tolna"}'>Tabodszerdahely</div>
<div class="option" data='{"value":"Tamasi","state":"Tolna"}'>Tamasi</div>
<div class="option" data='{"value":"Tanyavolgy","state":"Tolna"}'>Tanyavolgy</div>
<div class="option" data='{"value":"Tarkany","state":"Tolna"}'>Tarkany</div>
<div class="option" data='{"value":"Tarkanypuszta","state":"Tolna"}'>Tarkanypuszta</div>
<div class="option" data='{"value":"Tarlogyer","state":"Tolna"}'>Tarlogyer</div>
<div class="option" data='{"value":"Telekmajor","state":"Tolna"}'>Telekmajor</div>
<div class="option" data='{"value":"Tenczlingerszallas","state":"Tolna"}'>Tenczlingerszallas</div>
<div class="option" data='{"value":"Tengelic","state":"Tolna"}'>Tengelic</div>
<div class="option" data='{"value":"Tevel","state":"Tolna"}'>Tevel</div>
<div class="option" data='{"value":"Tokosremete","state":"Tolna"}'>Tokosremete</div>
<div class="option" data='{"value":"Tolma","state":"Tolna"}'>Tolma</div>
<div class="option" data='{"value":"Tolna","state":"Tolna"}'>Tolna</div>
<div class="option" data='{"value":"Tolna County","state":"Tolna"}'>Tolna County</div>
<div class="option" data='{"value":"Tolna Megye","state":"Tolna"}'>Tolna Megye</div>
<div class="option" data='{"value":"Tolnaitanyak","state":"Tolna"}'>Tolnaitanyak</div>
<div class="option" data='{"value":"Tolnanemedi","state":"Tolna"}'>Tolnanemedi</div>
<div class="option" data='{"value":"Tomorpuszta","state":"Tolna"}'>Tomorpuszta</div>
<div class="option" data='{"value":"Totvolgy","state":"Tolna"}'>Totvolgy</div>
<div class="option" data='{"value":"Tukormajor","state":"Tolna"}'>Tukormajor</div>
<div class="option" data='{"value":"Tuladuna","state":"Tolna"}'>Tuladuna</div>
<div class="option" data='{"value":"Tuladunadulo","state":"Tolna"}'>Tuladunadulo</div>
<div class="option" data='{"value":"Tuladunatanya","state":"Tolna"}'>Tuladunatanya</div>
<div class="option" data='{"value":"Tuske","state":"Tolna"}'>Tuske</div>
<div class="option" data='{"value":"Tusko","state":"Tolna"}'>Tusko</div>
<div class="option" data='{"value":"Tuskos","state":"Tolna"}'>Tuskos</div>
<div class="option" data='{"value":"Udvari","state":"Tolna"}'>Udvari</div>
<div class="option" data='{"value":"Ugrocz","state":"Tolna"}'>Ugrocz</div>
<div class="option" data='{"value":"Ujaladar","state":"Tolna"}'>Ujaladar</div>
<div class="option" data='{"value":"Ujberek","state":"Tolna"}'>Ujberek</div>
<div class="option" data='{"value":"Ujberekpuszta","state":"Tolna"}'>Ujberekpuszta</div>
<div class="option" data='{"value":"Ujbirod","state":"Tolna"}'>Ujbirod</div>
<div class="option" data='{"value":"Ujborjad","state":"Tolna"}'>Ujborjad</div>
<div class="option" data='{"value":"Ujdalmand","state":"Tolna"}'>Ujdalmand</div>
<div class="option" data='{"value":"Ujdombovar","state":"Tolna"}'>Ujdombovar</div>
<div class="option" data='{"value":"Ujfalu","state":"Tolna"}'>Ujfalu</div>
<div class="option" data='{"value":"Ujfokitanya","state":"Tolna"}'>Ujfokitanya</div>
<div class="option" data='{"value":"Ujhegy","state":"Tolna"}'>Ujhegy</div>
<div class="option" data='{"value":"Ujireg","state":"Tolna"}'>Ujireg</div>
<div class="option" data='{"value":"Ujmajor","state":"Tolna"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujtelep","state":"Tolna"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujvarhegy","state":"Tolna"}'>Ujvarhegy</div>
<div class="option" data='{"value":"Ujvolgy","state":"Tolna"}'>Ujvolgy</div>
<div class="option" data='{"value":"Urgevar","state":"Tolna"}'>Urgevar</div>
<div class="option" data='{"value":"Urgevarpuszta","state":"Tolna"}'>Urgevarpuszta</div>
<div class="option" data='{"value":"Utorhaz","state":"Tolna"}'>Utorhaz</div>
<div class="option" data='{"value":"Uveghuta","state":"Tolna"}'>Uveghuta</div>
<div class="option" data='{"value":"Vadaszmajor","state":"Tolna"}'>Vadaszmajor</div>
<div class="option" data='{"value":"Vadkert","state":"Tolna"}'>Vadkert</div>
<div class="option" data='{"value":"Vajertanya","state":"Tolna"}'>Vajertanya</div>
<div class="option" data='{"value":"Vajka","state":"Tolna"}'>Vajka</div>
<div class="option" data='{"value":"Vajkapuszta","state":"Tolna"}'>Vajkapuszta</div>
<div class="option" data='{"value":"Varad","state":"Tolna"}'>Varad</div>
<div class="option" data='{"value":"Varalja","state":"Tolna"}'>Varalja</div>
<div class="option" data='{"value":"Vardomb","state":"Tolna"}'>Vardomb</div>
<div class="option" data='{"value":"Varhegy","state":"Tolna"}'>Varhegy</div>
<div class="option" data='{"value":"Varong","state":"Tolna"}'>Varong</div>
<div class="option" data='{"value":"Varsad","state":"Tolna"}'>Varsad</div>
<div class="option" data='{"value":"Varszeg","state":"Tolna"}'>Varszeg</div>
<div class="option" data='{"value":"Vasarter","state":"Tolna"}'>Vasarter</div>
<div class="option" data='{"value":"Vetlepuszta","state":"Tolna"}'>Vetlepuszta</div>
<div class="option" data='{"value":"Vettlepuszta","state":"Tolna"}'>Vettlepuszta</div>
<div class="option" data='{"value":"Villanytelep","state":"Tolna"}'>Villanytelep</div>
<div class="option" data='{"value":"Vilmosmajor","state":"Tolna"}'>Vilmosmajor</div>
<div class="option" data='{"value":"Vitezitelek","state":"Tolna"}'>Vitezitelek</div>
<div class="option" data='{"value":"Vorosegyhaz","state":"Tolna"}'>Vorosegyhaz</div>
<div class="option" data='{"value":"Vorosegyhaza","state":"Tolna"}'>Vorosegyhaza</div>
<div class="option" data='{"value":"Voroskeresztdulo","state":"Tolna"}'>Voroskeresztdulo</div>
<div class="option" data='{"value":"Walterhaz","state":"Tolna"}'>Walterhaz</div>
<div class="option" data='{"value":"Zacskomajor","state":"Tolna"}'>Zacskomajor</div>
<div class="option" data='{"value":"Zardoka","state":"Tolna"}'>Zardoka</div>
<div class="option" data='{"value":"Zavod","state":"Tolna"}'>Zavod</div>
<div class="option" data='{"value":"Zomba","state":"Tolna"}'>Zomba</div>
<div class="option" id="option_end" data='{"value":"Zsibrik","state":"Tolna"}'>Zsibrik</div>

