<div class="option" data='{"value":"Aba","state":"Fejer"}'>Aba</div>
<div class="option" data='{"value":"Adony","state":"Fejer"}'>Adony</div>
<div class="option" data='{"value":"Agard","state":"Fejer"}'>Agard</div>
<div class="option" data='{"value":"Agardi Villatelep","state":"Fejer"}'>Agardi Villatelep</div>
<div class="option" data='{"value":"Agardpuszta","state":"Fejer"}'>Agardpuszta</div>
<div class="option" data='{"value":"Aggszentpeter","state":"Fejer"}'>Aggszentpeter</div>
<div class="option" data='{"value":"Agnesforras","state":"Fejer"}'>Agnesforras</div>
<div class="option" data='{"value":"Agnesmajor","state":"Fejer"}'>Agnesmajor</div>
<div class="option" data='{"value":"Agostmajor","state":"Fejer"}'>Agostmajor</div>
<div class="option" data='{"value":"Agostonpuszta","state":"Fejer"}'>Agostonpuszta</div>
<div class="option" data='{"value":"Akohegy","state":"Fejer"}'>Akohegy</div>
<div class="option" data='{"value":"Aladarmajor","state":"Fejer"}'>Aladarmajor</div>
<div class="option" data='{"value":"Alajarodulo","state":"Fejer"}'>Alajarodulo</div>
<div class="option" data='{"value":"Alajaroduloi Tanyak","state":"Fejer"}'>Alajaroduloi Tanyak</div>
<div class="option" data='{"value":"Alap","state":"Fejer"}'>Alap</div>
<div class="option" data='{"value":"Alapi Resz","state":"Fejer"}'>Alapi Resz</div>
<div class="option" data='{"value":"Alcsut","state":"Fejer"}'>Alcsut</div>
<div class="option" data='{"value":"Alcsutdoboz","state":"Fejer"}'>Alcsutdoboz</div>
<div class="option" data='{"value":"Aligvaromtelep","state":"Fejer"}'>Aligvaromtelep</div>
<div class="option" data='{"value":"Almajor","state":"Fejer"}'>Almajor</div>
<div class="option" data='{"value":"Alsobesnyo","state":"Fejer"}'>Alsobesnyo</div>
<div class="option" data='{"value":"Alsobogardpuszta","state":"Fejer"}'>Alsobogardpuszta</div>
<div class="option" data='{"value":"Alsocikola","state":"Fejer"}'>Alsocikola</div>
<div class="option" data='{"value":"Alsodobos","state":"Fejer"}'>Alsodobos</div>
<div class="option" data='{"value":"Alsogajdimalom","state":"Fejer"}'>Alsogajdimalom</div>
<div class="option" data='{"value":"Alsohangos","state":"Fejer"}'>Alsohangos</div>
<div class="option" data='{"value":"Alsohatartanyak","state":"Fejer"}'>Alsohatartanyak</div>
<div class="option" data='{"value":"Alsohegy","state":"Fejer"}'>Alsohegy</div>
<div class="option" data='{"value":"Alsokispuszta","state":"Fejer"}'>Alsokispuszta</div>
<div class="option" data='{"value":"Alsokortvelyes","state":"Fejer"}'>Alsokortvelyes</div>
<div class="option" data='{"value":"Alsomalom","state":"Fejer"}'>Alsomalom</div>
<div class="option" data='{"value":"Alsomenyod","state":"Fejer"}'>Alsomenyod</div>
<div class="option" data='{"value":"Alsomenyodpuszta","state":"Fejer"}'>Alsomenyodpuszta</div>
<div class="option" data='{"value":"Alsoorspuszta","state":"Fejer"}'>Alsoorspuszta</div>
<div class="option" data='{"value":"Alsopuszta","state":"Fejer"}'>Alsopuszta</div>
<div class="option" data='{"value":"Alsosomlyo","state":"Fejer"}'>Alsosomlyo</div>
<div class="option" data='{"value":"Alsoszentivan","state":"Fejer"}'>Alsoszentivan</div>
<div class="option" data='{"value":"Alsoteglahaz","state":"Fejer"}'>Alsoteglahaz</div>
<div class="option" data='{"value":"Alsotekeres","state":"Fejer"}'>Alsotekeres</div>
<div class="option" data='{"value":"Alsotoborzsok","state":"Fejer"}'>Alsotoborzsok</div>
<div class="option" data='{"value":"Aluminiumercbanyatelep","state":"Fejer"}'>Aluminiumercbanyatelep</div>
<div class="option" data='{"value":"Alvegi Tanya","state":"Fejer"}'>Alvegi Tanya</div>
<div class="option" data='{"value":"Andormajor","state":"Fejer"}'>Andormajor</div>
<div class="option" data='{"value":"Annamajor","state":"Fejer"}'>Annamajor</div>
<div class="option" data='{"value":"Annatanya","state":"Fejer"}'>Annatanya</div>
<div class="option" data='{"value":"Antalmajor","state":"Fejer"}'>Antalmajor</div>
<div class="option" data='{"value":"Antoniamajor","state":"Fejer"}'>Antoniamajor</div>
<div class="option" data='{"value":"Aranyhegy","state":"Fejer"}'>Aranyhegy</div>
<div class="option" data='{"value":"Aranyospuszta","state":"Fejer"}'>Aranyospuszta</div>
<div class="option" data='{"value":"Arkipuszta","state":"Fejer"}'>Arkipuszta</div>
<div class="option" data='{"value":"Arkitanya","state":"Fejer"}'>Arkitanya</div>
<div class="option" data='{"value":"Attilapuszta","state":"Fejer"}'>Attilapuszta</div>
<div class="option" data='{"value":"Atya","state":"Fejer"}'>Atya</div>
<div class="option" data='{"value":"Atyamajor","state":"Fejer"}'>Atyamajor</div>
<div class="option" data='{"value":"Bacs","state":"Fejer"}'>Bacs</div>
<div class="option" data='{"value":"Bacskai Tanyak","state":"Fejer"}'>Bacskai Tanyak</div>
<div class="option" data='{"value":"Badertanya","state":"Fejer"}'>Badertanya</div>
<div class="option" data='{"value":"Bagolyvar","state":"Fejer"}'>Bagolyvar</div>
<div class="option" data='{"value":"Bagolyvartanya","state":"Fejer"}'>Bagolyvartanya</div>
<div class="option" data='{"value":"Bakonycsernye","state":"Fejer"}'>Bakonycsernye</div>
<div class="option" data='{"value":"Bakonykuti","state":"Fejer"}'>Bakonykuti</div>
<div class="option" data='{"value":"Bakonykuti Puszta","state":"Fejer"}'>Bakonykuti Puszta</div>
<div class="option" data='{"value":"Balassatanya","state":"Fejer"}'>Balassatanya</div>
<div class="option" data='{"value":"Balatonbozsok","state":"Fejer"}'>Balatonbozsok</div>
<div class="option" data='{"value":"Balazstanya","state":"Fejer"}'>Balazstanya</div>
<div class="option" data='{"value":"Balinka","state":"Fejer"}'>Balinka</div>
<div class="option" data='{"value":"Balistanya","state":"Fejer"}'>Balistanya</div>
<div class="option" data='{"value":"Balogtanya","state":"Fejer"}'>Balogtanya</div>
<div class="option" data='{"value":"Banksismand","state":"Fejer"}'>Banksismand</div>
<div class="option" data='{"value":"Banomtelep","state":"Fejer"}'>Banomtelep</div>
<div class="option" data='{"value":"Banyatelep","state":"Fejer"}'>Banyatelep</div>
<div class="option" data='{"value":"Banyavolgy","state":"Fejer"}'>Banyavolgy</div>
<div class="option" data='{"value":"Baracs","state":"Fejer"}'>Baracs</div>
<div class="option" data='{"value":"Baracska","state":"Fejer"}'>Baracska</div>
<div class="option" data='{"value":"Barakapuszta","state":"Fejer"}'>Barakapuszta</div>
<div class="option" data='{"value":"Baranyaszollohegy","state":"Fejer"}'>Baranyaszollohegy</div>
<div class="option" data='{"value":"Baranyjaraspuszta","state":"Fejer"}'>Baranyjaraspuszta</div>
<div class="option" data='{"value":"Baratidulo","state":"Fejer"}'>Baratidulo</div>
<div class="option" data='{"value":"Baratlakaspuszta","state":"Fejer"}'>Baratlakaspuszta</div>
<div class="option" data='{"value":"Barczatanya","state":"Fejer"}'>Barczatanya</div>
<div class="option" data='{"value":"Bariczatanya","state":"Fejer"}'>Bariczatanya</div>
<div class="option" data='{"value":"Becsalipuszta","state":"Fejer"}'>Becsalipuszta</div>
<div class="option" data='{"value":"Bekemajor","state":"Fejer"}'>Bekemajor</div>
<div class="option" data='{"value":"Beketelep","state":"Fejer"}'>Beketelep</div>
<div class="option" data='{"value":"Belamajor","state":"Fejer"}'>Belamajor</div>
<div class="option" data='{"value":"Belapapuszta","state":"Fejer"}'>Belapapuszta</div>
<div class="option" data='{"value":"Belatohegy","state":"Fejer"}'>Belatohegy</div>
<div class="option" data='{"value":"Belmajor","state":"Fejer"}'>Belmajor</div>
<div class="option" data='{"value":"Beloiannisz","state":"Fejer"}'>Beloiannisz</div>
<div class="option" data='{"value":"Belsobarand","state":"Fejer"}'>Belsobarand</div>
<div class="option" data='{"value":"Belsohegy","state":"Fejer"}'>Belsohegy</div>
<div class="option" data='{"value":"Belsokajtor","state":"Fejer"}'>Belsokajtor</div>
<div class="option" data='{"value":"Belsosari","state":"Fejer"}'>Belsosari</div>
<div class="option" data='{"value":"Belsosaripuszta","state":"Fejer"}'>Belsosaripuszta</div>
<div class="option" data='{"value":"Belsoszollohegy","state":"Fejer"}'>Belsoszollohegy</div>
<div class="option" data='{"value":"Belsotukros","state":"Fejer"}'>Belsotukros</div>
<div class="option" data='{"value":"Benditanya","state":"Fejer"}'>Benditanya</div>
<div class="option" data='{"value":"Benedekpuszta","state":"Fejer"}'>Benedekpuszta</div>
<div class="option" data='{"value":"Bereckytanya","state":"Fejer"}'>Bereckytanya</div>
<div class="option" data='{"value":"Berestanya","state":"Fejer"}'>Berestanya</div>
<div class="option" data='{"value":"Berkitanya","state":"Fejer"}'>Berkitanya</div>
<div class="option" data='{"value":"Bernatkut","state":"Fejer"}'>Bernatkut</div>
<div class="option" data='{"value":"Besnyo","state":"Fejer"}'>Besnyo</div>
<div class="option" data='{"value":"Besnyomajor","state":"Fejer"}'>Besnyomajor</div>
<div class="option" data='{"value":"Bevar","state":"Fejer"}'>Bevar</div>
<div class="option" data='{"value":"Bicske","state":"Fejer"}'>Bicske</div>
<div class="option" data='{"value":"Biglitanya","state":"Fejer"}'>Biglitanya</div>
<div class="option" data='{"value":"Biharpuszta","state":"Fejer"}'>Biharpuszta</div>
<div class="option" data='{"value":"Bito","state":"Fejer"}'>Bito</div>
<div class="option" data='{"value":"Bodajk","state":"Fejer"}'>Bodajk</div>
<div class="option" data='{"value":"Bodakajtor","state":"Fejer"}'>Bodakajtor</div>
<div class="option" data='{"value":"Bodmer","state":"Fejer"}'>Bodmer</div>
<div class="option" data='{"value":"Bodritanya","state":"Fejer"}'>Bodritanya</div>
<div class="option" data='{"value":"Bogatanya","state":"Fejer"}'>Bogatanya</div>
<div class="option" data='{"value":"Bognarhaz","state":"Fejer"}'>Bognarhaz</div>
<div class="option" data='{"value":"Bogyatanya","state":"Fejer"}'>Bogyatanya</div>
<div class="option" data='{"value":"Bolgarkert","state":"Fejer"}'>Bolgarkert</div>
<div class="option" data='{"value":"Bolgarkertitanyak","state":"Fejer"}'>Bolgarkertitanyak</div>
<div class="option" data='{"value":"Bolondvaritanya","state":"Fejer"}'>Bolondvaritanya</div>
<div class="option" data='{"value":"Bolvaritanya","state":"Fejer"}'>Bolvaritanya</div>
<div class="option" data='{"value":"Bolvarytanya","state":"Fejer"}'>Bolvarytanya</div>
<div class="option" data='{"value":"Borbalapuszta","state":"Fejer"}'>Borbalapuszta</div>
<div class="option" data='{"value":"Borbelymajor","state":"Fejer"}'>Borbelymajor</div>
<div class="option" data='{"value":"Borgond","state":"Fejer"}'>Borgond</div>
<div class="option" data='{"value":"Boronkaypuszta","state":"Fejer"}'>Boronkaypuszta</div>
<div class="option" data='{"value":"Bot","state":"Fejer"}'>Bot</div>
<div class="option" data='{"value":"Botpuszta","state":"Fejer"}'>Botpuszta</div>
<div class="option" data='{"value":"Buhim","state":"Fejer"}'>Buhim</div>
<div class="option" data='{"value":"Buhinpuszta","state":"Fejer"}'>Buhinpuszta</div>
<div class="option" data='{"value":"Burarihaz","state":"Fejer"}'>Burarihaz</div>
<div class="option" data='{"value":"Busfeketepuszta","state":"Fejer"}'>Busfeketepuszta</div>
<div class="option" data='{"value":"Cece","state":"Fejer"}'>Cece</div>
<div class="option" data='{"value":"Cekustanya","state":"Fejer"}'>Cekustanya</div>
<div class="option" data='{"value":"Cicemalom","state":"Fejer"}'>Cicemalom</div>
<div class="option" data='{"value":"Cicmalom","state":"Fejer"}'>Cicmalom</div>
<div class="option" data='{"value":"Cikola Uti Tanya","state":"Fejer"}'>Cikola Uti Tanya</div>
<div class="option" data='{"value":"Cikolauti Tanyak","state":"Fejer"}'>Cikolauti Tanyak</div>
<div class="option" data='{"value":"Csabdi","state":"Fejer"}'>Csabdi</div>
<div class="option" data='{"value":"Csajkastanya","state":"Fejer"}'>Csajkastanya</div>
<div class="option" data='{"value":"Csakbereny","state":"Fejer"}'>Csakbereny</div>
<div class="option" data='{"value":"Csakvar","state":"Fejer"}'>Csakvar</div>
<div class="option" data='{"value":"Csakyar","state":"Fejer"}'>Csakyar</div>
<div class="option" data='{"value":"Csakytanya","state":"Fejer"}'>Csakytanya</div>
<div class="option" data='{"value":"Csala","state":"Fejer"}'>Csala</div>
<div class="option" data='{"value":"Csalaerdeszlak","state":"Fejer"}'>Csalaerdeszlak</div>
<div class="option" data='{"value":"Csalai Also Malom","state":"Fejer"}'>Csalai Also Malom</div>
<div class="option" data='{"value":"Csalakastely","state":"Fejer"}'>Csalakastely</div>
<div class="option" data='{"value":"Csalamalom","state":"Fejer"}'>Csalamalom</div>
<div class="option" data='{"value":"Csaszartanya","state":"Fejer"}'>Csaszartanya</div>
<div class="option" data='{"value":"Csekelyes","state":"Fejer"}'>Csekelyes</div>
<div class="option" data='{"value":"Csekes","state":"Fejer"}'>Csekes</div>
<div class="option" data='{"value":"Csetenyitanya","state":"Fejer"}'>Csetenyitanya</div>
<div class="option" data='{"value":"Csikotanya","state":"Fejer"}'>Csikotanya</div>
<div class="option" data='{"value":"Csillagmajor","state":"Fejer"}'>Csillagmajor</div>
<div class="option" data='{"value":"Csillagpuszta","state":"Fejer"}'>Csillagpuszta</div>
<div class="option" data='{"value":"Csillagtanya","state":"Fejer"}'>Csillagtanya</div>
<div class="option" data='{"value":"Csillermajor","state":"Fejer"}'>Csillermajor</div>
<div class="option" data='{"value":"Csimatanya","state":"Fejer"}'>Csimatanya</div>
<div class="option" data='{"value":"Csiribmajor","state":"Fejer"}'>Csiribmajor</div>
<div class="option" data='{"value":"Csiribpuszta","state":"Fejer"}'>Csiribpuszta</div>
<div class="option" data='{"value":"Csiripmajor","state":"Fejer"}'>Csiripmajor</div>
<div class="option" data='{"value":"Csokako","state":"Fejer"}'>Csokako</div>
<div class="option" data='{"value":"Csongrad","state":"Fejer"}'>Csongrad</div>
<div class="option" data='{"value":"Csontospuszta","state":"Fejer"}'>Csontospuszta</div>
<div class="option" data='{"value":"Csontostanya","state":"Fejer"}'>Csontostanya</div>
<div class="option" data='{"value":"Csor","state":"Fejer"}'>Csor</div>
<div class="option" data='{"value":"Csordakut","state":"Fejer"}'>Csordakut</div>
<div class="option" data='{"value":"Csosz","state":"Fejer"}'>Csosz</div>
<div class="option" data='{"value":"Csuktanya","state":"Fejer"}'>Csuktanya</div>
<div class="option" data='{"value":"Czekustanya","state":"Fejer"}'>Czekustanya</div>
<div class="option" data='{"value":"Czuczakmajor","state":"Fejer"}'>Czuczakmajor</div>
<div class="option" data='{"value":"Dadpuszta","state":"Fejer"}'>Dadpuszta</div>
<div class="option" data='{"value":"Daja","state":"Fejer"}'>Daja</div>
<div class="option" data='{"value":"Dajapuszta","state":"Fejer"}'>Dajapuszta</div>
<div class="option" data='{"value":"Danielpuszta","state":"Fejer"}'>Danielpuszta</div>
<div class="option" data='{"value":"Danielresz","state":"Fejer"}'>Danielresz</div>
<div class="option" data='{"value":"Danieltelep","state":"Fejer"}'>Danieltelep</div>
<div class="option" data='{"value":"Daruhegy","state":"Fejer"}'>Daruhegy</div>
<div class="option" data='{"value":"Daruhegyi Szolok","state":"Fejer"}'>Daruhegyi Szolok</div>
<div class="option" data='{"value":"Darumajor","state":"Fejer"}'>Darumajor</div>
<div class="option" data='{"value":"Darvastelep","state":"Fejer"}'>Darvastelep</div>
<div class="option" data='{"value":"Davidmajor","state":"Fejer"}'>Davidmajor</div>
<div class="option" data='{"value":"Deaktanya","state":"Fejer"}'>Deaktanya</div>
<div class="option" data='{"value":"Deg","state":"Fejer"}'>Deg</div>
<div class="option" data='{"value":"Delihegyiresz","state":"Fejer"}'>Delihegyiresz</div>
<div class="option" data='{"value":"Delyhegy","state":"Fejer"}'>Delyhegy</div>
<div class="option" data='{"value":"Derfitanya","state":"Fejer"}'>Derfitanya</div>
<div class="option" data='{"value":"Deutschtanya","state":"Fejer"}'>Deutschtanya</div>
<div class="option" data='{"value":"Dinnyes","state":"Fejer"}'>Dinnyes</div>
<div class="option" data='{"value":"Diofasori Ujtelep","state":"Fejer"}'>Diofasori Ujtelep</div>
<div class="option" data='{"value":"Dios","state":"Fejer"}'>Dios</div>
<div class="option" data='{"value":"Diosfasori Ujtelep","state":"Fejer"}'>Diosfasori Ujtelep</div>
<div class="option" data='{"value":"Dobogohegy","state":"Fejer"}'>Dobogohegy</div>
<div class="option" data='{"value":"Doboz","state":"Fejer"}'>Doboz</div>
<div class="option" data='{"value":"Dobozipuszta","state":"Fejer"}'>Dobozipuszta</div>
<div class="option" data='{"value":"Dogvolgyi Puszta","state":"Fejer"}'>Dogvolgyi Puszta</div>
<div class="option" data='{"value":"Dogvolgypuszta","state":"Fejer"}'>Dogvolgypuszta</div>
<div class="option" data='{"value":"Dolosd","state":"Fejer"}'>Dolosd</div>
<div class="option" data='{"value":"Dultfas","state":"Fejer"}'>Dultfas</div>
<div class="option" data='{"value":"Dunaduloi Tanyak","state":"Fejer"}'>Dunaduloi Tanyak</div>
<div class="option" data='{"value":"Dunapentele","state":"Fejer"}'>Dunapentele</div>
<div class="option" data='{"value":"Dunaujvaros","state":"Fejer"}'>Dunaujvaros</div>
<div class="option" data='{"value":"Ecsimajor","state":"Fejer"}'>Ecsimajor</div>
<div class="option" data='{"value":"Edinapuszta","state":"Fejer"}'>Edinapuszta</div>
<div class="option" data='{"value":"Egetthalom","state":"Fejer"}'>Egetthalom</div>
<div class="option" data='{"value":"Egetthaz","state":"Fejer"}'>Egetthaz</div>
<div class="option" data='{"value":"Egettmajor","state":"Fejer"}'>Egettmajor</div>
<div class="option" data='{"value":"Egyhazpuszta","state":"Fejer"}'>Egyhazpuszta</div>
<div class="option" data='{"value":"Elohegy","state":"Fejer"}'>Elohegy</div>
<div class="option" data='{"value":"Eloszallas","state":"Fejer"}'>Eloszallas</div>
<div class="option" data='{"value":"Elzamajor","state":"Fejer"}'>Elzamajor</div>
<div class="option" data='{"value":"Endltanya","state":"Fejer"}'>Endltanya</div>
<div class="option" data='{"value":"Enying","state":"Fejer"}'>Enying</div>
<div class="option" data='{"value":"Ercs","state":"Fejer"}'>Ercs</div>
<div class="option" data='{"value":"Ercsi","state":"Fejer"}'>Ercsi</div>
<div class="option" data='{"value":"Erdohat","state":"Fejer"}'>Erdohat</div>
<div class="option" data='{"value":"Erdohely","state":"Fejer"}'>Erdohely</div>
<div class="option" data='{"value":"Erdohelynyesta","state":"Fejer"}'>Erdohelynyesta</div>
<div class="option" data='{"value":"Erdohivatal Gaja","state":"Fejer"}'>Erdohivatal Gaja</div>
<div class="option" data='{"value":"Erdomajor","state":"Fejer"}'>Erdomajor</div>
<div class="option" data='{"value":"Ernomajor","state":"Fejer"}'>Ernomajor</div>
<div class="option" data='{"value":"Erzsebetmajor","state":"Fejer"}'>Erzsebetmajor</div>
<div class="option" data='{"value":"Eszeny","state":"Fejer"}'>Eszeny</div>
<div class="option" data='{"value":"Eszenyi Malom","state":"Fejer"}'>Eszenyi Malom</div>
<div class="option" data='{"value":"Esztermajor","state":"Fejer"}'>Esztermajor</div>
<div class="option" data='{"value":"Etelka","state":"Fejer"}'>Etelka</div>
<div class="option" data='{"value":"Etelkapuszta","state":"Fejer"}'>Etelkapuszta</div>
<div class="option" data='{"value":"Etyek","state":"Fejer"}'>Etyek</div>
<div class="option" data='{"value":"Ezeres","state":"Fejer"}'>Ezeres</div>
<div class="option" data='{"value":"Ezrespuszta","state":"Fejer"}'>Ezrespuszta</div>
<div class="option" data='{"value":"Fabriciustanya","state":"Fejer"}'>Fabriciustanya</div>
<div class="option" data='{"value":"Falubattyan","state":"Fejer"}'>Falubattyan</div>
<div class="option" data='{"value":"Fancs","state":"Fejer"}'>Fancs</div>
<div class="option" data='{"value":"Fanimajor","state":"Fejer"}'>Fanimajor</div>
<div class="option" data='{"value":"Farkasfapuszta","state":"Fejer"}'>Farkasfapuszta</div>
<div class="option" data='{"value":"Farkassimand","state":"Fejer"}'>Farkassimand</div>
<div class="option" data='{"value":"Farkastanya","state":"Fejer"}'>Farkastanya</div>
<div class="option" data='{"value":"Fehertanya","state":"Fejer"}'>Fehertanya</div>
<div class="option" data='{"value":"Fehervarcscurgo","state":"Fejer"}'>Fehervarcscurgo</div>
<div class="option" data='{"value":"Fehervarcsurgo","state":"Fejer"}'>Fehervarcsurgo</div>
<div class="option" data='{"value":"Fehervarcsurgoi Tanyak","state":"Fejer"}'>Fehervarcsurgoi Tanyak</div>
<div class="option" data='{"value":"Fehervarscsurgo","state":"Fejer"}'>Fehervarscsurgo</div>
<div class="option" data='{"value":"Fejer","state":"Fejer"}'>Fejer</div>
<div class="option" data='{"value":"Fejer County","state":"Fejer"}'>Fejer County</div>
<div class="option" data='{"value":"Fejer Megye","state":"Fejer"}'>Fejer Megye</div>
<div class="option" data='{"value":"Felcsut","state":"Fejer"}'>Felcsut</div>
<div class="option" data='{"value":"Felsobesnyo","state":"Fejer"}'>Felsobesnyo</div>
<div class="option" data='{"value":"Felsobogard","state":"Fejer"}'>Felsobogard</div>
<div class="option" data='{"value":"Felsobogardpuszta","state":"Fejer"}'>Felsobogardpuszta</div>
<div class="option" data='{"value":"Felsocikola","state":"Fejer"}'>Felsocikola</div>
<div class="option" data='{"value":"Felsocikolapuszta","state":"Fejer"}'>Felsocikolapuszta</div>
<div class="option" data='{"value":"Felsodobos","state":"Fejer"}'>Felsodobos</div>
<div class="option" data='{"value":"Felsokortvelyes","state":"Fejer"}'>Felsokortvelyes</div>
<div class="option" data='{"value":"Felsomajor","state":"Fejer"}'>Felsomajor</div>
<div class="option" data='{"value":"Felsomajor Termeloszovetkezet","state":"Fejer"}'>Felsomajor Termeloszovetkezet</div>
<div class="option" data='{"value":"Felsomalom","state":"Fejer"}'>Felsomalom</div>
<div class="option" data='{"value":"Felsoorspuszta","state":"Fejer"}'>Felsoorspuszta</div>
<div class="option" data='{"value":"Felsopettend","state":"Fejer"}'>Felsopettend</div>
<div class="option" data='{"value":"Felsopuszta","state":"Fejer"}'>Felsopuszta</div>
<div class="option" data='{"value":"Felsosomlyo","state":"Fejer"}'>Felsosomlyo</div>
<div class="option" data='{"value":"Felsoszentivan","state":"Fejer"}'>Felsoszentivan</div>
<div class="option" data='{"value":"Felsoszitanyipuszta","state":"Fejer"}'>Felsoszitanyipuszta</div>
<div class="option" data='{"value":"Felsoszolgaegyhaza","state":"Fejer"}'>Felsoszolgaegyhaza</div>
<div class="option" data='{"value":"Felsotarnoca","state":"Fejer"}'>Felsotarnoca</div>
<div class="option" data='{"value":"Felsoteglahaz","state":"Fejer"}'>Felsoteglahaz</div>
<div class="option" data='{"value":"Felsotoborzsok","state":"Fejer"}'>Felsotoborzsok</div>
<div class="option" data='{"value":"Felsovenyim","state":"Fejer"}'>Felsovenyim</div>
<div class="option" data='{"value":"Felszermajor","state":"Fejer"}'>Felszermajor</div>
<div class="option" data='{"value":"Fenyvesmajor","state":"Fejer"}'>Fenyvesmajor</div>
<div class="option" data='{"value":"Ferenctanya","state":"Fejer"}'>Ferenctanya</div>
<div class="option" data='{"value":"Fisitanya","state":"Fejer"}'>Fisitanya</div>
<div class="option" data='{"value":"Fornapuszta","state":"Fejer"}'>Fornapuszta</div>
<div class="option" data='{"value":"Forsterpuszta","state":"Fejer"}'>Forsterpuszta</div>
<div class="option" data='{"value":"Fovenyi Csarda","state":"Fejer"}'>Fovenyi Csarda</div>
<div class="option" data='{"value":"Fovenyitanya","state":"Fejer"}'>Fovenyitanya</div>
<div class="option" data='{"value":"Fovenypuszta","state":"Fejer"}'>Fovenypuszta</div>
<div class="option" data='{"value":"Friedrichtanya","state":"Fejer"}'>Friedrichtanya</div>
<div class="option" data='{"value":"Fule","state":"Fejer"}'>Fule</div>
<div class="option" data='{"value":"Fulopmajor","state":"Fejer"}'>Fulopmajor</div>
<div class="option" data='{"value":"Furdotanya","state":"Fejer"}'>Furdotanya</div>
<div class="option" data='{"value":"Fureditanya","state":"Fejer"}'>Fureditanya</div>
<div class="option" data='{"value":"Furesztelep","state":"Fejer"}'>Furesztelep</div>
<div class="option" data='{"value":"Fuzmatanya","state":"Fejer"}'>Fuzmatanya</div>
<div class="option" data='{"value":"Gabonastanya","state":"Fejer"}'>Gabonastanya</div>
<div class="option" data='{"value":"Gabormajor","state":"Fejer"}'>Gabormajor</div>
<div class="option" data='{"value":"Gaja","state":"Fejer"}'>Gaja</div>
<div class="option" data='{"value":"Galagonyas","state":"Fejer"}'>Galagonyas</div>
<div class="option" data='{"value":"Galambos","state":"Fejer"}'>Galambos</div>
<div class="option" data='{"value":"Galambospuszta","state":"Fejer"}'>Galambospuszta</div>
<div class="option" data='{"value":"Ganesztanya","state":"Fejer"}'>Ganesztanya</div>
<div class="option" data='{"value":"Gant","state":"Fejer"}'>Gant</div>
<div class="option" data='{"value":"Garasmajor","state":"Fejer"}'>Garasmajor</div>
<div class="option" data='{"value":"Garastanya","state":"Fejer"}'>Garastanya</div>
<div class="option" data='{"value":"Gardamajor","state":"Fejer"}'>Gardamajor</div>
<div class="option" data='{"value":"Gardapuszta","state":"Fejer"}'>Gardapuszta</div>
<div class="option" data='{"value":"Gardony","state":"Fejer"}'>Gardony</div>
<div class="option" data='{"value":"Gecseg","state":"Fejer"}'>Gecseg</div>
<div class="option" data='{"value":"Gecsegtanya","state":"Fejer"}'>Gecsegtanya</div>
<div class="option" data='{"value":"Gecseytanya","state":"Fejer"}'>Gecseytanya</div>
<div class="option" data='{"value":"Gedovari Puszta","state":"Fejer"}'>Gedovari Puszta</div>
<div class="option" data='{"value":"Gedovaritanya","state":"Fejer"}'>Gedovaritanya</div>
<div class="option" data='{"value":"Gellert","state":"Fejer"}'>Gellert</div>
<div class="option" data='{"value":"Gellertpuszta","state":"Fejer"}'>Gellertpuszta</div>
<div class="option" data='{"value":"Gezakoz","state":"Fejer"}'>Gezakoz</div>
<div class="option" data='{"value":"Gezamajor","state":"Fejer"}'>Gezamajor</div>
<div class="option" data='{"value":"Gizellatanya","state":"Fejer"}'>Gizellatanya</div>
<div class="option" data='{"value":"Goboljaras","state":"Fejer"}'>Goboljaras</div>
<div class="option" data='{"value":"Golyadulo","state":"Fejer"}'>Golyadulo</div>
<div class="option" data='{"value":"Goncsogmajor","state":"Fejer"}'>Goncsogmajor</div>
<div class="option" data='{"value":"Goncsokmajor","state":"Fejer"}'>Goncsokmajor</div>
<div class="option" data='{"value":"Gottltanya","state":"Fejer"}'>Gottltanya</div>
<div class="option" data='{"value":"Gulyamajor","state":"Fejer"}'>Gulyamajor</div>
<div class="option" data='{"value":"Gurdimajor","state":"Fejer"}'>Gurdimajor</div>
<div class="option" data='{"value":"Gusztus","state":"Fejer"}'>Gusztus</div>
<div class="option" data='{"value":"Gusztuspuszta","state":"Fejer"}'>Gusztuspuszta</div>
<div class="option" data='{"value":"Guttamasi","state":"Fejer"}'>Guttamasi</div>
<div class="option" data='{"value":"Gyeneitanya","state":"Fejer"}'>Gyeneitanya</div>
<div class="option" data='{"value":"Gyorgyitanya","state":"Fejer"}'>Gyorgyitanya</div>
<div class="option" data='{"value":"Gyorgymajor","state":"Fejer"}'>Gyorgymajor</div>
<div class="option" data='{"value":"Gyoritanya","state":"Fejer"}'>Gyoritanya</div>
<div class="option" data='{"value":"Gyulamajor","state":"Fejer"}'>Gyulamajor</div>
<div class="option" data='{"value":"Gyulatanya","state":"Fejer"}'>Gyulatanya</div>
<div class="option" data='{"value":"Gyuro","state":"Fejer"}'>Gyuro</div>
<div class="option" data='{"value":"Gyuroipuszta","state":"Fejer"}'>Gyuroipuszta</div>
<div class="option" data='{"value":"Gyurusaljapuszta","state":"Fejer"}'>Gyurusaljapuszta</div>
<div class="option" data='{"value":"Habocskitanya","state":"Fejer"}'>Habocskitanya</div>
<div class="option" data='{"value":"Haboczkytanya","state":"Fejer"}'>Haboczkytanya</div>
<div class="option" data='{"value":"Hadnagypuszta","state":"Fejer"}'>Hadnagypuszta</div>
<div class="option" data='{"value":"Hajdupuszta","state":"Fejer"}'>Hajdupuszta</div>
<div class="option" data='{"value":"Hajdutanya","state":"Fejer"}'>Hajdutanya</div>
<div class="option" data='{"value":"Halasto","state":"Fejer"}'>Halasto</div>
<div class="option" data='{"value":"Halaszhaz","state":"Fejer"}'>Halaszhaz</div>
<div class="option" data='{"value":"Hanaktanya","state":"Fejer"}'>Hanaktanya</div>
<div class="option" data='{"value":"Hangaszpuszta","state":"Fejer"}'>Hangaszpuszta</div>
<div class="option" data='{"value":"Hantos","state":"Fejer"}'>Hantos</div>
<div class="option" data='{"value":"Harangozotanya","state":"Fejer"}'>Harangozotanya</div>
<div class="option" data='{"value":"Harasztosi Banya","state":"Fejer"}'>Harasztosi Banya</div>
<div class="option" data='{"value":"Harmatosmajor","state":"Fejer"}'>Harmatosmajor</div>
<div class="option" data='{"value":"Harmatospuszta","state":"Fejer"}'>Harmatospuszta</div>
<div class="option" data='{"value":"Haromrozsa","state":"Fejer"}'>Haromrozsa</div>
<div class="option" data='{"value":"Hatarvolgy","state":"Fejer"}'>Hatarvolgy</div>
<div class="option" data='{"value":"Hatarvolgypuszta","state":"Fejer"}'>Hatarvolgypuszta</div>
<div class="option" data='{"value":"Hathaz","state":"Fejer"}'>Hathaz</div>
<div class="option" data='{"value":"Hathazsismand","state":"Fejer"}'>Hathazsismand</div>
<div class="option" data='{"value":"Hatvan","state":"Fejer"}'>Hatvan</div>
<div class="option" data='{"value":"Hatvanpuszta","state":"Fejer"}'>Hatvanpuszta</div>
<div class="option" data='{"value":"Hegeduspuszta","state":"Fejer"}'>Hegeduspuszta</div>
<div class="option" data='{"value":"Hegyikastely","state":"Fejer"}'>Hegyikastely</div>
<div class="option" data='{"value":"Hercegfalva","state":"Fejer"}'>Hercegfalva</div>
<div class="option" data='{"value":"Hermanntanya","state":"Fejer"}'>Hermanntanya</div>
<div class="option" data='{"value":"Hethazpuszta","state":"Fejer"}'>Hethazpuszta</div>
<div class="option" data='{"value":"Hidastanya","state":"Fejer"}'>Hidastanya</div>
<div class="option" data='{"value":"Hippolitpuszta","state":"Fejer"}'>Hippolitpuszta</div>
<div class="option" data='{"value":"Hippolytpuszta","state":"Fejer"}'>Hippolytpuszta</div>
<div class="option" data='{"value":"Hollotanya","state":"Fejer"}'>Hollotanya</div>
<div class="option" data='{"value":"Hordovolgy","state":"Fejer"}'>Hordovolgy</div>
<div class="option" data='{"value":"Horvathtanya","state":"Fejer"}'>Horvathtanya</div>
<div class="option" data='{"value":"Huszarpuszta","state":"Fejer"}'>Huszarpuszta</div>
<div class="option" data='{"value":"Huszartanya","state":"Fejer"}'>Huszartanya</div>
<div class="option" data='{"value":"Igar","state":"Fejer"}'>Igar</div>
<div class="option" data='{"value":"Ilonamajor","state":"Fejer"}'>Ilonamajor</div>
<div class="option" data='{"value":"Imremajor","state":"Fejer"}'>Imremajor</div>
<div class="option" data='{"value":"Innensoangyad","state":"Fejer"}'>Innensoangyad</div>
<div class="option" data='{"value":"Inotapuszta","state":"Fejer"}'>Inotapuszta</div>
<div class="option" data='{"value":"Ipartelep","state":"Fejer"}'>Ipartelep</div>
<div class="option" data='{"value":"Ipolydulo","state":"Fejer"}'>Ipolydulo</div>
<div class="option" data='{"value":"Irtas","state":"Fejer"}'>Irtas</div>
<div class="option" data='{"value":"Irtaspuszta","state":"Fejer"}'>Irtaspuszta</div>
<div class="option" data='{"value":"Istvanhegyi Szollo","state":"Fejer"}'>Istvanhegyi Szollo</div>
<div class="option" data='{"value":"Iszka","state":"Fejer"}'>Iszka</div>
<div class="option" data='{"value":"Iszkaszentgyorgy","state":"Fejer"}'>Iszkaszentgyorgy</div>
<div class="option" data='{"value":"Isztimer","state":"Fejer"}'>Isztimer</div>
<div class="option" data='{"value":"Ivancsa","state":"Fejer"}'>Ivancsa</div>
<div class="option" data='{"value":"Jakabszallas","state":"Fejer"}'>Jakabszallas</div>
<div class="option" data='{"value":"Janitsaripuszta","state":"Fejer"}'>Janitsaripuszta</div>
<div class="option" data='{"value":"Janitsarypuszta","state":"Fejer"}'>Janitsarypuszta</div>
<div class="option" data='{"value":"Janosfutas","state":"Fejer"}'>Janosfutas</div>
<div class="option" data='{"value":"Janosi Volgy","state":"Fejer"}'>Janosi Volgy</div>
<div class="option" data='{"value":"Janosmajor","state":"Fejer"}'>Janosmajor</div>
<div class="option" data='{"value":"Janostanya","state":"Fejer"}'>Janostanya</div>
<div class="option" data='{"value":"Jarastanya","state":"Fejer"}'>Jarastanya</div>
<div class="option" data='{"value":"Jeno","state":"Fejer"}'>Jeno</div>
<div class="option" data='{"value":"Jenomajor","state":"Fejer"}'>Jenomajor</div>
<div class="option" data='{"value":"Jilektanya","state":"Fejer"}'>Jilektanya</div>
<div class="option" data='{"value":"Jozsatanya","state":"Fejer"}'>Jozsatanya</div>
<div class="option" data='{"value":"Jozsefmajor","state":"Fejer"}'>Jozsefmajor</div>
<div class="option" data='{"value":"Jozsefpuszta","state":"Fejer"}'>Jozsefpuszta</div>
<div class="option" data='{"value":"Juliamajor","state":"Fejer"}'>Juliamajor</div>
<div class="option" data='{"value":"Kabokapuszta","state":"Fejer"}'>Kabokapuszta</div>
<div class="option" data='{"value":"Kajaszo","state":"Fejer"}'>Kajaszo</div>
<div class="option" data='{"value":"Kajaszoszentivan","state":"Fejer"}'>Kajaszoszentivan</div>
<div class="option" data='{"value":"Kajaszoszentpeter","state":"Fejer"}'>Kajaszoszentpeter</div>
<div class="option" data='{"value":"Kajditanya","state":"Fejer"}'>Kajditanya</div>
<div class="option" data='{"value":"Kajdytanya","state":"Fejer"}'>Kajdytanya</div>
<div class="option" data='{"value":"Kajmati","state":"Fejer"}'>Kajmati</div>
<div class="option" data='{"value":"Kajmati Malom","state":"Fejer"}'>Kajmati Malom</div>
<div class="option" data='{"value":"Kajtori Tanyak","state":"Fejer"}'>Kajtori Tanyak</div>
<div class="option" data='{"value":"Kakavolgy","state":"Fejer"}'>Kakavolgy</div>
<div class="option" data='{"value":"Kaloz","state":"Fejer"}'>Kaloz</div>
<div class="option" data='{"value":"Kapitanytanya","state":"Fejer"}'>Kapitanytanya</div>
<div class="option" data='{"value":"Kapolnasnyek","state":"Fejer"}'>Kapolnasnyek</div>
<div class="option" data='{"value":"Karolinapuszta","state":"Fejer"}'>Karolinapuszta</div>
<div class="option" data='{"value":"Karolinpuszta","state":"Fejer"}'>Karolinpuszta</div>
<div class="option" data='{"value":"Kastely","state":"Fejer"}'>Kastely</div>
<div class="option" data='{"value":"Katalinpuszta","state":"Fejer"}'>Katalinpuszta</div>
<div class="option" data='{"value":"Katlanvolgy","state":"Fejer"}'>Katlanvolgy</div>
<div class="option" data='{"value":"Kazsokitanya","state":"Fejer"}'>Kazsokitanya</div>
<div class="option" data='{"value":"Kelementanya","state":"Fejer"}'>Kelementanya</div>
<div class="option" data='{"value":"Kenedytanya","state":"Fejer"}'>Kenedytanya</div>
<div class="option" data='{"value":"Kijatztanya","state":"Fejer"}'>Kijatztanya</div>
<div class="option" data='{"value":"Kilicsan","state":"Fejer"}'>Kilicsan</div>
<div class="option" data='{"value":"Killertanya","state":"Fejer"}'>Killertanya</div>
<div class="option" data='{"value":"Kincses","state":"Fejer"}'>Kincses</div>
<div class="option" data='{"value":"Kincsesbanya","state":"Fejer"}'>Kincsesbanya</div>
<div class="option" data='{"value":"Kiralyszallas","state":"Fejer"}'>Kiralyszallas</div>
<div class="option" data='{"value":"Kis Karacsony Puszta","state":"Fejer"}'>Kis Karacsony Puszta</div>
<div class="option" data='{"value":"Kis Zakarias Tanya","state":"Fejer"}'>Kis Zakarias Tanya</div>
<div class="option" data='{"value":"Kisapostag","state":"Fejer"}'>Kisapostag</div>
<div class="option" data='{"value":"Kisasszony","state":"Fejer"}'>Kisasszony</div>
<div class="option" data='{"value":"Kisasszonytanya","state":"Fejer"}'>Kisasszonytanya</div>
<div class="option" data='{"value":"Kisbaratpuszta","state":"Fejer"}'>Kisbaratpuszta</div>
<div class="option" data='{"value":"Kisbogard","state":"Fejer"}'>Kisbogard</div>
<div class="option" data='{"value":"Kiscseripuszta","state":"Fejer"}'>Kiscseripuszta</div>
<div class="option" data='{"value":"Kisdadpuszta","state":"Fejer"}'>Kisdadpuszta</div>
<div class="option" data='{"value":"Kisdoboka","state":"Fejer"}'>Kisdoboka</div>
<div class="option" data='{"value":"Kiserdo","state":"Fejer"}'>Kiserdo</div>
<div class="option" data='{"value":"Kiseszter","state":"Fejer"}'>Kiseszter</div>
<div class="option" data='{"value":"Kiseszterpuszta","state":"Fejer"}'>Kiseszterpuszta</div>
<div class="option" data='{"value":"Kisfalud","state":"Fejer"}'>Kisfalud</div>
<div class="option" data='{"value":"Kisfalud Alsomajor","state":"Fejer"}'>Kisfalud Alsomajor</div>
<div class="option" data='{"value":"Kisfalud Felsomajor","state":"Fejer"}'>Kisfalud Felsomajor</div>
<div class="option" data='{"value":"Kisfalud Ujtelep","state":"Fejer"}'>Kisfalud Ujtelep</div>
<div class="option" data='{"value":"Kisgyon","state":"Fejer"}'>Kisgyon</div>
<div class="option" data='{"value":"Kisgyonbanya","state":"Fejer"}'>Kisgyonbanya</div>
<div class="option" data='{"value":"Kishalom","state":"Fejer"}'>Kishalom</div>
<div class="option" data='{"value":"Kishalompuszta","state":"Fejer"}'>Kishalompuszta</div>
<div class="option" data='{"value":"Kishantos","state":"Fejer"}'>Kishantos</div>
<div class="option" data='{"value":"Kishorcsokpuszta","state":"Fejer"}'>Kishorcsokpuszta</div>
<div class="option" data='{"value":"Kiskaracsonyszallas","state":"Fejer"}'>Kiskaracsonyszallas</div>
<div class="option" data='{"value":"Kiskokasd","state":"Fejer"}'>Kiskokasd</div>
<div class="option" data='{"value":"Kislang","state":"Fejer"}'>Kislang</div>
<div class="option" data='{"value":"Kislok","state":"Fejer"}'>Kislok</div>
<div class="option" data='{"value":"Kislokpuszta","state":"Fejer"}'>Kislokpuszta</div>
<div class="option" data='{"value":"Kisloktelep","state":"Fejer"}'>Kisloktelep</div>
<div class="option" data='{"value":"Kismalom","state":"Fejer"}'>Kismalom</div>
<div class="option" data='{"value":"Kismarton","state":"Fejer"}'>Kismarton</div>
<div class="option" data='{"value":"Kispuszta","state":"Fejer"}'>Kispuszta</div>
<div class="option" data='{"value":"Kisstanya","state":"Fejer"}'>Kisstanya</div>
<div class="option" data='{"value":"Kisszentmiklos","state":"Fejer"}'>Kisszentmiklos</div>
<div class="option" data='{"value":"Kisszentmiklostelep","state":"Fejer"}'>Kisszentmiklostelep</div>
<div class="option" data='{"value":"Kistad","state":"Fejer"}'>Kistad</div>
<div class="option" data='{"value":"Kistelekitanya","state":"Fejer"}'>Kistelekitanya</div>
<div class="option" data='{"value":"Kistelep","state":"Fejer"}'>Kistelep</div>
<div class="option" data='{"value":"Kisvelence","state":"Fejer"}'>Kisvelence</div>
<div class="option" data='{"value":"Kisvelencze","state":"Fejer"}'>Kisvelencze</div>
<div class="option" data='{"value":"Kisvenyim","state":"Fejer"}'>Kisvenyim</div>
<div class="option" data='{"value":"Kisvenyimalsopuszta","state":"Fejer"}'>Kisvenyimalsopuszta</div>
<div class="option" data='{"value":"Kisvenyimfelsopuszta","state":"Fejer"}'>Kisvenyimfelsopuszta</div>
<div class="option" data='{"value":"Kleinpuszta","state":"Fejer"}'>Kleinpuszta</div>
<div class="option" data='{"value":"Klementinmajor","state":"Fejer"}'>Klementinmajor</div>
<div class="option" data='{"value":"Kochtanya","state":"Fejer"}'>Kochtanya</div>
<div class="option" data='{"value":"Kocsihegy","state":"Fejer"}'>Kocsihegy</div>
<div class="option" data='{"value":"Kocsishazapuszta","state":"Fejer"}'>Kocsishazapuszta</div>
<div class="option" data='{"value":"Kocsistanya","state":"Fejer"}'>Kocsistanya</div>
<div class="option" data='{"value":"Kohanyas","state":"Fejer"}'>Kohanyas</div>
<div class="option" data='{"value":"Kohanyaspuszta","state":"Fejer"}'>Kohanyaspuszta</div>
<div class="option" data='{"value":"Kohiditabla","state":"Fejer"}'>Kohiditabla</div>
<div class="option" data='{"value":"Kokasdi Dulo","state":"Fejer"}'>Kokasdi Dulo</div>
<div class="option" data='{"value":"Kokutpuszta","state":"Fejer"}'>Kokutpuszta</div>
<div class="option" data='{"value":"Kolestelek","state":"Fejer"}'>Kolestelek</div>
<div class="option" data='{"value":"Kollerresz","state":"Fejer"}'>Kollerresz</div>
<div class="option" data='{"value":"Kolompos","state":"Fejer"}'>Kolompos</div>
<div class="option" data='{"value":"Komaromitanya","state":"Fejer"}'>Komaromitanya</div>
<div class="option" data='{"value":"Korakas","state":"Fejer"}'>Korakas</div>
<div class="option" data='{"value":"Koreppuszta","state":"Fejer"}'>Koreppuszta</div>
<div class="option" data='{"value":"Kormendipuszta","state":"Fejer"}'>Kormendipuszta</div>
<div class="option" data='{"value":"Kormendypuszta","state":"Fejer"}'>Kormendypuszta</div>
<div class="option" data='{"value":"Kortelyesmajor","state":"Fejer"}'>Kortelyesmajor</div>
<div class="option" data='{"value":"Kortvelyesmajor","state":"Fejer"}'>Kortvelyesmajor</div>
<div class="option" data='{"value":"Kossuthpuszta","state":"Fejer"}'>Kossuthpuszta</div>
<div class="option" data='{"value":"Kossuthvolgy","state":"Fejer"}'>Kossuthvolgy</div>
<div class="option" data='{"value":"Koszarhegy","state":"Fejer"}'>Koszarhegy</div>
<div class="option" data='{"value":"Kovacssziget","state":"Fejer"}'>Kovacssziget</div>
<div class="option" data='{"value":"Kovacstanya","state":"Fejer"}'>Kovacstanya</div>
<div class="option" data='{"value":"Kozepbogard","state":"Fejer"}'>Kozepbogard</div>
<div class="option" data='{"value":"Kozepdobos","state":"Fejer"}'>Kozepdobos</div>
<div class="option" data='{"value":"Kozeppuszta","state":"Fejer"}'>Kozeppuszta</div>
<div class="option" data='{"value":"Kozepszolgaegyhaza","state":"Fejer"}'>Kozepszolgaegyhaza</div>
<div class="option" data='{"value":"Kozmagyumolcs","state":"Fejer"}'>Kozmagyumolcs</div>
<div class="option" data='{"value":"Kozmagyumolcsos","state":"Fejer"}'>Kozmagyumolcsos</div>
<div class="option" data='{"value":"Kozmatanya","state":"Fejer"}'>Kozmatanya</div>
<div class="option" data='{"value":"Kulapuszta","state":"Fejer"}'>Kulapuszta</div>
<div class="option" data='{"value":"Kulcs","state":"Fejer"}'>Kulcs</div>
<div class="option" data='{"value":"Kulcspuszta","state":"Fejer"}'>Kulcspuszta</div>
<div class="option" data='{"value":"Kuldo","state":"Fejer"}'>Kuldo</div>
<div class="option" data='{"value":"Kulmajor","state":"Fejer"}'>Kulmajor</div>
<div class="option" data='{"value":"Kulmajori Tanya","state":"Fejer"}'>Kulmajori Tanya</div>
<div class="option" data='{"value":"Kulsobarand","state":"Fejer"}'>Kulsobarand</div>
<div class="option" data='{"value":"Kulsohatvan","state":"Fejer"}'>Kulsohatvan</div>
<div class="option" data='{"value":"Kulsokajtor","state":"Fejer"}'>Kulsokajtor</div>
<div class="option" data='{"value":"Kulsokisperkatapuszta","state":"Fejer"}'>Kulsokisperkatapuszta</div>
<div class="option" data='{"value":"Kulsopotollepuszta","state":"Fejer"}'>Kulsopotollepuszta</div>
<div class="option" data='{"value":"Kulsosari","state":"Fejer"}'>Kulsosari</div>
<div class="option" data='{"value":"Kulsosaripuszta","state":"Fejer"}'>Kulsosaripuszta</div>
<div class="option" data='{"value":"Kulsoszollohegy","state":"Fejer"}'>Kulsoszollohegy</div>
<div class="option" data='{"value":"Kulsoszolohegy","state":"Fejer"}'>Kulsoszolohegy</div>
<div class="option" data='{"value":"Kulsotukros","state":"Fejer"}'>Kulsotukros</div>
<div class="option" data='{"value":"Kuti","state":"Fejer"}'>Kuti</div>
<div class="option" data='{"value":"Lajoskomarom","state":"Fejer"}'>Lajoskomarom</div>
<div class="option" data='{"value":"Lajostelep","state":"Fejer"}'>Lajostelep</div>
<div class="option" data='{"value":"Langtanya","state":"Fejer"}'>Langtanya</div>
<div class="option" data='{"value":"Lapostanya","state":"Fejer"}'>Lapostanya</div>
<div class="option" data='{"value":"Lapseny","state":"Fejer"}'>Lapseny</div>
<div class="option" data='{"value":"Laszlomajor","state":"Fejer"}'>Laszlomajor</div>
<div class="option" data='{"value":"Laszlopuszta","state":"Fejer"}'>Laszlopuszta</div>
<div class="option" data='{"value":"Lazlopuszta","state":"Fejer"}'>Lazlopuszta</div>
<div class="option" data='{"value":"Leanyvago","state":"Fejer"}'>Leanyvago</div>
<div class="option" data='{"value":"Leitnertanya","state":"Fejer"}'>Leitnertanya</div>
<div class="option" data='{"value":"Lenkemajor","state":"Fejer"}'>Lenkemajor</div>
<div class="option" data='{"value":"Lepseny","state":"Fejer"}'>Lepseny</div>
<div class="option" data='{"value":"Leshegy","state":"Fejer"}'>Leshegy</div>
<div class="option" data='{"value":"Liget Sor","state":"Fejer"}'>Liget Sor</div>
<div class="option" data='{"value":"Lipotpuszta","state":"Fejer"}'>Lipotpuszta</div>
<div class="option" data='{"value":"Liviamajor","state":"Fejer"}'>Liviamajor</div>
<div class="option" data='{"value":"Liviapuszta","state":"Fejer"}'>Liviapuszta</div>
<div class="option" data='{"value":"Lobbmajor","state":"Fejer"}'>Lobbmajor</div>
<div class="option" data='{"value":"Lojatanya","state":"Fejer"}'>Lojatanya</div>
<div class="option" data='{"value":"Lovasbereny","state":"Fejer"}'>Lovasbereny</div>
<div class="option" data='{"value":"Lowytanya","state":"Fejer"}'>Lowytanya</div>
<div class="option" data='{"value":"Lusztret","state":"Fejer"}'>Lusztret</div>
<div class="option" data='{"value":"Magyaralmas","state":"Fejer"}'>Magyaralmas</div>
<div class="option" data='{"value":"Magyartanya","state":"Fejer"}'>Magyartanya</div>
<div class="option" data='{"value":"Malachegy","state":"Fejer"}'>Malachegy</div>
<div class="option" data='{"value":"Malehegy","state":"Fejer"}'>Malehegy</div>
<div class="option" data='{"value":"Malomto","state":"Fejer"}'>Malomto</div>
<div class="option" data='{"value":"Many","state":"Fejer"}'>Many</div>
<div class="option" data='{"value":"Marcinkahaz","state":"Fejer"}'>Marcinkahaz</div>
<div class="option" data='{"value":"Marcinkatanya","state":"Fejer"}'>Marcinkatanya</div>
<div class="option" data='{"value":"Marcsamajor","state":"Fejer"}'>Marcsamajor</div>
<div class="option" data='{"value":"Margittanya","state":"Fejer"}'>Margittanya</div>
<div class="option" data='{"value":"Mariaannapuszta","state":"Fejer"}'>Mariaannapuszta</div>
<div class="option" data='{"value":"Mariamajor","state":"Fejer"}'>Mariamajor</div>
<div class="option" data='{"value":"Mariatelep","state":"Fejer"}'>Mariatelep</div>
<div class="option" data='{"value":"Mariavolgy","state":"Fejer"}'>Mariavolgy</div>
<div class="option" data='{"value":"Mariskapuszta","state":"Fejer"}'>Mariskapuszta</div>
<div class="option" data='{"value":"Markovicstanya","state":"Fejer"}'>Markovicstanya</div>
<div class="option" data='{"value":"Martonvasar","state":"Fejer"}'>Martonvasar</div>
<div class="option" data='{"value":"Matesztanya","state":"Fejer"}'>Matesztanya</div>
<div class="option" data='{"value":"Matyasdomb","state":"Fejer"}'>Matyasdomb</div>
<div class="option" data='{"value":"Mayertanya","state":"Fejer"}'>Mayertanya</div>
<div class="option" data='{"value":"Mecser","state":"Fejer"}'>Mecser</div>
<div class="option" data='{"value":"Mecsertelep","state":"Fejer"}'>Mecsertelep</div>
<div class="option" data='{"value":"Mehadiapuszta","state":"Fejer"}'>Mehadiapuszta</div>
<div class="option" data='{"value":"Mehes","state":"Fejer"}'>Mehes</div>
<div class="option" data='{"value":"Mehestanya","state":"Fejer"}'>Mehestanya</div>
<div class="option" data='{"value":"Mehesvolgyitanya","state":"Fejer"}'>Mehesvolgyitanya</div>
<div class="option" data='{"value":"Melykut","state":"Fejer"}'>Melykut</div>
<div class="option" data='{"value":"Melyvolgy","state":"Fejer"}'>Melyvolgy</div>
<div class="option" data='{"value":"Melyvolgypuszta","state":"Fejer"}'>Melyvolgypuszta</div>
<div class="option" data='{"value":"Menesmajor","state":"Fejer"}'>Menesmajor</div>
<div class="option" data='{"value":"Menyod","state":"Fejer"}'>Menyod</div>
<div class="option" data='{"value":"Mereymajor","state":"Fejer"}'>Mereymajor</div>
<div class="option" data='{"value":"Merito","state":"Fejer"}'>Merito</div>
<div class="option" data='{"value":"Meritopuszta","state":"Fejer"}'>Meritopuszta</div>
<div class="option" data='{"value":"Meszarosdulo","state":"Fejer"}'>Meszarosdulo</div>
<div class="option" data='{"value":"Meszarostanya","state":"Fejer"}'>Meszarostanya</div>
<div class="option" data='{"value":"Meszotanya","state":"Fejer"}'>Meszotanya</div>
<div class="option" data='{"value":"Mezofalva","state":"Fejer"}'>Mezofalva</div>
<div class="option" data='{"value":"Mezokomarom","state":"Fejer"}'>Mezokomarom</div>
<div class="option" data='{"value":"Mezoszentgyorgy","state":"Fejer"}'>Mezoszentgyorgy</div>
<div class="option" data='{"value":"Mezoszilas","state":"Fejer"}'>Mezoszilas</div>
<div class="option" data='{"value":"Miklosmajor","state":"Fejer"}'>Miklosmajor</div>
<div class="option" data='{"value":"Miklosvar","state":"Fejer"}'>Miklosvar</div>
<div class="option" data='{"value":"Mikustanya","state":"Fejer"}'>Mikustanya</div>
<div class="option" data='{"value":"Mindszentpuszta","state":"Fejer"}'>Mindszentpuszta</div>
<div class="option" data='{"value":"Moha","state":"Fejer"}'>Moha</div>
<div class="option" data='{"value":"Molnarsziget","state":"Fejer"}'>Molnarsziget</div>
<div class="option" data='{"value":"Molnartanya","state":"Fejer"}'>Molnartanya</div>
<div class="option" data='{"value":"Mor","state":"Fejer"}'>Mor</div>
<div class="option" data='{"value":"Moricmajor","state":"Fejer"}'>Moricmajor</div>
<div class="option" data='{"value":"Moriczmajor","state":"Fejer"}'>Moriczmajor</div>
<div class="option" data='{"value":"Nadap","state":"Fejer"}'>Nadap</div>
<div class="option" data='{"value":"Nadasdladany","state":"Fejer"}'>Nadasdladany</div>
<div class="option" data='{"value":"Nadasdypuszta","state":"Fejer"}'>Nadasdypuszta</div>
<div class="option" data='{"value":"Nagy Lajos Tanya","state":"Fejer"}'>Nagy Lajos Tanya</div>
<div class="option" data='{"value":"Nagy Pal Sismand","state":"Fejer"}'>Nagy Pal Sismand</div>
<div class="option" data='{"value":"Nagycseripuszta","state":"Fejer"}'>Nagycseripuszta</div>
<div class="option" data='{"value":"Nagydoboka","state":"Fejer"}'>Nagydoboka</div>
<div class="option" data='{"value":"Nagyegyhaza","state":"Fejer"}'>Nagyegyhaza</div>
<div class="option" data='{"value":"Nagygyon","state":"Fejer"}'>Nagygyon</div>
<div class="option" data='{"value":"Nagygyonpuszta","state":"Fejer"}'>Nagygyonpuszta</div>
<div class="option" data='{"value":"Nagygyorgyszallas","state":"Fejer"}'>Nagygyorgyszallas</div>
<div class="option" data='{"value":"Nagyhalom","state":"Fejer"}'>Nagyhalom</div>
<div class="option" data='{"value":"Nagyhantos","state":"Fejer"}'>Nagyhantos</div>
<div class="option" data='{"value":"Nagyhantosierdomajor","state":"Fejer"}'>Nagyhantosierdomajor</div>
<div class="option" data='{"value":"Nagyhegy","state":"Fejer"}'>Nagyhegy</div>
<div class="option" data='{"value":"Nagyhorcsokpuszta","state":"Fejer"}'>Nagyhorcsokpuszta</div>
<div class="option" data='{"value":"Nagykaracsony","state":"Fejer"}'>Nagykaracsony</div>
<div class="option" data='{"value":"Nagykaracsony Puszta","state":"Fejer"}'>Nagykaracsony Puszta</div>
<div class="option" data='{"value":"Nagykaracsonyszallas","state":"Fejer"}'>Nagykaracsonyszallas</div>
<div class="option" data='{"value":"Nagykustyan","state":"Fejer"}'>Nagykustyan</div>
<div class="option" data='{"value":"Nagylang","state":"Fejer"}'>Nagylang</div>
<div class="option" data='{"value":"Nagylok","state":"Fejer"}'>Nagylok</div>
<div class="option" data='{"value":"Nagyloki Erdomajor","state":"Fejer"}'>Nagyloki Erdomajor</div>
<div class="option" data='{"value":"Nagyloktelep","state":"Fejer"}'>Nagyloktelep</div>
<div class="option" data='{"value":"Nagynemetegyhaz","state":"Fejer"}'>Nagynemetegyhaz</div>
<div class="option" data='{"value":"Nagysismand","state":"Fejer"}'>Nagysismand</div>
<div class="option" data='{"value":"Nagysziget","state":"Fejer"}'>Nagysziget</div>
<div class="option" data='{"value":"Nagyveleg","state":"Fejer"}'>Nagyveleg</div>
<div class="option" data='{"value":"Nagyvenyim","state":"Fejer"}'>Nagyvenyim</div>
<div class="option" data='{"value":"Nagyvenyimi Major","state":"Fejer"}'>Nagyvenyimi Major</div>
<div class="option" data='{"value":"Nagyvenyimpuszta","state":"Fejer"}'>Nagyvenyimpuszta</div>
<div class="option" data='{"value":"Nagyvolgy","state":"Fejer"}'>Nagyvolgy</div>
<div class="option" data='{"value":"Nandormajor","state":"Fejer"}'>Nandormajor</div>
<div class="option" data='{"value":"Nandorpuszta","state":"Fejer"}'>Nandorpuszta</div>
<div class="option" data='{"value":"Napraforgopuszta","state":"Fejer"}'>Napraforgopuszta</div>
<div class="option" data='{"value":"Nolltanya","state":"Fejer"}'>Nolltanya</div>
<div class="option" data='{"value":"Novothtanya","state":"Fejer"}'>Novothtanya</div>
<div class="option" data='{"value":"Nyedampuszta","state":"Fejer"}'>Nyedampuszta</div>
<div class="option" data='{"value":"Nyuldulo","state":"Fejer"}'>Nyuldulo</div>
<div class="option" data='{"value":"Obarok","state":"Fejer"}'>Obarok</div>
<div class="option" data='{"value":"Obarokpuszta","state":"Fejer"}'>Obarokpuszta</div>
<div class="option" data='{"value":"Odonmajor","state":"Fejer"}'>Odonmajor</div>
<div class="option" data='{"value":"Odonpuszta","state":"Fejer"}'>Odonpuszta</div>
<div class="option" data='{"value":"Ohodospuszta","state":"Fejer"}'>Ohodospuszta</div>
<div class="option" data='{"value":"Olajtelep","state":"Fejer"}'>Olajtelep</div>
<div class="option" data='{"value":"Oreghegy","state":"Fejer"}'>Oreghegy</div>
<div class="option" data='{"value":"Oregtarnok","state":"Fejer"}'>Oregtarnok</div>
<div class="option" data='{"value":"Orgonas","state":"Fejer"}'>Orgonas</div>
<div class="option" data='{"value":"Orhalmi Szollok","state":"Fejer"}'>Orhalmi Szollok</div>
<div class="option" data='{"value":"Orhalmiszolok","state":"Fejer"}'>Orhalmiszolok</div>
<div class="option" data='{"value":"Orondpuszta","state":"Fejer"}'>Orondpuszta</div>
<div class="option" data='{"value":"Orondszollok","state":"Fejer"}'>Orondszollok</div>
<div class="option" data='{"value":"Oroszimajor","state":"Fejer"}'>Oroszimajor</div>
<div class="option" data='{"value":"Oroszipuszta","state":"Fejer"}'>Oroszipuszta</div>
<div class="option" data='{"value":"Orspuszta","state":"Fejer"}'>Orspuszta</div>
<div class="option" data='{"value":"Orszagutduloi Tanyak","state":"Fejer"}'>Orszagutduloi Tanyak</div>
<div class="option" data='{"value":"Orszaguti Tanya","state":"Fejer"}'>Orszaguti Tanya</div>
<div class="option" data='{"value":"Pajortanya","state":"Fejer"}'>Pajortanya</div>
<div class="option" data='{"value":"Pakozd","state":"Fejer"}'>Pakozd</div>
<div class="option" data='{"value":"Palhalma","state":"Fejer"}'>Palhalma</div>
<div class="option" data='{"value":"Palhalmapuszta","state":"Fejer"}'>Palhalmapuszta</div>
<div class="option" data='{"value":"Palinkahazpuszta","state":"Fejer"}'>Palinkahazpuszta</div>
<div class="option" data='{"value":"Palmajor","state":"Fejer"}'>Palmajor</div>
<div class="option" data='{"value":"Papfold","state":"Fejer"}'>Papfold</div>
<div class="option" data='{"value":"Parragpuszta","state":"Fejer"}'>Parragpuszta</div>
<div class="option" data='{"value":"Paskum","state":"Fejer"}'>Paskum</div>
<div class="option" data='{"value":"Paszkalinmajor","state":"Fejer"}'>Paszkalinmajor</div>
<div class="option" data='{"value":"Patka","state":"Fejer"}'>Patka</div>
<div class="option" data='{"value":"Patkai Tanyak","state":"Fejer"}'>Patkai Tanyak</div>
<div class="option" data='{"value":"Paulamajor","state":"Fejer"}'>Paulamajor</div>
<div class="option" data='{"value":"Paulapuszta","state":"Fejer"}'>Paulapuszta</div>
<div class="option" data='{"value":"Pazmand","state":"Fejer"}'>Pazmand</div>
<div class="option" data='{"value":"Pazmandpuszta","state":"Fejer"}'>Pazmandpuszta</div>
<div class="option" data='{"value":"Pelpuszta","state":"Fejer"}'>Pelpuszta</div>
<div class="option" data='{"value":"Penzvero","state":"Fejer"}'>Penzvero</div>
<div class="option" data='{"value":"Perjesitanya","state":"Fejer"}'>Perjesitanya</div>
<div class="option" data='{"value":"Perkata","state":"Fejer"}'>Perkata</div>
<div class="option" data='{"value":"Pesthytanya","state":"Fejer"}'>Pesthytanya</div>
<div class="option" data='{"value":"Petermajor","state":"Fejer"}'>Petermajor</div>
<div class="option" data='{"value":"Peterszallas","state":"Fejer"}'>Peterszallas</div>
<div class="option" data='{"value":"Pettend","state":"Fejer"}'>Pettend</div>
<div class="option" data='{"value":"Pincevolgy","state":"Fejer"}'>Pincevolgy</div>
<div class="option" data='{"value":"Piripocs","state":"Fejer"}'>Piripocs</div>
<div class="option" data='{"value":"Piripocstelep","state":"Fejer"}'>Piripocstelep</div>
<div class="option" data='{"value":"Piros","state":"Fejer"}'>Piros</div>
<div class="option" data='{"value":"Piszkeritanya","state":"Fejer"}'>Piszkeritanya</div>
<div class="option" data='{"value":"Pityerdulo","state":"Fejer"}'>Pityerdulo</div>
<div class="option" data='{"value":"Plihaltanya","state":"Fejer"}'>Plihaltanya</div>
<div class="option" data='{"value":"Poganyvar","state":"Fejer"}'>Poganyvar</div>
<div class="option" data='{"value":"Polgardi","state":"Fejer"}'>Polgardi</div>
<div class="option" data='{"value":"Polgardi Ipartelepek","state":"Fejer"}'>Polgardi Ipartelepek</div>
<div class="option" data='{"value":"Polgarditekeres","state":"Fejer"}'>Polgarditekeres</div>
<div class="option" data='{"value":"Pongractanya","state":"Fejer"}'>Pongractanya</div>
<div class="option" data='{"value":"Potolle","state":"Fejer"}'>Potolle</div>
<div class="option" data='{"value":"Potollepuszta","state":"Fejer"}'>Potollepuszta</div>
<div class="option" data='{"value":"Potvelence","state":"Fejer"}'>Potvelence</div>
<div class="option" data='{"value":"Prazsaktanya","state":"Fejer"}'>Prazsaktanya</div>
<div class="option" data='{"value":"Prazsoktanya","state":"Fejer"}'>Prazsoktanya</div>
<div class="option" data='{"value":"Pusztaegres","state":"Fejer"}'>Pusztaegres</div>
<div class="option" data='{"value":"Pusztaegresi Tarnoca","state":"Fejer"}'>Pusztaegresi Tarnoca</div>
<div class="option" data='{"value":"Pusztakapolna","state":"Fejer"}'>Pusztakapolna</div>
<div class="option" data='{"value":"Pusztaszabolcs","state":"Fejer"}'>Pusztaszabolcs</div>
<div class="option" data='{"value":"Pusztaszentmihalyfa","state":"Fejer"}'>Pusztaszentmihalyfa</div>
<div class="option" data='{"value":"Pusztavam","state":"Fejer"}'>Pusztavam</div>
<div class="option" data='{"value":"Rabocky Volgy","state":"Fejer"}'>Rabocky Volgy</div>
<div class="option" data='{"value":"Racalmas","state":"Fejer"}'>Racalmas</div>
<div class="option" data='{"value":"Rachegy","state":"Fejer"}'>Rachegy</div>
<div class="option" data='{"value":"Rackeresztur","state":"Fejer"}'>Rackeresztur</div>
<div class="option" data='{"value":"Racszentmiklos","state":"Fejer"}'>Racszentmiklos</div>
<div class="option" data='{"value":"Racszentpeter","state":"Fejer"}'>Racszentpeter</div>
<div class="option" data='{"value":"Raczalmas","state":"Fejer"}'>Raczalmas</div>
<div class="option" data='{"value":"Raczszentpeter","state":"Fejer"}'>Raczszentpeter</div>
<div class="option" data='{"value":"Radicsa","state":"Fejer"}'>Radicsa</div>
<div class="option" data='{"value":"Radicsapuszta","state":"Fejer"}'>Radicsapuszta</div>
<div class="option" data='{"value":"Rakhegy","state":"Fejer"}'>Rakhegy</div>
<div class="option" data='{"value":"Rebecpuszta","state":"Fejer"}'>Rebecpuszta</div>
<div class="option" data='{"value":"Remenysor","state":"Fejer"}'>Remenysor</div>
<div class="option" data='{"value":"Retimajor","state":"Fejer"}'>Retimajor</div>
<div class="option" data='{"value":"Retszilas","state":"Fejer"}'>Retszilas</div>
<div class="option" data='{"value":"Rezsotanya","state":"Fejer"}'>Rezsotanya</div>
<div class="option" data='{"value":"Richardmajor","state":"Fejer"}'>Richardmajor</div>
<div class="option" data='{"value":"Rikimajor","state":"Fejer"}'>Rikimajor</div>
<div class="option" data='{"value":"Robertvolgy","state":"Fejer"}'>Robertvolgy</div>
<div class="option" data='{"value":"Robertvolgy Szallas","state":"Fejer"}'>Robertvolgy Szallas</div>
<div class="option" data='{"value":"Robozhegy","state":"Fejer"}'>Robozhegy</div>
<div class="option" data='{"value":"Roboztanya","state":"Fejer"}'>Roboztanya</div>
<div class="option" data='{"value":"Rohoncztanya","state":"Fejer"}'>Rohoncztanya</div>
<div class="option" data='{"value":"Rokamajor","state":"Fejer"}'>Rokamajor</div>
<div class="option" data='{"value":"Rokas","state":"Fejer"}'>Rokas</div>
<div class="option" data='{"value":"Rongyos","state":"Fejer"}'>Rongyos</div>
<div class="option" data='{"value":"Rozsamajor","state":"Fejer"}'>Rozsamajor</div>
<div class="option" data='{"value":"Sagihegy","state":"Fejer"}'>Sagihegy</div>
<div class="option" data='{"value":"Sagmajor","state":"Fejer"}'>Sagmajor</div>
<div class="option" data='{"value":"Sancpuszta","state":"Fejer"}'>Sancpuszta</div>
<div class="option" data='{"value":"Sandorhazapuszta","state":"Fejer"}'>Sandorhazapuszta</div>
<div class="option" data='{"value":"Sandorka","state":"Fejer"}'>Sandorka</div>
<div class="option" data='{"value":"Sandorkapuszta","state":"Fejer"}'>Sandorkapuszta</div>
<div class="option" data='{"value":"Sandormajor","state":"Fejer"}'>Sandormajor</div>
<div class="option" data='{"value":"Sandorszallas","state":"Fejer"}'>Sandorszallas</div>
<div class="option" data='{"value":"Sarbogard","state":"Fejer"}'>Sarbogard</div>
<div class="option" data='{"value":"Saregres","state":"Fejer"}'>Saregres</div>
<div class="option" data='{"value":"Sariujmajor","state":"Fejer"}'>Sariujmajor</div>
<div class="option" data='{"value":"Sarkeresztes","state":"Fejer"}'>Sarkeresztes</div>
<div class="option" data='{"value":"Sarkeresztur","state":"Fejer"}'>Sarkeresztur</div>
<div class="option" data='{"value":"Sarkeszi","state":"Fejer"}'>Sarkeszi</div>
<div class="option" data='{"value":"Sarkeszi Felsomajor","state":"Fejer"}'>Sarkeszi Felsomajor</div>
<div class="option" data='{"value":"Sarosd","state":"Fejer"}'>Sarosd</div>
<div class="option" data='{"value":"Sarpentele","state":"Fejer"}'>Sarpentele</div>
<div class="option" data='{"value":"Sarszentagota","state":"Fejer"}'>Sarszentagota</div>
<div class="option" data='{"value":"Sarszentmihaly","state":"Fejer"}'>Sarszentmihaly</div>
<div class="option" data='{"value":"Sarszentmiklos","state":"Fejer"}'>Sarszentmiklos</div>
<div class="option" data='{"value":"Sashalom","state":"Fejer"}'>Sashalom</div>
<div class="option" data='{"value":"Sattelbergertanya","state":"Fejer"}'>Sattelbergertanya</div>
<div class="option" data='{"value":"Schacktanya","state":"Fejer"}'>Schacktanya</div>
<div class="option" data='{"value":"Schweizerei","state":"Fejer"}'>Schweizerei</div>
<div class="option" data='{"value":"Selyemmajor","state":"Fejer"}'>Selyemmajor</div>
<div class="option" data='{"value":"Selymespuszta","state":"Fejer"}'>Selymespuszta</div>
<div class="option" data='{"value":"Semseitanya","state":"Fejer"}'>Semseitanya</div>
<div class="option" data='{"value":"Seregelyes","state":"Fejer"}'>Seregelyes</div>
<div class="option" data='{"value":"Seregelyesi Tanyak","state":"Fejer"}'>Seregelyesi Tanyak</div>
<div class="option" data='{"value":"Sikator","state":"Fejer"}'>Sikator</div>
<div class="option" data='{"value":"Sikatorpuszta","state":"Fejer"}'>Sikatorpuszta</div>
<div class="option" data='{"value":"Somoshegy","state":"Fejer"}'>Somoshegy</div>
<div class="option" data='{"value":"Somosmal","state":"Fejer"}'>Somosmal</div>
<div class="option" data='{"value":"Soponya","state":"Fejer"}'>Soponya</div>
<div class="option" data='{"value":"Sored","state":"Fejer"}'>Sored</div>
<div class="option" data='{"value":"Sorke","state":"Fejer"}'>Sorke</div>
<div class="option" data='{"value":"Sorkedulok","state":"Fejer"}'>Sorkedulok</div>
<div class="option" data='{"value":"Sovenykut","state":"Fejer"}'>Sovenykut</div>
<div class="option" data='{"value":"Sovenykutpuszta","state":"Fejer"}'>Sovenykutpuszta</div>
<div class="option" data='{"value":"Stalinvaros","state":"Fejer"}'>Stalinvaros</div>
<div class="option" data='{"value":"Stegertanya","state":"Fejer"}'>Stegertanya</div>
<div class="option" data='{"value":"Sukoro","state":"Fejer"}'>Sukoro</div>
<div class="option" data='{"value":"Szabadbattyan","state":"Fejer"}'>Szabadbattyan</div>
<div class="option" data='{"value":"Szabadegyhaza","state":"Fejer"}'>Szabadegyhaza</div>
<div class="option" data='{"value":"Szabadhegy","state":"Fejer"}'>Szabadhegy</div>
<div class="option" data='{"value":"Szabadhidveg","state":"Fejer"}'>Szabadhidveg</div>
<div class="option" data='{"value":"Szabadsaghegy","state":"Fejer"}'>Szabadsaghegy</div>
<div class="option" data='{"value":"Szabolcsiuti Haromfa","state":"Fejer"}'>Szabolcsiuti Haromfa</div>
<div class="option" data='{"value":"Szabolcspuszta","state":"Fejer"}'>Szabolcspuszta</div>
<div class="option" data='{"value":"Szabotanya","state":"Fejer"}'>Szabotanya</div>
<div class="option" data='{"value":"Szallaskut","state":"Fejer"}'>Szallaskut</div>
<div class="option" data='{"value":"Szallaskutpuszta","state":"Fejer"}'>Szallaskutpuszta</div>
<div class="option" data='{"value":"Szar","state":"Fejer"}'>Szar</div>
<div class="option" data='{"value":"Szarazret","state":"Fejer"}'>Szarazret</div>
<div class="option" data='{"value":"Szarazretek","state":"Fejer"}'>Szarazretek</div>
<div class="option" data='{"value":"Szarujtelep","state":"Fejer"}'>Szarujtelep</div>
<div class="option" data='{"value":"Szarvaspuszta","state":"Fejer"}'>Szarvaspuszta</div>
<div class="option" data='{"value":"Szarvastanya","state":"Fejer"}'>Szarvastanya</div>
<div class="option" data='{"value":"Szauerweintanya","state":"Fejer"}'>Szauerweintanya</div>
<div class="option" data='{"value":"Szedrespuszta","state":"Fejer"}'>Szedrespuszta</div>
<div class="option" data='{"value":"Szekesfehervar","state":"Fejer"}'>Szekesfehervar</div>
<div class="option" data='{"value":"Szeles","state":"Fejer"}'>Szeles</div>
<div class="option" data='{"value":"Szelescsapas","state":"Fejer"}'>Szelescsapas</div>
<div class="option" data='{"value":"Szelesmajor","state":"Fejer"}'>Szelesmajor</div>
<div class="option" data='{"value":"Szelestanya","state":"Fejer"}'>Szelestanya</div>
<div class="option" data='{"value":"Szenavolgy","state":"Fejer"}'>Szenavolgy</div>
<div class="option" data='{"value":"Szenettatanya","state":"Fejer"}'>Szenettatanya</div>
<div class="option" data='{"value":"Szentgyorgy","state":"Fejer"}'>Szentgyorgy</div>
<div class="option" data='{"value":"Szentgyorgypuszta","state":"Fejer"}'>Szentgyorgypuszta</div>
<div class="option" data='{"value":"Szentimremajor","state":"Fejer"}'>Szentimremajor</div>
<div class="option" data='{"value":"Szentimretelep","state":"Fejer"}'>Szentimretelep</div>
<div class="option" data='{"value":"Szentkutimajor","state":"Fejer"}'>Szentkutimajor</div>
<div class="option" data='{"value":"Szentlaszlo","state":"Fejer"}'>Szentlaszlo</div>
<div class="option" data='{"value":"Szentlaszlopuszta","state":"Fejer"}'>Szentlaszlopuszta</div>
<div class="option" data='{"value":"Szentlaszlotelke","state":"Fejer"}'>Szentlaszlotelke</div>
<div class="option" data='{"value":"Szentmihaly","state":"Fejer"}'>Szentmihaly</div>
<div class="option" data='{"value":"Szentmihalypuszta","state":"Fejer"}'>Szentmihalypuszta</div>
<div class="option" data='{"value":"Szentterezmajor","state":"Fejer"}'>Szentterezmajor</div>
<div class="option" data='{"value":"Szeszgyar","state":"Fejer"}'>Szeszgyar</div>
<div class="option" data='{"value":"Szeszgyartelep","state":"Fejer"}'>Szeszgyartelep</div>
<div class="option" data='{"value":"Sziget","state":"Fejer"}'>Sziget</div>
<div class="option" data='{"value":"Szigetduloi Tanyak","state":"Fejer"}'>Szigetduloi Tanyak</div>
<div class="option" data='{"value":"Szigettanya","state":"Fejer"}'>Szigettanya</div>
<div class="option" data='{"value":"Szilfamajor","state":"Fejer"}'>Szilfamajor</div>
<div class="option" data='{"value":"Szlatina","state":"Fejer"}'>Szlatina</div>
<div class="option" data='{"value":"Szlatinapuszta","state":"Fejer"}'>Szlatinapuszta</div>
<div class="option" data='{"value":"Szluhapuszta","state":"Fejer"}'>Szluhapuszta</div>
<div class="option" data='{"value":"Szoketanya","state":"Fejer"}'>Szoketanya</div>
<div class="option" data='{"value":"Szolgaegyhaza","state":"Fejer"}'>Szolgaegyhaza</div>
<div class="option" data='{"value":"Szonyegitanya","state":"Fejer"}'>Szonyegitanya</div>
<div class="option" data='{"value":"Szoradidulo","state":"Fejer"}'>Szoradidulo</div>
<div class="option" data='{"value":"Sztalinvaros","state":"Fejer"}'>Sztalinvaros</div>
<div class="option" data='{"value":"Szucstanya","state":"Fejer"}'>Szucstanya</div>
<div class="option" data='{"value":"Szunyogmajor","state":"Fejer"}'>Szunyogmajor</div>
<div class="option" data='{"value":"Szunyogpuszta","state":"Fejer"}'>Szunyogpuszta</div>
<div class="option" data='{"value":"Szuszki","state":"Fejer"}'>Szuszki</div>
<div class="option" data='{"value":"Tabajd","state":"Fejer"}'>Tabajd</div>
<div class="option" data='{"value":"Taborszallaspuszta","state":"Fejer"}'>Taborszallaspuszta</div>
<div class="option" data='{"value":"Tac","state":"Fejer"}'>Tac</div>
<div class="option" data='{"value":"Taligastanya","state":"Fejer"}'>Taligastanya</div>
<div class="option" data='{"value":"Tallianpuszta","state":"Fejer"}'>Tallianpuszta</div>
<div class="option" data='{"value":"Tarnoca","state":"Fejer"}'>Tarnoca</div>
<div class="option" data='{"value":"Tarnok","state":"Fejer"}'>Tarnok</div>
<div class="option" data='{"value":"Tarnokpuszta","state":"Fejer"}'>Tarnokpuszta</div>
<div class="option" data='{"value":"Tavaszmajor","state":"Fejer"}'>Tavaszmajor</div>
<div class="option" data='{"value":"Teglatelep","state":"Fejer"}'>Teglatelep</div>
<div class="option" data='{"value":"Telizoldes","state":"Fejer"}'>Telizoldes</div>
<div class="option" data='{"value":"Temetohegy","state":"Fejer"}'>Temetohegy</div>
<div class="option" data='{"value":"Templompuszta","state":"Fejer"}'>Templompuszta</div>
<div class="option" data='{"value":"Terezmajor","state":"Fejer"}'>Terezmajor</div>
<div class="option" data='{"value":"Teseny","state":"Fejer"}'>Teseny</div>
<div class="option" data='{"value":"Tilos","state":"Fejer"}'>Tilos</div>
<div class="option" data='{"value":"Tilospuszta","state":"Fejer"}'>Tilospuszta</div>
<div class="option" data='{"value":"Timarpuszta","state":"Fejer"}'>Timarpuszta</div>
<div class="option" data='{"value":"Tiringertanya","state":"Fejer"}'>Tiringertanya</div>
<div class="option" data='{"value":"Tirringertanya","state":"Fejer"}'>Tirringertanya</div>
<div class="option" data='{"value":"Tischlertanya","state":"Fejer"}'>Tischlertanya</div>
<div class="option" data='{"value":"Tokjo","state":"Fejer"}'>Tokjo</div>
<div class="option" data='{"value":"Tolnaitelep","state":"Fejer"}'>Tolnaitelep</div>
<div class="option" data='{"value":"Tompapuszta","state":"Fejer"}'>Tompapuszta</div>
<div class="option" data='{"value":"Tordas","state":"Fejer"}'>Tordas</div>
<div class="option" data='{"value":"Tornyo","state":"Fejer"}'>Tornyo</div>
<div class="option" data='{"value":"Torospuszta","state":"Fejer"}'>Torospuszta</div>
<div class="option" data='{"value":"Tothtanya","state":"Fejer"}'>Tothtanya</div>
<div class="option" data='{"value":"Totipuszta","state":"Fejer"}'>Totipuszta</div>
<div class="option" data='{"value":"Totret","state":"Fejer"}'>Totret</div>
<div class="option" data='{"value":"Tukros","state":"Fejer"}'>Tukros</div>
<div class="option" data='{"value":"Tukrosmajor","state":"Fejer"}'>Tukrosmajor</div>
<div class="option" data='{"value":"Tukrospuszta","state":"Fejer"}'>Tukrospuszta</div>
<div class="option" data='{"value":"Tukrosujtelep","state":"Fejer"}'>Tukrosujtelep</div>
<div class="option" data='{"value":"Tulsoangyad","state":"Fejer"}'>Tulsoangyad</div>
<div class="option" data='{"value":"Tuskesmajor","state":"Fejer"}'>Tuskesmajor</div>
<div class="option" data='{"value":"Tuskespuszta","state":"Fejer"}'>Tuskespuszta</div>
<div class="option" data='{"value":"Tutyimajor","state":"Fejer"}'>Tutyimajor</div>
<div class="option" data='{"value":"Ubaldpuszta","state":"Fejer"}'>Ubaldpuszta</div>
<div class="option" data='{"value":"Ujbarok","state":"Fejer"}'>Ujbarok</div>
<div class="option" data='{"value":"Ujbogardpuszta","state":"Fejer"}'>Ujbogardpuszta</div>
<div class="option" data='{"value":"Ujfalu","state":"Fejer"}'>Ujfalu</div>
<div class="option" data='{"value":"Ujgalambos","state":"Fejer"}'>Ujgalambos</div>
<div class="option" data='{"value":"Ujgalambospuszta","state":"Fejer"}'>Ujgalambospuszta</div>
<div class="option" data='{"value":"Ujgut","state":"Fejer"}'>Ujgut</div>
<div class="option" data='{"value":"Ujhegy","state":"Fejer"}'>Ujhegy</div>
<div class="option" data='{"value":"Ujhodospuszta","state":"Fejer"}'>Ujhodospuszta</div>
<div class="option" data='{"value":"Ujiskola","state":"Fejer"}'>Ujiskola</div>
<div class="option" data='{"value":"Ujkutpuszta","state":"Fejer"}'>Ujkutpuszta</div>
<div class="option" data='{"value":"Ujmajor","state":"Fejer"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujmenyod","state":"Fejer"}'>Ujmenyod</div>
<div class="option" data='{"value":"Ujtelep","state":"Fejer"}'>Ujtelep</div>
<div class="option" data='{"value":"Ujvaritanya","state":"Fejer"}'>Ujvaritanya</div>
<div class="option" data='{"value":"Urgemajor","state":"Fejer"}'>Urgemajor</div>
<div class="option" data='{"value":"Urhida","state":"Fejer"}'>Urhida</div>
<div class="option" data='{"value":"Vajta","state":"Fejer"}'>Vajta</div>
<div class="option" data='{"value":"Val","state":"Fejer"}'>Val</div>
<div class="option" data='{"value":"Vampuszta","state":"Fejer"}'>Vampuszta</div>
<div class="option" data='{"value":"Vancsaitelep","state":"Fejer"}'>Vancsaitelep</div>
<div class="option" data='{"value":"Vancsaytanya","state":"Fejer"}'>Vancsaytanya</div>
<div class="option" data='{"value":"Vantsaypuszta","state":"Fejer"}'>Vantsaypuszta</div>
<div class="option" data='{"value":"Vargahegy","state":"Fejer"}'>Vargahegy</div>
<div class="option" data='{"value":"Vargatanya","state":"Fejer"}'>Vargatanya</div>
<div class="option" data='{"value":"Varjudulo","state":"Fejer"}'>Varjudulo</div>
<div class="option" data='{"value":"Varjuvar","state":"Fejer"}'>Varjuvar</div>
<div class="option" data='{"value":"Varosretidulo","state":"Fejer"}'>Varosretidulo</div>
<div class="option" data='{"value":"Vaskapu","state":"Fejer"}'>Vaskapu</div>
<div class="option" data='{"value":"Vastaghalompuszta","state":"Fejer"}'>Vastaghalompuszta</div>
<div class="option" data='{"value":"Vasutisor","state":"Fejer"}'>Vasutisor</div>
<div class="option" data='{"value":"Vasztely","state":"Fejer"}'>Vasztely</div>
<div class="option" data='{"value":"Vasztelypuszta","state":"Fejer"}'>Vasztelypuszta</div>
<div class="option" data='{"value":"Vattaitanya","state":"Fejer"}'>Vattaitanya</div>
<div class="option" data='{"value":"Veghmajor","state":"Fejer"}'>Veghmajor</div>
<div class="option" data='{"value":"Velence","state":"Fejer"}'>Velence</div>
<div class="option" data='{"value":"Velis","state":"Fejer"}'>Velis</div>
<div class="option" data='{"value":"Velistanya","state":"Fejer"}'>Velistanya</div>
<div class="option" data='{"value":"Vendeldulo","state":"Fejer"}'>Vendeldulo</div>
<div class="option" data='{"value":"Venyinidulo","state":"Fejer"}'>Venyinidulo</div>
<div class="option" data='{"value":"Vereb","state":"Fejer"}'>Vereb</div>
<div class="option" data='{"value":"Verebiuti Ujtelep","state":"Fejer"}'>Verebiuti Ujtelep</div>
<div class="option" data='{"value":"Vert","state":"Fejer"}'>Vert</div>
<div class="option" data='{"value":"Vertesacsa","state":"Fejer"}'>Vertesacsa</div>
<div class="option" data='{"value":"Vertesboglar","state":"Fejer"}'>Vertesboglar</div>
<div class="option" data='{"value":"Vertesdoboz","state":"Fejer"}'>Vertesdoboz</div>
<div class="option" data='{"value":"Verteskoma","state":"Fejer"}'>Verteskoma</div>
<div class="option" data='{"value":"Verteskozma","state":"Fejer"}'>Verteskozma</div>
<div class="option" data='{"value":"Vertesnana","state":"Fejer"}'>Vertesnana</div>
<div class="option" data='{"value":"Vertpuszta","state":"Fejer"}'>Vertpuszta</div>
<div class="option" data='{"value":"Vidatanya","state":"Fejer"}'>Vidatanya</div>
<div class="option" data='{"value":"Vilagos","state":"Fejer"}'>Vilagos</div>
<div class="option" data='{"value":"Vilagosmajor","state":"Fejer"}'>Vilagosmajor</div>
<div class="option" data='{"value":"Vilagospuszta","state":"Fejer"}'>Vilagospuszta</div>
<div class="option" data='{"value":"Vilagostelep","state":"Fejer"}'>Vilagostelep</div>
<div class="option" data='{"value":"Vilhelmtanya","state":"Fejer"}'>Vilhelmtanya</div>
<div class="option" data='{"value":"Villa","state":"Fejer"}'>Villa</div>
<div class="option" data='{"value":"Viraghegy","state":"Fejer"}'>Viraghegy</div>
<div class="option" data='{"value":"Vitezitelep","state":"Fejer"}'>Vitezitelep</div>
<div class="option" data='{"value":"Viteztelek","state":"Fejer"}'>Viteztelek</div>
<div class="option" data='{"value":"Vitzmantanya","state":"Fejer"}'>Vitzmantanya</div>
<div class="option" data='{"value":"Vizmesteritelep","state":"Fejer"}'>Vizmesteritelep</div>
<div class="option" data='{"value":"Vizmestertelep","state":"Fejer"}'>Vizmestertelep</div>
<div class="option" data='{"value":"Voroshegy","state":"Fejer"}'>Voroshegy</div>
<div class="option" data='{"value":"Vukajtotanya","state":"Fejer"}'>Vukajtotanya</div>
<div class="option" data='{"value":"Zamoly","state":"Fejer"}'>Zamoly</div>
<div class="option" data='{"value":"Zedregpuszta","state":"Fejer"}'>Zedregpuszta</div>
<div class="option" data='{"value":"Zichymajor","state":"Fejer"}'>Zichymajor</div>
<div class="option" data='{"value":"Zichyujfalu","state":"Fejer"}'>Zichyujfalu</div>
<div class="option" data='{"value":"Zoldmajor","state":"Fejer"}'>Zoldmajor</div>
<div class="option" data='{"value":"Zsemberitanya","state":"Fejer"}'>Zsemberitanya</div>
<div class="option" data='{"value":"Zsidohegy","state":"Fejer"}'>Zsidohegy</div>
<div class="option" data='{"value":"Zsidokalapmajor","state":"Fejer"}'>Zsidokalapmajor</div>
<div class="option" data='{"value":"Zsuzsannamajor","state":"Fejer"}'>Zsuzsannamajor</div>
<div class="option" id="option_end" data='{"value":"Zsuzsatanya","state":"Fejer"}'>Zsuzsatanya</div>

