<div class="option" data='{"value":"Acsad","state":"Vas"}'>Acsad</div>
<div class="option" data='{"value":"Acsadi Malom","state":"Vas"}'>Acsadi Malom</div>
<div class="option" data='{"value":"Afrikamajor","state":"Vas"}'>Afrikamajor</div>
<div class="option" data='{"value":"Allami Malom","state":"Vas"}'>Allami Malom</div>
<div class="option" data='{"value":"Alsocsatar","state":"Vas"}'>Alsocsatar</div>
<div class="option" data='{"value":"Alsomajor","state":"Vas"}'>Alsomajor</div>
<div class="option" data='{"value":"Alsonyirvarimajor","state":"Vas"}'>Alsonyirvarimajor</div>
<div class="option" data='{"value":"Alsonyirvarmajor","state":"Vas"}'>Alsonyirvarmajor</div>
<div class="option" data='{"value":"Alsopaty","state":"Vas"}'>Alsopaty</div>
<div class="option" data='{"value":"Alsoronok","state":"Vas"}'>Alsoronok</div>
<div class="option" data='{"value":"Alsosag","state":"Vas"}'>Alsosag</div>
<div class="option" data='{"value":"Alsoszeleste","state":"Vas"}'>Alsoszeleste</div>
<div class="option" data='{"value":"Alsoszolnok","state":"Vas"}'>Alsoszolnok</div>
<div class="option" data='{"value":"Alsoszolnoki Tanyak","state":"Vas"}'>Alsoszolnoki Tanyak</div>
<div class="option" data='{"value":"Alsoujlak","state":"Vas"}'>Alsoujlak</div>
<div class="option" data='{"value":"Andrasfa","state":"Vas"}'>Andrasfa</div>
<div class="option" data='{"value":"Andrastanya","state":"Vas"}'>Andrastanya</div>
<div class="option" data='{"value":"Annamajor","state":"Vas"}'>Annamajor</div>
<div class="option" data='{"value":"Antoniamajor","state":"Vas"}'>Antoniamajor</div>
<div class="option" data='{"value":"Apatipuszta","state":"Vas"}'>Apatipuszta</div>
<div class="option" data='{"value":"Apatistvanfalva","state":"Vas"}'>Apatistvanfalva</div>
<div class="option" data='{"value":"Bajansenye","state":"Vas"}'>Bajansenye</div>
<div class="option" data='{"value":"Bajti","state":"Vas"}'>Bajti</div>
<div class="option" data='{"value":"Balogunyom","state":"Vas"}'>Balogunyom</div>
<div class="option" data='{"value":"Balozsameggyes","state":"Vas"}'>Balozsameggyes</div>
<div class="option" data='{"value":"Barnevolnamajor","state":"Vas"}'>Barnevolnamajor</div>
<div class="option" data='{"value":"Bebicmajor","state":"Vas"}'>Bebicmajor</div>
<div class="option" data='{"value":"Benkehaza","state":"Vas"}'>Benkehaza</div>
<div class="option" data='{"value":"Benkehazamajor","state":"Vas"}'>Benkehazamajor</div>
<div class="option" data='{"value":"Berbaltavar","state":"Vas"}'>Berbaltavar</div>
<div class="option" data='{"value":"Berekmajor","state":"Vas"}'>Berekmajor</div>
<div class="option" data='{"value":"Berzsenyimajor","state":"Vas"}'>Berzsenyimajor</div>
<div class="option" data='{"value":"Bicsakmalom","state":"Vas"}'>Bicsakmalom</div>
<div class="option" data='{"value":"Bogatimajor","state":"Vas"}'>Bogatimajor</div>
<div class="option" data='{"value":"Boldogasszonymajor","state":"Vas"}'>Boldogasszonymajor</div>
<div class="option" data='{"value":"Borgata","state":"Vas"}'>Borgata</div>
<div class="option" data='{"value":"Botkahaza","state":"Vas"}'>Botkahaza</div>
<div class="option" data='{"value":"Bozsok","state":"Vas"}'>Bozsok</div>
<div class="option" data='{"value":"Bozzai","state":"Vas"}'>Bozzai</div>
<div class="option" data='{"value":"Bucsu","state":"Vas"}'>Bucsu</div>
<div class="option" data='{"value":"Buda","state":"Vas"}'>Buda</div>
<div class="option" data='{"value":"Budahegy","state":"Vas"}'>Budahegy</div>
<div class="option" data='{"value":"Buk","state":"Vas"}'>Buk</div>
<div class="option" data='{"value":"Busmajor","state":"Vas"}'>Busmajor</div>
<div class="option" data='{"value":"Cak","state":"Vas"}'>Cak</div>
<div class="option" data='{"value":"Celldomolk","state":"Vas"}'>Celldomolk</div>
<div class="option" data='{"value":"Ceretnek","state":"Vas"}'>Ceretnek</div>
<div class="option" data='{"value":"Cetehaza","state":"Vas"}'>Cetehaza</div>
<div class="option" data='{"value":"Chernelhazadamonya","state":"Vas"}'>Chernelhazadamonya</div>
<div class="option" data='{"value":"Csakanydoroszlo","state":"Vas"}'>Csakanydoroszlo</div>
<div class="option" data='{"value":"Csardamalom","state":"Vas"}'>Csardamalom</div>
<div class="option" data='{"value":"Csaszartanya","state":"Vas"}'>Csaszartanya</div>
<div class="option" data='{"value":"Csehi","state":"Vas"}'>Csehi</div>
<div class="option" data='{"value":"Csehimindszent","state":"Vas"}'>Csehimindszent</div>
<div class="option" data='{"value":"Csehitelep","state":"Vas"}'>Csehitelep</div>
<div class="option" data='{"value":"Csempeszkopacs","state":"Vas"}'>Csempeszkopacs</div>
<div class="option" data='{"value":"Csencsberekimajor","state":"Vas"}'>Csencsberekimajor</div>
<div class="option" data='{"value":"Csencsiberekmajor","state":"Vas"}'>Csencsiberekmajor</div>
<div class="option" data='{"value":"Csenye","state":"Vas"}'>Csenye</div>
<div class="option" data='{"value":"Csenyeujmajor","state":"Vas"}'>Csenyeujmajor</div>
<div class="option" data='{"value":"Csepreg","state":"Vas"}'>Csepreg</div>
<div class="option" data='{"value":"Cserfasmajor","state":"Vas"}'>Cserfasmajor</div>
<div class="option" data='{"value":"Cserhatmajor","state":"Vas"}'>Cserhatmajor</div>
<div class="option" data='{"value":"Cserhatnyir","state":"Vas"}'>Cserhatnyir</div>
<div class="option" data='{"value":"Cserhidimajor","state":"Vas"}'>Cserhidimajor</div>
<div class="option" data='{"value":"Cseritanya","state":"Vas"}'>Cseritanya</div>
<div class="option" data='{"value":"Csermajor","state":"Vas"}'>Csermajor</div>
<div class="option" data='{"value":"Csermelymajor","state":"Vas"}'>Csermelymajor</div>
<div class="option" data='{"value":"Csillaghegy","state":"Vas"}'>Csillaghegy</div>
<div class="option" data='{"value":"Csillagmajor","state":"Vas"}'>Csillagmajor</div>
<div class="option" data='{"value":"Csipkerek","state":"Vas"}'>Csipkerek</div>
<div class="option" data='{"value":"Csoka","state":"Vas"}'>Csoka</div>
<div class="option" data='{"value":"Csokakomajor","state":"Vas"}'>Csokakomajor</div>
<div class="option" data='{"value":"Csomahazi Major","state":"Vas"}'>Csomahazi Major</div>
<div class="option" data='{"value":"Csonkamajor","state":"Vas"}'>Csonkamajor</div>
<div class="option" data='{"value":"Csordajaras","state":"Vas"}'>Csordajaras</div>
<div class="option" data='{"value":"Csorotnek","state":"Vas"}'>Csorotnek</div>
<div class="option" data='{"value":"Czelldomolk","state":"Vas"}'>Czelldomolk</div>
<div class="option" data='{"value":"Daniellamajor","state":"Vas"}'>Daniellamajor</div>
<div class="option" data='{"value":"Davidhaza","state":"Vas"}'>Davidhaza</div>
<div class="option" data='{"value":"Denesdmajor","state":"Vas"}'>Denesdmajor</div>
<div class="option" data='{"value":"Dobjanhegy","state":"Vas"}'>Dobjanhegy</div>
<div class="option" data='{"value":"Dobogoi Hazak","state":"Vas"}'>Dobogoi Hazak</div>
<div class="option" data='{"value":"Dobogoi Szallas","state":"Vas"}'>Dobogoi Szallas</div>
<div class="option" data='{"value":"Doborhegy","state":"Vas"}'>Doborhegy</div>
<div class="option" data='{"value":"Doborhegyi Major","state":"Vas"}'>Doborhegyi Major</div>
<div class="option" data='{"value":"Dombhatimajor","state":"Vas"}'>Dombhatimajor</div>
<div class="option" data='{"value":"Domolki Major","state":"Vas"}'>Domolki Major</div>
<div class="option" data='{"value":"Domotori","state":"Vas"}'>Domotori</div>
<div class="option" data='{"value":"Doroske","state":"Vas"}'>Doroske</div>
<div class="option" data='{"value":"Dozmat","state":"Vas"}'>Dozmat</div>
<div class="option" data='{"value":"Dozsamajor","state":"Vas"}'>Dozsamajor</div>
<div class="option" data='{"value":"Egervolgy","state":"Vas"}'>Egervolgy</div>
<div class="option" data='{"value":"Egonmajor","state":"Vas"}'>Egonmajor</div>
<div class="option" data='{"value":"Egyhazashetye","state":"Vas"}'>Egyhazashetye</div>
<div class="option" data='{"value":"Egyhazashollos","state":"Vas"}'>Egyhazashollos</div>
<div class="option" data='{"value":"Egyhazasradoc","state":"Vas"}'>Egyhazasradoc</div>
<div class="option" data='{"value":"Emiliamajor","state":"Vas"}'>Emiliamajor</div>
<div class="option" data='{"value":"Endredpuszta","state":"Vas"}'>Endredpuszta</div>
<div class="option" data='{"value":"Erdohaza","state":"Vas"}'>Erdohaza</div>
<div class="option" data='{"value":"Erdohaztelep","state":"Vas"}'>Erdohaztelep</div>
<div class="option" data='{"value":"Erzsebetmajor","state":"Vas"}'>Erzsebetmajor</div>
<div class="option" data='{"value":"Estemajor","state":"Vas"}'>Estemajor</div>
<div class="option" data='{"value":"Evamajor","state":"Vas"}'>Evamajor</div>
<div class="option" data='{"value":"Farkaserdo","state":"Vas"}'>Farkaserdo</div>
<div class="option" data='{"value":"Farkasfa","state":"Vas"}'>Farkasfa</div>
<div class="option" data='{"value":"Felsoberkifalu","state":"Vas"}'>Felsoberkifalu</div>
<div class="option" data='{"value":"Felsocsatar","state":"Vas"}'>Felsocsatar</div>
<div class="option" data='{"value":"Felsofutelekimajor","state":"Vas"}'>Felsofutelekimajor</div>
<div class="option" data='{"value":"Felsogyar","state":"Vas"}'>Felsogyar</div>
<div class="option" data='{"value":"Felsojanosfa","state":"Vas"}'>Felsojanosfa</div>
<div class="option" data='{"value":"Felsomajor","state":"Vas"}'>Felsomajor</div>
<div class="option" data='{"value":"Felsomarac","state":"Vas"}'>Felsomarac</div>
<div class="option" data='{"value":"Felsomezo","state":"Vas"}'>Felsomezo</div>
<div class="option" data='{"value":"Felsonyirvarimajor","state":"Vas"}'>Felsonyirvarimajor</div>
<div class="option" data='{"value":"Felsonyirvarmajor","state":"Vas"}'>Felsonyirvarmajor</div>
<div class="option" data='{"value":"Felsopaty","state":"Vas"}'>Felsopaty</div>
<div class="option" data='{"value":"Felsoronok","state":"Vas"}'>Felsoronok</div>
<div class="option" data='{"value":"Felsoszeleste","state":"Vas"}'>Felsoszeleste</div>
<div class="option" data='{"value":"Felsoszolnok","state":"Vas"}'>Felsoszolnok</div>
<div class="option" data='{"value":"Felsotelekesi Major","state":"Vas"}'>Felsotelekesi Major</div>
<div class="option" data='{"value":"Felsotelekesmajor","state":"Vas"}'>Felsotelekesmajor</div>
<div class="option" data='{"value":"Ferdinandmajor","state":"Vas"}'>Ferdinandmajor</div>
<div class="option" data='{"value":"Ferencmajor","state":"Vas"}'>Ferencmajor</div>
<div class="option" data='{"value":"Ferenczmajor","state":"Vas"}'>Ferenczmajor</div>
<div class="option" data='{"value":"Foldvarpuszta","state":"Vas"}'>Foldvarpuszta</div>
<div class="option" data='{"value":"Furdosmajor","state":"Vas"}'>Furdosmajor</div>
<div class="option" data='{"value":"Furesztelep","state":"Vas"}'>Furesztelep</div>
<div class="option" data='{"value":"Futeleki Puszta","state":"Vas"}'>Futeleki Puszta</div>
<div class="option" data='{"value":"Futelekimajor","state":"Vas"}'>Futelekimajor</div>
<div class="option" data='{"value":"Fuztu","state":"Vas"}'>Fuztu</div>
<div class="option" data='{"value":"Gasztony","state":"Vas"}'>Gasztony</div>
<div class="option" data='{"value":"Gencsapati","state":"Vas"}'>Gencsapati</div>
<div class="option" data='{"value":"Gerce","state":"Vas"}'>Gerce</div>
<div class="option" data='{"value":"Gerse","state":"Vas"}'>Gerse</div>
<div class="option" data='{"value":"Gersekarat","state":"Vas"}'>Gersekarat</div>
<div class="option" data='{"value":"Gezamajor","state":"Vas"}'>Gezamajor</div>
<div class="option" data='{"value":"Gizellamajor","state":"Vas"}'>Gizellamajor</div>
<div class="option" data='{"value":"Godorhaza","state":"Vas"}'>Godorhaza</div>
<div class="option" data='{"value":"Goncsegmajor","state":"Vas"}'>Goncsegmajor</div>
<div class="option" data='{"value":"Goncsegpuszta","state":"Vas"}'>Goncsegpuszta</div>
<div class="option" data='{"value":"Gor","state":"Vas"}'>Gor</div>
<div class="option" data='{"value":"Guns","state":"Vas"}'>Guns</div>
<div class="option" data='{"value":"Gurgato","state":"Vas"}'>Gurgato</div>
<div class="option" data='{"value":"Gurgatomajor","state":"Vas"}'>Gurgatomajor</div>
<div class="option" data='{"value":"Gutahaza","state":"Vas"}'>Gutahaza</div>
<div class="option" data='{"value":"Gutatottos","state":"Vas"}'>Gutatottos</div>
<div class="option" data='{"value":"Gyanogeregye","state":"Vas"}'>Gyanogeregye</div>
<div class="option" data='{"value":"Gydnogeregye","state":"Vas"}'>Gydnogeregye</div>
<div class="option" data='{"value":"Gyertyamos","state":"Vas"}'>Gyertyamos</div>
<div class="option" data='{"value":"Gyertyamospuszta","state":"Vas"}'>Gyertyamospuszta</div>
<div class="option" data='{"value":"Gyertyanospuszta","state":"Vas"}'>Gyertyanospuszta</div>
<div class="option" data='{"value":"Gyongyosfalu","state":"Vas"}'>Gyongyosfalu</div>
<div class="option" data='{"value":"Gyongyosherman","state":"Vas"}'>Gyongyosherman</div>
<div class="option" data='{"value":"Gyorgymajor","state":"Vas"}'>Gyorgymajor</div>
<div class="option" data='{"value":"Gyorvar","state":"Vas"}'>Gyorvar</div>
<div class="option" data='{"value":"Gyulahaza","state":"Vas"}'>Gyulahaza</div>
<div class="option" data='{"value":"Gyulekezetimajor","state":"Vas"}'>Gyulekezetimajor</div>
<div class="option" data='{"value":"Hajas","state":"Vas"}'>Hajas</div>
<div class="option" data='{"value":"Halasto","state":"Vas"}'>Halasto</div>
<div class="option" data='{"value":"Halogy","state":"Vas"}'>Halogy</div>
<div class="option" data='{"value":"Harasztifalu","state":"Vas"}'>Harasztifalu</div>
<div class="option" data='{"value":"Haromhaz","state":"Vas"}'>Haromhaz</div>
<div class="option" data='{"value":"Hatlabucsarda","state":"Vas"}'>Hatlabucsarda</div>
<div class="option" data='{"value":"Hegy","state":"Vas"}'>Hegy</div>
<div class="option" data='{"value":"Hegyalja","state":"Vas"}'>Hegyalja</div>
<div class="option" data='{"value":"Hegyfalu","state":"Vas"}'>Hegyfalu</div>
<div class="option" data='{"value":"Hegyhathodasz","state":"Vas"}'>Hegyhathodasz</div>
<div class="option" data='{"value":"Hegyhatsal","state":"Vas"}'>Hegyhatsal</div>
<div class="option" data='{"value":"Hegyhatszentjakab","state":"Vas"}'>Hegyhatszentjakab</div>
<div class="option" data='{"value":"Hegyhatszentmarton","state":"Vas"}'>Hegyhatszentmarton</div>
<div class="option" data='{"value":"Hegyhatszentpeter","state":"Vas"}'>Hegyhatszentpeter</div>
<div class="option" data='{"value":"Hegyhatszentpeteri Major","state":"Vas"}'>Hegyhatszentpeteri Major</div>
<div class="option" data='{"value":"Hercseghegy","state":"Vas"}'>Hercseghegy</div>
<div class="option" data='{"value":"Hereny","state":"Vas"}'>Hereny</div>
<div class="option" data='{"value":"Hertelendytelep","state":"Vas"}'>Hertelendytelep</div>
<div class="option" data='{"value":"Hidas","state":"Vas"}'>Hidas</div>
<div class="option" data='{"value":"Hidashollos","state":"Vas"}'>Hidashollos</div>
<div class="option" data='{"value":"Himfamajor","state":"Vas"}'>Himfamajor</div>
<div class="option" data='{"value":"Homokgodor","state":"Vas"}'>Homokgodor</div>
<div class="option" data='{"value":"Horvatlovo","state":"Vas"}'>Horvatlovo</div>
<div class="option" data='{"value":"Horvatnadalja","state":"Vas"}'>Horvatnadalja</div>
<div class="option" data='{"value":"Horvatzsidany","state":"Vas"}'>Horvatzsidany</div>
<div class="option" data='{"value":"Hossznakdulo","state":"Vas"}'>Hossznakdulo</div>
<div class="option" data='{"value":"Hosszupereszteg","state":"Vas"}'>Hosszupereszteg</div>
<div class="option" data='{"value":"Huszaszialsomajor","state":"Vas"}'>Huszaszialsomajor</div>
<div class="option" data='{"value":"Huszaszimajor","state":"Vas"}'>Huszaszimajor</div>
<div class="option" data='{"value":"Ikervar","state":"Vas"}'>Ikervar</div>
<div class="option" data='{"value":"Ikervari Villanytelep","state":"Vas"}'>Ikervari Villanytelep</div>
<div class="option" data='{"value":"Iklanbereny","state":"Vas"}'>Iklanbereny</div>
<div class="option" data='{"value":"Ilonamajor","state":"Vas"}'>Ilonamajor</div>
<div class="option" data='{"value":"Intahaza","state":"Vas"}'>Intahaza</div>
<div class="option" data='{"value":"Intapuszta","state":"Vas"}'>Intapuszta</div>
<div class="option" data='{"value":"Ispank","state":"Vas"}'>Ispank</div>
<div class="option" data='{"value":"Istvanmajor","state":"Vas"}'>Istvanmajor</div>
<div class="option" data='{"value":"Ivanc","state":"Vas"}'>Ivanc</div>
<div class="option" data='{"value":"Izsakfa","state":"Vas"}'>Izsakfa</div>
<div class="option" data='{"value":"Izsakfaujtelep","state":"Vas"}'>Izsakfaujtelep</div>
<div class="option" data='{"value":"Jak","state":"Vas"}'>Jak</div>
<div class="option" data='{"value":"Jakabhaza","state":"Vas"}'>Jakabhaza</div>
<div class="option" data='{"value":"Jakfa","state":"Vas"}'>Jakfa</div>
<div class="option" data='{"value":"Janoshaza","state":"Vas"}'>Janoshaza</div>
<div class="option" data='{"value":"Janosmajor","state":"Vas"}'>Janosmajor</div>
<div class="option" data='{"value":"Japla","state":"Vas"}'>Japla</div>
<div class="option" data='{"value":"Jozsefmajor","state":"Vas"}'>Jozsefmajor</div>
<div class="option" data='{"value":"Kald","state":"Vas"}'>Kald</div>
<div class="option" data='{"value":"Kam","state":"Vas"}'>Kam</div>
<div class="option" data='{"value":"Kamon","state":"Vas"}'>Kamon</div>
<div class="option" data='{"value":"Kanotapuszta","state":"Vas"}'>Kanotapuszta</div>
<div class="option" data='{"value":"Kanyas","state":"Vas"}'>Kanyas</div>
<div class="option" data='{"value":"Kanyasmajor","state":"Vas"}'>Kanyasmajor</div>
<div class="option" data='{"value":"Kapolna","state":"Vas"}'>Kapolna</div>
<div class="option" data='{"value":"Karako","state":"Vas"}'>Karako</div>
<div class="option" data='{"value":"Karatfold","state":"Vas"}'>Karatfold</div>
<div class="option" data='{"value":"Karolinamajor","state":"Vas"}'>Karolinamajor</div>
<div class="option" data='{"value":"Karolymajor","state":"Vas"}'>Karolymajor</div>
<div class="option" data='{"value":"Katafa","state":"Vas"}'>Katafa</div>
<div class="option" data='{"value":"Keled","state":"Vas"}'>Keled</div>
<div class="option" data='{"value":"Kelemenmajor","state":"Vas"}'>Kelemenmajor</div>
<div class="option" data='{"value":"Kemeneskapolna","state":"Vas"}'>Kemeneskapolna</div>
<div class="option" data='{"value":"Kemenesmagasi","state":"Vas"}'>Kemenesmagasi</div>
<div class="option" data='{"value":"Kemenesmihalyfa","state":"Vas"}'>Kemenesmihalyfa</div>
<div class="option" data='{"value":"Kemenespalfa","state":"Vas"}'>Kemenespalfa</div>
<div class="option" data='{"value":"Kemenespuszta","state":"Vas"}'>Kemenespuszta</div>
<div class="option" data='{"value":"Kemenessomjen","state":"Vas"}'>Kemenessomjen</div>
<div class="option" data='{"value":"Kemenesszentmarton","state":"Vas"}'>Kemenesszentmarton</div>
<div class="option" data='{"value":"Kemesmal","state":"Vas"}'>Kemesmal</div>
<div class="option" data='{"value":"Kemestarodfa","state":"Vas"}'>Kemestarodfa</div>
<div class="option" data='{"value":"Kenez","state":"Vas"}'>Kenez</div>
<div class="option" data='{"value":"Kenyeri","state":"Vas"}'>Kenyeri</div>
<div class="option" data='{"value":"Kercaszomor","state":"Vas"}'>Kercaszomor</div>
<div class="option" data='{"value":"Keresztmajor","state":"Vas"}'>Keresztmajor</div>
<div class="option" data='{"value":"Kerkaskapolna","state":"Vas"}'>Kerkaskapolna</div>
<div class="option" data='{"value":"Ketvolgy","state":"Vas"}'>Ketvolgy</div>
<div class="option" data='{"value":"Kincsedpuszta","state":"Vas"}'>Kincsedpuszta</div>
<div class="option" data='{"value":"Kiralyvolgy","state":"Vas"}'>Kiralyvolgy</div>
<div class="option" data='{"value":"Kiscsakanypuszta","state":"Vas"}'>Kiscsakanypuszta</div>
<div class="option" data='{"value":"Kiscsomote","state":"Vas"}'>Kiscsomote</div>
<div class="option" data='{"value":"Kisdoborhegy","state":"Vas"}'>Kisdoborhegy</div>
<div class="option" data='{"value":"Kisgecseny","state":"Vas"}'>Kisgecseny</div>
<div class="option" data='{"value":"Kisgecsenymajor","state":"Vas"}'>Kisgecsenymajor</div>
<div class="option" data='{"value":"Kishalogy","state":"Vas"}'>Kishalogy</div>
<div class="option" data='{"value":"Kishalogy Also","state":"Vas"}'>Kishalogy Also</div>
<div class="option" data='{"value":"Kishalogy Felso","state":"Vas"}'>Kishalogy Felso</div>
<div class="option" data='{"value":"Kishegy","state":"Vas"}'>Kishegy</div>
<div class="option" data='{"value":"Kiskocsk","state":"Vas"}'>Kiskocsk</div>
<div class="option" data='{"value":"Kiskoveshegy","state":"Vas"}'>Kiskoveshegy</div>
<div class="option" data='{"value":"Kismajor","state":"Vas"}'>Kismajor</div>
<div class="option" data='{"value":"Kismakfa","state":"Vas"}'>Kismakfa</div>
<div class="option" data='{"value":"Kismezo","state":"Vas"}'>Kismezo</div>
<div class="option" data='{"value":"Kisnarda","state":"Vas"}'>Kisnarda</div>
<div class="option" data='{"value":"Kisolbo","state":"Vas"}'>Kisolbo</div>
<div class="option" data='{"value":"Kispeterfa","state":"Vas"}'>Kispeterfa</div>
<div class="option" data='{"value":"Kisradoc","state":"Vas"}'>Kisradoc</div>
<div class="option" data='{"value":"Kisradocz","state":"Vas"}'>Kisradocz</div>
<div class="option" data='{"value":"Kisrakos","state":"Vas"}'>Kisrakos</div>
<div class="option" data='{"value":"Kissaroslak","state":"Vas"}'>Kissaroslak</div>
<div class="option" data='{"value":"Kissitke","state":"Vas"}'>Kissitke</div>
<div class="option" data='{"value":"Kissomlyo","state":"Vas"}'>Kissomlyo</div>
<div class="option" data='{"value":"Kisunyom","state":"Vas"}'>Kisunyom</div>
<div class="option" data='{"value":"Kiszsennye","state":"Vas"}'>Kiszsennye</div>
<div class="option" data='{"value":"Kiszsennyemajor","state":"Vas"}'>Kiszsennyemajor</div>
<div class="option" data='{"value":"Kiszsidany","state":"Vas"}'>Kiszsidany</div>
<div class="option" data='{"value":"Klaramajor","state":"Vas"}'>Klaramajor</div>
<div class="option" data='{"value":"Kocsk","state":"Vas"}'>Kocsk</div>
<div class="option" data='{"value":"Kondorfa","state":"Vas"}'>Kondorfa</div>
<div class="option" data='{"value":"Konradmajor","state":"Vas"}'>Konradmajor</div>
<div class="option" data='{"value":"Koponyas","state":"Vas"}'>Koponyas</div>
<div class="option" data='{"value":"Koponyas es Kornyeke","state":"Vas"}'>Koponyas es Kornyeke</div>
<div class="option" data='{"value":"Kormend","state":"Vas"}'>Kormend</div>
<div class="option" data='{"value":"Korpamajor","state":"Vas"}'>Korpamajor</div>
<div class="option" data='{"value":"Kortvelyesmajor","state":"Vas"}'>Kortvelyesmajor</div>
<div class="option" data='{"value":"Kortvelyespuszta","state":"Vas"}'>Kortvelyespuszta</div>
<div class="option" data='{"value":"Koszeg","state":"Vas"}'>Koszeg</div>
<div class="option" data='{"value":"Koszegdoroszlo","state":"Vas"}'>Koszegdoroszlo</div>
<div class="option" data='{"value":"Koszegfalva","state":"Vas"}'>Koszegfalva</div>
<div class="option" data='{"value":"Koszegpaty","state":"Vas"}'>Koszegpaty</div>
<div class="option" data='{"value":"Koszegszerdahely","state":"Vas"}'>Koszegszerdahely</div>
<div class="option" data='{"value":"Koszegszerhadely","state":"Vas"}'>Koszegszerhadely</div>
<div class="option" data='{"value":"Kosztolanci Tanya","state":"Vas"}'>Kosztolanci Tanya</div>
<div class="option" data='{"value":"Kosztolanczitanya","state":"Vas"}'>Kosztolanczitanya</div>
<div class="option" data='{"value":"Kotormany","state":"Vas"}'>Kotormany</div>
<div class="option" data='{"value":"Kozarmajor","state":"Vas"}'>Kozarmajor</div>
<div class="option" data='{"value":"Kozarpuszta","state":"Vas"}'>Kozarpuszta</div>
<div class="option" data='{"value":"Kozepmajor","state":"Vas"}'>Kozepmajor</div>
<div class="option" data='{"value":"Kozepmalom","state":"Vas"}'>Kozepmalom</div>
<div class="option" data='{"value":"Kozepnyirvarmajor","state":"Vas"}'>Kozepnyirvarmajor</div>
<div class="option" data='{"value":"Kozmafa","state":"Vas"}'>Kozmafa</div>
<div class="option" data='{"value":"Kozmaolaszfa","state":"Vas"}'>Kozmaolaszfa</div>
<div class="option" data='{"value":"Kukucsamajor","state":"Vas"}'>Kukucsamajor</div>
<div class="option" data='{"value":"Kulsomajor","state":"Vas"}'>Kulsomajor</div>
<div class="option" data='{"value":"Kurconmajor","state":"Vas"}'>Kurconmajor</div>
<div class="option" data='{"value":"Kurczonmajor","state":"Vas"}'>Kurczonmajor</div>
<div class="option" data='{"value":"Lajerhazidulo","state":"Vas"}'>Lajerhazidulo</div>
<div class="option" data='{"value":"Lajosmajor","state":"Vas"}'>Lajosmajor</div>
<div class="option" data='{"value":"Lajostelep","state":"Vas"}'>Lajostelep</div>
<div class="option" data='{"value":"Lankapuszta","state":"Vas"}'>Lankapuszta</div>
<div class="option" data='{"value":"Laszlomajor","state":"Vas"}'>Laszlomajor</div>
<div class="option" data='{"value":"Lempegtanya","state":"Vas"}'>Lempegtanya</div>
<div class="option" data='{"value":"Leventehegy","state":"Vas"}'>Leventehegy</div>
<div class="option" data='{"value":"Lipart","state":"Vas"}'>Lipart</div>
<div class="option" data='{"value":"Lipoldamajor","state":"Vas"}'>Lipoldamajor</div>
<div class="option" data='{"value":"Locs","state":"Vas"}'>Locs</div>
<div class="option" data='{"value":"Lorinctanya","state":"Vas"}'>Lorinctanya</div>
<div class="option" data='{"value":"Lukacshaza","state":"Vas"}'>Lukacshaza</div>
<div class="option" data='{"value":"Macfa","state":"Vas"}'>Macfa</div>
<div class="option" data='{"value":"Macfamajor","state":"Vas"}'>Macfamajor</div>
<div class="option" data='{"value":"Magyarbukos","state":"Vas"}'>Magyarbukos</div>
<div class="option" data='{"value":"Magyarbukstelep","state":"Vas"}'>Magyarbukstelep</div>
<div class="option" data='{"value":"Magyarlak","state":"Vas"}'>Magyarlak</div>
<div class="option" data='{"value":"Magyarnadalja","state":"Vas"}'>Magyarnadalja</div>
<div class="option" data='{"value":"Magyarszecsod","state":"Vas"}'>Magyarszecsod</div>
<div class="option" data='{"value":"Magyarszombatfa","state":"Vas"}'>Magyarszombatfa</div>
<div class="option" data='{"value":"Malomtelep","state":"Vas"}'>Malomtelep</div>
<div class="option" data='{"value":"Manettamajor","state":"Vas"}'>Manettamajor</div>
<div class="option" data='{"value":"Marcali major","state":"Vas"}'>Marcali major</div>
<div class="option" data='{"value":"Marcalmajor","state":"Vas"}'>Marcalmajor</div>
<div class="option" data='{"value":"Margithaza","state":"Vas"}'>Margithaza</div>
<div class="option" data='{"value":"Margitmajor","state":"Vas"}'>Margitmajor</div>
<div class="option" data='{"value":"Mariamajor","state":"Vas"}'>Mariamajor</div>
<div class="option" data='{"value":"Mariatanya","state":"Vas"}'>Mariatanya</div>
<div class="option" data='{"value":"Mariaujfalu","state":"Vas"}'>Mariaujfalu</div>
<div class="option" data='{"value":"Meggyeskovacsi","state":"Vas"}'>Meggyeskovacsi</div>
<div class="option" data='{"value":"Meggyespuszta","state":"Vas"}'>Meggyespuszta</div>
<div class="option" data='{"value":"Megyehid","state":"Vas"}'>Megyehid</div>
<div class="option" data='{"value":"Menestelep","state":"Vas"}'>Menestelep</div>
<div class="option" data='{"value":"Mentelep","state":"Vas"}'>Mentelep</div>
<div class="option" data='{"value":"Merse","state":"Vas"}'>Merse</div>
<div class="option" data='{"value":"Mersevat","state":"Vas"}'>Mersevat</div>
<div class="option" data='{"value":"Mesterhaza","state":"Vas"}'>Mesterhaza</div>
<div class="option" data='{"value":"Mesteri","state":"Vas"}'>Mesteri</div>
<div class="option" data='{"value":"Meszlen","state":"Vas"}'>Meszlen</div>
<div class="option" data='{"value":"Metnekpuszta","state":"Vas"}'>Metnekpuszta</div>
<div class="option" data='{"value":"Mihalyfa","state":"Vas"}'>Mihalyfa</div>
<div class="option" data='{"value":"Mikosdkastely","state":"Vas"}'>Mikosdkastely</div>
<div class="option" data='{"value":"Mikosdpuszta","state":"Vas"}'>Mikosdpuszta</div>
<div class="option" data='{"value":"Mikosszeplak","state":"Vas"}'>Mikosszeplak</div>
<div class="option" data='{"value":"Mikosszeplaki Mezo","state":"Vas"}'>Mikosszeplaki Mezo</div>
<div class="option" data='{"value":"Molnaszecsod","state":"Vas"}'>Molnaszecsod</div>
<div class="option" data='{"value":"Muhelytelep","state":"Vas"}'>Muhelytelep</div>
<div class="option" data='{"value":"Nadasd","state":"Vas"}'>Nadasd</div>
<div class="option" data='{"value":"Nadcakanj","state":"Vas"}'>Nadcakanj</div>
<div class="option" data='{"value":"Nagy Janos Major","state":"Vas"}'>Nagy Janos Major</div>
<div class="option" data='{"value":"Nagy Retimajor","state":"Vas"}'>Nagy Retimajor</div>
<div class="option" data='{"value":"Nagycsomote","state":"Vas"}'>Nagycsomote</div>
<div class="option" data='{"value":"Nagyecseny","state":"Vas"}'>Nagyecseny</div>
<div class="option" data='{"value":"Nagygecsenymajor","state":"Vas"}'>Nagygecsenymajor</div>
<div class="option" data='{"value":"Nagygeresd","state":"Vas"}'>Nagygeresd</div>
<div class="option" data='{"value":"Nagyjaplani Major","state":"Vas"}'>Nagyjaplani Major</div>
<div class="option" data='{"value":"Nagykocsk","state":"Vas"}'>Nagykocsk</div>
<div class="option" data='{"value":"Nagykolked","state":"Vas"}'>Nagykolked</div>
<div class="option" data='{"value":"Nagymakfa","state":"Vas"}'>Nagymakfa</div>
<div class="option" data='{"value":"Nagymizdo","state":"Vas"}'>Nagymizdo</div>
<div class="option" data='{"value":"Nagynarda","state":"Vas"}'>Nagynarda</div>
<div class="option" data='{"value":"Nagyrakos","state":"Vas"}'>Nagyrakos</div>
<div class="option" data='{"value":"Nagysimonyi","state":"Vas"}'>Nagysimonyi</div>
<div class="option" data='{"value":"Nagysitke","state":"Vas"}'>Nagysitke</div>
<div class="option" data='{"value":"Nagytilaj","state":"Vas"}'>Nagytilaj</div>
<div class="option" data='{"value":"Nagytilaji Hegy","state":"Vas"}'>Nagytilaji Hegy</div>
<div class="option" data='{"value":"Nandormajor","state":"Vas"}'>Nandormajor</div>
<div class="option" data='{"value":"Narai","state":"Vas"}'>Narai</div>
<div class="option" data='{"value":"Narda","state":"Vas"}'>Narda</div>
<div class="option" data='{"value":"Nemesbod","state":"Vas"}'>Nemesbod</div>
<div class="option" data='{"value":"Nemescso","state":"Vas"}'>Nemescso</div>
<div class="option" data='{"value":"Nemeskeresztur","state":"Vas"}'>Nemeskeresztur</div>
<div class="option" data='{"value":"Nemeskocs","state":"Vas"}'>Nemeskocs</div>
<div class="option" data='{"value":"Nemeskolta","state":"Vas"}'>Nemeskolta</div>
<div class="option" data='{"value":"Nemesladony","state":"Vas"}'>Nemesladony</div>
<div class="option" data='{"value":"Nemesmedves","state":"Vas"}'>Nemesmedves</div>
<div class="option" data='{"value":"Nemesrempehollos","state":"Vas"}'>Nemesrempehollos</div>
<div class="option" data='{"value":"Nemetfalumajor","state":"Vas"}'>Nemetfalumajor</div>
<div class="option" data='{"value":"Nemetzsidany","state":"Vas"}'>Nemetzsidany</div>
<div class="option" data='{"value":"Nick","state":"Vas"}'>Nick</div>
<div class="option" data='{"value":"Novaktanya","state":"Vas"}'>Novaktanya</div>
<div class="option" data='{"value":"Nyestemajor","state":"Vas"}'>Nyestemajor</div>
<div class="option" data='{"value":"Nyoger","state":"Vas"}'>Nyoger</div>
<div class="option" data='{"value":"Olad","state":"Vas"}'>Olad</div>
<div class="option" data='{"value":"Olaszfa","state":"Vas"}'>Olaszfa</div>
<div class="option" data='{"value":"Olaszka","state":"Vas"}'>Olaszka</div>
<div class="option" data='{"value":"Olbo","state":"Vas"}'>Olbo</div>
<div class="option" data='{"value":"Olmod","state":"Vas"}'>Olmod</div>
<div class="option" data='{"value":"Omajor","state":"Vas"}'>Omajor</div>
<div class="option" data='{"value":"Ondod","state":"Vas"}'>Ondod</div>
<div class="option" data='{"value":"Orbantanya","state":"Vas"}'>Orbantanya</div>
<div class="option" data='{"value":"Orfalu","state":"Vas"}'>Orfalu</div>
<div class="option" data='{"value":"Orimagyarosd","state":"Vas"}'>Orimagyarosd</div>
<div class="option" data='{"value":"Oriszentpeter","state":"Vas"}'>Oriszentpeter</div>
<div class="option" data='{"value":"Ostffyasszonyfa","state":"Vas"}'>Ostffyasszonyfa</div>
<div class="option" data='{"value":"Ostsfyasszonvfa","state":"Vas"}'>Ostsfyasszonvfa</div>
<div class="option" data='{"value":"Oszko","state":"Vas"}'>Oszko</div>
<div class="option" data='{"value":"Pacsony","state":"Vas"}'>Pacsony</div>
<div class="option" data='{"value":"Pacsonyujmajor","state":"Vas"}'>Pacsonyujmajor</div>
<div class="option" data='{"value":"Pacsonyujtelep","state":"Vas"}'>Pacsonyujtelep</div>
<div class="option" data='{"value":"Palmajor","state":"Vas"}'>Palmajor</div>
<div class="option" data='{"value":"Pankasz","state":"Vas"}'>Pankasz</div>
<div class="option" data='{"value":"Papoc","state":"Vas"}'>Papoc</div>
<div class="option" data='{"value":"Pecol","state":"Vas"}'>Pecol</div>
<div class="option" data='{"value":"Pecolrozsamajor","state":"Vas"}'>Pecolrozsamajor</div>
<div class="option" data='{"value":"Perecmajor","state":"Vas"}'>Perecmajor</div>
<div class="option" data='{"value":"Perenye","state":"Vas"}'>Perenye</div>
<div class="option" data='{"value":"Peresznye","state":"Vas"}'>Peresznye</div>
<div class="option" data='{"value":"Peresztegtacskand","state":"Vas"}'>Peresztegtacskand</div>
<div class="option" data='{"value":"Perint","state":"Vas"}'>Perint</div>
<div class="option" data='{"value":"Peterfa","state":"Vas"}'>Peterfa</div>
<div class="option" data='{"value":"Peterfapuszta","state":"Vas"}'>Peterfapuszta</div>
<div class="option" data='{"value":"Petofa","state":"Vas"}'>Petofa</div>
<div class="option" data='{"value":"Petomihalyfa","state":"Vas"}'>Petomihalyfa</div>
<div class="option" data='{"value":"Pinkamindszent","state":"Vas"}'>Pinkamindszent</div>
<div class="option" data='{"value":"Pletnicsmajor","state":"Vas"}'>Pletnicsmajor</div>
<div class="option" data='{"value":"Pokhaza","state":"Vas"}'>Pokhaza</div>
<div class="option" data='{"value":"Polgar","state":"Vas"}'>Polgar</div>
<div class="option" data='{"value":"Polgarhegy","state":"Vas"}'>Polgarhegy</div>
<div class="option" data='{"value":"Pornoapati","state":"Vas"}'>Pornoapati</div>
<div class="option" data='{"value":"Porpac","state":"Vas"}'>Porpac</div>
<div class="option" data='{"value":"Porpaczytanya","state":"Vas"}'>Porpaczytanya</div>
<div class="option" data='{"value":"Pose","state":"Vas"}'>Pose</div>
<div class="option" data='{"value":"Posfa","state":"Vas"}'>Posfa</div>
<div class="option" data='{"value":"Potypuszta","state":"Vas"}'>Potypuszta</div>
<div class="option" data='{"value":"Potyrozsamajor","state":"Vas"}'>Potyrozsamajor</div>
<div class="option" data='{"value":"Puspokmolnari","state":"Vas"}'>Puspokmolnari</div>
<div class="option" data='{"value":"Puspoktamasi","state":"Vas"}'>Puspoktamasi</div>
<div class="option" data='{"value":"Pusztacso","state":"Vas"}'>Pusztacso</div>
<div class="option" data='{"value":"Pusztalanc","state":"Vas"}'>Pusztalanc</div>
<div class="option" data='{"value":"Putrimajor","state":"Vas"}'>Putrimajor</div>
<div class="option" data='{"value":"Rababogyoszlo","state":"Vas"}'>Rababogyoszlo</div>
<div class="option" data='{"value":"Rabafuzes","state":"Vas"}'>Rabafuzes</div>
<div class="option" data='{"value":"Rabagyarmat","state":"Vas"}'>Rabagyarmat</div>
<div class="option" data='{"value":"Rabahidveg","state":"Vas"}'>Rabahidveg</div>
<div class="option" data='{"value":"Rabakecsed","state":"Vas"}'>Rabakecsed</div>
<div class="option" data='{"value":"Rabakethely","state":"Vas"}'>Rabakethely</div>
<div class="option" data='{"value":"Rabakisfalud","state":"Vas"}'>Rabakisfalud</div>
<div class="option" data='{"value":"Rabakovacsi","state":"Vas"}'>Rabakovacsi</div>
<div class="option" data='{"value":"Rabakovesd","state":"Vas"}'>Rabakovesd</div>
<div class="option" data='{"value":"Rabamolnari","state":"Vas"}'>Rabamolnari</div>
<div class="option" data='{"value":"Rabanalul","state":"Vas"}'>Rabanalul</div>
<div class="option" data='{"value":"Rabapaty","state":"Vas"}'>Rabapaty</div>
<div class="option" data='{"value":"Rabapuspoki","state":"Vas"}'>Rabapuspoki</div>
<div class="option" data='{"value":"Rabasomjen","state":"Vas"}'>Rabasomjen</div>
<div class="option" data='{"value":"Rabaszenttamas","state":"Vas"}'>Rabaszenttamas</div>
<div class="option" data='{"value":"Rabatotfalu","state":"Vas"}'>Rabatotfalu</div>
<div class="option" data='{"value":"Radockolked","state":"Vas"}'>Radockolked</div>
<div class="option" data='{"value":"Radocujfalu","state":"Vas"}'>Radocujfalu</div>
<div class="option" data='{"value":"Radohaza","state":"Vas"}'>Radohaza</div>
<div class="option" data='{"value":"Radohazapuszta","state":"Vas"}'>Radohazapuszta</div>
<div class="option" data='{"value":"Radohegy","state":"Vas"}'>Radohegy</div>
<div class="option" data='{"value":"Radomajor","state":"Vas"}'>Radomajor</div>
<div class="option" data='{"value":"Radopuszta","state":"Vas"}'>Radopuszta</div>
<div class="option" data='{"value":"Ragyogo","state":"Vas"}'>Ragyogo</div>
<div class="option" data='{"value":"Ratot","state":"Vas"}'>Ratot</div>
<div class="option" data='{"value":"Redeymajor","state":"Vas"}'>Redeymajor</div>
<div class="option" data='{"value":"Repcelak","state":"Vas"}'>Repcelak</div>
<div class="option" data='{"value":"Repcelaki Tanya","state":"Vas"}'>Repcelaki Tanya</div>
<div class="option" data='{"value":"Repceszentgyorgy","state":"Vas"}'>Repceszentgyorgy</div>
<div class="option" data='{"value":"Retimajor","state":"Vas"}'>Retimajor</div>
<div class="option" data='{"value":"Ribaritstanya","state":"Vas"}'>Ribaritstanya</div>
<div class="option" data='{"value":"Richardmajor","state":"Vas"}'>Richardmajor</div>
<div class="option" data='{"value":"Rimany","state":"Vas"}'>Rimany</div>
<div class="option" data='{"value":"Rimanymajor","state":"Vas"}'>Rimanymajor</div>
<div class="option" data='{"value":"Ritkahaza","state":"Vas"}'>Ritkahaza</div>
<div class="option" data='{"value":"Ronok","state":"Vas"}'>Ronok</div>
<div class="option" data='{"value":"Rotivolgy","state":"Vas"}'>Rotivolgy</div>
<div class="option" data='{"value":"Rozsamajor","state":"Vas"}'>Rozsamajor</div>
<div class="option" data='{"value":"Rum","state":"Vas"}'>Rum</div>
<div class="option" data='{"value":"Sabaria","state":"Vas"}'>Sabaria</div>
<div class="option" data='{"value":"Saghegy","state":"Vas"}'>Saghegy</div>
<div class="option" data='{"value":"Sajtoskal","state":"Vas"}'>Sajtoskal</div>
<div class="option" data='{"value":"Salkoveskut","state":"Vas"}'>Salkoveskut</div>
<div class="option" data='{"value":"Sandorhaza","state":"Vas"}'>Sandorhaza</div>
<div class="option" data='{"value":"Sandorhazamajor","state":"Vas"}'>Sandorhazamajor</div>
<div class="option" data='{"value":"Sandorhazimajor","state":"Vas"}'>Sandorhazimajor</div>
<div class="option" data='{"value":"Sandormajor","state":"Vas"}'>Sandormajor</div>
<div class="option" data='{"value":"Santavolgy","state":"Vas"}'>Santavolgy</div>
<div class="option" data='{"value":"Sardipuszta","state":"Vas"}'>Sardipuszta</div>
<div class="option" data='{"value":"Sarfimizdo","state":"Vas"}'>Sarfimizdo</div>
<div class="option" data='{"value":"Saroltamajor","state":"Vas"}'>Saroltamajor</div>
<div class="option" data='{"value":"Sarsziget","state":"Vas"}'>Sarsziget</div>
<div class="option" data='{"value":"Sarvar","state":"Vas"}'>Sarvar</div>
<div class="option" data='{"value":"Sarvolgymajor","state":"Vas"}'>Sarvolgymajor</div>
<div class="option" data='{"value":"Savar","state":"Vas"}'>Savar</div>
<div class="option" data='{"value":"Savaria","state":"Vas"}'>Savaria</div>
<div class="option" data='{"value":"Se","state":"Vas"}'>Se</div>
<div class="option" data='{"value":"Seregelyhazamajor","state":"Vas"}'>Seregelyhazamajor</div>
<div class="option" data='{"value":"Seregelyhazi Major","state":"Vas"}'>Seregelyhazi Major</div>
<div class="option" data='{"value":"Simahaza","state":"Vas"}'>Simahaza</div>
<div class="option" data='{"value":"Simasag","state":"Vas"}'>Simasag</div>
<div class="option" data='{"value":"Sitke","state":"Vas"}'>Sitke</div>
<div class="option" data='{"value":"Skultethymajor","state":"Vas"}'>Skultethymajor</div>
<div class="option" data='{"value":"Somjen","state":"Vas"}'>Somjen</div>
<div class="option" data='{"value":"Soospuszta","state":"Vas"}'>Soospuszta</div>
<div class="option" data='{"value":"Sopte","state":"Vas"}'>Sopte</div>
<div class="option" data='{"value":"Sorkifalud","state":"Vas"}'>Sorkifalud</div>
<div class="option" data='{"value":"Sorkikapolna","state":"Vas"}'>Sorkikapolna</div>
<div class="option" data='{"value":"Sorkikisfalud","state":"Vas"}'>Sorkikisfalud</div>
<div class="option" data='{"value":"Sorkipolany","state":"Vas"}'>Sorkipolany</div>
<div class="option" data='{"value":"Sorkitotfalu","state":"Vas"}'>Sorkitotfalu</div>
<div class="option" data='{"value":"Sorokpolany","state":"Vas"}'>Sorokpolany</div>
<div class="option" data='{"value":"Sorokpuszta","state":"Vas"}'>Sorokpuszta</div>
<div class="option" data='{"value":"Sorokujfalu","state":"Vas"}'>Sorokujfalu</div>
<div class="option" data='{"value":"Sosmajor","state":"Vas"}'>Sosmajor</div>
<div class="option" data='{"value":"Sotony","state":"Vas"}'>Sotony</div>
<div class="option" data='{"value":"Spiccermajor","state":"Vas"}'>Spiccermajor</div>
<div class="option" data='{"value":"Spitzermajor","state":"Vas"}'>Spitzermajor</div>
<div class="option" data='{"value":"Stajerhazak","state":"Vas"}'>Stajerhazak</div>
<div class="option" data='{"value":"Stayerhazak","state":"Vas"}'>Stayerhazak</div>
<div class="option" data='{"value":"Steinamanger","state":"Vas"}'>Steinamanger</div>
<div class="option" data='{"value":"Sultfejmajor","state":"Vas"}'>Sultfejmajor</div>
<div class="option" data='{"value":"Szabohegy","state":"Vas"}'>Szabohegy</div>
<div class="option" data='{"value":"Szabohegytelep","state":"Vas"}'>Szabohegytelep</div>
<div class="option" data='{"value":"Szabotanya","state":"Vas"}'>Szabotanya</div>
<div class="option" data='{"value":"Szajkpuszta","state":"Vas"}'>Szajkpuszta</div>
<div class="option" data='{"value":"Szaknyer","state":"Vas"}'>Szaknyer</div>
<div class="option" data='{"value":"Szakonyfalu","state":"Vas"}'>Szakonyfalu</div>
<div class="option" data='{"value":"Szalafo","state":"Vas"}'>Szalafo</div>
<div class="option" data='{"value":"Szallashely","state":"Vas"}'>Szallashely</div>
<div class="option" data='{"value":"Szallashelyimajor","state":"Vas"}'>Szallashelyimajor</div>
<div class="option" data='{"value":"Szarvaskend","state":"Vas"}'>Szarvaskend</div>
<div class="option" data='{"value":"Szarvaskendi Major","state":"Vas"}'>Szarvaskendi Major</div>
<div class="option" data='{"value":"Szatta","state":"Vas"}'>Szatta</div>
<div class="option" data='{"value":"Szeleste","state":"Vas"}'>Szeleste</div>
<div class="option" data='{"value":"Szemenye","state":"Vas"}'>Szemenye</div>
<div class="option" data='{"value":"Szentgotthard","state":"Vas"}'>Szentgotthard</div>
<div class="option" data='{"value":"Szentgyorgy","state":"Vas"}'>Szentgyorgy</div>
<div class="option" data='{"value":"Szentimre Hegykozseg","state":"Vas"}'>Szentimre Hegykozseg</div>
<div class="option" data='{"value":"Szentivanfa","state":"Vas"}'>Szentivanfa</div>
<div class="option" data='{"value":"Szentkeresztmajor","state":"Vas"}'>Szentkeresztmajor</div>
<div class="option" data='{"value":"Szentkiraly","state":"Vas"}'>Szentkiraly</div>
<div class="option" data='{"value":"Szentlerant","state":"Vas"}'>Szentlerant</div>
<div class="option" data='{"value":"Szentodorfa","state":"Vas"}'>Szentodorfa</div>
<div class="option" data='{"value":"Szentpeterfa","state":"Vas"}'>Szentpeterfa</div>
<div class="option" data='{"value":"Szepvolgy","state":"Vas"}'>Szepvolgy</div>
<div class="option" data='{"value":"Szepvolgyimajor","state":"Vas"}'>Szepvolgyimajor</div>
<div class="option" data='{"value":"Szepvolgymajor","state":"Vas"}'>Szepvolgymajor</div>
<div class="option" data='{"value":"Szergeny","state":"Vas"}'>Szergeny</div>
<div class="option" data='{"value":"Szinese","state":"Vas"}'>Szinese</div>
<div class="option" data='{"value":"Szinesemajor","state":"Vas"}'>Szinesemajor</div>
<div class="option" data='{"value":"Szoce","state":"Vas"}'>Szoce</div>
<div class="option" data='{"value":"Szocze","state":"Vas"}'>Szocze</div>
<div class="option" data='{"value":"Szollokalja","state":"Vas"}'>Szollokalja</div>
<div class="option" data='{"value":"Szombatehly","state":"Vas"}'>Szombatehly</div>
<div class="option" data='{"value":"Szombathely","state":"Vas"}'>Szombathely</div>
<div class="option" data='{"value":"Szombatnely","state":"Vas"}'>Szombatnely</div>
<div class="option" data='{"value":"Szunyogmajor","state":"Vas"}'>Szunyogmajor</div>
<div class="option" data='{"value":"Talapatka","state":"Vas"}'>Talapatka</div>
<div class="option" data='{"value":"Tanakajd","state":"Vas"}'>Tanakajd</div>
<div class="option" data='{"value":"Taplanszentkereszt","state":"Vas"}'>Taplanszentkereszt</div>
<div class="option" data='{"value":"Tarodhaza","state":"Vas"}'>Tarodhaza</div>
<div class="option" data='{"value":"Teget","state":"Vas"}'>Teget</div>
<div class="option" data='{"value":"Tegetmajor","state":"Vas"}'>Tegetmajor</div>
<div class="option" data='{"value":"Teglaegeto","state":"Vas"}'>Teglaegeto</div>
<div class="option" data='{"value":"Telekes","state":"Vas"}'>Telekes</div>
<div class="option" data='{"value":"Terestyenjakfa","state":"Vas"}'>Terestyenjakfa</div>
<div class="option" data='{"value":"Tizenharomsoros","state":"Vas"}'>Tizenharomsoros</div>
<div class="option" data='{"value":"Tizenharomvaros","state":"Vas"}'>Tizenharomvaros</div>
<div class="option" data='{"value":"Tokorcs","state":"Vas"}'>Tokorcs</div>
<div class="option" data='{"value":"Tomajor","state":"Vas"}'>Tomajor</div>
<div class="option" data='{"value":"Tomord","state":"Vas"}'>Tomord</div>
<div class="option" data='{"value":"Tompaladony","state":"Vas"}'>Tompaladony</div>
<div class="option" data='{"value":"Tordasiujmajor","state":"Vas"}'>Tordasiujmajor</div>
<div class="option" data='{"value":"Torony","state":"Vas"}'>Torony</div>
<div class="option" data='{"value":"Totfalupuszta","state":"Vas"}'>Totfalupuszta</div>
<div class="option" data='{"value":"Trombitasmalom","state":"Vas"}'>Trombitasmalom</div>
<div class="option" data='{"value":"Tucsokmajor","state":"Vas"}'>Tucsokmajor</div>
<div class="option" data='{"value":"Turbina","state":"Vas"}'>Turbina</div>
<div class="option" data='{"value":"Ujbalazsfalva","state":"Vas"}'>Ujbalazsfalva</div>
<div class="option" data='{"value":"Ujhegy","state":"Vas"}'>Ujhegy</div>
<div class="option" data='{"value":"Ujkut","state":"Vas"}'>Ujkut</div>
<div class="option" data='{"value":"Ujmajor","state":"Vas"}'>Ujmajor</div>
<div class="option" data='{"value":"Ujmihalyfa","state":"Vas"}'>Ujmihalyfa</div>
<div class="option" data='{"value":"Ujtelep","state":"Vas"}'>Ujtelep</div>
<div class="option" data='{"value":"Uraiujfalu","state":"Vas"}'>Uraiujfalu</div>
<div class="option" data='{"value":"Urszegmajor","state":"Vas"}'>Urszegmajor</div>
<div class="option" data='{"value":"Vamoscsalad","state":"Vas"}'>Vamoscsalad</div>
<div class="option" data='{"value":"Vargatanya","state":"Vas"}'>Vargatanya</div>
<div class="option" data='{"value":"Varoserdo","state":"Vas"}'>Varoserdo</div>
<div class="option" data='{"value":"Vas","state":"Vas"}'>Vas</div>
<div class="option" data='{"value":"Vas County","state":"Vas"}'>Vas County</div>
<div class="option" data='{"value":"Vas Megye","state":"Vas"}'>Vas Megye</div>
<div class="option" data='{"value":"Vasalja","state":"Vas"}'>Vasalja</div>
<div class="option" data='{"value":"Vasarosmiske","state":"Vas"}'>Vasarosmiske</div>
<div class="option" data='{"value":"Vasasszonyfa","state":"Vas"}'>Vasasszonyfa</div>
<div class="option" data='{"value":"Vasegerszeg","state":"Vas"}'>Vasegerszeg</div>
<div class="option" data='{"value":"Vashegy","state":"Vas"}'>Vashegy</div>
<div class="option" data='{"value":"Vashegyalja","state":"Vas"}'>Vashegyalja</div>
<div class="option" data='{"value":"Vashosszufalu","state":"Vas"}'>Vashosszufalu</div>
<div class="option" data='{"value":"Vaskeresztes","state":"Vas"}'>Vaskeresztes</div>
<div class="option" data='{"value":"Vassurany","state":"Vas"}'>Vassurany</div>
<div class="option" data='{"value":"Vasszecseny","state":"Vas"}'>Vasszecseny</div>
<div class="option" data='{"value":"Vasszentmihaly","state":"Vas"}'>Vasszentmihaly</div>
<div class="option" data='{"value":"Vasszilvagy","state":"Vas"}'>Vasszilvagy</div>
<div class="option" data='{"value":"Vasuti Ujlaktanya","state":"Vas"}'>Vasuti Ujlaktanya</div>
<div class="option" data='{"value":"Vasvar","state":"Vas"}'>Vasvar</div>
<div class="option" data='{"value":"Vat","state":"Vas"}'>Vat</div>
<div class="option" data='{"value":"Vegmalom","state":"Vas"}'>Vegmalom</div>
<div class="option" data='{"value":"Velem","state":"Vas"}'>Velem</div>
<div class="option" data='{"value":"Velemer","state":"Vas"}'>Velemer</div>
<div class="option" data='{"value":"Veorosmajor","state":"Vas"}'>Veorosmajor</div>
<div class="option" data='{"value":"Vep","state":"Vas"}'>Vep</div>
<div class="option" data='{"value":"Vienermajor","state":"Vas"}'>Vienermajor</div>
<div class="option" data='{"value":"Viktorinmajor","state":"Vas"}'>Viktorinmajor</div>
<div class="option" data='{"value":"Viktormajor","state":"Vas"}'>Viktormajor</div>
<div class="option" data='{"value":"Vilmosmajor","state":"Vas"}'>Vilmosmajor</div>
<div class="option" data='{"value":"Viszak","state":"Vas"}'>Viszak</div>
<div class="option" data='{"value":"Viteztelek","state":"Vas"}'>Viteztelek</div>
<div class="option" data='{"value":"Vonock","state":"Vas"}'>Vonock</div>
<div class="option" data='{"value":"Weltendorf","state":"Vas"}'>Weltendorf</div>
<div class="option" data='{"value":"Wettendorf","state":"Vas"}'>Wettendorf</div>
<div class="option" data='{"value":"Zanat","state":"Vas"}'>Zanat</div>
<div class="option" data='{"value":"Zertmajor","state":"Vas"}'>Zertmajor</div>
<div class="option" data='{"value":"Zongormajor","state":"Vas"}'>Zongormajor</div>
<div class="option" data='{"value":"Zsedeny","state":"Vas"}'>Zsedeny</div>
<div class="option" data='{"value":"Zsennye","state":"Vas"}'>Zsennye</div>
<div class="option" data='{"value":"Zsida","state":"Vas"}'>Zsida</div>
<div class="option" data='{"value":"Zuggo","state":"Vas"}'>Zuggo</div>
<div class="option" id="option_end" data='{"value":"Zugo","state":"Vas"}'>Zugo</div>

