<div class="option" data='{"value":"Adyliget","state":"Budapest"}'>Adyliget</div>
<div class="option" data='{"value":"Albertfalva","state":"Budapest"}'>Albertfalva</div>
<div class="option" data='{"value":"Angyalfold","state":"Budapest"}'>Angyalfold</div>
<div class="option" data='{"value":"Auwinkel","state":"Budapest"}'>Auwinkel</div>
<div class="option" data='{"value":"Bekasmegyer","state":"Budapest"}'>Bekasmegyer</div>
<div class="option" data='{"value":"Buda","state":"Budapest"}'>Buda</div>
<div class="option" data='{"value":"Budafok","state":"Budapest"}'>Budafok</div>
<div class="option" data='{"value":"Budapest","state":"Budapest"}'>Budapest</div>
<div class="option" data='{"value":"Budapest Fovaros","state":"Budapest"}'>Budapest Fovaros</div>
<div class="option" data='{"value":"Budateteny","state":"Budapest"}'>Budateteny</div>
<div class="option" data='{"value":"Chepel","state":"Budapest"}'>Chepel</div>
<div class="option" data='{"value":"Cinkota","state":"Budapest"}'>Cinkota</div>
<div class="option" data='{"value":"Csepel","state":"Budapest"}'>Csepel</div>
<div class="option" data='{"value":"Csilleberc","state":"Budapest"}'>Csilleberc</div>
<div class="option" data='{"value":"Csillebercz","state":"Budapest"}'>Csillebercz</div>
<div class="option" data='{"value":"Erzsebetfalva","state":"Budapest"}'>Erzsebetfalva</div>
<div class="option" data='{"value":"Erzsebetvaros","state":"Budapest"}'>Erzsebetvaros</div>
<div class="option" data='{"value":"Ferencvaros","state":"Budapest"}'>Ferencvaros</div>
<div class="option" data='{"value":"Gellert","state":"Budapest"}'>Gellert</div>
<div class="option" data='{"value":"Gellerthegy","state":"Budapest"}'>Gellerthegy</div>
<div class="option" data='{"value":"Kelenfold","state":"Budapest"}'>Kelenfold</div>
<div class="option" data='{"value":"Kelenvolgy","state":"Budapest"}'>Kelenvolgy</div>
<div class="option" data='{"value":"Kispest","state":"Budapest"}'>Kispest</div>
<div class="option" data='{"value":"Kobanya","state":"Budapest"}'>Kobanya</div>
<div class="option" data='{"value":"Lagymanyos","state":"Budapest"}'>Lagymanyos</div>
<div class="option" data='{"value":"Leninvaros","state":"Budapest"}'>Leninvaros</div>
<div class="option" data='{"value":"Martonhegy","state":"Budapest"}'>Martonhegy</div>
<div class="option" data='{"value":"Matiasfold","state":"Budapest"}'>Matiasfold</div>
<div class="option" data='{"value":"Matyasfold","state":"Budapest"}'>Matyasfold</div>
<div class="option" data='{"value":"Nagyteteny","state":"Budapest"}'>Nagyteteny</div>
<div class="option" data='{"value":"Obuda","state":"Budapest"}'>Obuda</div>
<div class="option" data='{"value":"Ofen","state":"Budapest"}'>Ofen</div>
<div class="option" data='{"value":"Pest","state":"Budapest"}'>Pest</div>
<div class="option" data='{"value":"Pesterzsebet","state":"Budapest"}'>Pesterzsebet</div>
<div class="option" data='{"value":"Pesth","state":"Budapest"}'>Pesth</div>
<div class="option" data='{"value":"Pesthidegkut","state":"Budapest"}'>Pesthidegkut</div>
<div class="option" data='{"value":"Pestimre","state":"Budapest"}'>Pestimre</div>
<div class="option" data='{"value":"Pestj","state":"Budapest"}'>Pestj</div>
<div class="option" data='{"value":"Pestlorinc","state":"Budapest"}'>Pestlorinc</div>
<div class="option" data='{"value":"Pestszenterzsebet","state":"Budapest"}'>Pestszenterzsebet</div>
<div class="option" data='{"value":"Pestszentimre","state":"Budapest"}'>Pestszentimre</div>
<div class="option" data='{"value":"Pestszentlorinc","state":"Budapest"}'>Pestszentlorinc</div>
<div class="option" data='{"value":"Pestujhely","state":"Budapest"}'>Pestujhely</div>
<div class="option" data='{"value":"Promontor","state":"Budapest"}'>Promontor</div>
<div class="option" data='{"value":"Rakoscsaba","state":"Budapest"}'>Rakoscsaba</div>
<div class="option" data='{"value":"Rakoshegy","state":"Budapest"}'>Rakoshegy</div>
<div class="option" data='{"value":"Rakoskeresztur","state":"Budapest"}'>Rakoskeresztur</div>
<div class="option" data='{"value":"Rakosliget","state":"Budapest"}'>Rakosliget</div>
<div class="option" data='{"value":"Rakospalota","state":"Budapest"}'>Rakospalota</div>
<div class="option" data='{"value":"Rakosszentmihaly","state":"Budapest"}'>Rakosszentmihaly</div>
<div class="option" data='{"value":"Remetekertearos","state":"Budapest"}'>Remetekertearos</div>
<div class="option" data='{"value":"Remetekertvaros","state":"Budapest"}'>Remetekertvaros</div>
<div class="option" data='{"value":"Romaifurdo","state":"Budapest"}'>Romaifurdo</div>
<div class="option" data='{"value":"Sashalom","state":"Budapest"}'>Sashalom</div>
<div class="option" data='{"value":"Soroksar","state":"Budapest"}'>Soroksar</div>
<div class="option" data='{"value":"Taban","state":"Budapest"}'>Taban</div>
<div class="option" data='{"value":"Ujpest","state":"Budapest"}'>Ujpest</div>
<div class="option" data='{"value":"Var","state":"Budapest"}'>Var</div>
<div class="option" data='{"value":"Zugliget","state":"Budapest"}'>Zugliget</div>
<div class="option" id="option_end" data='{"value":"Zuglo","state":"Budapest"}'>Zuglo</div>

