<div class="option" data='{"value":"Arakura","state":"Yamanashi"}'>Arakura</div>
<div class="option" data='{"value":"Ararakura","state":"Yamanashi"}'>Ararakura</div>
<div class="option" data='{"value":"Asakawa","state":"Yamanashi"}'>Asakawa</div>
<div class="option" data='{"value":"Azagawa","state":"Yamanashi"}'>Azagawa</div>
<div class="option" data='{"value":"Banya","state":"Yamanashi"}'>Banya</div>
<div class="option" data='{"value":"Daigahara","state":"Yamanashi"}'>Daigahara</div>
<div class="option" data='{"value":"Enzan","state":"Yamanashi"}'>Enzan</div>
<div class="option" data='{"value":"Fujinoki","state":"Yamanashi"}'>Fujinoki</div>
<div class="option" data='{"value":"Funatsu","state":"Yamanashi"}'>Funatsu</div>
<div class="option" data='{"value":"Furuseki","state":"Yamanashi"}'>Furuseki</div>
<div class="option" data='{"value":"Furuzeki","state":"Yamanashi"}'>Furuzeki</div>
<div class="option" data='{"value":"Hagii","state":"Yamanashi"}'>Hagii</div>
<div class="option" data='{"value":"Hakii","state":"Yamanashi"}'>Hakii</div>
<div class="option" data='{"value":"Hakushu","state":"Yamanashi"}'>Hakushu</div>
<div class="option" data='{"value":"Hanawa","state":"Yamanashi"}'>Hanawa</div>
<div class="option" data='{"value":"Hara","state":"Yamanashi"}'>Hara</div>
<div class="option" data='{"value":"Hayakawa","state":"Yamanashi"}'>Hayakawa</div>
<div class="option" data='{"value":"Hirose","state":"Yamanashi"}'>Hirose</div>
<div class="option" data='{"value":"Ichikawadaimon","state":"Yamanashi"}'>Ichikawadaimon</div>
<div class="option" data='{"value":"Iidamachi","state":"Yamanashi"}'>Iidamachi</div>
<div class="option" data='{"value":"Iino","state":"Yamanashi"}'>Iino</div>
<div class="option" data='{"value":"Iitomi","state":"Yamanashi"}'>Iitomi</div>
<div class="option" data='{"value":"Imaru","state":"Yamanashi"}'>Imaru</div>
<div class="option" data='{"value":"Inuma","state":"Yamanashi"}'>Inuma</div>
<div class="option" data='{"value":"Isawa","state":"Yamanashi"}'>Isawa</div>
<div class="option" data='{"value":"Iwama","state":"Yamanashi"}'>Iwama</div>
<div class="option" data='{"value":"Kai","state":"Yamanashi"}'>Kai</div>
<div class="option" data='{"value":"Kajikazawa","state":"Yamanashi"}'>Kajikazawa</div>
<div class="option" data='{"value":"Kakiibo","state":"Yamanashi"}'>Kakiibo</div>
<div class="option" data='{"value":"Kakubo","state":"Yamanashi"}'>Kakubo</div>
<div class="option" data='{"value":"Kanoiwa","state":"Yamanashi"}'>Kanoiwa</div>
<div class="option" data='{"value":"Katsunuma","state":"Yamanashi"}'>Katsunuma</div>
<div class="option" data='{"value":"Kawakubo","state":"Yamanashi"}'>Kawakubo</div>
<div class="option" data='{"value":"Kofu","state":"Yamanashi"}'>Kofu</div>
<div class="option" data='{"value":"Kohu","state":"Yamanashi"}'>Kohu</div>
<div class="option" data='{"value":"Kokkai","state":"Yamanashi"}'>Kokkai</div>
<div class="option" data='{"value":"Kokukai","state":"Yamanashi"}'>Kokukai</div>
<div class="option" data='{"value":"Komuro","state":"Yamanashi"}'>Komuro</div>
<div class="option" data='{"value":"Komurosawa","state":"Yamanashi"}'>Komurosawa</div>
<div class="option" data='{"value":"Kotsubaki","state":"Yamanashi"}'>Kotsubaki</div>
<div class="option" data='{"value":"Kubo","state":"Yamanashi"}'>Kubo</div>
<div class="option" data='{"value":"Kunizakai","state":"Yamanashi"}'>Kunizakai</div>
<div class="option" data='{"value":"Kuromori","state":"Yamanashi"}'>Kuromori</div>
<div class="option" data='{"value":"Kusakabe","state":"Yamanashi"}'>Kusakabe</div>
<div class="option" data='{"value":"Manzawa","state":"Yamanashi"}'>Manzawa</div>
<div class="option" data='{"value":"Minobu","state":"Yamanashi"}'>Minobu</div>
<div class="option" data='{"value":"Mitake","state":"Yamanashi"}'>Mitake</div>
<div class="option" data='{"value":"Mura","state":"Yamanashi"}'>Mura</div>
<div class="option" data='{"value":"Mushono","state":"Yamanashi"}'>Mushono</div>
<div class="option" data='{"value":"Nagasaka","state":"Yamanashi"}'>Nagasaka</div>
<div class="option" data='{"value":"Nagasawa","state":"Yamanashi"}'>Nagasawa</div>
<div class="option" data='{"value":"Nambu","state":"Yamanashi"}'>Nambu</div>
<div class="option" data='{"value":"Narada","state":"Yamanashi"}'>Narada</div>
<div class="option" data='{"value":"Narisawa","state":"Yamanashi"}'>Narisawa</div>
<div class="option" data='{"value":"Narusawa","state":"Yamanashi"}'>Narusawa</div>
<div class="option" data='{"value":"Nirasaki","state":"Yamanashi"}'>Nirasaki</div>
<div class="option" data='{"value":"Nirasakimachi","state":"Yamanashi"}'>Nirasakimachi</div>
<div class="option" data='{"value":"Nirazaki","state":"Yamanashi"}'>Nirazaki</div>
<div class="option" data='{"value":"Nirazakimachi","state":"Yamanashi"}'>Nirazakimachi</div>
<div class="option" data='{"value":"Nishibara","state":"Yamanashi"}'>Nishibara</div>
<div class="option" data='{"value":"Nishikicho","state":"Yamanashi"}'>Nishikicho</div>
<div class="option" data='{"value":"Ochiai","state":"Yamanashi"}'>Ochiai</div>
<div class="option" data='{"value":"Oishi","state":"Yamanashi"}'>Oishi</div>
<div class="option" data='{"value":"Okubo","state":"Yamanashi"}'>Okubo</div>
<div class="option" data='{"value":"Omurozasu","state":"Yamanashi"}'>Omurozasu</div>
<div class="option" data='{"value":"Omurozawa","state":"Yamanashi"}'>Omurozawa</div>
<div class="option" data='{"value":"Onuma","state":"Yamanashi"}'>Onuma</div>
<div class="option" data='{"value":"Otsuki","state":"Yamanashi"}'>Otsuki</div>
<div class="option" data='{"value":"Owatari","state":"Yamanashi"}'>Owatari</div>
<div class="option" data='{"value":"Ryuo","state":"Yamanashi"}'>Ryuo</div>
<div class="option" data='{"value":"Saruhashi","state":"Yamanashi"}'>Saruhashi</div>
<div class="option" data='{"value":"Sasaguma","state":"Yamanashi"}'>Sasaguma</div>
<div class="option" data='{"value":"Shikadome","state":"Yamanashi"}'>Shikadome</div>
<div class="option" data='{"value":"Shimoiwa","state":"Yamanashi"}'>Shimoiwa</div>
<div class="option" data='{"value":"Shimoyama","state":"Yamanashi"}'>Shimoyama</div>
<div class="option" data='{"value":"Shinjuku","state":"Yamanashi"}'>Shinjuku</div>
<div class="option" data='{"value":"Shinkura","state":"Yamanashi"}'>Shinkura</div>
<div class="option" data='{"value":"Shinshuku","state":"Yamanashi"}'>Shinshuku</div>
<div class="option" data='{"value":"Shirasu","state":"Yamanashi"}'>Shirasu</div>
<div class="option" data='{"value":"Shishidome","state":"Yamanashi"}'>Shishidome</div>
<div class="option" data='{"value":"Shishitome","state":"Yamanashi"}'>Shishitome</div>
<div class="option" data='{"value":"Shoji","state":"Yamanashi"}'>Shoji</div>
<div class="option" data='{"value":"Shojin","state":"Yamanashi"}'>Shojin</div>
<div class="option" data='{"value":"Tachibanacho","state":"Yamanashi"}'>Tachibanacho</div>
<div class="option" data='{"value":"Terashito","state":"Yamanashi"}'>Terashito</div>
<div class="option" data='{"value":"Tomihama","state":"Yamanashi"}'>Tomihama</div>
<div class="option" data='{"value":"Tonoki","state":"Yamanashi"}'>Tonoki</div>
<div class="option" data='{"value":"Torisawa","state":"Yamanashi"}'>Torisawa</div>
<div class="option" data='{"value":"Torizawa","state":"Yamanashi"}'>Torizawa</div>
<div class="option" data='{"value":"Ubaguchi","state":"Yamanashi"}'>Ubaguchi</div>
<div class="option" data='{"value":"Ubakuchi","state":"Yamanashi"}'>Ubakuchi</div>
<div class="option" data='{"value":"Uenohara","state":"Yamanashi"}'>Uenohara</div>
<div class="option" data='{"value":"Wakamiko","state":"Yamanashi"}'>Wakamiko</div>
<div class="option" data='{"value":"Yamanashi","state":"Yamanashi"}'>Yamanashi</div>
<div class="option" data='{"value":"Yatsusawa","state":"Yamanashi"}'>Yatsusawa</div>
<div class="option" data='{"value":"Yatsuzawa","state":"Yamanashi"}'>Yatsuzawa</div>
<div class="option" data='{"value":"Yodake","state":"Yamanashi"}'>Yodake</div>
<div class="option" id="option_end" data='{"value":"Yokobuki","state":"Yamanashi"}'>Yokobuki</div>

