<div class="option" data='{"value":"Amino","state":"Kyoto"}'>Amino</div>
<div class="option" data='{"value":"Anju","state":"Kyoto"}'>Anju</div>
<div class="option" data='{"value":"Anshucho","state":"Kyoto"}'>Anshucho</div>
<div class="option" data='{"value":"Asamogawa","state":"Kyoto"}'>Asamogawa</div>
<div class="option" data='{"value":"Asamokawa","state":"Kyoto"}'>Asamokawa</div>
<div class="option" data='{"value":"Ashiu","state":"Kyoto"}'>Ashiu</div>
<div class="option" data='{"value":"Ashu","state":"Kyoto"}'>Ashu</div>
<div class="option" data='{"value":"Ayabe","state":"Kyoto"}'>Ayabe</div>
<div class="option" data='{"value":"Daigo","state":"Kyoto"}'>Daigo</div>
<div class="option" data='{"value":"Daigocho","state":"Kyoto"}'>Daigocho</div>
<div class="option" data='{"value":"Fukuchiyama","state":"Kyoto"}'>Fukuchiyama</div>
<div class="option" data='{"value":"Funaya","state":"Kyoto"}'>Funaya</div>
<div class="option" data='{"value":"Fushimi","state":"Kyoto"}'>Fushimi</div>
<div class="option" data='{"value":"Gamanyu","state":"Kyoto"}'>Gamanyu</div>
<div class="option" data='{"value":"Giommachi","state":"Kyoto"}'>Giommachi</div>
<div class="option" data='{"value":"Gion","state":"Kyoto"}'>Gion</div>
<div class="option" data='{"value":"Gonokuchi","state":"Kyoto"}'>Gonokuchi</div>
<div class="option" data='{"value":"Habu","state":"Kyoto"}'>Habu</div>
<div class="option" data='{"value":"Hama","state":"Kyoto"}'>Hama</div>
<div class="option" data='{"value":"Hashitsume","state":"Kyoto"}'>Hashitsume</div>
<div class="option" data='{"value":"Hashizume","state":"Kyoto"}'>Hashizume</div>
<div class="option" data='{"value":"Hinobe","state":"Kyoto"}'>Hinobe</div>
<div class="option" data='{"value":"Hiraya","state":"Kyoto"}'>Hiraya</div>
<div class="option" data='{"value":"Honjo","state":"Kyoto"}'>Honjo</div>
<div class="option" data='{"value":"Horikoshi","state":"Kyoto"}'>Horikoshi</div>
<div class="option" data='{"value":"Hukutiyama","state":"Kyoto"}'>Hukutiyama</div>
<div class="option" data='{"value":"Ido","state":"Kyoto"}'>Ido</div>
<div class="option" data='{"value":"Ine","state":"Kyoto"}'>Ine</div>
<div class="option" data='{"value":"Ishikawa","state":"Kyoto"}'>Ishikawa</div>
<div class="option" data='{"value":"Itsumori","state":"Kyoto"}'>Itsumori</div>
<div class="option" data='{"value":"Itsutsumori","state":"Kyoto"}'>Itsutsumori</div>
<div class="option" data='{"value":"Itunomori","state":"Kyoto"}'>Itunomori</div>
<div class="option" data='{"value":"Iwagahana","state":"Kyoto"}'>Iwagahana</div>
<div class="option" data='{"value":"Iwakura","state":"Kyoto"}'>Iwakura</div>
<div class="option" data='{"value":"Iwataki","state":"Kyoto"}'>Iwataki</div>
<div class="option" data='{"value":"Kamanyu","state":"Kyoto"}'>Kamanyu</div>
<div class="option" data='{"value":"Kameoka","state":"Kyoto"}'>Kameoka</div>
<div class="option" data='{"value":"Kameshima","state":"Kyoto"}'>Kameshima</div>
<div class="option" data='{"value":"Kamikoma","state":"Kyoto"}'>Kamikoma</div>
<div class="option" data='{"value":"Kanzaki","state":"Kyoto"}'>Kanzaki</div>
<div class="option" data='{"value":"Karahashi Rashomon","state":"Kyoto"}'>Karahashi Rashomon</div>
<div class="option" data='{"value":"Kasagi","state":"Kyoto"}'>Kasagi</div>
<div class="option" data='{"value":"Katsura","state":"Kyoto"}'>Katsura</div>
<div class="option" data='{"value":"Katsuracho","state":"Kyoto"}'>Katsuracho</div>
<div class="option" data='{"value":"Kawabe","state":"Kyoto"}'>Kawabe</div>
<div class="option" data='{"value":"Kawahara","state":"Kyoto"}'>Kawahara</div>
<div class="option" data='{"value":"Kawara","state":"Kyoto"}'>Kawara</div>
<div class="option" data='{"value":"Kaya","state":"Kyoto"}'>Kaya</div>
<div class="option" data='{"value":"Kazuka","state":"Kyoto"}'>Kazuka</div>
<div class="option" data='{"value":"Kazurano","state":"Kyoto"}'>Kazurano</div>
<div class="option" data='{"value":"Keage","state":"Kyoto"}'>Keage</div>
<div class="option" data='{"value":"Kichisaka","state":"Kyoto"}'>Kichisaka</div>
<div class="option" data='{"value":"Kichisaki","state":"Kyoto"}'>Kichisaki</div>
<div class="option" data='{"value":"Kinugasa","state":"Kyoto"}'>Kinugasa</div>
<div class="option" data='{"value":"Kioto","state":"Kyoto"}'>Kioto</div>
<div class="option" data='{"value":"Kissaka","state":"Kyoto"}'>Kissaka</div>
<div class="option" data='{"value":"Kizu","state":"Kyoto"}'>Kizu</div>
<div class="option" data='{"value":"Kizumachi","state":"Kyoto"}'>Kizumachi</div>
<div class="option" data='{"value":"Kobe","state":"Kyoto"}'>Kobe</div>
<div class="option" data='{"value":"Komori","state":"Kyoto"}'>Komori</div>
<div class="option" data='{"value":"Kotari","state":"Kyoto"}'>Kotari</div>
<div class="option" data='{"value":"Kumihama","state":"Kyoto"}'>Kumihama</div>
<div class="option" data='{"value":"Kumobara","state":"Kyoto"}'>Kumobara</div>
<div class="option" data='{"value":"Kumohara","state":"Kyoto"}'>Kumohara</div>
<div class="option" data='{"value":"Kunda","state":"Kyoto"}'>Kunda</div>
<div class="option" data='{"value":"Kuradani","state":"Kyoto"}'>Kuradani</div>
<div class="option" data='{"value":"Kurama","state":"Kyoto"}'>Kurama</div>
<div class="option" data='{"value":"Kuratami","state":"Kyoto"}'>Kuratami</div>
<div class="option" data='{"value":"Kuratani","state":"Kyoto"}'>Kuratani</div>
<div class="option" data='{"value":"Kurida","state":"Kyoto"}'>Kurida</div>
<div class="option" data='{"value":"Kurodani","state":"Kyoto"}'>Kurodani</div>
<div class="option" data='{"value":"Kurotani","state":"Kyoto"}'>Kurotani</div>
<div class="option" data='{"value":"Kurotanicho","state":"Kyoto"}'>Kurotanicho</div>
<div class="option" data='{"value":"Kutami","state":"Kyoto"}'>Kutami</div>
<div class="option" data='{"value":"Kuzuno","state":"Kyoto"}'>Kuzuno</div>
<div class="option" data='{"value":"Kyoguchi","state":"Kyoto"}'>Kyoguchi</div>
<div class="option" data='{"value":"Kyoto","state":"Kyoto"}'>Kyoto</div>
<div class="option" data='{"value":"Maidsuru","state":"Kyoto"}'>Maidsuru</div>
<div class="option" data='{"value":"Maiduru","state":"Kyoto"}'>Maiduru</div>
<div class="option" data='{"value":"Maizuru","state":"Kyoto"}'>Maizuru</div>
<div class="option" data='{"value":"Migochi","state":"Kyoto"}'>Migochi</div>
<div class="option" data='{"value":"Mihama","state":"Kyoto"}'>Mihama</div>
<div class="option" data='{"value":"Mikochi","state":"Kyoto"}'>Mikochi</div>
<div class="option" data='{"value":"Mimata","state":"Kyoto"}'>Mimata</div>
<div class="option" data='{"value":"Minama","state":"Kyoto"}'>Minama</div>
<div class="option" data='{"value":"Minamijo","state":"Kyoto"}'>Minamijo</div>
<div class="option" data='{"value":"Minatomiya","state":"Kyoto"}'>Minatomiya</div>
<div class="option" data='{"value":"Mineyama","state":"Kyoto"}'>Mineyama</div>
<div class="option" data='{"value":"Miyazu","state":"Kyoto"}'>Miyazu</div>
<div class="option" data='{"value":"Mizotani","state":"Kyoto"}'>Mizotani</div>
<div class="option" data='{"value":"Mizusu","state":"Kyoto"}'>Mizusu</div>
<div class="option" data='{"value":"Monju","state":"Kyoto"}'>Monju</div>
<div class="option" data='{"value":"Monobe","state":"Kyoto"}'>Monobe</div>
<div class="option" data='{"value":"Mononobe","state":"Kyoto"}'>Mononobe</div>
<div class="option" data='{"value":"Monshu","state":"Kyoto"}'>Monshu</div>
<div class="option" data='{"value":"Muko","state":"Kyoto"}'>Muko</div>
<div class="option" data='{"value":"Nagaike","state":"Kyoto"}'>Nagaike</div>
<div class="option" data='{"value":"Naka","state":"Kyoto"}'>Naka</div>
<div class="option" data='{"value":"Nakada","state":"Kyoto"}'>Nakada</div>
<div class="option" data='{"value":"Nakahama","state":"Kyoto"}'>Nakahama</div>
<div class="option" data='{"value":"Nakamura","state":"Kyoto"}'>Nakamura</div>
<div class="option" data='{"value":"Nakasuji","state":"Kyoto"}'>Nakasuji</div>
<div class="option" data='{"value":"Nakata","state":"Kyoto"}'>Nakata</div>
<div class="option" data='{"value":"Nanjo","state":"Kyoto"}'>Nanjo</div>
<div class="option" data='{"value":"Nishijin","state":"Kyoto"}'>Nishijin</div>
<div class="option" data='{"value":"Nishinotoin","state":"Kyoto"}'>Nishinotoin</div>
<div class="option" data='{"value":"Nishinotoindori","state":"Kyoto"}'>Nishinotoindori</div>
<div class="option" data='{"value":"Nobuchika","state":"Kyoto"}'>Nobuchika</div>
<div class="option" data='{"value":"Nohara","state":"Kyoto"}'>Nohara</div>
<div class="option" data='{"value":"Nomi","state":"Kyoto"}'>Nomi</div>
<div class="option" data='{"value":"Nomuro","state":"Kyoto"}'>Nomuro</div>
<div class="option" data='{"value":"Nonaka","state":"Kyoto"}'>Nonaka</div>
<div class="option" data='{"value":"Obara","state":"Kyoto"}'>Obara</div>
<div class="option" data='{"value":"Obuse","state":"Kyoto"}'>Obuse</div>
<div class="option" data='{"value":"Ofuse","state":"Kyoto"}'>Ofuse</div>
<div class="option" data='{"value":"Ogura","state":"Kyoto"}'>Ogura</div>
<div class="option" data='{"value":"Oguracho","state":"Kyoto"}'>Oguracho</div>
<div class="option" data='{"value":"Oguramachi","state":"Kyoto"}'>Oguramachi</div>
<div class="option" data='{"value":"Ohara","state":"Kyoto"}'>Ohara</div>
<div class="option" data='{"value":"Oji","state":"Kyoto"}'>Oji</div>
<div class="option" data='{"value":"Okuse","state":"Kyoto"}'>Okuse</div>
<div class="option" data='{"value":"Ono","state":"Kyoto"}'>Ono</div>
<div class="option" data='{"value":"Onyo","state":"Kyoto"}'>Onyo</div>
<div class="option" data='{"value":"Onyu","state":"Kyoto"}'>Onyu</div>
<div class="option" data='{"value":"Ota","state":"Kyoto"}'>Ota</div>
<div class="option" data='{"value":"Otani","state":"Kyoto"}'>Otani</div>
<div class="option" data='{"value":"Otanu","state":"Kyoto"}'>Otanu</div>
<div class="option" data='{"value":"Rokujizo","state":"Kyoto"}'>Rokujizo</div>
<div class="option" data='{"value":"Sabaka","state":"Kyoto"}'>Sabaka</div>
<div class="option" data='{"value":"Saeki","state":"Kyoto"}'>Saeki</div>
<div class="option" data='{"value":"Saga","state":"Kyoto"}'>Saga</div>
<div class="option" data='{"value":"Sagano","state":"Kyoto"}'>Sagano</div>
<div class="option" data='{"value":"Saiin","state":"Kyoto"}'>Saiin</div>
<div class="option" data='{"value":"Saiki","state":"Kyoto"}'>Saiki</div>
<div class="option" data='{"value":"Sain","state":"Kyoto"}'>Sain</div>
<div class="option" data='{"value":"Sasari","state":"Kyoto"}'>Sasari</div>
<div class="option" data='{"value":"Seidoindori","state":"Kyoto"}'>Seidoindori</div>
<div class="option" data='{"value":"Shijodori","state":"Kyoto"}'>Shijodori</div>
<div class="option" data='{"value":"Shimmachidori","state":"Kyoto"}'>Shimmachidori</div>
<div class="option" data='{"value":"Shimoku","state":"Kyoto"}'>Shimoku</div>
<div class="option" data='{"value":"Shinomiya","state":"Kyoto"}'>Shinomiya</div>
<div class="option" data='{"value":"Shinomiyacho","state":"Kyoto"}'>Shinomiyacho</div>
<div class="option" data='{"value":"Shioe","state":"Kyoto"}'>Shioe</div>
<div class="option" data='{"value":"Shirasugi","state":"Kyoto"}'>Shirasugi</div>
<div class="option" data='{"value":"Shitsugawa","state":"Kyoto"}'>Shitsugawa</div>
<div class="option" data='{"value":"Shitsukawa","state":"Kyoto"}'>Shitsukawa</div>
<div class="option" data='{"value":"Shizu Gawa","state":"Kyoto"}'>Shizu Gawa</div>
<div class="option" data='{"value":"Shuchi","state":"Kyoto"}'>Shuchi</div>
<div class="option" data='{"value":"Shuzan","state":"Kyoto"}'>Shuzan</div>
<div class="option" data='{"value":"Sodeshi","state":"Kyoto"}'>Sodeshi</div>
<div class="option" data='{"value":"Sonobe","state":"Kyoto"}'>Sonobe</div>
<div class="option" data='{"value":"Suchi","state":"Kyoto"}'>Suchi</div>
<div class="option" data='{"value":"Suki","state":"Kyoto"}'>Suki</div>
<div class="option" data='{"value":"Taga","state":"Kyoto"}'>Taga</div>
<div class="option" data='{"value":"Tai","state":"Kyoto"}'>Tai</div>
<div class="option" data='{"value":"Taira","state":"Kyoto"}'>Taira</div>
<div class="option" data='{"value":"Taiza","state":"Kyoto"}'>Taiza</div>
<div class="option" data='{"value":"Taka","state":"Kyoto"}'>Taka</div>
<div class="option" data='{"value":"Takanosu","state":"Kyoto"}'>Takanosu</div>
<div class="option" data='{"value":"Takanoyuri","state":"Kyoto"}'>Takanoyuri</div>
<div class="option" data='{"value":"Takasu","state":"Kyoto"}'>Takasu</div>
<div class="option" data='{"value":"Tamamizu","state":"Kyoto"}'>Tamamizu</div>
<div class="option" data='{"value":"Tamba","state":"Kyoto"}'>Tamba</div>
<div class="option" data='{"value":"Tanabe","state":"Kyoto"}'>Tanabe</div>
<div class="option" data='{"value":"Tango","state":"Kyoto"}'>Tango</div>
<div class="option" data='{"value":"Terada","state":"Kyoto"}'>Terada</div>
<div class="option" data='{"value":"Teramachi","state":"Kyoto"}'>Teramachi</div>
<div class="option" data='{"value":"Tonoda","state":"Kyoto"}'>Tonoda</div>
<div class="option" data='{"value":"Ubara","state":"Kyoto"}'>Ubara</div>
<div class="option" data='{"value":"Ueno","state":"Kyoto"}'>Ueno</div>
<div class="option" data='{"value":"Uesugi","state":"Kyoto"}'>Uesugi</div>
<div class="option" data='{"value":"Uji","state":"Kyoto"}'>Uji</div>
<div class="option" data='{"value":"Wachi","state":"Kyoto"}'>Wachi</div>
<div class="option" data='{"value":"Yagi","state":"Kyoto"}'>Yagi</div>
<div class="option" data='{"value":"Yahata","state":"Kyoto"}'>Yahata</div>
<div class="option" data='{"value":"Yahatanosho","state":"Kyoto"}'>Yahatanosho</div>
<div class="option" data='{"value":"Yahatasho","state":"Kyoto"}'>Yahatasho</div>
<div class="option" data='{"value":"Yamaga","state":"Kyoto"}'>Yamaga</div>
<div class="option" data='{"value":"Yatsuai","state":"Kyoto"}'>Yatsuai</div>
<div class="option" data='{"value":"Yawata","state":"Kyoto"}'>Yawata</div>
<div class="option" data='{"value":"Yawatasho","state":"Kyoto"}'>Yawatasho</div>
<div class="option" data='{"value":"Yodo","state":"Kyoto"}'>Yodo</div>
<div class="option" data='{"value":"Yotsuji","state":"Kyoto"}'>Yotsuji</div>
<div class="option" data='{"value":"Yotsutsuji","state":"Kyoto"}'>Yotsutsuji</div>
<div class="option" data='{"value":"Yotsuya","state":"Kyoto"}'>Yotsuya</div>
<div class="option" id="option_end" data='{"value":"Yura","state":"Kyoto"}'>Yura</div>

