<div class="option" data='{"value":"Achigaya","state":"Shizuoka"}'>Achigaya</div>
<div class="option" data='{"value":"Aioicho","state":"Shizuoka"}'>Aioicho</div>
<div class="option" data='{"value":"Aioimachi","state":"Shizuoka"}'>Aioimachi</div>
<div class="option" data='{"value":"Ajiro","state":"Shizuoka"}'>Ajiro</div>
<div class="option" data='{"value":"Amishiro","state":"Shizuoka"}'>Amishiro</div>
<div class="option" data='{"value":"Aoicho","state":"Shizuoka"}'>Aoicho</div>
<div class="option" data='{"value":"Arai","state":"Shizuoka"}'>Arai</div>
<div class="option" data='{"value":"Arari","state":"Shizuoka"}'>Arari</div>
<div class="option" data='{"value":"Ashiro","state":"Shizuoka"}'>Ashiro</div>
<div class="option" data='{"value":"Ashitaka","state":"Shizuoka"}'>Ashitaka</div>
<div class="option" data='{"value":"Atami","state":"Shizuoka"}'>Atami</div>
<div class="option" data='{"value":"Aziro","state":"Shizuoka"}'>Aziro</div>
<div class="option" data='{"value":"Chihama","state":"Shizuoka"}'>Chihama</div>
<div class="option" data='{"value":"Dategata","state":"Shizuoka"}'>Dategata</div>
<div class="option" data='{"value":"Doi","state":"Shizuoka"}'>Doi</div>
<div class="option" data='{"value":"Ejiri","state":"Shizuoka"}'>Ejiri</div>
<div class="option" data='{"value":"Ejirimachi","state":"Shizuoka"}'>Ejirimachi</div>
<div class="option" data='{"value":"Ena","state":"Shizuoka"}'>Ena</div>
<div class="option" data='{"value":"Enoura","state":"Shizuoka"}'>Enoura</div>
<div class="option" data='{"value":"Fuji","state":"Shizuoka"}'>Fuji</div>
<div class="option" data='{"value":"Fujieda","state":"Shizuoka"}'>Fujieda</div>
<div class="option" data='{"value":"Fujimiya","state":"Shizuoka"}'>Fujimiya</div>
<div class="option" data='{"value":"Fujinomiya","state":"Shizuoka"}'>Fujinomiya</div>
<div class="option" data='{"value":"Fujioka","state":"Shizuoka"}'>Fujioka</div>
<div class="option" data='{"value":"Fujiokacho","state":"Shizuoka"}'>Fujiokacho</div>
<div class="option" data='{"value":"Fukuda","state":"Shizuoka"}'>Fukuda</div>
<div class="option" data='{"value":"Fukude","state":"Shizuoka"}'>Fukude</div>
<div class="option" data='{"value":"Fukuroi","state":"Shizuoka"}'>Fukuroi</div>
<div class="option" data='{"value":"Funayama","state":"Shizuoka"}'>Funayama</div>
<div class="option" data='{"value":"Futamata","state":"Shizuoka"}'>Futamata</div>
<div class="option" data='{"value":"Futo","state":"Shizuoka"}'>Futo</div>
<div class="option" data='{"value":"Gokanjima","state":"Shizuoka"}'>Gokanjima</div>
<div class="option" data='{"value":"Gokanmori","state":"Shizuoka"}'>Gokanmori</div>
<div class="option" data='{"value":"Gotemba","state":"Shizuoka"}'>Gotemba</div>
<div class="option" data='{"value":"Hachiman","state":"Shizuoka"}'>Hachiman</div>
<div class="option" data='{"value":"Hagiwara","state":"Shizuoka"}'>Hagiwara</div>
<div class="option" data='{"value":"Hamakita","state":"Shizuoka"}'>Hamakita</div>
<div class="option" data='{"value":"Hamamatsu","state":"Shizuoka"}'>Hamamatsu</div>
<div class="option" data='{"value":"Hamamatu","state":"Shizuoka"}'>Hamamatu</div>
<div class="option" data='{"value":"Hamana","state":"Shizuoka"}'>Hamana</div>
<div class="option" data='{"value":"Hanazawa","state":"Shizuoka"}'>Hanazawa</div>
<div class="option" data='{"value":"Hara","state":"Shizuoka"}'>Hara</div>
<div class="option" data='{"value":"Harada","state":"Shizuoka"}'>Harada</div>
<div class="option" data='{"value":"Hatsushima","state":"Shizuoka"}'>Hatsushima</div>
<div class="option" data='{"value":"Heda","state":"Shizuoka"}'>Heda</div>
<div class="option" data='{"value":"Heigaki","state":"Shizuoka"}'>Heigaki</div>
<div class="option" data='{"value":"Hiekawa","state":"Shizuoka"}'>Hiekawa</div>
<div class="option" data='{"value":"Hinata","state":"Shizuoka"}'>Hinata</div>
<div class="option" data='{"value":"Hinodecho","state":"Shizuoka"}'>Hinodecho</div>
<div class="option" data='{"value":"Hiragaki","state":"Shizuoka"}'>Hiragaki</div>
<div class="option" data='{"value":"Hitoana","state":"Shizuoka"}'>Hitoana</div>
<div class="option" data='{"value":"Horinouchi","state":"Shizuoka"}'>Horinouchi</div>
<div class="option" data='{"value":"Ichino","state":"Shizuoka"}'>Ichino</div>
<div class="option" data='{"value":"Idozawa","state":"Shizuoka"}'>Idozawa</div>
<div class="option" data='{"value":"Ieyama","state":"Shizuoka"}'>Ieyama</div>
<div class="option" data='{"value":"Ihama","state":"Shizuoka"}'>Ihama</div>
<div class="option" data='{"value":"Ihara","state":"Shizuoka"}'>Ihara</div>
<div class="option" data='{"value":"Iinoya","state":"Shizuoka"}'>Iinoya</div>
<div class="option" data='{"value":"Iiya","state":"Shizuoka"}'>Iiya</div>
<div class="option" data='{"value":"Ikawa","state":"Shizuoka"}'>Ikawa</div>
<div class="option" data='{"value":"Ikeda","state":"Shizuoka"}'>Ikeda</div>
<div class="option" data='{"value":"Ikeshinden","state":"Shizuoka"}'>Ikeshinden</div>
<div class="option" data='{"value":"Inatori","state":"Shizuoka"}'>Inatori</div>
<div class="option" data='{"value":"Inokashira","state":"Shizuoka"}'>Inokashira</div>
<div class="option" data='{"value":"Inui","state":"Shizuoka"}'>Inui</div>
<div class="option" data='{"value":"Inuma","state":"Shizuoka"}'>Inuma</div>
<div class="option" data='{"value":"Iriyamase","state":"Shizuoka"}'>Iriyamase</div>
<div class="option" data='{"value":"Iriyamaze","state":"Shizuoka"}'>Iriyamaze</div>
<div class="option" data='{"value":"Iruma","state":"Shizuoka"}'>Iruma</div>
<div class="option" data='{"value":"Ishibu","state":"Shizuoka"}'>Ishibu</div>
<div class="option" data='{"value":"Ito","state":"Shizuoka"}'>Ito</div>
<div class="option" data='{"value":"Itozawa","state":"Shizuoka"}'>Itozawa</div>
<div class="option" data='{"value":"Iwabuchi","state":"Shizuoka"}'>Iwabuchi</div>
<div class="option" data='{"value":"Iwachi","state":"Shizuoka"}'>Iwachi</div>
<div class="option" data='{"value":"Iwafuchi","state":"Shizuoka"}'>Iwafuchi</div>
<div class="option" data='{"value":"Iwamoto","state":"Shizuoka"}'>Iwamoto</div>
<div class="option" data='{"value":"Iwata","state":"Shizuoka"}'>Iwata</div>
<div class="option" data='{"value":"Jidogata","state":"Shizuoka"}'>Jidogata</div>
<div class="option" data='{"value":"Jitogata","state":"Shizuoka"}'>Jitogata</div>
<div class="option" data='{"value":"Kachi","state":"Shizuoka"}'>Kachi</div>
<div class="option" data='{"value":"Kaishima","state":"Shizuoka"}'>Kaishima</div>
<div class="option" data='{"value":"Kakegawa","state":"Shizuoka"}'>Kakegawa</div>
<div class="option" data='{"value":"Kaketsuka","state":"Shizuoka"}'>Kaketsuka</div>
<div class="option" data='{"value":"Kakezuka","state":"Shizuoka"}'>Kakezuka</div>
<div class="option" data='{"value":"Kambara","state":"Shizuoka"}'>Kambara</div>
<div class="option" data='{"value":"Kanasashi","state":"Shizuoka"}'>Kanasashi</div>
<div class="option" data='{"value":"Kanaya","state":"Shizuoka"}'>Kanaya</div>
<div class="option" data='{"value":"Kano","state":"Shizuoka"}'>Kano</div>
<div class="option" data='{"value":"Kasai","state":"Shizuoka"}'>Kasai</div>
<div class="option" data='{"value":"Katase","state":"Shizuoka"}'>Katase</div>
<div class="option" data='{"value":"Katsura","state":"Shizuoka"}'>Katsura</div>
<div class="option" data='{"value":"Kawai","state":"Shizuoka"}'>Kawai</div>
<div class="option" data='{"value":"Kawana","state":"Shizuoka"}'>Kawana</div>
<div class="option" data='{"value":"Kawara","state":"Shizuoka"}'>Kawara</div>
<div class="option" data='{"value":"Kawaramachi","state":"Shizuoka"}'>Kawaramachi</div>
<div class="option" data='{"value":"Kawasaki","state":"Shizuoka"}'>Kawasaki</div>
<div class="option" data='{"value":"Kawazu","state":"Shizuoka"}'>Kawazu</div>
<div class="option" data='{"value":"Kazono","state":"Shizuoka"}'>Kazono</div>
<div class="option" data='{"value":"Kega","state":"Shizuoka"}'>Kega</div>
<div class="option" data='{"value":"Keta","state":"Shizuoka"}'>Keta</div>
<div class="option" data='{"value":"Kibune","state":"Shizuoka"}'>Kibune</div>
<div class="option" data='{"value":"Kida","state":"Shizuoka"}'>Kida</div>
<div class="option" data='{"value":"Kiga","state":"Shizuoka"}'>Kiga</div>
<div class="option" data='{"value":"Kita","state":"Shizuoka"}'>Kita</div>
<div class="option" data='{"value":"Kitayama","state":"Shizuoka"}'>Kitayama</div>
<div class="option" data='{"value":"Kochi","state":"Shizuoka"}'>Kochi</div>
<div class="option" data='{"value":"Koizumi","state":"Shizuoka"}'>Koizumi</div>
<div class="option" data='{"value":"Komagoe","state":"Shizuoka"}'>Komagoe</div>
<div class="option" data='{"value":"Komakoe","state":"Shizuoka"}'>Komakoe</div>
<div class="option" data='{"value":"Kona","state":"Shizuoka"}'>Kona</div>
<div class="option" data='{"value":"Kora","state":"Shizuoka"}'>Kora</div>
<div class="option" data='{"value":"Koura","state":"Shizuoka"}'>Koura</div>
<div class="option" data='{"value":"Kuma","state":"Shizuoka"}'>Kuma</div>
<div class="option" data='{"value":"Kune","state":"Shizuoka"}'>Kune</div>
<div class="option" data='{"value":"Kunowaki","state":"Shizuoka"}'>Kunowaki</div>
<div class="option" data='{"value":"Maejima","state":"Shizuoka"}'>Maejima</div>
<div class="option" data='{"value":"Magome","state":"Shizuoka"}'>Magome</div>
<div class="option" data='{"value":"Magori","state":"Shizuoka"}'>Magori</div>
<div class="option" data='{"value":"Maisaka","state":"Shizuoka"}'>Maisaka</div>
<div class="option" data='{"value":"Makinohara","state":"Shizuoka"}'>Makinohara</div>
<div class="option" data='{"value":"Makori","state":"Shizuoka"}'>Makori</div>
<div class="option" data='{"value":"Mamiya","state":"Shizuoka"}'>Mamiya</div>
<div class="option" data='{"value":"Manaitahara","state":"Shizuoka"}'>Manaitahara</div>
<div class="option" data='{"value":"Manaitakara","state":"Shizuoka"}'>Manaitakara</div>
<div class="option" data='{"value":"Mangori","state":"Shizuoka"}'>Mangori</div>
<div class="option" data='{"value":"Matsuzaki","state":"Shizuoka"}'>Matsuzaki</div>
<div class="option" data='{"value":"Mera","state":"Shizuoka"}'>Mera</div>
<div class="option" data='{"value":"Michibe","state":"Shizuoka"}'>Michibe</div>
<div class="option" data='{"value":"Michibu","state":"Shizuoka"}'>Michibu</div>
<div class="option" data='{"value":"Midaka","state":"Shizuoka"}'>Midaka</div>
<div class="option" data='{"value":"Miho","state":"Shizuoka"}'>Miho</div>
<div class="option" data='{"value":"Mijuku","state":"Shizuoka"}'>Mijuku</div>
<div class="option" data='{"value":"Mikkabi","state":"Shizuoka"}'>Mikkabi</div>
<div class="option" data='{"value":"Mikura","state":"Shizuoka"}'>Mikura</div>
<div class="option" data='{"value":"Minamiosaka","state":"Shizuoka"}'>Minamiosaka</div>
<div class="option" data='{"value":"Minato","state":"Shizuoka"}'>Minato</div>
<div class="option" data='{"value":"Minatocho","state":"Shizuoka"}'>Minatocho</div>
<div class="option" data='{"value":"Minenosawa","state":"Shizuoka"}'>Minenosawa</div>
<div class="option" data='{"value":"Misakubo","state":"Shizuoka"}'>Misakubo</div>
<div class="option" data='{"value":"Mishima","state":"Shizuoka"}'>Mishima</div>
<div class="option" data='{"value":"Mishimacho","state":"Shizuoka"}'>Mishimacho</div>
<div class="option" data='{"value":"Mishuku","state":"Shizuoka"}'>Mishuku</div>
<div class="option" data='{"value":"Mitaka","state":"Shizuoka"}'>Mitaka</div>
<div class="option" data='{"value":"Mitsuke","state":"Shizuoka"}'>Mitsuke</div>
<div class="option" data='{"value":"Miyajima","state":"Shizuoka"}'>Miyajima</div>
<div class="option" data='{"value":"Miyakami","state":"Shizuoka"}'>Miyakami</div>
<div class="option" data='{"value":"Miyakasa","state":"Shizuoka"}'>Miyakasa</div>
<div class="option" data='{"value":"Mochigoshi","state":"Shizuoka"}'>Mochigoshi</div>
<div class="option" data='{"value":"Mochikoshi","state":"Shizuoka"}'>Mochikoshi</div>
<div class="option" data='{"value":"Mochimune","state":"Shizuoka"}'>Mochimune</div>
<div class="option" data='{"value":"Monzen","state":"Shizuoka"}'>Monzen</div>
<div class="option" data='{"value":"Mori","state":"Shizuoka"}'>Mori</div>
<div class="option" data='{"value":"Motoichiba","state":"Shizuoka"}'>Motoichiba</div>
<div class="option" data='{"value":"Murakushi","state":"Shizuoka"}'>Murakushi</div>
<div class="option" data='{"value":"Muramatsu","state":"Shizuoka"}'>Muramatsu</div>
<div class="option" data='{"value":"Mutsumi","state":"Shizuoka"}'>Mutsumi</div>
<div class="option" data='{"value":"Naganuma","state":"Shizuoka"}'>Naganuma</div>
<div class="option" data='{"value":"Nagaoka","state":"Shizuoka"}'>Nagaoka</div>
<div class="option" data='{"value":"Nagatsuro","state":"Shizuoka"}'>Nagatsuro</div>
<div class="option" data='{"value":"Nagatsuru","state":"Shizuoka"}'>Nagatsuru</div>
<div class="option" data='{"value":"Nagaturo","state":"Shizuoka"}'>Nagaturo</div>
<div class="option" data='{"value":"Nakaizumi","state":"Shizuoka"}'>Nakaizumi</div>
<div class="option" data='{"value":"Nakajiku","state":"Shizuoka"}'>Nakajiku</div>
<div class="option" data='{"value":"Nakajuku","state":"Shizuoka"}'>Nakajuku</div>
<div class="option" data='{"value":"Nakano","state":"Shizuoka"}'>Nakano</div>
<div class="option" data='{"value":"Nakanomachi","state":"Shizuoka"}'>Nakanomachi</div>
<div class="option" data='{"value":"Nakappe","state":"Shizuoka"}'>Nakappe</div>
<div class="option" data='{"value":"Nakashuku","state":"Shizuoka"}'>Nakashuku</div>
<div class="option" data='{"value":"Nakatsu","state":"Shizuoka"}'>Nakatsu</div>
<div class="option" data='{"value":"Nawaji","state":"Shizuoka"}'>Nawaji</div>
<div class="option" data='{"value":"Nebara","state":"Shizuoka"}'>Nebara</div>
<div class="option" data='{"value":"Neginohata","state":"Shizuoka"}'>Neginohata</div>
<div class="option" data='{"value":"Nehara","state":"Shizuoka"}'>Nehara</div>
<div class="option" data='{"value":"Nishijama","state":"Shizuoka"}'>Nishijama</div>
<div class="option" data='{"value":"Nishijima","state":"Shizuoka"}'>Nishijima</div>
<div class="option" data='{"value":"Nishina","state":"Shizuoka"}'>Nishina</div>
<div class="option" data='{"value":"Nishiura","state":"Shizuoka"}'>Nishiura</div>
<div class="option" data='{"value":"Nishiure","state":"Shizuoka"}'>Nishiure</div>
<div class="option" data='{"value":"Nissaka","state":"Shizuoka"}'>Nissaka</div>
<div class="option" data='{"value":"Numadu","state":"Shizuoka"}'>Numadu</div>
<div class="option" data='{"value":"Numazu","state":"Shizuoka"}'>Numazu</div>
<div class="option" data='{"value":"Ogi","state":"Shizuoka"}'>Ogi</div>
<div class="option" data='{"value":"Ohata","state":"Shizuoka"}'>Ohata</div>
<div class="option" data='{"value":"Ohito","state":"Shizuoka"}'>Ohito</div>
<div class="option" data='{"value":"Oike","state":"Shizuoka"}'>Oike</div>
<div class="option" data='{"value":"Oiwake","state":"Shizuoka"}'>Oiwake</div>
<div class="option" data='{"value":"Oiwakecho","state":"Shizuoka"}'>Oiwakecho</div>
<div class="option" data='{"value":"Okaba","state":"Shizuoka"}'>Okaba</div>
<div class="option" data='{"value":"Okabacho","state":"Shizuoka"}'>Okabacho</div>
<div class="option" data='{"value":"Okabe","state":"Shizuoka"}'>Okabe</div>
<div class="option" data='{"value":"Okawa","state":"Shizuoka"}'>Okawa</div>
<div class="option" data='{"value":"Okitsu","state":"Shizuoka"}'>Okitsu</div>
<div class="option" data='{"value":"Okuryoke","state":"Shizuoka"}'>Okuryoke</div>
<div class="option" data='{"value":"Okuyama","state":"Shizuoka"}'>Okuyama</div>
<div class="option" data='{"value":"Oma","state":"Shizuoka"}'>Oma</div>
<div class="option" data='{"value":"Omiya","state":"Shizuoka"}'>Omiya</div>
<div class="option" data='{"value":"Orido","state":"Shizuoka"}'>Orido</div>
<div class="option" data='{"value":"Osaki","state":"Shizuoka"}'>Osaki</div>
<div class="option" data='{"value":"Oyama","state":"Shizuoka"}'>Oyama</div>
<div class="option" data='{"value":"Riemon","state":"Shizuoka"}'>Riemon</div>
<div class="option" data='{"value":"Ryoke","state":"Shizuoka"}'>Ryoke</div>
<div class="option" data='{"value":"Sagara","state":"Shizuoka"}'>Sagara</div>
<div class="option" data='{"value":"Sakamoto","state":"Shizuoka"}'>Sakamoto</div>
<div class="option" data='{"value":"Sakuma","state":"Shizuoka"}'>Sakuma</div>
<div class="option" data='{"value":"Samejima","state":"Shizuoka"}'>Samejima</div>
<div class="option" data='{"value":"Seikenji","state":"Shizuoka"}'>Seikenji</div>
<div class="option" data='{"value":"Sejiri","state":"Shizuoka"}'>Sejiri</div>
<div class="option" data='{"value":"Senzu","state":"Shizuoka"}'>Senzu</div>
<div class="option" data='{"value":"Settaichaya","state":"Shizuoka"}'>Settaichaya</div>
<div class="option" data='{"value":"Shibakawa","state":"Shizuoka"}'>Shibakawa</div>
<div class="option" data='{"value":"Shimada","state":"Shizuoka"}'>Shimada</div>
<div class="option" data='{"value":"Shimizu","state":"Shizuoka"}'>Shimizu</div>
<div class="option" data='{"value":"Shimizuhatoba","state":"Shizuoka"}'>Shimizuhatoba</div>
<div class="option" data='{"value":"Shimocha","state":"Shizuoka"}'>Shimocha</div>
<div class="option" data='{"value":"Shimoda","state":"Shizuoka"}'>Shimoda</div>
<div class="option" data='{"value":"Shimotcha","state":"Shizuoka"}'>Shimotcha</div>
<div class="option" data='{"value":"Shinden","state":"Shizuoka"}'>Shinden</div>
<div class="option" data='{"value":"Shiraha","state":"Shizuoka"}'>Shiraha</div>
<div class="option" data='{"value":"Shirahama","state":"Shizuoka"}'>Shirahama</div>
<div class="option" data='{"value":"Shirasuka","state":"Shizuoka"}'>Shirasuka</div>
<div class="option" data='{"value":"Shiroha","state":"Shizuoka"}'>Shiroha</div>
<div class="option" data='{"value":"Shirowa","state":"Shizuoka"}'>Shirowa</div>
<div class="option" data='{"value":"Shishihama","state":"Shizuoka"}'>Shishihama</div>
<div class="option" data='{"value":"Shizunami","state":"Shizuoka"}'>Shizunami</div>
<div class="option" data='{"value":"Shizuoka","state":"Shizuoka"}'>Shizuoka</div>
<div class="option" data='{"value":"Shusenji","state":"Shizuoka"}'>Shusenji</div>
<div class="option" data='{"value":"Shuzenji","state":"Shizuoka"}'>Shuzenji</div>
<div class="option" data='{"value":"Siduoka","state":"Shizuoka"}'>Siduoka</div>
<div class="option" data='{"value":"Simidu","state":"Shizuoka"}'>Simidu</div>
<div class="option" data='{"value":"Simizu","state":"Shizuoka"}'>Simizu</div>
<div class="option" data='{"value":"Sizuoka","state":"Shizuoka"}'>Sizuoka</div>
<div class="option" data='{"value":"Subashiri","state":"Shizuoka"}'>Subashiri</div>
<div class="option" data='{"value":"Suganuma","state":"Shizuoka"}'>Suganuma</div>
<div class="option" data='{"value":"Sugawa","state":"Shizuoka"}'>Sugawa</div>
<div class="option" data='{"value":"Sukawa","state":"Shizuoka"}'>Sukawa</div>
<div class="option" data='{"value":"Sumiyoshi","state":"Shizuoka"}'>Sumiyoshi</div>
<div class="option" data='{"value":"Susaki","state":"Shizuoka"}'>Susaki</div>
<div class="option" data='{"value":"Susuki","state":"Shizuoka"}'>Susuki</div>
<div class="option" data='{"value":"Suzaki","state":"Shizuoka"}'>Suzaki</div>
<div class="option" data='{"value":"Suzukawa","state":"Shizuoka"}'>Suzukawa</div>
<div class="option" data='{"value":"Suzukawamachi","state":"Shizuoka"}'>Suzukawamachi</div>
<div class="option" data='{"value":"Suzuki","state":"Shizuoka"}'>Suzuki</div>
<div class="option" data='{"value":"Tadama","state":"Shizuoka"}'>Tadama</div>
<div class="option" data='{"value":"Tadekata","state":"Shizuoka"}'>Tadekata</div>
<div class="option" data='{"value":"Taga","state":"Shizuoka"}'>Taga</div>
<div class="option" data='{"value":"Tago","state":"Shizuoka"}'>Tago</div>
<div class="option" data='{"value":"Taira","state":"Shizuoka"}'>Taira</div>
<div class="option" data='{"value":"Takajomachi","state":"Shizuoka"}'>Takajomachi</div>
<div class="option" data='{"value":"Takatsuka","state":"Shizuoka"}'>Takatsuka</div>
<div class="option" data='{"value":"Takazuka","state":"Shizuoka"}'>Takazuka</div>
<div class="option" data='{"value":"Tawarano","state":"Shizuoka"}'>Tawarano</div>
<div class="option" data='{"value":"Teishi","state":"Shizuoka"}'>Teishi</div>
<div class="option" data='{"value":"Toda","state":"Shizuoka"}'>Toda</div>
<div class="option" data='{"value":"Tohi","state":"Shizuoka"}'>Tohi</div>
<div class="option" data='{"value":"Toi","state":"Shizuoka"}'>Toi</div>
<div class="option" data='{"value":"Tsuburano","state":"Shizuoka"}'>Tsuburano</div>
<div class="option" data='{"value":"Tsukama","state":"Shizuoka"}'>Tsukama</div>
<div class="option" data='{"value":"Ugusu","state":"Shizuoka"}'>Ugusu</div>
<div class="option" data='{"value":"Ukihashi","state":"Shizuoka"}'>Ukihashi</div>
<div class="option" data='{"value":"Ukishima","state":"Shizuoka"}'>Ukishima</div>
<div class="option" data='{"value":"Ukusu","state":"Shizuoka"}'>Ukusu</div>
<div class="option" data='{"value":"Uriuno","state":"Shizuoka"}'>Uriuno</div>
<div class="option" data='{"value":"Uryuno","state":"Shizuoka"}'>Uryuno</div>
<div class="option" data='{"value":"Uyama","state":"Shizuoka"}'>Uyama</div>
<div class="option" data='{"value":"Wachi","state":"Shizuoka"}'>Wachi</div>
<div class="option" data='{"value":"Waji","state":"Shizuoka"}'>Waji</div>
<div class="option" data='{"value":"Wakami","state":"Shizuoka"}'>Wakami</div>
<div class="option" data='{"value":"Wakamidaira","state":"Shizuoka"}'>Wakamidaira</div>
<div class="option" data='{"value":"Warabo","state":"Shizuoka"}'>Warabo</div>
<div class="option" data='{"value":"Warao","state":"Shizuoka"}'>Warao</div>
<div class="option" data='{"value":"Washizu","state":"Shizuoka"}'>Washizu</div>
<div class="option" data='{"value":"Wasizu","state":"Shizuoka"}'>Wasizu</div>
<div class="option" data='{"value":"Yagiyama","state":"Shizuoka"}'>Yagiyama</div>
<div class="option" data='{"value":"Yahata","state":"Shizuoka"}'>Yahata</div>
<div class="option" data='{"value":"Yaidu","state":"Shizuoka"}'>Yaidu</div>
<div class="option" data='{"value":"Yaizu","state":"Shizuoka"}'>Yaizu</div>
<div class="option" data='{"value":"Yaizu Mati","state":"Shizuoka"}'>Yaizu Mati</div>
<div class="option" data='{"value":"Yakiyama","state":"Shizuoka"}'>Yakiyama</div>
<div class="option" data='{"value":"Yamada","state":"Shizuoka"}'>Yamada</div>
<div class="option" data='{"value":"Yamahara","state":"Shizuoka"}'>Yamahara</div>
<div class="option" data='{"value":"Yamanashi","state":"Shizuoka"}'>Yamanashi</div>
<div class="option" data='{"value":"Yambara","state":"Shizuoka"}'>Yambara</div>
<div class="option" data='{"value":"Yatsu","state":"Shizuoka"}'>Yatsu</div>
<div class="option" data='{"value":"Yawata","state":"Shizuoka"}'>Yawata</div>
<div class="option" data='{"value":"Yawatano","state":"Shizuoka"}'>Yawatano</div>
<div class="option" data='{"value":"Yokosuka","state":"Shizuoka"}'>Yokosuka</div>
<div class="option" data='{"value":"Yokosuna","state":"Shizuoka"}'>Yokosuna</div>
<div class="option" data='{"value":"Yoshinaga","state":"Shizuoka"}'>Yoshinaga</div>
<div class="option" data='{"value":"Yoshiwara","state":"Shizuoka"}'>Yoshiwara</div>
<div class="option" data='{"value":"Yugashima","state":"Shizuoka"}'>Yugashima</div>
<div class="option" data='{"value":"Yui","state":"Shizuoka"}'>Yui</div>
<div class="option" data='{"value":"Yuyama","state":"Shizuoka"}'>Yuyama</div>
<div class="option" id="option_end" data='{"value":"Zitogata","state":"Shizuoka"}'>Zitogata</div>

