<div class="option" data='{"value":"Asakayamacho","state":"Osaka"}'>Asakayamacho</div>
<div class="option" data='{"value":"Ashiharacho","state":"Osaka"}'>Ashiharacho</div>
<div class="option" data='{"value":"Babacho","state":"Osaka"}'>Babacho</div>
<div class="option" data='{"value":"Bode","state":"Osaka"}'>Bode</div>
<div class="option" data='{"value":"Bote","state":"Osaka"}'>Bote</div>
<div class="option" data='{"value":"Chishimacho","state":"Osaka"}'>Chishimacho</div>
<div class="option" data='{"value":"Choshoji","state":"Osaka"}'>Choshoji</div>
<div class="option" data='{"value":"Daito","state":"Osaka"}'>Daito</div>
<div class="option" data='{"value":"Doto","state":"Osaka"}'>Doto</div>
<div class="option" data='{"value":"Dotocho","state":"Osaka"}'>Dotocho</div>
<div class="option" data='{"value":"Dotomachi","state":"Osaka"}'>Dotomachi</div>
<div class="option" data='{"value":"Ebisucho","state":"Osaka"}'>Ebisucho</div>
<div class="option" data='{"value":"Fujisaka","state":"Osaka"}'>Fujisaka</div>
<div class="option" data='{"value":"Fuke","state":"Osaka"}'>Fuke</div>
<div class="option" data='{"value":"Fukui","state":"Osaka"}'>Fukui</div>
<div class="option" data='{"value":"Fukumachi","state":"Osaka"}'>Fukumachi</div>
<div class="option" data='{"value":"Funamachi","state":"Osaka"}'>Funamachi</div>
<div class="option" data='{"value":"Furuichi","state":"Osaka"}'>Furuichi</div>
<div class="option" data='{"value":"Furuichicho","state":"Osaka"}'>Furuichicho</div>
<div class="option" data='{"value":"Furukawabashi","state":"Osaka"}'>Furukawabashi</div>
<div class="option" data='{"value":"Furukawahashi","state":"Osaka"}'>Furukawahashi</div>
<div class="option" data='{"value":"Fuse","state":"Osaka"}'>Fuse</div>
<div class="option" data='{"value":"Fushio","state":"Osaka"}'>Fushio</div>
<div class="option" data='{"value":"Fushiocho","state":"Osaka"}'>Fushiocho</div>
<div class="option" data='{"value":"Hakata","state":"Osaka"}'>Hakata</div>
<div class="option" data='{"value":"Hakatacho","state":"Osaka"}'>Hakatacho</div>
<div class="option" data='{"value":"Hanaden","state":"Osaka"}'>Hanaden</div>
<div class="option" data='{"value":"Hanatemmachi","state":"Osaka"}'>Hanatemmachi</div>
<div class="option" data='{"value":"Hanaten","state":"Osaka"}'>Hanaten</div>
<div class="option" data='{"value":"Hanatencho","state":"Osaka"}'>Hanatencho</div>
<div class="option" data='{"value":"Hanazonocho","state":"Osaka"}'>Hanazonocho</div>
<div class="option" data='{"value":"Handa","state":"Osaka"}'>Handa</div>
<div class="option" data='{"value":"Haruki","state":"Osaka"}'>Haruki</div>
<div class="option" data='{"value":"Harukicho","state":"Osaka"}'>Harukicho</div>
<div class="option" data='{"value":"Haute","state":"Osaka"}'>Haute</div>
<div class="option" data='{"value":"Higashicho","state":"Osaka"}'>Higashicho</div>
<div class="option" data='{"value":"Higashimachi","state":"Osaka"}'>Higashimachi</div>
<div class="option" data='{"value":"Hirakata","state":"Osaka"}'>Hirakata</div>
<div class="option" data='{"value":"Hoshida","state":"Osaka"}'>Hoshida</div>
<div class="option" data='{"value":"Ibaragi","state":"Osaka"}'>Ibaragi</div>
<div class="option" data='{"value":"Ibaraki","state":"Osaka"}'>Ibaraki</div>
<div class="option" data='{"value":"Ichiba","state":"Osaka"}'>Ichiba</div>
<div class="option" data='{"value":"Imafuku","state":"Osaka"}'>Imafuku</div>
<div class="option" data='{"value":"Imafukucho","state":"Osaka"}'>Imafukucho</div>
<div class="option" data='{"value":"Imafukumachi","state":"Osaka"}'>Imafukumachi</div>
<div class="option" data='{"value":"Ishizucho","state":"Osaka"}'>Ishizucho</div>
<div class="option" data='{"value":"Izumi","state":"Osaka"}'>Izumi</div>
<div class="option" data='{"value":"Izumiotsu","state":"Osaka"}'>Izumiotsu</div>
<div class="option" data='{"value":"Jinai","state":"Osaka"}'>Jinai</div>
<div class="option" data='{"value":"Juso","state":"Osaka"}'>Juso</div>
<div class="option" data='{"value":"Jusocho","state":"Osaka"}'>Jusocho</div>
<div class="option" data='{"value":"Kadoma","state":"Osaka"}'>Kadoma</div>
<div class="option" data='{"value":"Kaitsuka","state":"Osaka"}'>Kaitsuka</div>
<div class="option" data='{"value":"Kaizuka","state":"Osaka"}'>Kaizuka</div>
<div class="option" data='{"value":"Kajima","state":"Osaka"}'>Kajima</div>
<div class="option" data='{"value":"Kajimacho","state":"Osaka"}'>Kajimacho</div>
<div class="option" data='{"value":"Karitacho","state":"Osaka"}'>Karitacho</div>
<div class="option" data='{"value":"Kashihara","state":"Osaka"}'>Kashihara</div>
<div class="option" data='{"value":"Kashiharacho","state":"Osaka"}'>Kashiharacho</div>
<div class="option" data='{"value":"Kashimacho","state":"Osaka"}'>Kashimacho</div>
<div class="option" data='{"value":"Kashiwabara","state":"Osaka"}'>Kashiwabara</div>
<div class="option" data='{"value":"Kashiwara","state":"Osaka"}'>Kashiwara</div>
<div class="option" data='{"value":"Kashoji","state":"Osaka"}'>Kashoji</div>
<div class="option" data='{"value":"Kasuga","state":"Osaka"}'>Kasuga</div>
<div class="option" data='{"value":"Katsuyama","state":"Osaka"}'>Katsuyama</div>
<div class="option" data='{"value":"Katsuyamadori","state":"Osaka"}'>Katsuyamadori</div>
<div class="option" data='{"value":"Kawachi","state":"Osaka"}'>Kawachi</div>
<div class="option" data='{"value":"Kawada","state":"Osaka"}'>Kawada</div>
<div class="option" data='{"value":"Kawaramachi","state":"Osaka"}'>Kawaramachi</div>
<div class="option" data='{"value":"Kawata","state":"Osaka"}'>Kawata</div>
<div class="option" data='{"value":"Kema","state":"Osaka"}'>Kema</div>
<div class="option" data='{"value":"Kemacho","state":"Osaka"}'>Kemacho</div>
<div class="option" data='{"value":"Kemamachi","state":"Osaka"}'>Kemamachi</div>
<div class="option" data='{"value":"Kisabe","state":"Osaka"}'>Kisabe</div>
<div class="option" data='{"value":"Kishiwada","state":"Osaka"}'>Kishiwada</div>
<div class="option" data='{"value":"Kisiwada","state":"Osaka"}'>Kisiwada</div>
<div class="option" data='{"value":"Kitafukusaki","state":"Osaka"}'>Kitafukusaki</div>
<div class="option" data='{"value":"Kitajimacho","state":"Osaka"}'>Kitajimacho</div>
<div class="option" data='{"value":"Kobayashicho","state":"Osaka"}'>Kobayashicho</div>
<div class="option" data='{"value":"Koencho","state":"Osaka"}'>Koencho</div>
<div class="option" data='{"value":"Kokubu","state":"Osaka"}'>Kokubu</div>
<div class="option" data='{"value":"Koyama","state":"Osaka"}'>Koyama</div>
<div class="option" data='{"value":"Kozu","state":"Osaka"}'>Kozu</div>
<div class="option" data='{"value":"Kubo","state":"Osaka"}'>Kubo</div>
<div class="option" data='{"value":"Kujo","state":"Osaka"}'>Kujo</div>
<div class="option" data='{"value":"Kumanda","state":"Osaka"}'>Kumanda</div>
<div class="option" data='{"value":"Kumanoda","state":"Osaka"}'>Kumanoda</div>
<div class="option" data='{"value":"Kunijima","state":"Osaka"}'>Kunijima</div>
<div class="option" data='{"value":"Kunijimacho","state":"Osaka"}'>Kunijimacho</div>
<div class="option" data='{"value":"Kunijimamachi","state":"Osaka"}'>Kunijimamachi</div>
<div class="option" data='{"value":"Kuraji","state":"Osaka"}'>Kuraji</div>
<div class="option" data='{"value":"Kyobashi","state":"Osaka"}'>Kyobashi</div>
<div class="option" data='{"value":"Kyuhoji","state":"Osaka"}'>Kyuhoji</div>
<div class="option" data='{"value":"Makino","state":"Osaka"}'>Makino</div>
<div class="option" data='{"value":"Matsubara","state":"Osaka"}'>Matsubara</div>
<div class="option" data='{"value":"Matsushimacho","state":"Osaka"}'>Matsushimacho</div>
<div class="option" data='{"value":"Mikaichi","state":"Osaka"}'>Mikaichi</div>
<div class="option" data='{"value":"Mikkaichi","state":"Osaka"}'>Mikkaichi</div>
<div class="option" data='{"value":"Mikuni","state":"Osaka"}'>Mikuni</div>
<div class="option" data='{"value":"Mikunicho","state":"Osaka"}'>Mikunicho</div>
<div class="option" data='{"value":"Mimiharacho","state":"Osaka"}'>Mimiharacho</div>
<div class="option" data='{"value":"Minamicho","state":"Osaka"}'>Minamicho</div>
<div class="option" data='{"value":"Minamikagaya","state":"Osaka"}'>Minamikagaya</div>
<div class="option" data='{"value":"Minatomachi","state":"Osaka"}'>Minatomachi</div>
<div class="option" data='{"value":"Minoo","state":"Osaka"}'>Minoo</div>
<div class="option" data='{"value":"Miyaharacho","state":"Osaka"}'>Miyaharacho</div>
<div class="option" data='{"value":"Miyake","state":"Osaka"}'>Miyake</div>
<div class="option" data='{"value":"Moriguchi","state":"Osaka"}'>Moriguchi</div>
<div class="option" data='{"value":"Nagano","state":"Osaka"}'>Nagano</div>
<div class="option" data='{"value":"Nakanoshima","state":"Osaka"}'>Nakanoshima</div>
<div class="option" data='{"value":"Namada","state":"Osaka"}'>Namada</div>
<div class="option" data='{"value":"Nashitsukuri","state":"Osaka"}'>Nashitsukuri</div>
<div class="option" data='{"value":"Nashizukuri","state":"Osaka"}'>Nashizukuri</div>
<div class="option" data='{"value":"Nishi Tanabe","state":"Osaka"}'>Nishi Tanabe</div>
<div class="option" data='{"value":"Nishigori","state":"Osaka"}'>Nishigori</div>
<div class="option" data='{"value":"Nishikigori","state":"Osaka"}'>Nishikigori</div>
<div class="option" data='{"value":"Nishikikori","state":"Osaka"}'>Nishikikori</div>
<div class="option" data='{"value":"Nishikori","state":"Osaka"}'>Nishikori</div>
<div class="option" data='{"value":"Niu","state":"Osaka"}'>Niu</div>
<div class="option" data='{"value":"Nomakuchi","state":"Osaka"}'>Nomakuchi</div>
<div class="option" data='{"value":"Nyu","state":"Osaka"}'>Nyu</div>
<div class="option" data='{"value":"Oka","state":"Osaka"}'>Oka</div>
<div class="option" data='{"value":"Osaka","state":"Osaka"}'>Osaka</div>
<div class="option" data='{"value":"Osaki","state":"Osaka"}'>Osaki</div>
<div class="option" data='{"value":"Otemaecho","state":"Osaka"}'>Otemaecho</div>
<div class="option" data='{"value":"Otemaenocho","state":"Osaka"}'>Otemaenocho</div>
<div class="option" data='{"value":"Otsu","state":"Osaka"}'>Otsu</div>
<div class="option" data='{"value":"Ozaki","state":"Osaka"}'>Ozaki</div>
<div class="option" data='{"value":"Sakai","state":"Osaka"}'>Sakai</div>
<div class="option" data='{"value":"Sakuragawa","state":"Osaka"}'>Sakuragawa</div>
<div class="option" data='{"value":"Sakuragawacho","state":"Osaka"}'>Sakuragawacho</div>
<div class="option" data='{"value":"Sakurajimacho","state":"Osaka"}'>Sakurajimacho</div>
<div class="option" data='{"value":"Sangenyacho","state":"Osaka"}'>Sangenyacho</div>
<div class="option" data='{"value":"Sano","state":"Osaka"}'>Sano</div>
<div class="option" data='{"value":"Sekimecho","state":"Osaka"}'>Sekimecho</div>
<div class="option" data='{"value":"Semba","state":"Osaka"}'>Semba</div>
<div class="option" data='{"value":"Sennyama","state":"Osaka"}'>Sennyama</div>
<div class="option" data='{"value":"Senriyama","state":"Osaka"}'>Senriyama</div>
<div class="option" data='{"value":"Shibajimacho","state":"Osaka"}'>Shibajimacho</div>
<div class="option" data='{"value":"Shibashimacho","state":"Osaka"}'>Shibashimacho</div>
<div class="option" data='{"value":"Shibatanicho","state":"Osaka"}'>Shibatanicho</div>
<div class="option" data='{"value":"Shichido Nishimachi","state":"Osaka"}'>Shichido Nishimachi</div>
<div class="option" data='{"value":"Shimomatsu","state":"Osaka"}'>Shimomatsu</div>
<div class="option" data='{"value":"Shimomatsucho","state":"Osaka"}'>Shimomatsucho</div>
<div class="option" data='{"value":"Shoki","state":"Osaka"}'>Shoki</div>
<div class="option" data='{"value":"Sugiyamacho","state":"Osaka"}'>Sugiyamacho</div>
<div class="option" data='{"value":"Suika","state":"Osaka"}'>Suika</div>
<div class="option" data='{"value":"Suita","state":"Osaka"}'>Suita</div>
<div class="option" data='{"value":"Sumiyoshi","state":"Osaka"}'>Sumiyoshi</div>
<div class="option" data='{"value":"Sumiyoshicho","state":"Osaka"}'>Sumiyoshicho</div>
<div class="option" data='{"value":"Tadaoka","state":"Osaka"}'>Tadaoka</div>
<div class="option" data='{"value":"Tagawa","state":"Osaka"}'>Tagawa</div>
<div class="option" data='{"value":"Takaishi","state":"Osaka"}'>Takaishi</div>
<div class="option" data='{"value":"Takatsuki","state":"Osaka"}'>Takatsuki</div>
<div class="option" data='{"value":"Takatuki","state":"Osaka"}'>Takatuki</div>
<div class="option" data='{"value":"Tanigawa","state":"Osaka"}'>Tanigawa</div>
<div class="option" data='{"value":"Tanikawa","state":"Osaka"}'>Tanikawa</div>
<div class="option" data='{"value":"Tannowa","state":"Osaka"}'>Tannowa</div>
<div class="option" data='{"value":"Tarui","state":"Osaka"}'>Tarui</div>
<div class="option" data='{"value":"Tennoji","state":"Osaka"}'>Tennoji</div>
<div class="option" data='{"value":"Tennojicho","state":"Osaka"}'>Tennojicho</div>
<div class="option" data='{"value":"Terauchi","state":"Osaka"}'>Terauchi</div>
<div class="option" data='{"value":"Tomijimacho","state":"Osaka"}'>Tomijimacho</div>
<div class="option" data='{"value":"Tomishimacho","state":"Osaka"}'>Tomishimacho</div>
<div class="option" data='{"value":"Tomobuchi","state":"Osaka"}'>Tomobuchi</div>
<div class="option" data='{"value":"Tomobuchicho","state":"Osaka"}'>Tomobuchicho</div>
<div class="option" data='{"value":"Tomobuchimachi","state":"Osaka"}'>Tomobuchimachi</div>
<div class="option" data='{"value":"Tomofuchicho","state":"Osaka"}'>Tomofuchicho</div>
<div class="option" data='{"value":"Tonda","state":"Osaka"}'>Tonda</div>
<div class="option" data='{"value":"Tondabayashi","state":"Osaka"}'>Tondabayashi</div>
<div class="option" data='{"value":"Tosabori","state":"Osaka"}'>Tosabori</div>
<div class="option" data='{"value":"Tosaboridori","state":"Osaka"}'>Tosaboridori</div>
<div class="option" data='{"value":"Toyonaka","state":"Osaka"}'>Toyonaka</div>
<div class="option" data='{"value":"Tsuda","state":"Osaka"}'>Tsuda</div>
<div class="option" data='{"value":"Tsuigomecho","state":"Osaka"}'>Tsuigomecho</div>
<div class="option" data='{"value":"Tsuigomicho","state":"Osaka"}'>Tsuigomicho</div>
<div class="option" data='{"value":"Tsumoricho","state":"Osaka"}'>Tsumoricho</div>
<div class="option" data='{"value":"Tsuruhamadori","state":"Osaka"}'>Tsuruhamadori</div>
<div class="option" data='{"value":"Tsurumachi","state":"Osaka"}'>Tsurumachi</div>
<div class="option" data='{"value":"Uchinohata","state":"Osaka"}'>Uchinohata</div>
<div class="option" data='{"value":"Umemachi","state":"Osaka"}'>Umemachi</div>
<div class="option" data='{"value":"Utsubo","state":"Osaka"}'>Utsubo</div>
<div class="option" data='{"value":"Yakumocho","state":"Osaka"}'>Yakumocho</div>
<div class="option" data='{"value":"Yamada","state":"Osaka"}'>Yamada</div>
<div class="option" data='{"value":"Yamaguchi","state":"Osaka"}'>Yamaguchi</div>
<div class="option" data='{"value":"Yamazaki","state":"Osaka"}'>Yamazaki</div>
<div class="option" data='{"value":"Yao","state":"Osaka"}'>Yao</div>
<div class="option" data='{"value":"Yaocho","state":"Osaka"}'>Yaocho</div>
<div class="option" data='{"value":"Yasaka","state":"Osaka"}'>Yasaka</div>
<div class="option" id="option_end" data='{"value":"Yoshimi","state":"Osaka"}'>Yoshimi</div>

