<div class="option" data='{"value":""}'>[ please select ]</div>
<div class="option" data='{"value":"Aichi"}'>Aichi</div>
<div class="option" data='{"value":"Akita"}'>Akita</div>
<div class="option" data='{"value":"Aomori"}'>Aomori</div>
<div class="option" data='{"value":"Chiba"}'>Chiba</div>
<div class="option" data='{"value":"Ehime"}'>Ehime</div>
<div class="option" data='{"value":"Fukui"}'>Fukui</div>
<div class="option" data='{"value":"Fukuoka"}'>Fukuoka</div>
<div class="option" data='{"value":"Fukushima"}'>Fukushima</div>
<div class="option" data='{"value":"Gifu"}'>Gifu</div>
<div class="option" data='{"value":"Gumma"}'>Gumma</div>
<div class="option" data='{"value":"Hiroshima"}'>Hiroshima</div>
<div class="option" data='{"value":"Hokkaido"}'>Hokkaido</div>
<div class="option" data='{"value":"Honshu-miyagi-ken"}'>Honshu-miyagi-ken</div>
<div class="option" data='{"value":"Hyogo"}'>Hyogo</div>
<div class="option" data='{"value":"Ibaraki"}'>Ibaraki</div>
<div class="option" data='{"value":"Ihate-ken"}'>Ihate-ken</div>
<div class="option" data='{"value":"Ishikawa"}'>Ishikawa</div>
<div class="option" data='{"value":"Japan "}'>Japan </div>
<div class="option" data='{"value":"Kagawa"}'>Kagawa</div>
<div class="option" data='{"value":"Kagoshima"}'>Kagoshima</div>
<div class="option" data='{"value":"Kanagawa"}'>Kanagawa</div>
<div class="option" data='{"value":"Kochi"}'>Kochi</div>
<div class="option" data='{"value":"Kumamoto"}'>Kumamoto</div>
<div class="option" data='{"value":"Kyoto"}'>Kyoto</div>
<div class="option" data='{"value":"Mie"}'>Mie</div>
<div class="option" data='{"value":"Miyazaki"}'>Miyazaki</div>
<div class="option" data='{"value":"Nagano"}'>Nagano</div>
<div class="option" data='{"value":"Nagasaki"}'>Nagasaki</div>
<div class="option" data='{"value":"Nara"}'>Nara</div>
<div class="option" data='{"value":"Niigata"}'>Niigata</div>
<div class="option" data='{"value":"Oita"}'>Oita</div>
<div class="option" data='{"value":"Okayama"}'>Okayama</div>
<div class="option" data='{"value":"Okinawa-ken"}'>Okinawa-ken</div>
<div class="option" data='{"value":"Osaka"}'>Osaka</div>
<div class="option" data='{"value":"Saga"}'>Saga</div>
<div class="option" data='{"value":"Saitama"}'>Saitama</div>
<div class="option" data='{"value":"Shiga"}'>Shiga</div>
<div class="option" data='{"value":"Shimane"}'>Shimane</div>
<div class="option" data='{"value":"Shizuoka"}'>Shizuoka</div>
<div class="option" data='{"value":"Tochigi"}'>Tochigi</div>
<div class="option" data='{"value":"Tokushima"}'>Tokushima</div>
<div class="option" data='{"value":"Tokyo-fu"}'>Tokyo-fu</div>
<div class="option" data='{"value":"Tottori"}'>Tottori</div>
<div class="option" data='{"value":"Toyama"}'>Toyama</div>
<div class="option" data='{"value":"Wakayama"}'>Wakayama</div>
<div class="option" data='{"value":"Yamagata"}'>Yamagata</div>
<div class="option" data='{"value":"Yamaguchi"}'>Yamaguchi</div>
<div id="option_end" class="option" data='{"value":"Yamanashi"}'>Yamanashi</div>