<div class="option" data='{"value":"Aimata","state":"Gumma"}'>Aimata</div>
<div class="option" data='{"value":"Akutsu","state":"Gumma"}'>Akutsu</div>
<div class="option" data='{"value":"Annaka","state":"Gumma"}'>Annaka</div>
<div class="option" data='{"value":"Azuma","state":"Gumma"}'>Azuma</div>
<div class="option" data='{"value":"Azumaiokozan","state":"Gumma"}'>Azumaiokozan</div>
<div class="option" data='{"value":"Doai","state":"Gumma"}'>Doai</div>
<div class="option" data='{"value":"Fujioka","state":"Gumma"}'>Fujioka</div>
<div class="option" data='{"value":"Fukuro","state":"Gumma"}'>Fukuro</div>
<div class="option" data='{"value":"Fukushima","state":"Gumma"}'>Fukushima</div>
<div class="option" data='{"value":"Fuse","state":"Gumma"}'>Fuse</div>
<div class="option" data='{"value":"Godo","state":"Gumma"}'>Godo</div>
<div class="option" data='{"value":"Gonda","state":"Gumma"}'>Gonda</div>
<div class="option" data='{"value":"Gumma","state":"Gumma"}'>Gumma</div>
<div class="option" data='{"value":"Haido","state":"Gumma"}'>Haido</div>
<div class="option" data='{"value":"Hakojima","state":"Gumma"}'>Hakojima</div>
<div class="option" data='{"value":"Hanawa","state":"Gumma"}'>Hanawa</div>
<div class="option" data='{"value":"Haneo","state":"Gumma"}'>Haneo</div>
<div class="option" data='{"value":"Hanezawa","state":"Gumma"}'>Hanezawa</div>
<div class="option" data='{"value":"Hara","state":"Gumma"}'>Hara</div>
<div class="option" data='{"value":"Haraichi","state":"Gumma"}'>Haraichi</div>
<div class="option" data='{"value":"Haramachi","state":"Gumma"}'>Haramachi</div>
<div class="option" data='{"value":"Hataya","state":"Gumma"}'>Hataya</div>
<div class="option" data='{"value":"Honjuku","state":"Gumma"}'>Honjuku</div>
<div class="option" data='{"value":"Horiguchi","state":"Gumma"}'>Horiguchi</div>
<div class="option" data='{"value":"Horikuchi","state":"Gumma"}'>Horikuchi</div>
<div class="option" data='{"value":"Ichiba","state":"Gumma"}'>Ichiba</div>
<div class="option" data='{"value":"Ichinomiya","state":"Gumma"}'>Ichinomiya</div>
<div class="option" data='{"value":"Ikaho","state":"Gumma"}'>Ikaho</div>
<div class="option" data='{"value":"Ikao","state":"Gumma"}'>Ikao</div>
<div class="option" data='{"value":"Imai","state":"Gumma"}'>Imai</div>
<div class="option" data='{"value":"Ise","state":"Gumma"}'>Ise</div>
<div class="option" data='{"value":"Isemachi","state":"Gumma"}'>Isemachi</div>
<div class="option" data='{"value":"Isesaki","state":"Gumma"}'>Isesaki</div>
<div class="option" data='{"value":"Isezaki","state":"Gumma"}'>Isezaki</div>
<div class="option" data='{"value":"Ishitsu","state":"Gumma"}'>Ishitsu</div>
<div class="option" data='{"value":"Ishizu","state":"Gumma"}'>Ishizu</div>
<div class="option" data='{"value":"Isobe","state":"Gumma"}'>Isobe</div>
<div class="option" data='{"value":"Itabana","state":"Gumma"}'>Itabana</div>
<div class="option" data='{"value":"Itahana","state":"Gumma"}'>Itahana</div>
<div class="option" data='{"value":"Iwado","state":"Gumma"}'>Iwado</div>
<div class="option" data='{"value":"Iwahana","state":"Gumma"}'>Iwahana</div>
<div class="option" data='{"value":"Iwajuku","state":"Gumma"}'>Iwajuku</div>
<div class="option" data='{"value":"Iwamoto","state":"Gumma"}'>Iwamoto</div>
<div class="option" data='{"value":"Iwamura","state":"Gumma"}'>Iwamura</div>
<div class="option" data='{"value":"Iwamuro","state":"Gumma"}'>Iwamuro</div>
<div class="option" data='{"value":"Iwashuku","state":"Gumma"}'>Iwashuku</div>
<div class="option" data='{"value":"Iwato","state":"Gumma"}'>Iwato</div>
<div class="option" data='{"value":"Kamada","state":"Gumma"}'>Kamada</div>
<div class="option" data='{"value":"Kamata","state":"Gumma"}'>Kamata</div>
<div class="option" data='{"value":"Kamiyuka","state":"Gumma"}'>Kamiyuka</div>
<div class="option" data='{"value":"Kanai","state":"Gumma"}'>Kanai</div>
<div class="option" data='{"value":"Kaneko","state":"Gumma"}'>Kaneko</div>
<div class="option" data='{"value":"Kanobara","state":"Gumma"}'>Kanobara</div>
<div class="option" data='{"value":"Kanohara","state":"Gumma"}'>Kanohara</div>
<div class="option" data='{"value":"Kazawa","state":"Gumma"}'>Kazawa</div>
<div class="option" data='{"value":"Kiriu","state":"Gumma"}'>Kiriu</div>
<div class="option" data='{"value":"Kiryu","state":"Gumma"}'>Kiryu</div>
<div class="option" data='{"value":"Kizaki","state":"Gumma"}'>Kizaki</div>
<div class="option" data='{"value":"Kobinata","state":"Gumma"}'>Kobinata</div>
<div class="option" data='{"value":"Kochi","state":"Gumma"}'>Kochi</div>
<div class="option" data='{"value":"Komagata","state":"Gumma"}'>Komagata</div>
<div class="option" data='{"value":"Komatsu","state":"Gumma"}'>Komatsu</div>
<div class="option" data='{"value":"Kunisada","state":"Gumma"}'>Kunisada</div>
<div class="option" data='{"value":"Kuragano","state":"Gumma"}'>Kuragano</div>
<div class="option" data='{"value":"Kuraganomachi","state":"Gumma"}'>Kuraganomachi</div>
<div class="option" data='{"value":"Kuruwacho","state":"Gumma"}'>Kuruwacho</div>
<div class="option" data='{"value":"Kuruwamachi","state":"Gumma"}'>Kuruwamachi</div>
<div class="option" data='{"value":"Kusatsu","state":"Gumma"}'>Kusatsu</div>
<div class="option" data='{"value":"Kusatu","state":"Gumma"}'>Kusatu</div>
<div class="option" data='{"value":"Maebashi","state":"Gumma"}'>Maebashi</div>
<div class="option" data='{"value":"Mamba","state":"Gumma"}'>Mamba</div>
<div class="option" data='{"value":"Matsuida","state":"Gumma"}'>Matsuida</div>
<div class="option" data='{"value":"Mihara","state":"Gumma"}'>Mihara</div>
<div class="option" data='{"value":"Minowa","state":"Gumma"}'>Minowa</div>
<div class="option" data='{"value":"Miyamaecho","state":"Gumma"}'>Miyamaecho</div>
<div class="option" data='{"value":"Miyosawa","state":"Gumma"}'>Miyosawa</div>
<div class="option" data='{"value":"Miyozawa","state":"Gumma"}'>Miyozawa</div>
<div class="option" data='{"value":"Motojiku","state":"Gumma"}'>Motojiku</div>
<div class="option" data='{"value":"Motojuku","state":"Gumma"}'>Motojuku</div>
<div class="option" data='{"value":"Naganohara","state":"Gumma"}'>Naganohara</div>
<div class="option" data='{"value":"Nakano","state":"Gumma"}'>Nakano</div>
<div class="option" data='{"value":"Nakanojo","state":"Gumma"}'>Nakanojo</div>
<div class="option" data='{"value":"Nakayama","state":"Gumma"}'>Nakayama</div>
<div class="option" data='{"value":"Nishikubo","state":"Gumma"}'>Nishikubo</div>
<div class="option" data='{"value":"Nishimachi","state":"Gumma"}'>Nishimachi</div>
<div class="option" data='{"value":"Numata","state":"Gumma"}'>Numata</div>
<div class="option" data='{"value":"Obata","state":"Gumma"}'>Obata</div>
<div class="option" data='{"value":"Odo","state":"Gumma"}'>Odo</div>
<div class="option" data='{"value":"Ogai","state":"Gumma"}'>Ogai</div>
<div class="option" data='{"value":"Ogo","state":"Gumma"}'>Ogo</div>
<div class="option" data='{"value":"Ogushi","state":"Gumma"}'>Ogushi</div>
<div class="option" data='{"value":"Ogushiiozan","state":"Gumma"}'>Ogushiiozan</div>
<div class="option" data='{"value":"Ojima","state":"Gumma"}'>Ojima</div>
<div class="option" data='{"value":"Okkai","state":"Gumma"}'>Okkai</div>
<div class="option" data='{"value":"Okkia","state":"Gumma"}'>Okkia</div>
<div class="option" data='{"value":"Okuwa","state":"Gumma"}'>Okuwa</div>
<div class="option" data='{"value":"Omama","state":"Gumma"}'>Omama</div>
<div class="option" data='{"value":"Omotecho","state":"Gumma"}'>Omotecho</div>
<div class="option" data='{"value":"Omura","state":"Gumma"}'>Omura</div>
<div class="option" data='{"value":"Osaki","state":"Gumma"}'>Osaki</div>
<div class="option" data='{"value":"Oshima","state":"Gumma"}'>Oshima</div>
<div class="option" data='{"value":"Ota","state":"Gumma"}'>Ota</div>
<div class="option" data='{"value":"Otani","state":"Gumma"}'>Otani</div>
<div class="option" data='{"value":"Oto","state":"Gumma"}'>Oto</div>
<div class="option" data='{"value":"Otomo","state":"Gumma"}'>Otomo</div>
<div class="option" data='{"value":"Oya","state":"Gumma"}'>Oya</div>
<div class="option" data='{"value":"Renjakucho","state":"Gumma"}'>Renjakucho</div>
<div class="option" data='{"value":"Ryumai","state":"Gumma"}'>Ryumai</div>
<div class="option" data='{"value":"Saikubo","state":"Gumma"}'>Saikubo</div>
<div class="option" data='{"value":"Sakai","state":"Gumma"}'>Sakai</div>
<div class="option" data='{"value":"Sakamoto","state":"Gumma"}'>Sakamoto</div>
<div class="option" data='{"value":"Saku","state":"Gumma"}'>Saku</div>
<div class="option" data='{"value":"Samata","state":"Gumma"}'>Samata</div>
<div class="option" data='{"value":"Sannokura","state":"Gumma"}'>Sannokura</div>
<div class="option" data='{"value":"Sarugakyo","state":"Gumma"}'>Sarugakyo</div>
<div class="option" data='{"value":"Shibukawa","state":"Gumma"}'>Shibukawa</div>
<div class="option" data='{"value":"Shima","state":"Gumma"}'>Shima</div>
<div class="option" data='{"value":"Shimmachi","state":"Gumma"}'>Shimmachi</div>
<div class="option" data='{"value":"Shimonita","state":"Gumma"}'>Shimonita</div>
<div class="option" data='{"value":"Shirane","state":"Gumma"}'>Shirane</div>
<div class="option" data='{"value":"Shiraneonsen","state":"Gumma"}'>Shiraneonsen</div>
<div class="option" data='{"value":"Soja","state":"Gumma"}'>Soja</div>
<div class="option" data='{"value":"Sosha","state":"Gumma"}'>Sosha</div>
<div class="option" data='{"value":"Sudagai","state":"Gumma"}'>Sudagai</div>
<div class="option" data='{"value":"Sudakai","state":"Gumma"}'>Sudakai</div>
<div class="option" data='{"value":"Takahira","state":"Gumma"}'>Takahira</div>
<div class="option" data='{"value":"Takasaki","state":"Gumma"}'>Takasaki</div>
<div class="option" data='{"value":"Takatoya","state":"Gumma"}'>Takatoya</div>
<div class="option" data='{"value":"Tamamura","state":"Gumma"}'>Tamamura</div>
<div class="option" data='{"value":"Tamegai","state":"Gumma"}'>Tamegai</div>
<div class="option" data='{"value":"Tanagai","state":"Gumma"}'>Tanagai</div>
<div class="option" data='{"value":"Tanakamachi","state":"Gumma"}'>Tanakamachi</div>
<div class="option" data='{"value":"Tashiro","state":"Gumma"}'>Tashiro</div>
<div class="option" data='{"value":"Tatebayashi","state":"Gumma"}'>Tatebayashi</div>
<div class="option" data='{"value":"Tateiwa","state":"Gumma"}'>Tateiwa</div>
<div class="option" data='{"value":"Tatsuiwa","state":"Gumma"}'>Tatsuiwa</div>
<div class="option" data='{"value":"Tokura","state":"Gumma"}'>Tokura</div>
<div class="option" data='{"value":"Tomioka","state":"Gumma"}'>Tomioka</div>
<div class="option" data='{"value":"Toyooka","state":"Gumma"}'>Toyooka</div>
<div class="option" data='{"value":"Tsuchiai","state":"Gumma"}'>Tsuchiai</div>
<div class="option" data='{"value":"Tsukiyono","state":"Gumma"}'>Tsukiyono</div>
<div class="option" data='{"value":"Yatoko","state":"Gumma"}'>Yatoko</div>
<div class="option" data='{"value":"Yokogawa","state":"Gumma"}'>Yokogawa</div>
<div class="option" data='{"value":"Yokokawa","state":"Gumma"}'>Yokokawa</div>
<div class="option" data='{"value":"Yoshii","state":"Gumma"}'>Yoshii</div>
<div class="option" data='{"value":"Yujuku","state":"Gumma"}'>Yujuku</div>
<div class="option" data='{"value":"Yushiku","state":"Gumma"}'>Yushiku</div>
<div class="option" data='{"value":"Yushuku","state":"Gumma"}'>Yushuku</div>
<div class="option" id="option_end" data='{"value":"Zama","state":"Gumma"}'>Zama</div>

