<div class="option" data='{"value":"Aji","state":"Kagawa"}'>Aji</div>
<div class="option" data='{"value":"Aogi","state":"Kagawa"}'>Aogi</div>
<div class="option" data='{"value":"Aoki","state":"Kagawa"}'>Aoki</div>
<div class="option" data='{"value":"Awashima","state":"Kagawa"}'>Awashima</div>
<div class="option" data='{"value":"Enza","state":"Kagawa"}'>Enza</div>
<div class="option" data='{"value":"Fuchisaki","state":"Kagawa"}'>Fuchisaki</div>
<div class="option" data='{"value":"Fuchizaki","state":"Kagawa"}'>Fuchizaki</div>
<div class="option" data='{"value":"Fukuda","state":"Kagawa"}'>Fukuda</div>
<div class="option" data='{"value":"Hama","state":"Kagawa"}'>Hama</div>
<div class="option" data='{"value":"Hamada","state":"Kagawa"}'>Hamada</div>
<div class="option" data='{"value":"Higashibun","state":"Kagawa"}'>Higashibun</div>
<div class="option" data='{"value":"Higashiura","state":"Kagawa"}'>Higashiura</div>
<div class="option" data='{"value":"Hijiki","state":"Kagawa"}'>Hijiki</div>
<div class="option" data='{"value":"Hikeda","state":"Kagawa"}'>Hikeda</div>
<div class="option" data='{"value":"Hiketa","state":"Kagawa"}'>Hiketa</div>
<div class="option" data='{"value":"Hommura","state":"Kagawa"}'>Hommura</div>
<div class="option" data='{"value":"Honjima","state":"Kagawa"}'>Honjima</div>
<div class="option" data='{"value":"Honura","state":"Kagawa"}'>Honura</div>
<div class="option" data='{"value":"Ibuki","state":"Kagawa"}'>Ibuki</div>
<div class="option" data='{"value":"Ibukijima","state":"Kagawa"}'>Ibukijima</div>
<div class="option" data='{"value":"Ichii","state":"Kagawa"}'>Ichii</div>
<div class="option" data='{"value":"Ichimonji","state":"Kagawa"}'>Ichimonji</div>
<div class="option" data='{"value":"Ienoura","state":"Kagawa"}'>Ienoura</div>
<div class="option" data='{"value":"Ieura","state":"Kagawa"}'>Ieura</div>
<div class="option" data='{"value":"Igisue","state":"Kagawa"}'>Igisue</div>
<div class="option" data='{"value":"Ikeda","state":"Kagawa"}'>Ikeda</div>
<div class="option" data='{"value":"Ikisue","state":"Kagawa"}'>Ikisue</div>
<div class="option" data='{"value":"Kagawa","state":"Kagawa"}'>Kagawa</div>
<div class="option" data='{"value":"Kaminoura","state":"Kagawa"}'>Kaminoura</div>
<div class="option" data='{"value":"Kannonji","state":"Kagawa"}'>Kannonji</div>
<div class="option" data='{"value":"Kannonzi","state":"Kagawa"}'>Kannonzi</div>
<div class="option" data='{"value":"Kanonji","state":"Kagawa"}'>Kanonji</div>
<div class="option" data='{"value":"Kasuga","state":"Kagawa"}'>Kasuga</div>
<div class="option" data='{"value":"Kawashima","state":"Kagawa"}'>Kawashima</div>
<div class="option" data='{"value":"Kinashi","state":"Kagawa"}'>Kinashi</div>
<div class="option" data='{"value":"Kokubu","state":"Kagawa"}'>Kokubu</div>
<div class="option" data='{"value":"Konoura","state":"Kagawa"}'>Konoura</div>
<div class="option" data='{"value":"Konzoji","state":"Kagawa"}'>Konzoji</div>
<div class="option" data='{"value":"Kosai","state":"Kagawa"}'>Kosai</div>
<div class="option" data='{"value":"Kose","state":"Kagawa"}'>Kose</div>
<div class="option" data='{"value":"Koteshima","state":"Kagawa"}'>Koteshima</div>
<div class="option" data='{"value":"Kotohira","state":"Kagawa"}'>Kotohira</div>
<div class="option" data='{"value":"Kotohiro","state":"Kagawa"}'>Kotohiro</div>
<div class="option" data='{"value":"Kozai","state":"Kagawa"}'>Kozai</div>
<div class="option" data='{"value":"Koze","state":"Kagawa"}'>Koze</div>
<div class="option" data='{"value":"Kusababe","state":"Kagawa"}'>Kusababe</div>
<div class="option" data='{"value":"Kusakabe","state":"Kagawa"}'>Kusakabe</div>
<div class="option" data='{"value":"Kusakabehommachi","state":"Kagawa"}'>Kusakabehommachi</div>
<div class="option" data='{"value":"Kusukamicho","state":"Kagawa"}'>Kusukamicho</div>
<div class="option" data='{"value":"Kusukamimachi","state":"Kagawa"}'>Kusukamimachi</div>
<div class="option" data='{"value":"Machida","state":"Kagawa"}'>Machida</div>
<div class="option" data='{"value":"Marugame","state":"Kagawa"}'>Marugame</div>
<div class="option" data='{"value":"Marukame","state":"Kagawa"}'>Marukame</div>
<div class="option" data='{"value":"Matoba","state":"Kagawa"}'>Matoba</div>
<div class="option" data='{"value":"Megishima","state":"Kagawa"}'>Megishima</div>
<div class="option" data='{"value":"Miyaji","state":"Kagawa"}'>Miyaji</div>
<div class="option" data='{"value":"Motoshima","state":"Kagawa"}'>Motoshima</div>
<div class="option" data='{"value":"Motoura","state":"Kagawa"}'>Motoura</div>
<div class="option" data='{"value":"Muromoto","state":"Kagawa"}'>Muromoto</div>
<div class="option" data='{"value":"Nagao","state":"Kagawa"}'>Nagao</div>
<div class="option" data='{"value":"Naiden","state":"Kagawa"}'>Naiden</div>
<div class="option" data='{"value":"Nanabancho","state":"Kagawa"}'>Nanabancho</div>
<div class="option" data='{"value":"Naoshima","state":"Kagawa"}'>Naoshima</div>
<div class="option" data='{"value":"Nio","state":"Kagawa"}'>Nio</div>
<div class="option" data='{"value":"Obe","state":"Kagawa"}'>Obe</div>
<div class="option" data='{"value":"Oda","state":"Kagawa"}'>Oda</div>
<div class="option" data='{"value":"Odeshima","state":"Kagawa"}'>Odeshima</div>
<div class="option" data='{"value":"Ogijima","state":"Kagawa"}'>Ogijima</div>
<div class="option" data='{"value":"Ogishima","state":"Kagawa"}'>Ogishima</div>
<div class="option" data='{"value":"Ohama","state":"Kagawa"}'>Ohama</div>
<div class="option" data='{"value":"Oiage","state":"Kagawa"}'>Oiage</div>
<div class="option" data='{"value":"Oikami","state":"Kagawa"}'>Oikami</div>
<div class="option" data='{"value":"Oninashi","state":"Kagawa"}'>Oninashi</div>
<div class="option" data='{"value":"Oyabu","state":"Kagawa"}'>Oyabu</div>
<div class="option" data='{"value":"Sakaide","state":"Kagawa"}'>Sakaide</div>
<div class="option" data='{"value":"Sakaidecho","state":"Kagawa"}'>Sakaidecho</div>
<div class="option" data='{"value":"Sakate","state":"Kagawa"}'>Sakate</div>
<div class="option" data='{"value":"Sambancho","state":"Kagawa"}'>Sambancho</div>
<div class="option" data='{"value":"Sambommatsu","state":"Kagawa"}'>Sambommatsu</div>
<div class="option" data='{"value":"Sanbancho","state":"Kagawa"}'>Sanbancho</div>
<div class="option" data='{"value":"Sanbommatsu","state":"Kagawa"}'>Sanbommatsu</div>
<div class="option" data='{"value":"Sei","state":"Kagawa"}'>Sei</div>
<div class="option" data='{"value":"Shichibancho","state":"Kagawa"}'>Shichibancho</div>
<div class="option" data='{"value":"Shichika","state":"Kagawa"}'>Shichika</div>
<div class="option" data='{"value":"Shido","state":"Kagawa"}'>Shido</div>
<div class="option" data='{"value":"Shimmei","state":"Kagawa"}'>Shimmei</div>
<div class="option" data='{"value":"Shimminatomachi","state":"Kagawa"}'>Shimminatomachi</div>
<div class="option" data='{"value":"Shimmyo","state":"Kagawa"}'>Shimmyo</div>
<div class="option" data='{"value":"Shimo","state":"Kagawa"}'>Shimo</div>
<div class="option" data='{"value":"Shimomura","state":"Kagawa"}'>Shimomura</div>
<div class="option" data='{"value":"Shinmyo","state":"Kagawa"}'>Shinmyo</div>
<div class="option" data='{"value":"Shioiria","state":"Kagawa"}'>Shioiria</div>
<div class="option" data='{"value":"Shionoe","state":"Kagawa"}'>Shionoe</div>
<div class="option" data='{"value":"Shioya","state":"Kagawa"}'>Shioya</div>
<div class="option" data='{"value":"Tadotsu","state":"Kagawa"}'>Tadotsu</div>
<div class="option" data='{"value":"Tadotsucho","state":"Kagawa"}'>Tadotsucho</div>
<div class="option" data='{"value":"Takamatsu","state":"Kagawa"}'>Takamatsu</div>
<div class="option" data='{"value":"Takamatu","state":"Kagawa"}'>Takamatu</div>
<div class="option" data='{"value":"Takamijima","state":"Kagawa"}'>Takamijima</div>
<div class="option" data='{"value":"Takamishima","state":"Kagawa"}'>Takamishima</div>
<div class="option" data='{"value":"Takaya","state":"Kagawa"}'>Takaya</div>
<div class="option" data='{"value":"Takenoura","state":"Kagawa"}'>Takenoura</div>
<div class="option" data='{"value":"Takeura","state":"Kagawa"}'>Takeura</div>
<div class="option" data='{"value":"Takima","state":"Kagawa"}'>Takima</div>
<div class="option" data='{"value":"Takinomiya","state":"Kagawa"}'>Takinomiya</div>
<div class="option" data='{"value":"Takuma","state":"Kagawa"}'>Takuma</div>
<div class="option" data='{"value":"Tanokuchi","state":"Kagawa"}'>Tanokuchi</div>
<div class="option" data='{"value":"Tanoura","state":"Kagawa"}'>Tanoura</div>
<div class="option" data='{"value":"Tatsukawa","state":"Kagawa"}'>Tatsukawa</div>
<div class="option" data='{"value":"Tenjimmae","state":"Kagawa"}'>Tenjimmae</div>
<div class="option" data='{"value":"Teshima","state":"Kagawa"}'>Teshima</div>
<div class="option" data='{"value":"Tobun","state":"Kagawa"}'>Tobun</div>
<div class="option" data='{"value":"Tomari","state":"Kagawa"}'>Tomari</div>
<div class="option" data='{"value":"Tonosho","state":"Kagawa"}'>Tonosho</div>
<div class="option" data='{"value":"Tonosyo","state":"Kagawa"}'>Tonosyo</div>
<div class="option" data='{"value":"Toyohama","state":"Kagawa"}'>Toyohama</div>
<div class="option" data='{"value":"Tsuda","state":"Kagawa"}'>Tsuda</div>
<div class="option" data='{"value":"Tsuruha","state":"Kagawa"}'>Tsuruha</div>
<div class="option" data='{"value":"Tsuruwa","state":"Kagawa"}'>Tsuruwa</div>
<div class="option" data='{"value":"Turuha","state":"Kagawa"}'>Turuha</div>
<div class="option" data='{"value":"Uchida","state":"Kagawa"}'>Uchida</div>
<div class="option" data='{"value":"Urao","state":"Kagawa"}'>Urao</div>
<div class="option" data='{"value":"Uro","state":"Kagawa"}'>Uro</div>
<div class="option" data='{"value":"Ushijima","state":"Kagawa"}'>Ushijima</div>
<div class="option" data='{"value":"Ushishima","state":"Kagawa"}'>Ushishima</div>
<div class="option" data='{"value":"Utazu","state":"Kagawa"}'>Utazu</div>
<div class="option" data='{"value":"Yamawaki","state":"Kagawa"}'>Yamawaki</div>
<div class="option" data='{"value":"Yodayama","state":"Kagawa"}'>Yodayama</div>
<div class="option" data='{"value":"Yoshimi","state":"Kagawa"}'>Yoshimi</div>
<div class="option" data='{"value":"Yotayama","state":"Kagawa"}'>Yotayama</div>
<div class="option" data='{"value":"Yuturiha","state":"Kagawa"}'>Yuturiha</div>
<div class="option" data='{"value":"Yuzuriha","state":"Kagawa"}'>Yuzuriha</div>
<div class="option" id="option_end" data='{"value":"Zentsujicho","state":"Kagawa"}'>Zentsujicho</div>

