<%@ page contentType="text/html; charset=iso-8859-1" language="java" import="java.io.* , java.util.* , java.sql.* , java.util.Calendar , java.text.SimpleDateFormat" %>

<%!	
String state = null;
%>

<%
state = request.getParameter("state");
	if (state != null)
	{
		if (state.equals("Greenland"))
		{
%>
<div class="option" data='{"value":"Aalatsivik","state":"Greenland"}'>Aalatsivik</div>
<div class="option" data='{"value":"Aappilattoq","state":"Greenland"}'>Aappilattoq</div>
<div class="option" data='{"value":"Aappilattorq","state":"Greenland"}'>Aappilattorq</div>
<div class="option" data='{"value":"Aasiaat","state":"Greenland"}'>Aasiaat</div>
<div class="option" data='{"value":"Aasivik","state":"Greenland"}'>Aasivik</div>
<div class="option" data='{"value":"Agdluitsoq","state":"Greenland"}'>Agdluitsoq</div>
<div class="option" data='{"value":"Agdluitsup Pa","state":"Greenland"}'>Agdluitsup Pa</div>
<div class="option" data='{"value":"Agpamiut","state":"Greenland"}'>Agpamiut</div>
<div class="option" data='{"value":"Agparssuit","state":"Greenland"}'>Agparssuit</div>
<div class="option" data='{"value":"Agpat","state":"Greenland"}'>Agpat</div>
<div class="option" data='{"value":"Agto","state":"Greenland"}'>Agto</div>
<div class="option" data='{"value":"Akigsungek","state":"Greenland"}'>Akigsungek</div>
<div class="option" data='{"value":"Akinaitsat","state":"Greenland"}'>Akinaitsat</div>
<div class="option" data='{"value":"Akinatsiait","state":"Greenland"}'>Akinatsiait</div>
<div class="option" data='{"value":"Akiqsserniak","state":"Greenland"}'>Akiqsserniak</div>
<div class="option" data='{"value":"Akugdlek","state":"Greenland"}'>Akugdlek</div>
<div class="option" data='{"value":"Akugdlit","state":"Greenland"}'>Akugdlit</div>
<div class="option" data='{"value":"Akuliarusek","state":"Greenland"}'>Akuliarusek</div>
<div class="option" data='{"value":"Akuliaruseq","state":"Greenland"}'>Akuliaruseq</div>
<div class="option" data='{"value":"Akulliit","state":"Greenland"}'>Akulliit</div>
<div class="option" data='{"value":"Akumak","state":"Greenland"}'>Akumak</div>
<div class="option" data='{"value":"Akunaq","state":"Greenland"}'>Akunaq</div>
<div class="option" data='{"value":"Akunnaaq","state":"Greenland"}'>Akunnaaq</div>
<div class="option" data='{"value":"Alluitsoq","state":"Greenland"}'>Alluitsoq</div>
<div class="option" data='{"value":"Alluitsup Paa","state":"Greenland"}'>Alluitsup Paa</div>
<div class="option" data='{"value":"Amerdlok","state":"Greenland"}'>Amerdlok</div>
<div class="option" data='{"value":"Ammassalik","state":"Greenland"}'>Ammassalik</div>
<div class="option" data='{"value":"Ammassivik","state":"Greenland"}'>Ammassivik</div>
<div class="option" data='{"value":"Angmagssalik","state":"Greenland"}'>Angmagssalik</div>
<div class="option" data='{"value":"Angmagssivik","state":"Greenland"}'>Angmagssivik</div>
<div class="option" data='{"value":"Angmagsslik","state":"Greenland"}'>Angmagsslik</div>
<div class="option" data='{"value":"Angmassalik","state":"Greenland"}'>Angmassalik</div>
<div class="option" data='{"value":"Anordliuitsoq","state":"Greenland"}'>Anordliuitsoq</div>
<div class="option" data='{"value":"Anorliuitsoq","state":"Greenland"}'>Anorliuitsoq</div>
<div class="option" data='{"value":"Appaarsuit","state":"Greenland"}'>Appaarsuit</div>
<div class="option" data='{"value":"Appamiut","state":"Greenland"}'>Appamiut</div>
<div class="option" data='{"value":"Appat","state":"Greenland"}'>Appat</div>
<div class="option" data='{"value":"Aputiteeq","state":"Greenland"}'>Aputiteeq</div>
<div class="option" data='{"value":"Aputiteq","state":"Greenland"}'>Aputiteq</div>
<div class="option" data='{"value":"Aqigsserniaq","state":"Greenland"}'>Aqigsserniaq</div>
<div class="option" data='{"value":"Aqisserniaq","state":"Greenland"}'>Aqisserniaq</div>
<div class="option" data='{"value":"Arsivik","state":"Greenland"}'>Arsivik</div>
<div class="option" data='{"value":"Arsuk","state":"Greenland"}'>Arsuk</div>
<div class="option" data='{"value":"Asatdlut","state":"Greenland"}'>Asatdlut</div>
<div class="option" data='{"value":"Assaqutaq","state":"Greenland"}'>Assaqutaq</div>
<div class="option" data='{"value":"Ata","state":"Greenland"}'>Ata</div>
<div class="option" data='{"value":"Ataa","state":"Greenland"}'>Ataa</div>
<div class="option" data='{"value":"Atammik","state":"Greenland"}'>Atammik</div>
<div class="option" data='{"value":"Atangmik","state":"Greenland"}'>Atangmik</div>
<div class="option" data='{"value":"Atarta","state":"Greenland"}'>Atarta</div>
<div class="option" data='{"value":"Attu","state":"Greenland"}'>Attu</div>
<div class="option" data='{"value":"Augpaiartok","state":"Greenland"}'>Augpaiartok</div>
<div class="option" data='{"value":"Augpalartok","state":"Greenland"}'>Augpalartok</div>
<div class="option" data='{"value":"Augpilagtok","state":"Greenland"}'>Augpilagtok</div>
<div class="option" data='{"value":"Augpilagtoq","state":"Greenland"}'>Augpilagtoq</div>
<div class="option" data='{"value":"Aulatsivik","state":"Greenland"}'>Aulatsivik</div>
<div class="option" data='{"value":"Aumarutigssat","state":"Greenland"}'>Aumarutigssat</div>
<div class="option" data='{"value":"Ausiait","state":"Greenland"}'>Ausiait</div>
<div class="option" data='{"value":"Aussivik","state":"Greenland"}'>Aussivik</div>
<div class="option" data='{"value":"Autdlainiarfinguaq","state":"Greenland"}'>Autdlainiarfinguaq</div>
<div class="option" data='{"value":"Avangnardlit","state":"Greenland"}'>Avangnardlit</div>
<div class="option" data='{"value":"Avigaat","state":"Greenland"}'>Avigaat</div>
<div class="option" data='{"value":"Avigait","state":"Greenland"}'>Avigait</div>
<div class="option" data='{"value":"Avssaqutaq","state":"Greenland"}'>Avssaqutaq</div>
<div class="option" data='{"value":"Camp Lloyd","state":"Greenland"}'>Camp Lloyd</div>
<div class="option" data='{"value":"Cape York","state":"Greenland"}'>Cape York</div>
<div class="option" data='{"value":"Christianshaab","state":"Greenland"}'>Christianshaab</div>
<div class="option" data='{"value":"Christianshab","state":"Greenland"}'>Christianshab</div>
<div class="option" data='{"value":"Claushavn","state":"Greenland"}'>Claushavn</div>
<div class="option" data='{"value":"Diskofjord","state":"Greenland"}'>Diskofjord</div>
<div class="option" data='{"value":"Dundas","state":"Greenland"}'>Dundas</div>
<div class="option" data='{"value":"East Proven","state":"Greenland"}'>East Proven</div>
<div class="option" data='{"value":"Egedesminde","state":"Greenland"}'>Egedesminde</div>
<div class="option" data='{"value":"Ekogfat","state":"Greenland"}'>Ekogfat</div>
<div class="option" data='{"value":"Eqalugaarsuit","state":"Greenland"}'>Eqalugaarsuit</div>
<div class="option" data='{"value":"Eqi","state":"Greenland"}'>Eqi</div>
<div class="option" data='{"value":"Eripassut","state":"Greenland"}'>Eripassut</div>
<div class="option" data='{"value":"Erkigtok","state":"Greenland"}'>Erkigtok</div>
<div class="option" data='{"value":"Etah","state":"Greenland"}'>Etah</div>
<div class="option" data='{"value":"Evkitsok","state":"Greenland"}'>Evkitsok</div>
<div class="option" data='{"value":"Faeringerhavnen","state":"Greenland"}'>Faeringerhavnen</div>
<div class="option" data='{"value":"Faringehavn","state":"Greenland"}'>Faringehavn</div>
<div class="option" data='{"value":"Finnsbu","state":"Greenland"}'>Finnsbu</div>
<div class="option" data='{"value":"Fiskenaes","state":"Greenland"}'>Fiskenaes</div>
<div class="option" data='{"value":"Fiskenasset","state":"Greenland"}'>Fiskenasset</div>
<div class="option" data='{"value":"Fiskengesset","state":"Greenland"}'>Fiskengesset</div>
<div class="option" data='{"value":"Fiskernas","state":"Greenland"}'>Fiskernas</div>
<div class="option" data='{"value":"Frederiksdal","state":"Greenland"}'>Frederiksdal</div>
<div class="option" data='{"value":"Frederikshaab","state":"Greenland"}'>Frederikshaab</div>
<div class="option" data='{"value":"Frederikshab","state":"Greenland"}'>Frederikshab</div>
<div class="option" data='{"value":"Gamle Egedesminde","state":"Greenland"}'>Gamle Egedesminde</div>
<div class="option" data='{"value":"Gamle Qutdligssat","state":"Greenland"}'>Gamle Qutdligssat</div>
<div class="option" data='{"value":"Gammel Sukkertoppen","state":"Greenland"}'>Gammel Sukkertoppen</div>
<div class="option" data='{"value":"Godhavn","state":"Greenland"}'>Godhavn</div>
<div class="option" data='{"value":"Godthaab","state":"Greenland"}'>Godthaab</div>
<div class="option" data='{"value":"Godthab","state":"Greenland"}'>Godthab</div>
<div class="option" data='{"value":"Greenland","state":"Greenland"}'>Greenland</div>
<div class="option" data='{"value":"Gronland","state":"Greenland"}'>Gronland</div>
<div class="option" data='{"value":"Gronnedal","state":"Greenland"}'>Gronnedal</div>
<div class="option" data='{"value":"Harbor Camp","state":"Greenland"}'>Harbor Camp</div>
<div class="option" data='{"value":"Herjolfsnes","state":"Greenland"}'>Herjolfsnes</div>
<div class="option" data='{"value":"Holsteinborg","state":"Greenland"}'>Holsteinborg</div>
<div class="option" data='{"value":"Holsteinsborg","state":"Greenland"}'>Holsteinsborg</div>
<div class="option" data='{"value":"Holstenborg","state":"Greenland"}'>Holstenborg</div>
<div class="option" data='{"value":"Holstensborg","state":"Greenland"}'>Holstensborg</div>
<div class="option" data='{"value":"Hunde Ejland","state":"Greenland"}'>Hunde Ejland</div>
<div class="option" data='{"value":"Igaliko","state":"Greenland"}'>Igaliko</div>
<div class="option" data='{"value":"Igaliku","state":"Greenland"}'>Igaliku</div>
<div class="option" data='{"value":"Igdloluarsuit","state":"Greenland"}'>Igdloluarsuit</div>
<div class="option" data='{"value":"Igdlorpait","state":"Greenland"}'>Igdlorpait</div>
<div class="option" data='{"value":"Igdlorqortormiut","state":"Greenland"}'>Igdlorqortormiut</div>
<div class="option" data='{"value":"Igdlorssuit","state":"Greenland"}'>Igdlorssuit</div>
<div class="option" data='{"value":"Igdlorsuit","state":"Greenland"}'>Igdlorsuit</div>
<div class="option" data='{"value":"Igdluiartorfik","state":"Greenland"}'>Igdluiartorfik</div>
<div class="option" data='{"value":"Igdlukavsak","state":"Greenland"}'>Igdlukavsak</div>
<div class="option" data='{"value":"Igdlukorssuit","state":"Greenland"}'>Igdlukorssuit</div>
<div class="option" data='{"value":"Igdluligssuak","state":"Greenland"}'>Igdluligssuak</div>
<div class="option" data='{"value":"Igdlulik","state":"Greenland"}'>Igdlulik</div>
<div class="option" data='{"value":"Igdluluarssuit","state":"Greenland"}'>Igdluluarssuit</div>
<div class="option" data='{"value":"Igdlumiut","state":"Greenland"}'>Igdlumiut</div>
<div class="option" data='{"value":"Igdlunguaq","state":"Greenland"}'>Igdlunguaq</div>
<div class="option" data='{"value":"Iginiarfik","state":"Greenland"}'>Iginiarfik</div>
<div class="option" data='{"value":"Iginniarfik","state":"Greenland"}'>Iginniarfik</div>
<div class="option" data='{"value":"Igssalik","state":"Greenland"}'>Igssalik</div>
<div class="option" data='{"value":"Igterajivit","state":"Greenland"}'>Igterajivit</div>
<div class="option" data='{"value":"Igtorqortormit","state":"Greenland"}'>Igtorqortormit</div>
<div class="option" data='{"value":"Igtumit","state":"Greenland"}'>Igtumit</div>
<div class="option" data='{"value":"Ikamiut","state":"Greenland"}'>Ikamiut</div>
<div class="option" data='{"value":"Ikateq","state":"Greenland"}'>Ikateq</div>
<div class="option" data='{"value":"Ikerarssuk","state":"Greenland"}'>Ikerarssuk</div>
<div class="option" data='{"value":"Ikerasaarsuk","state":"Greenland"}'>Ikerasaarsuk</div>
<div class="option" data='{"value":"Ikerasagssuak","state":"Greenland"}'>Ikerasagssuak</div>
<div class="option" data='{"value":"Ikerasagssuaq","state":"Greenland"}'>Ikerasagssuaq</div>
<div class="option" data='{"value":"Ikerasak","state":"Greenland"}'>Ikerasak</div>
<div class="option" data='{"value":"Ikerasarssuk","state":"Greenland"}'>Ikerasarssuk</div>
<div class="option" data='{"value":"Ikerasassuaq","state":"Greenland"}'>Ikerasassuaq</div>
<div class="option" data='{"value":"Ikeraussak","state":"Greenland"}'>Ikeraussak</div>
<div class="option" data='{"value":"Ikeraussek","state":"Greenland"}'>Ikeraussek</div>
<div class="option" data='{"value":"Ikigait","state":"Greenland"}'>Ikigait</div>
<div class="option" data='{"value":"Ikkamiut","state":"Greenland"}'>Ikkamiut</div>
<div class="option" data='{"value":"Ikorfat","state":"Greenland"}'>Ikorfat</div>
<div class="option" data='{"value":"Ilimanaq","state":"Greenland"}'>Ilimanaq</div>
<div class="option" data='{"value":"Ilivileq","state":"Greenland"}'>Ilivileq</div>
<div class="option" data='{"value":"Illoqqortoormiut","state":"Greenland"}'>Illoqqortoormiut</div>
<div class="option" data='{"value":"Illorpaat","state":"Greenland"}'>Illorpaat</div>
<div class="option" data='{"value":"Illorsuit","state":"Greenland"}'>Illorsuit</div>
<div class="option" data='{"value":"Illulik","state":"Greenland"}'>Illulik</div>
<div class="option" data='{"value":"Iluilek","state":"Greenland"}'>Iluilek</div>
<div class="option" data='{"value":"Ilulisat","state":"Greenland"}'>Ilulisat</div>
<div class="option" data='{"value":"Ilulissat","state":"Greenland"}'>Ilulissat</div>
<div class="option" data='{"value":"Innalik","state":"Greenland"}'>Innalik</div>
<div class="option" data='{"value":"Inugsuk","state":"Greenland"}'>Inugsuk</div>
<div class="option" data='{"value":"Inussuk","state":"Greenland"}'>Inussuk</div>
<div class="option" data='{"value":"Ippik","state":"Greenland"}'>Ippik</div>
<div class="option" data='{"value":"Isertoq","state":"Greenland"}'>Isertoq</div>
<div class="option" data='{"value":"Isortoq","state":"Greenland"}'>Isortoq</div>
<div class="option" data='{"value":"Isua","state":"Greenland"}'>Isua</div>
<div class="option" data='{"value":"Iterdlak","state":"Greenland"}'>Iterdlak</div>
<div class="option" data='{"value":"Iterlak","state":"Greenland"}'>Iterlak</div>
<div class="option" data='{"value":"Itilleq","state":"Greenland"}'>Itilleq</div>
<div class="option" data='{"value":"Itivdlek","state":"Greenland"}'>Itivdlek</div>
<div class="option" data='{"value":"Itivdleq","state":"Greenland"}'>Itivdleq</div>
<div class="option" data='{"value":"Itivnera","state":"Greenland"}'>Itivnera</div>
<div class="option" data='{"value":"Itseqqortoormiit","state":"Greenland"}'>Itseqqortoormiit</div>
<div class="option" data='{"value":"Ittaajimmiut","state":"Greenland"}'>Ittaajimmiut</div>
<div class="option" data='{"value":"Itterajivit","state":"Greenland"}'>Itterajivit</div>
<div class="option" data='{"value":"Ittoqqortoormiit","state":"Greenland"}'>Ittoqqortoormiit</div>
<div class="option" data='{"value":"Ittorisseq","state":"Greenland"}'>Ittorisseq</div>
<div class="option" data='{"value":"Ittumiit","state":"Greenland"}'>Ittumiit</div>
<div class="option" data='{"value":"Ivanganek","state":"Greenland"}'>Ivanganek</div>
<div class="option" data='{"value":"Iviggut","state":"Greenland"}'>Iviggut</div>
<div class="option" data='{"value":"Ivigtut","state":"Greenland"}'>Ivigtut</div>
<div class="option" data='{"value":"Ivittuut","state":"Greenland"}'>Ivittuut</div>
<div class="option" data='{"value":"Ivnalik","state":"Greenland"}'>Ivnalik</div>
<div class="option" data='{"value":"Ivnanganek","state":"Greenland"}'>Ivnanganek</div>
<div class="option" data='{"value":"Ivssorigseg","state":"Greenland"}'>Ivssorigseg</div>
<div class="option" data='{"value":"Ivssorigseq","state":"Greenland"}'>Ivssorigseq</div>
<div class="option" data='{"value":"Ivtorigteq","state":"Greenland"}'>Ivtorigteq</div>
<div class="option" data='{"value":"Jakobshavn","state":"Greenland"}'>Jakobshavn</div>
<div class="option" data='{"value":"Julian Haab","state":"Greenland"}'>Julian Haab</div>
<div class="option" data='{"value":"Julianehaab","state":"Greenland"}'>Julianehaab</div>
<div class="option" data='{"value":"Julianehab","state":"Greenland"}'>Julianehab</div>
<div class="option" data='{"value":"Kaersut","state":"Greenland"}'>Kaersut</div>
<div class="option" data='{"value":"Kagsiarsuk","state":"Greenland"}'>Kagsiarsuk</div>
<div class="option" data='{"value":"Kagsimiut","state":"Greenland"}'>Kagsimiut</div>
<div class="option" data='{"value":"Kagssiarssuk","state":"Greenland"}'>Kagssiarssuk</div>
<div class="option" data='{"value":"Kagssigssalik","state":"Greenland"}'>Kagssigssalik</div>
<div class="option" data='{"value":"Kakortak","state":"Greenland"}'>Kakortak</div>
<div class="option" data='{"value":"Kakortok","state":"Greenland"}'>Kakortok</div>
<div class="option" data='{"value":"Kalaallit Nunaat","state":"Greenland"}'>Kalaallit Nunaat</div>
<div class="option" data='{"value":"Kanak","state":"Greenland"}'>Kanak</div>
<div class="option" data='{"value":"Kanaq","state":"Greenland"}'>Kanaq</div>
<div class="option" data='{"value":"Kangaamiut","state":"Greenland"}'>Kangaamiut</div>
<div class="option" data='{"value":"Kangaarsuk","state":"Greenland"}'>Kangaarsuk</div>
<div class="option" data='{"value":"Kangaatsiaq","state":"Greenland"}'>Kangaatsiaq</div>
<div class="option" data='{"value":"Kangamiut","state":"Greenland"}'>Kangamiut</div>
<div class="option" data='{"value":"Kanganiut","state":"Greenland"}'>Kanganiut</div>
<div class="option" data='{"value":"Kangarssuk","state":"Greenland"}'>Kangarssuk</div>
<div class="option" data='{"value":"Kangatok","state":"Greenland"}'>Kangatok</div>
<div class="option" data='{"value":"Kangatsiak","state":"Greenland"}'>Kangatsiak</div>
<div class="option" data='{"value":"Kangatsiaq","state":"Greenland"}'>Kangatsiaq</div>
<div class="option" data='{"value":"Kangek","state":"Greenland"}'>Kangek</div>
<div class="option" data='{"value":"Kangeq","state":"Greenland"}'>Kangeq</div>
<div class="option" data='{"value":"Kangerdluarssoruseq","state":"Greenland"}'>Kangerdluarssoruseq</div>
<div class="option" data='{"value":"Kangerdluarssuk","state":"Greenland"}'>Kangerdluarssuk</div>
<div class="option" data='{"value":"Kangerdlugssuaq","state":"Greenland"}'>Kangerdlugssuaq</div>
<div class="option" data='{"value":"Kangerluarsoruseq","state":"Greenland"}'>Kangerluarsoruseq</div>
<div class="option" data='{"value":"Kangerluarsuk","state":"Greenland"}'>Kangerluarsuk</div>
<div class="option" data='{"value":"Kangerlussuaq","state":"Greenland"}'>Kangerlussuaq</div>
<div class="option" data='{"value":"Kangerssuatsiaq","state":"Greenland"}'>Kangerssuatsiaq</div>
<div class="option" data='{"value":"Kangersuatsiak","state":"Greenland"}'>Kangersuatsiak</div>
<div class="option" data='{"value":"Kangersuatsiaq","state":"Greenland"}'>Kangersuatsiaq</div>
<div class="option" data='{"value":"Kangerup Nua","state":"Greenland"}'>Kangerup Nua</div>
<div class="option" data='{"value":"Kangidlermiut","state":"Greenland"}'>Kangidlermiut</div>
<div class="option" data='{"value":"Kangigdlermiut","state":"Greenland"}'>Kangigdlermiut</div>
<div class="option" data='{"value":"Kangikasik","state":"Greenland"}'>Kangikasik</div>
<div class="option" data='{"value":"Kangikitsoq","state":"Greenland"}'>Kangikitsoq</div>
<div class="option" data='{"value":"Kangilineq","state":"Greenland"}'>Kangilineq</div>
<div class="option" data='{"value":"Kanissut","state":"Greenland"}'>Kanissut</div>
<div class="option" data='{"value":"Kanisut","state":"Greenland"}'>Kanisut</div>
<div class="option" data='{"value":"Kap Dan","state":"Greenland"}'>Kap Dan</div>
<div class="option" data='{"value":"Kap Hope","state":"Greenland"}'>Kap Hope</div>
<div class="option" data='{"value":"Kap Tobin","state":"Greenland"}'>Kap Tobin</div>
<div class="option" data='{"value":"Kapingasok","state":"Greenland"}'>Kapingasok</div>
<div class="option" data='{"value":"Kapisigdlit","state":"Greenland"}'>Kapisigdlit</div>
<div class="option" data='{"value":"Kapisilik","state":"Greenland"}'>Kapisilik</div>
<div class="option" data='{"value":"Kapisillit","state":"Greenland"}'>Kapisillit</div>
<div class="option" data='{"value":"Karna","state":"Greenland"}'>Karna</div>
<div class="option" data='{"value":"Kasigianguit","state":"Greenland"}'>Kasigianguit</div>
<div class="option" data='{"value":"Kekertak","state":"Greenland"}'>Kekertak</div>
<div class="option" data='{"value":"Kekertarssuak","state":"Greenland"}'>Kekertarssuak</div>
<div class="option" data='{"value":"Kekertarsuak","state":"Greenland"}'>Kekertarsuak</div>
<div class="option" data='{"value":"Kekertarsuatsiak","state":"Greenland"}'>Kekertarsuatsiak</div>
<div class="option" data='{"value":"Kekertat","state":"Greenland"}'>Kekertat</div>
<div class="option" data='{"value":"Kekertgarsuatsiak","state":"Greenland"}'>Kekertgarsuatsiak</div>
<div class="option" data='{"value":"Kiatak","state":"Greenland"}'>Kiatak</div>
<div class="option" data='{"value":"Kigdlussat","state":"Greenland"}'>Kigdlussat</div>
<div class="option" data='{"value":"Kigtorsak","state":"Greenland"}'>Kigtorsak</div>
<div class="option" data='{"value":"Kigtorsaq","state":"Greenland"}'>Kigtorsaq</div>
<div class="option" data='{"value":"Kiinnarissoq","state":"Greenland"}'>Kiinnarissoq</div>
<div class="option" data='{"value":"Kiirigsoq","state":"Greenland"}'>Kiirigsoq</div>
<div class="option" data='{"value":"Killiat","state":"Greenland"}'>Killiat</div>
<div class="option" data='{"value":"Kinalik","state":"Greenland"}'>Kinalik</div>
<div class="option" data='{"value":"Kitdli","state":"Greenland"}'>Kitdli</div>
<div class="option" data='{"value":"Kitdliat","state":"Greenland"}'>Kitdliat</div>
<div class="option" data='{"value":"Kitdlusat","state":"Greenland"}'>Kitdlusat</div>
<div class="option" data='{"value":"Kitorsak","state":"Greenland"}'>Kitorsak</div>
<div class="option" data='{"value":"Kitsigsuarssuit","state":"Greenland"}'>Kitsigsuarssuit</div>
<div class="option" data='{"value":"Kittorsaq","state":"Greenland"}'>Kittorsaq</div>
<div class="option" data='{"value":"Klatak","state":"Greenland"}'>Klatak</div>
<div class="option" data='{"value":"Kornok","state":"Greenland"}'>Kornok</div>
<div class="option" data='{"value":"Kraulshavn","state":"Greenland"}'>Kraulshavn</div>
<div class="option" data='{"value":"Kronprinsen Ejland","state":"Greenland"}'>Kronprinsen Ejland</div>
<div class="option" data='{"value":"Kuanit","state":"Greenland"}'>Kuanit</div>
<div class="option" data='{"value":"Kugkat","state":"Greenland"}'>Kugkat</div>
<div class="option" data='{"value":"Kugsiarsuk","state":"Greenland"}'>Kugsiarsuk</div>
<div class="option" data='{"value":"Kuinassuk","state":"Greenland"}'>Kuinassuk</div>
<div class="option" data='{"value":"Kuk","state":"Greenland"}'>Kuk</div>
<div class="option" data='{"value":"Kullorsuaq","state":"Greenland"}'>Kullorsuaq</div>
<div class="option" data='{"value":"Kulusuk","state":"Greenland"}'>Kulusuk</div>
<div class="option" data='{"value":"Kungmiut","state":"Greenland"}'>Kungmiut</div>
<div class="option" data='{"value":"Kutdligssat","state":"Greenland"}'>Kutdligssat</div>
<div class="option" data='{"value":"Kutdlisat","state":"Greenland"}'>Kutdlisat</div>
<div class="option" data='{"value":"Kuuk","state":"Greenland"}'>Kuuk</div>
<div class="option" data='{"value":"Kuummiit","state":"Greenland"}'>Kuummiit</div>
<div class="option" data='{"value":"Kuummiut","state":"Greenland"}'>Kuummiut</div>
<div class="option" data='{"value":"Kuvdlorssuak","state":"Greenland"}'>Kuvdlorssuak</div>
<div class="option" data='{"value":"Lichtenau","state":"Greenland"}'>Lichtenau</div>
<div class="option" data='{"value":"Maarmorilik","state":"Greenland"}'>Maarmorilik</div>
<div class="option" data='{"value":"Maitsoq","state":"Greenland"}'>Maitsoq</div>
<div class="option" data='{"value":"Majestic Bay Settlement","state":"Greenland"}'>Majestic Bay Settlement</div>
<div class="option" data='{"value":"Manermiut","state":"Greenland"}'>Manermiut</div>
<div class="option" data='{"value":"Maniitsoq","state":"Greenland"}'>Maniitsoq</div>
<div class="option" data='{"value":"Manitsok","state":"Greenland"}'>Manitsok</div>
<div class="option" data='{"value":"Manitsoq","state":"Greenland"}'>Manitsoq</div>
<div class="option" data='{"value":"Manussak","state":"Greenland"}'>Manussak</div>
<div class="option" data='{"value":"Manussaq","state":"Greenland"}'>Manussaq</div>
<div class="option" data='{"value":"Manuusaq","state":"Greenland"}'>Manuusaq</div>
<div class="option" data='{"value":"Marmorbrud","state":"Greenland"}'>Marmorbrud</div>
<div class="option" data='{"value":"Marmorilik","state":"Greenland"}'>Marmorilik</div>
<div class="option" data='{"value":"Marraat","state":"Greenland"}'>Marraat</div>
<div class="option" data='{"value":"Marrait","state":"Greenland"}'>Marrait</div>
<div class="option" data='{"value":"Moriusaq","state":"Greenland"}'>Moriusaq</div>
<div class="option" data='{"value":"Moriussaq","state":"Greenland"}'>Moriussaq</div>
<div class="option" data='{"value":"Myggbukta","state":"Greenland"}'>Myggbukta</div>
<div class="option" data='{"value":"Naajat","state":"Greenland"}'>Naajat</div>
<div class="option" data='{"value":"Nanortalik","state":"Greenland"}'>Nanortalik</div>
<div class="option" data='{"value":"Napasok","state":"Greenland"}'>Napasok</div>
<div class="option" data='{"value":"Napasoq","state":"Greenland"}'>Napasoq</div>
<div class="option" data='{"value":"Napassok","state":"Greenland"}'>Napassok</div>
<div class="option" data='{"value":"Napassoq","state":"Greenland"}'>Napassoq</div>
<div class="option" data='{"value":"Napasuligssuaq","state":"Greenland"}'>Napasuligssuaq</div>
<div class="option" data='{"value":"Narsaarsuk","state":"Greenland"}'>Narsaarsuk</div>
<div class="option" data='{"value":"Narsak","state":"Greenland"}'>Narsak</div>
<div class="option" data='{"value":"Narsalik","state":"Greenland"}'>Narsalik</div>
<div class="option" data='{"value":"Narsaq","state":"Greenland"}'>Narsaq</div>
<div class="option" data='{"value":"Narsaq Kujalleq","state":"Greenland"}'>Narsaq Kujalleq</div>
<div class="option" data='{"value":"Narsarmiut","state":"Greenland"}'>Narsarmiut</div>
<div class="option" data='{"value":"Narsarssauk","state":"Greenland"}'>Narsarssauk</div>
<div class="option" data='{"value":"Narsarssuak","state":"Greenland"}'>Narsarssuak</div>
<div class="option" data='{"value":"Narsarssunk","state":"Greenland"}'>Narsarssunk</div>
<div class="option" data='{"value":"Narsarssurk","state":"Greenland"}'>Narsarssurk</div>
<div class="option" data='{"value":"Narsarsuak","state":"Greenland"}'>Narsarsuak</div>
<div class="option" data='{"value":"Narsarsuaq","state":"Greenland"}'>Narsarsuaq</div>
<div class="option" data='{"value":"Narsatsiaat","state":"Greenland"}'>Narsatsiaat</div>
<div class="option" data='{"value":"Narssak","state":"Greenland"}'>Narssak</div>
<div class="option" data='{"value":"Narssak kujatdlek","state":"Greenland"}'>Narssak kujatdlek</div>
<div class="option" data='{"value":"Narssalik","state":"Greenland"}'>Narssalik</div>
<div class="option" data='{"value":"Narssaq","state":"Greenland"}'>Narssaq</div>
<div class="option" data='{"value":"Narssarmiut","state":"Greenland"}'>Narssarmiut</div>
<div class="option" data='{"value":"Narssarssuaq","state":"Greenland"}'>Narssarssuaq</div>
<div class="option" data='{"value":"Narssarssuk","state":"Greenland"}'>Narssarssuk</div>
<div class="option" data='{"value":"Narssatsiait","state":"Greenland"}'>Narssatsiait</div>
<div class="option" data='{"value":"Narssurscuk","state":"Greenland"}'>Narssurscuk</div>
<div class="option" data='{"value":"Narssurssuk","state":"Greenland"}'>Narssurssuk</div>
<div class="option" data='{"value":"Natsilivik","state":"Greenland"}'>Natsilivik</div>
<div class="option" data='{"value":"Natsillvik","state":"Greenland"}'>Natsillvik</div>
<div class="option" data='{"value":"Naujat","state":"Greenland"}'>Naujat</div>
<div class="option" data='{"value":"Neke","state":"Greenland"}'>Neke</div>
<div class="option" data='{"value":"Neqe","state":"Greenland"}'>Neqe</div>
<div class="option" data='{"value":"Neqi","state":"Greenland"}'>Neqi</div>
<div class="option" data='{"value":"Neria","state":"Greenland"}'>Neria</div>
<div class="option" data='{"value":"Neriunaq","state":"Greenland"}'>Neriunaq</div>
<div class="option" data='{"value":"Niakornarsuk","state":"Greenland"}'>Niakornarsuk</div>
<div class="option" data='{"value":"Niakornat","state":"Greenland"}'>Niakornat</div>
<div class="option" data='{"value":"Niaqornaarsuk","state":"Greenland"}'>Niaqornaarsuk</div>
<div class="option" data='{"value":"Niaqornaq","state":"Greenland"}'>Niaqornaq</div>
<div class="option" data='{"value":"Niaqornarssuk","state":"Greenland"}'>Niaqornarssuk</div>
<div class="option" data='{"value":"Niaqornat","state":"Greenland"}'>Niaqornat</div>
<div class="option" data='{"value":"Nivaaq","state":"Greenland"}'>Nivaaq</div>
<div class="option" data='{"value":"Nivak","state":"Greenland"}'>Nivak</div>
<div class="option" data='{"value":"Nivaq","state":"Greenland"}'>Nivaq</div>
<div class="option" data='{"value":"Nord","state":"Greenland"}'>Nord</div>
<div class="option" data='{"value":"Nordre Huse","state":"Greenland"}'>Nordre Huse</div>
<div class="option" data='{"value":"North House","state":"Greenland"}'>North House</div>
<div class="option" data='{"value":"Nugak","state":"Greenland"}'>Nugak</div>
<div class="option" data='{"value":"Nugaq","state":"Greenland"}'>Nugaq</div>
<div class="option" data='{"value":"Nugatsiaq","state":"Greenland"}'>Nugatsiaq</div>
<div class="option" data='{"value":"Nugssuta","state":"Greenland"}'>Nugssuta</div>
<div class="option" data='{"value":"Nuk","state":"Greenland"}'>Nuk</div>
<div class="option" data='{"value":"Nuliarfik","state":"Greenland"}'>Nuliarfik</div>
<div class="option" data='{"value":"Nunat","state":"Greenland"}'>Nunat</div>
<div class="option" data='{"value":"Nunatame","state":"Greenland"}'>Nunatame</div>
<div class="option" data='{"value":"Nunatami","state":"Greenland"}'>Nunatami</div>
<div class="option" data='{"value":"Nunatarssuak","state":"Greenland"}'>Nunatarssuak</div>
<div class="option" data='{"value":"Nunatarssuaq","state":"Greenland"}'>Nunatarssuaq</div>
<div class="option" data='{"value":"Nunatarsuaq","state":"Greenland"}'>Nunatarsuaq</div>
<div class="option" data='{"value":"Nursak","state":"Greenland"}'>Nursak</div>
<div class="option" data='{"value":"Nussaq","state":"Greenland"}'>Nussaq</div>
<div class="option" data='{"value":"Nutat","state":"Greenland"}'>Nutat</div>
<div class="option" data='{"value":"Nuugaaq","state":"Greenland"}'>Nuugaaq</div>
<div class="option" data='{"value":"Nuugaatsiaq","state":"Greenland"}'>Nuugaatsiaq</div>
<div class="option" data='{"value":"Nuuk","state":"Greenland"}'>Nuuk</div>
<div class="option" data='{"value":"Nuussuaq","state":"Greenland"}'>Nuussuaq</div>
<div class="option" data='{"value":"Old Sukkertoppen","state":"Greenland"}'>Old Sukkertoppen</div>
<div class="option" data='{"value":"Oqaitsut","state":"Greenland"}'>Oqaitsut</div>
<div class="option" data='{"value":"Ostproven","state":"Greenland"}'>Ostproven</div>
<div class="option" data='{"value":"Paamiut","state":"Greenland"}'>Paamiut</div>
<div class="option" data='{"value":"Paarnakajiit","state":"Greenland"}'>Paarnakajiit</div>
<div class="option" data='{"value":"Pamiut","state":"Greenland"}'>Pamiut</div>
<div class="option" data='{"value":"Paornakajit","state":"Greenland"}'>Paornakajit</div>
<div class="option" data='{"value":"Perdlernerit","state":"Greenland"}'>Perdlernerit</div>
<div class="option" data='{"value":"Perlernerit","state":"Greenland"}'>Perlernerit</div>
<div class="option" data='{"value":"Pingorssuaq","state":"Greenland"}'>Pingorssuaq</div>
<div class="option" data='{"value":"Pingorsuaq","state":"Greenland"}'>Pingorsuaq</div>
<div class="option" data='{"value":"Pitorqeq","state":"Greenland"}'>Pitorqeq</div>
<div class="option" data='{"value":"Port of Lievely","state":"Greenland"}'>Port of Lievely</div>
<div class="option" data='{"value":"Portusooq","state":"Greenland"}'>Portusooq</div>
<div class="option" data='{"value":"Portusoq","state":"Greenland"}'>Portusoq</div>
<div class="option" data='{"value":"Prins Christian Sund","state":"Greenland"}'>Prins Christian Sund</div>
<div class="option" data='{"value":"Prins Christians Sund","state":"Greenland"}'>Prins Christians Sund</div>
<div class="option" data='{"value":"Prins Christianssund","state":"Greenland"}'>Prins Christianssund</div>
<div class="option" data='{"value":"Proven","state":"Greenland"}'>Proven</div>
<div class="option" data='{"value":"Qaanaaq","state":"Greenland"}'>Qaanaaq</div>
<div class="option" data='{"value":"Qaarsoq","state":"Greenland"}'>Qaarsoq</div>
<div class="option" data='{"value":"Qaarsut","state":"Greenland"}'>Qaarsut</div>
<div class="option" data='{"value":"Qaersut","state":"Greenland"}'>Qaersut</div>
<div class="option" data='{"value":"Qagdlimiut","state":"Greenland"}'>Qagdlimiut</div>
<div class="option" data='{"value":"Qagssiarssuk","state":"Greenland"}'>Qagssiarssuk</div>
<div class="option" data='{"value":"Qagssimiut","state":"Greenland"}'>Qagssimiut</div>
<div class="option" data='{"value":"Qagssissalik","state":"Greenland"}'>Qagssissalik</div>
<div class="option" data='{"value":"Qaksiarsuk","state":"Greenland"}'>Qaksiarsuk</div>
<div class="option" data='{"value":"Qallimiut","state":"Greenland"}'>Qallimiut</div>
<div class="option" data='{"value":"Qanaq","state":"Greenland"}'>Qanaq</div>
<div class="option" data='{"value":"Qangatait","state":"Greenland"}'>Qangatait</div>
<div class="option" data='{"value":"Qangattaat","state":"Greenland"}'>Qangattaat</div>
<div class="option" data='{"value":"Qaqortoq","state":"Greenland"}'>Qaqortoq</div>
<div class="option" data='{"value":"Qarajat","state":"Greenland"}'>Qarajat</div>
<div class="option" data='{"value":"Qasigianguit","state":"Greenland"}'>Qasigianguit</div>
<div class="option" data='{"value":"Qasigiannguit","state":"Greenland"}'>Qasigiannguit</div>
<div class="option" data='{"value":"Qassiarsuk","state":"Greenland"}'>Qassiarsuk</div>
<div class="option" data='{"value":"Qassimiut","state":"Greenland"}'>Qassimiut</div>
<div class="option" data='{"value":"Qassisalik","state":"Greenland"}'>Qassisalik</div>
<div class="option" data='{"value":"Qaugatait","state":"Greenland"}'>Qaugatait</div>
<div class="option" data='{"value":"Qeertartivatsiaq","state":"Greenland"}'>Qeertartivatsiaq</div>
<div class="option" data='{"value":"Qekertarssuaq","state":"Greenland"}'>Qekertarssuaq</div>
<div class="option" data='{"value":"Qeqertaarsuk","state":"Greenland"}'>Qeqertaarsuk</div>
<div class="option" data='{"value":"Qeqertaq","state":"Greenland"}'>Qeqertaq</div>
<div class="option" data='{"value":"Qeqertarssuaq","state":"Greenland"}'>Qeqertarssuaq</div>
<div class="option" data='{"value":"Qeqertarssuatsiait","state":"Greenland"}'>Qeqertarssuatsiait</div>
<div class="option" data='{"value":"Qeqertarssuatsiaq","state":"Greenland"}'>Qeqertarssuatsiaq</div>
<div class="option" data='{"value":"Qeqertarssuk","state":"Greenland"}'>Qeqertarssuk</div>
<div class="option" data='{"value":"Qeqertarssuq","state":"Greenland"}'>Qeqertarssuq</div>
<div class="option" data='{"value":"Qeqertarsuaq","state":"Greenland"}'>Qeqertarsuaq</div>
<div class="option" data='{"value":"Qeqertarsuatsiaat","state":"Greenland"}'>Qeqertarsuatsiaat</div>
<div class="option" data='{"value":"Qeqertarsuatsiaq","state":"Greenland"}'>Qeqertarsuatsiaq</div>
<div class="option" data='{"value":"Qeqertat","state":"Greenland"}'>Qeqertat</div>
<div class="option" data='{"value":"Qernertuarssivit","state":"Greenland"}'>Qernertuarssivit</div>
<div class="option" data='{"value":"Qernertuarssuit","state":"Greenland"}'>Qernertuarssuit</div>
<div class="option" data='{"value":"Qigdlussat","state":"Greenland"}'>Qigdlussat</div>
<div class="option" data='{"value":"Qingeq","state":"Greenland"}'>Qingeq</div>
<div class="option" data='{"value":"Qingua","state":"Greenland"}'>Qingua</div>
<div class="option" data='{"value":"Qipingasoq","state":"Greenland"}'>Qipingasoq</div>
<div class="option" data='{"value":"Qipingassoq","state":"Greenland"}'>Qipingassoq</div>
<div class="option" data='{"value":"Qiqdlussat","state":"Greenland"}'>Qiqdlussat</div>
<div class="option" data='{"value":"Qitdlorfik","state":"Greenland"}'>Qitdlorfik</div>
<div class="option" data='{"value":"Qooqqut","state":"Greenland"}'>Qooqqut</div>
<div class="option" data='{"value":"Qoornoq","state":"Greenland"}'>Qoornoq</div>
<div class="option" data='{"value":"Qornoq","state":"Greenland"}'>Qornoq</div>
<div class="option" data='{"value":"Qorqut","state":"Greenland"}'>Qorqut</div>
<div class="option" data='{"value":"Qubdligssat","state":"Greenland"}'>Qubdligssat</div>
<div class="option" data='{"value":"Quequrtat","state":"Greenland"}'>Quequrtat</div>
<div class="option" data='{"value":"Quinassuk","state":"Greenland"}'>Quinassuk</div>
<div class="option" data='{"value":"Quinissut","state":"Greenland"}'>Quinissut</div>
<div class="option" data='{"value":"Qullissat","state":"Greenland"}'>Qullissat</div>
<div class="option" data='{"value":"Qunnermiut","state":"Greenland"}'>Qunnermiut</div>
<div class="option" data='{"value":"Qutdligssarqat","state":"Greenland"}'>Qutdligssarqat</div>
<div class="option" data='{"value":"Qutdligssat","state":"Greenland"}'>Qutdligssat</div>
<div class="option" data='{"value":"Quvnermiut","state":"Greenland"}'>Quvnermiut</div>
<div class="option" data='{"value":"Ritenbenk","state":"Greenland"}'>Ritenbenk</div>
<div class="option" data='{"value":"Rodebay","state":"Greenland"}'>Rodebay</div>
<div class="option" data='{"value":"Saarloq","state":"Greenland"}'>Saarloq</div>
<div class="option" data='{"value":"Saattut","state":"Greenland"}'>Saattut</div>
<div class="option" data='{"value":"Sammisoq","state":"Greenland"}'>Sammisoq</div>
<div class="option" data='{"value":"Sangmisok","state":"Greenland"}'>Sangmisok</div>
<div class="option" data='{"value":"Sangmissok","state":"Greenland"}'>Sangmissok</div>
<div class="option" data='{"value":"Sangmissoq","state":"Greenland"}'>Sangmissoq</div>
<div class="option" data='{"value":"Saqqamiut","state":"Greenland"}'>Saqqamiut</div>
<div class="option" data='{"value":"Saqqaq","state":"Greenland"}'>Saqqaq</div>
<div class="option" data='{"value":"Saqqarliit","state":"Greenland"}'>Saqqarliit</div>
<div class="option" data='{"value":"Saqqisikuik","state":"Greenland"}'>Saqqisikuik</div>
<div class="option" data='{"value":"Sardlog","state":"Greenland"}'>Sardlog</div>
<div class="option" data='{"value":"Sardlok","state":"Greenland"}'>Sardlok</div>
<div class="option" data='{"value":"Sardloq","state":"Greenland"}'>Sardloq</div>
<div class="option" data='{"value":"Sarfanguak","state":"Greenland"}'>Sarfanguak</div>
<div class="option" data='{"value":"Sarfanguaq","state":"Greenland"}'>Sarfanguaq</div>
<div class="option" data='{"value":"Sarfannguaq","state":"Greenland"}'>Sarfannguaq</div>
<div class="option" data='{"value":"Sarfannguit","state":"Greenland"}'>Sarfannguit</div>
<div class="option" data='{"value":"Sarkak","state":"Greenland"}'>Sarkak</div>
<div class="option" data='{"value":"Sarkardlit","state":"Greenland"}'>Sarkardlit</div>
<div class="option" data='{"value":"Sarqamiut","state":"Greenland"}'>Sarqamiut</div>
<div class="option" data='{"value":"Sarqaq","state":"Greenland"}'>Sarqaq</div>
<div class="option" data='{"value":"Sarqardlit","state":"Greenland"}'>Sarqardlit</div>
<div class="option" data='{"value":"Satut","state":"Greenland"}'>Satut</div>
<div class="option" data='{"value":"Savigsivik","state":"Greenland"}'>Savigsivik</div>
<div class="option" data='{"value":"Savissivik","state":"Greenland"}'>Savissivik</div>
<div class="option" data='{"value":"Scoresby Sound","state":"Greenland"}'>Scoresby Sound</div>
<div class="option" data='{"value":"Scoresbysund","state":"Greenland"}'>Scoresbysund</div>
<div class="option" data='{"value":"Sermiarssuit","state":"Greenland"}'>Sermiarssuit</div>
<div class="option" data='{"value":"Sermiarsuit","state":"Greenland"}'>Sermiarsuit</div>
<div class="option" data='{"value":"Sermiarsut","state":"Greenland"}'>Sermiarsut</div>
<div class="option" data='{"value":"Sermiligaaq","state":"Greenland"}'>Sermiligaaq</div>
<div class="option" data='{"value":"Sermiligaq","state":"Greenland"}'>Sermiligaq</div>
<div class="option" data='{"value":"Sermilik","state":"Greenland"}'>Sermilik</div>
<div class="option" data='{"value":"Simiutaq","state":"Greenland"}'>Simiutaq</div>
<div class="option" data='{"value":"Siorapaluk","state":"Greenland"}'>Siorapaluk</div>
<div class="option" data='{"value":"Sioropaluk","state":"Greenland"}'>Sioropaluk</div>
<div class="option" data='{"value":"Sisimiut","state":"Greenland"}'>Sisimiut</div>
<div class="option" data='{"value":"Sivsingassoq","state":"Greenland"}'>Sivsingassoq</div>
<div class="option" data='{"value":"Sivtingaleq","state":"Greenland"}'>Sivtingaleq</div>
<div class="option" data='{"value":"Skansen","state":"Greenland"}'>Skansen</div>
<div class="option" data='{"value":"Skanske","state":"Greenland"}'>Skanske</div>
<div class="option" data='{"value":"Skjoldungen","state":"Greenland"}'>Skjoldungen</div>
<div class="option" data='{"value":"Sletten","state":"Greenland"}'>Sletten</div>
<div class="option" data='{"value":"Sondre Igaliko","state":"Greenland"}'>Sondre Igaliko</div>
<div class="option" data='{"value":"Sondre Igaliku","state":"Greenland"}'>Sondre Igaliku</div>
<div class="option" data='{"value":"Sondre Stromfjord","state":"Greenland"}'>Sondre Stromfjord</div>
<div class="option" data='{"value":"Sondre Upernavik","state":"Greenland"}'>Sondre Upernavik</div>
<div class="option" data='{"value":"Sondre Upernivik","state":"Greenland"}'>Sondre Upernivik</div>
<div class="option" data='{"value":"South Proven","state":"Greenland"}'>South Proven</div>
<div class="option" data='{"value":"South Upernavik","state":"Greenland"}'>South Upernavik</div>
<div class="option" data='{"value":"Sowallick Point","state":"Greenland"}'>Sowallick Point</div>
<div class="option" data='{"value":"Sujunerajik","state":"Greenland"}'>Sujunerajik</div>
<div class="option" data='{"value":"Sukkertoppen","state":"Greenland"}'>Sukkertoppen</div>
<div class="option" data='{"value":"Summer Place","state":"Greenland"}'>Summer Place</div>
<div class="option" data='{"value":"Sydproven","state":"Greenland"}'>Sydproven</div>
<div class="option" data='{"value":"Tartanaq","state":"Greenland"}'>Tartanaq</div>
<div class="option" data='{"value":"Tartunak","state":"Greenland"}'>Tartunak</div>
<div class="option" data='{"value":"Tartunaq","state":"Greenland"}'>Tartunaq</div>
<div class="option" data='{"value":"Tasiilaq","state":"Greenland"}'>Tasiilaq</div>
<div class="option" data='{"value":"Tasiusak","state":"Greenland"}'>Tasiusak</div>
<div class="option" data='{"value":"Tasiusaq","state":"Greenland"}'>Tasiusaq</div>
<div class="option" data='{"value":"Tasiussak","state":"Greenland"}'>Tasiussak</div>
<div class="option" data='{"value":"Tasiussaq","state":"Greenland"}'>Tasiussaq</div>
<div class="option" data='{"value":"Taupait","state":"Greenland"}'>Taupait</div>
<div class="option" data='{"value":"Thule","state":"Greenland"}'>Thule</div>
<div class="option" data='{"value":"Tikeraasaq","state":"Greenland"}'>Tikeraasaq</div>
<div class="option" data='{"value":"Tikeraussaq","state":"Greenland"}'>Tikeraussaq</div>
<div class="option" data='{"value":"Timerdlit","state":"Greenland"}'>Timerdlit</div>
<div class="option" data='{"value":"Timerliit","state":"Greenland"}'>Timerliit</div>
<div class="option" data='{"value":"Timmiarmiut","state":"Greenland"}'>Timmiarmiut</div>
<div class="option" data='{"value":"Tingmiarmiut","state":"Greenland"}'>Tingmiarmiut</div>
<div class="option" data='{"value":"Tiniteqilaaq","state":"Greenland"}'>Tiniteqilaaq</div>
<div class="option" data='{"value":"Tiniteqilaarmiit","state":"Greenland"}'>Tiniteqilaarmiit</div>
<div class="option" data='{"value":"Tiniteqilaq","state":"Greenland"}'>Tiniteqilaq</div>
<div class="option" data='{"value":"Tiniteqilarmit","state":"Greenland"}'>Tiniteqilarmit</div>
<div class="option" data='{"value":"Tinuteqissaq","state":"Greenland"}'>Tinuteqissaq</div>
<div class="option" data='{"value":"Toqqusaq","state":"Greenland"}'>Toqqusaq</div>
<div class="option" data='{"value":"Tovqussaq","state":"Greenland"}'>Tovqussaq</div>
<div class="option" data='{"value":"Trigtut","state":"Greenland"}'>Trigtut</div>
<div class="option" data='{"value":"Tuapaat","state":"Greenland"}'>Tuapaat</div>
<div class="option" data='{"value":"Tuapail","state":"Greenland"}'>Tuapail</div>
<div class="option" data='{"value":"Tuapait","state":"Greenland"}'>Tuapait</div>
<div class="option" data='{"value":"Tugssaq","state":"Greenland"}'>Tugssaq</div>
<div class="option" data='{"value":"Tunungassoq","state":"Greenland"}'>Tunungassoq</div>
<div class="option" data='{"value":"Tununngasoq","state":"Greenland"}'>Tununngasoq</div>
<div class="option" data='{"value":"Tussaaq","state":"Greenland"}'>Tussaaq</div>
<div class="option" data='{"value":"Tuvgssaq","state":"Greenland"}'>Tuvgssaq</div>
<div class="option" data='{"value":"Tuvssaq","state":"Greenland"}'>Tuvssaq</div>
<div class="option" data='{"value":"Ujaraat","state":"Greenland"}'>Ujaraat</div>
<div class="option" data='{"value":"Ujarait","state":"Greenland"}'>Ujarait</div>
<div class="option" data='{"value":"Ujarasugssuk","state":"Greenland"}'>Ujarasugssuk</div>
<div class="option" data='{"value":"Ujarasussuk","state":"Greenland"}'>Ujarasussuk</div>
<div class="option" data='{"value":"Ukiverajik","state":"Greenland"}'>Ukiverajik</div>
<div class="option" data='{"value":"Ukkusissat","state":"Greenland"}'>Ukkusissat</div>
<div class="option" data='{"value":"Ulugssat","state":"Greenland"}'>Ulugssat</div>
<div class="option" data='{"value":"Ulussat","state":"Greenland"}'>Ulussat</div>
<div class="option" data='{"value":"Umanak","state":"Greenland"}'>Umanak</div>
<div class="option" data='{"value":"Umanaq","state":"Greenland"}'>Umanaq</div>
<div class="option" data='{"value":"Umanarssuk","state":"Greenland"}'>Umanarssuk</div>
<div class="option" data='{"value":"Umanatsiak","state":"Greenland"}'>Umanatsiak</div>
<div class="option" data='{"value":"Umanatsiaq","state":"Greenland"}'>Umanatsiaq</div>
<div class="option" data='{"value":"Umiagtuartivit","state":"Greenland"}'>Umiagtuartivit</div>
<div class="option" data='{"value":"Umiartorfik","state":"Greenland"}'>Umiartorfik</div>
<div class="option" data='{"value":"Umiattuartivit","state":"Greenland"}'>Umiattuartivit</div>
<div class="option" data='{"value":"Umigtuarajit","state":"Greenland"}'>Umigtuarajit</div>
<div class="option" data='{"value":"Umigtuarjit","state":"Greenland"}'>Umigtuarjit</div>
<div class="option" data='{"value":"Umigtuarssuit","state":"Greenland"}'>Umigtuarssuit</div>
<div class="option" data='{"value":"Umigtuartivit","state":"Greenland"}'>Umigtuartivit</div>
<div class="option" data='{"value":"Unarteq","state":"Greenland"}'>Unarteq</div>
<div class="option" data='{"value":"Unartok","state":"Greenland"}'>Unartok</div>
<div class="option" data='{"value":"Unartoq","state":"Greenland"}'>Unartoq</div>
<div class="option" data='{"value":"Upernaviarssuk","state":"Greenland"}'>Upernaviarssuk</div>
<div class="option" data='{"value":"Upernaviarsuk","state":"Greenland"}'>Upernaviarsuk</div>
<div class="option" data='{"value":"Upernavigssuak","state":"Greenland"}'>Upernavigssuak</div>
<div class="option" data='{"value":"Upernavik","state":"Greenland"}'>Upernavik</div>
<div class="option" data='{"value":"Upernavik Kujalleq","state":"Greenland"}'>Upernavik Kujalleq</div>
<div class="option" data='{"value":"Upernavissuaq","state":"Greenland"}'>Upernavissuaq</div>
<div class="option" data='{"value":"Upernivik","state":"Greenland"}'>Upernivik</div>
<div class="option" data='{"value":"Utoqqarmiut","state":"Greenland"}'>Utoqqarmiut</div>
<div class="option" data='{"value":"Utorkarmiut","state":"Greenland"}'>Utorkarmiut</div>
<div class="option" data='{"value":"Utorqarmiut","state":"Greenland"}'>Utorqarmiut</div>
<div class="option" data='{"value":"Uummannaarsuk","state":"Greenland"}'>Uummannaarsuk</div>
<div class="option" data='{"value":"Uummannaq","state":"Greenland"}'>Uummannaq</div>
<div class="option" data='{"value":"Uummannatsiaq","state":"Greenland"}'>Uummannatsiaq</div>
<div class="option" data='{"value":"Uunarteq","state":"Greenland"}'>Uunarteq</div>
<div class="option" data='{"value":"Uunartoq","state":"Greenland"}'>Uunartoq</div>
<div class="option" data='{"value":"Uvdle","state":"Greenland"}'>Uvdle</div>
<div class="option" data='{"value":"Uvkusigsat","state":"Greenland"}'>Uvkusigsat</div>
<div class="option" data='{"value":"Uvkusigssat","state":"Greenland"}'>Uvkusigssat</div>
<div class="option" data='{"value":"Vandreblok","state":"Greenland"}'>Vandreblok</div>
<div class="option" data='{"value":"Vandreblokken","state":"Greenland"}'>Vandreblokken</div>
<div class="option" id="option_end" data='{"value":"Vester Ejland","state":"Greenland"}'>Vester Ejland</div>
<%
		}
	}
%>